

# This file was *autogenerated* from the file theta_padic.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_78 = Integer(78); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_900p0 = RealNumber('900.0'); _sage_const_120 = Integer(120); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11); _sage_const_8 = Integer(8)# cycle 19 / T3 Pure: theta >= ell+1 の領域（cycle 18 §6.1 が残した宿題）。
#
# 対応する証明本体: outputs/reports/cycle19_T3_theta_ge_ell_plus_1.md
# 直前の一次情報: outputs/reports/cycle18_T3_general_degenerate_tower.md（§4.2 命題 G、§4.3、§4.4、§6.1）
#
# 本スクリプトが照合するもの（証明は report 本体にある。ここは照合であって証明ではない）:
#
#   Step A  定理 J2（桁定理）: 0 <= m <= ell^L なら A_m mod ell は (a,b) mod ell^L だけの関数。
#           m = ell^L + 1 で**実際に破れる**ことを件数つきで示す（0 件で満足しない）。
#   Step B  定理 B'（Phi の 2 付値 Newton 多角形）: 最小点が一意なら
#           hat theta_M = min_m ( phi(ell^M) v_ell(A_m) + m )。円分体での実測と照合する。
#   Step C  定理 J4（ファイバー Newton 公式）: theta >= Lambda(r)、argmin が一意なら等号。
#           破れ（cancellation）の件数も出す。
#   Step D  定理 K（一般の予言アルゴリズム）: 母集団を全走査し、塔の値と照合する。
#           予言はフィットパラメータ 0 個なので全段 out-of-sample。
#   Step E  定理 J6 / 系 J5: theta が有限で判定条件が通るとき、型 II の閉形式。
#           とくに cycle 18 §4.4 の例（ell=3, (1,0),(0,1),(1,1)）を格上げする。
#   Step F  定理 J7: theta = oo の方向があると n ell^n 項が出る。閉形式を 2 例で照合。
#           および ell=2 トーラスが定理 J7 の仮定 j* <= ell-2 を破る**反例**であること。
#   Step G  敵対的レビュー。
#
# 実行: sage theta_padic.sage > theta_padic.out 2>&1

import sys, time
from itertools import combinations_with_replacement as cwr
sys.stdout.reconfigure(line_buffering=True)

load('_defs19.sage')

FAIL = _sage_const_0 
TRUNC = []
def check(cond, msg):
    global FAIL
    if not cond:
        FAIL += _sage_const_1 
        print("   *** FAIL:", msg)
    return cond

def bq(vs):
    return (_sage_const_1 , [(_sage_const_0 , _sage_const_0 , tuple(v)) for v in vs])

print("=" * _sage_const_78 )
print("cycle 19 / T3: theta >= ell+1 の領域（桁定理・ファイバー Newton 公式・閉形式）")
print("=" * _sage_const_78 )

# ==========================================================================
print()
print("=" * _sage_const_78 )
print("Step A: 定理 J2（桁定理）— Lucas を第 2・第 3 桁へ延長", el())
print("=" * _sage_const_78 )
print("""
  主張: 0 <= m <= ell^L なら A_m(a,b) mod ell は (a,b) mod ell^L だけの関数。
  照合: (a,b) を ell^L 倍のシフトで動かし、m <= ell^L で不変であることを全列挙で確認し、
        m = ell^L + 1 での破れの件数を数える（破れが正であることを要求する）。
""")

A_EX = [
    ('bq (1,0),(0,1) = torus', bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 )])),
    ('bq (1,0),(0,1),(1,1)', bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 ), (_sage_const_1 , _sage_const_1 )])),
    ('bq (1,0)x2,(0,1)', bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 )])),
    ('bq (1,0),(2,3),(1,1)', bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_2 , _sage_const_3 ), (_sage_const_1 , _sage_const_1 )])),
    ('2v 3-fold (0,0),(1,0),(0,1)', (_sage_const_2 , [(_sage_const_0 , _sage_const_1 , (_sage_const_0 , _sage_const_0 )), (_sage_const_0 , _sage_const_1 , (_sage_const_1 , _sage_const_0 )), (_sage_const_0 , _sage_const_1 , (_sage_const_0 , _sage_const_1 ))])),
]

def A_row(coeffs, a, b, mmax, ell):
    """A_m(a,b) mod ell (m = 0..mmax) を Phi の係数から一度に取る（速い）。"""
    f = Phi_ZZ(coeffs, a, b)
    return [ZZ(f[m]) % ell for m in range(mmax + _sage_const_1 )]

def polar_form_A2(coeffs, ell):
    """bar B((1,0),(0,1)) など、bar A_2 の極形式が非零かどうか（命題 J2'）。
       bar B(x,y) = sum bar c_pq (p x1 + q x2)(p y1 + q y2)。"""
    F = GF(ell)
    def B(x, y):
        return sum(F(c) * F(p * x[_sage_const_0 ] + q * x[_sage_const_1 ]) * F(p * y[_sage_const_0 ] + q * y[_sage_const_1 ])
                   for ((p, q), c) in coeffs.items())
    return any(B(x, y) != _sage_const_0 
               for x in [(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 ), (_sage_const_1 , _sage_const_1 )] for y in [(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 ), (_sage_const_1 , _sage_const_1 )])

for ell in [_sage_const_2 , _sage_const_3 , _sage_const_5 ]:
    for L in [_sage_const_1 , _sage_const_2 ]:
        if ell**L > _sage_const_9 :
            continue
        nstable = nbreak_at = nbreak_next = _sage_const_0 
        polar_nz = {}
        for (name, (m, edges)) in A_EX:
            D = detL(m, edges)
            mu = mu_content(D, ell)
            coeffs = cleared_coeffs(E_of(D, ell, mu))
            polar_nz[name] = polar_form_A2(coeffs, ell)
            q = ell**L
            nb_here = _sage_const_0 
            for a in range(q):
                for b in range(q):
                    r0 = A_row(coeffs, a, b, q + _sage_const_1 , ell)
                    for u in range(ell):
                        for v in range(ell):
                            r1 = A_row(coeffs, a + q * u, b + q * v, q + _sage_const_1 , ell)
                            for mm in range(q + _sage_const_1 ):
                                if r0[mm] == r1[mm]:
                                    nstable += _sage_const_1 
                                else:
                                    nbreak_at += _sage_const_1 
                            if r0[q + _sage_const_1 ] != r1[q + _sage_const_1 ]:
                                nbreak_next += _sage_const_1 ; nb_here += _sage_const_1 
            # 命題 J2': 破れる <=> bar A_2 の極形式が非零
            check((nb_here > _sage_const_0 ) == polar_nz[name],
                  "ell=%d L=%d %s: 破れ %d 件 だが極形式 非零=%s（命題 J2' と矛盾）"
                  % (ell, L, name, nb_here, polar_nz[name]))
        print("  ell=%d L=%d : m <= ell^L の照合 %d 件、うち破れ %d 件 / m = ell^L+1 の破れ %d 件"
              % (ell, L, nstable + nbreak_at, nbreak_at, nbreak_next))
        print("           bar A_2 の極形式が非零な例: %s"
              % {k: v for (k, v) in polar_nz.items()})
        check(nbreak_at == _sage_const_0 , "ell=%d L=%d: m <= ell^L で digit 安定性が破れた" % (ell, L))
        if any(polar_nz.values()):
            check(nbreak_next > _sage_const_0 , "ell=%d L=%d: 極形式が非零な例があるのに m = ell^L+1 の破れが 0 件"
                                   "（検証が破れを検出できていない）" % (ell, L))
        else:
            print("           （この ell では全例で極形式が消えるため破れ 0 件が正しい。命題 J2'）")

# L = 2, 3 の全列挙は重いので (a,b) を間引いて回す（間引きの事実を明示する）。
# step は ell と互いに素に取る。step が ell の倍数だと標本が全て (a,b) = (0,0) mod ell に
# なってしまい、破れを与える双一次形式 bar B((a,b),(u,v)) が恒等的に消えて検出できない
# （最初 step = ell と書いて破れ 0 件になり、この落とし穴に気づいた）。
for (ell, L, step) in [(_sage_const_5 , _sage_const_2 , _sage_const_4 ), (_sage_const_3 , _sage_const_3 , _sage_const_4 )]:
    assert gcd(step, ell) == _sage_const_1 
    q = ell**L
    nstable = nbreak_at = nbreak_next = _sage_const_0 
    npair = _sage_const_0 
    for (name, (m, edges)) in A_EX:
        D = detL(m, edges); mu = mu_content(D, ell)
        coeffs = cleared_coeffs(E_of(D, ell, mu))
        for a in range(_sage_const_0 , q, step):
            for b in range(_sage_const_0 , q, step):
                r0 = A_row(coeffs, a, b, q + _sage_const_1 , ell)
                npair += _sage_const_1 
                for (u, v) in [(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 )]:
                    r1 = A_row(coeffs, a + q * u, b + q * v, q + _sage_const_1 , ell)
                    for mm in range(q + _sage_const_1 ):
                        if r0[mm] == r1[mm]:
                            nstable += _sage_const_1 
                        else:
                            nbreak_at += _sage_const_1 
                    if r0[q + _sage_const_1 ] != r1[q + _sage_const_1 ]:
                        nbreak_next += _sage_const_1 
    print("  ell=%d L=%d（間引き step=%d, (a,b) %d 組, シフト (1,0),(0,1)）: "
          "m <= ell^L の照合 %d 件、うち破れ %d 件 / m = ell^L+1 の破れ %d 件"
          % (ell, L, step, npair, nstable + nbreak_at, nbreak_at, nbreak_next))
    check(nbreak_at == _sage_const_0 , "ell=%d L=%d: m <= ell^L で digit 安定性が破れた" % (ell, L))
    check(nbreak_next > _sage_const_0 , "ell=%d L=%d: m = ell^L+1 の破れが 0 件" % (ell, L))

# ==========================================================================
print()
print("=" * _sage_const_78 )
print("Step B: 定理 B'（2 付値 Newton 多角形）を円分体での実測と照合", el())
print("=" * _sage_const_78 )
print("""
  主張: min_m ( phi(ell^M) v_ell(A_m) + m ) が一意なら、それが hat theta_M = phi(ell^M) v_ell(E)。
  照合: Q(zeta_{ell^M}) の ell の上の素点での付値を独立に計算し、突き合わせる。
""")

B_CASES = [(_sage_const_2 , bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 )]), _sage_const_4 ),
           (_sage_const_3 , bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 ), (_sage_const_1 , _sage_const_1 )]), _sage_const_3 ),
           (_sage_const_3 , bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 )]), _sage_const_3 ),
           (_sage_const_5 , bq([(_sage_const_1 , _sage_const_0 )] * _sage_const_4  + [(_sage_const_0 , _sage_const_1 )]), _sage_const_2 )]

for (ell, (m, edges), Mmax) in B_CASES:
    D = detL(m, edges); mu = mu_content(D, ell)
    coeffs = cleared_coeffs(E_of(D, ell, mu))
    print("  --- ell=%d %s" % (ell, edges))
    for M in range(_sage_const_1 , Mmax + _sage_const_1 ):
        nuniq = ntie = nagree = _sage_const_0 
        for (a, b) in P1_reps(ell, M):
            (v, uniq, arg) = hat_theta_predicted(coeffs, ell, M, a, b)
            meas = delta_measured(D, ell, mu, M, a, b)
            if uniq:
                nuniq += _sage_const_1 
                if meas is not None and QQ(meas) == QQ(v):
                    nagree += _sage_const_1 
                else:
                    check(False, "ell=%d M=%d (a,b)=(%s,%s): 予言 %s != 実測 %s"
                          % (ell, M, a, b, v, meas))
            else:
                ntie += _sage_const_1 
                # 一意でないときは予言は下界にすぎない。実測が下界以上であることだけ確認する。
                check(meas is None or QQ(meas) >= QQ(v),
                      "ell=%d M=%d (a,b)=(%s,%s): 実測 %s が下界 %s を下回った"
                      % (ell, M, a, b, meas, v))
        print("      M=%d: 点 %d 個、最小点が一意 %d 個（うち実測一致 %d 個）、tie %d 個"
              % (M, len(P1_reps(ell, M)), nuniq, nagree, ntie))

# ==========================================================================
print()
print("=" * _sage_const_78 )
print("Step C: 定理 J4（ファイバー Newton 公式）", el())
print("=" * _sage_const_78 )
print("""
  主張: 方向 P0 のファイバーの点 beta（v = v_ell(beta), r = v+1）で
        theta >= Lambda(r) = min_j ( e_j + j ell^r )、argmin が一意なら等号。
  照合: theta を Phi mod ell から直接計算し、Lambda と突き合わせる。
        argmin が一意でない（＝先頭係数が打ち消しうる）件数も出す。
""")

C_CASES = [(_sage_const_2 , bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 )]), _sage_const_3 ),
           (_sage_const_3 , bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 ), (_sage_const_1 , _sage_const_1 )]), _sage_const_3 ),
           (_sage_const_3 , bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 )]), _sage_const_3 ),
           (_sage_const_3 , bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_2 , _sage_const_3 ), (_sage_const_1 , _sage_const_1 )]), _sage_const_3 ),
           (_sage_const_5 , bq([(_sage_const_1 , _sage_const_0 )] * _sage_const_4  + [(_sage_const_0 , _sage_const_1 )]), _sage_const_2 ),
           (_sage_const_5 , bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 )]), _sage_const_2 )]

for (ell, (m, edges), rmax) in C_CASES:
    D = detL(m, edges); mu = mu_content(D, ell)
    coeffs = cleared_coeffs(E_of(D, ell, mu))
    print("  --- ell=%d %s" % (ell, edges))
    for (lab, es, e0, crit, jstar) in direction_data(coeffs, ell):
        eshow = [('oo' if e is oo else str(e)) for (e, lc) in es]
        print("      P0=%-6s e_j=%s  e_0=%s  判定条件=%s  j*=%s"
              % (lab, eshow, ('oo' if e0 is oo else e0), crit, jstar))
        (a0, b0) = ((ZZ(_sage_const_0 ), ZZ(_sage_const_1 )) if lab == '(0:1)'
                    else (ZZ(_sage_const_1 ), ZZ(lab[_sage_const_3 :-_sage_const_1 ])))
        pert = 'w' if a0 == _sage_const_1  else 'z'
        nlt = neq = _sage_const_0 
        for r in range(_sage_const_1 , rmax + _sage_const_1 ):
            (lam, arg) = Lambda_at(es, ell, r)
            for beta in range(ell**(rmax - _sage_const_1 )):
                if beta == _sage_const_0  or ZZ(beta).valuation(ell) != r - _sage_const_1 :
                    continue
                if pert == 'w':
                    (a, b) = (a0, b0 + ell * beta)
                else:
                    (a, b) = (ell * beta, b0)
                th = theta_of(coeffs, ell, a, b)
                check(th is oo or lam is oo or ZZ(th) >= ZZ(lam),
                      "ell=%d %s beta=%d: theta=%s < Lambda=%s" % (ell, lab, beta, th, lam))
                if len(arg) == _sage_const_1 :
                    if th is not oo and lam is not oo and ZZ(th) == ZZ(lam):
                        neq += _sage_const_1 
                    else:
                        check(False, "ell=%d %s beta=%d: argmin 一意なのに theta=%s != Lambda=%s"
                              % (ell, lab, beta, th, lam))
                else:
                    nlt += _sage_const_1 
        print("           argmin 一意で等号成立 %d 件 / argmin が一意でない（打ち消しうる）%d 件"
              % (neq, nlt))

# ==========================================================================
print()
print("=" * _sage_const_78 )
print("Step D: 定理 K（一般の予言アルゴリズム）を母集団で塔の値と照合", el())
print("=" * _sage_const_78 )

def gen_pop():
    out = []
    V = [(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 ), (_sage_const_1 , _sage_const_1 ), (_sage_const_1 , -_sage_const_1 ), (_sage_const_2 , _sage_const_1 ), (_sage_const_1 , _sage_const_2 ), (_sage_const_2 , _sage_const_3 ), (_sage_const_0 , _sage_const_2 ), (_sage_const_2 , _sage_const_0 )]
    for r in [_sage_const_2 , _sage_const_3 ]:
        for combo in cwr(range(len(V)), r):
            out.append(('bq ' + ' '.join(str(V[i]) for i in combo), _sage_const_1 ,
                        [(_sage_const_0 , _sage_const_0 , V[i]) for i in combo]))
    for r in [_sage_const_3 ]:
        for combo in cwr(range(len(V) + _sage_const_1 ), r):
            edges = [(_sage_const_0 , _sage_const_1 , ((_sage_const_0 , _sage_const_0 ) if i == len(V) else V[i])) for i in combo]
            out.append(('2v ' + ' '.join(('(0,0)' if i == len(V) else str(V[i]))
                                         for i in combo), _sage_const_2 , edges))
    return out

POP = gen_pop()
print("""
  母集団 %d 個（bouquet 2-3 ループ / 2 頂点 3 重辺、voltage 9 種）。
  各 (グラフ, ell) について、D の係数だけから ord_ell(kappa_n) を予言し、
  Matrix-Tree 定理による塔の値の独立計算と照合する（フィットパラメータ 0 個）。
""" % len(POP))

NMAX = {_sage_const_2 : _sage_const_4 , _sage_const_3 : _sage_const_3 , _sage_const_5 : _sage_const_2 , _sage_const_7 : _sage_const_1 }
BUDGET = _sage_const_900p0         # ell ごとの壁時計上限（秒）。超えたら残りは打ち切って全件記録する。
D_STATS = {}
for ell in [_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 ]:
    nchecked = nagree = nskip_tie = nskip_H = _sage_const_0 
    tie_examples = []
    tell = time.time()
    nleft = _sage_const_0 
    for (name, m, edges) in POP:
        if time.time() - tell > BUDGET:
            nleft += _sage_const_1 
            continue
        if not connected_by_lattice(m, edges, ell, ell):
            nskip_H += _sage_const_1 
            continue
        D = detL(m, edges)
        if D == _sage_const_0 :
            nskip_H += _sage_const_1 
            continue
        t0 = time.time()
        (preds, inv) = predicted_ord_K(m, edges, ell, NMAX[ell])
        if inv.get('dead'):
            nskip_H += _sage_const_1 
            continue
        okall = True
        for (n, pred, ok) in preds:
            if not ok:
                okall = False
                break
            N = ell**n
            kap = kappa_derived(m, edges, N, N)
            actual = ZZ(kap).valuation(ell)
            nchecked += _sage_const_1 
            if actual == pred:
                nagree += _sage_const_1 
            else:
                check(False, "ell=%d %s n=%d: 予言 %s != 実測 %s" % (ell, name, n, pred, actual))
        if not okall:
            nskip_tie += _sage_const_1 
            if len(tie_examples) < _sage_const_5 :
                tie_examples.append(name)
        if time.time() - t0 > _sage_const_120 :
            TRUNC.append("Step D ell=%d %s: %.0fs" % (ell, name, time.time() - t0))
    if nleft:
        TRUNC.append("Step D ell=%d: 壁時計 %.0fs 超過のため %d 個を打ち切り" % (ell, BUDGET, nleft))
    D_STATS[ell] = (nchecked, nagree, nskip_tie, nskip_H)
    print("  ell=%-2d : 照合 %d 段（一致 %d 段）/ tie があり予言を出さなかった塔 %d 個 / (H) 等で除外 %d 個 / 時間切れで未実施 %d 個"
          % (ell, nchecked, nagree, nskip_tie, nskip_H, nleft))
    if tie_examples:
        print("           tie の例: %s" % ', '.join(tie_examples))

# ==========================================================================
print()
print("=" * _sage_const_78 )
print("Step E: 定理 J6 / 系 J5 — theta 有限のときの閉形式（型 II）", el())
print("=" * _sage_const_78 )
print("""
  cycle 18 §4.4 は ell=3, bouquet (1,0),(0,1),(1,1) を「theta = 4 = ell+1 なのに
  M 依存しない」例として挙げ、**数値支持どまり**と明記していた。
  系 J5（Newton 判定条件）はこれを証明する。ここではその照合を行う。
""")

(m3, e3) = bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 ), (_sage_const_1 , _sage_const_1 )])
D3 = detL(m3, e3); mu3 = mu_content(D3, _sage_const_3 )
co3 = cleared_coeffs(E_of(D3, _sage_const_3 , mu3))
print("  k, H =", lowest_form(D3, _sage_const_3 ), " mu =", mu3)
for (lab, es, e0, crit, jstar) in direction_data(co3, _sage_const_3 ):
    print("      P0=%-6s e_j=%s 判定条件=%s" % (lab, [('oo' if e is oo else str(e)) for (e, lc) in es], crit))
    check(crit, "ell=3 (1,0),(0,1),(1,1): 方向 %s で判定条件が通らない" % lab)

print("  ファイバー上で theta が定数であることの全列挙照合（レベル 4 まで）:")
for M in range(_sage_const_1 , _sage_const_5 ):
    vals = {}
    for (a, b) in P1_reps(_sage_const_3 , M):
        P0 = dir_label((ZZ(_sage_const_1 ), ZZ(b) % _sage_const_3 )) if a % _sage_const_3  != _sage_const_0  else '(0:1)'
        th = theta_of(co3, _sage_const_3 , a, b)
        vals.setdefault(P0, set()).add(th)
    print("      M=%d : %s" % (M, {k: sorted(v) for (k, v) in sorted(vals.items())}))
    for (k, v) in vals.items():
        check(len(v) == _sage_const_1 , "ell=3 M=%d 方向 %s で theta が一定でない: %s" % (M, k, v))

print("  Theta_{M'} と閉形式（Theta = 10, Sigma_n = 5(3^n - 1)）:")
for M in range(_sage_const_1 , _sage_const_5 ):
    (th, ok) = Theta_level(co3, _sage_const_3 , M)
    print("      Theta_%d = %s（定理 B' の一意性 %s） 予言 10*3^{M-1} = %s"
          % (M, th, ok, _sage_const_10  * _sage_const_3 **(M - _sage_const_1 )))
    check(th == _sage_const_10  * _sage_const_3 **(M - _sage_const_1 ), "ell=3: Theta_%d が 10*3^{M-1} と違う" % M)
print("  塔の値との照合（ord_3(kappa_n) = 5(3^n - 1) - 2n）:")
for n in range(_sage_const_0 , _sage_const_4 ):
    N = _sage_const_3 **n
    actual = ZZ(kappa_derived(m3, e3, N, N)).valuation(_sage_const_3 )
    pred = _sage_const_5  * (_sage_const_3 **n - _sage_const_1 ) - _sage_const_2  * n
    print("      n=%d 実測 %d 予言 %d %s" % (n, actual, pred, "OK" if actual == pred else "MISMATCH"))
    check(actual == pred, "ell=3 (1,0),(0,1),(1,1) n=%d" % n)

# ==========================================================================
print()
print("=" * _sage_const_78 )
print("Step F: 定理 J7 — theta = oo の方向があると n ell^n 項が出る", el())
print("=" * _sage_const_78 )
print("""
  閉形式（本 report §5.3 で導出、フィットパラメータ 0 個）:
      定理 J8: ell 奇素数、bouquet に (1,0) を ell-1 本、(0,1) を 1 本置くと
               ord_ell(kappa_n) = 2 n ell^n + 2 ell^n - 2   （全ての n >= 0）
  いずれも theta = oo の方向が 2 本、j* = 1 なので b = sum j* = 2。
  ell = 3, 5, 7, 11 で照合する（到達段数は ell^{2n} 頂点の行列式の壁で決まる）。
""")

F_CASES = [(ell, bq([(_sage_const_1 , _sage_const_0 )] * (ell - _sage_const_1 ) + [(_sage_const_0 , _sage_const_1 )]), nmax)
           for (ell, nmax) in [(_sage_const_3 , _sage_const_3 ), (_sage_const_5 , _sage_const_2 ), (_sage_const_7 , _sage_const_1 ), (_sage_const_11 , _sage_const_1 )]]
print("""
  【重要な注意（本サイクルで踏んだ落とし穴）】
  theta = oo の点は P^1(F_ell) の方向ではなく **P^1(Z_ell) の点**である。
  方向 (1:ell-1) の mod ell 代表 (1, ell-1) と、Z_ell の点 (1, -1) は別の点であり、
  前者では theta は有限（下の e_0 を見よ）。したがって基点は -1 側に取らねばならない。
""")

for (ell, (m, edges), nmax) in F_CASES:
    pred = (lambda L: (lambda n: _sage_const_2  * n * L**n + _sage_const_2  * L**n - _sage_const_2 ))(ell)
    D = detL(m, edges); mu = mu_content(D, ell)
    coeffs = cleared_coeffs(E_of(D, ell, mu))
    print("  --- ell=%d bouquet (1,0)x%d, (0,1)   [定理 J8 の族]" % (ell, ell - _sage_const_1 ))
    print("      k,H = %s  mu = %d" % (lowest_form(D, ell), mu))
    # 整数代表での方向データ（落とし穴の実演）
    for (lab, es, e0, crit, jstar) in direction_data(coeffs, ell):
        print("      整数代表 P0=%-6s e_j=%s e_0=%s"
              % (lab, [('oo' if e is oo else str(e)) for (e, lc) in es],
                 ('oo' if e0 is oo else e0)))
    # Z_ell の点として S_oo = {(1:1), (1:-1)} を確かめ、そこで j* を取る
    b_pred = _sage_const_0 ; S_inf = []
    for b0 in [_sage_const_1 , -_sage_const_1 ]:
        th = theta_signed(coeffs, ell, _sage_const_1 , b0)
        es = psi_data(coeffs, ell, _sage_const_1 , b0, 'w')
        jstar = min([j for (j, (e, lc)) in enumerate(es) if j >= _sage_const_1  and e is not oo])
        print("      Z_ell 点 (1:%2d): theta=%s  e_j=%s  j*=%s"
              % (b0, th, [('oo' if e is oo else str(e)) for (e, lc) in es], jstar))
        check(th is oo, "ell=%d: (1:%d) で theta が oo でない" % (ell, b0))
        S_inf.append((b0, jstar)); b_pred += jstar
    # S_oo が本当にこの 2 点だけであることの照合（report §5.3 で証明済み）:
    # theta(a,b) = oo <=> (1+x)^a = (1+x)^b または (1+x)^{a+b} = 1
    nother = _sage_const_0 
    for b0 in range(-_sage_const_2  * ell, _sage_const_2  * ell + _sage_const_1 ):
        if b0 in (_sage_const_1 , -_sage_const_1 ):
            continue
        if theta_signed(coeffs, ell, _sage_const_1 , b0) is oo:
            nother += _sage_const_1 
    check(nother == _sage_const_0 , "ell=%d: (1:1),(1:-1) 以外に theta=oo の整数点が %d 個" % (ell, nother))
    print("      S_oo = %s（|b0| <= 2 ell の整数点で他に theta=oo は %d 個）  b = sum j* = %d"
          % (S_inf, nother, b_pred))
    check(b_pred == _sage_const_2 , "ell=%d: b = sum j* が 2 でない" % ell)
    for M in range(_sage_const_1 , min(nmax, _sage_const_2 ) + _sage_const_1 ):
        (th, ok) = Theta_level(coeffs, ell, M)
        exp = _sage_const_2  * ell**M + _sage_const_2  + _sage_const_2  * M * euler_phi(ell**M)
        print("      Theta_%d = %s（一意 %s） 予言 2*ell^M + 2 + 2M phi(ell^M) = %s"
              % (M, th, ok, exp))
        check(th == exp, "ell=%d: Theta_%d が (5.6) と違う" % (ell, M))
    for n in range(nmax + _sage_const_1 ):
        N = ell**n
        actual = ZZ(kappa_derived(m, edges, N, N)).valuation(ell)
        print("      n=%d 実測 %d 予言 %d %s" % (n, actual, pred(n),
              "OK" if actual == pred(n) else "MISMATCH"))
        check(actual == pred(n), "ell=%d 型 III 閉形式 n=%d" % (ell, n))

print()
print("  --- ell=2 トーラス: 結論 (5.2) は当たるが、定理 J7 の仮定は破れている")
print("""      ell=2 では 1 = -1 mod 2 なので、S_oo の 2 点 (1:1), (1:-1) が**同じ**方向 (1:1) に入り、
      2 進距離 1/2 しか離れていない。これが tie（打ち消し）の源である。""")
(m2, e2) = bq([(_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 )])
D2 = detL(m2, e2); mu2 = mu_content(D2, _sage_const_2 )
co2 = cleared_coeffs(E_of(D2, _sage_const_2 , mu2))
b2 = _sage_const_0 
for b0 in [_sage_const_1 , -_sage_const_1 ]:
    th = theta_signed(co2, _sage_const_2 , _sage_const_1 , b0)
    es = psi_data(co2, _sage_const_2 , _sage_const_1 , b0, 'w')
    js = min([j for (j, (e, lc)) in enumerate(es) if j >= _sage_const_1  and e is not oo])
    print("      Z_2 点 (1:%2d): theta=%s e_j=%s j*=%s"
          % (b0, th, [('oo' if e is oo else str(e)) for (e, lc) in es], js))
    check(th is oo, "ell=2 トーラス: (1:%d) で theta が oo でない" % b0)
    b2 += js
print("      b = sum_{P in S_oo} j* = %d。cycle 16 定理 D2 の真の値は 2。一致 %s"
      % (b2, b2 == _sage_const_2 ))
check(b2 == _sage_const_2 , "ell=2 トーラス: sum j* が 2 でない")
print("      ただし下の tie 件数の通り定理 B' の一意性が破れる層があり、**定理 J7 の証明は")
print("      この塔を覆っていない**（結論が当たるのは照合であって証明ではない）。")
for M in range(_sage_const_1 , _sage_const_5 ):
    nt = _sage_const_0 
    for (a, b) in P1_reps(_sage_const_2 , M):
        (v, uniq, arg) = hat_theta_predicted(co2, _sage_const_2 , M, a, b)
        if not uniq:
            nt += _sage_const_1 
    (th, ok) = Theta_level(co2, _sage_const_2 , M)
    true_th = (M + _sage_const_3 ) * _sage_const_2 **M - _sage_const_4  if M >= _sage_const_2  else _sage_const_7 
    print("      M=%d : 点 %d 個中 tie %d 個、定理 B' の和 = %s (一意 %s)、cycle16 の真値 = %s%s"
          % (M, len(P1_reps(_sage_const_2 , M)), nt, th, ok, true_th,
             "" if th == true_th else "  ← tie のぶん食い違う（下界）"))
    check(th <= true_th, "ell=2 トーラス M=%d: 定理 B' の和が真値を超えた（下界のはずが）" % M)

# ==========================================================================
print()
print("=" * _sage_const_78 )
print("Step G: 敵対的レビュー", el())
print("=" * _sage_const_78 )

print("  G1: 「定理 K の予言は塔の値へのフィットではないか」")
print("      -> predicted_ord_K は kappa_derived を v_ell(kappa(X))（n=0 の底グラフ）に")
print("         しか使わない。n >= 1 の予言は D の係数だけから出る。Step D の全段が out-of-sample。")

print("  G2: 「系 J5 の判定条件は theta <= ell を真に拡張しているか（空でないか）」")
n_new = n_old = _sage_const_0 
NEW_EX = []
for ell in [_sage_const_3 , _sage_const_5 , _sage_const_7 ]:
    for (name, m, edges) in POP:
        if not connected_by_lattice(m, edges, ell, ell):
            continue
        D = detL(m, edges)
        if D == _sage_const_0 :
            continue
        mu = mu_content(D, ell)
        coeffs = cleared_coeffs(E_of(D, ell, mu))
        dd = direction_data(coeffs, ell)
        if any(e0 is oo for (lab, es, e0, crit, j) in dd):
            continue
        if not all(crit for (lab, es, e0, crit, j) in dd):
            continue
        if all(e0 <= ell for (lab, es, e0, crit, j) in dd):
            n_old += _sage_const_1 
        else:
            n_new += _sage_const_1 
            if len(NEW_EX) < _sage_const_8 :
                NEW_EX.append((ell, name, [e0 for (lab, es, e0, crit, j) in dd]))
print("      判定条件が通る塔: cycle 18 定理 C でも扱えるもの %d 個 / **本サイクルで新たに扱えるもの %d 個**"
      % (n_old, n_new))
for (ell, name, es) in NEW_EX:
    print("        新規: ell=%d %s  e_0 = %s" % (ell, name, es))
check(n_new > _sage_const_0 , "判定条件が theta <= ell を真に拡張する例が 0 件（拡張になっていない）")

print("  G3: 「theta が有限なら本当に n ell^n 項が出ないか」")
print("      -> Step E の例（e_0 = 4 > ell = 3）で閉形式に n 3^n 項が無いことを n <= 3 で照合済み。")
print("         母集団側は Step D が定理 K の予言と実測の一致で保証している。")

print("  G4: 「theta = oo は本当に n ell^n を生むのか、たまたまではないか」")
print("      -> Step F の族は ell = 3,5,7,11 で b = sum j* = 2 と一致（塔の値と照合）。")
print("         ell=2 トーラス（cycle 16 定理 D2, b=2）も同じ式に乗るが、そこでは仮定が破れており")
print("         **証明が覆っていない**（照合であって証明ではない）ことを Step F に明記した。")

print("  G6: 「S_oo を P^1(F_ell) の方向と取り違えていないか」")
print("      -> 取り違えていた（report §11.2）。Step F は Z_ell の点 (1:1),(1:-1) を基点に取り、")
print("         整数代表 (1, ell-1) では theta が有限であることも同時に出力して差を見せている。")

print("  G5: 「Step A の破れ件数が 0 でないことを要求したか」")
print("      -> 要求した（cycle 18 注 2.2 の教訓）。0 件なら FAIL する。")

# ==========================================================================
print()
print("=" * _sage_const_78 )
print("まとめ", el())
print("=" * _sage_const_78 )
print("  FAIL 件数: %d" % FAIL)
print("  打ち切った計算: %d 件" % len(TRUNC))
for t in TRUNC:
    print("    -", t)
print("  ※ Step A-F は証明済み命題の照合である。証明は report 本体にある。")

