

# This file was *autogenerated* from the file tau_vp_law.sage
from sage.all_cmdline import *   # import sage library

_sage_const_70 = Integer(70); _sage_const_2 = Integer(2); _sage_const_13 = Integer(13); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11)# cycle 10 / T1: 全域木数 τ(L)=#spanning trees of L×L トーラス の v_p(τ(L)) の L 依存則。
# τ(L) を厳密整数で計算(Kirchhoff, spanning_trees_count)。Λ側=Φ_L=log τ(L) の ℓ_p 係数。

def torus(L):
    C=graphs.CycleGraph(L)
    return C.cartesian_product(C)

print("="*_sage_const_70 )
print("τ(L)=#spanning trees(L×L torus) の素因数分解と v_p 則")
print("="*_sage_const_70 )
taus={}
for L in range(_sage_const_2 ,_sage_const_13 ):
    G=torus(L)
    t=ZZ(G.spanning_trees_count())
    taus[L]=t
    fac=factor(t)
    print(f"  L={L:2}: τ={t}")
    print(f"        = {fac}")

print("\n--- v_p(τ(L)) を p 別に(L=2..12) ---")
for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ]:
    row=[taus[L].valuation(p) for L in range(_sage_const_2 ,_sage_const_13 )]
    print(f"  p={p:2}: {row}")

print("\n--- 素数 L=p での v_p(τ(p)) ---")
for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ]:
    print(f"  L=p={p}: v_p(τ(p))={taus[p].valuation(p)}")

print("\n"+"="*_sage_const_70 )
print("観察: v_p(τ(L)) の L 依存則を読む(下の README に記述)。")
print(" 全て有限 L で厳密整数=決定可能(Λ側)。ℝ側は (1/L^2)logτ→4G/π。")
print("="*_sage_const_70 )

