

# This file was *autogenerated* from the file check_01_transfer_matrix_sanity.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0p4 = RealNumber('0.4'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p25 = RealNumber('0.25'); _sage_const_1p3 = RealNumber('1.3'); _sage_const_0 = Integer(0); _sage_const_1en15 = RealNumber('1e-15'); _sage_const_1 = Integer(1)# <def_transfer_matrix>: V_1 は対角、V_2 は対称、成分は正、サイズは 2^N x 2^N
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import itertools
load(os.path.join(_dir, "_prelude.sage"))
rep = CheckReport("def_transfer_matrix")
for N in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    for (J,Jp) in [(_sage_const_0p4 ,_sage_const_0p9 ),(_sage_const_0p9 ,_sage_const_0p4 ),(_sage_const_0p25 ,_sage_const_1p3 )]:
        V1,V2 = transfer_matrices(J,Jp,N)
        n = _sage_const_2 **N
        rep.truth(V1.shape == (n,n) and V2.shape == (n,n), f"N={N}: サイズ 2^N x 2^N")
        rep.close(V1, np.diag(np.diag(V1)), f"N={N}: V_1 は対角行列（delta_(mu=mu')）")
        rep.close(V2, V2.T, f"N={N}: V_2 は対称")
        rep.truth(np.all(np.real(np.diag(V1)) > _sage_const_0 ) and np.all(np.real(V2) > _sage_const_0 ), f"N={N}: 成分は正")
        rep.truth(abs(np.imag(V1)).max() < _sage_const_1en15  and abs(np.imag(V2)).max() < _sage_const_1en15 , f"N={N}: 実行列")
        mus = list(itertools.product([-_sage_const_1 ,_sage_const_1 ], repeat=N))
        for a,mu in enumerate(mus):
            rep.close(V1[a,a], np.exp(sum(Jp*mu[j]*mu[(j+_sage_const_1 )%N] for j in range(N))), f"N={N} a={a}: V_1 の成分")
            for b,mup in enumerate(mus):
                rep.close(V2[a,b], np.exp(sum(J*mu[j]*mup[j] for j in range(N))), f"N={N} ({a},{b}): V_2 の成分")
rep.finish()

