/**
 * Chapter 4: the finite, elementary, decidable propositions on the Λ side
 * (Propositions A, B, C, C′, N, L) — English version.
 *
 * **正本は日本語版 `../../structured-latex/content/004_lambda_finite.ts` である。**
 * このファイルはその英訳であり、ブロック id・ラベル・`habitat`・`verification` / `lean`・
 * `proof` の有無・**数式**は日本語版と完全に同じにする
 * （`tools/verify-ja-en-correspondence.ts` がこれを検査する）。
 * 訳語は `integrable-lattice/docs/paper001-en-glossary.md` を正本とする。
 *
 * **この英訳が扱うのは日本語版 9 ブロックのうち先頭 7 ブロックである。**
 * 残る 2 ブロック（`paper_045_theorem_trace_ladder` = 命題 C″、
 * `paper_046_theorem_wstar_different` = 命題 W*）は別担当が足す。したがって
 * 日本語版がその 2 つへ張っている `ref()` は、英語版のラベルがまだ実在せず型検査が通らないため、
 * **暫定的に地の文の言い回しへ落としてある**（該当箇所には TODO コメントを置いた）。
 * 2 ブロックが英語版へ入ったら `ref("paper_prop_C_trace_ladder")` /
 * `ref("paper_wstar_different")` へ戻すこと。参照先が失われているのではなく、
 * 相互参照の機構に戻す作業が残っているだけである。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_040_heading_lambda",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex-en/content/004_lambda_finite.ts", ordinal: 1 },
    title: {
      text: "The finite, decidable face of the Λ side — Propositions A, B, C, N, L",
    },
    labels: [],
  },
  {
    id: "paper_041_theorem_periodicity",
    kind: "theorem",
    origin: { path: "structured-latex-en/content/004_lambda_finite.ts", ordinal: 2 },
    // 日本語版のタイトルは「命題 A（v_p の最終周期性）」。地の文へ数式記法を持ち込むと
    // そのままの文字として組まれる（生成器が警告する）ので、語で書いた。
    title: { text: "Proposition A (eventual periodicity of the p-adic valuation)" },
    labels: ["paper_prop_A"],
    habitat: "Z",
    verification: ["sagemath/check/cycle3_T1_period_bound", "sagemath/check/D-U2_padic_law"],
    lean: [
      "IntegrableLattice.exists_eventually_periodic_pow",
      "IntegrableLattice.exists_eventually_periodic_matrixPow",
      "IntegrableLattice.exists_eventually_periodic_trace",
      "IntegrableLattice.exists_eventually_periodic_truncVal",
      "IntegrableLattice.exists_eventually_periodic_min_padicValInt",
    ],
    statement: [
      paragraph([
        "Let ",
        math(String.raw`T\in M_d(\mathbb{Z})`),
        ", put ",
        math(String.raw`Z_N:=\operatorname{Tr}T^N`),
        ", and let ",
        math(String.raw`p`),
        " be a prime with ",
        math(String.raw`p\nmid\det T`),
        ". For every truncation level ",
        math(String.raw`k\ge1`),
        ", the quantity ",
        math(String.raw`\min\bigl(v_p(Z_N),k\bigr)`),
        " is **eventually periodic** in ",
        math(String.raw`N`),
        ", and its period divides the eventual period ",
        math(String.raw`\pi(p,k)`),
        " of the matrix power sequence ",
        math(String.raw`T^N\bmod p^k`),
        ".",
      ]),
      paragraph([
        "The quantity ",
        math(String.raw`\pi(p,k)`),
        " is **decidable** inside the finite monoid ",
        math(String.raw`M_d(\mathbb{Z}/p^k)`),
        ": one generates the elements of the sequence in turn and looks for the first repetition.",
      ]),
      paragraph([
        "**A caution on notation (the two periods must not be confused)**: ",
        math(String.raw`\pi(p,k)`),
        " is the period of the **matrix power sequence**, and it is a different quantity from ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)`),
        ", the period of the **trace sequence**, which appears in ",
        ref("paper_prop_B"),
        ". The divisibility ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)\mid\pi(p,k)`),
        " holds, but **the converse does not hold**: there are actual examples in which the ratio is not ",
        math(String.raw`1`),
        ".",
      ]),
    ],
    proof: [
      paragraph([
        "Since ",
        math(String.raw`T\bmod p^k`),
        " is an element of the finite set ",
        math(String.raw`M_d(\mathbb{Z}/p^k)`),
        ", the sequence ",
        math(String.raw`(T^N\bmod p^k)_{N\ge0}`),
        " is eventually periodic by the pigeonhole principle. As ",
        math(String.raw`Z_N\bmod p^k`),
        " is the trace of that sequence, it is eventually periodic with the same period, and ",
        math(String.raw`\min(v_p(Z_N),k)`),
        " is determined by ",
        math(String.raw`Z_N\bmod p^k`),
        ".",
      ]),
      paragraph([
        "**Note**: the only tool used is the pigeonhole principle on a finite set; neither ",
        math(String.raw`\mathbb{Q}_p`),
        " nor any analysis is used. The statement is a restatement of the known ",
        math(String.raw`p`),
        "-adic analysis of linear recurrence sequences.",
      ]),
    ],
  },
  {
    id: "paper_042_theorem_pi_p1",
    kind: "theorem",
    origin: { path: "structured-latex-en/content/004_lambda_finite.ts", ordinal: 3 },
    title: {
      text: "Proposition B (exact formula for the period of the trace sequence at level one)",
    },
    labels: ["paper_prop_B"],
    habitat: "Z",
    verification: ["sagemath/check/cycle3_T3_period"],
    lean: [
      "IntegrableLattice.expSum_eventually_periodic_iff_lcm_dvd",
      "IntegrableLattice.isLeast_period_expSum",
      "IntegrableLattice.trace_pow_eq_sum_maxGenEigenspace",
      "IntegrableLattice.trace_pow_eventually_periodic_iff",
    ],
    statement: [
      paragraph([
        "Let ",
        math(String.raw`\pi_{\mathrm{tr}}(p,1)`),
        " denote the eventual period of the **trace sequence** ",
        math(String.raw`Z_N=\mathrm{Tr}\,T^N\bmod p`),
        ". Then",
      ]),
      displayMath(
        String.raw`\pi_{\mathrm{tr}}(p,1)=\operatorname{lcm}\bigl\{\operatorname{ord}(\lambda)\ :\ \lambda\in\overline{\mathbb{F}_p}^{\times}\ \text{は }\chi_T\bmod p\text{ の相異なる根},\ p\nmid m_\lambda\bigr\}`,
      ),
      paragraph([
        "Here ",
        math(String.raw`m_\lambda`),
        " denotes the algebraic multiplicity of the root ",
        math(String.raw`\lambda`),
        ".",
      ]),
      paragraph([
        "**[Correction]** This statement is **not** a statement about the quantity ",
        math(String.raw`\pi(p,1)`),
        " of ",
        ref("paper_prop_A"),
        ", that is, about the eventual period of the **matrix power sequence** ",
        math(String.raw`T^N\bmod p^k`),
        ". An earlier version of this paper wrote the two quantities with the same symbol, and ",
        "**under that reading the statement was false**. Counterexample: for ",
        math(String.raw`T=\begin{pmatrix}0&1\\1&1\end{pmatrix}^{\oplus2}`),
        " and ",
        math(String.raw`p=2`),
        ", the period of the matrix power sequence is ",
        math(String.raw`3`),
        ", whereas the trace sequence is identically ",
        math(String.raw`0`),
        " and therefore has period ",
        math(String.raw`1`),
        "; the right-hand side of the formula is ",
        math(String.raw`1`),
        " as well, because both multiplicities equal ",
        math(String.raw`2`),
        " and the set is empty. The matrix ",
        math(String.raw`T`),
        " of this counterexample is semisimple, so **assuming semisimplicity does not rescue the " +
          "statement**. In a random sample of 2487 examples, the two periods disagreed in 563 cases " +
          "(22.6%).",
      ]),
    ],
    proof: [
      paragraph([
        "**We prove both directions.** The generalised eigenspace decomposition gives ",
        math(String.raw`Z_N=\sum_\lambda m_\lambda\lambda^N`),
        " over ",
        math(String.raw`\overline{\mathbb{F}_p}`),
        "; in characteristic ",
        math(String.raw`p`),
        " the condition ",
        math(String.raw`m_\lambda\not\equiv0`),
        " is the same as ",
        math(String.raw`p\nmid m_\lambda`),
        ".",
      ]),
      paragraph([
        "The exponential functions ",
        math(String.raw`N\mapsto\lambda^N`),
        " attached to distinct ",
        math(String.raw`\lambda`),
        " are linearly independent (Artin's linear independence of characters). Hence ",
        math(String.raw`t`),
        " is an eventual period of ",
        math(String.raw`Z_N`),
        " **if and only if** ",
        math(String.raw`\operatorname{ord}(\lambda)\mid t`),
        " holds for every ",
        math(String.raw`\lambda`),
        " with ",
        math(String.raw`p\nmid m_\lambda`),
        ", and the least such ",
        math(String.raw`t`),
        " is the least common multiple displayed above. The terms with ",
        math(String.raw`p\mid m_\lambda`),
        " vanish ",
        math(String.raw`\bmod p`),
        " and contribute nothing.",
      ]),
      paragraph([
        "**This proposition has been formalised in Lean** (over an algebraically closed field, in ",
        "complete form and with no auxiliary hypothesis). The supporting report is ",
        math(String.raw`\texttt{outputs/reports/cycle17\_ops\_lean\_propB.md}`),
        ".",
      ]),
    ],
  },
  {
    id: "paper_043_theorem_bound",
    kind: "theorem",
    origin: { path: "structured-latex-en/content/004_lambda_finite.ts", ordinal: 4 },
    title: {
      text: "Proposition C (upper bound for the period; equality of Wall type does not hold in general)",
    },
    labels: ["paper_prop_C"],
    habitat: "Z",
    verification: ["sagemath/check/cycle3_T3_period"],
    lean: [
      "IntegrableLattice.dvd_one_add_pow_prime_sub_one",
      "IntegrableLattice.dvd_pow_prime_pow_sub_one",
      "IntegrableLattice.pow_prime_pow_eq_one_of_eq_one_add",
      "IntegrableLattice.matrix_pow_prime_pow_eq_one",
    ],
    statement: [
      paragraph([
        "The divisibility ",
        math(String.raw`\pi(p,k)\ \bigm|\ p^{k-1}\pi(p,1)`),
        " holds (an upper bound of Pisano type; **known**). Here ",
        math(String.raw`\pi`),
        " is, as in ",
        ref("paper_prop_A"),
        ", the eventual period of the **matrix power sequence** ",
        math(String.raw`T^N\bmod p^k`),
        ".",
      ]),
      paragraph([
        "**Read with the trace sequence in place of the matrix power sequence, this upper bound " +
          "becomes false.** If the period ",
        math(String.raw`\pi_{\mathrm{tr}}`),
        " of the trace sequence of ",
        ref("paper_prop_B"),
        " is substituted here, the divisibility fails in 56 out of 1669 examples (3.4%). The two ",
        "periods are different quantities and cannot share a symbol. The correct upper bound for ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)`),
        " with ",
        math(String.raw`k\ge2`),
        " is given in ",
        ref("paper_prop_C_trace"),
        ".",
      ]),
      paragraph([
        "**Equality (of Wall type) does not hold in general.** In the verification carried out for this ",
        "paper, equality failed for 10 out of 472 non-degenerate companion matrices (about 2.1%), and for ",
        "26 out of 572 transfer matrices of the six-vertex model (about 4.5%).",
      ]),
    ],
    proof: [
      paragraph([
        "The upper bound follows by writing ",
        math(String.raw`T^{\pi(p,1)}\equiv I+pS`),
        " and raising this to the ",
        math(String.raw`p^{k-1}`),
        "-th power (known). That equality fails is shown by the counterexamples recorded above.",
      ]),
      paragraph([
        "**A methodological note (a lesson this paper states explicitly)**: at the outset of this work, a ",
        "search over 43 examples produced no counterexample, and from that observation we formed the ",
        "hypothesis that integrability protects equality of Wall type. But an absence of counterexamples ",
        "is no support for a hypothesis. When the sample was enlarged by an order of magnitude, to 572 ",
        "examples, counterexamples appeared at a rate of 4.5%, and **the hypothesis was refuted**. An ",
        "observation of zero cases must not be used as evidence.",
      ]),
    ],
  },
  {
    id: "paper_043b_theorem_trace_bound",
    kind: "theorem",
    origin: { path: "structured-latex-en/content/004_lambda_finite.ts", ordinal: 5 },
    title: {
      text:
        "Proposition C' (upper bound for the period of the trace sequence; " +
        "the trace-sequence counterpart of Proposition C)",
    },
    labels: ["paper_prop_C_trace"],
    habitat: "Z",
    verification: ["sagemath/check/cycle18_T3_trace_period"],
    statement: [
      paragraph([
        "Let ",
        math(String.raw`\chi_T=\prod_i f_i^{a_i}`),
        " be the factorisation into irreducibles over ",
        math(String.raw`\mathbb{Z}[x]`),
        ", put ",
        math(String.raw`\rho=\prod_i f_i`),
        " (the radical) and ",
        math(String.raw`r=\deg\rho`),
        ", and let ",
        math(String.raw`e_r`),
        " be the largest elementary divisor (the last diagonal entry of the Smith normal form) of the ",
        "Gram matrix ",
        math(String.raw`G=\bigl(\operatorname{Tr}T^{i+j}\bigr)_{0\le i,j<r}\in M_r(\mathbb{Z})`),
        ". Set ",
        math(String.raw`w^*=v_p(e_r)`),
        ". Then",
      ]),
      displayMath(
        String.raw`\pi_{\mathrm{tr}}(p,k)\ \bigm|\ p^{\,k-1}\,\pi_{\mathrm{tr}}(p,\,w^*+1)\qquad(k\ge1).`,
      ),
      paragraph([
        "Moreover ",
        math(String.raw`\det G=\operatorname{disc}(\rho)\cdot\prod_\lambda m_\lambda\neq0`),
        ", and ",
        math(String.raw`w^*=0`),
        " is equivalent to the conjunction of the two conditions that ",
        math(String.raw`\rho\bmod p`),
        " is separable and that ",
        math(String.raw`p\nmid m_\lambda`),
        " holds for every multiplicity; the second of these is exactly the condition of ",
        ref("paper_prop_B"),
        ". When ",
        math(String.raw`w^*=0`),
        ", the upper bound takes the same shape as in ",
        ref("paper_prop_C"),
        ", namely ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)\mid p^{k-1}\pi_{\mathrm{tr}}(p,1)`),
        ".",
      ]),
      paragraph([
        "**No correction is possible that keeps the base level fixed at one.** The divisibility ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)\mid p^{a}\pi_{\mathrm{tr}}(p,1)`),
        ", whose base level is ",
        math(String.raw`1`),
        ", is false however the exponent ",
        math(String.raw`a`),
        " is chosen: ",
        math(String.raw`T=F\oplus F`),
        " with ",
        math(String.raw`F=\begin{pmatrix}0&1\\1&1\end{pmatrix}`),
        " and ",
        math(String.raw`p=2`),
        " is a counterexample, since ",
        math(String.raw`\pi_{\mathrm{tr}}(2,1)=1`),
        " while ",
        math(String.raw`\pi_{\mathrm{tr}}(2,2)=3`),
        ". What has to be corrected is not the exponent but the base level.",
      ]),
      paragraph([
        "**Decidability**: ",
        math(String.raw`w^*`),
        " is determined by a finite procedure from the Smith normal form of the integer matrix ",
        math(String.raw`G`),
        ", and ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)`),
        " itself is determined by a search in the finite ring ",
        math(String.raw`M_d(\mathbb{Z}/p^k)`),
        ". The proof is closed within linear algebra over integer matrices (Cramer's rule and the Smith ",
        "normal form) together with the Vandermonde determinant of algebraic numbers, and it never ",
        "escapes to an uncountable field: neither to the reals, nor to the complex numbers, nor to the ",
        "ring of ",
        math(String.raw`p`),
        "-adic integers.",
      ]),
      paragraph([
        "**This upper bound is not the best possible.** The exponent ",
        math(String.raw`p^{k-1}`),
        " can be lowered to ",
        math(String.raw`p^{\,k-w^*-1}`),
        // TODO(統合時): 英語版に paper_prop_C_trace_ladder が入ったら ref() へ戻す。
        " (the ladder proposition later in this chapter). An algebraic closed form for ",
        math(String.raw`w^*`),
        " itself is given by the proposition on the trace dual and the different, also later in this ",
        // TODO(統合時): 英語版に paper_wstar_different が入ったら ref() へ戻す。
        "chapter.",
      ]),
    ],
    proof: [
      paragraph([
        "Put ",
        math(String.raw`S=\bigoplus_i C_{f_i}^{\oplus a_i}`),
        ", where ",
        math(String.raw`C_f`),
        " denotes the companion matrix. Then ",
        math(String.raw`\chi_S=\chi_T`),
        ", so Newton's identities give ",
        math(String.raw`\operatorname{Tr}S^N=\operatorname{Tr}T^N`),
        " for every ",
        math(String.raw`N`),
        ", and ",
        math(String.raw`\mathrm{minpoly}(S)=\rho`),
        ".",
      ]),
      paragraph([
        "Write ",
        math(String.raw`t=\pi_{\mathrm{tr}}(p,k)`),
        " and ",
        math(String.raw`B=S^t-I\in\mathbb{Z}[S]=\bigoplus_{j<r}\mathbb{Z}S^j`),
        ". Periodicity gives ",
        math(String.raw`\operatorname{Tr}(S^NB)\equiv0\ (p^k)`),
        " for every ",
        math(String.raw`N`),
        ", and taking ",
        math(String.raw`N=0,\dots,r-1`),
        " yields ",
        math(String.raw`Gb\equiv0\ (p^k)`),
        " for the coefficient vector ",
        math(String.raw`b\in\mathbb{Z}^r`),
        ". Since ",
        math(String.raw`p^{w^*}G^{-1}`),
        " has ",
        math(String.raw`p`),
        "-adically integral entries, ",
        math(String.raw`b\equiv0\ (p^{k-w^*})`),
        ", that is, ",
        math(String.raw`\pi(p,k-w^*;S)\mid t`),
        " whenever ",
        math(String.raw`k>w^*`),
        ".",
      ]),
      paragraph([
        "Applying this with ",
        math(String.raw`k=w^*+1`),
        " gives ",
        math(String.raw`\pi(p,1;S)\mid\pi_{\mathrm{tr}}(p,w^*+1)`),
        ". Combined with the matrix power sequence version of ",
        ref("paper_prop_C"),
        ", this yields ",
        math(
          String.raw`\pi_{\mathrm{tr}}(p,k)\mid\pi(p,k;S)\mid p^{k-1}\pi(p,1;S)\mid p^{k-1}\pi_{\mathrm{tr}}(p,w^*+1)`,
        ),
        "; for ",
        math(String.raw`k\le w^*+1`),
        " the claim follows from the monotonicity ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)\mid\pi_{\mathrm{tr}}(p,k+1)`),
        ". The formula for ",
        math(String.raw`\det G`),
        " follows from ",
        math(String.raw`G=V\,\mathrm{diag}(m_\lambda)\,V^{\mathsf T}`),
        ", where ",
        math(String.raw`V`),
        " is the Vandermonde matrix of the distinct roots.",
      ]),
      paragraph([
        "The counterexample comes from ",
        math(String.raw`\operatorname{Tr}T^N=2L_N`),
        " (Lucas numbers): ",
        math(String.raw`\bmod2`),
        " the sequence is identically ",
        math(String.raw`0`),
        ", whereas ",
        math(String.raw`\bmod4`),
        " the least period of ",
        math(String.raw`L_N\bmod2`),
        ", which is ",
        math(String.raw`3`),
        ", becomes visible. The supporting report for this proposition is ",
        math(String.raw`\texttt{outputs/reports/cycle18\_T3\_trace\_period\_bound.md}`),
        ".",
      ]),
    ],
  },
  {
    id: "paper_044_theorem_newton",
    kind: "theorem",
    origin: { path: "structured-latex-en/content/004_lambda_finite.ts", ordinal: 6 },
    title: { text: "Proposition N (the linear growth rate is determined by the Newton polygon)" },
    labels: ["paper_prop_N"],
    habitat: "Z",
    verification: [
      "sagemath/check/D-U2_padic_law",
      "sagemath/check/cycle18_ops_NTW_recheck",
    ],
    lean: [
      "IntegrableLattice.trace_pow_add_eq_neg_sum",
      "IntegrableLattice.trace_pow_dvd_of_charpoly_coeff_dvd",
      "IntegrableLattice.le_padicValInt_trace_pow",
      "IntegrableLattice.trace_cexN_pow_odd",
      "IntegrableLattice.cexN_exceptional_unbounded",
    ],
    statement: [
      paragraph([
        "The rate of linear growth in ",
        math(String.raw`N`),
        " of ",
        math(String.raw`v_p(Z_N)`),
        " equals",
      ]),
      displayMath(String.raw`\mu_{\min}(p)=\min_i v_p(\lambda_i)`),
      paragraph([
        "and this quantity is determined as the **minimal slope** of the ",
        math(String.raw`p`),
        "-adic Newton polygon of the characteristic polynomial ",
        math(String.raw`\chi_T`),
        ".",
      ]),
      paragraph([
        "**Convention on the orientation of the Newton polygon**: in this paper, for ",
        math(String.raw`\chi_T=\sum_i c_ix^i`),
        " we take the lower convex hull of the point set ",
        math(String.raw`\{(d-i,\,v_p(c_i))\}`),
        ", with the orientation in which the slopes are the valuations of the roots themselves; the ",
        "**minimal slope** for this orientation is ",
        math(String.raw`\min_i v_p(\lambda_i)`),
        ". Under the opposite convention the sign is reversed, so the phrase minimal slope must never be ",
        "used without stating the convention.",
      ]),
      paragraph([
        "**Lower bound, in a form that holds for each single index**: ",
        math(String.raw`v_p(Z_N)\ge\mu_{\min}(p)\,N`),
        " for every ",
        math(String.raw`N`),
        ". In particular, ",
        math(String.raw`\mu_{\min}\ge m`),
        " for an integer ",
        math(String.raw`m`),
        " can be checked finitely, as it amounts to the condition ",
        math(String.raw`p^{m(d-i)}\mid c_i`),
        " on the coefficients, and from this condition alone the Cayley–Hamilton theorem yields",
      ]),
      displayMath(String.raw`p^{mN}\ \Big|\ p^{md}\,Z_N\qquad(\forall N)`),
      paragraph([
        "This derivation never constructs ",
        math(String.raw`\mathbb{Q}_p`),
        ", and **it uses neither the eigenvalues nor the Newton polygon**; it has been formalised with ",
        "Lean 4 and mathlib4 in Chapter 8. The constant offset ",
        math(String.raw`md`),
        " does not depend on ",
        math(String.raw`N`),
        ", so the inequality is enough as a lower bound for the linear growth rate.",
      ]),
      paragraph([
        "**Decidability**: the Newton polygon is the lower convex hull of a set of points whose ",
        "coordinates are the ",
        math(String.raw`p`),
        "-adic valuations of the coefficients, hence integers, and it is obtained by a finite ",
        "combinatorial computation. **Neither the individual eigenvalues nor the field** ",
        math(String.raw`\mathbb{Q}_p`),
        " **has to be constructed.**",
      ]),
    ],
    proof: [
      paragraph([
        "In ",
        math(String.raw`Z_N=\sum_i\lambda_i^N`),
        " the eigenvalue of least valuation is dominant, which gives the statement (the known Newton ",
        "polygon argument). **However, cancellation of Skolem–Mahler–Lech type creates exceptions.** " +
          "The exceptional set is a finite union of arithmetic progressions and is therefore " +
          "**infinite in general**. This is an error in the text of an earlier version, discovered " +
          "during the Lean formalisation of cycle 18: that version wrote that there are finitely many " +
          "exceptional ",
        math(String.raw`N`),
        ", which misread the phrase finite union of arithmetic progressions in the supporting report. ",
        "**Counterexample**: for ",
        math(String.raw`T=\begin{pmatrix}0&1\\2&0\end{pmatrix}`),
        " and ",
        math(String.raw`p=2`),
        " we have ",
        math(String.raw`\chi_T=x^2-2`),
        " and ",
        math(String.raw`\mu_{\min}=1/2`),
        ", and yet ",
        math(String.raw`Z_N=0`),
        " for **every odd index** ",
        math(String.raw`N`),
        " (this was formalised in Chapter 8). For ",
        math(String.raw`N=2k`),
        " one has ",
        math(String.raw`Z_N=2^{k+1}`),
        ", and the growth rate agrees with ",
        math(String.raw`1/2`),
        ". Equality is therefore correct only as a statement about those ",
        math(String.raw`N`),
        " that lie **outside the exceptional set**. In the verification carried out for this paper, ",
        "period detection failed in one instance as well, namely the six-vertex model with weights ",
        math(String.raw`(1,1,1)`),
        ", ",
        math(String.raw`L=2`),
        " and ",
        math(String.raw`p=7`),
        ". This caveat must not be dropped, and the equality must not be stated as a general rule.",
      ]),
    ],
  },
  {
    id: "paper_045_theorem_lte",
    kind: "theorem",
    origin: { path: "structured-latex-en/content/004_lambda_finite.ts", ordinal: 7 },
    title: { text: "Proposition L (the one-variable minimal example in complete form; LTE)" },
    labels: ["paper_prop_L"],
    habitat: "Z",
    verification: ["sagemath/check/cycle7_T1_lte"],
    lean: [
      "IntegrableLattice.padicValNat_pow_sub_one_of_dvd",
      "IntegrableLattice.padicValNat_pow_sub_one_of_not_dvd_order",
      "IntegrableLattice.padicValNat_pow_sub_one_odd",
      "IntegrableLattice.padicValNat_two_pow_sub_one_odd_exp",
      "IntegrableLattice.padicValNat_two_pow_sub_one_even_exp",
    ],
    statement: [
      paragraph([
        "For ",
        math(String.raw`P(z)=z-c`),
        " with ",
        math(String.raw`c\in\mathbb{Z}_{\ge2}`),
        " one has ",
        math(String.raw`|a_L|=c^L-1`),
        ", and in this case ",
        math(String.raw`v_p`),
        " is completely determined.",
      ]),
      list([
        [
          "**For an odd prime** ",
          math(String.raw`p`),
          " **with** ",
          math(String.raw`p\nmid c`),
          " **, putting** ",
          math(String.raw`d=\operatorname{ord}_p(c)`),
          ": if ",
          math(String.raw`d\mid L`),
          " then ",
          math(String.raw`v_p(c^L-1)=v_p(c^d-1)+v_p(L)`),
          ", and if ",
          math(String.raw`d\nmid L`),
          " the valuation is ",
          math(String.raw`0`),
          ".",
        ],
        [
          "**For** ",
          math(String.raw`p=2`),
          " **with** ",
          math(String.raw`c`),
          " **odd**: if ",
          math(String.raw`L`),
          " is odd then ",
          math(String.raw`v_2(c^L-1)=v_2(c-1)`),
          ", and if ",
          math(String.raw`L`),
          " is even the value is ",
          math(String.raw`v_2(c-1)+v_2(c+1)+v_2(L)-1`),
          ".",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "This is the standard lemma of lifting the exponent (LTE) (**known**). For odd ",
        math(String.raw`p`),
        " it follows from ",
        math(String.raw`c^d\equiv1`),
        " together with the binomial expansion; for ",
        math(String.raw`p=2`),
        " it follows by iterating the factorisation ",
        math(String.raw`c^L-1=(c^{L/2}-1)(c^{L/2}+1)`),
        ".",
      ]),
      paragraph([
        "**This proposition has been formalised with Lean 4 and mathlib4** (Chapter 8). On the ",
        "archimedean side one has ",
        math(String.raw`\lim_L\frac1L\log|a_L|=\log c=m(z-c)`),
        ", so this is the smallest example in which both places can be written down explicitly for one ",
        "and the same ",
        math(String.raw`P`),
        ".",
      ]),
    ],
  },
]);
