

# This file was *autogenerated* from the file check_01_pauli_group.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_30 = Integer(30); _sage_const_8 = Integer(8)# <def_pauli_group>, <def_clifford_group>: Pauli 群が積で閉じ、位数が 4*4^M
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import itertools
rep = CheckReport("def_pauli_group / def_clifford_group")
def pauli_group(M):
    out = []
    for k in range(_sage_const_4 ):
        for combo in itertools.product('0xyz', repeat=M):
            out.append((_sage_const_1j **k) * kron_list([PAULI[a] for a in combo]))
    return out
def in_group(X, mats, tol=_sage_const_1en8 ):
    for Y in mats:
        if np.max(np.abs(X - Y)) < tol:
            return True
    return False
for M in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ]:
    mats = pauli_group(M)
    rep.truth(len(mats) == _sage_const_4  * _sage_const_4 **M, f"M={M}: #P_M = 4*4^M = {_sage_const_4 *_sage_const_4 **M}")
    # 相異なる元であること（重複していないこと）
    if M <= _sage_const_2 :
        dup = _sage_const_0 
        for a in range(len(mats)):
            for b in range(a+_sage_const_1 , len(mats)):
                if np.max(np.abs(mats[a]-mats[b])) < _sage_const_1en9 :
                    dup += _sage_const_1 
        rep.truth(dup == _sage_const_0 , f"M={M}: 列挙に重複が無い")
    rng = np.random.default_rng(int(M))
    idx = [int(k) for k in rng.choice(len(mats), size=min(len(mats), _sage_const_30 ), replace=False)]
    for a in idx:
        for b in idx[:_sage_const_8 ]:
            rep.truth(in_group(mats[a] @ mats[b], mats), f"M={M}: 積が P_M に属する")
    rep.truth(in_group(eye_M(M), mats), f"M={M}: 単位元を含む")
    for a in idx[:_sage_const_8 ]:
        rep.truth(in_group(np.linalg.inv(mats[a]), mats), f"M={M}: 逆元を含む")
rep.finish()

