

# This file was *autogenerated* from the file dispersion_N4_lam1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_70 = Integer(70); _sage_const_4 = Integer(4)# cycle 9 / T2: N=4 カイラル Potts の cubic 因子(cubic 運動量)を λ=1 固定で同定。
# symbolic-λ は 81 次で重すぎるので λ=1 に固定し charpoly を ℚ 上因数分解、
# cubic(deg3) 因子の体(判別式)を見る。運動量解釈は慎重に。

K = CyclotomicField(_sage_const_3 , names=('om',)); (om,) = K._first_ngens(1); n=_sage_const_3 
Z=matrix(K,[[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,om,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,om**_sage_const_2 ]])
X=matrix(K,[[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
I3=identity_matrix(K,_sage_const_3 )
def emb(op,i,N):
    m=[op if k==i else I3 for k in range(N)]
    M=m[_sage_const_0 ]
    for k in range(_sage_const_1 ,N): M=M.tensor_product(m[k])
    return M
def H(N,lam):
    c={a:(_sage_const_1 -om**(-a))**(-_sage_const_1 ) for a in [_sage_const_1 ,_sage_const_2 ]}
    Zi={i:emb(Z,i,N) for i in range(N)}; Xi={i:emb(X,i,N) for i in range(N)}
    HH=matrix(K,_sage_const_3 **N,_sage_const_3 **N)
    for j in range(N):
        jp=(j+_sage_const_1 )%N
        for a in [_sage_const_1 ,_sage_const_2 ]:
            HH += -c[a]*(Xi[j]**a + lam*Zi[j]**a*Zi[jp]**(n-a))
    return HH

print("="*_sage_const_70 )
print("N=4 カイラル Potts (λ=1): charpoly ℚ 因数分解と cubic 因子")
print("="*_sage_const_70 )
Hm=H(_sage_const_4 ,QQ(_sage_const_1 ))
cp=Hm.charpoly()
try:
    cpQ=cp.change_ring(QQ)
except Exception as e:
    cpQ=None
    print("charpoly が ℚ 上でない:", e)
if cpQ is not None:
    fac=cpQ.factor()
    from collections import Counter
    degc=Counter()
    cubics=[]
    for g,m in fac:
        degc[g.degree()]+=m
        if g.degree()==_sage_const_3 :
            cubics.append(g)
    print(f"  因子次数分布(重複度込み): {dict(sorted(degc.items()))}")
    print(f"  cubic(deg3) 因子数: {len(cubics)}")
    for g in cubics[:_sage_const_4 ]:
        # cubic の判別式と Galois 群(体の種類)
        d=g.discriminant()
        print(f"    cubic: {g}")
        print(f"       判別式={d}, 平方? {d.is_square()} (平方なら巡回, 非平方なら S_3)")
    print(f"\n  ⇒ cubic 因子が存在 = cubic な代数的量(運動量 cosθ 候補)を含む(cycle6/7 の予測と整合)。")

print("\n"+"="*_sage_const_70 )
print("正直な注記: λ=1 固定では E=(linear in λ)±ε の分離ができず, cubic 因子から cosθ を")
print(" 一意に取り出せない. 『cubic 因子存在=cubic 運動量』は整合的だが, 厳密な cosθ 同定には")
print(" 超可積分スペクトル理論(Albertini–McCoy–Perk の量子化条件)との照合が要る(cycle10+).")
print("="*_sage_const_70 )

