

# This file was *autogenerated* from the file dispersion_N3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_70 = Integer(70); _sage_const_4 = Integer(4)# cycle 8 / T2: N=3 カイラル Potts の λ 記号スペクトルから運動量 cosθ_k を抽出。
# charpoly(x) over ℚ(ω)[λ] を因数分解。deg2(x) 因子の判別式 = A(1+λ^2-2λcosθ) → cosθ。
# 高次(deg 3,4,6) 因子は cubic 等の運動量を符号化(cycle6/7 の説明)。

K = CyclotomicField(_sage_const_3 , names=('om',)); (om,) = K._first_ngens(1); n=_sage_const_3 
Rl = K['lam']; (lam,) = Rl._first_ngens(1)
Z=matrix(K,[[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,om,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,om**_sage_const_2 ]])
X=matrix(K,[[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
I3=identity_matrix(K,_sage_const_3 )
def emb(op,i,N):
    m=[op if k==i else I3 for k in range(N)]
    M=m[_sage_const_0 ]
    for k in range(_sage_const_1 ,N): M=M.tensor_product(m[k])
    return M
def H_lambda(N):
    c={a:(_sage_const_1 -om**(-a))**(-_sage_const_1 ) for a in [_sage_const_1 ,_sage_const_2 ]}
    Zi={i:emb(Z,i,N) for i in range(N)}; Xi={i:emb(X,i,N) for i in range(N)}
    H0=matrix(K,_sage_const_3 **N,_sage_const_3 **N); H1=matrix(K,_sage_const_3 **N,_sage_const_3 **N)
    for j in range(N):
        jp=(j+_sage_const_1 )%N
        for a in [_sage_const_1 ,_sage_const_2 ]:
            H0 += -c[a]*Xi[j]**a
            H1 += -c[a]*Zi[j]**a*Zi[jp]**(n-a)
    return H0.change_ring(Rl)+lam*H1.change_ring(Rl)

N=_sage_const_3 
print("="*_sage_const_70 ); print(f"カイラル Potts N={N}: λ 記号スペクトルと運動量 cosθ_k"); print("="*_sage_const_70 )
H=H_lambda(N)
S = Rl['x']; (x,) = S._first_ngens(1)
cp=H.charpoly(x)
print("因数分解中(27次, 時間がかかる場合あり)...")
fac=cp.factor()
degcount={}
cosset=[]
for g,mult in fac:
    d=g.degree()
    degcount[d]=degcount.get(d,_sage_const_0 )+mult
    if d==_sage_const_2 :
        co=g.list(); a2,b1,c0=co[_sage_const_2 ],co[_sage_const_1 ],co[_sage_const_0 ]
        disc=Rl((b1**_sage_const_2 -_sage_const_4 *a2*c0)/a2**_sage_const_2 )
        cl=disc.list()
        if len(cl)==_sage_const_3  and cl[_sage_const_2 ]!=_sage_const_0  and cl[_sage_const_0 ]/cl[_sage_const_2 ]==_sage_const_1 :
            costh=-(cl[_sage_const_1 ]/cl[_sage_const_2 ])/_sage_const_2 
            cosset.append(costh)
            print(f"  deg2(x) x{mult}: disc={disc} → 1+λ²-2λ·({costh}),  cosθ={costh}")
        else:
            print(f"  deg2(x) x{mult}: disc={disc} (Onsager 型でない or 定数項≠λ²係数)")
    else:
        print(f"  deg{d}(x) x{mult}: 高次因子(cubic 等の運動量を符号化)")

print(f"\n  因子次数分布(x について): {degcount}")
print(f"  抽出された cosθ_k(deg2 由来): {sorted(set(cosset))}")
print("\n"+"="*_sage_const_70 )
print("読み: deg2 因子から cosθ を直接抽出。高次因子は cosθ が cubic 等(非2冪次数の由来)。")
print(" N とともに cosθ_k が [-1,1] を稠密化 → 連続分散 ε(θ)=√(1+λ²-2λcosθ)(ℝ脱出一点)。")
print("="*_sage_const_70 )

