# 対象ラベル: claim_one_sided_parallel_return_repetition
import os
import sys
check_directory = os.path.dirname(os.path.abspath(sys.argv[0]))
load(os.path.join(check_directory, 'check_inside_substitute_index.sage'))
load(os.path.join(check_directory, 'check_inside_reassociate.sage'))
load(os.path.join(check_directory, 'check_inside_quotient.sage'))
load(os.path.join(check_directory, 'check_inside_remainder.sage'))
load(os.path.join(check_directory, 'check_inside_expand.sage'))
load(os.path.join(check_directory, 'check_inside_cancel.sage'))
load(os.path.join(check_directory, 'check_inside_negate.sage'))
load(os.path.join(check_directory, 'check_inside_step.sage'))
load(os.path.join(check_directory, 'check_seam_substitute_index.sage'))
load(os.path.join(check_directory, 'check_seam_reassociate.sage'))
load(os.path.join(check_directory, 'check_seam_substitute_remainder.sage'))
load(os.path.join(check_directory, 'check_seam_factor.sage'))
load(os.path.join(check_directory, 'check_seam_quotient.sage'))
load(os.path.join(check_directory, 'check_seam_remainder.sage'))
load(os.path.join(check_directory, 'check_seam_expand.sage'))
load(os.path.join(check_directory, 'check_seam_zero.sage'))
load(os.path.join(check_directory, 'check_seam_collect.sage'))
load(os.path.join(check_directory, 'check_seam_coefficient.sage'))
load(os.path.join(check_directory, 'check_seam_negate.sage'))
load(os.path.join(check_directory, 'check_seam_endpoint.sage'))
load(os.path.join(check_directory, 'check_seam_last_index.sage'))
load(os.path.join(check_directory, 'check_seam_step.sage'))
load(os.path.join(check_directory, 'check_repetition.sage'))
