

# This file was *autogenerated* from the file check_01_bruteforce_vs_trace.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1en10 = RealNumber('1e-10'); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_1p3 = RealNumber('1.3'); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p7 = RealNumber('0.7'); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_1en6 = RealNumber('1e-6')# <partition_function_via_transfer_matrix>: Z(K_1,K_2) = tr((V_1 V_2)^{N_row})（数値）
# 左辺は全 2^{N_row M_col} 配位のブルートフォース、右辺は 2^{M_col} 次の転送行列（成分を ord で指す）。
# 完全に独立な 2 経路。K_1 と K_2 を入れ替えた転送行列では一致しないことも確かめる。
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
load(os.path.join(_dir, "_prelude.sage"))
rep = CheckReport("partition_function_via_transfer_matrix", tol=_sage_const_1en10 )
cases = [(_sage_const_2 ,_sage_const_2 ),(_sage_const_3 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_3 ),(_sage_const_4 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_4 ),(_sage_const_3 ,_sage_const_3 ),(_sage_const_4 ,_sage_const_3 ),(_sage_const_3 ,_sage_const_4 )]
for (N_row, M_col) in cases:
    for (K1, K2) in [(_sage_const_0p9 ,_sage_const_0p4 ),(_sage_const_0p4 ,_sage_const_0p9 ),(_sage_const_1p3 ,_sage_const_0p25 ),(_sage_const_0p7 ,_sage_const_0p7 )]:
        lhs = Z_bruteforce(K1, K2, N_row, M_col)
        V1, V2 = transfer_matrices(K1, K2, M_col)
        rhs = np.trace(np.linalg.matrix_power(V1 @ V2, N_row))
        rep.close(lhs, rhs, f"N_row={N_row} M_col={M_col} K_1={K1} K_2={K2}")
        if N_row != M_col and abs(K1 - K2) > _sage_const_1en9 :
            W1, W2 = transfer_matrices(K2, K1, M_col)
            wrong = np.trace(np.linalg.matrix_power(W1 @ W2, N_row))
            rep.truth(abs(wrong - lhs) > _sage_const_1en6  * abs(lhs),
                      f"N_row={N_row} M_col={M_col}: K_1 と K_2 を入れ替えると一致しない（割り当てが本質的）")
rep.finish()

