

# This file was *autogenerated* from the file check_03_JJprime_assignment.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0p3 = RealNumber('0.3'); _sage_const_0p7 = RealNumber('0.7'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_1p3 = RealNumber('1.3'); _sage_const_1p1 = RealNumber('1.1'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_0p9414 = RealNumber('0.9414'); _sage_const_1en3 = RealNumber('1e-3')# 252-03: J と J' の割り当ての訂正が正しいことの確認（反例探し）
#
# 本文 def_transfer_matrix の conversion.notes は、原文の割り当て
#   （V_1 の行内相互作用に J、V_2 の行間相互作用に J'）
# では M ≠ N のとき Z(J,J') と一致せず、Z(J',J) と一致してしまうので、
# V_1 に J'（行内、周期 N）、V_2 に J（行間、転送 M 回）と入れ替えて訂正した、と述べている。
#
# この主張そのものを検証する:
#   (a) 訂正後の割り当て … tr((V_1V_2)^M) = Z(J,J')
#   (b) 原文の割り当て   … tr((V_1V_2)^M) = Z(J',J)
#   (c) M ≠ N かつ J ≠ J' では Z(J,J') ≠ Z(J',J)（＝(a) と (b) は実際に区別できる）
# (c) が成り立たないパラメータでしか試していなければ、この check は無意味である。

import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '../../_shared/operators.sage'))
load(os.path.join(_dir, '_prelude.sage'))

rep = CheckReport("def_transfer_matrix: J/J' の割り当ての訂正（M≠N, J≠J' で識別可能）")

ASYM = [(_sage_const_2 , _sage_const_3 ), (_sage_const_3 , _sage_const_2 ), (_sage_const_2 , _sage_const_4 ), (_sage_const_4 , _sage_const_2 ), (_sage_const_3 , _sage_const_4 ), (_sage_const_4 , _sage_const_3 )]
for (M, N) in ASYM:
    for (J, Jp) in [(_sage_const_0p3 , _sage_const_0p7 ), (_sage_const_0p1 , _sage_const_1p3 ), (_sage_const_1p1 , _sage_const_0p05 ), (_sage_const_0p2 , _sage_const_0p9414 )]:
        Z = brute_force_Z(M, N, J, Jp)
        Zswap = brute_force_Z(M, N, Jp, J)
        tr_fixed = trace_transfer(M, N, J, Jp)          # 訂正後: V_1←J', V_2←J
        tr_orig = trace_transfer(M, N, Jp, J)           # 原文の割り当て（J と J' を入れ替えたもの）

        rep.close(tr_fixed, Z, "(a) M=%d N=%d: 訂正後 tr = Z(J,J')" % (M, N))
        rep.close(tr_orig, Zswap, "(b) M=%d N=%d: 原文の割り当て tr = Z(J',J)" % (M, N))
        sep = abs(Z - Zswap) / max(abs(Z), abs(Zswap))
        rep.truth(sep > _sage_const_1en3 , "(c) M=%d N=%d J=%.3g J'=%.3g: Z(J,J') と Z(J',J) が実際に異なる"
                  % (M, N, J, Jp))
        print("  M=%d N=%d J=%.4g J'=%.4g : Z(J,J')=%.6e  Z(J',J)=%.6e  相対差=%.3f"
              % (M, N, J, Jp, Z, Zswap, sep))

rep.finish()

