

# This file was *autogenerated* from the file check_01_vector_bound.sage
from sage.all_cmdline import *   # import sage library

_sage_const_103 = Integer(103); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_30 = Integer(30); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_1en10 = RealNumber('1e-10')# <matrix_norm_vector_bound>: ||Aw|| <= ||A|| ||w||
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
rng = np.random.default_rng(int(_sage_const_103 ))
rep = CheckReport("matrix_norm_vector_bound")
def nrm(A):
    return float(np.sqrt(np.sum(np.abs(A)**_sage_const_2 )))
for n in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_8 ]:
    for _ in range(_sage_const_30 ):
        A = rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n))
        w = rng.normal(size=(n,)) + _sage_const_1j *rng.normal(size=(n,))
        rep.truth(nrm(A@w) <= nrm(A)*nrm(w) + _sage_const_1en10 , f"n={n}: ||Aw|| <= ||A|| ||w||")
    # 等号: A がランク1で w が A の行ベクトルに比例するとき
    v = rng.normal(size=(n,)) + _sage_const_1j *rng.normal(size=(n,))
    u = rng.normal(size=(n,)) + _sage_const_1j *rng.normal(size=(n,))
    A = np.outer(u, v.conj())
    w = v
    rep.close(nrm(A@w), nrm(A)*nrm(w), f"n={n}: ランク1で等号")
rep.finish()

