/**
 * 論文本体 第 4 章: Λ 側の有限・初等・決定可能な命題群（命題 A・B・C・N・L）。
 *
 * すべて ℝ を使わず、有限手続きで決定できる。数学的内容は既知の初等整数論であり、
 * 本論文の寄与は「可積分模型の Massieu 自由エントロピーへの適用と、決定手続きの明示」に限られる。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_040_heading_lambda",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/004_lambda_finite.ts", ordinal: 1 },
    title: { text: "Λ 側の有限・決定可能な顔 — 命題 A・B・C・N・L" },
    labels: [],
  },
  {
    id: "paper_041_theorem_periodicity",
    kind: "theorem",
    origin: { path: "structured-latex/content/004_lambda_finite.ts", ordinal: 2 },
    title: { text: "命題 A（v_p の最終周期性）" },
    labels: ["paper_prop_A"],
    habitat: "Z",
    verification: ["sagemath/check/cycle3_T1_period_bound", "sagemath/check/D-U2_padic_law"],
    lean: [
      "IntegrableLattice.exists_eventually_periodic_pow",
      "IntegrableLattice.exists_eventually_periodic_matrixPow",
      "IntegrableLattice.exists_eventually_periodic_trace",
      "IntegrableLattice.exists_eventually_periodic_truncVal",
      "IntegrableLattice.exists_eventually_periodic_min_padicValInt",
    ],
    statement: [
      paragraph([
        math(String.raw`T\in M_d(\mathbb{Z})`),
        "、",
        math(String.raw`Z_N:=\operatorname{Tr}T^N`),
        "、",
        math(String.raw`p`),
        " を ",
        math(String.raw`p\nmid\det T`),
        " なる素数とする。任意の切断 ",
        math(String.raw`k\ge1`),
        " に対し ",
        math(String.raw`\min\bigl(v_p(Z_N),k\bigr)`),
        " は ",
        math(String.raw`N`),
        " について**最終周期的**であり、その周期は ",
        math(String.raw`T^N\bmod p^k`),
        " の最終周期 ",
        math(String.raw`\pi(p,k)`),
        " を割る。",
      ]),
      paragraph([
        math(String.raw`\pi(p,k)`),
        " は有限モノイド ",
        math(String.raw`M_d(\mathbb{Z}/p^k)`),
        " の上で**決定可能**である（元を順に生成して最初の再訪を見つければよい）。",
      ]),
      paragraph([
        "**記号の注意（2 つの周期を混同しないこと）**: ",
        math(String.raw`\pi(p,k)`),
        " は**行列冪列**の周期であり、",
        ref("paper_prop_B"),
        " の ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)`),
        "（**トレース列**の周期）とは別の量である。",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)\mid\pi(p,k)`),
        " は成り立つが**逆は成り立たない**（比が ",
        math(String.raw`1`),
        " でない例が実際にある）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`T\bmod p^k`),
        " は有限集合 ",
        math(String.raw`M_d(\mathbb{Z}/p^k)`),
        " の元なので、列 ",
        math(String.raw`(T^N\bmod p^k)_{N\ge0}`),
        " は鳩の巣原理により最終周期的である。",
        math(String.raw`Z_N\bmod p^k`),
        " はこの列のトレースなので同じ周期で最終周期的になり、",
        math(String.raw`\min(v_p(Z_N),k)`),
        " は ",
        math(String.raw`Z_N\bmod p^k`),
        " から決まる。",
      ]),
      paragraph([
        "**注**: 使ったのは有限集合上の鳩の巣だけで、",
        math(String.raw`\mathbb{Q}_p`),
        " も解析も使わない。この主張は既知の線形漸化列の ",
        math(String.raw`p`),
        " 進解析の言い換えである。",
      ]),
    ],
  },
  {
    id: "paper_042_theorem_pi_p1",
    kind: "theorem",
    origin: { path: "structured-latex/content/004_lambda_finite.ts", ordinal: 3 },
    title: { text: "命題 B（トレース列の周期 π_tr(p,1) の精密公式）" },
    labels: ["paper_prop_B"],
    habitat: "Z",
    verification: ["sagemath/check/cycle3_T3_period"],
    lean: [
      "IntegrableLattice.expSum_eventually_periodic_iff_lcm_dvd",
      "IntegrableLattice.isLeast_period_expSum",
      "IntegrableLattice.trace_pow_eq_sum_maxGenEigenspace",
      "IntegrableLattice.trace_pow_eventually_periodic_iff",
    ],
    statement: [
      paragraph([
        math(String.raw`\pi_{\mathrm{tr}}(p,1)`),
        " を**トレース列** ",
        math(String.raw`Z_N=\mathrm{Tr}\,T^N\bmod p`),
        " の最終周期とすると",
      ]),
      displayMath(
        String.raw`\pi_{\mathrm{tr}}(p,1)=\operatorname{lcm}\bigl\{\operatorname{ord}(\lambda)\ :\ \lambda\in\overline{\mathbb{F}_p}^{\times}\ \text{は }\chi_T\bmod p\text{ の相異なる根},\ p\nmid m_\lambda\bigr\}`,
      ),
      paragraph([
        "が成り立つ。ここで ",
        math(String.raw`m_\lambda`),
        " は ",
        math(String.raw`\lambda`),
        " の代数的重複度である。",
      ]),
      paragraph([
        "**【訂正】この主張は ",
        ref("paper_prop_A"),
        " の ",
        math(String.raw`\pi(p,1)`),
        "（＝**行列冪列** ",
        math(String.raw`T^N\bmod p^k`),
        " の最終周期）についての主張では**ない**。**",
        "本論文の以前の版は 2 つの量を同じ記号で書いており、**その読みでは主張は偽であった**。",
        "反例: ",
        math(String.raw`T=\begin{pmatrix}0&1\\1&1\end{pmatrix}^{\oplus2}`),
        "、",
        math(String.raw`p=2`),
        " では行列冪列の周期は ",
        math(String.raw`3`),
        " だがトレース列は恒等的に ",
        math(String.raw`0`),
        " で周期 ",
        math(String.raw`1`),
        "、右辺も ",
        math(String.raw`1`),
        " である（重複度がともに ",
        math(String.raw`2`),
        " なので集合が空）。",
        "**この ",
        math(String.raw`T`),
        " は半単純なので、半単純性を仮定しても救済できない。** ",
        "無作為標本 2487 例中 563 例（22.6%）で 2 つの周期は食い違う。",
      ]),
    ],
    proof: [
      paragraph([
        "**両方向を証明する。** まず一般化固有空間分解から ",
        math(String.raw`\overline{\mathbb{F}_p}`),
        " 上で ",
        math(String.raw`Z_N=\sum_\lambda m_\lambda\lambda^N`),
        " が成り立つ（標数 ",
        math(String.raw`p`),
        " では ",
        math(String.raw`m_\lambda\not\equiv0`),
        " が ",
        math(String.raw`p\nmid m_\lambda`),
        " と一致する）。",
      ]),
      paragraph([
        "指数函数 ",
        math(String.raw`N\mapsto\lambda^N`),
        " たちは相異なる ",
        math(String.raw`\lambda`),
        " について一次独立（Artin の指標の一次独立性）なので、",
        math(String.raw`t`),
        " が ",
        math(String.raw`Z_N`),
        " の最終周期であることと、",
        math(String.raw`p\nmid m_\lambda`),
        " なるすべての ",
        math(String.raw`\lambda`),
        " について ",
        math(String.raw`\operatorname{ord}(\lambda)\mid t`),
        " であることが**同値**である。よって最小の ",
        math(String.raw`t`),
        " は上式の最小公倍数に等しい。",
        math(String.raw`p\mid m_\lambda`),
        " の項は ",
        math(String.raw`\bmod p`),
        " で消えるので寄与しない。",
      ]),
      paragraph([
        "**この命題は Lean で形式化した**（代数閉体上、仮定なしの完成形）。",
        "根拠レポートは ",
        math(String.raw`\texttt{outputs/reports/cycle17\_ops\_lean\_propB.md}`),
        "。",
      ]),
    ],
  },
  {
    id: "paper_043_theorem_bound",
    kind: "theorem",
    origin: { path: "structured-latex/content/004_lambda_finite.ts", ordinal: 4 },
    title: { text: "命題 C（周期の上界。Wall 型の等号は一般に成立しない）" },
    labels: ["paper_prop_C"],
    habitat: "Z",
    verification: ["sagemath/check/cycle3_T3_period"],
    // 形式化は**部分的**。代数的核（U ≡ I mod p ⇒ U^{p^{k-1}} = I）までを Lean で証明した。
    // π(p,k) を最終周期の最小値として定義して結論する段は未整備（lean/README.md の表を参照）。
    lean: [
      "IntegrableLattice.dvd_one_add_pow_prime_sub_one",
      "IntegrableLattice.dvd_pow_prime_pow_sub_one",
      "IntegrableLattice.pow_prime_pow_eq_one_of_eq_one_add",
      "IntegrableLattice.matrix_pow_prime_pow_eq_one",
    ],
    statement: [
      paragraph([
        math(String.raw`\pi(p,k)\ \bigm|\ p^{k-1}\pi(p,1)`),
        " が成り立つ（Pisano 型の上界。**既知**）。ここで ",
        math(String.raw`\pi`),
        " は ",
        ref("paper_prop_A"),
        " と同じく**行列冪列** ",
        math(String.raw`T^N\bmod p^k`),
        " の最終周期である。",
      ]),
      paragraph([
        "**読みを ",
        ref("paper_prop_B"),
        " のトレース列 ",
        math(String.raw`\pi_{\mathrm{tr}}`),
        " に変えると、この上界は偽になる**（1669 例中 56 例＝3.4% で破れる）。",
        "2 つの周期は別の量であり、同じ記号を共有できない。",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)`),
        "（",
        math(String.raw`k\ge2`),
        "）に対する正しい上界は ",
        ref("paper_prop_C_trace"),
        " で与える。",
      ]),
      paragraph([
        "**等号（Wall 型）は一般には成立しない。** 本論文の検証では、",
        "非退化な companion 行列 472 例中 10 例（約 2.1%）で等号が破れ、",
        "六頂点模型の転送行列 572 例中 26 例（約 4.5%）で破れた。",
      ]),
    ],
    proof: [
      paragraph([
        "上界は ",
        math(String.raw`T^{\pi(p,1)}\equiv I+pS`),
        " と書いて ",
        math(String.raw`p^{k-1}`),
        " 乗すれば従う（既知）。等号が破れることは上記の反例が示す。",
      ]),
      paragraph([
        "**方法論上の注記（本論文が明示する教訓）**: 本研究では当初、",
        "43 例の探索で反例が 0 件だったことから「可積分性が Wall 型等号を保護する」という仮説を立てた。",
        "しかし 0 件は仮説の支持根拠にならない。標本を 572 例へ桁で拡大したところ 4.5% の反例が現れ、",
        "**仮説は棄却された**。0 件の観察を根拠にしてはならない。",
      ]),
    ],
  },
  {
    id: "paper_043b_theorem_trace_bound",
    kind: "theorem",
    origin: { path: "structured-latex/content/004_lambda_finite.ts", ordinal: 5 },
    title: { text: "命題 C′（トレース列の周期の上界。命題 C のトレース列版）" },
    labels: ["paper_prop_C_trace"],
    habitat: "Z",
    verification: ["sagemath/check/cycle18_T3_trace_period"],
    statement: [
      paragraph([
        math(String.raw`\chi_T=\prod_i f_i^{a_i}`),
        " を ",
        math(String.raw`\mathbb{Z}[x]`),
        " での既約分解、",
        math(String.raw`\rho=\prod_i f_i`),
        "（根基）、",
        math(String.raw`r=\deg\rho`),
        " とし、Gram 行列 ",
        math(String.raw`G=\bigl(\operatorname{Tr}T^{i+j}\bigr)_{0\le i,j<r}\in M_r(\mathbb{Z})`),
        " の最大単因子（Smith 標準形の最後の対角成分）を ",
        math(String.raw`e_r`),
        "、",
        math(String.raw`w^*=v_p(e_r)`),
        " とおく。このとき",
      ]),
      displayMath(
        String.raw`\pi_{\mathrm{tr}}(p,k)\ \bigm|\ p^{\,k-1}\,\pi_{\mathrm{tr}}(p,\,w^*+1)\qquad(k\ge1).`,
      ),
      paragraph([
        "さらに ",
        math(String.raw`\det G=\operatorname{disc}(\rho)\cdot\prod_\lambda m_\lambda\neq0`),
        " であり、",
        math(String.raw`w^*=0`),
        " は「",
        math(String.raw`\rho\bmod p`),
        " が分離的、かつ全ての重複度で ",
        math(String.raw`p\nmid m_\lambda`),
        "」と同値である（後半は ",
        ref("paper_prop_B"),
        " の条件そのもの）。",
        math(String.raw`w^*=0`),
        " のとき上界は ",
        ref("paper_prop_C"),
        " と同じ形 ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)\mid p^{k-1}\pi_{\mathrm{tr}}(p,1)`),
        " になる。",
      ]),
      paragraph([
        "**基準レベルを ",
        math(String.raw`1`),
        " のままにした補正は不可能である。** ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)\mid p^{a}\pi_{\mathrm{tr}}(p,1)`),
        " は ",
        math(String.raw`a`),
        " をどう取っても偽で、",
        math(String.raw`T=F\oplus F`),
        "（",
        math(String.raw`F=\begin{pmatrix}0&1\\1&1\end{pmatrix}`),
        "）、",
        math(String.raw`p=2`),
        " が反例である（",
        math(String.raw`\pi_{\mathrm{tr}}(2,1)=1`),
        " だが ",
        math(String.raw`\pi_{\mathrm{tr}}(2,2)=3`),
        "）。直すべきは指数ではなく基準レベルである。",
      ]),
      paragraph([
        "**決定可能性**: ",
        math(String.raw`w^*`),
        " は整数行列 ",
        math(String.raw`G`),
        " の Smith 標準形から有限手続きで決まり、",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)`),
        " 自身も有限環 ",
        math(String.raw`M_d(\mathbb{Z}/p^k)`),
        " 上の探索で決まる。証明は整数行列上の線形代数（Cramer 則・Smith 標準形）と",
        "代数的数の Vandermonde だけで閉じており、非可算な体（実数体・複素数体・",
        math(String.raw`p`),
        " 進整数環）へは一度も脱出しない。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`S=\bigoplus_i C_{f_i}^{\oplus a_i}`),
        "（",
        math(String.raw`C_f`),
        " は同伴行列）とおくと ",
        math(String.raw`\chi_S=\chi_T`),
        " なので Newton の公式より ",
        math(String.raw`\operatorname{Tr}S^N=\operatorname{Tr}T^N`),
        "（全 ",
        math(String.raw`N`),
        "）、また ",
        math(String.raw`\mathrm{minpoly}(S)=\rho`),
        "。",
      ]),
      paragraph([
        math(String.raw`t=\pi_{\mathrm{tr}}(p,k)`),
        "、",
        math(String.raw`B=S^t-I\in\mathbb{Z}[S]=\bigoplus_{j<r}\mathbb{Z}S^j`),
        " と書く。周期性より全ての ",
        math(String.raw`N`),
        " で ",
        math(String.raw`\operatorname{Tr}(S^NB)\equiv0\ (p^k)`),
        " であり、",
        math(String.raw`N=0,\dots,r-1`),
        " を取ると係数ベクトル ",
        math(String.raw`b\in\mathbb{Z}^r`),
        " について ",
        math(String.raw`Gb\equiv0\ (p^k)`),
        "。",
        math(String.raw`p^{w^*}G^{-1}`),
        " は ",
        math(String.raw`p`),
        " 進整数成分をもつので ",
        math(String.raw`b\equiv0\ (p^{k-w^*})`),
        "、すなわち ",
        math(String.raw`k>w^*`),
        " なら ",
        math(String.raw`\pi(p,k-w^*;S)\mid t`),
        "。",
      ]),
      paragraph([
        "これを ",
        math(String.raw`k=w^*+1`),
        " に使うと ",
        math(String.raw`\pi(p,1;S)\mid\pi_{\mathrm{tr}}(p,w^*+1)`),
        "。よって ",
        ref("paper_prop_C"),
        " の行列冪列版と合わせて ",
        math(
          String.raw`\pi_{\mathrm{tr}}(p,k)\mid\pi(p,k;S)\mid p^{k-1}\pi(p,1;S)\mid p^{k-1}\pi_{\mathrm{tr}}(p,w^*+1)`,
        ),
        "（",
        math(String.raw`k\le w^*+1`),
        " では単調性 ",
        math(String.raw`\pi_{\mathrm{tr}}(p,k)\mid\pi_{\mathrm{tr}}(p,k+1)`),
        " から従う）。",
        math(String.raw`\det G`),
        " の公式は ",
        math(String.raw`G=V\,\mathrm{diag}(m_\lambda)\,V^{\mathsf T}`),
        "（",
        math(String.raw`V`),
        " は相異なる根の Vandermonde）から従う。",
      ]),
      paragraph([
        "反例は ",
        math(String.raw`\operatorname{Tr}T^N=2L_N`),
        "（Lucas 数）から: ",
        math(String.raw`\bmod2`),
        " で恒等的に ",
        math(String.raw`0`),
        "、",
        math(String.raw`\bmod4`),
        " では ",
        math(String.raw`L_N\bmod2`),
        " の最小周期 ",
        math(String.raw`3`),
        " が現れる。詳細は ",
        math(String.raw`\texttt{outputs/reports/cycle18\_T3\_trace\_period\_bound.md}`),
        "。",
      ]),
    ],
  },
  {
    id: "paper_044_theorem_newton",
    kind: "theorem",
    origin: { path: "structured-latex/content/004_lambda_finite.ts", ordinal: 5 },
    title: { text: "命題 N（線形成長率は Newton 多角形で決まる）" },
    labels: ["paper_prop_N"],
    habitat: "Z",
    verification: ["sagemath/check/D-U2_padic_law"],
    statement: [
      paragraph([
        math(String.raw`v_p(Z_N)`),
        " の ",
        math(String.raw`N`),
        " 線形成長率は",
      ]),
      displayMath(String.raw`\mu_{\min}(p)=\min_i v_p(\lambda_i)`),
      paragraph([
        "に等しく、これは特性多項式 ",
        math(String.raw`\chi_T`),
        " の ",
        math(String.raw`p`),
        " 進 Newton 多角形の**最小傾き**として決まる。",
      ]),
      paragraph([
        "**決定可能性**: Newton 多角形は係数の ",
        math(String.raw`p`),
        " 進付値（整数）の点集合の下方凸包であり、有限組合せ的に求まる。",
        "**固有値を個別に構成する必要も ",
        math(String.raw`\mathbb{Q}_p`),
        " を構成する必要もない。**",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`Z_N=\sum_i\lambda_i^N`),
        " において最小付値の固有値が支配的になることによる（既知の Newton 多角形の議論）。",
        "**ただし Skolem–Mahler–Lech 型の相殺により、有限個の ",
        math(String.raw`N`),
        " で例外が生じうる。** 本論文の検証でも 1 例",
        "（六頂点 ",
        math(String.raw`(1,1,1)`),
        ", ",
        math(String.raw`L=2`),
        ", ",
        math(String.raw`p=7`),
        "）で周期検出が失敗した。この caveat を落として一般則として述べてはならない。",
      ]),
    ],
  },
  {
    id: "paper_045_theorem_lte",
    kind: "theorem",
    origin: { path: "structured-latex/content/004_lambda_finite.ts", ordinal: 6 },
    title: { text: "命題 L（1 変数最小例の完全形。LTE）" },
    labels: ["paper_prop_L"],
    habitat: "Z",
    verification: ["sagemath/check/cycle7_T1_lte"],
    lean: [
      "IntegrableLattice.padicValNat_pow_sub_one_of_dvd",
      "IntegrableLattice.padicValNat_pow_sub_one_of_not_dvd_order",
      "IntegrableLattice.padicValNat_pow_sub_one_odd",
      "IntegrableLattice.padicValNat_two_pow_sub_one_odd_exp",
      "IntegrableLattice.padicValNat_two_pow_sub_one_even_exp",
    ],
    statement: [
      paragraph([
        math(String.raw`P(z)=z-c`),
        "（",
        math(String.raw`c\in\mathbb{Z}_{\ge2}`),
        "）のとき ",
        math(String.raw`|a_L|=c^L-1`),
        " である。この場合の ",
        math(String.raw`v_p`),
        " は完全に決まる。",
      ]),
      list([
        [
          "**奇素数 ",
          math(String.raw`p`),
          "、",
          math(String.raw`p\nmid c`),
          "、",
          math(String.raw`d=\operatorname{ord}_p(c)`),
          " のとき**: ",
          math(String.raw`d\mid L`),
          " なら ",
          math(String.raw`v_p(c^L-1)=v_p(c^d-1)+v_p(L)`),
          "、",
          math(String.raw`d\nmid L`),
          " なら ",
          math(String.raw`0`),
          "。",
        ],
        [
          "**",
          math(String.raw`p=2`),
          "、",
          math(String.raw`c`),
          " 奇のとき**: ",
          math(String.raw`L`),
          " 奇なら ",
          math(String.raw`v_2(c^L-1)=v_2(c-1)`),
          "、",
          math(String.raw`L`),
          " 偶なら ",
          math(String.raw`v_2(c-1)+v_2(c+1)+v_2(L)-1`),
          "。",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "lifting-the-exponent（LTE）の標準的な補題である（**既知**）。",
        math(String.raw`p`),
        " 奇の場合は ",
        math(String.raw`c^d\equiv1`),
        " と二項展開、",
        math(String.raw`p=2`),
        " の場合は ",
        math(String.raw`c^L-1=(c^{L/2}-1)(c^{L/2}+1)`),
        " の繰り返しによる。",
      ]),
      paragraph([
        "**この命題は Lean 4 + mathlib4 で形式化した**（第 8 章）。",
        "アルキメデス側は ",
        math(String.raw`\lim_L\frac1L\log|a_L|=\log c=m(z-c)`),
        " であり、両素点が同一の ",
        math(String.raw`P`),
        " について具体的に書ける最小例になっている。",
      ]),
    ],
  },
]);
