/**
 * 論文本体 第 4 章: Λ 側の有限・初等・決定可能な命題群（命題 A・B・C・N・L）。
 *
 * すべて ℝ を使わず、有限手続きで決定できる。数学的内容は既知の初等整数論であり、
 * 本論文の寄与は「可積分模型の Massieu 自由エントロピーへの適用と、決定手続きの明示」に限られる。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_040_heading_lambda",
    kind: "heading",
    level: 1,
    sourcePath: "structured-latex/content/004_lambda_finite.ts",
    sourceOrdinal: 1,
    title: { text: "Λ 側の有限・決定可能な顔 — 命題 A・B・C・N・L" },
    labels: [],
    conversion: { status: "added" },
  },
  {
    id: "paper_041_theorem_periodicity",
    kind: "theorem",
    sourcePath: "structured-latex/content/004_lambda_finite.ts",
    sourceOrdinal: 2,
    title: { text: "命題 A（v_p の最終周期性）" },
    labels: ["paper_prop_A"],
    habitat: "Z",
    verification: ["sagemath/check/cycle3_T1_period_bound", "sagemath/check/D-U2_padic_law"],
    lean: [
      "IntegrableLattice.exists_eventually_periodic_pow",
      "IntegrableLattice.exists_eventually_periodic_matrixPow",
      "IntegrableLattice.exists_eventually_periodic_trace",
      "IntegrableLattice.exists_eventually_periodic_truncVal",
      "IntegrableLattice.exists_eventually_periodic_min_padicValInt",
    ],
    statement: [
      paragraph([
        math(String.raw`T\in M_d(\mathbb{Z})`),
        "、",
        math(String.raw`Z_N:=\operatorname{Tr}T^N`),
        "、",
        math(String.raw`p`),
        " を ",
        math(String.raw`p\nmid\det T`),
        " なる素数とする。任意の切断 ",
        math(String.raw`k\ge1`),
        " に対し ",
        math(String.raw`\min\bigl(v_p(Z_N),k\bigr)`),
        " は ",
        math(String.raw`N`),
        " について**最終周期的**であり、その周期は ",
        math(String.raw`T^N\bmod p^k`),
        " の最終周期 ",
        math(String.raw`\pi(p,k)`),
        " を割る。",
      ]),
      paragraph([
        math(String.raw`\pi(p,k)`),
        " は有限モノイド ",
        math(String.raw`M_d(\mathbb{Z}/p^k)`),
        " の上で**決定可能**である（元を順に生成して最初の再訪を見つければよい）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`T\bmod p^k`),
        " は有限集合 ",
        math(String.raw`M_d(\mathbb{Z}/p^k)`),
        " の元なので、列 ",
        math(String.raw`(T^N\bmod p^k)_{N\ge0}`),
        " は鳩の巣原理により最終周期的である。",
        math(String.raw`Z_N\bmod p^k`),
        " はこの列のトレースなので同じ周期で最終周期的になり、",
        math(String.raw`\min(v_p(Z_N),k)`),
        " は ",
        math(String.raw`Z_N\bmod p^k`),
        " から決まる。",
      ]),
      paragraph([
        "**注**: 使ったのは有限集合上の鳩の巣だけで、",
        math(String.raw`\mathbb{Q}_p`),
        " も解析も使わない。この主張は既知の線形漸化列の ",
        math(String.raw`p`),
        " 進解析の言い換えである。",
      ]),
    ],
    conversion: { status: "added" },
  },
  {
    id: "paper_042_theorem_pi_p1",
    kind: "theorem",
    sourcePath: "structured-latex/content/004_lambda_finite.ts",
    sourceOrdinal: 3,
    title: { text: "命題 B（π(p,1) の精密公式）" },
    labels: ["paper_prop_B"],
    habitat: "Z",
    verification: ["sagemath/check/cycle3_T3_period"],
    statement: [
      paragraph([
        ref("paper_prop_A"),
        " の ",
        math(String.raw`\pi(p,1)`),
        " について",
      ]),
      displayMath(
        String.raw`\pi(p,1)=\operatorname{lcm}\bigl\{\operatorname{ord}(\lambda)\ :\ \lambda\in\overline{\mathbb{F}_p}^{\times}\ \text{は }\chi_T\bmod p\text{ の相異なる根},\ p\nmid m_\lambda\bigr\}`,
      ),
      paragraph([
        "が成り立つ。ここで ",
        math(String.raw`m_\lambda`),
        " は ",
        math(String.raw`\lambda`),
        " の代数的重複度である。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`\overline{\mathbb{F}_p}`),
        " 上で ",
        math(String.raw`Z_N\bmod p=\sum_\lambda m_\lambda\lambda^N`),
        " と書ける。指数函数 ",
        math(String.raw`N\mapsto\lambda^N`),
        " たちは相異なる ",
        math(String.raw`\lambda`),
        " について一次独立（Artin の指標の一次独立性）なので、",
        math(String.raw`Z_N\bmod p`),
        " の周期は ",
        math(String.raw`m_\lambda\not\equiv0`),
        " なる ",
        math(String.raw`\lambda`),
        " の位数の最小公倍数に等しい。",
        math(String.raw`p\mid m_\lambda`),
        " の項は ",
        math(String.raw`\bmod p`),
        " で消えるので寄与しない。",
      ]),
    ],
    conversion: { status: "added" },
  },
  {
    id: "paper_043_theorem_bound",
    kind: "theorem",
    sourcePath: "structured-latex/content/004_lambda_finite.ts",
    sourceOrdinal: 4,
    title: { text: "命題 C（周期の上界。Wall 型の等号は一般に成立しない）" },
    labels: ["paper_prop_C"],
    habitat: "Z",
    verification: ["sagemath/check/cycle3_T3_period"],
    // 形式化は**部分的**。代数的核（U ≡ I mod p ⇒ U^{p^{k-1}} = I）までを Lean で証明した。
    // π(p,k) を最終周期の最小値として定義して結論する段は未整備（lean/README.md の表を参照）。
    lean: [
      "IntegrableLattice.dvd_one_add_pow_prime_sub_one",
      "IntegrableLattice.dvd_pow_prime_pow_sub_one",
      "IntegrableLattice.pow_prime_pow_eq_one_of_eq_one_add",
      "IntegrableLattice.matrix_pow_prime_pow_eq_one",
    ],
    statement: [
      paragraph([
        math(String.raw`\pi(p,k)\ \bigm|\ p^{k-1}\pi(p,1)`),
        " が成り立つ（Pisano 型の上界。**既知**）。",
      ]),
      paragraph([
        "**等号（Wall 型）は一般には成立しない。** 本論文の検証では、",
        "非退化な companion 行列 472 例中 10 例（約 2.1%）で等号が破れ、",
        "六頂点模型の転送行列 572 例中 26 例（約 4.5%）で破れた。",
      ]),
    ],
    proof: [
      paragraph([
        "上界は ",
        math(String.raw`T^{\pi(p,1)}\equiv I+pS`),
        " と書いて ",
        math(String.raw`p^{k-1}`),
        " 乗すれば従う（既知）。等号が破れることは上記の反例が示す。",
      ]),
      paragraph([
        "**方法論上の注記（本論文が明示する教訓）**: 本研究では当初、",
        "43 例の探索で反例が 0 件だったことから「可積分性が Wall 型等号を保護する」という仮説を立てた。",
        "しかし 0 件は仮説の支持根拠にならない。標本を 572 例へ桁で拡大したところ 4.5% の反例が現れ、",
        "**仮説は棄却された**。0 件の観察を根拠にしてはならない。",
      ]),
    ],
    conversion: { status: "added" },
  },
  {
    id: "paper_044_theorem_newton",
    kind: "theorem",
    sourcePath: "structured-latex/content/004_lambda_finite.ts",
    sourceOrdinal: 5,
    title: { text: "命題 N（線形成長率は Newton 多角形で決まる）" },
    labels: ["paper_prop_N"],
    habitat: "Z",
    verification: ["sagemath/check/D-U2_padic_law"],
    statement: [
      paragraph([
        math(String.raw`v_p(Z_N)`),
        " の ",
        math(String.raw`N`),
        " 線形成長率は",
      ]),
      displayMath(String.raw`\mu_{\min}(p)=\min_i v_p(\lambda_i)`),
      paragraph([
        "に等しく、これは特性多項式 ",
        math(String.raw`\chi_T`),
        " の ",
        math(String.raw`p`),
        " 進 Newton 多角形の**最小傾き**として決まる。",
      ]),
      paragraph([
        "**決定可能性**: Newton 多角形は係数の ",
        math(String.raw`p`),
        " 進付値（整数）の点集合の下方凸包であり、有限組合せ的に求まる。",
        "**固有値を個別に構成する必要も ",
        math(String.raw`\mathbb{Q}_p`),
        " を構成する必要もない。**",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`Z_N=\sum_i\lambda_i^N`),
        " において最小付値の固有値が支配的になることによる（既知の Newton 多角形の議論）。",
        "**ただし Skolem–Mahler–Lech 型の相殺により、有限個の ",
        math(String.raw`N`),
        " で例外が生じうる。** 本論文の検証でも 1 例",
        "（六頂点 ",
        math(String.raw`(1,1,1)`),
        ", ",
        math(String.raw`L=2`),
        ", ",
        math(String.raw`p=7`),
        "）で周期検出が失敗した。この caveat を落として一般則として述べてはならない。",
      ]),
    ],
    conversion: { status: "added" },
  },
  {
    id: "paper_045_theorem_lte",
    kind: "theorem",
    sourcePath: "structured-latex/content/004_lambda_finite.ts",
    sourceOrdinal: 6,
    title: { text: "命題 L（1 変数最小例の完全形。LTE）" },
    labels: ["paper_prop_L"],
    habitat: "Z",
    verification: ["sagemath/check/cycle7_T1_lte"],
    lean: [
      "IntegrableLattice.padicValNat_pow_sub_one_of_dvd",
      "IntegrableLattice.padicValNat_pow_sub_one_of_not_dvd_order",
      "IntegrableLattice.padicValNat_pow_sub_one_odd",
      "IntegrableLattice.padicValNat_two_pow_sub_one_odd_exp",
      "IntegrableLattice.padicValNat_two_pow_sub_one_even_exp",
    ],
    statement: [
      paragraph([
        math(String.raw`P(z)=z-c`),
        "（",
        math(String.raw`c\in\mathbb{Z}_{\ge2}`),
        "）のとき ",
        math(String.raw`|a_L|=c^L-1`),
        " である。この場合の ",
        math(String.raw`v_p`),
        " は完全に決まる。",
      ]),
      list([
        [
          "**奇素数 ",
          math(String.raw`p`),
          "、",
          math(String.raw`p\nmid c`),
          "、",
          math(String.raw`d=\operatorname{ord}_p(c)`),
          " のとき**: ",
          math(String.raw`d\mid L`),
          " なら ",
          math(String.raw`v_p(c^L-1)=v_p(c^d-1)+v_p(L)`),
          "、",
          math(String.raw`d\nmid L`),
          " なら ",
          math(String.raw`0`),
          "。",
        ],
        [
          "**",
          math(String.raw`p=2`),
          "、",
          math(String.raw`c`),
          " 奇のとき**: ",
          math(String.raw`L`),
          " 奇なら ",
          math(String.raw`v_2(c^L-1)=v_2(c-1)`),
          "、",
          math(String.raw`L`),
          " 偶なら ",
          math(String.raw`v_2(c-1)+v_2(c+1)+v_2(L)-1`),
          "。",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "lifting-the-exponent（LTE）の標準的な補題である（**既知**）。",
        math(String.raw`p`),
        " 奇の場合は ",
        math(String.raw`c^d\equiv1`),
        " と二項展開、",
        math(String.raw`p=2`),
        " の場合は ",
        math(String.raw`c^L-1=(c^{L/2}-1)(c^{L/2}+1)`),
        " の繰り返しによる。",
      ]),
      paragraph([
        "**この命題は Lean 4 + mathlib4 で形式化した**（第 8 章）。",
        "アルキメデス側は ",
        math(String.raw`\lim_L\frac1L\log|a_L|=\log c=m(z-c)`),
        " であり、両素点が同一の ",
        math(String.raw`P`),
        " について具体的に書ける最小例になっている。",
      ]),
    ],
    conversion: { status: "added" },
  },
]);
