/**
 * 論文本体 第 5 章: 中核命題 D（二素点の双対）。
 *
 * (∞) 側は既知（第 3 章）、(p) 側は Monsky / Cuoco–Monsky の定理の適用である。
 * 本論文の寄与は対応を明示したことに限られ、定理そのものは既知である。
 * 明示された限界 3 点を命題の一部として述べる。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_050_heading_duality",
    kind: "heading",
    level: 1,
    sourcePath: "structured-latex/content/005_duality.ts",
    sourceOrdinal: 1,
    title: { text: "中核命題 D — 同一の整数曲線の二素点" },
    labels: [],
    conversion: { status: "added" },
  },
  {
    id: "paper_051_theorem_duality",
    kind: "theorem",
    sourcePath: "structured-latex/content/005_duality.ts",
    sourceOrdinal: 2,
    title: { text: "双対命題 D" },
    labels: ["paper_prop_D"],
    habitat: "mixed",
    realEscape:
      "本命題は (∞ 素点) の主張で L → ∞ の極限を取る。ℝ を使うのはこの一点だけであり、" +
      "(p 素点) の 2 つの主張はいずれも Z・Q の中で閉じる。",
    verification: [
      "sagemath/check/cycle5_T1_mahler",
      "sagemath/check/cycle9_T1_spanning_tree",
      "sagemath/check/cycle15_T1_monsky_shape",
      "sagemath/check/cycle6_T1_padic_mahler",
    ],
    statement: [
      paragraph([
        ref("paper_def_curve"),
        " の設定で ",
        math(String.raw`P\neq0`),
        " とし、",
        math(String.raw`\mathsf U(P)`),
        " を複素単位トーラス上の零点集合とする。",
      ]),
      paragraph([
        "**(∞ 素点)** ",
        math(String.raw`\dim\mathsf U(P)\le d-2`),
        "（atoral）ならば",
      ]),
      displayMath(
        String.raw`\frac{1}{L^{d}}\log\bigl|a^{\mathrm{red}}_L\bigr|\ \longrightarrow\ \log m(P)\qquad(L\to\infty).`,
      ),
      paragraph([
        "根拠は ",
        ref("paper_thm_archimedean"),
        "（Lind–Schmidt–Ward Thm 3.1 / 7.1、Lind–Schmidt–Verbitskiy Thm 1.2 / 1.3）。",
      ]),
      paragraph([
        "**(p 素点, 有限 L)** 任意の素数 ",
        math(String.raw`p`),
        " と任意の ",
        math(String.raw`L`),
        " について ",
        math(String.raw`v_p(a^{\mathrm{red}}_L)\in\mathbb{Z}_{\ge0}`),
        " は ",
        math(String.raw`\mathbb{Z}`),
        " 上の有限手続きで計算できる（",
        ref("paper_claim_resultant"),
        "）。さらに ",
        math(String.raw`L=p^n`),
        " の塔では非自明性が完全に判定できる（",
        ref("paper_prop_V"),
        "）。",
      ]),
      paragraph([
        "**(p 素点, 塔の漸近)** ",
        math(String.raw`\Gamma\simeq\mathbb{Z}_p^d`),
        "、",
        math(String.raw`f:=P(\sigma_1,\dots,\sigma_d)\in\mathbb{Z}_p[\Gamma]`),
        "（Serre 同型 ",
        math(String.raw`\sigma_i\mapsto1+T_i`),
        "）とすると",
      ]),
      displayMath(
        String.raw`v_p\bigl(a^{\mathrm{red}}_{p^n}\bigr)=\sum_{\substack{\chi\in\widehat{\Gamma_n}\\ \chi(f)\neq0}}\mathrm{ord}_p(\chi(f)),`,
      ),
      paragraph([
        "したがって有理数 ",
        math(String.raw`\lambda_i,\mu_i,\nu`),
        " が存在して ",
        math(String.raw`n\gg0`),
        " で",
      ]),
      displayMath(
        String.raw`v_p\bigl(a^{\mathrm{red}}_{p^n}\bigr)=\bigl(\lambda n+\mu p^n\bigr)p^{(d-1)n}
+\sum_{i=1}^{d-1}\bigl(\lambda_i n+\mu_i p^n\bigr)p^{(d-1-i)n}+\nu,`,
      ),
      displayMath(
        String.raw`\lambda=l_0(f),\qquad \mu=m_0(f)=v_p\bigl(\mathrm{content}\,P\bigr)\in\mathbb{Z}_{\ge0}.`,
      ),
      paragraph([
        "**主要 2 係数はいずれも ",
        math(String.raw`\mathbb{Z}`),
        " 上の有限手続きで計算できる。** ",
        math(String.raw`\mu`),
        " は content の付値、",
        math(String.raw`\lambda`),
        " は ",
        ref("paper_prop_F"),
        " による。",
      ]),
    ],
    proof: [
      paragraph([
        "**(∞ 素点)**: ",
        ref("paper_thm_archimedean"),
        " の引用である。本論文は証明しない。",
      ]),
      paragraph([
        "**(p 素点, 塔の漸近)**: これは **Monsky の定理（Theorem 5.6）と Cuoco–Monsky の定理（Theorem 1.7）の適用**である。",
        "本論文は証明しない。両定理は Kataoka, arXiv:2606.03579 の Theorem 2.1 / Theorem 2.3 として引用されており、",
        "本論文はその本文（pp.1–8）で仮定と命題番号を確認した。",
      ]),
      paragraph([
        "**重要な点は、Monsky の定理がグラフに限定されていないことである。** 同定理は任意の ",
        math(String.raw`f\in\mathbb{Z}_p[[\Gamma]]`),
        " と半代数的 ",
        math(String.raw`S\subset\widehat\Gamma`),
        " についての主張であり、上の和はちょうどその左辺（",
        math(String.raw`S=\widehat\Gamma`),
        "）である。したがって**グラフのラプラシアンでない一般の ",
        math(String.raw`P`),
        " にそのまま適用できる**。",
      ]),
      paragraph([
        math(String.raw`\mu=m_0(f)`),
        " が content の付値に等しいのは定義の言い換えである。Kataoka Definition 2.2（= Cuoco–Monsky Definitions 1.1, 1.2）は ",
        math(String.raw`m_0(f)`),
        " を「",
        math(String.raw`p^{-m_0(f)}f\in\mathbb{Z}_p[[\Gamma]]\setminus p\mathbb{Z}_p[[\Gamma]]`),
        "」すなわち ",
        math(String.raw`f`),
        " を割り切る ",
        math(String.raw`p`),
        " の最大冪として定義している。",
        math(String.raw`z_i\mapsto1+T_i`),
        " は ",
        math(String.raw`\mathbb{Z}`),
        " 上の環同型なので content を保ち、単項式因子は ",
        math(String.raw`\mathbb{Z}[[T]]`),
        " の単元だから落とせる。よって ",
        math(String.raw`m_0(f)=v_p(\mathrm{content}\,P)`),
        "。",
      ]),
    ],
    conversion: { status: "added" },
  },
  {
    id: "paper_052_theorem_l0_computable",
    kind: "theorem",
    sourcePath: "structured-latex/content/005_duality.ts",
    sourceOrdinal: 3,
    title: { text: "命題 F — 有限台なら λ は有限手続きで計算できる（およびその境界）" },
    labels: ["paper_prop_F"],
    habitat: "Z",
    verification: ["sagemath/check/cycle16_T1_lambda_l0"],
    statement: [
      paragraph([
        "**(F1 計算可能性)** ",
        math(String.raw`0\neq P\in\mathbb{Z}[z_1^{\pm1},\dots,z_d^{\pm1}]`),
        "、",
        math(String.raw`f=P(1+T_1,\dots,1+T_d)`),
        " とし、",
        math(String.raw`\bar P`),
        " を ",
        math(String.raw`p^{-m_0(f)}P`),
        " の ",
        math(String.raw`\bmod\,p`),
        " 還元、その台を ",
        math(String.raw`E\subset\mathbb{Z}^d`),
        " とする。このとき",
      ]),
      displayMath(
        String.raw`\lambda=l_0(f)=\sum_{v\in V(\bar P)}\mathrm{ord}_{(\gamma_v-1)}(\bar f),
\qquad V(\bar P):=\{\mathrm{prim}(e-e')\ :\ e\neq e'\in E\},`,
      ),
      paragraph([
        "であり、右辺は ",
        math(String.raw`\mathbb{F}_p`),
        " と ",
        math(String.raw`\mathbb{Z}^d`),
        " 上の有限個の演算（",
        math(String.raw`\gcd`),
        "、Smith 標準形、多項式展開、係数和）だけで計算できる。",
        math(String.raw`d`),
        " は任意で、",
        math(String.raw`P`),
        " に非退化性の仮定は要らない。",
      ]),
      paragraph([
        "とくに、",
        math(String.raw`\bar f`),
        " の最低次斉次部分の ",
        math(String.raw`\mathbb{P}^{d-1}(\mathbb{F}_p)`),
        " 有理線形因子を数える素朴なレシピは**上限しか与えない**（原因は素イデアル ",
        math(String.raw`(\gamma-1)`),
        " が ",
        math(String.raw`\mathbb{F}_p`),
        " ではなく ",
        math(String.raw`\mathbb{Z}_p`),
        " 上の方向で添字づけられることである）。反例: ",
        math(String.raw`P=z+w^2-2w`),
        ", ",
        math(String.raw`p=3`),
        " では上限が ",
        math(String.raw`1`),
        " なのに ",
        math(String.raw`l_0=0`),
        "（和は ",
        math(String.raw`\tfrac52(3^n-1)`),
        " で ",
        math(String.raw`n\,3^n`),
        " 項をもたない）。上式はこの例でも正しい値を返す。",
      ]),
      paragraph([
        "**(F2 境界)** ",
        math(String.raw`d\ge2`),
        " のとき、係数を計算する手続きで与えられた一般の ",
        math(String.raw`f\in\mathbb{Z}_p[[\Gamma]]`),
        " に対しては、",
        math(String.raw`m_0(f)=0`),
        " という約束の下でさえ述語 ",
        math(String.raw`l_0(f)\ge1`),
        " は**決定不能**である（停止問題に還元される）。",
        math(String.raw`d=1`),
        " では ",
        math(String.raw`m_0(f)=0`),
        " の約束の下で ",
        math(String.raw`\lambda`),
        " は計算可能なので、境界は ",
        math(String.raw`d`),
        " ではなく**台の有限性**にある。",
      ]),
    ],
    proof: [
      paragraph([
        "**(F1)** 要は、素イデアル ",
        math(String.raw`(\gamma_v-1)`),
        " の添字集合 ",
        math(String.raw`\mathbb{P}^{d-1}(\mathbb{Z}_p)`),
        " が非可算であっても、**",
        math(String.raw`\bar P`),
        " を割りうるものは有限個の有理方向に限られる**ことである。",
        math(String.raw`\pi:\mathbb{Z}^d\to\Gamma/\overline{\langle\gamma_v\rangle}`),
        " を自然な写像とすると、標数 ",
        math(String.raw`p`),
        " では ",
        math(String.raw`\{\prod_i(1+T_i)^{a_i}\}_{a\in A}`),
        " が任意の有限 ",
        math(String.raw`A\subset\mathbb{Z}_p^{d-1}`),
        " について ",
        math(String.raw`\mathbb{F}_p`),
        " 上線形独立である（",
        math(String.raw`(1+T)^{p^N}=1+T^{p^N}`),
        " により ",
        math(String.raw`\mathbb{Z}/p^N`),
        " へ落として示す）から、",
      ]),
      displayMath(
        String.raw`(\gamma_v-1)\mid\bar f\iff\forall a\in\pi(E):\ \sum_{e\in E,\ \pi(e)=a}c_e=0 .`,
      ),
      paragraph([
        "各 ",
        math(String.raw`c_e\neq0`),
        " なので、割るためにはどのファイバーも 2 点以上でなければならず、したがって ",
        math(String.raw`\pi(e)=\pi(e')`),
        " なる ",
        math(String.raw`e\neq e'`),
        " が存在し ",
        math(String.raw`\mathbb{Z}_pv=\mathbb{Z}_p\,\mathrm{prim}(e-e')`),
        " となる。方向が有理的に決まったあとは ",
        math(String.raw`U\in GL_d(\mathbb{Z})`),
        " で ",
        math(String.raw`(\gamma_v-1)\mapsto(T_1)`),
        " と正規化し、重複度は多項式 ",
        math(String.raw`Q(1+T)`),
        " の ",
        math(String.raw`T_1`),
        " 最低次数として有限計算で読める。",
      ]),
      paragraph([
        "**(F2)** ",
        math(String.raw`l_0`),
        " は ",
        math(String.raw`(p,T)`),
        " 進位相について不連続である: ",
        math(String.raw`f=z_1-1`),
        " は ",
        math(String.raw`l_0=1`),
        " だが、これに位数 ",
        math(String.raw`\ge p^m`),
        " の摂動を加えた ",
        math(String.raw`f_m`),
        " は ",
        math(String.raw`l_0=0`),
        " となり ",
        math(String.raw`f_m\to f`),
        "。そこで Turing 機械 ",
        math(String.raw`M`),
        " が ",
        math(String.raw`m`),
        " ステップで停止するときだけ摂動を入れた ",
        math(String.raw`f_M`),
        " を作ると、その係数は一様に計算可能で ",
        math(String.raw`m_0(f_M)=0`),
        " かつ ",
        math(String.raw`l_0(f_M)=0\iff M`),
        " が停止する。",
      ]),
      paragraph([
        "詳細は ",
        ref("paper_prop_D"),
        " の根拠レポート（",
        math(String.raw`\texttt{outputs/reports/cycle16\_T1\_lambda\_l0\_computability.md}`),
        "）にある。**新規性は主張しない。** 群環の素因子を線形代数で決める議論は folklore の可能性が高く、",
        "対応する文献命題は特定できていない。",
      ]),
    ],
    conversion: { status: "added" },
  },
  {
    id: "paper_053_remark_limits",
    kind: "remark",
    sourcePath: "structured-latex/content/005_duality.ts",
    sourceOrdinal: 4,
    title: { text: "命題 D に残る限界（命題の一部として明示する）" },
    labels: ["paper_remark_D_limits"],
    habitat: "none",
    statement: [
      paragraph([
        ref("paper_prop_D"),
        " には次の 2 つの未解決点が残る。**これらは限界として命題に付随するものであり、隠さない。**",
        "（かつてここに挙げていた「",
        math(String.raw`\lambda`),
        " の計算可能性が未確立」は ",
        ref("paper_prop_F"),
        " で解消した。ただし解消したのは**台が有限な場合**に限る。）",
      ]),
      list([
        [
          "**(i) ",
          math(String.raw`\lambda_i,\mu_i,\nu`),
          "（",
          math(String.raw`i\ge1`),
          "）の明示公式が無い。** これらは**有理数**であって整数とは限らない。",
          "文献（Kataoka）も ",
          math(String.raw`\lambda,\mu`),
          " だけを explicit と述べ、低位項の係数は「有理数が存在する」としか主張していない。",
          "本論文が明示できるのは非退化な ",
          math(String.raw`d=2`),
          " グラフ塔の ",
          math(String.raw`\mu_1`),
          " のみである（",
          ref("paper_prop_W"),
          "）。",
        ],
        [
          "**(ii) 退化点が増える ",
          math(String.raw`P`),
          " の整理が未了。** ",
          math(String.raw`\chi(f)=0`),
          " となる ",
          math(String.raw`\chi`),
          " の個数が ",
          math(String.raw`n`),
          " とともに増える場合、",
          math(String.raw`a^{\mathrm{red}}`),
          " と ",
          math(String.raw`a`),
          " の関係の記述が本論文の水準では足りない。",
        ],
      ]),
      paragraph([
        "**規約の注意**: グラフの全域木数 ",
        math(String.raw`\kappa_{X_n}`),
        " は上式から ",
        math(String.raw`-dn+\mathrm{ord}_p(\kappa(X))-\mathrm{ord}_p(\#V_X)`),
        " だけずれる（",
        math(String.raw`\#V_{X_n}=\#V_X\cdot p^{dn}`),
        " で割るため）。「Monsky の定理の左辺 ＝ ",
        math(String.raw`\mathrm{ord}_p(\kappa)`),
        "」ではない。",
      ]),
    ],
    conversion: { status: "added" },
  },
]);
