/**
 * 論文本体 第 5 章の続き: 命題 G′（消滅深度が無限大になる方向と、その族の閉形式）。
 *
 * 命題 G の (G6) は「消滅深度 θ(P) ≤ ℓ」の下でのみ閉形式を与える。本ブロックはその仮定が
 * 最も強く破れる場合（方向上で Ē が恒等的に消える。θ = ∞）を扱い、
 *   (G′1) θ = ∞ の軌跡が有限本の直線であること（判定は D の係数からの有限計算）、
 *   (G′2) その下での点ごとの付値（段階的処理）、
 *   (G′3) 具体族の閉形式と、それが任意の奇素数で n ℓ^n 項を持つこと
 * を述べる。根拠レポートは outputs/reports/cycle19_T3_theta_infinity.md。
 *
 * **新規性は主張しない**（同 report §10）。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_055_theorem_theta_infinity",
    kind: "theorem",
    origin: { path: "structured-latex/content/005b_theta_infinity.ts", ordinal: 1 },
    title: {
      text: "命題 G′ — 消滅深度が無限大になる方向、段階的処理、および型 III の奇素数族",
    },
    labels: ["paper_prop_G_infty"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle19_T3_theta_infinity"],
    lean: [
      "IntegrableLattice.bouquet_cases_exclusive",
      "IntegrableLattice.card_diag_three",
      "IntegrableLattice.card_diag_two",
      "IntegrableLattice.sum_level_A",
      "IntegrableLattice.sum_level_B",
      "IntegrableLattice.ordKappa_of_sigma",
      "IntegrableLattice.theoremJ8_eq_XPrime",
    ],
    statement: [
      paragraph([
        ref("paper_prop_G"),
        " の設定で、消滅深度を ",
        math(String.raw`\theta(a,b)=\mathrm{ord}_{x=0}\overline{\Phi_{(a,b)}}`),
        "（",
        math(String.raw`\Phi_{(a,b)}(x)=\tilde E((1+x)^a,(1+x)^b)\in\mathbb{Z}[x]`),
        "）とする。",
        ref("paper_prop_G"),
        " の閉形式は全方向で ",
        math(String.raw`\theta(P)\le\ell`),
        " を仮定するが、その仮定が最も強く破れるのは ",
        math(String.raw`\theta=\infty`),
        "、すなわち ",
        math(String.raw`\bar E`),
        " が 1 径数部分群 ",
        math(String.raw`y\mapsto(y^a,y^b)`),
        " 上で恒等的に消える場合である。",
      ]),
      paragraph([
        "**(G′1 消滅深度が無限大になる軌跡)** ",
        math(String.raw`u=(a,b)\in\mathbb{Z}^2`),
        " を原始ベクトル、",
        math(String.raw`u^\perp=(b,-a)`),
        "、",
        math(String.raw`\chi^{(p,q)}=z^pw^q`),
        " と書くと",
      ]),
      displayMath(
        String.raw`\theta(u)=\infty\iff\bigl(\chi^{u^\perp}-1\bigr)\ \bigm|\ \bar{\tilde E}
        \quad\text{in }\mathbb{F}_\ell[z^{\pm1},w^{\pm1}].`,
      ),
      paragraph([
        "さらに Newton 多面体の Minkowski 分解（",
        math(String.raw`\mathrm{Newt}(fg)=\mathrm{Newt}(f)+\mathrm{Newt}(g)`),
        "）より、そのような ",
        math(String.raw`u^\perp`),
        " の方向は ",
        math(String.raw`\mathrm{Newt}(\bar{\tilde E})`),
        " の辺方向に限られる。したがって ",
        math(String.raw`\{\theta=\infty\}`),
        " は**原点を通る有限本の直線の合併**であり、その全体は ",
        math(String.raw`D`),
        " の係数からの有限計算で決まる（塔の値も円分体も使わない）。",
      ]),
      paragraph([
        "**(G′2 段階的処理による点ごとの付値)** ",
        math(String.raw`\lambda(a,b):=v_\ell(\mathrm{content}\,\Phi_{(a,b)})`),
        "、",
        math(String.raw`\Psi:=\ell^{-\lambda}\Phi_{(a,b)}=\sum_mB_mx^m`),
        "、",
        math(String.raw`\theta^*:=\min\{m:\ell\nmid B_m\}`),
        "、",
        math(String.raw`m_1:=\min\{m<\theta^*:B_m\neq0\}`),
        " と置くと、",
        math(String.raw`\theta=\infty\iff\lambda\ge1`),
        " であり、**内容を 1 回割るだけで必ず ",
        math(String.raw`\theta^*<\infty`),
        " になる**（反復は要らない）。",
        math(String.raw`\theta^*-m_1<\varphi(\ell^M)`),
        " ならば",
      ]),
      displayMath(
        String.raw`v_\ell\bigl(E(\zeta,\xi)\bigr)=\lambda+\frac{\theta^*}{\varphi(\ell^M)}
        \qquad(\zeta=g^a,\ \xi=g^b,\ g\ \text{は原始}\ \ell^M\ \text{乗根}).`,
      ),
      paragraph([
        math(String.raw`\lambda,\theta^*,m_1`),
        " は**点 ",
        math(String.raw`(\zeta,\xi)`),
        " ではなく整数ベクトル ",
        math(String.raw`(a,b)`),
        " の関数**であり、同じ点の別の代表では値が違いうる。上の等式は「仮定が成り立つ代表で使う」",
        "という形で運用する。方向 ",
        math(String.raw`P`),
        " のレベルちょうど ",
        math(String.raw`M`),
        " の点 ",
        math(String.raw`(\ell-1)\ell^{2M-2}`),
        " 個のうち、直線 ",
        math(String.raw`\mathbb{Z}u`),
        " に乗る代表を持つものはちょうど ",
        math(String.raw`\varphi(\ell^M)`),
        " 個（割合 ",
        math(String.raw`\ell^{1-M}`),
        "）である。これが「",
        math(String.raw`\theta=\infty`),
        " の点と有限の点が同じ方向に同居する」ことの内容である。",
      ]),
      paragraph([
        "また、直線 ",
        math(String.raw`\mathbb{Z}u`),
        " 上の点の ",
        math(String.raw`\Sigma_n`),
        " への寄与は ",
        math(String.raw`\lambda(\ell^n-1)+n\theta^*`),
        " であり、**",
        math(String.raw`n\ell^n`),
        " 項を作らない**。",
      ]),
      paragraph([
        "**(G′3 型 III の奇素数族)** ",
        math(String.raw`\ell`),
        " を奇素数、",
        math(String.raw`X`),
        " を 1 頂点の bouquet（voltage ",
        math(String.raw`(1,0)`),
        " のループ ",
        math(String.raw`p`),
        " 本、",
        math(String.raw`(0,1)`),
        " のループ ",
        math(String.raw`q`),
        " 本）とし、",
        math(String.raw`\mu=v_\ell(\gcd(p,q))`),
        "、",
        math(String.raw`p'=p/\ell^\mu`),
        "、",
        math(String.raw`q'=q/\ell^\mu`),
        " とする。このとき ",
        math(String.raw`\theta=\infty`),
        " が起きるのは ",
        math(String.raw`\ell\mid p'q'(p'+q')`),
        " のときちょうどで、例外直線は ",
        math(String.raw`\ell\mid p'+q'`),
        " なら 2 本 ",
        math(String.raw`\mathbb{Z}(1,1),\mathbb{Z}(1,-1)`),
        "（各 ",
        math(String.raw`\lambda=v_\ell(p'+q')`),
        "）、",
        math(String.raw`\ell\mid p'`),
        " なら 1 本 ",
        math(String.raw`\mathbb{Z}(1,0)`),
        "（",
        math(String.raw`\lambda=v_\ell(p')`),
        "）、",
        math(String.raw`\ell\mid q'`),
        " なら 1 本 ",
        math(String.raw`\mathbb{Z}(0,1)`),
        "（",
        math(String.raw`\lambda=v_\ell(q')`),
        "）である。",
        math(String.raw`\Lambda:=\sum_{\text{例外直線}}\lambda`),
        " と置くと、例外直線があるとき**全ての ",
        math(String.raw`n\ge0`),
        " で**",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_\ell(\kappa_n)=\mu\,(\ell^{2n}-1)+2\,n\,\ell^{n}+\Lambda\,(\ell^{n}-1).`,
      ),
      paragraph([
        "すなわち ",
        ref("paper_prop_W"),
        " の 5 係数は ",
        math(String.raw`a=\mu,\ b=2,\ c=\Lambda,\ d=0,\ e=-\mu-\Lambda`),
        "、",
        math(String.raw`n_0=0`),
        "。**",
        math(String.raw`b=2\neq0`),
        " なのでこの塔は型 III（",
        math(String.raw`n\ell^n`),
        " 項を持つ）であり、これは任意の奇素数 ",
        math(String.raw`\ell`),
        " について無限個の ",
        math(String.raw`(p,q)`),
        " で実現する。** ",
        math(String.raw`n\ell^n`),
        " 項の出所は ",
        math(String.raw`\theta=\infty`),
        " の点そのものではなく（上の寄与の式）、その ",
        math(String.raw`\ell`),
        " 進近傍で ",
        math(String.raw`\theta`),
        " が幾何級数的に深くなる点の集積である。",
      ]),
      paragraph([
        "**この族は ",
        math(String.raw`\ell`),
        " が奇なら完全に解けている**: 非退化なら ",
        ref("paper_prop_W"),
        "、退化かつ例外直線なしなら全退化方向で ",
        math(String.raw`\theta(P)=4\le\ell`),
        " なので ",
        ref("paper_prop_G"),
        " (G6)、例外直線ありなら上式。",
        math(String.raw`\ell=3`),
        " では中間の場合が空である。",
      ]),
      paragraph([
        "**射程の限界（誇張しないために明記する）。** 上の閉形式の形を",
        "「例外直線を持つ一般の塔」へ素朴に延長した式 ",
        math(String.raw`\mu(\ell^{2n}-1)+k\,n\ell^n+\Lambda(\ell^n-1)+v_\ell(\kappa_X)`),
        " は**偽**である（反例: ",
        math(String.raw`\ell=3`),
        "、voltage ",
        math(String.raw`(1,0),(1,-1),(1,2)`),
        " で実測 ",
        math(String.raw`0,10,50`),
        " に対し右辺は ",
        math(String.raw`0,8,44`),
        "）。一般の塔で例外直線の**近傍**の寄与を決める方法は得られていない。",
        "また ",
        math(String.raw`\ell=2`),
        " では (G′3) の証明が成り立たない（2 が単位元でないため）。",
        "詳細は根拠レポート ",
        math(String.raw`\texttt{outputs/reports/cycle19\_T3\_theta\_infinity.md}`),
        "。**新規性は主張しない。**",
      ]),
    ],
  },
]);
