/**
 * 論文本体 第 5 章の続き: 命題 G′（消滅深度が無限大になる方向と、その族の閉形式）。
 *
 * 命題 G の (G6) は「消滅深度 θ(P) ≤ ℓ」の下でのみ閉形式を与える。本ブロックはその仮定が
 * 最も強く破れる場合（方向上で Ē が恒等的に消える。θ = ∞）を扱い、
 *   (G′1) θ = ∞ の軌跡が有限本の直線であること（判定は D の係数からの有限計算）、
 *   (G′2) その下での点ごとの付値（段階的処理）、
 *   (G′3) 具体族の閉形式と、それが任意の奇素数で n ℓ^n 項を持つこと
 * を述べる。根拠レポートは outputs/reports/cycle19_T3_theta_infinity.md。
 *
 * **新規性は主張しない**（同 report §10）。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_055_theorem_theta_infinity",
    kind: "theorem",
    origin: { path: "structured-latex/content/005b_theta_infinity.ts", ordinal: 1 },
    title: {
      text: "命題 G′ — 消滅深度が無限大になる方向、段階的処理、および型 III の奇素数族",
    },
    labels: ["paper_prop_G_infty"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle19_T3_theta_infinity"],
    lean: [
      "IntegrableLattice.bouquet_cases_exclusive",
      "IntegrableLattice.card_diag_three",
      "IntegrableLattice.card_diag_two",
      "IntegrableLattice.sum_level_A",
      "IntegrableLattice.sum_level_B",
      "IntegrableLattice.ordKappa_of_sigma",
      "IntegrableLattice.theoremJ8_eq_XPrime",
    ],
    statement: [
      paragraph([
        ref("paper_prop_G"),
        " の設定で、消滅深度を ",
        math(String.raw`\theta(a,b)=\mathrm{ord}_{x=0}\overline{\Phi_{(a,b)}}`),
        "（",
        math(String.raw`\Phi_{(a,b)}(x)=\tilde E((1+x)^a,(1+x)^b)\in\mathbb{Z}[x]`),
        "）とする。",
        ref("paper_prop_G"),
        " の閉形式は全方向で ",
        math(String.raw`\theta(P)\le\ell`),
        " を仮定するが、その仮定が最も強く破れるのは ",
        math(String.raw`\theta=\infty`),
        "、すなわち ",
        math(String.raw`\bar E`),
        " が 1 径数部分群 ",
        math(String.raw`y\mapsto(y^a,y^b)`),
        " 上で恒等的に消える場合である。",
      ]),
      paragraph([
        "(G′1 消滅深度が無限大になる軌跡) ",
        math(String.raw`u=(a,b)\in\mathbb{Z}^2`),
        " を原始ベクトル、",
        math(String.raw`u^\perp=(b,-a)`),
        "、",
        math(String.raw`\chi^{(p,q)}=z^pw^q`),
        " と書くと",
      ]),
      displayMath(
        String.raw`\theta(u)=\infty\iff\bigl(\chi^{u^\perp}-1\bigr)\ \bigm|\ \bar{\tilde E}
        \quad\text{in }\mathbb{F}_\ell[z^{\pm1},w^{\pm1}].`,
      ),
      paragraph([
        "さらに Newton 多面体の Minkowski 分解（",
        math(String.raw`\mathrm{Newt}(fg)=\mathrm{Newt}(f)+\mathrm{Newt}(g)`),
        "）より、そのような ",
        math(String.raw`u^\perp`),
        " の方向は ",
        math(String.raw`\mathrm{Newt}(\bar{\tilde E})`),
        " の辺方向に限られる。したがって ",
        math(String.raw`\{\theta=\infty\}`),
        " は原点を通る有限本の直線の合併であり、その全体は ",
        math(String.raw`D`),
        " の係数からの有限計算で決まる（塔の値も円分体も使わない）。",
      ]),
      paragraph([
        "(G′2 段階的処理による点ごとの付値) ",
        math(String.raw`\lambda(a,b):=v_\ell(\mathrm{content}\,\Phi_{(a,b)})`),
        "、",
        math(String.raw`\Psi:=\ell^{-\lambda}\Phi_{(a,b)}=\sum_mB_mx^m`),
        "、",
        math(String.raw`\theta^*:=\min\{m:\ell\nmid B_m\}`),
        "、",
        math(String.raw`m_1:=\min\{m<\theta^*:B_m\neq0\}`),
        " と置く（規約（書き落とせない）: そのような ",
        math(String.raw`m`),
        " が 1 つも無ければ ",
        math(String.raw`m_1=+\infty`),
        " と読み、",
        math(String.raw`m_1`),
        " を含む引き算の条件は自動的に満たされているとする。この規約が無いと、",
        math(String.raw`\min\emptyset=0`),
        " と読んだ場合に (G′3) の族（",
        math(String.raw`\theta^*=2`),
        "）で条件が ",
        math(String.raw`\ell\ge5`),
        " を要求し、「任意の奇素数で成り立つ」という (G′3) の主張から ",
        math(String.raw`\ell=3`),
        " だけが落ちる）。こう置くと、",
        math(String.raw`\theta=\infty\iff\lambda\ge1`),
        " であり、内容を 1 回割るだけで必ず ",
        math(String.raw`\theta^*<\infty`),
        " になる（反復は要らない）。",
        math(String.raw`\theta^*-m_1<\varphi(\ell^M)`),
        " ならば",
      ]),
      displayMath(
        String.raw`v_\ell\bigl(E(\zeta,\xi)\bigr)=\lambda+\frac{\theta^*}{\varphi(\ell^M)}
        \qquad(\zeta=g^a,\ \xi=g^b,\ g\ \text{は原始}\ \ell^M\ \text{乗根}).`,
      ),
      paragraph([
        math(String.raw`\lambda,\theta^*,m_1`),
        " は点 ",
        math(String.raw`(\zeta,\xi)`),
        " ではなく整数ベクトル ",
        math(String.raw`(a,b)`),
        " の関数であり、同じ点の別の代表では値が違いうる。上の等式は「仮定が成り立つ代表で使う」",
        "という形で運用する。方向 ",
        math(String.raw`P`),
        " のレベルちょうど ",
        math(String.raw`M`),
        " の点 ",
        math(String.raw`(\ell-1)\ell^{2M-2}`),
        " 個のうち、直線 ",
        math(String.raw`\mathbb{Z}u`),
        " に乗る代表を持つものはちょうど ",
        math(String.raw`\varphi(\ell^M)`),
        " 個（割合 ",
        math(String.raw`\ell^{1-M}`),
        "）である。これが「",
        math(String.raw`\theta=\infty`),
        " の点と有限の点が同じ方向に同居する」ことの内容である。",
      ]),
      paragraph([
        "また、",
        math(String.raw`\theta^*-m_1<\ell-1`),
        " を仮定すると（このとき ",
        math(String.raw`\varphi(\ell^M)\ge\ell-1`),
        " なので、この 1 条件で全レベル ",
        math(String.raw`M\ge1`),
        " について上の付値公式が使える）、直線 ",
        math(String.raw`\mathbb{Z}u`),
        " 上の点の ",
        math(String.raw`\Sigma_n`),
        " への寄与は ",
        math(String.raw`\lambda(\ell^n-1)+n\theta^*`),
        " であり、",
        math(String.raw`n\ell^n`),
        " 項を作らない。この仮定なしにはこの等式は述べられない。 ",
        "(G′3) の族では ",
        math(String.raw`\theta^*=2`),
        "、",
        math(String.raw`m_1=+\infty`),
        " なので自動的に満たされる。",
      ]),
      paragraph([
        "(G′3 型 III の奇素数族) ",
        math(String.raw`\ell`),
        " を奇素数、",
        math(String.raw`X`),
        " を 1 頂点の bouquet（voltage ",
        math(String.raw`(1,0)`),
        " のループ ",
        math(String.raw`p`),
        " 本、",
        math(String.raw`(0,1)`),
        " のループ ",
        math(String.raw`q`),
        " 本）とし、",
        math(String.raw`\mu=v_\ell(\gcd(p,q))`),
        "、",
        math(String.raw`p'=p/\ell^\mu`),
        "、",
        math(String.raw`q'=q/\ell^\mu`),
        " とする。このとき ",
        math(String.raw`\theta=\infty`),
        " が起きるのは ",
        math(String.raw`\ell\mid p'q'(p'+q')`),
        " のときちょうどで、例外直線は ",
        math(String.raw`\ell\mid p'+q'`),
        " なら 2 本 ",
        math(String.raw`\mathbb{Z}(1,1),\mathbb{Z}(1,-1)`),
        "（各 ",
        math(String.raw`\lambda=v_\ell(p'+q')`),
        "）、",
        math(String.raw`\ell\mid p'`),
        " なら 1 本 ",
        math(String.raw`\mathbb{Z}(1,0)`),
        "（",
        math(String.raw`\lambda=v_\ell(p')`),
        "）、",
        math(String.raw`\ell\mid q'`),
        " なら 1 本 ",
        math(String.raw`\mathbb{Z}(0,1)`),
        "（",
        math(String.raw`\lambda=v_\ell(q')`),
        "）である。",
        math(String.raw`\lambda_{\mathrm{exc}}:=\sum_{\text{例外直線}}\lambda`),
        " と置くと、例外直線があるとき全ての ",
        math(String.raw`n\ge0`),
        " で",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_\ell(\kappa_n)=\mu\,(\ell^{2n}-1)+2\,n\,\ell^{n}+\lambda_{\mathrm{exc}}\,(\ell^{n}-1).`,
      ),
      paragraph([
        "すなわち ",
        ref("paper_prop_W"),
        " の 5 係数は ",
        math(String.raw`a=\mu,\ b=2,\ c=\lambda_{\mathrm{exc}},\ d=0,\ e=-\mu-\lambda_{\mathrm{exc}}`),
        "、",
        math(String.raw`n_0=0`),
        "。",
        math(String.raw`b=2\neq0`),
        " なのでこの塔は型 III（",
        math(String.raw`n\ell^n`),
        " 項を持つ）であり、これは任意の奇素数 ",
        math(String.raw`\ell`),
        " について無限個の ",
        math(String.raw`(p,q)`),
        " で実現する。 ",
        math(String.raw`n\ell^n`),
        " 項の出所は ",
        math(String.raw`\theta=\infty`),
        " の点そのものではなく（上の寄与の式）、その ",
        math(String.raw`\ell`),
        " 進近傍で ",
        math(String.raw`\theta`),
        " が幾何級数的に深くなる点の集積である。",
      ]),
      paragraph([
        "この族は ",
        math(String.raw`\ell`),
        " が奇なら完全に解けている: 非退化なら ",
        ref("paper_prop_W"),
        "、退化かつ例外直線なしなら全退化方向で ",
        math(String.raw`\theta(P)=4\le\ell`),
        " なので ",
        ref("paper_prop_G"),
        " (G6)、例外直線ありなら上式。",
        math(String.raw`\ell=3`),
        " では中間の場合が空である。",
      ]),
      paragraph([
        "射程の限界（誇張しないために明記する）。 上の閉形式の形を",
        "「例外直線を持つ一般の塔」へ素朴に延長した式 ",
        math(String.raw`\mu(\ell^{2n}-1)+k\,n\ell^n+\lambda_{\mathrm{exc}}\,(\ell^n-1)+v_\ell(\kappa_X)`),
        " は偽である（反例: ",
        math(String.raw`\ell=3`),
        "、voltage ",
        math(String.raw`(1,0),(1,-1),(1,2)`),
        " で実測 ",
        math(String.raw`0,10,50`),
        " に対し右辺は ",
        math(String.raw`0,8,44`),
        "）。一般の塔で例外直線の近傍の寄与を決める方法は得られていない。",
        "また ",
        math(String.raw`\ell=2`),
        " では (G′3) の証明がそのままでは成り立たない（",
        math(String.raw`2`),
        " が単元でないため）。同じ族の ",
        math(String.raw`\ell=2`),
        " は別に決着しており、(G′3) の閉形式が ",
        math(String.raw`\ell=2`),
        " で正しいのは 1 つの場合に限る（",
        ref("paper_prop_G_ell2"),
        "）。",
        "新規性は主張しない。",
      ]),
    ],
    proof: [
      paragraph([
        "証明は 3 部からなる。本文に無い補題へ暗黙に依存しないために、途中で使う事実は",
        "すべてその主張をここで述べてから使う。 使う道具は、有限体上の Laurent 多項式環の",
        "座標変換、Newton 多面体の加法性、および円分体 ",
        math(String.raw`\mathbb{Q}(\zeta_{\ell^M})`),
        " の ",
        math(String.raw`\ell`),
        " の上の唯一の素点での付値だけであり、実数体へは一度も出ない。",
      ]),
      paragraph([
        "(0) 出発点の総和公式。 ",
        ref("paper_prop_W"),
        " の証明にある恒等式に ",
        math(String.raw`N=N'=\ell^{n}`),
        " を入れ、",
        math(String.raw`\det L=\ell^{\mu}E`),
        " と、走る点の個数が ",
        math(String.raw`\ell^{2n}-1`),
        " 個であることを使うと",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_\ell(\kappa_n)=v_\ell(\kappa_X)-2n+\mu\bigl(\ell^{2n}-1\bigr)+\Sigma_n,
        \qquad
        \Sigma_n=\sum_{\substack{\zeta^{\ell^n}=\xi^{\ell^n}=1\\ (\zeta,\xi)\neq(1,1)}}v_\ell\bigl(E(\zeta,\xi)\bigr)`,
      ),
      paragraph([
        "を得る。以下すべてこの ",
        math(String.raw`\Sigma_n`),
        " を計算する形で進む。",
      ]),
      paragraph([
        "(G′1) の証明。まず補題 A（スケール不変性）を述べる。 ",
        math(String.raw`c\neq0`),
        " なる整数について ",
        math(String.raw`\lambda(ca,cb)=\lambda(a,b)`),
        " であり、さらに ",
        math(String.raw`\ell\nmid c`),
        " ならば ",
        math(String.raw`\theta^*(ca,cb)=\theta^*(a,b)`),
        " である。実際、",
        math(String.raw`\psi_u:\mathbb{Z}[z^{\pm1},w^{\pm1}]\to\mathbb{Z}[y^{\pm1}]`),
        "（",
        math(String.raw`z\mapsto y^a,\ w\mapsto y^b`),
        "）と置くと ",
        math(String.raw`\psi_{(ca,cb)}=(y\mapsto y^{c})\circ\psi_{(a,b)}`),
        " で、",
        math(String.raw`y\mapsto y^{c}`),
        " は単項式を単項式へ単射に写すから係数の集合を変えず、内容の ",
        math(String.raw`\ell`),
        " 付値 ",
        math(String.raw`\lambda`),
        " は不変である。",
        math(String.raw`\theta^*`),
        " については ",
        math(String.raw`\rho(x)=(1+x)^{c}-1`),
        " が ",
        math(String.raw`\bmod\ \ell`),
        " で ",
        math(String.raw`x=0`),
        " における位数ちょうど ",
        math(String.raw`1`),
        " をもつ（最低次係数が ",
        math(String.raw`c\neq0`),
        "）ことと ",
        math(String.raw`\Phi_{(ca,cb)}=\Phi_{(a,b)}\circ\rho`),
        " から、合成の位数が保たれる。したがって ",
        math(String.raw`\theta=\infty`),
        " は原点を通る直線に沿った性質である。",
      ]),
      paragraph([
        "補題 B（内容が消滅深度を支配し、1 回で閉じる）。 ",
        math(String.raw`\Phi_{(a,b)}\neq0`),
        " のとき ",
        math(String.raw`\theta(a,b)=\infty\iff\lambda(a,b)\ge1`),
        " であり、内容で 1 回割った ",
        math(String.raw`\Psi=\ell^{-\lambda}\Phi_{(a,b)}`),
        " は必ず ",
        math(String.raw`\theta^*<\infty`),
        " を満たす。実際 ",
        math(String.raw`\theta=\infty`),
        " とは ",
        math(String.raw`\overline{\Phi_{(a,b)}}=0`),
        "、すなわち全ての係数が ",
        math(String.raw`\ell`),
        " で割れること、すなわち ",
        math(String.raw`\ell\mid\mathrm{content}\,\Phi_{(a,b)}`),
        " である。他方 ",
        math(String.raw`\Psi`),
        " の内容は ",
        math(String.raw`\ell`),
        " と互いに素なので、ある ",
        math(String.raw`m`),
        " で ",
        math(String.raw`\ell\nmid B_m`),
        " となり ",
        math(String.raw`\theta^*<\infty`),
        "。反復は要らない。",
      ]),
      paragraph([
        "補題 C（判定条件）。 ",
        math(String.raw`u=(a,b)`),
        " を原始ベクトルとし、",
        math(String.raw`\bar\psi_u:\mathbb{F}_\ell[z^{\pm1},w^{\pm1}]\to\mathbb{F}_\ell[y^{\pm1}]`),
        " を ",
        math(String.raw`\psi_u`),
        " の ",
        math(String.raw`\bmod\ \ell`),
        " 還元とすると",
      ]),
      displayMath(String.raw`\ker\bar\psi_u=\bigl(\chi^{u^\perp}-1\bigr).`),
      paragraph([
        "証明。 群準同型 ",
        math(String.raw`\varepsilon:\mathbb{Z}^2\to\mathbb{Z}`),
        "、",
        math(String.raw`(p,q)\mapsto pa+qb`),
        " は ",
        math(String.raw`u`),
        " が原始なので全射で、核は ",
        math(String.raw`\mathbb{Z}u^\perp`),
        " である。",
        math(String.raw`\langle t,u\rangle=1`),
        " なる ",
        math(String.raw`t\in\mathbb{Z}^2`),
        " を取ると ",
        math(String.raw`(u^\perp,t)`),
        " は ",
        math(String.raw`\mathbb{Z}^2`),
        " の基底で、",
        math(String.raw`s:=\chi^{u^\perp}`),
        "、",
        math(String.raw`v:=\chi^{t}`),
        " と置けば ",
        math(String.raw`\mathbb{F}_\ell[z^{\pm1},w^{\pm1}]=\mathbb{F}_\ell[s^{\pm1},v^{\pm1}]`),
        " で、この座標で ",
        math(String.raw`\bar\psi_u`),
        " は ",
        math(String.raw`s\mapsto1`),
        "、",
        math(String.raw`v\mapsto y`),
        " である。",
        math(String.raw`\mathbb{F}_\ell[s^{\pm1},v^{\pm1}]/(s-1)\cong\mathbb{F}_\ell[y^{\pm1}]`),
        " なので核はちょうど ",
        math(String.raw`(s-1)`),
        "。",
      ]),
      paragraph([
        "補題 B と補題 C を合わせると ",
        math(String.raw`\theta(u)=\infty\iff\lambda(u)\ge1\iff\bar\psi_u(\bar{\tilde E})=0
        \iff(\chi^{u^\perp}-1)\mid\bar{\tilde E}`),
        " であり、これが (G′1) の同値である。",
      ]),
      paragraph([
        "有限性。 ",
        math(String.raw`(\chi^{v}-1)\mid\bar{\tilde E}`),
        " なら ",
        math(String.raw`\bar{\tilde E}=(\chi^{v}-1)G`),
        " と書け、Laurent 多項式の Newton 多面体の加法性（Ostrowski の定理）より ",
        math(String.raw`\mathrm{Newt}(\bar{\tilde E})=[0,v]+\mathrm{Newt}(G)`),
        " である。Minkowski 和の辺方向は各因子の辺方向の合併なので、",
        math(String.raw`v`),
        " の方向は ",
        math(String.raw`\mathrm{Newt}(\bar{\tilde E})`),
        " の辺方向のいずれかに限り、長さも対応する辺を超えない。辺は有限本なので候補は有限個であり、",
        "各候補について ",
        math(String.raw`\mathbb{F}_\ell[z^{\pm1},w^{\pm1}]`),
        " での割り算を 1 回行えば判定できる。補題 A と合わせて ",
        math(String.raw`\{\theta=\infty\}`),
        " は原点を通る有限本の直線の合併であり、その全体は ",
        math(String.raw`D`),
        " の係数からの有限計算で決まる。これで (G′1) が示された。",
      ]),
      paragraph([
        "(G′2) の証明。 ",
        math(String.raw`M\ge1`),
        "、",
        math(String.raw`g`),
        " を原始 ",
        math(String.raw`\ell^{M}`),
        " 乗根、",
        math(String.raw`\pi=g-1`),
        "、",
        math(String.raw`\alpha:=v_\ell(\pi)=1/\varphi(\ell^{M})`),
        " とする（",
        math(String.raw`\ell`),
        " は ",
        math(String.raw`\mathbb{Q}(\zeta_{\ell^{M}})`),
        " で完全分岐する）。",
        math(String.raw`E`),
        " と ",
        math(String.raw`\tilde E`),
        " は単項式（1 の冪根＝単元）だけ違うので ",
        math(String.raw`v_\ell(E(\zeta,\xi))=v_\ell(\tilde E(\zeta,\xi))=v_\ell\bigl(\Phi_{(a,b)}(\pi)\bigr)
        =\lambda+v_\ell\bigl(\Psi(\pi)\bigr)`),
        " である。",
        math(String.raw`\Psi(\pi)=\sum_mB_m\pi^m`),
        " の各項の付値は次のとおりである。",
      ]),
      displayMath(
        String.raw`v_\ell\bigl(B_{\theta^*}\pi^{\theta^*}\bigr)=\theta^*\alpha,\qquad
        v_\ell\bigl(B_m\pi^m\bigr)\ge m\alpha>\theta^*\alpha\ \ (m>\theta^*),\qquad
        v_\ell\bigl(B_m\pi^m\bigr)\ge1+m\alpha\ge1+m_1\alpha\ \ (m<\theta^*,\ B_m\neq0).`,
      ),
      paragraph([
        "ここで ",
        math(String.raw`m_1`),
        " は ",
        math(String.raw`B_m\neq0`),
        " なる ",
        math(String.raw`m<\theta^*`),
        " についてのみ最小を取る量であり、そのような ",
        math(String.raw`m`),
        " が 1 つも無ければ ",
        math(String.raw`m_1=+\infty`),
        " と読む（このとき仮定は自動的に満たされる）。仮定 ",
        math(String.raw`\theta^*-m_1<\varphi(\ell^{M})`),
        " は ",
        math(String.raw`(\theta^*-m_1)\alpha<1`),
        "、すなわち ",
        math(String.raw`1+m_1\alpha>\theta^*\alpha`),
        " と同値だから、最小値 ",
        math(String.raw`\theta^*\alpha`),
        " は ",
        math(String.raw`m=\theta^*`),
        " でのみ達成される。非アルキメデス的評価より ",
        math(String.raw`v_\ell(\Psi(\pi))=\theta^*\alpha`),
        " で、(G′2) の等式を得る。",
      ]),
      paragraph([
        "代表への依存。 ",
        math(String.raw`\lambda,\theta^*,m_1`),
        " は ",
        math(String.raw`\Phi_{(a,b)}`),
        " から定まるので整数ベクトル ",
        math(String.raw`(a,b)`),
        " の関数であり、点 ",
        math(String.raw`(\zeta,\xi)`),
        " は ",
        math(String.raw`(a,b)\bmod\ell^{M}`),
        " しか決めない。したがって同じ点の別の代表では ",
        math(String.raw`\theta^*-m_1<\varphi(\ell^{M})`),
        " が破れることがあり、そのときこの等式を使ってはならない。",
      ]),
      paragraph([
        "計数。 ",
        math(String.raw`u`),
        " は原始なので ",
        math(String.raw`u\bmod\ell\neq0`),
        "、よって ",
        math(String.raw`c\mapsto cu\bmod\ell^{M}`),
        " は単射であり、",
        math(String.raw`cu`),
        " のレベルがちょうど ",
        math(String.raw`M`),
        " になるのは ",
        math(String.raw`\ell\nmid c`),
        " のときだけだから、直線 ",
        math(String.raw`\mathbb{Z}u`),
        " に乗る代表をもつレベル ",
        math(String.raw`M`),
        " の点はちょうど ",
        math(String.raw`\varphi(\ell^{M})`),
        " 個である。方向は補題 A より ",
        math(String.raw`u\bmod\ell`),
        " で一定なので、これらはすべて同じ方向 ",
        math(String.raw`P`),
        " に属し、方向のレベル ",
        math(String.raw`M`),
        " の点 ",
        math(String.raw`(\ell-1)\ell^{2M-2}`),
        " 個に対する割合は ",
        math(String.raw`\ell^{1-M}`),
        " である。",
      ]),
      paragraph([
        "直線の寄与。 主張が置いた仮定 ",
        math(String.raw`\theta^*-m_1<\ell-1`),
        " を使う（",
        math(String.raw`\varphi(\ell^{M})\ge\ell-1`),
        " なので、この 1 条件で全レベルで上の付値公式が使える）。各点の付値は ",
        math(String.raw`\lambda+\theta^*/\varphi(\ell^{M})`),
        " で、",
        math(String.raw`\sum_{M=1}^{n}\varphi(\ell^{M})=\ell^{n}-1`),
        " だから",
      ]),
      displayMath(
        String.raw`\sum_{M=1}^{n}\varphi(\ell^{M})\Bigl(\lambda+\frac{\theta^*}{\varphi(\ell^{M})}\Bigr)
        =\lambda\,(\ell^{n}-1)+n\,\theta^{*},`,
      ),
      paragraph([
        "すなわち ",
        math(String.raw`n\ell^{n}`),
        " 項は現れない。",
      ]),
      paragraph([
        "(G′3) の証明。まず例外直線を完全に決める。 ",
        math(String.raw`\tilde E=zw\,E=-\bigl(p'(z^2w+w)+q'(zw^2+z)-2(p'+q')zw\bigr)`),
        " である。3 つの場合に分ける。",
      ]),
      paragraph([
        "(i) ",
        math(String.raw`\ell\nmid p'q'`),
        " のとき。 ",
        math(String.raw`\bar{\tilde E}`),
        " の 4 つの単項式 ",
        math(String.raw`z^2w,\ w,\ zw^2,\ z`),
        " の係数 ",
        math(String.raw`-p',-p',-q',-q'`),
        " はすべて ",
        math(String.raw`0`),
        " でないので ",
        math(String.raw`\mathrm{Newt}(\bar{\tilde E})`),
        " は頂点 ",
        math(String.raw`(2,1),(1,2),(0,1),(1,0)`),
        " の平行四辺形であり、辺方向は ",
        math(String.raw`\pm(1,1),\pm(1,-1)`),
        "、各辺の格子長は ",
        math(String.raw`1`),
        " である。(G′1) の有限性より候補は ",
        math(String.raw`u\in\{(1,1),(1,-1)\}`),
        " に限り、",
      ]),
      displayMath(
        String.raw`\psi_{(1,1)}(\tilde E)=-(p'+q')\,y\,(y-1)^2,\qquad
        \psi_{(1,-1)}(\tilde E)=-(p'+q')\,y^{-1}(y-1)^2\cdot(\text{monomial})`,
      ),
      paragraph([
        "（",
        math(String.raw`z+z^{-1}-2`),
        " は ",
        math(String.raw`z\mapsto z^{-1}`),
        " で不変なので ",
        math(String.raw`\psi_{(1,-1)}`),
        " でも ",
        math(String.raw`p'f+q'f`),
        " の形になる）。どちらも ",
        math(String.raw`\bmod\ \ell`),
        " で消えるのは ",
        math(String.raw`\ell\mid p'+q'`),
        " のときちょうどであり、そのとき ",
        math(String.raw`\Phi_u(x)=-(p'+q')x^2\cdot(\text{unit})`),
        " なので ",
        math(String.raw`\lambda=v_\ell(p'+q')`),
        "、",
        math(String.raw`\theta^*=2`),
        "、",
        math(String.raw`m_1=+\infty`),
        " である。",
      ]),
      paragraph([
        "(ii) ",
        math(String.raw`\ell\mid p'`),
        " のとき（このとき ",
        math(String.raw`\ell\nmid q'`),
        "）。",
        math(String.raw`\bar{\tilde E}=-q'z(w-1)^2`),
        " なので ",
        math(String.raw`\mathrm{Newt}`),
        " は線分 ",
        math(String.raw`[(1,0),(1,2)]`),
        "、辺方向は ",
        math(String.raw`\pm(0,1)`),
        " だけで候補は ",
        math(String.raw`u=(1,0)`),
        "。",
        math(String.raw`\psi_{(1,0)}(\tilde E)=-p'(y-1)^2`),
        " より ",
        math(String.raw`\lambda=v_\ell(p')\ge1`),
        "、",
        math(String.raw`\theta^*=2`),
        "、",
        math(String.raw`m_1=+\infty`),
        "。(iii) ",
        math(String.raw`\ell\mid q'`),
        " は ",
        math(String.raw`z\leftrightarrow w`),
        " の対称である。",
        math(String.raw`p',q'`),
        " が同時に ",
        math(String.raw`\ell`),
        " で割れることはないので 3 つの場合は排反であり、これで主張の表が得られた。",
      ]),
      paragraph([
        "次に点ごとの付値を決める。 以下 ",
        math(String.raw`\ell`),
        " は奇素数、",
        math(String.raw`n\ge1`),
        "、",
        math(String.raw`g`),
        " は原始 ",
        math(String.raw`\ell^{n}`),
        " 乗根、",
        math(String.raw`\nu(x):=v_\ell(x)`),
        "（",
        math(String.raw`x\equiv0`),
        " なら ",
        math(String.raw`\nu=n`),
        "）、",
        math(String.raw`\varphi_m:=\varphi(\ell^{m})`),
        " とする。",
        math(String.raw`\varepsilon:=\min(\nu(a),\nu(b))`),
        "、",
        math(String.raw`m:=n-\varepsilon`),
        "、",
        math(String.raw`h:=g^{\ell^{\varepsilon}}`),
        "（原始 ",
        math(String.raw`\ell^{m}`),
        " 乗根）、",
        math(String.raw`a':=a/\ell^{\varepsilon}`),
        "、",
        math(String.raw`b':=b/\ell^{\varepsilon}`),
        " と置くと ",
        math(String.raw`E(g^a,g^b)=-\bigl(p'f(a')+q'f(b')\bigr)`),
        "（",
        math(String.raw`f(c):=h^{c}+h^{-c}-2=h^{-c}(h^{c}-1)^2`),
        "）である。",
        math(String.raw`h^{N}-1`),
        " は ",
        math(String.raw`N\not\equiv0`),
        " のとき付値 ",
        math(String.raw`\ell^{\nu(N)}/\varphi_m`),
        " をもつので ",
        math(String.raw`v_\ell(f(c))=2\ell^{\nu(c)}/\varphi_m`),
        " である。",
      ]),
      paragraph([
        "場合 [A]（",
        math(String.raw`\ell\mid p'+q'`),
        "、",
        math(String.raw`\lambda_0:=v_\ell(p'+q')`),
        "）。 ",
        math(String.raw`a',b'`),
        " の一方だけが単元なら、単元側の項の付値 ",
        math(String.raw`2/\varphi_m`),
        " が他方より真に小さいので ",
        math(String.raw`\varphi_mv_\ell(E)=2`),
        "。両方単元のときは恒等式 ",
        math(String.raw`p'f(a')+q'f(b')=p'\bigl(f(a')-f(b')\bigr)+(p'+q')f(b')`),
        " と",
      ]),
      displayMath(
        String.raw`f(a')-f(b')=-h^{-a'}\bigl(h^{a'-b'}-1\bigr)\bigl(h^{a'+b'}-1\bigr)`,
      ),
      paragraph([
        "を使う（右辺を展開すると ",
        math(String.raw`h^{a'}+h^{-a'}-h^{b'}-h^{-b'}`),
        " になる）。",
        math(String.raw`\ell`),
        " は奇で ",
        math(String.raw`a'`),
        " は単元だから ",
        math(String.raw`(a'-b')+(a'+b')=2a'`),
        " も単元で、",
        math(String.raw`\nu(a'-b')`),
        " と ",
        math(String.raw`\nu(a'+b')`),
        " が同時に正になることはない。一方は ",
        math(String.raw`0`),
        "、他方を ",
        math(String.raw`r`),
        " とすると第 1 項の ",
        math(String.raw`\varphi_m`),
        " 倍は ",
        math(String.raw`1+\ell^{r}`),
        "、第 2 項のそれは ",
        math(String.raw`\lambda_0\varphi_m+2`),
        " である。",
        math(String.raw`r<m`),
        " のとき ",
        math(String.raw`\lambda_0\ge1`),
        " と ",
        math(String.raw`\ell\ge3`),
        " より ",
        math(String.raw`\lambda_0\varphi_m+2\ge\ell^{m-1}(\ell-1)+2\ge2\ell^{m-1}+2>\ell^{m-1}+1\ge\ell^{r}+1`),
        " と狭義に大きいので ",
        math(String.raw`\varphi_mv_\ell(E)=1+\ell^{r}`),
        "。",
        math(String.raw`a'\equiv\pm b'`),
        " のときは ",
        math(String.raw`f`),
        " が偶関数なので第 1 項が消え、",
        math(String.raw`\varphi_mv_\ell(E)=\lambda_0\varphi_m+2`),
        " である。",
      ]),
      paragraph([
        "場合 [B]（",
        math(String.raw`\ell\mid p'`),
        "、",
        math(String.raw`\lambda_1:=v_\ell(p')`),
        "）。 ",
        math(String.raw`m=n`),
        " として ",
        math(String.raw`\varphi_nv_\ell(p'f(a))=\lambda_1\varphi_n+2\ell^{\nu(a)}`),
        "、",
        math(String.raw`\varphi_nv_\ell(q'f(b))=2\ell^{\nu(b)}`),
        "。",
        math(String.raw`b\not\equiv0`),
        " なら ",
        math(String.raw`\lambda_1\varphi_n+2\ell^{\nu(a)}\ge\ell^{n-1}(\ell-1)+2\ge2\ell^{n-1}+2>2\ell^{n-1}\ge2\ell^{\nu(b)}`),
        " と狭義なので ",
        math(String.raw`\varphi_nv_\ell(E)=2\ell^{\nu(b)}`),
        "、",
        math(String.raw`b\equiv0`),
        " なら第 2 項が消えて ",
        math(String.raw`\varphi_nv_\ell(E)=\lambda_1\varphi_n+2\ell^{\nu(a)}`),
        " である。場合 [B′]（",
        math(String.raw`\ell\mid q'`),
        "） は対称。",
      ]),
      paragraph([
        "閉形式。 ",
        math(String.raw`\kappa(X)=1`),
        " なので、(0) より ",
        math(String.raw`\Sigma_n=2n\ell^{n}+\lambda_{\mathrm{exc}}\,(\ell^{n}-1)+2n`),
        " を示せばよい。場合 [A]（このとき ",
        math(String.raw`\lambda_{\mathrm{exc}}=2\lambda_0`),
        "）でレベルちょうど ",
        math(String.raw`m`),
        " の点の寄与 ",
        math(String.raw`S_m`),
        " を数える。片方だけ単元の点は ",
        math(String.raw`2\varphi_m\ell^{m-1}`),
        " 個で各 ",
        math(String.raw`\varphi_mv=2`),
        "、両方単元（",
        math(String.raw`\varphi_m^2`),
        " 組）のうち ",
        math(String.raw`a'\equiv\pm b'`),
        " は ",
        math(String.raw`2\varphi_m`),
        " 組で各 ",
        math(String.raw`\lambda_0\varphi_m+2`),
        "、",
        math(String.raw`r=j\ (1\le j\le m-1)`),
        " は ",
        math(String.raw`2\varphi_m\ell^{m-j-1}(\ell-1)`),
        " 組で各 ",
        math(String.raw`1+\ell^{j}`),
        "、残る ",
        math(String.raw`\varphi_m\ell^{m-1}(\ell-3)`),
        " 組は各 ",
        math(String.raw`2`),
        " である。",
        math(String.raw`\sum_{j=1}^{m-1}\ell^{m-j-1}(\ell-1)=\ell^{m-1}-1`),
        " を使って足し合わせると",
      ]),
      displayMath(
        String.raw`S_m=2+2\ell^{m-1}\bigl[(\lambda_0+m-1)(\ell-1)+\ell\bigr].`,
      ),
      paragraph([
        math(String.raw`\sum_{m=1}^{n}\ell^{m-1}=\frac{\ell^{n}-1}{\ell-1}`),
        " と ",
        math(String.raw`\sum_{m=1}^{n}(m-1)\ell^{m-1}=\frac{(n-1)\ell^{n+1}-n\ell^{n}+\ell}{(\ell-1)^2}`),
        " を代入すると ",
        math(String.raw`\Sigma_n=2n\ell^{n}+2\lambda_0(\ell^{n}-1)+2n`),
        " を得る（最後の分数の分子が ",
        math(String.raw`n\ell^{n}(\ell-1)`),
        " になる）。場合 [B]（",
        math(String.raw`\lambda_{\mathrm{exc}}=\lambda_1`),
        "）はレベルで層別せず直接数える。",
        math(String.raw`\nu(x)=\alpha<n`),
        " なる ",
        math(String.raw`x`),
        " は ",
        math(String.raw`\ell^{n-\alpha-1}(\ell-1)`),
        " 個なので",
      ]),
      displayMath(
        String.raw`\varphi_n\Sigma_n=\sum_{\beta=0}^{n-1}\ell^{n}\,\ell^{n-\beta-1}(\ell-1)\cdot2\ell^{\beta}
        +\sum_{\alpha=0}^{n-1}\ell^{n-\alpha-1}(\ell-1)\bigl(\lambda_1\varphi_n+2\ell^{\alpha}\bigr)
        =\varphi_n\bigl[2n\ell^{n}+\lambda_1(\ell^{n}-1)+2n\bigr]`,
      ),
      paragraph([
        "であり、場合 [B′] は対称である。いずれも ",
        math(String.raw`\Sigma_n=2n\ell^{n}+\lambda_{\mathrm{exc}}\,(\ell^{n}-1)+2n`),
        " なので (0) に入れて ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)=\mu(\ell^{2n}-1)+2n\ell^{n}+\lambda_{\mathrm{exc}}\,(\ell^{n}-1)`),
        " を得る。",
        math(String.raw`n=0`),
        " では両辺 ",
        math(String.raw`0`),
        " である。",
      ]),
      paragraph([
        "",
        math(String.raw`n\ell^{n}`),
        " 項の出所。 上の内訳で、例外直線上の点の寄与は ",
        math(String.raw`2\bigl[\lambda_0(\ell^{n}-1)+2n\bigr]`),
        " であり（(G′2) の寄与の式と一致する）、",
        math(String.raw`n\ell^{n}`),
        " 項を含む主要部を出すのは ",
        math(String.raw`r\ge1`),
        " の点、すなわち消滅深度が ",
        math(String.raw`1+\ell^{r}`),
        " と幾何級数的に深くなる点の層である。したがって型 III の ",
        math(String.raw`n\ell^{n}`),
        " 項は ",
        math(String.raw`\theta=\infty`),
        " の点そのものではなく、その ",
        math(String.raw`\ell`),
        " 進近傍の集積から出る。",
      ]),
      paragraph([
        "最後に 3 分割を確かめる。 ",
        math(String.raw`\ell\nmid p'q'(p'+q')`),
        " とすると、",
        math(String.raw`H=-(p'T^2+q'S^2)`),
        " の ",
        math(String.raw`\mathbb{P}^1(\mathbb{F}_\ell)`),
        " 零点は ",
        math(String.raw`T^2/S^2=-q'/p'`),
        " の解なので、非退化 ",
        math(String.raw`\iff-q'/p'`),
        " が平方でない。退化方向 ",
        math(String.raw`(a,b)`),
        "（",
        math(String.raw`\ell\nmid ab`),
        "、",
        math(String.raw`p'a^2+q'b^2\equiv0`),
        "）では ",
        math(String.raw`F_c(x):=(1+x)^{c}+(1+x)^{-c}-2`),
        " の低次係数が ",
        math(String.raw`0,0,c^2,-c^2,(c^4+11c^2)/12`),
        " なので ",
        math(String.raw`\bar A_2=\bar A_3=0`),
        " かつ ",
        math(String.raw`\bar A_4=(p'a^4+q'b^4)/12`),
        "（",
        math(String.raw`\ell\ge5`),
        " で ",
        math(String.raw`12`),
        " は単元）。",
        math(String.raw`q'b^2=-p'a^2`),
        " より ",
        math(String.raw`p'a^4+q'b^4=p'a^4(p'+q')/q'\neq0`),
        " なので ",
        math(String.raw`\theta(P)=4`),
        "、非退化方向では ",
        math(String.raw`\theta=2`),
        " である。よって全方向で ",
        math(String.raw`\theta\le4\le\ell`),
        " となり ",
        ref("paper_prop_G"),
        " (G6) が使える。",
        math(String.raw`\ell=3`),
        " では平方剰余が ",
        math(String.raw`\{1\}`),
        " だけなので、退化 ",
        math(String.raw`\iff-q'/p'\equiv1\iff\ell\mid p'+q'`),
        " となり中間の場合は空である。",
      ]),
      paragraph([
        "射程の限界について。 主張に挙げた反例（",
        math(String.raw`\ell=3`),
        "、voltage ",
        math(String.raw`(1,0),(1,-1),(1,2)`),
        "）の値 ",
        math(String.raw`0,10,50`),
        " は塔の値からの独立計算で得たものであり、素朴に延長した式の値 ",
        math(String.raw`0,8,44`),
        " と食い違う。したがって上の計数が使えたのは、この族で ",
        math(String.raw`\bar{\tilde E}`),
        " が二項式の積へ分解し、層ごとの消滅深度が ",
        math(String.raw`1+\ell^{r}`),
        " という具体形をもつことによる。また ",
        math(String.raw`\ell=2`),
        " では上の証明が 3 箇所で通らない（",
        math(String.raw`2`),
        " が単元であること、",
        math(String.raw`a'\equiv b'`),
        " と ",
        math(String.raw`a'\equiv-b'`),
        " が排反であること、",
        math(String.raw`\ell-1\ge2`),
        " による狭義不等号）。その場合の決着は ",
        ref("paper_prop_G_ell2"),
        " である。",
      ]),
    ],
  },
]);
