/**
 * 論文本体 第 5 章の続き（2）: 命題 G″（ℓ = 2 の bouquet 族の閉形式）。
 *
 * 命題 G′ の (G′3) は「ℓ が奇である」ことを 3 箇所で使っており、ℓ = 2 を射程外に置いていた。
 * 本ブロックはその 3 箇所を修復し、族 p(1,0)+q(0,1) について ℓ = 2 でも
 *   (G″1) 場合分けが排反かつ網羅であること、
 *   (G″2) 族が例外なく型 III であること、
 *   (G″3) 全レベル・全点の付値（ℓ 奇に無い 2 つの枝＝飽和・打ち消し）、
 *   (G″4) 全ての n の閉形式（4 通り）、
 *   (G″5) 命題 G′ (G′3) が ℓ = 2 で正しい範囲
 * を述べる。根拠レポートは outputs/reports/cycle20_T3_ell_equals_2.md。
 *
 * **射程は族に限る。** 一般の ℓ = 2 塔の閉形式は得られていない（限界に明記した）。
 *
 * 本章の主張はすべて Z・Z/2^m・Q(ζ_{2^m}) の中で閉じる（ℝ を使わない）。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_056_theorem_ell2_family",
    kind: "theorem",
    origin: { path: "structured-latex/content/005c_ell2_family.ts", ordinal: 1 },
    title: {
      text: "命題 G″ — ℓ = 2 の bouquet 族: 飽和と打ち消し、そして 4 通りの閉形式",
    },
    labels: ["paper_prop_G_ell2"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle20_T3_ell2"],
    statement: [
      paragraph([
        math(String.raw`\ell=2`),
        " とし、",
        math(String.raw`X(p,q)`),
        " を ",
        ref("paper_prop_G_infty"),
        " (G′3) と同じ 1 頂点の bouquet（voltage ",
        math(String.raw`(1,0)`),
        " のループ ",
        math(String.raw`p`),
        " 本、",
        math(String.raw`(0,1)`),
        " のループ ",
        math(String.raw`q`),
        " 本、",
        math(String.raw`p,q\ge1`),
        "）とする。底グラフは 1 頂点なので ",
        math(String.raw`\kappa(X)=1`),
        "、サイクル voltage 格子は ",
        math(String.raw`\mathbb{Z}^2`),
        " なので**塔の全段が連結という仮定は全ての ",
        math(String.raw`n`),
        " で自動的に満たされる**。",
        math(String.raw`f_z:=z+z^{-1}-2`),
        "、",
        math(String.raw`f_w:=w+w^{-1}-2`),
        " と置くと ",
        math(String.raw`D=\det L=-(p\,f_z+q\,f_w)`),
        " で、",
        math(String.raw`\mu=v_2(\gcd(p,q))`),
        "、",
        math(String.raw`p':=p/2^{\mu}`),
        "、",
        math(String.raw`q':=q/2^{\mu}`),
        "、",
        math(String.raw`E=2^{-\mu}D=-(p'f_z+q'f_w)`),
        " である。とくに ",
        math(String.raw`p'`),
        " と ",
        math(String.raw`q'`),
        " が同時に偶になることはない。次の 2 つの場合に分ける。",
      ]),
      list([
        [
          "**case A**: ",
          math(String.raw`p',q'`),
          " がともに奇。",
          math(String.raw`\lambda_0:=v_2(p'+q')\ \ (\ge1)`),
          "、",
          math(String.raw`\lambda_-:=v_2(p'-q')`),
          "（",
          math(String.raw`p'=q'`),
          " なら ",
          math(String.raw`+\infty`),
          "）。",
        ],
        [
          "**case B**: 一方が偶。偶な側の係数を ",
          math(String.raw`c_e`),
          "、奇な側を ",
          math(String.raw`c_o`),
          " と書き、",
          math(String.raw`\lambda_1:=v_2(c_e)\ \ (\ge1)`),
          "、",
          math(String.raw`w:=v_2\bigl(c_e/2+c_o\bigr)`),
          " と置く（",
          math(String.raw`\lambda_1=1`),
          " なら ",
          math(String.raw`c_e/2`),
          " は奇で ",
          math(String.raw`c_o`),
          " も奇なので ",
          math(String.raw`w\ge1`),
          "。",
          math(String.raw`\lambda_1\ge2`),
          " なら ",
          math(String.raw`w=0`),
          " で、下では使わない）。",
        ],
      ]),
      paragraph([
        "**(G″1 場合分けが排反かつ網羅であること)** ",
        math(String.raw`p',q'`),
        " がともに奇なら ",
        math(String.raw`\lambda_0\neq\lambda_-`),
        " かつ ",
        math(String.raw`\min(\lambda_0,\lambda_-)=1`),
        " である。したがって case A は ",
        math(String.raw`\lambda_0=1`),
        "（case A",
        math(String.raw`\alpha`),
        "。トーラス ",
        math(String.raw`(p,q)=(1,1)`),
        " はここ）と ",
        math(String.raw`\lambda_0\ge2`),
        "（case A",
        math(String.raw`\beta`),
        "）に排反に分かれる。同様に、",
        math(String.raw`m\ge2`),
        " で ",
        math(String.raw`a',b'`),
        " がともに奇なら ",
        math(String.raw`s:=v_2(a'-b')`),
        "、",
        math(String.raw`t:=v_2(a'+b')`),
        " は ",
        math(String.raw`s,t\ge1`),
        "、",
        math(String.raw`\min(s,t)=1`),
        " を満たし、",
        math(String.raw`s\ge m`),
        " と ",
        math(String.raw`t\ge m`),
        " が同時に起きることはない。**以下の場合分けが排反かつ網羅であることは、この 2 つの主張なしには言えない。**",
      ]),
      paragraph([
        "**(G″2 この族は例外なく型 III)** 全ての ",
        math(String.raw`p,q\ge1`),
        " で ",
        math(String.raw`X(p,q)`),
        " の塔は退化であり、しかも ",
        math(String.raw`\theta=\infty`),
        " の点をもつ。すなわち ",
        math(String.raw`n2^{n}`),
        " 項を持つ（型 III）。",
        ref("paper_prop_G_infty"),
        " (G′3) が ",
        math(String.raw`\ell`),
        " 奇で与えた 3 分割（非退化 / 例外直線なし / 例外直線あり）のうち、",
        math(String.raw`\ell=2`),
        " ではこの族について前 2 者が**空**になる。",
        "**ただしこれは族に固有の性質であって、",
        math(String.raw`\ell=2`),
        " の一般の塔の性質ではない**（下の限界を見よ）。",
      ]),
      paragraph([
        "**(G″3 点ごとの付値。",
        math(String.raw`\ell`),
        " 奇に無い 2 つの枝)** ",
        math(String.raw`n\ge1`),
        "、",
        math(String.raw`g`),
        " を原始 ",
        math(String.raw`2^{n}`),
        " 乗根、",
        math(String.raw`(a,b)\in(\mathbb{Z}/2^{n})^{2}\setminus\{0\}`),
        " とし、",
        math(String.raw`\varepsilon:=\min(v_2(a),v_2(b))`),
        "、",
        math(String.raw`m:=n-\varepsilon\ (\ge1)`),
        "、",
        math(String.raw`h:=g^{2^{\varepsilon}}`),
        "（原始 ",
        math(String.raw`2^{m}`),
        " 乗根）、",
        math(String.raw`a':=a/2^{\varepsilon}`),
        "、",
        math(String.raw`b':=b/2^{\varepsilon}`),
        "、",
        math(String.raw`\varphi_m:=\varphi(2^{m})=2^{m-1}`),
        " と置く（",
        math(String.raw`E(g^a,g^b)=-(p'f_h(a')+q'f_h(b'))`),
        "）。",
      ]),
      paragraph([
        "**[A]（",
        math(String.raw`p',q'`),
        " ともに奇）** ",
        math(String.raw`m\ge2`),
        " かつ ",
        math(String.raw`a',b'`),
        " がともに奇のとき、",
        math(String.raw`r:=\max(s,t)`),
        " として",
      ]),
      displayMath(
        String.raw`\varphi_m\,v_2\bigl(E(h^{a'},h^{b'})\bigr)=
        \begin{cases}
        \lambda_0\varphi_m+2 & (r\ge m,\ \text{すなわち } a'\equiv\pm b'\ \text{。例外直線上})\\
        2^{m} & (\lambda_0=1\ \text{かつ}\ r=m-1\ \text{。}\textbf{飽和})\\
        2+2^{\,r} & (2\le r\le m-1).
        \end{cases}`,
      ),
      paragraph([
        math(String.raw`a',b'`),
        " の一方だけが奇なら ",
        math(String.raw`\varphi_m v_2(E)=2`),
        "。",
        math(String.raw`m=1`),
        " では ",
        math(String.raw`v_2(E)=2+\lambda_0`),
        "（",
        math(String.raw`a'=b'=1`),
        "）または ",
        math(String.raw`2`),
        "（一方が ",
        math(String.raw`0`),
        "）である。",
      ]),
      paragraph([
        "**[B]（一方が偶）** この場合は ",
        math(String.raw`m=n`),
        " でよい。",
        math(String.raw`c_e,c_o`),
        " に対応する指数を ",
        math(String.raw`a_e,a_o`),
        " と書き",
      ]),
      displayMath(
        String.raw`U_e:=\lambda_1\varphi_n+2^{\,v_2(a_e)+1},\qquad U_o:=2^{\,v_2(a_o)+1}`,
      ),
      paragraph([
        "と置く（",
        math(String.raw`a_e\equiv0`),
        " なら ",
        math(String.raw`U_e=+\infty`),
        "、",
        math(String.raw`a_o\equiv0`),
        " なら ",
        math(String.raw`U_o=+\infty`),
        "）。",
        math(String.raw`U_e\neq U_o`),
        " なら ",
        math(String.raw`\varphi_n v_2(E)=\min(U_e,U_o)`),
        " である。",
        math(String.raw`U_e=U_o<\infty`),
        " となるのは ",
        math(String.raw`\lambda_1=1`),
        " かつ ",
        math(String.raw`\bigl(v_2(a_e),v_2(a_o)\bigr)=(n-2,\,n-1)`),
        " のとき、**そのときに限る**（したがって ",
        math(String.raw`n\ge2`),
        " が必要）。そこでの真の値は",
      ]),
      displayMath(String.raw`v_2\bigl(E\bigr)=2+w,\qquad w=v_2\bigl(c_e/2+c_o\bigr)\ge1,`),
      paragraph([
        "であり、素朴な ",
        math(String.raw`\min(U_e,U_o)/\varphi_n=2`),
        " より**狭義に深い**（**打ち消し**）。",
      ]),
      paragraph([
        "**飽和と打ち消しは ",
        math(String.raw`\ell`),
        " 奇には無い枝である。** 飽和は ",
        math(String.raw`1+h^{N}=0`),
        "（すなわち ",
        math(String.raw`h^{N}=-1`),
        "）に由来し、これは ",
        math(String.raw`a'\mp b'`),
        " が**ともに偶**であることの帰結なので ",
        math(String.raw`\ell`),
        " 奇では起こり得ない。打ち消しで降りる先は**指数の次の桁ではなく係数 ",
        math(String.raw`c_e`),
        " の次の ",
        math(String.raw`2`),
        " 進桁 ",
        math(String.raw`w`),
        "** であり、**1 段で閉じる**。",
      ]),
      paragraph([
        "**(G″4 閉形式)** 全ての ",
        math(String.raw`n\ge1`),
        " で",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_2(\kappa_n)=\mu\,(4^{n}-1)+
        \begin{cases}
        2n\,2^{n}+4\cdot2^{n}-6n-1 & (\text{A}\alpha:\ \lambda_0=1)\\
        2n\,2^{n}+2\lambda_0\,2^{n}-2n-3\lambda_0+2 & (\text{A}\beta:\ \lambda_0\ge2)\\
        2n\,2^{n}+\lambda_1\,(2^{n}-1) & (\text{B}:\ \lambda_1\ge2\text{、および }\text{B}\text{ かつ }\lambda_1=1\text{ の } n=1)\\
        2n\,2^{n}+2n-1+2w & (\text{B}:\ \lambda_1=1,\ n\ge2).
        \end{cases}`,
      ),
      paragraph([
        "**第 4 行が ",
        math(String.raw`n\ge2`),
        " に限られるのは打ち消しの条件 ",
        math(String.raw`v_2(a_e)=n-2`),
        " が ",
        math(String.raw`n=1`),
        " では実現しないためであり、",
        math(String.raw`n=1`),
        " は第 3 行が与える。** ",
        ref("paper_prop_W"),
        " の 5 係数でいうと ",
        math(String.raw`a=\mu`),
        "、",
        math(String.raw`b=2`),
        " は 4 つの場合すべてで共通で、",
        math(String.raw`(c,d)`),
        " はそれぞれ ",
        math(String.raw`(4,-6)`),
        "、",
        math(String.raw`(2\lambda_0,-2)`),
        "、",
        math(String.raw`(\lambda_1,0)`),
        "、",
        math(String.raw`(0,+2)`),
        " である。とくに ",
        math(String.raw`n\,2^{n}`),
        " の係数は 4 つの場合すべてで ",
        math(String.raw`2`),
        " であり、",
        ref("paper_prop_G_infty"),
        " (G′3) の ",
        math(String.raw`\ell`),
        " 奇の値と**同じ**である。差が出るのは ",
        math(String.raw`2^{n}`),
        " の係数と ",
        math(String.raw`n`),
        " の係数、および ",
        math(String.raw`\ell`),
        " 奇には無い不変量 ",
        math(String.raw`w`),
        " を要することである。",
      ]),
      paragraph([
        "**(G″5 ",
        ref("paper_prop_G_infty"),
        " (G′3) が ",
        math(String.raw`\ell=2`),
        " で正しい範囲)** (G′3) の閉形式 ",
        math(String.raw`\mu(\ell^{2n}-1)+2n\ell^{n}+\Lambda(\ell^{n}-1)`),
        " を ",
        math(String.raw`\ell=2`),
        " に当てたものが全ての ",
        math(String.raw`n\ge1`),
        " で正しいのは、**case B かつ ",
        math(String.raw`\lambda_1\ge2`),
        " のとき、そのときに限る**（このとき ",
        math(String.raw`\Lambda=\lambda_1`),
        "）。他の 3 つの場合は (G′3) の式が持たない ",
        math(String.raw`n`),
        " の線形項（それぞれ ",
        math(String.raw`-6n,\ -2n,\ +2n`),
        "）を持つので一致しない。",
      ]),
      paragraph([
        "**実数体を使っていないことの明示**: 使ったのは (a) ",
        math(String.raw`\mathbb{Q}(\zeta_{2^{m}})`),
        "（",
        math(String.raw`\mathbb{Q}`),
        " の可算な代数拡大）の ",
        math(String.raw`2`),
        " の上の唯一の素点での付値、(b) ",
        math(String.raw`\mathbb{Z}`),
        " の ",
        math(String.raw`2`),
        " 進付値、(c) ",
        math(String.raw`\mathbb{Z}/2^{m}`),
        " 上の有限計算だけである。",
      ]),
      paragraph([
        "**限界（主張の一部として述べる）**",
      ]),
      list([
        [
          "**本命題は族 ",
          math(String.raw`p(1,0)+q(0,1)`),
          " に限る。一般の ",
          math(String.raw`\ell=2`),
          " 塔の閉形式は得られていない。** 本命題の証明で効いたのは ",
          math(String.raw`\bar{\tilde E}`),
          " が二項式の積に分解し、層ごとの消滅深度が ",
          math(String.raw`2+2^{r}`),
          " という具体形をもつことである。一般の塔では飽和が起きる「定数項」に相当する量の ",
          math(String.raw`2`),
          " 進付値が場合により変わるため、層の構造が族ほど単純にならない。",
        ],
        [
          "**族の外の一般の ",
          math(String.raw`\ell=2`),
          " 塔でも ",
          math(String.raw`n2^{n}`),
          " の係数が ",
          math(String.raw`b=\sum_{P\in S_\infty}j^{*}(P)`),
          "（",
          ref("paper_prop_K"),
          " (K6)）になることは、数値支持どまりであって証明ではない。** 宣言した母集団（辺数 ",
          math(String.raw`\le3`),
          " の 430 塔）の全走査で対象となった 174 塔すべてで一致し不一致は 0 だが、これは**その有限母集団に対する判定**であって母集団の外については何も主張しない（標本と見なすなら、除外できるのは破れ率 ",
          math(String.raw`1.7\%`),
          " までである）。",
        ],
        [
          "**(G″2) の「常に型 III」は族に固有である。** 同じ母集団には ",
          math(String.raw`b=0`),
          "（型 II）の ",
          math(String.raw`\ell=2`),
          " 塔が 39 個ある。同様に、母集団で ",
          math(String.raw`n`),
          " の係数が ",
          math(String.raw`0`),
          " の塔が 1 個も無いことも母集団の設計（辺数の制限）の帰結であって ",
          math(String.raw`\ell=2`),
          " 一般の性質ではない。**0 件の観察を性質として読まない。**",
        ],
        [
          ref("paper_prop_J"),
          " (J4) の仮定（十分深いレベルで最小点が一意）は、この族の ",
          math(String.raw`\ell=2`),
          " では case A の全組と case B・",
          math(String.raw`\lambda_1=1`),
          " の組で破れ、case B・",
          math(String.raw`\lambda_1\ge2`),
          " でのみ成り立つ（(G″5) の場合分けとちょうど一致する）。**この破れが ",
          math(String.raw`\ell=2`),
          " に固有だとは主張しない**（",
          ref("paper_prop_K"),
          " の限界のとおり、奇素数でも破れる塔がある）。それでも ",
          math(String.raw`n2^{n}`),
          " の係数は 4 つの場合とも ",
          math(String.raw`2`),
          " で、",
          math(String.raw`\sum_{P\in S_\infty}j^{*}(P)`),
          " も全組で ",
          math(String.raw`2`),
          " である（case A では ",
          math(String.raw`S_\infty`),
          " が 2 点で各 ",
          math(String.raw`j^{*}=1`),
          "、case B では 1 点で ",
          math(String.raw`j^{*}=2`),
          "）。",
        ],
        [
          "**最小点が同点になる箇所でも、値そのものは ",
          ref("paper_prop_R"),
          " (R4) の終結式公式が無条件に与える。** したがって ",
          math(String.raw`w`),
          " は「値を計算するために必要な量」ではなく「**値を ",
          math(String.raw`(p,q)`),
          " の不変量として閉形式に載せるために必要な量**」である。",
        ],
        [
          "本命題は ",
          math(String.raw`d=2`),
          " に限る。",
        ],
        [
          "**新規性は主張しない。** A",
          math(String.raw`\alpha`),
          " の値（トーラス ",
          math(String.raw`(p,q)=(1,1)`),
          " では ",
          math(String.raw`\mathrm{ord}_2(\kappa_n)=2n2^{n}+4\cdot2^{n}-6n-1`),
          "）そのものは DuBose–Vallières（Alg. Comb. 6 (2023), alco.304）§7 例 (1) に数値例として現れる。",
          "また「",
          math(String.raw`\mathbb{Z}_\ell`),
          " 拡大の岩澤不変量で ",
          math(String.raw`\ell=2`),
          " が特別に振る舞う」こと自体は岩澤理論では標準的な現象であり、本命題の内容が Monsky / Cuoco–Monsky の枠組みで既に扱われている可能性は高い。**確認できていない。**",
        ],
      ]),
    ],
  },
]);
