/**
 * 論文本体 第 5 章の続き（2）: 命題 G″（ℓ = 2 の bouquet 族の閉形式）。
 *
 * 命題 G′ の (G′3) は「ℓ が奇である」ことを 3 箇所で使っており、ℓ = 2 を射程外に置いていた。
 * 本ブロックはその 3 箇所を修復し、族 p(1,0)+q(0,1) について ℓ = 2 でも
 *   (G″1) 場合分けが排反かつ網羅であること、
 *   (G″2) 族が例外なく型 III であること、
 *   (G″3) 全レベル・全点の付値（ℓ 奇に無い 2 つの枝＝飽和・打ち消し）、
 *   (G″4) 全ての n の閉形式（4 通り）、
 *   (G″5) 命題 G′ (G′3) が ℓ = 2 で正しい範囲
 * を述べる。根拠レポートは outputs/reports/cycle20_T3_ell_equals_2.md。
 *
 * **射程は族に限る。** 一般の ℓ = 2 塔の閉形式は得られていない（限界に明記した）。
 *
 * 本章の主張はすべて Z・Z/2^m・Q(ζ_{2^m}) の中で閉じる（ℝ を使わない）。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_056_theorem_ell2_family",
    kind: "theorem",
    origin: { path: "structured-latex/content/005c_ell2_family.ts", ordinal: 1 },
    title: {
      text: "命題 G″ — ℓ = 2 の bouquet 族: 飽和と打ち消し、そして 4 通りの閉形式",
    },
    labels: ["paper_prop_G_ell2"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle20_T3_ell2"],
    lean: [
      "IntegrableLattice.gpp1_both_even",
      "IntegrableLattice.gpp1_not_both_four",
      "IntegrableLattice.gpp1_lambda_ne",
      "IntegrableLattice.gpp1_st_not_both_ge",
    ],
    statement: [
      paragraph([
        math(String.raw`\ell=2`),
        " とし、",
        math(String.raw`X(p,q)`),
        " を ",
        ref("paper_prop_G_infty"),
        " (G′3) と同じ 1 頂点の bouquet（voltage ",
        math(String.raw`(1,0)`),
        " のループ ",
        math(String.raw`p`),
        " 本、",
        math(String.raw`(0,1)`),
        " のループ ",
        math(String.raw`q`),
        " 本、",
        math(String.raw`p,q\ge1`),
        "）とする。底グラフは 1 頂点なので ",
        math(String.raw`\kappa(X)=1`),
        "、サイクル voltage 格子は ",
        math(String.raw`\mathbb{Z}^2`),
        " なので**塔の全段が連結という仮定は全ての ",
        math(String.raw`n`),
        " で自動的に満たされる**。",
        math(String.raw`f_z:=z+z^{-1}-2`),
        "、",
        math(String.raw`f_w:=w+w^{-1}-2`),
        " と置くと ",
        math(String.raw`D=\det L=-(p\,f_z+q\,f_w)`),
        " で、",
        math(String.raw`\mu=v_2(\gcd(p,q))`),
        "、",
        math(String.raw`p':=p/2^{\mu}`),
        "、",
        math(String.raw`q':=q/2^{\mu}`),
        "、",
        math(String.raw`E=2^{-\mu}D=-(p'f_z+q'f_w)`),
        " である。とくに ",
        math(String.raw`p'`),
        " と ",
        math(String.raw`q'`),
        " が同時に偶になることはない。次の 2 つの場合に分ける。",
      ]),
      list([
        [
          "**case A**: ",
          math(String.raw`p',q'`),
          " がともに奇。",
          math(String.raw`\lambda_0:=v_2(p'+q')\ \ (\ge1)`),
          "、",
          math(String.raw`\lambda_-:=v_2(p'-q')`),
          "（",
          math(String.raw`p'=q'`),
          " なら ",
          math(String.raw`+\infty`),
          "）。",
        ],
        [
          "**case B**: 一方が偶。偶な側の係数を ",
          math(String.raw`c_e`),
          "、奇な側を ",
          math(String.raw`c_o`),
          " と書き、",
          math(String.raw`\lambda_1:=v_2(c_e)\ \ (\ge1)`),
          "、",
          math(String.raw`w:=v_2\bigl(c_e/2+c_o\bigr)`),
          " と置く（",
          math(String.raw`\lambda_1=1`),
          " なら ",
          math(String.raw`c_e/2`),
          " は奇で ",
          math(String.raw`c_o`),
          " も奇なので ",
          math(String.raw`w\ge1`),
          "。",
          math(String.raw`\lambda_1\ge2`),
          " なら ",
          math(String.raw`w=0`),
          " で、下では使わない）。",
        ],
      ]),
      paragraph([
        "**(G″1 場合分けが排反かつ網羅であること)** ",
        math(String.raw`p',q'`),
        " がともに奇なら ",
        math(String.raw`\lambda_0\neq\lambda_-`),
        " かつ ",
        math(String.raw`\min(\lambda_0,\lambda_-)=1`),
        " である。したがって case A は ",
        math(String.raw`\lambda_0=1`),
        "（case A",
        math(String.raw`\alpha`),
        "。トーラス ",
        math(String.raw`(p,q)=(1,1)`),
        " はここ）と ",
        math(String.raw`\lambda_0\ge2`),
        "（case A",
        math(String.raw`\beta`),
        "）に排反に分かれる。同様に、",
        math(String.raw`m\ge2`),
        " で ",
        math(String.raw`a',b'`),
        " がともに奇なら ",
        math(String.raw`s:=v_2(a'-b')`),
        "、",
        math(String.raw`t:=v_2(a'+b')`),
        " は ",
        math(String.raw`s,t\ge1`),
        "、",
        math(String.raw`\min(s,t)=1`),
        " を満たし、",
        math(String.raw`s\ge m`),
        " と ",
        math(String.raw`t\ge m`),
        " が同時に起きることはない。**以下の場合分けが排反かつ網羅であることは、この 2 つの主張なしには言えない。**",
      ]),
      paragraph([
        "**(G″2 この族は例外なく型 III)** 全ての ",
        math(String.raw`p,q\ge1`),
        " で ",
        math(String.raw`X(p,q)`),
        " の塔は退化であり、しかも ",
        math(String.raw`\theta=\infty`),
        " の点をもつ。すなわち ",
        math(String.raw`n2^{n}`),
        " 項を持つ（型 III）。",
        ref("paper_prop_G_infty"),
        " (G′3) が ",
        math(String.raw`\ell`),
        " 奇で与えた 3 分割（非退化 / 例外直線なし / 例外直線あり）のうち、",
        math(String.raw`\ell=2`),
        " ではこの族について前 2 者が**空**になる。",
        "**ただしこれは族に固有の性質であって、",
        math(String.raw`\ell=2`),
        " の一般の塔の性質ではない**（下の限界を見よ）。",
      ]),
      paragraph([
        "**(G″3 点ごとの付値。",
        math(String.raw`\ell`),
        " 奇に無い 2 つの枝)** ",
        math(String.raw`n\ge1`),
        "、",
        math(String.raw`g`),
        " を原始 ",
        math(String.raw`2^{n}`),
        " 乗根、",
        math(String.raw`(a,b)\in(\mathbb{Z}/2^{n})^{2}\setminus\{0\}`),
        " とし、",
        math(String.raw`\varepsilon:=\min(v_2(a),v_2(b))`),
        "、",
        math(String.raw`m:=n-\varepsilon\ (\ge1)`),
        "、",
        math(String.raw`h:=g^{2^{\varepsilon}}`),
        "（原始 ",
        math(String.raw`2^{m}`),
        " 乗根）、",
        math(String.raw`a':=a/2^{\varepsilon}`),
        "、",
        math(String.raw`b':=b/2^{\varepsilon}`),
        "、",
        math(String.raw`\varphi_m:=\varphi(2^{m})=2^{m-1}`),
        " と置く（",
        math(String.raw`E(g^a,g^b)=-(p'f_h(a')+q'f_h(b'))`),
        "）。",
      ]),
      paragraph([
        "**[A]（",
        math(String.raw`p',q'`),
        " ともに奇）** ",
        math(String.raw`m\ge2`),
        " かつ ",
        math(String.raw`a',b'`),
        " がともに奇のとき、",
        math(String.raw`r:=\max(s,t)`),
        " として",
      ]),
      displayMath(
        String.raw`\varphi_m\,v_2\bigl(E(h^{a'},h^{b'})\bigr)=
        \begin{cases}
        \lambda_0\varphi_m+2 & (r\ge m,\ \text{すなわち } a'\equiv\pm b'\ \text{。例外直線上})\\
        2^{m} & (\lambda_0=1\ \text{かつ}\ r=m-1\ \text{。}\textbf{飽和})\\
        2+2^{\,r} & (2\le r\le m-1).
        \end{cases}`,
      ),
      paragraph([
        math(String.raw`a',b'`),
        " の一方だけが奇なら ",
        math(String.raw`\varphi_m v_2(E)=2`),
        "。",
        math(String.raw`m=1`),
        " では ",
        math(String.raw`v_2(E)=2+\lambda_0`),
        "（",
        math(String.raw`a'=b'=1`),
        "）または ",
        math(String.raw`2`),
        "（一方が ",
        math(String.raw`0`),
        "）である。",
      ]),
      paragraph([
        "**[B]（一方が偶）** この場合は ",
        math(String.raw`m=n`),
        " でよい。",
        math(String.raw`c_e,c_o`),
        " に対応する指数を ",
        math(String.raw`a_e,a_o`),
        " と書き",
      ]),
      displayMath(
        String.raw`U_e:=\lambda_1\varphi_n+2^{\,v_2(a_e)+1},\qquad U_o:=2^{\,v_2(a_o)+1}`,
      ),
      paragraph([
        "と置く（",
        math(String.raw`a_e\equiv0`),
        " なら ",
        math(String.raw`U_e=+\infty`),
        "、",
        math(String.raw`a_o\equiv0`),
        " なら ",
        math(String.raw`U_o=+\infty`),
        "）。",
        math(String.raw`U_e\neq U_o`),
        " なら ",
        math(String.raw`\varphi_n v_2(E)=\min(U_e,U_o)`),
        " である。",
        math(String.raw`U_e=U_o<\infty`),
        " となるのは ",
        math(String.raw`\lambda_1=1`),
        " かつ ",
        math(String.raw`\bigl(v_2(a_e),v_2(a_o)\bigr)=(n-2,\,n-1)`),
        " のとき、**そのときに限る**（したがって ",
        math(String.raw`n\ge2`),
        " が必要）。そこでの真の値は",
      ]),
      displayMath(String.raw`v_2\bigl(E\bigr)=2+w,\qquad w=v_2\bigl(c_e/2+c_o\bigr)\ge1,`),
      paragraph([
        "であり、素朴な ",
        math(String.raw`\min(U_e,U_o)/\varphi_n=2`),
        " より**狭義に深い**（**打ち消し**）。",
      ]),
      paragraph([
        "**飽和と打ち消しは ",
        math(String.raw`\ell`),
        " 奇には無い枝である。** 飽和は ",
        math(String.raw`1+h^{N}=0`),
        "（すなわち ",
        math(String.raw`h^{N}=-1`),
        "）に由来し、これは ",
        math(String.raw`a'\mp b'`),
        " が**ともに偶**であることの帰結なので ",
        math(String.raw`\ell`),
        " 奇では起こり得ない。打ち消しで降りる先は**指数の次の桁ではなく係数 ",
        math(String.raw`c_e`),
        " の次の ",
        math(String.raw`2`),
        " 進桁 ",
        math(String.raw`w`),
        "** であり、**1 段で閉じる**。",
      ]),
      paragraph([
        "**(G″4 閉形式)** 全ての ",
        math(String.raw`n\ge1`),
        " で",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_2(\kappa_n)=\mu\,(4^{n}-1)+
        \begin{cases}
        2n\,2^{n}+4\cdot2^{n}-6n-1 & (\text{A}\alpha:\ \lambda_0=1)\\
        2n\,2^{n}+2\lambda_0\,2^{n}-2n-3\lambda_0+2 & (\text{A}\beta:\ \lambda_0\ge2)\\
        2n\,2^{n}+\lambda_1\,(2^{n}-1) & (\text{B}:\ \lambda_1\ge2\text{、および }\text{B}\text{ かつ }\lambda_1=1\text{ の } n=1)\\
        2n\,2^{n}+2n-1+2w & (\text{B}:\ \lambda_1=1,\ n\ge2).
        \end{cases}`,
      ),
      paragraph([
        "**第 4 行が ",
        math(String.raw`n\ge2`),
        " に限られるのは打ち消しの条件 ",
        math(String.raw`v_2(a_e)=n-2`),
        " が ",
        math(String.raw`n=1`),
        " では実現しないためであり、",
        math(String.raw`n=1`),
        " は第 3 行が与える。** ",
        ref("paper_prop_W"),
        " の 5 係数でいうと ",
        math(String.raw`a=\mu`),
        "、",
        math(String.raw`b=2`),
        " は 4 つの場合すべてで共通で、",
        math(String.raw`(c,d)`),
        " はそれぞれ ",
        math(String.raw`(4,-6)`),
        "、",
        math(String.raw`(2\lambda_0,-2)`),
        "、",
        math(String.raw`(\lambda_1,0)`),
        "、",
        math(String.raw`(0,+2)`),
        " である。とくに ",
        math(String.raw`n\,2^{n}`),
        " の係数は 4 つの場合すべてで ",
        math(String.raw`2`),
        " であり、",
        ref("paper_prop_G_infty"),
        " (G′3) の ",
        math(String.raw`\ell`),
        " 奇の値と**同じ**である。差が出るのは ",
        math(String.raw`2^{n}`),
        " の係数と ",
        math(String.raw`n`),
        " の係数、および ",
        math(String.raw`\ell`),
        " 奇には無い不変量 ",
        math(String.raw`w`),
        " を要することである。",
      ]),
      paragraph([
        "**(G″5 ",
        ref("paper_prop_G_infty"),
        " (G′3) が ",
        math(String.raw`\ell=2`),
        " で正しい範囲)** (G′3) の閉形式 ",
        math(String.raw`\mu(\ell^{2n}-1)+2n\ell^{n}+\Lambda(\ell^{n}-1)`),
        " を ",
        math(String.raw`\ell=2`),
        " に当てたものが全ての ",
        math(String.raw`n\ge1`),
        " で正しいのは、**case B かつ ",
        math(String.raw`\lambda_1\ge2`),
        " のとき、そのときに限る**（このとき ",
        math(String.raw`\Lambda=\lambda_1`),
        "）。他の 3 つの場合は (G′3) の式が持たない ",
        math(String.raw`n`),
        " の線形項（それぞれ ",
        math(String.raw`-6n,\ -2n,\ +2n`),
        "）を持つので一致しない。",
      ]),
      paragraph([
        "**実数体を使っていないことの明示**: 使ったのは (a) ",
        math(String.raw`\mathbb{Q}(\zeta_{2^{m}})`),
        "（",
        math(String.raw`\mathbb{Q}`),
        " の可算な代数拡大）の ",
        math(String.raw`2`),
        " の上の唯一の素点での付値、(b) ",
        math(String.raw`\mathbb{Z}`),
        " の ",
        math(String.raw`2`),
        " 進付値、(c) ",
        math(String.raw`\mathbb{Z}/2^{m}`),
        " 上の有限計算だけである。",
      ]),
      paragraph([
        "**限界（主張の一部として述べる）**",
      ]),
      list([
        [
          "**本命題は族 ",
          math(String.raw`p(1,0)+q(0,1)`),
          " に限る。一般の ",
          math(String.raw`\ell=2`),
          " 塔の閉形式は得られていない。** 本命題の証明で効いたのは ",
          math(String.raw`\bar{\tilde E}`),
          " が二項式の積に分解し、層ごとの消滅深度が ",
          math(String.raw`2+2^{r}`),
          " という具体形をもつことである。一般の塔では飽和が起きる「定数項」に相当する量の ",
          math(String.raw`2`),
          " 進付値が場合により変わるため、層の構造が族ほど単純にならない。",
        ],
        [
          "**族の外の一般の ",
          math(String.raw`\ell=2`),
          " 塔でも ",
          math(String.raw`n2^{n}`),
          " の係数が ",
          math(String.raw`b=\sum_{P\in S_\infty}j^{*}(P)`),
          "（",
          ref("paper_prop_K"),
          " (K6)）になることは、数値支持どまりであって証明ではない。** 宣言した母集団（辺数 ",
          math(String.raw`\le3`),
          " の 430 塔）の全走査で対象となった 174 塔すべてで一致し不一致は 0 だが、これは**その有限母集団に対する判定**であって母集団の外については何も主張しない（標本と見なすなら、除外できるのは破れ率 ",
          math(String.raw`1.7\%`),
          " までである）。",
        ],
        [
          "**(G″2) の「常に型 III」は族に固有である。** 同じ母集団には ",
          math(String.raw`b=0`),
          "（型 II）の ",
          math(String.raw`\ell=2`),
          " 塔が 39 個ある。同様に、母集団で ",
          math(String.raw`n`),
          " の係数が ",
          math(String.raw`0`),
          " の塔が 1 個も無いことも母集団の設計（辺数の制限）の帰結であって ",
          math(String.raw`\ell=2`),
          " 一般の性質ではない。**0 件の観察を性質として読まない。**",
        ],
        [
          ref("paper_prop_J"),
          " (J4) の仮定（十分深いレベルで最小点が一意）は、この族の ",
          math(String.raw`\ell=2`),
          " では case A の全組と case B・",
          math(String.raw`\lambda_1=1`),
          " の組で破れ、case B・",
          math(String.raw`\lambda_1\ge2`),
          " でのみ成り立つ（(G″5) の場合分けとちょうど一致する）。**この破れが ",
          math(String.raw`\ell=2`),
          " に固有だとは主張しない**（",
          ref("paper_prop_K"),
          " の限界のとおり、奇素数でも破れる塔がある）。それでも ",
          math(String.raw`n2^{n}`),
          " の係数は 4 つの場合とも ",
          math(String.raw`2`),
          " で、",
          math(String.raw`\sum_{P\in S_\infty}j^{*}(P)`),
          " も全組で ",
          math(String.raw`2`),
          " である（case A では ",
          math(String.raw`S_\infty`),
          " が 2 点で各 ",
          math(String.raw`j^{*}=1`),
          "、case B では 1 点で ",
          math(String.raw`j^{*}=2`),
          "）。",
        ],
        [
          "**最小点が同点になる箇所でも、値そのものは ",
          ref("paper_prop_R"),
          " (R4) の終結式公式が無条件に与える。** したがって ",
          math(String.raw`w`),
          " は「値を計算するために必要な量」ではなく「**値を ",
          math(String.raw`(p,q)`),
          " の不変量として閉形式に載せるために必要な量**」である。",
        ],
        [
          "本命題は ",
          math(String.raw`d=2`),
          " に限る。",
        ],
        [
          "**新規性は主張しない。** A",
          math(String.raw`\alpha`),
          " の値（トーラス ",
          math(String.raw`(p,q)=(1,1)`),
          " では ",
          math(String.raw`\mathrm{ord}_2(\kappa_n)=2n2^{n}+4\cdot2^{n}-6n-1`),
          "）そのものは DuBose–Vallières（Alg. Comb. 6 (2023), alco.304）§7 例 (1) に数値例として現れる。",
          "また「",
          math(String.raw`\mathbb{Z}_\ell`),
          " 拡大の岩澤不変量で ",
          math(String.raw`\ell=2`),
          " が特別に振る舞う」こと自体は岩澤理論では標準的な現象であり、本命題の内容が Monsky / Cuoco–Monsky の枠組みで既に扱われている可能性は高い。**確認できていない。**",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "**本文に無い補題へ暗黙に依存しないために、途中で使う事実はすべてその主張をここで述べてから使う。** ",
        "使う道具は ",
        math(String.raw`\mathbb{Q}(\zeta_{2^{m}})`),
        " の ",
        math(String.raw`2`),
        " の上の唯一の素点での付値、",
        math(String.raw`\mathbb{Z}`),
        " の ",
        math(String.raw`2`),
        " 進付値、",
        math(String.raw`\mathbb{Z}/2^{m}`),
        " 上の有限計算だけであり、実数体へは一度も出ない。",
      ]),
      paragraph([
        "**(0) 出発点。** ",
        ref("paper_prop_G_infty"),
        " の証明の (0) と同じ総和公式",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_2(\kappa_n)=v_2(\kappa_X)-2n+\mu\bigl(4^{n}-1\bigr)+\Sigma_n,
        \qquad
        \Sigma_n=\sum_{\substack{\zeta^{2^n}=\xi^{2^n}=1\\ (\zeta,\xi)\neq(1,1)}}v_2\bigl(E(\zeta,\xi)\bigr)`,
      ),
      paragraph([
        "を使う（",
        math(String.raw`\kappa(X)=1`),
        " なので ",
        math(String.raw`v_2(\kappa_X)=0`),
        "）。",
        math(String.raw`m\ge1`),
        "、",
        math(String.raw`h`),
        " を原始 ",
        math(String.raw`2^{m}`),
        " 乗根、",
        math(String.raw`\alpha_m:=1/\varphi_m=2^{1-m}`),
        "、",
        math(String.raw`\nu(\cdot):=v_2(\cdot)`),
        " とすると、",
        math(String.raw`2`),
        " が完全分岐することから",
      ]),
      displayMath(
        String.raw`v_2\bigl(h^{N}-1\bigr)=2^{\,\nu(N)}\alpha_m\ \ (\nu(N)<m),\qquad
        h^{N}-1=0\ \ (2^{m}\mid N),\qquad
        f_h(c)=h^{-c}\bigl(h^{c}-1\bigr)^2`,
      ),
      paragraph([
        "であり、したがって ",
        math(String.raw`v_2(f_h(c))=2\cdot2^{\,\nu(c)}\alpha_m`),
        "（",
        math(String.raw`\nu(c)<m`),
        "）である。さらに ",
        math(String.raw`-1=h^{2^{m-1}}`),
        " より ",
        math(String.raw`1+h^{N}=1-h^{\,N+2^{m-1}}`),
        " なので、",
      ]),
      displayMath(
        String.raw`\mathrm{ph}(e):=v_2\bigl(1+h^{N}\bigr)\Big|_{\nu(N)=e}=
        \begin{cases}
        2^{\,e}\alpha_m & (e\le m-2)\\
        +\infty & (e=m-1)\\
        1 & (e\ge m).
        \end{cases}`,
      ),
      paragraph([
        "**",
        math(String.raw`\mathrm{ph}(m-1)=+\infty`),
        " は ",
        math(String.raw`h^{N}=-1`),
        " という現象であり、奇素数には存在しない。** これが以下の「飽和」の源である。",
      ]),
      paragraph([
        "**(G″1) の証明。** ",
        math(String.raw`p',q'`),
        " が奇なら ",
        math(String.raw`p'\pm q'`),
        " は偶なので ",
        math(String.raw`\lambda_0,\lambda_-\ge1`),
        "。もし ",
        math(String.raw`\lambda_0=\lambda_-=k`),
        " なら、付値がちょうど ",
        math(String.raw`k`),
        " の 2 元の和は付値 ",
        math(String.raw`\ge k+1`),
        " をもつので ",
        math(String.raw`v_2\bigl((p'+q')+(p'-q')\bigr)=v_2(2p')=1\ge k+1`),
        " となり ",
        math(String.raw`k\le0`),
        " で矛盾する。よって ",
        math(String.raw`\lambda_0\neq\lambda_-`),
        " で、非アルキメデス的評価の等号成立から ",
        math(String.raw`\min(\lambda_0,\lambda_-)=v_2(2p')=1`),
        " である。",
      ]),
      paragraph([
        "同じ議論を ",
        math(String.raw`a',b'`),
        " に当てる。",
        math(String.raw`a'\mp b'`),
        " は偶なので ",
        math(String.raw`s,t\ge1`),
        "、",
        math(String.raw`(a'-b')+(a'+b')=2a'`),
        " で ",
        math(String.raw`a'`),
        " が奇だから ",
        math(String.raw`\min(s,t)\le1`),
        "、よって ",
        math(String.raw`\min(s,t)=1`),
        "。また ",
        math(String.raw`s,t\ge m`),
        " なら ",
        math(String.raw`2^{m}\mid2a'`),
        " となり ",
        math(String.raw`m\le1`),
        " で ",
        math(String.raw`m\ge2`),
        " に反する。",
      ]),
      paragraph([
        "**(G″2) の証明。** ",
        math(String.raw`g(T,S)=E(1+T,1+S)`),
        " の最低次斉次部分は ",
        math(String.raw`H=-(p'T^2+q'S^2)`),
        " である。",
        math(String.raw`\mathbb{F}_2`),
        " 上、",
        math(String.raw`p',q'`),
        " がともに奇なら ",
        math(String.raw`H\equiv T^2+S^2=(T+S)^2`),
        " で ",
        math(String.raw`(1{:}1)`),
        " が零点、一方が偶なら（例えば ",
        math(String.raw`p'`),
        " が偶なら）",
        math(String.raw`H\equiv S^2`),
        " で ",
        math(String.raw`(1{:}0)`),
        " が零点であり、いずれにせよ退化する。",
        ref("paper_prop_G_infty"),
        " (G′1) の判定（その証明は ",
        math(String.raw`\ell`),
        " の奇偶を使わないのでそのまま通る）より ",
        math(String.raw`\theta=\infty`),
        " が起きるのは ",
        math(String.raw`2\mid p'q'(p'+q')`),
        " のときちょうどだが、",
        math(String.raw`p',q'`),
        " が同時に偶になることはないので「両方奇なら ",
        math(String.raw`2\mid p'+q'`),
        "」「一方が偶なら ",
        math(String.raw`2\mid p'q'`),
        "」となり、**条件は常に満たされる**。",
      ]),
      paragraph([
        "**(G″3) の証明。** ",
        math(String.raw`A=(p'+q')/2`),
        "、",
        math(String.raw`B=(p'-q')/2`),
        " と置く（(G″1) よりちょうど一方が奇）。次の 3 つの恒等式を使う。",
      ]),
      displayMath(
        String.raw`p'f_h(a')+q'f_h(b')=A\bigl(f_h(a')+f_h(b')\bigr)+B\bigl(f_h(a')-f_h(b')\bigr),`,
      ),
      displayMath(
        String.raw`f_h(a')+f_h(b')=h^{-b'}\bigl(1+h^{\,b'-a'}\bigr)\bigl(1+h^{\,a'+b'}\bigr)-4,
        \qquad
        f_h(a')-f_h(b')=-h^{-a'}\bigl(h^{\,a'-b'}-1\bigr)\bigl(h^{\,a'+b'}-1\bigr)`,
      ),
      paragraph([
        "（第 1 式は ",
        math(String.raw`A+B=p'`),
        "、",
        math(String.raw`A-B=q'`),
        " から、第 2・第 3 式は右辺を展開すればよい）。3 つの項の付値を",
      ]),
      displayMath(
        String.raw`T_1:=(\lambda_0-1)+\mathrm{ph}(s)+\mathrm{ph}(t),\qquad
        T_2:=(\lambda_0-1)+2,\qquad
        T_3:=(\lambda_--1)+\bigl(2^{s}+2^{t}\bigr)\alpha_m`,
      ),
      paragraph([
        "と置く（",
        math(String.raw`T_1`),
        " は第 2 式の積の項、",
        math(String.raw`T_2`),
        " はその ",
        math(String.raw`-4`),
        " の項、",
        math(String.raw`T_3`),
        " は第 3 式の項。",
        math(String.raw`v_2(A)=\lambda_0-1`),
        "、",
        math(String.raw`v_2(B)=\lambda_--1`),
        "）。(G″1) より小さい方は ",
        math(String.raw`1`),
        " なので、",
        math(String.raw`r<m`),
        " のとき ",
        math(String.raw`T_3=(\lambda_--1)+(2+2^{r})\alpha_m`),
        " である。",
      ]),
      paragraph([
        "**一方だけ奇のとき**（",
        math(String.raw`a'`),
        " 奇、",
        math(String.raw`\nu(b')=\beta\ge1`),
        "）: ",
        math(String.raw`v_2(p'f_h(a'))=2\alpha_m`),
        " が ",
        math(String.raw`v_2(q'f_h(b'))=2\cdot2^{\beta}\alpha_m`),
        " より真に小さいので ",
        math(String.raw`\varphi_mv_2(E)=2`),
        "。**",
        math(String.raw`m=1`),
        " のとき**: ",
        math(String.raw`h=-1`),
        " で ",
        math(String.raw`f_h(1)=-4`),
        " だから ",
        math(String.raw`a'=b'=1`),
        " なら ",
        math(String.raw`E=(p'+q')\cdot4`),
        " で ",
        math(String.raw`v_2=2+\lambda_0`),
        "、一方が ",
        math(String.raw`0`),
        " なら ",
        math(String.raw`v_2=2`),
        "。**",
        math(String.raw`r\ge m`),
        " のとき**: 第 3 式の因子の一方が ",
        math(String.raw`0`),
        " なので ",
        math(String.raw`f_h(a')=f_h(b')`),
        "、すなわち ",
        math(String.raw`E=-(p'+q')f_h(b')`),
        " で ",
        math(String.raw`v_2(E)=\lambda_0+2\alpha_m`),
        "（厳密な等式）。",
      ]),
      paragraph([
        "**以下 ",
        math(String.raw`2\le r\le m-1`),
        "。case A",
        math(String.raw`\alpha`),
        "（",
        math(String.raw`\lambda_0=1,\ \lambda_-\ge2`),
        "、",
        math(String.raw`T_2=2`),
        "）。** ",
        math(String.raw`r\le m-2`),
        " なら ",
        math(String.raw`T_1=(2+2^{r})\alpha_m`),
        "、",
        math(String.raw`T_3=(\lambda_--1)+T_1>T_1`),
        " であり、",
        math(String.raw`T_1\le(2+2^{m-2})2^{1-m}=2^{2-m}+2^{-1}<2=T_2`),
        " なので最小は ",
        math(String.raw`T_1`),
        " で一意、",
        math(String.raw`v_2(E)=(2+2^{r})\alpha_m`),
        "。",
        math(String.raw`r=m-1`),
        " なら ",
        math(String.raw`\mathrm{ph}(m-1)=+\infty`),
        " より ",
        math(String.raw`T_1=+\infty`),
        " で、",
        math(String.raw`T_3\ge1+2^{2-m}+1>2=T_2`),
        " だから最小は ",
        math(String.raw`T_2=2`),
        " で一意、",
        math(String.raw`\varphi_mv_2(E)=2^{m}`),
        " である。**これが飽和である。**",
      ]),
      paragraph([
        "**case A",
        math(String.raw`\beta`),
        "（",
        math(String.raw`\lambda_0\ge2,\ \lambda_-=1`),
        "、",
        math(String.raw`T_2=\lambda_0+1\ge3`),
        "）。** ",
        math(String.raw`r\le m-2`),
        " なら ",
        math(String.raw`T_3=(2+2^{r})\alpha_m`),
        "、",
        math(String.raw`T_1=(\lambda_0-1)+T_3>T_3`),
        "、",
        math(String.raw`T_3<2<T_2`),
        " で最小は ",
        math(String.raw`T_3`),
        " で一意。",
        math(String.raw`r=m-1`),
        " なら ",
        math(String.raw`T_1=+\infty`),
        "、",
        math(String.raw`T_3=2^{2-m}+1\le2<3\le T_2`),
        "（",
        math(String.raw`m\ge2`),
        "）でやはり ",
        math(String.raw`T_3`),
        " が一意の最小。いずれも ",
        math(String.raw`\varphi_mv_2(E)=2+2^{r}`),
        " であり、これで [A] の 3 行が得られた。",
      ]),
      paragraph([
        "**[B] の証明。** ",
        math(String.raw`U_e=U_o<\infty`),
        " とすると ",
        math(String.raw`U_o=2^{\,\nu(a_o)+1}=2^{k}`),
        " は ",
        math(String.raw`2`),
        " 冪で、",
        math(String.raw`U_e=\lambda_1 2^{n-1}+2^{\,\nu(a_e)+1}=2^{k}\le2^{n}`),
        " の第 1 項が正だから ",
        math(String.raw`\lambda_1 2^{n-1}<2^{n}`),
        "、すなわち ",
        math(String.raw`\lambda_1=1`),
        "。すると ",
        math(String.raw`2^{n-1}+2^{\,\nu(a_e)+1}=2^{k}`),
        " となるが、**2 つの ",
        math(String.raw`2`),
        " 冪の和が ",
        math(String.raw`2`),
        " 冪になるのは両者が等しいときだけ**なので ",
        math(String.raw`\nu(a_e)=n-2`),
        "、",
        math(String.raw`k=n`),
        "（したがって ",
        math(String.raw`n\ge2`),
        "）。逆にこの条件下で ",
        math(String.raw`U_e=U_o=2^{n}`),
        " である。",
      ]),
      paragraph([
        "その同点の場所では ",
        math(String.raw`\nu(a_o)=n-1`),
        " より ",
        math(String.raw`h^{a_o}=-1`),
        " で ",
        math(String.raw`f_h(a_o)=-4`),
        "、",
        math(String.raw`\nu(a_e)=n-2`),
        " より ",
        math(String.raw`h^{a_e}`),
        " は位数 ",
        math(String.raw`4`),
        " で ",
        math(String.raw`f_h(a_e)=-2`),
        " だから ",
        math(String.raw`-E=-2c_e-4c_o=-4(c_e/2+c_o)`),
        "、すなわち ",
        math(String.raw`v_2(E)=2+w`),
        " である。",
        math(String.raw`\lambda_1=1`),
        " より ",
        math(String.raw`c_e/2`),
        " は奇、",
        math(String.raw`c_o`),
        " も奇なので ",
        math(String.raw`w\ge1`),
        "、素朴な ",
        math(String.raw`\min(U_e,U_o)/\varphi_n=2`),
        " より狭義に深い。**降りる先が指数の桁ではなく係数の第 2 の ",
        math(String.raw`2`),
        " 進桁であり、1 段で閉じる。**",
      ]),
      paragraph([
        "**(G″4) の証明。** レベルちょうど ",
        math(String.raw`m`),
        " の点は ",
        math(String.raw`(a',b')\in(\mathbb{Z}/2^{m})^2`),
        "、",
        math(String.raw`\min(\nu(a'),\nu(b'))=0`),
        " と 1 対 1 に対応する。**case A** で小計を ",
        math(String.raw`S_m`),
        " と書くと、",
      ]),
      displayMath(
        String.raw`S_1=2+2+(2+\lambda_0)=6+\lambda_0,\qquad
        S_m^{\mathrm{off}}=2^{2m-1}\cdot2^{2-m}=2^{m+1}\ \ (m\ge2)`,
      ),
      paragraph([
        "である（",
        math(String.raw`m=1`),
        " の点は ",
        math(String.raw`(1,0),(0,1),(1,1)`),
        " の 3 つ。一方だけ奇の点は ",
        math(String.raw`2^{2m-1}`),
        " 個で各 ",
        math(String.raw`v_2=2^{2-m}`),
        "）。両方奇の点は ",
        math(String.raw`a'`),
        " を奇に固定すると（",
        math(String.raw`2^{m-1}`),
        " 通り）、",
        math(String.raw`r=j\ (2\le j\le m-1)`),
        " となる ",
        math(String.raw`b'`),
        " が ",
        math(String.raw`2^{m-j}`),
        " 個、",
        math(String.raw`r\ge m`),
        " が ",
        math(String.raw`2`),
        " 個であり（検算: ",
        math(String.raw`\sum_{j=2}^{m-1}2^{m-j}+2=2^{m-1}`),
        "）、",
        math(String.raw`\varphi_m`),
        " で割った値を掛けると各層の寄与は ",
        math(String.raw`2^{2-j}+2`),
        " と ",
        math(String.raw`2\lambda_0+2^{3-m}`),
        " になる。",
      ]),
      paragraph([
        "したがって両方奇の点の小計 ",
        math(String.raw`S_m^{\mathrm{diag}}`),
        " は次のとおりである。",
      ]),
      displayMath(
        String.raw`S_m^{\mathrm{diag}}=\begin{cases}
        (m+1)2^{m}-4 & (\lambda_0=1)\\
        2^{m}\,(m-1+\lambda_0) & (\lambda_0\ge2).
        \end{cases}`,
      ),
      paragraph([
        "実際 ",
        math(String.raw`\lambda_0\ge2`),
        "（飽和なし）では括弧の中が ",
        math(String.raw`\sum_{j=2}^{m-1}(2^{2-j}+2)+2\lambda_0+2^{3-m}=2m-2+2\lambda_0`),
        " となり ",
        math(String.raw`2^{m-1}`),
        " 倍して下段を得る（",
        math(String.raw`m=2`),
        " でも和が空で一致）。",
        math(String.raw`\lambda_0=1`),
        " では層 ",
        math(String.raw`r=m-1`),
        " が飽和して寄与が ",
        math(String.raw`4`),
        " になり、",
        math(String.raw`m\ge3`),
        " で括弧の中は ",
        math(String.raw`2m+2-2^{3-m}`),
        "、",
        math(String.raw`2^{m-1}`),
        " 倍して上段を得る（",
        math(String.raw`m=2`),
        " は全点が ",
        math(String.raw`r\ge m`),
        " なので直接 ",
        math(String.raw`4(\lambda_0+1)=8`),
        " で一致）。",
      ]),
      paragraph([
        "**総和。** ",
        math(String.raw`\lambda_0=1`),
        " では ",
        math(String.raw`S_m=2^{m+1}+(m+1)2^{m}-4`),
        "（",
        math(String.raw`m\ge2`),
        "）、",
        math(String.raw`S_1=7`),
        " で、この式を ",
        math(String.raw`m=1`),
        " に当てた値 ",
        math(String.raw`4`),
        " との差は ",
        math(String.raw`3`),
        " だから",
      ]),
      displayMath(
        String.raw`\Sigma_n=3+\sum_{m=1}^{n}\bigl[2^{m+1}+(m+1)2^{m}-4\bigr]=2n\,2^{n}+4\cdot2^{n}-4n-1`,
      ),
      paragraph([
        "（",
        math(String.raw`\sum_{m=1}^{n}(m+1)2^{m}=n2^{n+1}`),
        " を使った）。",
        math(String.raw`-2n`),
        " を足して第 1 行を得る。",
        math(String.raw`\lambda_0\ge2`),
        " では ",
        math(String.raw`S_m=2^{m+1}+2^{m}(m-1+\lambda_0)`),
        "、",
        math(String.raw`S_1=6+\lambda_0`),
        " で差は ",
        math(String.raw`2-\lambda_0`),
        " だから ",
        math(String.raw`\Sigma_n=2^{n+1}(n+\lambda_0)+2-3\lambda_0`),
        " となり、",
        math(String.raw`-2n`),
        " を足して第 2 行を得る。",
      ]),
      paragraph([
        "**case B、",
        math(String.raw`\lambda_1\ge2`),
        "。** ",
        math(String.raw`a_o\not\equiv0`),
        " なら ",
        math(String.raw`U_e\ge2\cdot2^{n-1}+2>2^{n}\ge U_o`),
        "、",
        math(String.raw`a_o\equiv0`),
        " なら ",
        math(String.raw`U_o=+\infty`),
        " なので同点は起きない。",
        math(String.raw`\nu(x)=\gamma<n`),
        " なる ",
        math(String.raw`x`),
        " は ",
        math(String.raw`2^{n-\gamma-1}`),
        " 個なので",
      ]),
      displayMath(
        String.raw`\varphi_n\Sigma_n=\sum_{\gamma=0}^{n-1}2^{n-\gamma-1}\cdot2^{n}\cdot2^{\gamma+1}
        +\sum_{\gamma=0}^{n-1}2^{n-\gamma-1}\bigl(\lambda_1 2^{n-1}+2^{\gamma+1}\bigr)
        =n2^{2n}+\lambda_1 2^{n-1}\bigl(2^{n}-1\bigr)+n2^{n},`,
      ),
      paragraph([
        "すなわち ",
        math(String.raw`\Sigma_n=2n\,2^{n}+\lambda_1(2^{n}-1)+2n`),
        " で、",
        math(String.raw`-2n`),
        " を足して第 3 行を得る。**case B、",
        math(String.raw`\lambda_1=1`),
        "、",
        math(String.raw`n\ge2`),
        "** では、上の計算を基準にして補正する。基準から外れうるのは ",
        math(String.raw`a_o=2^{n-1}`),
        "（1 個）のときだけで、",
        math(String.raw`\nu(a_e)\le n-3`),
        " では差が ",
        math(String.raw`2^{\,\nu(a_e)+1}-2^{n-1}`),
        "、",
        math(String.raw`\nu(a_e)=n-2`),
        "（2 個）では差が ",
        math(String.raw`2^{n-1}w`),
        "、それ以外では ",
        math(String.raw`0`),
        " である。差の総和は",
      ]),
      displayMath(
        String.raw`\sum_{\gamma=0}^{n-3}2^{n-\gamma-1}\bigl(2^{\gamma+1}-2^{n-1}\bigr)+2\cdot2^{n-1}w
        =(n-2)2^{n}-2^{2n-1}+2^{n+1}+2^{n}w`,
      ),
      paragraph([
        "で、",
        math(String.raw`\varphi_n=2^{n-1}`),
        " で割ると ",
        math(String.raw`2n-2^{n}+2w`),
        "。よって ",
        math(String.raw`\Sigma_n=2n2^{n}+4n-1+2w`),
        " となり、",
        math(String.raw`-2n`),
        " を足して第 4 行を得る。",
        math(String.raw`n=1`),
        " では ",
        math(String.raw`\nu(a_e)=n-2=-1`),
        " が不可能なので同点が起きず、",
        math(String.raw`\lambda_1\ge2`),
        " と同じ計算が通って第 3 行が与える。",
      ]),
      paragraph([
        "**(G″5) の証明。** case B かつ ",
        math(String.raw`\lambda_1\ge2`),
        " では上の第 3 行が ",
        ref("paper_prop_G_infty"),
        " (G′3) の式（",
        math(String.raw`\Lambda=\lambda_1`),
        "）と一致する。逆に (G′3) の式は ",
        math(String.raw`n`),
        " の線形項をもたないのに対し、A",
        math(String.raw`\alpha`),
        " は ",
        math(String.raw`-6n`),
        "、A",
        math(String.raw`\beta`),
        " は ",
        math(String.raw`-2n`),
        "、B かつ ",
        math(String.raw`\lambda_1=1`),
        " は ",
        math(String.raw`+2n`),
        " をもつので一致しない（",
        math(String.raw`n=1,2`),
        " の 2 点で既に食い違う）。",
      ]),
      paragraph([
        "**限界について。** 上の計数で効いたのは ",
        math(String.raw`\bar{\tilde E}`),
        " が二項式の積へ分解し、層ごとの付値が ",
        math(String.raw`2+2^{r}`),
        " という具体形をもつことである。一般の ",
        math(String.raw`\ell=2`),
        " 塔では飽和が起きる「定数項」に相当する量の ",
        math(String.raw`2`),
        " 進付値が場合により変わるため、この計数はそのままでは通らない。",
        "限界に挙げた母集団についての言明（",
        math(String.raw`174`),
        " 塔で一致・",
        math(String.raw`39`),
        " 個の型 II の存在）は有限母集団の全走査による判定であって、母集団の外については何も述べていない。",
      ]),
    ],
  },
]);
