/**
 * 論文本体 第 6 章: 命題 T・V・W。
 *
 * 命題 T（全域木数の 2 進付値）と命題 V（Λ 側の非自明性の判定）は本プロジェクトで証明した。
 * 命題 W（非退化グラフ塔の閉形式）も証明したが、μ の上界方向は外部定理に依拠する。
 * いずれも新規性は主張しない。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_060_heading_tvw",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/006_propositions_TVW.ts", ordinal: 1 },
    title: { text: "命題 T・V・W — 具体的な決定手続きをもつ主張" },
    labels: [],
  },
  {
    id: "paper_061_theorem_V",
    kind: "theorem",
    origin: { path: "structured-latex/content/006_propositions_TVW.ts", ordinal: 2 },
    title: { text: "命題 V（Λ 側が非自明になる条件の完全な判定）" },
    labels: ["paper_prop_V", "paper_lemma_V0"],
    habitat: "Z",
    verification: ["sagemath/check/cycle14_T1_vp_two_var"],
    lean: [
      "IntegrableLattice.X_pow_char_pow_sub_one",
      "IntegrableLattice.resultant_X_pow_char_pow_sub_one",
      "IntegrableLattice.aOne_cast_zmod",
      "IntegrableLattice.dvd_aOne_iff",
      "IntegrableLattice.aTwo_cast_zmod",
      "IntegrableLattice.dvd_aTwo_iff",
    ],
    statement: [
      paragraph([
        math(String.raw`P\in\mathbb{Z}[z_1^{\pm},\dots,z_d^{\pm}]`),
        "、",
        math(String.raw`p`),
        " を素数、",
        math(String.raw`n\ge0`),
        " とする。**補題 V0** として",
      ]),
      displayMath(String.raw`a_{p^n}\equiv P(1,\dots,1)^{\,p^{dn}}\pmod p`),
      paragraph([
        "が成り立ち、したがって**命題 V**",
      ]),
      displayMath(String.raw`v_p(a_{p^n})>0\iff p\mid P(1,\dots,1)`),
      paragraph([
        "を得る（",
        math(String.raw`a_{p^n}=0`),
        " のときは ",
        math(String.raw`v_p=\infty>0`),
        " と読む）。**この同値は ",
        math(String.raw`n`),
        " に依らない。**",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`L=p^n`),
        " と置き、",
        math(String.raw`\bmod\,p`),
        " 還元を ",
        math(String.raw`\overline{\phantom{x}}`),
        " で表す。",
      ]),
      paragraph([
        "**(a)** ",
        math(String.raw`A`),
        " を可換環、",
        math(String.raw`f\in A[x]`),
        " をモニックとすると、環準同型 ",
        math(String.raw`\varphi`),
        " について ",
        math(String.raw`\varphi(\mathrm{Res}(f,g))=\mathrm{Res}(\varphi f,\varphi g)`),
        " が成り立つ。終結式は形式次数を指定した Sylvester 行列の行列式であり、",
        math(String.raw`\deg\varphi g<\deg g`),
        " となって形式次数がずれても、モニック性から ",
        math(String.raw`\mathrm{Res}_{\deg f,d}(f,g)=\mathrm{lc}(f)^{d-d'}\mathrm{Res}_{\deg f,d'}(f,g)`),
        " かつ ",
        math(String.raw`\mathrm{lc}(f)=1`),
        " なのでずれが吸収される。",
      ]),
      paragraph([
        "**(b)** Frobenius により ",
        math(String.raw`\mathbb{F}_p[z]`),
        " では ",
        math(String.raw`z^{p^n}-1=(z-1)^{p^n}`),
        " である。したがって ",
        math(String.raw`Q(z):=\mathrm{Res}_w(w^L-1,P(z,w))`),
        " について、(a) と終結式の乗法性を ",
        math(String.raw`(w-1)^L`),
        " に ",
        math(String.raw`L`),
        " 回適用して",
      ]),
      displayMath(String.raw`\bar Q(z)=\mathrm{Res}_w(w-1,\bar P(z,w))^{L}=\bar P(z,1)^{L}.`),
      paragraph([
        "**(c)** 同様に外側でも潰れて ",
        math(String.raw`\bar a_L=\bar Q(1)^L=\bigl(\bar P(1,1)^L\bigr)^L=\bar P(1,1)^{L^2}`),
        "。変数の個数は使っていないので ",
        math(String.raw`d`),
        " 変数でも同じ議論が通り、補題 V0 を得る。",
      ]),
      paragraph([
        "命題 V は補題 V0 から直ちに従う。",
        math(String.raw`p\nmid P(1,\dots,1)`),
        " なら ",
        math(String.raw`\mathbb{F}_p^\times`),
        " は群だから ",
        math(String.raw`\bar a_L\neq0`),
        " で ",
        math(String.raw`v_p=0`),
        "。",
        math(String.raw`p\mid P(1,\dots,1)`),
        " なら ",
        math(String.raw`\bar a_L=0`),
        " で ",
        math(String.raw`v_p\ge1`),
        "。",
      ]),
      paragraph([
        "**この証明は ",
        math(String.raw`\mathbb{Q}_p`),
        " も代数的整数論も使わない。** 使うのは ",
        math(String.raw`\mathbb{F}_p`),
        " 上の Frobenius と終結式の初等的性質だけである。",
      ]),
      paragraph([
        "**既出性（本論文は新規性を主張しない）**: ",
        math(String.raw`d=1`),
        " の場合は**既知の古典から直ちに従う**。周期点数の列は Dold 数列（Gauss 合同を満たす整数列）であり、",
        "Byszewski–Graff–Ward, *Dold sequences, periodic points, and dynamics*, Bull. London Math. Soc. **53** (2021), ",
        "Definition 2.1 の定義で ",
        math(String.raw`n=p`),
        " と取れば ",
        math(String.raw`a_p\equiv a_1\pmod p`),
        " が出る（本論文はこの定義を原文で確認した）。本命題の差分は「",
        math(String.raw`a_L=0`),
        " を許し ",
        math(String.raw`d`),
        " が任意の場合を無条件で扱う」1 点に限られる。",
        math(String.raw`d\ge2`),
        " の終結式合同の形は、調べた範囲では見つからなかった（無いとは言わない）。",
      ]),
    ],
  },
  {
    id: "paper_062_theorem_T",
    kind: "theorem",
    origin: { path: "structured-latex/content/006_propositions_TVW.ts", ordinal: 3 },
    title: { text: "命題 T（トーラス全域木数の 2 進付値）" },
    labels: ["paper_prop_T"],
    habitat: "Z",
    verification: [
      "sagemath/check/cycle13_T1_tau_v2",
      "sagemath/check/cycle10_T1_vp_law",
      "sagemath/check/cycle14_T1_tau_general",
      "sagemath/check/cycle15_T3_tau_d3",
      "sagemath/check/cycle17_T1_prior_art",
    ],
    statement: [
      paragraph([
        math(String.raw`\tau(L)`),
        " を ",
        math(String.raw`L\times L`),
        " トーラス ",
        math(String.raw`C_L\times C_L`),
        " の全域木数とすると、**任意の奇数 ",
        math(String.raw`L\ge3`),
        "** に対し",
      ]),
      displayMath(String.raw`v_2\bigl(\tau(L)\bigr)=2(L-1).`),
      paragraph([
        "**偶数 ",
        math(String.raw`L`),
        " では成立しない**（",
        math(String.raw`L=2,\dots,14`),
        " で ",
        math(String.raw`v_2=5,19,29,61,53,83,77`),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        "指標による対角化と Kirchhoff の matrix-tree 定理から",
      ]),
      displayMath(
        String.raw`\tau(L)=\prod_{j=1}^{L-1}\bigl(r_j^{L}+r_j^{-L}-2\bigr)=\prod_{j=1}^{L-1}\frac{(r_j^{L}-1)^2}{r_j^{L}},
\qquad r_j+r_j^{-1}=4-\zeta^{j}-\zeta^{-j}`,
      ),
      paragraph([
        "を得る（",
        math(String.raw`\zeta=\zeta_L`),
        "）。",
        math(String.raw`r_j`),
        " は単数なので ",
        math(String.raw`v(D_j)=2\,v(r_j^L-1)`),
        "。",
      ]),
      paragraph([
        math(String.raw`L`),
        " 奇より 2 は ",
        math(String.raw`\mathbb{Q}(\zeta_L)`),
        " で不分岐。",
        math(String.raw`\bmod\,P`),
        " で ",
        math(String.raw`w^2-A_jw+1\equiv(w-\zeta^j)(w-\zeta^{-j})`),
        " となり、",
        math(String.raw`j\not\equiv0`),
        " かつ ",
        math(String.raw`L`),
        " 奇から ",
        math(String.raw`2j\not\equiv0`),
        " なので 2 根は相異なる。Hensel により ",
        math(String.raw`r_j\equiv\zeta^j`),
        " なる根が取れる。",
      ]),
      paragraph([
        math(String.raw`r_j=\zeta^j(1+m_j)`),
        " と置くと ",
        math(String.raw`m_j`),
        " は",
      ]),
      displayMath(
        String.raw`\zeta^{j}m^2+\bigl(3\zeta^{j}+\zeta^{-j}-4\bigr)m-2(1-\zeta^{j})(1-\zeta^{-j})=0`,
      ),
      paragraph([
        "を満たす。3 係数の付値は ",
        math(String.raw`(0,0,1)`),
        " なので Newton 多角形から 2 根の付値は ",
        math(String.raw`1`),
        " と ",
        math(String.raw`0`),
        "、したがって ",
        math(String.raw`v(m_j)=1`),
        "。",
      ]),
      paragraph([
        math(String.raw`\zeta^L=1`),
        " より ",
        math(String.raw`r_j^L-1=(1+m_j)^L-1=L\,m_j+\sum_{i\ge2}\binom{L}{i}m_j^i`),
        " で、",
        math(String.raw`L`),
        " 奇より ",
        math(String.raw`v(L)=0`),
        " だから ",
        math(String.raw`v(r_j^L-1)=v(m_j)=1`),
        "。総和して ",
        math(String.raw`v_2(\tau(L))=\sum_{j=1}^{L-1}2=2(L-1)`),
        "。",
      ]),
      paragraph([
        "**奇数性を使ったのは 3 箇所**である: 2 の不分岐性、",
        math(String.raw`j\not\equiv0\Rightarrow2j\not\equiv0`),
        "、",
        math(String.raw`v(L)=0`),
        "。偶 ",
        math(String.raw`L`),
        " ではいずれも破れる。",
      ]),
      paragraph([
        "**新規性は主張しない。** 使った道具（matrix-tree、不分岐性、Hensel、Newton 多角形、二項展開）は",
        "すべて標準的である。",
      ]),
      paragraph([
        "**既出性**: **弱い形は既出である。** Mednykh–Mednykh, *Complexity of the circulant foliation over a graph*, ",
        "arXiv:1902.05681 の Theorem 5.1（§7.6 が本件の離散トーラス ",
        math(String.raw`C_L\times C_L`),
        " を明示的に扱う）から、奇 ",
        math(String.raw`L`),
        " について ",
        math(String.raw`\tau(L)=L^2a(L)^2`),
        " の形が従い、したがって ",
        math(String.raw`v_2(\tau(L))`),
        " が**偶数であること**は既知である。本論文はこれを原文で確認した。",
        "**等号 ",
        math(String.raw`v_2(\tau(L))=2(L-1)`),
        " そのものは、調べた範囲では見つからなかった。** 本命題はその強化として位置づく。",
        "（両者の整合は ",
        math(String.raw`L=3,\dots,13`),
        " で厳密整数計算により確認した。浮動小数点では ",
        math(String.raw`L\ge7`),
        " で桁落ちし誤った結論が出るので使ってはならない。）",
      ]),
    ],
  },
  {
    id: "paper_063_theorem_W",
    kind: "theorem",
    origin: { path: "structured-latex/content/006_propositions_TVW.ts", ordinal: 4 },
    title: { text: "命題 W（非退化グラフ塔の閉形式）" },
    labels: ["paper_prop_W"],
    habitat: "Q",
    verification: [
      "sagemath/check/cycle14_T3_two_var",
      "sagemath/check/cycle14_T3_Zl2_tower",
      "sagemath/check/cycle12_T3_nonzero_mu_p",
      "sagemath/check/cycle13_T3_criterion_proof",
    ],
    statement: [
      paragraph([
        math(String.raw`X`),
        " を有限連結多重グラフ、",
        math(String.raw`\alpha:E\to\mathbb{Z}^2`),
        " を voltage 割り当て、",
        math(String.raw`\ell`),
        " を素数とする。",
        math(String.raw`f=\det L(1+T,1+S)`),
        " の ",
        math(String.raw`\bmod\,\ell`),
        " 還元の最低次斉次部分を ",
        math(String.raw`H`),
        "（次数 ",
        math(String.raw`k`),
        "）とし、",
        math(String.raw`H`),
        " が ",
        math(String.raw`\mathbb{P}^1(\mathbb{F}_\ell)`),
        " 上に零点をもたない（**非退化**）と仮定する。このとき ",
        math(String.raw`n\gg0`),
        " で",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_\ell(\kappa_n)=\mu\,\ell^{2n}+\frac{k(\ell+1)}{\ell-1}\,\ell^{n}-2n+\nu,
\qquad \mu=v_\ell\bigl(\mathrm{content}_{z,w}\det L\bigr).`,
      ),
      paragraph([
        "非退化性は ",
        math(String.raw`\det L`),
        " の係数からの**有限計算で判定できる**。",
      ]),
    ],
    proof: [
      paragraph([
        "証明は 2 段からなる。第 1 に ",
        math(String.raw`(★_2)`),
        "（ブロック巡回の 2 重離散 Fourier 対角化と matrix-tree 定理）により",
      ]),
      displayMath(
        String.raw`N N'\,\kappa(X_{N,N'})=\kappa(X)\prod_{(\zeta,\xi)\neq(1,1)}\det L(\zeta,\xi)`,
      ),
      paragraph([
        "を得る（連結性の仮定は不要。退化ケースは両辺 ",
        math(String.raw`0`),
        "）。第 2 に、非退化条件の下で各点の付値を評価して総和する。",
      ]),
      paragraph([
        "**",
        math(String.raw`\mu`),
        " の上界方向は自前で証明していない。** これは Cuoco–Monsky Theorem 1.7 の帰結であり、",
        math(String.raw`\mu=m_0(f)`),
        " が等号で与えられる。下界方向は自前で証明した。",
      ]),
      paragraph([
        "**非退化条件と ",
        math(String.raw`\lambda`),
        " の関係**: 「",
        math(String.raw`H`),
        " が ",
        math(String.raw`\mathbb{P}^1(\mathbb{F}_\ell)`),
        " 上に零点をもたない」ならば ",
        math(String.raw`l_0(f)=0`),
        "（すなわち ",
        math(String.raw`\lambda=0`),
        "）である。**逆は偽**であり（",
        ref("paper_remark_D_limits"),
        " (i) の反例）、同値ではない。命題 W が必要とするのは前者の向きだけである。",
      ]),
      paragraph([
        "**適用例**: ",
        math(String.raw`L\times L`),
        " トーラス（2 ループ bouquet）では ",
        math(String.raw`H=-(T^2+S^2)`),
        "、",
        math(String.raw`k=2`),
        "。",
        math(String.raw`\ell=3`),
        " では ",
        math(String.raw`-1`),
        " が非平方なので非退化で、",
        math(String.raw`\mathrm{ord}_3(\tau(3^n))=4\cdot3^n-2n-4`),
        "（",
        math(String.raw`n=0,1,2`),
        " で ",
        math(String.raw`0,6,28`),
        " と厳密一致）。",
        math(String.raw`\ell=2`),
        " では ",
        math(String.raw`H\equiv(T+S)^2`),
        " が有理零点をもつので**射程外**である。",
      ]),
      paragraph([
        "**新規性は主張しない。** 漸近形は Kataoka arXiv:2606.03579 Theorem 1.1 で既知であり、",
        math(String.raw`\mu`),
        " の明示公式も Cuoco–Monsky で既知である。",
        math(String.raw`\mu_1=k(\ell+1)/(\ell-1)`),
        " の明示式は文献で見つけられなかったが、網羅調査ではないので新規性は主張しない。",
      ]),
      paragraph([
        "**既出性の調査結果**: ",
        "(i) 「非退化なら閉形式」という**形そのものは ",
        math(String.raw`d=1`),
        " で既出**である（Vallières, arXiv:2006.14012, Corollary 5.7）。",
        "(ii) ",
        math(String.raw`d=2`),
        " の低位項については、Kataoka arXiv:2606.03579 §4.3 が「",
        math(String.raw`\lambda_1,\mu_1,\nu`),
        " の同定は本論文では追わない」と**明記**しており、DuBose–Vallières（Alg. Comb. 6 (2023), alco.304）§7 も",
        "数値フィットであって証明ではないと**自認**している。",
        "(iii) Monsky, *Fine estimates for the growth of ",
        math(String.raw`e_n`),
        " in ",
        math(String.raw`\mathbb{Z}_p^d`),
        "-extensions*, ASPM **17** (1989), 309–330 の**本文を確認した**（Project Euclid の Open Access 版）。",
        "同論文の Theorem 3.13 は、数体の ",
        math(String.raw`\mathbb{Z}_p^d`),
        " 拡大の類数について ",
        math(String.raw`e_n=(m_0p^n+\ell_0n+\alpha^*)p^{(d-1)n}+O(np^{(d-2)n})`),
        " を示すが、",
        math(String.raw`\alpha^*`),
        "（本命題の ",
        math(String.raw`\mu_1`),
        " に対応する位置の定数）については**存在と、",
        math(String.raw`d=2`),
        " のときの有理性しか主張していない**。Monsky 自身が Introduction で「",
        math(String.raw`\alpha^*`),
        " には easy な記述が無く、常に有理数かどうかも分からない」と書いており、同論文が明示的に同定した係数は ",
        math(String.raw`p^{dn}`),
        " の係数 ",
        math(String.raw`m_0`),
        " と ",
        math(String.raw`np^{(d-1)n}`),
        " の係数 ",
        math(String.raw`\ell_0`),
        " の 2 つだけである（Theorem 1.20）。",
        "したがって本命題の ",
        math(String.raw`\mu_1`),
        " の値は同論文には無く、むしろ同論文の「",
        math(String.raw`d=2`),
        " なら有理数」という一般定理に対して、本命題はある族でその有理数の値を与えていることになる。",
        "なお Monsky の主張は数体の類数についてであってグラフの全域木数についてではない。",
      ]),
    ],
  },
]);
