/**
 * 論文本体 第 7 章（決定可能性の非対称）と第 8 章（スコープと限界・形式検証）。
 *
 * 第 8 章は本論文の主張の限界を集約する。再框であること、未解決点、
 * 形式検証の到達点をここで正直に述べる。
 */

import { defineBlocks, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_070_heading_asymmetry",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/007_asymmetry_scope.ts", ordinal: 1 },
    title: { text: "決定可能性の非対称 — 難しい連続問題は ℝ 側にのみ現れる" },
    labels: [],
  },
  {
    id: "paper_071_remark_asymmetry",
    kind: "remark",
    origin: { path: "structured-latex/content/007_asymmetry_scope.ts", ordinal: 2 },
    title: { text: "二素点の難易度は対称でない" },
    labels: ["paper_remark_asymmetry"],
    habitat: "mixed",
    realEscape:
      "本注記は ℝ 側の量（Mahler 測度）と Λ 側の量（岩澤 μ）を比較する。ℝ が現れるのは比較の左辺だけで、" +
      "本論文の Λ 側の主張はこの比較に依存しない。",
    verification: ["sagemath/check/cycle10_T3_lehmer"],
    statement: [
      paragraph([
        ref("paper_prop_D"),
        " の二素点は同じ ",
        math(String.raw`P`),
        " から出るが、難易度は対称でない。",
      ]),
      list([
        [
          "",
          math(String.raw`\mathbb{R}`),
          " 側: Mahler 測度 ＝ エントロピー ＝ 自由エネルギー密度は ",
          math(String.raw`\mathbb{R}`),
          " の元で連続。最小正値の問題は Lehmer 問題（1933 年以来未解決の連続ギャップ）になる。",
          "一般の値は計算不能実数でもありうる。",
        ],
        [
          "",
          math(String.raw`\Lambda`),
          " 側: 岩澤型不変量 ",
          math(String.raw`\mu\in\mathbb{Z}_{\ge0}`),
          " は離散。最小正値は ",
          math(String.raw`1`),
          " で自明であり、Lehmer 型の問題は立たない。",
          "有限 ",
          math(String.raw`L`),
          " の ",
          math(String.raw`v_p(a_L)`),
          " は無条件に決定可能（",
          ref("paper_claim_resultant"),
          "）。",
        ],
      ]),
      paragraph([
        "主張: 難しい未解決の連続問題は ",
        math(String.raw`\mathbb{R}`),
        " 側にのみ現れ、",
        math(String.raw`\Lambda`),
        " 側は離散・決定可能である。これは既知の 2 つの理論（Lehmer/Mahler と 岩澤/Ferrero–Washington）が",
        "双対のどちらの素点に乗るかの地図であって、新しい定理ではない。",
      ]),
      paragraph([
        "注意（スケールの偶然一致を接続と呼ばない）: ",
        math(String.raw`\mathbb{Z}^2`),
        " トーラスの全域木エントロピー ",
        math(String.raw`4G/\pi\approx1.166`),
        " と Lehmer 数 ",
        math(String.raw`\approx1.176`),
        " は数値が近いが、これはスケール違いの偶然であって接続ではない。",
        "本論文は両者を接続しない。",
      ]),
    ],
  },
  {
    id: "paper_072_remark_qp_free",
    kind: "remark",
    origin: { path: "structured-latex/content/007_asymmetry_scope.ts", ordinal: 3 },
    title: { text: "Q_p を避ける動機は決定不能性ではない" },
    labels: ["paper_remark_qp_motivation"],
    habitat: "none",
    statement: [
      paragraph([
        "本論文は ",
        math(String.raw`\mathbb{Q}_p`),
        "（非可算）を使わずに議論を組む。この動機を誤解してはならない。",
      ]),
      paragraph([
        math(String.raw`\mathbb{Q}_p`),
        " の一階理論は、正規化された切断つきの付値体の言語で決定可能である",
        "（Ax–Kochen / Ershov）。したがって「",
        math(String.raw`\mathbb{Q}_p`),
        " を避ける」理由は ",
        math(String.raw`\mathbb{Q}_p`),
        " の理論が決定不能だからではない。",
      ]),
      paragraph([
        "本論文の動機は、有限手続きと witness の水準まで降ろすことにある。",
        math(String.raw`\Lambda`),
        " での等号は素因数分解の一致、",
        math(String.raw`\overline{\mathbb{Q}}`),
        " での等号は根の分離であり、いずれも具体的な証拠を伴って判定できる。",
        "既出性の調査結果: 「非可算対象を可算符号で扱う」という移動そのものは確立した標準手法である",
        "（逆数学では実数を急収束 Cauchy 列で符号化し、完備可分距離空間をその一般化として扱う。",
        "構成的代数には完備化を経由せずに Henselization を構成する仕事がある",
        "— Alonso García–Lombardi–Perdry, MLQ 54 (2008)）。",
        "したがって本論文の差分は「可算にしたこと」ではなく、等号を決定可能な水準まで降ろしたことの 1 点に絞られる",
        "（逆数学の符号化では実数・",
        math(String.raw`p`),
        " 進数の等号は決定可能にならない）。",
        math(String.raw`p`),
        " 進付値・岩澤型増大則をこの流儀で扱った文献は、調べた範囲では見つからなかった",
        "（見つからなかったことを新規性の根拠にはしない。MathSciNet は未使用で、検索は本文検索ではない）。",
      ]),
    ],
  },
  {
    id: "paper_080_heading_scope",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/007_asymmetry_scope.ts", ordinal: 4 },
    title: { text: "スコープと限界、形式検証" },
    labels: [],
  },
  {
    id: "paper_081_remark_scope",
    kind: "remark",
    origin: { path: "structured-latex/content/007_asymmetry_scope.ts", ordinal: 5 },
    title: { text: "本論文が主張しないこと" },
    labels: ["paper_remark_scope"],
    habitat: "none",
    statement: [
      paragraph([
        ref("paper_positioning"),
        " を再掲する。本論文は再框であり、新しい定理を主張しない。",
        "以下は本論文が主張しないことの明示である。",
      ]),
      list([
        [
          "可解性について何も主張しない。 熱力学極限の閉形式の有無は軸 4 の問題であり、",
          "本論文が扱う軸 1・2 とは独立である（",
          ref("paper_four_axes"),
          "）。",
        ],
        [
          "新しい厳密解を与えない。 第 3 章のアルキメデス側はすべて既知定理の引用である。",
        ],
        [
          "新しい数論を与えない。 第 4 章の命題 A・B・C・N・L は既知の初等整数論であり、",
          "第 5 章の命題 D の ",
          math(String.raw`(p)`),
          " 側は Monsky / Cuoco–Monsky の定理の適用である。",
        ],
        [
          "命題 T・V・W についても新規性を主張しない。 文献調査の結果は次のとおりである: ",
          "命題 V は ",
          math(String.raw`d=1`),
          " で既出（Gauss–Dold 合同の帰結）、命題 T は弱い形（",
          math(String.raw`v_2`),
          " が偶数）が既出（Kwon–Mednykh–Mednykh）、命題 W は形が ",
          math(String.raw`d=1`),
          " で既出（Vallières Cor 5.7）。",
          "命題 W の ",
          math(String.raw`\mu_1`),
          " については Monsky (ASPM 17, 1989) の本文を Open Access 版で確認した。",
          "同論文は対応する定数 ",
          math(String.raw`\alpha^*`),
          " の存在と（",
          math(String.raw`d=2`),
          " での）有理性しか主張しておらず、明示式は与えていない（",
          ref("paper_prop_W"),
          " の証明の既出性調査を参照）。",
        ],
      ]),
      paragraph([
        "残る未解決点は 2 つである（",
        ref("paper_remark_D_limits"),
        "）: 低位項 ",
        math(String.raw`\lambda_i,\mu_i,\nu`),
        "（",
        math(String.raw`i\ge1`),
        "）の明示公式が一般には無いこと、および消滅深度が ",
        math(String.raw`\theta(P)\ge\ell+1`),
        " となる退化塔の閉形式が無いことである。",
        "（かつてここに挙げていた ",
        math(String.raw`\lambda=l_0(f)`),
        " の計算可能性は ",
        ref("paper_prop_F"),
        " で解消した。ただし解消したのは台が有限な場合に限る。）",
        "いずれも命題 D の限界として明記してあり、論文の射程を狭める。",
      ]),
    ],
  },
  {
    id: "paper_082_remark_formalization",
    kind: "remark",
    origin: { path: "structured-latex/content/007_asymmetry_scope.ts", ordinal: 6 },
    title: { text: "形式検証の到達点" },
    labels: ["paper_remark_formalization"],
    habitat: "none",
    statement: [
      paragraph([
        "本論文は選別基準が要求する「原理的に ",
        math(String.raw`\mathrm{decide}`),
        " ／ witness に乗る」という水準に留めず、",
        "Lean 4 + mathlib4 で実際に形式化した。形式化した命題については",
        math(String.raw`\mathrm{sorry}`),
        " ゼロを機械確認している。",
      ]),
      paragraph([
        "被覆は全数ではない。本論文の主張 24 件のうち、内容が形式化されているのは 8 件、",
        "一部が形式化されているのは 14 件、未着手が 2 件である。",
        "全数の形式化を目標に置いており、残っている主張と、その一つ一つについて",
        "何が残っているか（あるいはなぜ着手していないか）は、下記の表に記録する。",
      ]),
      paragraph([
        "目標は本論文が自分で述べる主張だけを対象にしていない。",
        "本論文が証明せず引用している外部定理も、証明を添える対象に含める。",
        "無制限に広げないための線引きは、証明の根拠として引いているか、",
        "可算側の内容を担うか、既に mathlib にあるか、の三つで決める。",
        "この線引きを当てた結果、",
        "自分で証明することにした外部定理は 7 件であり、",
        "そのうち証明を書き終えたのは 1 件である。",
        "実数側の解析を主張の本体とする外部定理 2 件は、証明せず脱出の一点として隔離する。",
        "隔離できていること（可算側の主張がそれに依存しないこと）は、その都度根拠を書く。",
      ]),
      paragraph([
        "形式化の現状（完了・部分的・未着手と、その理由）は ",
        math(String.raw`\texttt{integrable-lattice/lean/README.md}`),
        " の表に記録する。 形式化できなかった命題については、",
        "mathlib に何が無いか、あるいはどの段で詰まったかを一次情報（試したコードとエラー出力）で",
        "具体化してある。「難しそう」という理由は書かない。",
      ]),
      paragraph([
        "数値検証（SageMath）との対応は各ブロックの ",
        math(String.raw`\texttt{verification}`),
        " フィールド、",
        "Lean 定理との対応は ",
        math(String.raw`\texttt{lean}`),
        " フィールドで機械的に辿れる。対応が切れていないことは",
        math(String.raw`\texttt{sagemath/tools/verify-check-linkage.ts}`),
        " が検査する。",
      ]),
    ],
  },
]);
