/**
 * 論文本体 第 9 章: 消滅深度の p 進化（命題 J）。
 *
 * 命題 G (G1'') が「消滅深度 θ ≤ ℓ の範囲でだけ方向の不変量になる」と述べていた部分を、
 * θ を P^1(Z_ℓ) 上の関数として扱い直すことで拡張する。根拠レポートは
 * outputs/reports/cycle19_T3_theta_ge_ell_plus_1.md。
 *
 * 本章の主張はすべて Z・F_ℓ・Q(ζ_{ℓ^M}) の中で閉じる（ℝ を使わない）。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_090_heading_theta_padic",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/008_theta_padic.ts", ordinal: 1 },
    title: { text: "消滅深度の p 進化 — 塔の型を決めるのは θ = ∞ の p 進点である" },
    labels: [],
  },
  {
    id: "paper_091_theorem_theta_padic",
    kind: "theorem",
    origin: { path: "structured-latex/content/008_theta_padic.ts", ordinal: 2 },
    title: { text: "命題 J — 桁定理、ファイバー Newton 公式、型 II / 型 III の判別" },
    labels: ["paper_prop_J"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle19_T3_theta_ge_ell"],
    statement: [
      paragraph([
        ref("paper_prop_G"),
        " の設定（グラフの ",
        math(String.raw`\mathbb{Z}_\ell^2`),
        " 塔、",
        math(String.raw`\kappa_n`),
        " は ",
        math(String.raw`n`),
        " 段目の全域木数、",
        math(String.raw`\tilde E=\sum c_{pq}z^pw^q`),
        "、",
        math(String.raw`A_m(a,b)=\sum c_{pq}\binom{pa+qb}{m}`),
        "）で、消滅深度を ",
        math(String.raw`\theta(a,b)=\min\{m:\ell\nmid A_m(a,b)\}`),
        " とする。",
      ]),
      paragraph([
        "**(J1 桁定理)** ",
        math(String.raw`L\ge1`),
        " とすると、",
        math(String.raw`0\le m\le\ell^{L}`),
        " なる ",
        math(String.raw`m`),
        " について ",
        math(String.raw`A_m(a,b)\bmod\ell`),
        " は ",
        math(String.raw`(a,b)\bmod\ell^{L}`),
        " だけの関数である。したがって ",
        math(String.raw`\theta(a,b)\le\ell^{L}`),
        " ならば ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`(a,b)\bmod\ell^{L}`),
        " で決まる。とくに ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " 上の関数へ延び、有限な点では局所定数である。",
      ]),
      paragraph([
        "**(J1′ 閾値の鋭さ)** ",
        math(String.raw`m=\ell^{L}+1`),
        " での破れは ",
        math(String.raw`\bar A_2`),
        " の極形式 ",
        math(String.raw`\bar B(x,y)=\sum\bar c_{pq}\overline{(px_1+qx_2)}\,\overline{(py_1+qy_2)}`),
        " で与えられ、",
        math(String.raw`L`),
        " に依らない。よって ",
        math(String.raw`\ell`),
        " が奇素数なら「破れる ",
        math(String.raw`\iff k=2`),
        "」（ここで ",
        math(String.raw`k`),
        " は ",
        ref("paper_prop_W"),
        " と同じく、",
        math(String.raw`\bar E`),
        " の最低次斉次部分の次数である）、",
        math(String.raw`\ell=2`),
        " なら「破れる ",
        math(String.raw`\iff\bar A_2`),
        " が ",
        math(String.raw`\mathbb{F}_2`),
        " 上の平方でない」である。",
      ]),
      paragraph([
        "**(J2 ファイバー Newton 公式)** 方向 ",
        math(String.raw`P_0=(1{:}c)\in\mathbb{P}^1(\mathbb{F}_\ell)`),
        " について、",
        math(String.raw`\bar{\tilde E}(z,w(1+u))=\sum_j D_j(z,w)u^j`),
        "（",
        math(String.raw`D_j=\sum\bar c_{pq}\binom qj z^pw^q`),
        "）と置き、",
        math(String.raw`e_j:=\mathrm{ord}_{x=0}D_j\bigl(1+x,(1+x)^c\bigr)`),
        " とする。",
        math(String.raw`\beta\in\mathbb{Z}_\ell`),
        "、",
        math(String.raw`r=1+v_\ell(\beta)`),
        " に対し",
      ]),
      displayMath(
        String.raw`\theta(1,c+\ell\beta)\ \ge\ \Lambda(r):=\min_{j\ge0}\bigl(e_j+j\,\ell^{r}\bigr),`,
      ),
      paragraph([
        "であり、最小点が一意なら等号が成り立つ。とくに **",
        math(String.raw`e_0<\infty`),
        " かつ すべての ",
        math(String.raw`j\ge1`),
        " で ",
        math(String.raw`e_j+j\ell>e_0`),
        " ならば ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`P_0`),
        " 上のファイバー全体で定数 ",
        math(String.raw`e_0`),
        " である**。この判定条件は ",
        math(String.raw`\theta(P_0)\le\ell`),
        "（",
        ref("paper_prop_G"),
        " が要求していた条件）を真に含む有限計算である。",
      ]),
      paragraph([
        "**(J3 レベル分解と一般の予言)** ",
        math(String.raw`\hat\theta_{M}(\zeta,\xi):=\varphi(\ell^{M})\,v_\ell(E(\zeta,\xi))`),
        " と置くと、仮定なしに ",
        math(String.raw`\Sigma_n=\sum_{M=1}^{n}\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{M})}\hat\theta_{M}(P)`),
        " が成り立ち（",
        math(String.raw`\varphi`),
        " は完全に相殺する）、さらに ",
        math(String.raw`\min_m\bigl(\varphi(\ell^{M})v_\ell(A_m)+m\bigr)`),
        " の最小点が一意ならその値が ",
        math(String.raw`\hat\theta_{M}`),
        " に等しい。したがって ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)`),
        " は ",
        math(String.raw`D`),
        " の係数からの有限計算だけで決まる（塔の値も円分体の計算も使わない）。",
      ]),
      paragraph([
        "**(J4 型 II / 型 III の判別)** ",
        math(String.raw`\theta`),
        " が ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " 上で至る所有限ならば ",
        math(String.raw`\theta`),
        " は有界で、ある ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{L})`),
        " を経由し、",
        math(String.raw`n`),
        " が十分大きいところで",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_\ell(\kappa_n)=\mu(\ell^{2n}-1)+\frac{\Theta_L}{\varphi(\ell^{L})}\,\ell^{n}-2n+\nu,
        \qquad \Theta_L=\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{L})}\theta(P),`,
      ),
      paragraph([
        "すなわち **",
        math(String.raw`n\ell^n`),
        " 項は現れない（型 II）**。",
        ref("paper_prop_G"),
        " の (G1″) はこの ",
        math(String.raw`L=1`),
        " の場合である。逆に ",
        math(String.raw`\theta(P_0)=\infty`),
        "（",
        math(String.raw`\bar E`),
        " が 1 径数部分群上で恒等的に消える）方向があると ",
        math(String.raw`n\ell^n`),
        " 項が現れ、打ち消しが起きないという仮定の下でその係数は",
      ]),
      displayMath(
        String.raw`b=\sum_{P\in S_\infty} j^*(P),\qquad
        S_\infty=\{P\in\mathbb{P}^1(\mathbb{Z}_\ell):\theta(P)=\infty\},\qquad
        j^*(P)=\min\{j\ge1: e_j<\infty\}`,
      ),
      paragraph([
        "である（",
        math(String.raw`e_j`),
        " は ",
        math(String.raw`P`),
        " 自身を基点として取る）。**この和は ",
        math(String.raw`\mathbb{P}^1(\mathbb{F}_\ell)`),
        " の方向についてではなく ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " の点についてである**: 方向 ",
        math(String.raw`(1{:}\ell-1)`),
        " の整数代表 ",
        math(String.raw`(1,\ell-1)`),
        " と ",
        math(String.raw`\mathbb{Z}_\ell`),
        " の点 ",
        math(String.raw`(1,-1)`),
        " は別の点で、前者では ",
        math(String.raw`\theta`),
        " が有限ということが実際に起きる。",
        math(String.raw`\ell=2`),
        " では ",
        math(String.raw`S_\infty`),
        " の 2 点が ",
        math(String.raw`\bmod\ 2`),
        " で分離されないため打ち消しが起き、係数 ",
        math(String.raw`b`),
        " 以外は本命題の議論では出ない。",
      ]),
      paragraph([
        "**(J5 型 III の族)** ",
        math(String.raw`\ell`),
        " を奇素数とし、1 頂点の bouquet に voltage ",
        math(String.raw`(1,0)`),
        " のループを ",
        math(String.raw`\ell-1`),
        " 本、",
        math(String.raw`(0,1)`),
        " のループを 1 本置くと、**すべての ",
        math(String.raw`n\ge0`),
        " で**",
      ]),
      displayMath(String.raw`\mathrm{ord}_\ell(\kappa_n)=2n\,\ell^{n}+2\,\ell^{n}-2.`),
      paragraph([
        "これは ",
        math(String.raw`b=2`),
        " の型 III 塔であり、奇素数ごとに存在する。これは ",
        ref("paper_prop_G_infty"),
        " の族 ",
        math(String.raw`p(1,0)+q(0,1)`),
        " の ",
        math(String.raw`(p,q)=(\ell-1,1)`),
        " の場合であり、閉形式も同命題のものと一致する。**族としての一般形は ",
        ref("paper_prop_G_infty"),
        " が与える。** 本命題が (J5) を挙げるのは、それが (J4) の ",
        math(String.raw`b=\sum j^*`),
        " という**別の道具から独立に**導かれ、両者が同じ値に到達することが相互検証になるからである。",
      ]),
      paragraph([
        "**(J6 ",
        math(String.raw`S_\infty`),
        " は有限で、点はすべて有理点である)** 相異なる ",
        math(String.raw`\gamma_1,\dots,\gamma_k\in\mathbb{Z}_\ell`),
        " に対し ",
        math(String.raw`(1+x)^{\gamma_1},\dots,(1+x)^{\gamma_k}\in\mathbb{F}_\ell[[x]]`),
        " は ",
        math(String.raw`\mathbb{F}_\ell`),
        " 上一次独立である（(J1) の桁安定性から従う）。したがって ",
        math(String.raw`S:=\mathrm{supp}(\bar{\tilde E})`),
        " と置くと、原始的な ",
        math(String.raw`(a,b)\in\mathbb{Z}_\ell^2`),
        " について",
      ]),
      displayMath(
        String.raw`\theta(a,b)=\infty\iff
        \forall\gamma\in\mathbb{Z}_\ell:\ \sum_{\substack{(p,q)\in S\\ pa+qb=\gamma}}\bar c_{pq}=0,`,
      ),
      paragraph([
        "であり、とくに ",
        math(String.raw`\theta(a,b)=\infty`),
        " ならば相異なる ",
        math(String.raw`(p,q),(p',q')\in S`),
        " で ",
        math(String.raw`pa+qb=p'a+q'b`),
        " となるものが存在する。この条件は**整数係数の 1 次方程式**なので、",
      ]),
      displayMath(
        String.raw`S_\infty\subseteq\bigl\{(q-q'\,{:}\,p'-p)\ :\ (p,q)\neq(p',q')\in S\bigr\},`,
      ),
      paragraph([
        "すなわち ",
        math(String.raw`S_\infty`),
        " は高々 ",
        math(String.raw`\binom{|S|}{2}`),
        " 点の**有限集合**で、その点はすべて ",
        math(String.raw`\mathbb{P}^1(\mathbb{Q})`),
        " に属し、候補は ",
        math(String.raw`D`),
        " の係数からの有限計算で尽きる。**よって (J4) の後半で ",
        math(String.raw`b=\sum_{P\in S_\infty}j^*(P)`),
        " が有限和であるために暗に要求される「",
        math(String.raw`S_\infty`),
        " が有限」という条件は、自動的に満たされる（仮定として置く必要が無い）。** この候補集合は ",
        ref("paper_prop_G_infty"),
        " が Newton 多面体の Minkowski 分解から得た候補（",
        math(String.raw`\mathrm{Newt}(\bar{\tilde E})-\mathrm{Newt}(\bar{\tilde E})`),
        " の方向）と一致する。違いは、同命題が ",
        math(String.raw`\mathbb{Z}^2`),
        " のベクトルについて述べるのに対し、(J6) は ",
        math(String.raw`\mathbb{Z}_\ell^2`),
        " のベクトルについて述べていることであり、(J4) が必要とするのは後者である。",
      ]),
      paragraph([
        "**限界（主張の一部として述べる）**",
      ]),
      list([
        [
          "(J2) の最小点が一意でない（打ち消しが起きる）場合、",
          math(String.raw`\theta`),
          " は決まらない。実例は ",
          math(String.raw`\ell=2`),
          " のトーラスの ",
          math(String.raw`r=1`),
          " で、",
          math(String.raw`\Lambda(1)=4`),
          " に対し実際は ",
          math(String.raw`\theta=6`),
          " である。",
        ],
        [
          "(J6) は ",
          math(String.raw`S_\infty`),
          " の**候補**を有限個の有理点へ絞るが、各候補で ",
          math(String.raw`\theta=\infty`),
          " かどうかの**判定**（各 ",
          math(String.raw`\gamma`),
          " 類の係数和が消えるか）を一般の塔について実装・検証してはいない。",
          "族については ",
          ref("paper_prop_G_infty"),
          " が完全に解いている。",
        ],
        [
          "(J4) の残る仮定は、レベルが十分深いところで (J2)・(J3) の最小点が一意であること",
          "（打ち消しが起きないこと）である。",
          math(String.raw`\ell=2`),
          " のトーラスではこれが破れており、そこでは係数 ",
          math(String.raw`b`),
          " が正しい値を与えることは照合であって証明ではない。",
        ],
        [
          "本命題は ",
          math(String.raw`d=2`),
          " に限る。",
        ],
        [
          "**新規性は主張しない。** (J2) は形式群 ",
          math(String.raw`\hat{\mathbb{G}}_m`),
          " の 1 径数部分群への引き戻しの Newton 多角形であり、岩澤理論では標準的な道具である可能性が高い。",
          "対応する文献命題は特定できていない。",
        ],
      ]),
    ],
  },
]);
