/**
 * 論文本体 第 9 章: 消滅深度の p 進化（命題 J）。
 *
 * 命題 G (G6) が「消滅深度 θ ≤ ℓ の範囲でだけ方向の不変量になる」と述べていた部分を、
 * θ を P^1(Z_ℓ) 上の関数として扱い直すことで拡張する。根拠レポートは
 * outputs/reports/cycle19_T3_theta_ge_ell_plus_1.md。
 *
 * 本章の主張はすべて Z・F_ℓ・Q(ζ_{ℓ^M}) の中で閉じる（ℝ を使わない）。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_090_heading_theta_padic",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/008_theta_padic.ts", ordinal: 1 },
    title: { text: "消滅深度の p 進化 — 塔の型を決めるのは θ = ∞ の p 進点である" },
    labels: [],
  },
  {
    id: "paper_091_theorem_theta_padic",
    kind: "theorem",
    origin: { path: "structured-latex/content/008_theta_padic.ts", ordinal: 2 },
    title: { text: "命題 J — 桁定理、ファイバー Newton 公式、型 II / 型 III の判別" },
    labels: ["paper_prop_J"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle19_T3_theta_ge_ell"],
    lean: [
      "IntegrableLattice.choose_cast_of_lt",
      "IntegrableLattice.choose_cast_pow",
      "IntegrableLattice.choose_cast_pow_succ",
      "IntegrableLattice.Abar_shift",
      "IntegrableLattice.Abar_congr",
      "IntegrableLattice.Abar_shift_pow_succ",
      "IntegrableLattice.Bbar_diag",
      "IntegrableLattice.cexDigit_fails",
      "IntegrableLattice.sum_level_stab",
      "IntegrableLattice.level_ratio_indep",
      "IntegrableLattice.layer_sum",
      "IntegrableLattice.sum_mul_pow",
      "IntegrableLattice.sum_Theta_J8",
      "IntegrableLattice.ordKappa_J8",
      "IntegrableLattice.j1_freshman_dream",
    ],
    statement: [
      paragraph([
        ref("paper_prop_G"),
        " の設定（グラフの ",
        math(String.raw`\mathbb{Z}_\ell^2`),
        " 塔、",
        math(String.raw`\kappa_n`),
        " は ",
        math(String.raw`n`),
        " 段目の全域木数、",
        math(String.raw`\tilde E=\sum c_{pq}z^pw^q`),
        "、",
        math(String.raw`A_m(a,b)=\sum c_{pq}\binom{pa+qb}{m}`),
        "）で、消滅深度を ",
        math(String.raw`\theta(a,b)=\min\{m:\ell\nmid A_m(a,b)\}`),
        " とする。規約（書き落とせない）: そのような ",
        math(String.raw`m`),
        " が 1 つも無ければ ",
        math(String.raw`\theta(a,b):=\infty`),
        " と読む。本命題の主役である ",
        math(String.raw`S_\infty`),
        " はこの読みでしか定義されない（下の (J4) の ",
        math(String.raw`S_\infty=\{P:\theta(P)=\infty\}`),
        " は、",
        math(String.raw`\min\emptyset=0`),
        " と読むと空集合になり、",
        math(String.raw`n\ell^n`),
        " の係数 ",
        math(String.raw`b`),
        " が常に ",
        math(String.raw`0`),
        " になってしまう）。",
      ]),
      paragraph([
        "(J1 桁定理) ",
        math(String.raw`L\ge1`),
        " とすると、",
        math(String.raw`0\le m\le\ell^{L}`),
        " なる ",
        math(String.raw`m`),
        " について ",
        math(String.raw`A_m(a,b)\bmod\ell`),
        " は ",
        math(String.raw`(a,b)\bmod\ell^{L}`),
        " だけの関数である。ここで ",
        math(String.raw`m=\ell^{L}`),
        " ちょうどの場合には ",
        math(String.raw`A_1\equiv0`),
        "（",
        math(String.raw`D(z,w)=D(z^{-1},w^{-1})`),
        " から従う整数としての恒等式。",
        ref("paper_prop_G"),
        " の (G6)）を使う。実際この仮定を落とすと ",
        math(String.raw`m=\ell^{L}`),
        " の場合は偽で、",
        math(String.raw`\tilde E=z`),
        "、",
        math(String.raw`\ell=3`),
        "、",
        math(String.raw`L=1`),
        " が反例である（",
        math(String.raw`\bar A_3(3,0)=1\neq0=\bar A_3(0,0)`),
        "）。",
        math(String.raw`m<\ell^{L}`),
        " の場合は Lucas の定理だけから従い、この仮定を使わない。したがって ",
        math(String.raw`\theta(a,b)\le\ell^{L}`),
        " ならば ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`(a,b)\bmod\ell^{L}`),
        " で決まる。とくに ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " 上の関数へ延び、有限な点では局所定数である。",
      ]),
      paragraph([
        "(J1′ 閾値の鋭さ) ",
        math(String.raw`m=\ell^{L}+1`),
        " での破れは ",
        math(String.raw`\bar A_2`),
        " の極形式 ",
        math(String.raw`\bar B(x,y)=\sum\bar c_{pq}\overline{(px_1+qx_2)}\,\overline{(py_1+qy_2)}`),
        " で与えられ、",
        math(String.raw`L`),
        " に依らない。よって ",
        math(String.raw`\ell`),
        " が奇素数なら「破れる ",
        math(String.raw`\iff k=2`),
        "」（ここで ",
        math(String.raw`k`),
        " は ",
        ref("paper_prop_W"),
        " と同じく、",
        math(String.raw`\bar E`),
        " の最低次斉次部分の次数である）、",
        math(String.raw`\ell=2`),
        " なら「破れる ",
        math(String.raw`\iff\bar A_2`),
        " が ",
        math(String.raw`\mathbb{F}_2`),
        " 上の平方でない」である。",
      ]),
      paragraph([
        "(J2 ファイバー Newton 公式) 方向 ",
        math(String.raw`P_0=(1{:}c)\in\mathbb{P}^1(\mathbb{F}_\ell)`),
        " について、",
        math(String.raw`\bar{\tilde E}(z,w(1+u))=\sum_j D_j(z,w)u^j`),
        "（",
        math(String.raw`D_j=\sum\bar c_{pq}\binom qj z^pw^q`),
        "）と置き、",
        math(String.raw`e_j:=\mathrm{ord}_{x=0}D_j\bigl(1+x,(1+x)^c\bigr)`),
        " とする。",
        math(String.raw`\beta\in\mathbb{Z}_\ell`),
        "、",
        math(String.raw`r=1+v_\ell(\beta)`),
        " に対し",
      ]),
      displayMath(
        String.raw`\theta(1,c+\ell\beta)\ \ge\ \Lambda(r):=\min_{j\ge0}\bigl(e_j+j\,\ell^{r}\bigr),`,
      ),
      paragraph([
        "であり、最小点が一意なら等号が成り立つ。とくに ",
        math(String.raw`e_0<\infty`),
        " かつ すべての ",
        math(String.raw`j\ge1`),
        " で ",
        math(String.raw`e_j+j\ell>e_0`),
        " ならば ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`P_0`),
        " 上のファイバー全体で定数 ",
        math(String.raw`e_0`),
        " である。この判定条件は ",
        math(String.raw`\theta(P_0)\le\ell`),
        "（",
        ref("paper_prop_G"),
        " が要求していた条件）を真に含む有限計算である。",
      ]),
      paragraph([
        "(J3 レベル分解と一般の予言) ",
        math(String.raw`\hat\theta_{M}(\zeta,\xi):=\varphi(\ell^{M})\,v_\ell(E(\zeta,\xi))`),
        " と置くと、仮定なしに ",
        math(String.raw`\Sigma_n=\sum_{M=1}^{n}\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{M})}\hat\theta_{M}(P)`),
        " が成り立ち（",
        math(String.raw`\varphi`),
        " は完全に相殺する）、さらに ",
        math(String.raw`\min_m\bigl(\varphi(\ell^{M})v_\ell(A_m)+m\bigr)`),
        " の最小点が一意ならその値が ",
        math(String.raw`\hat\theta_{M}`),
        " に等しい。したがって ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)`),
        " は ",
        math(String.raw`D`),
        " の係数からの有限計算だけで決まる（塔の値も円分体の計算も使わない）。",
      ]),
      paragraph([
        "(J4 型 II / 型 III の判別) ",
        math(String.raw`\theta`),
        " が ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " 上で至る所有限ならば ",
        math(String.raw`\theta`),
        " は有界で、ある ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{L})`),
        " を経由し、",
        math(String.raw`n`),
        " が十分大きいところで",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_\ell(\kappa_n)=\mu(\ell^{2n}-1)+\frac{\Theta_L}{\varphi(\ell^{L})}\,\ell^{n}-2n+\nu,
        \qquad \Theta_L=\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{L})}\theta(P),`,
      ),
      paragraph([
        "すなわち ",
        math(String.raw`n\ell^n`),
        " 項は現れない（型 II）。",
        ref("paper_prop_G"),
        " の (G6) はこの ",
        math(String.raw`L=1`),
        " の場合である。逆に ",
        math(String.raw`\theta(P_0)=\infty`),
        "（",
        math(String.raw`\bar E`),
        " が 1 径数部分群上で恒等的に消える）方向があると ",
        math(String.raw`n\ell^n`),
        " 項が現れ、打ち消しが起きないという仮定の下でその係数は",
      ]),
      displayMath(
        String.raw`b=\sum_{P\in S_\infty} j^*(P),\qquad
        S_\infty=\{P\in\mathbb{P}^1(\mathbb{Z}_\ell):\theta(P)=\infty\},\qquad
        j^*(P)=\min\{j\ge1: e_j<\infty\}`,
      ),
      paragraph([
        "である（",
        math(String.raw`e_j`),
        " は ",
        math(String.raw`P`),
        " 自身を基点として取る）。",
        math(String.raw`j^*(P)`),
        " の最小を取る集合が空でないこと、すなわち ",
        math(String.raw`e_j<\infty`),
        " なる ",
        math(String.raw`j\ge1`),
        " が存在することは本命題では示していない。",
        ref("paper_prop_K"),
        " の (K4) が ",
        math(String.raw`e_{m_u}<\infty`),
        " を示してこれを埋める（",
        math(String.raw`m_u`),
        " は ",
        math(String.raw`\chi^{u^\perp}-1`),
        " の重複度）。この和は ",
        math(String.raw`\mathbb{P}^1(\mathbb{F}_\ell)`),
        " の方向についてではなく ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " の点についてである: 方向 ",
        math(String.raw`(1{:}\ell-1)`),
        " の整数代表 ",
        math(String.raw`(1,\ell-1)`),
        " と ",
        math(String.raw`\mathbb{Z}_\ell`),
        " の点 ",
        math(String.raw`(1,-1)`),
        " は別の点で、前者では ",
        math(String.raw`\theta`),
        " が有限ということが実際に起きる。",
        math(String.raw`\ell=2`),
        " では ",
        math(String.raw`S_\infty`),
        " の 2 点が ",
        math(String.raw`\bmod\ 2`),
        " で分離されないため打ち消しが起き、係数 ",
        math(String.raw`b`),
        " 以外は本命題の議論では出ない。",
      ]),
      paragraph([
        "(J5 型 III の族) ",
        math(String.raw`\ell`),
        " を奇素数とし、1 頂点の bouquet に voltage ",
        math(String.raw`(1,0)`),
        " のループを ",
        math(String.raw`\ell-1`),
        " 本、",
        math(String.raw`(0,1)`),
        " のループを 1 本置くと、すべての ",
        math(String.raw`n\ge0`),
        " で",
      ]),
      displayMath(String.raw`\mathrm{ord}_\ell(\kappa_n)=2n\,\ell^{n}+2\,\ell^{n}-2.`),
      paragraph([
        "これは ",
        math(String.raw`b=2`),
        " の型 III 塔であり、奇素数ごとに存在する。これは ",
        ref("paper_prop_G_infty"),
        " の族 ",
        math(String.raw`p(1,0)+q(0,1)`),
        " の ",
        math(String.raw`(p,q)=(\ell-1,1)`),
        " の場合であり、閉形式も同命題のものと一致する。族としての一般形は ",
        ref("paper_prop_G_infty"),
        " が与える。 本命題が (J5) を挙げるのは、それが (J4) の ",
        math(String.raw`b=\sum j^*`),
        " という別の道具から独立に導かれ、両者が同じ値に到達することが相互検証になるからである。",
      ]),
      paragraph([
        "(J6 ",
        math(String.raw`S_\infty`),
        " は有限で、点はすべて有理点である) 相異なる ",
        math(String.raw`\gamma_1,\dots,\gamma_k\in\mathbb{Z}_\ell`),
        " に対し ",
        math(String.raw`(1+x)^{\gamma_1},\dots,(1+x)^{\gamma_k}\in\mathbb{F}_\ell[[x]]`),
        " は ",
        math(String.raw`\mathbb{F}_\ell`),
        " 上一次独立である（(J1) の桁安定性から従う）。したがって ",
        math(String.raw`S:=\mathrm{supp}(\bar{\tilde E})`),
        " と置くと、原始的な ",
        math(String.raw`(a,b)\in\mathbb{Z}_\ell^2`),
        " について",
      ]),
      displayMath(
        String.raw`\theta(a,b)=\infty\iff
        \forall\gamma\in\mathbb{Z}_\ell:\ \sum_{\substack{(p,q)\in S\\ pa+qb=\gamma}}\bar c_{pq}=0,`,
      ),
      paragraph([
        "であり、とくに ",
        math(String.raw`\theta(a,b)=\infty`),
        " ならば相異なる ",
        math(String.raw`(p,q),(p',q')\in S`),
        " で ",
        math(String.raw`pa+qb=p'a+q'b`),
        " となるものが存在する。この条件は整数係数の 1 次方程式なので、",
      ]),
      displayMath(
        String.raw`S_\infty\subseteq\bigl\{(q-q'\,{:}\,p'-p)\ :\ (p,q)\neq(p',q')\in S\bigr\},`,
      ),
      paragraph([
        "すなわち ",
        math(String.raw`S_\infty`),
        " は高々 ",
        math(String.raw`\binom{|S|}{2}`),
        " 点の有限集合で、その点はすべて ",
        math(String.raw`\mathbb{P}^1(\mathbb{Q})`),
        " に属し、候補は ",
        math(String.raw`D`),
        " の係数からの有限計算で尽きる。よって (J4) の後半で ",
        math(String.raw`b=\sum_{P\in S_\infty}j^*(P)`),
        " が有限和であるために暗に要求される「",
        math(String.raw`S_\infty`),
        " が有限」という条件は、自動的に満たされる（仮定として置く必要が無い）。 この候補集合は ",
        ref("paper_prop_G_infty"),
        " が Newton 多面体の Minkowski 分解から得た候補（",
        math(String.raw`\mathrm{Newt}(\bar{\tilde E})-\mathrm{Newt}(\bar{\tilde E})`),
        " の方向）と一致する。違いは、同命題が ",
        math(String.raw`\mathbb{Z}^2`),
        " のベクトルについて述べるのに対し、(J6) は ",
        math(String.raw`\mathbb{Z}_\ell^2`),
        " のベクトルについて述べていることであり、(J4) が必要とするのは後者である。",
      ]),
      paragraph([
        "限界",
      ]),
      list([
        [
          "(J2) の最小点が一意でない（打ち消しが起きる）場合、",
          math(String.raw`\theta`),
          " は決まらない。実例は ",
          math(String.raw`\ell=2`),
          " のトーラスの ",
          math(String.raw`r=1`),
          " で、",
          math(String.raw`\Lambda(1)=4`),
          " に対し実際は ",
          math(String.raw`\theta=6`),
          " である。",
        ],
        [
          "(J6) は ",
          math(String.raw`S_\infty`),
          " の候補を有限個の有理点へ絞るが、各候補で ",
          math(String.raw`\theta=\infty`),
          " かどうかの判定（各 ",
          math(String.raw`\gamma`),
          " 類の係数和が消えるか）を一般の塔について実装・検証してはいない。",
          "族については ",
          ref("paper_prop_G_infty"),
          " が完全に解いている。",
        ],
        [
          "(J4) の残る仮定は、レベルが十分深いところで (J2)・(J3) の最小点が一意であること",
          "（打ち消しが起きないこと）である。",
          math(String.raw`\ell=2`),
          " のトーラスではこれが破れており、そこでは係数 ",
          math(String.raw`b`),
          " が正しい値を与えることは照合であって証明ではない。",
        ],
        [
          "本命題は ",
          math(String.raw`d=2`),
          " に限る。",
        ],
        [
          "新規性は主張しない。 (J2) は形式群 ",
          math(String.raw`\hat{\mathbb{G}}_m`),
          " の 1 径数部分群への引き戻しの Newton 多角形であり、岩澤理論では標準的な道具である可能性が高い。",
          "対応する文献命題は特定できていない。",
          "ただし (J4) の係数の式そのものは既出である。 当の係数は ",
          math(String.raw`b`),
          " であり、出典は Cuoco–Monsky, Math. Ann. 255 (1981) の Theorem 1.7 と Definition 1.2 である。",
          "帰属の詳細は ",
          ref("paper_prop_K"),
          " の「限界」に書いた。",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "本文に無い補題へ暗黙に依存しないために、途中で使う事実はすべてその主張をここで述べてから使う。 ",
        "使う道具は Lucas の定理、",
        math(String.raw`\mathbb{F}_\ell`),
        " 上の Frobenius、円分体 ",
        math(String.raw`\mathbb{Q}(\zeta_{\ell^{M}})`),
        " の ",
        math(String.raw`\ell`),
        " の上の唯一の素点での付値、および ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " のコンパクト性だけである。",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " は非可算だが、以下で使うのは有限レベル ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{L})`),
        " への還元と有限被覆の存在だけであり、実数体へは一度も出ない。",
      ]),
      paragraph([
        "(J1) の証明。 ",
        math(String.raw`(a,b)\mapsto(a+\ell^{L}u,\ b+\ell^{L}v)`),
        " による ",
        math(String.raw`\bar A_m`),
        " の変化を見る。",
        math(String.raw`N=pa+qb\mapsto N+\ell^{L}(pu+qv)`),
        " なので、",
        math(String.raw`N`),
        " の第 ",
        math(String.raw`0,\dots,L-1`),
        " 桁は変わらない。",
        math(String.raw`m<\ell^{L}`),
        " のときは、Lucas の定理 ",
        math(String.raw`\binom{N}{m}\equiv\prod_i\binom{N_i}{m_i}`),
        " において ",
        math(String.raw`i\ge L`),
        " で ",
        math(String.raw`m_i=0`),
        "、",
        math(String.raw`\binom{N_i}{0}=1`),
        " だから右辺は下位 ",
        math(String.raw`L`),
        " 桁だけで決まり、不変である。",
      ]),
      paragraph([
        math(String.raw`m=\ell^{L}`),
        " ちょうどのときは ",
        math(String.raw`m_L=1`),
        " で他の桁が ",
        math(String.raw`0`),
        " なので ",
        math(String.raw`\binom{N}{\ell^{L}}\equiv\binom{N_L}{1}=N_L`),
        " であり、下位桁が変わらないので第 ",
        math(String.raw`L`),
        " 桁への繰り上がりが無く ",
        math(String.raw`N_L\mapsto N_L+(pu+qv)`),
        " である。したがって",
      ]),
      displayMath(
        String.raw`\bar A_{\ell^{L}}\bigl(a+\ell^{L}u,\ b+\ell^{L}v\bigr)-\bar A_{\ell^{L}}(a,b)
        =\sum_{(p,q)}\bar c_{pq}\,\overline{(pu+qv)}=\overline{A_1(u,v)}=0,`,
      ),
      paragraph([
        "最後の等号が ",
        ref("paper_prop_G"),
        " の (G6) の ",
        math(String.raw`A_1\equiv0`),
        "（",
        math(String.raw`D(z,w)=D(z^{-1},w^{-1})`),
        " から従う整数としての恒等式）である。この仮定なしにはこの段は偽であり、主張に挙げた反例がそれを示す。 ",
        math(String.raw`\theta`),
        " の判定に使う添字は ",
        math(String.raw`m\le\theta\le\ell^{L}`),
        " だけなので、",
        math(String.raw`\theta(a,b)\le\ell^{L}`),
        " ならば ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`(a,b)\bmod\ell^{L}`),
        " で決まる。また ",
        math(String.raw`m`),
        " ごとに ",
        math(String.raw`L`),
        " を取り替えれば各 ",
        math(String.raw`\bar A_m`),
        " が ",
        math(String.raw`\mathbb{Z}_\ell^2`),
        " 上の局所定数関数へ延び、",
        math(String.raw`\rho(x)=(1+x)^{c}-1`),
        " の位数がちょうど ",
        math(String.raw`1`),
        " であることから ",
        math(String.raw`\theta(ca,cb)=\theta(a,b)`),
        "（",
        math(String.raw`c\in\mathbb{Z}_\ell^\times`),
        "）となるので、",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " 上の関数を定める。",
      ]),
      paragraph([
        "(J1′) の証明。 ",
        math(String.raw`m=\ell^{L}+1`),
        " は ",
        math(String.raw`m_0=m_L=1`),
        "、他の桁が ",
        math(String.raw`0`),
        " なので ",
        math(String.raw`\binom{N}{\ell^{L}+1}\equiv N_0N_L`),
        " である。",
        math(String.raw`N_0`),
        " は不変、",
        math(String.raw`N_L`),
        " は ",
        math(String.raw`(pu+qv)`),
        " だけ変化するので差は ",
        math(String.raw`\bar B\bigl((a,b),(u,v)\bigr)`),
        " に等しく、",
        math(String.raw`L`),
        " が現れない。",
        math(String.raw`N^2=2\binom{N}{2}+N`),
        " と ",
        math(String.raw`A_1=0`),
        " より ",
        math(String.raw`\bar B(x,x)=\overline{2A_2(x)}`),
        " なので ",
        math(String.raw`\bar B`),
        " は ",
        math(String.raw`\bar A_2`),
        " の極形式である。",
        math(String.raw`\ell`),
        " が奇なら ",
        math(String.raw`2`),
        " が単元で、標数 ",
        math(String.raw`\neq2`),
        " では二次形式は極形式から復元できるから ",
        math(String.raw`\bar B=0\iff\bar A_2=0\iff k\ge3`),
        "、すなわち破れる ",
        math(String.raw`\iff k=2`),
        "。",
        math(String.raw`\ell=2`),
        " では ",
        math(String.raw`\bar B(x,x)=0`),
        " で ",
        math(String.raw`\bar B`),
        " は交代形式になり、",
        math(String.raw`\mathbb{F}_2`),
        " 上で二次形式の極形式が消えることとその形式が Frobenius の像＝平方であることが同値である。",
      ]),
      paragraph([
        "(J2) の証明。 まず ",
        math(String.raw`\beta\in\mathbb{Z}_\ell`),
        "、",
        math(String.raw`v:=v_\ell(\beta)`),
        "、",
        math(String.raw`r=v+1`),
        " のとき ",
        math(String.raw`\mathbb{F}_\ell[[x]]`),
        " で ",
        math(String.raw`(1+x)^{c+\ell\beta}=(1+x)^{c}(1+x^{\ell})^{\beta}`),
        "（Frobenius）であり、",
        math(String.raw`u:=(1+x^{\ell})^{\beta}-1`),
        " は ",
        math(String.raw`\mathrm{ord}_xu=\ell^{r}`),
        "、最低次係数が ",
        math(String.raw`\beta`),
        " の第 ",
        math(String.raw`v`),
        " 桁 ",
        math(String.raw`\beta_v\neq0`),
        " である。実際 Lucas の ",
        math(String.raw`\mathbb{Z}_\ell`),
        " への連続延長 ",
        math(String.raw`\binom{\beta}{m}\equiv\prod_i\binom{\beta_i}{m_i}`),
        " が (J1) により well-defined で、",
        math(String.raw`m\ge1`),
        " でこれが ",
        math(String.raw`0`),
        " でない最小の ",
        math(String.raw`m`),
        " は全ての ",
        math(String.raw`i`),
        " で ",
        math(String.raw`m_i\le\beta_i`),
        " を要するから ",
        math(String.raw`m=\ell^{v}`),
        " であり、そのとき値は ",
        math(String.raw`\beta_v`),
        " である。",
      ]),
      paragraph([
        "そこで ",
        math(String.raw`z^pw^q(1+u)^q=\sum_j\binom qjz^pw^qu^j`),
        " による展開 ",
        math(String.raw`\bar{\tilde E}(z,w(1+u))=\sum_jD_j(z,w)u^j`),
        " に ",
        math(String.raw`z=1+x`),
        "、",
        math(String.raw`w=(1+x)^{c}`),
        "、",
        math(String.raw`1+u=(1+x^{\ell})^{\beta}`),
        " を代入すると、",
        math(String.raw`\psi_j(x):=D_j\bigl(1+x,(1+x)^{c}\bigr)`),
        " の最低次が ",
        math(String.raw`x^{e_j}`),
        "、",
        math(String.raw`u^j`),
        " の最低次が ",
        math(String.raw`\beta_v^{\,j}x^{\,j\ell^{r}}`),
        " だから ",
        math(String.raw`\mathrm{ord}_x(\psi_ju^j)=e_j+j\ell^{r}`),
        " である。よって ",
        math(String.raw`\theta(1,c+\ell\beta)\ge\Lambda(r)`),
        " であり、",
        math(String.raw`x^{\Lambda(r)}`),
        " の係数は ",
        math(String.raw`\sum_{j\in J(r)}\lambda_j\beta_v^{\,j}`),
        "（",
        math(String.raw`J(r)`),
        " は最小点の集合、",
        math(String.raw`\lambda_j`),
        " は ",
        math(String.raw`\psi_j`),
        " の最低次係数）なので、最小点が一意なら係数が ",
        math(String.raw`0`),
        " でなく等号が成り立つ。",
      ]),
      paragraph([
        "とくに ",
        math(String.raw`e_0<\infty`),
        " かつ 全ての ",
        math(String.raw`j\ge1`),
        " で ",
        math(String.raw`e_j+j\ell>e_0`),
        " ならば、",
        math(String.raw`r\ge1`),
        " より ",
        math(String.raw`e_j+j\ell^{r}\ge e_j+j\ell>e_0`),
        " なので ",
        math(String.raw`J(r)=\{0\}`),
        " が全ての ",
        math(String.raw`r`),
        " で成り立ち、ファイバー全体で ",
        math(String.raw`\theta\equiv e_0`),
        " である（",
        math(String.raw`\beta=0`),
        " の点は ",
        math(String.raw`P_0`),
        " 自身）。この条件が ",
        math(String.raw`\theta(P_0)\le\ell`),
        " を真に含むことは次で分かる: ",
        math(String.raw`\psi_1(0)=D_1(1,1)=\sum c_{pq}q=0`),
        "（",
        math(String.raw`E(1,1)=0`),
        " と ",
        math(String.raw`(\partial_wE)(1,1)=0`),
        " による）なので ",
        math(String.raw`e_1\ge1`),
        "、よって ",
        math(String.raw`e_1+\ell\ge1+\ell>\ell\ge e_0`),
        "、また ",
        math(String.raw`j\ge2`),
        " なら ",
        math(String.raw`e_j+j\ell\ge2\ell>\ell\ge e_0`),
        " である。",
      ]),
      paragraph([
        "(J3) の証明。 ",
        math(String.raw`\Sigma_n`),
        " の和をレベルちょうど ",
        math(String.raw`M`),
        " の点で層別する。レベルちょうど ",
        math(String.raw`M`),
        " の点は、原始 ",
        math(String.raw`\ell^{M}`),
        " 乗根 ",
        math(String.raw`g`),
        " を固定して ",
        math(String.raw`(\zeta,\xi)=(g^a,g^b)`),
        "、",
        math(String.raw`(a,b)`),
        " が原始的なもの全体と 1 対 1 に対応する。",
        math(String.raw`c\in(\mathbb{Z}/\ell^{M})^\times`),
        " による ",
        math(String.raw`(a,b)\mapsto(ca,cb)`),
        " は Galois 作用 ",
        math(String.raw`\zeta\mapsto\zeta^{c}`),
        " に対応し、",
        math(String.raw`\ell`),
        " の上の素点は 1 つしかないので付値を保つ。この作用は自由で軌道は ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{M})`),
        " の点、軌道の大きさは ",
        math(String.raw`\varphi(\ell^{M})`),
        " だから、各軌道の寄与は ",
        math(String.raw`\varphi(\ell^{M})\cdot\hat\theta_{M}(P)/\varphi(\ell^{M})=\hat\theta_{M}(P)`),
        " となり ",
        math(String.raw`\varphi`),
        " が完全に相殺して主張の分解を得る（仮定を使っていない）。",
      ]),
      paragraph([
        "後半は ",
        math(String.raw`\tilde E(\zeta,\xi)=\Phi_{(a,b)}(\pi)=\sum_mA_m\pi^m`),
        "（",
        math(String.raw`\pi=g-1`),
        "）で ",
        math(String.raw`v_\ell(A_m\pi^m)=v_\ell(A_m)+m/\varphi(\ell^{M})`),
        " だから、",
        math(String.raw`\varphi(\ell^{M})`),
        " 倍して非アルキメデス的評価を使えばよい。最小値が一意の ",
        math(String.raw`m`),
        " で達成されるなら和の付値はその最小値に等しい。",
      ]),
      paragraph([
        "(J4) の前半（型 II）の証明。 ",
        math(String.raw`\theta`),
        " が至る所有限とする。(J1) より ",
        math(String.raw`\theta`),
        " は有限な点で局所定数なので ",
        math(String.raw`\{\theta=t\}`),
        " は開集合であり、これらが ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " を被覆するからコンパクト性より有限部分被覆が取れ、値の集合は有限、すなわち ",
        math(String.raw`\theta`),
        " は有界である。",
        math(String.raw`\theta^{\max}`),
        " を最大値、",
        math(String.raw`\ell^{L}\ge\theta^{\max}`),
        " とすると (J1) より ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{L})`),
        " を経由する。",
      ]),
      paragraph([
        math(String.raw`n_1\ge L`),
        " を ",
        math(String.raw`\theta^{\max}-2<\varphi(\ell^{n_1})`),
        " を満たすように取ると、",
        math(String.raw`M\ge n_1`),
        " の点では ",
        math(String.raw`m_1\ge2`),
        "（",
        math(String.raw`A_1\equiv0`),
        " による）と合わせて ",
        math(String.raw`\theta-m_1<\varphi(\ell^{M})`),
        " となり (J3) の最小点は ",
        math(String.raw`m=\theta`),
        " で一意、すなわち ",
        math(String.raw`\hat\theta_{M}=\theta`),
        " である。",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{M})\to\mathbb{P}^1(\mathbb{Z}/\ell^{L})`),
        " のファイバーは一様に ",
        math(String.raw`\ell^{M-L}`),
        " 個なので ",
        math(String.raw`\Theta_{M}=\ell^{M-L}\Theta_L`),
        " となり、(J3) の分解から",
      ]),
      displayMath(
        String.raw`\Sigma_n=\Sigma_{n_1-1}+\Theta_L\sum_{M=n_1}^{n}\ell^{M-L}
        =\Sigma_{n_1-1}+\Theta_L\,\frac{\ell^{\,n-L+1}-\ell^{\,n_1-L}}{\ell-1}`,
      ),
      paragraph([
        "を得る。",
        math(String.raw`\ell^{n}`),
        " の係数は ",
        math(String.raw`\Theta_L\ell^{1-L}/(\ell-1)=\Theta_L/\varphi(\ell^{L})`),
        " で残りは定数だから主張の式になり、",
        math(String.raw`n\ell^{n}`),
        " 項は現れない。",
        math(String.raw`L`),
        " を ",
        math(String.raw`L'>L`),
        " に取り替えると ",
        math(String.raw`\Theta_{L'}=\ell^{L'-L}\Theta_L`),
        " と ",
        math(String.raw`\varphi(\ell^{L'})=\ell^{L'-L}\varphi(\ell^{L})`),
        " で比は不変である。",
      ]),
      paragraph([
        "(J4) の後半（",
        math(String.raw`n\ell^{n}`),
        " の係数）の証明。 ここでは打ち消しが起きないこと、すなわち次を仮定する: ",
        "(N) ある ",
        math(String.raw`r_0\ge1`),
        " があって半径 ",
        math(String.raw`\ell^{-r_0}`),
        " の球 ",
        math(String.raw`B(P,\ell^{-r_0})`),
        "（",
        math(String.raw`P\in S_\infty`),
        "）が互いに素で、各 ",
        math(String.raw`P`),
        " を基点とする ",
        math(String.raw`\Lambda(r)`),
        " の最小点が ",
        math(String.raw`r\ge r_0`),
        " で一意であること、および (B) レベルが十分深いところで (J3) の最小点が一意であること。",
        "この 2 つは限界に挙げた「残る仮定」そのものであり、(J6) が示す ",
        math(String.raw`S_\infty`),
        " の有限性は仮定しなくてよい。",
      ]),
      paragraph([
        math(String.raw`U:=\mathbb{P}^1(\mathbb{Z}_\ell)\setminus\bigcup_{P\in S_\infty}B(P,\ell^{-r_0})`),
        " と置く。",
        math(String.raw`U`),
        " はコンパクトで ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`U`),
        " 上至る所有限だから、前半と同じ議論で ",
        math(String.raw`U`),
        " 上有界であり、ある ",
        math(String.raw`L_U`),
        " で止まる。",
        math(String.raw`M\ge\max(r_0,L_U,n_1)`),
        " とすると、",
        math(String.raw`U`),
        " に含まれる球の寄与は ",
        math(String.raw`\ell^{M}`),
        " の定数倍であり ",
        math(String.raw`M\ell^{M}`),
        " 項をもたない。",
      ]),
      paragraph([
        math(String.raw`P\in S_\infty`),
        " のまわりの球では、",
        math(String.raw`B(P,\ell^{-r_0})`),
        " 内のレベル ",
        math(String.raw`M`),
        " の球が ",
        math(String.raw`\beta`),
        "（",
        math(String.raw`v=v_\ell(\beta)\ge r_0-1`),
        "）で添字づけられ、",
        math(String.raw`v\le M-2`),
        " の層は ",
        math(String.raw`\varphi(\ell^{M-1-v})`),
        " 個ある。",
        math(String.raw`R'\ge r_0`),
        " を ",
        math(String.raw`r\ge R'`),
        " で ",
        math(String.raw`\Lambda(r)=e_{j^*}+j^*\ell^{r}`),
        " となるように取る（",
        math(String.raw`j>j^*`),
        " の項は傾きが大きいので ",
        math(String.raw`r`),
        " が大きければ必ず負ける）。ここで ",
        math(String.raw`\varphi(\ell^{M-1-v})\cdot\ell^{v+1}=\varphi(\ell^{M})`),
        " は ",
        math(String.raw`v`),
        " に依らないので、",
        math(String.raw`v`),
        " が ",
        math(String.raw`R'-1`),
        " から ",
        math(String.raw`M-2`),
        " まで走る層の寄与は",
      ]),
      displayMath(
        String.raw`\sum_{v=R'-1}^{M-2}\varphi(\ell^{M-1-v})\bigl(e_{j^*}+j^*\ell^{\,v+1}\bigr)
        =e_{j^*}\bigl(\ell^{\,M-R'}-1\bigr)+j^*\,\varphi(\ell^{M})\,(M-R')`,
      ),
      paragraph([
        "となり、第 2 項が ",
        math(String.raw`M\ell^{M}`),
        " 項を生んでその係数は ",
        math(String.raw`j^*(P)\,(1-\ell^{-1})`),
        " である（",
        math(String.raw`v<R'-1`),
        " の有限個の層と最内球は ",
        math(String.raw`\ell^{M}`),
        " の定数倍と定数しか出さない）。合算すると ",
        math(String.raw`\Theta_{M}`),
        " の ",
        math(String.raw`M\ell^{M}`),
        " の係数は ",
        math(String.raw`\frac{\ell-1}{\ell}\sum_{P\in S_\infty}j^*(P)`),
        " であり、",
        math(String.raw`\sum_{M=1}^{n}M\ell^{M}`),
        " の ",
        math(String.raw`n\ell^{n}`),
        " 係数が ",
        math(String.raw`\frac{\ell}{\ell-1}`),
        " なので、両者を掛けて ",
        math(String.raw`b=\sum_{P\in S_\infty}j^*(P)`),
        " を得る。",
        math(String.raw`S_\infty=\emptyset`),
        " なら ",
        math(String.raw`b=0`),
        " で前半と整合する。",
      ]),
      paragraph([
        "(J5) の証明。 この族は ",
        ref("paper_prop_G_infty"),
        " (G′3) の ",
        math(String.raw`(p,q)=(\ell-1,1)`),
        " の場合で、",
        math(String.raw`\mu=0`),
        "、",
        math(String.raw`p'=\ell-1`),
        "、",
        math(String.raw`q'=1`),
        "、",
        math(String.raw`\ell\mid p'+q'`),
        " かつ ",
        math(String.raw`v_\ell(p'+q')=1`),
        " なので ",
        math(String.raw`\Lambda=2`),
        " であり、同命題の閉形式がそのまま主張の式を与える。以下は (J4) の ",
        math(String.raw`b=\sum j^*`),
        " という別の道具から独立に同じ式へ到達する経路であり、両者の一致が相互検証になる。",
      ]),
      paragraph([
        math(String.raw`D=(\ell-1)(2-z-z^{-1})+(2-w-w^{-1})`),
        " は係数の gcd が ",
        math(String.raw`1`),
        " なので ",
        math(String.raw`\mu=0`),
        "、",
        math(String.raw`E=D`),
        "、1 頂点なので ",
        math(String.raw`v_\ell(\kappa(X))=0`),
        " である。",
        math(String.raw`\bmod\ \ell`),
        " で ",
        math(String.raw`-(\ell-1)\equiv1`),
        " より ",
        math(String.raw`\bar{\tilde E}=w(z-1)^2-z(w-1)^2`),
        "、したがって ",
        math(String.raw`H=T^2-S^2`),
        "、",
        math(String.raw`k=2`),
        "、",
        math(String.raw`z_H=2`),
        " である。",
        math(String.raw`s:=(1+x)^{a}-1`),
        "、",
        math(String.raw`t:=(1+x)^{b}-1`),
        " と置くと",
      ]),
      displayMath(
        String.raw`\bar E\bigl((1+x)^{a},(1+x)^{b}\bigr)=\frac{s^2}{1+s}-\frac{t^2}{1+t}
        =\frac{(s-t)\bigl(s+t+st\bigr)}{(1+s)(1+t)}`,
      ),
      paragraph([
        "であり、これが ",
        math(String.raw`0`),
        " になるのは ",
        math(String.raw`(1+x)^{a}=(1+x)^{b}`),
        " か ",
        math(String.raw`(1+x)^{a+b}=1`),
        " のときだけである。",
        math(String.raw`\mathbb{F}_\ell[[x]]`),
        " では ",
        math(String.raw`(1+x)^{c}=1\iff c=0`),
        "（",
        math(String.raw`c\in\mathbb{Z}_\ell`),
        "）なので ",
        math(String.raw`S_\infty=\{(1{:}1),(1{:}-1)\}`),
        " である。",
        math(String.raw`\ell`),
        " が奇なら ",
        math(String.raw`1\not\equiv-1`),
        " なのでこの 2 点は異なる ",
        math(String.raw`\bmod\ \ell`),
        " 方向に属し、",
        math(String.raw`r_0=1`),
        " で仮定 (N) の球の分離が満たされる。",
      ]),
      paragraph([
        math(String.raw`D_0=\bar{\tilde E}`),
        "、",
        math(String.raw`D_1=w(z-1)^2-2zw(w-1)`),
        "、",
        math(String.raw`D_2=-zw^2`),
        "、",
        math(String.raw`D_j=0\ (j\ge3)`),
        " なので、",
        math(String.raw`P=(1{:}1)`),
        " を基点にすると ",
        math(String.raw`\psi_0=0`),
        "、",
        math(String.raw`e_1=1`),
        "（",
        math(String.raw`\ell`),
        " 奇より ",
        math(String.raw`-2\neq0`),
        "）、",
        math(String.raw`e_2=0`),
        " で ",
        math(String.raw`j^*=1`),
        "、",
        math(String.raw`\Lambda(r)=\min(1+\ell^{r},2\ell^{r})=1+\ell^{r}`),
        " は最小点が一意である。",
        math(String.raw`E(z,w)=E(z,w^{-1})`),
        " より ",
        math(String.raw`P=(1{:}-1)`),
        " でも同じ値になる。非退化方向（",
        math(String.raw`\ell-1`),
        " 本）では ",
        math(String.raw`e_0=2\le\ell`),
        " なので (J2) の判定条件によりファイバー全体で ",
        math(String.raw`\theta\equiv2`),
        " である。",
      ]),
      paragraph([
        math(String.raw`\Phi_{(1,1)}=-\ell(1+x)x^2`),
        " なので ",
        math(String.raw`A_2=A_3=-\ell`),
        "、他は ",
        math(String.raw`0`),
        " で、(J3) の最小値は ",
        math(String.raw`m=2`),
        " で一意に ",
        math(String.raw`\hat\theta_{M}=\varphi(\ell^{M})+2`),
        " を与える。退化方向のファイバーの点（",
        math(String.raw`v\le M-2`),
        "）は ",
        math(String.raw`\theta=1+\ell^{\,v+1}\le1+\ell^{M-1}`),
        " で ",
        math(String.raw`\theta-2<\varphi(\ell^{M})`),
        "（",
        math(String.raw`\ell\ge3`),
        "）なので ",
        math(String.raw`\hat\theta=\theta`),
        " である。したがって",
      ]),
      displayMath(
        String.raw`\Theta_{M}=2(\ell-1)\ell^{M-1}+2\Bigl[\ell^{M-1}+1+M\,\varphi(\ell^{M})\Bigr]
        =2\ell^{M}+2+2M\,\varphi(\ell^{M})`,
      ),
      paragraph([
        "であり（非退化方向 ",
        math(String.raw`\ell-1`),
        " 本が各ファイバー ",
        math(String.raw`\ell^{M-1}`),
        " 点で値 ",
        math(String.raw`2`),
        "、退化方向 2 本が各 ",
        math(String.raw`\ell^{M-1}+1+M\varphi(\ell^{M})`),
        "）、",
        math(String.raw`\sum_{M=1}^{n}\ell^{M}`),
        " と ",
        math(String.raw`\sum_{M=1}^{n}M\ell^{M}`),
        " を入れると ",
        math(String.raw`\Sigma_n=2n\ell^{n}+2\ell^{n}-2+2n`),
        "、これに ",
        math(String.raw`-2n`),
        " を足して主張の式を得る。",
        math(String.raw`n=0`),
        " では ",
        math(String.raw`0`),
        " となり底グラフと合う。",
      ]),
      paragraph([
        "(J6) の証明。 まず指数の一次独立性を示す: 相異なる ",
        math(String.raw`\gamma_1,\dots,\gamma_k\in\mathbb{Z}_\ell`),
        " について ",
        math(String.raw`\sum_ia_i(1+x)^{\gamma_i}=0`),
        "（",
        math(String.raw`a_i\in\mathbb{F}_\ell`),
        "）とすると、",
        math(String.raw`L`),
        " を十分大きく取れば ",
        math(String.raw`n_i:=\gamma_i\bmod\ell^{L}\in\{0,\dots,\ell^{L}-1\}`),
        " も相異なり、(J1) より ",
        math(String.raw`(1+x)^{\gamma_i}\equiv(1+x)^{n_i}\pmod{x^{\ell^{L}}}`),
        " である。左辺は次数 ",
        math(String.raw`\max_in_i<\ell^{L}`),
        " の多項式なので恒等的に ",
        math(String.raw`0`),
        " であり、",
        math(String.raw`(1+x)^{n_i}`),
        " たちの次数が相異なることから最大の項の係数 ",
        math(String.raw`a_i`),
        " が ",
        math(String.raw`0`),
        "、以下同様に全て ",
        math(String.raw`0`),
        " である。",
      ]),
      paragraph([
        "そこで ",
        math(String.raw`\overline{\Phi_{(a,b)}}=\sum_{(p,q)\in S}\bar c_{pq}(1+x)^{pa+qb}`),
        " を指数 ",
        math(String.raw`\gamma=pa+qb`),
        " の値ごとにまとめると、一次独立性より和が ",
        math(String.raw`0`),
        " であることと各類の係数和が ",
        math(String.raw`0`),
        " であることは同値であり、主張の判定条件を得る。",
        math(String.raw`S\neq\emptyset`),
        " なので少なくとも 1 つの類は空でなく、1 元だけの類はその係数 ",
        math(String.raw`\bar c_{pq}\neq0`),
        " がそのまま係数和になって条件を破る。よってすべての類が 2 元以上であり、とくに ",
        math(String.raw`\Delta p\,a+\Delta q\,b=0`),
        " なる整数ベクトル ",
        math(String.raw`(\Delta p,\Delta q)\neq(0,0)`),
        " が存在する。",
        math(String.raw`(a,b)`),
        " は原始的なので、この 1 次方程式の ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " での解は ",
        math(String.raw`(a{:}b)=(\Delta q{:}-\Delta p)`),
        " ただ 1 点であり、これは整数ベクトルの定める有理点である。したがって ",
        math(String.raw`S_\infty`),
        " は高々 ",
        math(String.raw`\binom{|S|}{2}`),
        " 点の有限集合で、候補は ",
        math(String.raw`D`),
        " の係数からの有限計算で尽きる。",
      ]),
    ],
  },
]);
