/**
 * 論文本体 第 10 章: θ = ∞ の点集合 S_∞ の判定手続きと、n ℓ^n の係数の閉じた式（命題 K）。
 *
 * 命題 J (J6) は S_∞ の**候補**を有限個の有理点へ絞ったが、各候補で θ = ∞ かどうかの
 * **判定**は族についてしか完成していなかった（同命題の「限界」の 2 番目）。本章はそれを
 * 一般の塔について閉じ、その帰結として n ℓ^n の係数 b を bar tilde E の二項式因子の
 * 重複度として書く。根拠レポートは outputs/reports/cycle20_T3_s_infinity_decision.md。
 *
 * 本章の主張はすべて Z・F_ℓ・Q(ζ_{ℓ^M}) の中で閉じる（ℝ を使わない）。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_100_heading_s_infinity_decision",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/009_s_infinity_decision.ts", ordinal: 1 },
    title: { text: "θ = ∞ の判定手続きと、n ℓ^n の係数 = 二項式因子の重複度" },
    labels: [],
  },
  {
    id: "paper_101_theorem_s_infinity_decision",
    kind: "theorem",
    origin: { path: "structured-latex/content/009_s_infinity_decision.ts", ordinal: 2 },
    title: { text: "命題 K — S_∞ の判定手続きと、n ℓ^n の係数の閉じた式" },
    labels: ["paper_prop_K"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle20_T3_s_infinity"],
    statement: [
      paragraph([
        ref("paper_prop_J"),
        " の設定（",
        math(String.raw`\tilde E=\sum c_{pq}z^pw^q`),
        "、",
        math(String.raw`\bar{\tilde E}`),
        " はその ",
        math(String.raw`\bmod\ \ell`),
        " 還元、",
        math(String.raw`S=\mathrm{supp}(\bar{\tilde E})`),
        "、",
        math(String.raw`\chi^{(p,q)}=z^pw^q`),
        "、",
        math(String.raw`S_\infty=\{P\in\mathbb{P}^1(\mathbb{Z}_\ell):\theta(P)=\infty\}`),
        "）で、",
        math(String.raw`u=(a,b)\in\mathbb{Z}^2`),
        " を原始ベクトル、",
        math(String.raw`u^\perp=(b,-a)`),
        " とする。",
      ]),
      paragraph([
        "**(K1 対応)** 原始整数ベクトルの ",
        math(String.raw`\pm`),
        " 同一視類から ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " への写像 ",
        math(String.raw`\iota([u])=(a{:}b)`),
        " は単射で、像は ",
        math(String.raw`\mathbb{P}^1(\mathbb{Q})`),
        " である。さらに ",
        math(String.raw`\iota`),
        " は ",
        ref("paper_prop_G_infty"),
        " の**例外直線の方向**の集合を ",
        math(String.raw`S_\infty`),
        " へ全単射で移す。とくに ",
        math(String.raw`|S_\infty|`),
        " は例外直線の本数に等しい。",
        "**すなわち、",
        math(String.raw`\mathbb{Z}^2`),
        " の直線として見る立場と ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " の点として見る立場は同一の有限集合を指している。**",
      ]),
      paragraph([
        "**(K2 判定条件の同一性)** 原始 ",
        math(String.raw`u`),
        " について次は同値である: (i) ",
        math(String.raw`\theta(u)=\infty`),
        "、(ii) ",
        math(String.raw`\lambda(u)\ge1`),
        "、(iii) ",
        math(String.raw`(\chi^{u^\perp}-1)\mid\bar{\tilde E}`),
        "、(iv) すべての ",
        math(String.raw`\gamma\in\mathbb{Z}`),
        " で",
      ]),
      displayMath(String.raw`\sum_{\substack{(p,q)\in S\\ pa+qb=\gamma}}\bar c_{pq}=0 .`),
      paragraph([
        ref("paper_prop_G_infty"),
        " が使う判定 (iii) と ",
        ref("paper_prop_J"),
        " が使う判定 (iv) は同じ判定である。",
      ]),
      paragraph([
        "**(K3 判定手続き)** したがって次は ",
        math(String.raw`D`),
        " の係数だけからの**有限手続き**であり、",
        math(String.raw`S_\infty`),
        " を完全に決める（塔の値も円分体も使わない）。(1) ",
        math(String.raw`\bar{\tilde E}`),
        " と ",
        math(String.raw`S`),
        " を作る。(2) ",
        math(String.raw`S`),
        " の相異なる 2 点の差 ",
        math(String.raw`(\Delta p,\Delta q)`),
        " から候補 ",
        math(String.raw`u=\mathrm{prim}(\Delta q,-\Delta p)`),
        " を列挙する（高々 ",
        math(String.raw`\binom{|S|}{2}`),
        " 個）。(3) 各候補で (K2) の (iv) を判定する。",
        "計算量は ",
        math(String.raw`\mathbb{F}_\ell`),
        " 上 ",
        math(String.raw`O(|S|^3)`),
        " 回の演算である。",
      ]),
      paragraph([
        "**(K4 ",
        math(String.raw`j^*`),
        " は重複度である)** ",
        math(String.raw`\mathbb{F}_\ell[z^{\pm1},w^{\pm1}]`),
        " は UFD で、原始 ",
        math(String.raw`v`),
        " に対し ",
        math(String.raw`\chi^{v}-1`),
        " は素元、相異なる方向のものは非同伴である。よって",
      ]),
      displayMath(
        String.raw`\bar{\tilde E}=c\,\chi^{w_0}\prod_{i=1}^{r}\bigl(\chi^{v_i}-1\bigr)^{m_i}\cdot G_0,
        \qquad (\chi^{v}-1)\nmid G_0\ \ (\forall v\ \text{原始})`,
      ),
      paragraph([
        "が一意に定まる。このとき ",
        math(String.raw`P=\iota([u])\in S_\infty`),
        "、",
        math(String.raw`m_u`),
        " を ",
        math(String.raw`\chi^{u^\perp}-1`),
        " の重複度として",
      ]),
      displayMath(String.raw`e_j=\infty\ \ (j<m_u),\qquad e_{m_u}<\infty,\qquad\text{したがって}\quad j^*(P)=m_u`),
      paragraph([
        "が成り立つ。すなわち ",
        ref("paper_prop_J"),
        " (J4) の ",
        math(String.raw`j^*`),
        "（",
        math(String.raw`\ell`),
        " 進近傍の変形から定まる量）は、",
        math(String.raw`\bar{\tilde E}`),
        " の**因数分解の重複度**という代数的な量に等しい。",
      ]),
      paragraph([
        "**(K5 仮定 (N) の解消)** ",
        math(String.raw`\ell^{r}>e_{m_u}`),
        " ならば ",
        math(String.raw`\Lambda(r)`),
        " の最小点は ",
        math(String.raw`j=m_u`),
        " ただ 1 つである。また相異なる ",
        math(String.raw`P=\iota([u]),P'=\iota([u'])`),
        " が ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{k})`),
        " で同じ点になるのは ",
        math(String.raw`\ell^{k}\mid\det(u,u')`),
        " のときに限る。したがって",
      ]),
      displayMath(
        String.raw`r_0:=1+\max\Bigl(\max_{P\neq P'}v_\ell\bigl(\det(u,u')\bigr),\ \max_{P}\bigl\lfloor\log_\ell e_{m_u}\bigr\rfloor\Bigr)`,
      ),
      paragraph([
        "と置けば ",
        ref("paper_prop_J"),
        " (J4) の仮定のうち「球の分離と ",
        math(String.raw`\mathrm{argmin}`),
        " の一意性」は**自動的に満たされる**。残る仮定は「レベルが十分深いところで ",
        math(String.raw`\hat\theta`),
        " を与える最小点が一意であること」だけになる。",
      ]),
      paragraph([
        "**(K6 ",
        math(String.raw`n\ell^n`),
        " の係数)** その残る仮定の下で、",
      ]),
      displayMath(
        String.raw`b=\sum_{P\in S_\infty}j^*(P)=\sum_{i=1}^{r}m_i
        \quad(=\ \bar{\tilde E}\ \text{の原始二項式部分の次数}),`,
      ),
      paragraph([
        "とくに ",
        math(String.raw`b=0`),
        " と「",
        math(String.raw`\bar{\tilde E}`),
        " が ",
        math(String.raw`\chi^{v}-1`),
        " の形の因子を持たない」と「型 II（",
        math(String.raw`n\ell^n`),
        " 項が出ない）」は同値である。**",
        math(String.raw`b`),
        " は ",
        math(String.raw`D`),
        " の係数からの ",
        math(String.raw`\mathbb{F}_\ell`),
        " 上の有限計算だけで決まる。** ",
        ref("paper_prop_G_infty"),
        " が族について与えた閉形式の ",
        math(String.raw`b=2`),
        " は、その族で二項式部分の次数が 2 であること（因子 2 本 × 重複度 1、または 1 本 × 重複度 2）に対応する。",
      ]),
      paragraph([
        "**(K6) は新しい主張ではない。** ここでの ",
        math(String.raw`b`),
        " は Cuoco–Monsky の ",
        math(String.raw`l_0`),
        " と**定義から一致し**、(K6) の等式は同論文 Theorem 1.7 が与える ",
        math(String.raw`n\ell^n`),
        " の係数そのものである。帰属は下の「限界」の末尾に書いた。",
      ]),
      paragraph([
        "**(K7 a priori 上界)** 格子多角形の格子周長（各辺の格子長の和）を ",
        math(String.raw`\mathrm{per}`),
        " と書くと",
      ]),
      displayMath(String.raw`b\ \le\ \tfrac12\,\mathrm{per}\bigl(\mathrm{Newt}(\bar{\tilde E})\bigr).`),
      paragraph([
        "すなわち ",
        math(String.raw`D`),
        " の Newton 多角形だけから ",
        math(String.raw`n\ell^n`),
        " 係数の上界が出る。等号が成り立つのは ",
        math(String.raw`G_0`),
        " が単項式のとき、すなわち ",
        math(String.raw`\bar{\tilde E}`),
        " が二項式に完全分解するときちょうどである。",
      ]),
      paragraph([
        "**限界（主張の一部として述べる）**",
      ]),
      list([
        [
          "(K6) は ",
          ref("paper_prop_J"),
          " (J4) の残る仮定（",
          math(String.raw`\hat\theta`),
          " を与える最小点の一意性）を引き継ぐ。この仮定は ",
          math(String.raw`\ell=2`),
          " のトーラスで実際に破れており、",
          math(String.raw`\ell=3`),
          " でも破れる塔がある。破れる塔でも ",
          math(String.raw`b`),
          " は当たっているが、**それは数値支持どまりであって証明ではない**。",
        ],
        [
          "(K1)–(K5)・(K7) は仮定を持たない。とくに (K3) の判定手続きは、",
          math(String.raw`\hat\theta`),
          " の振る舞いとは無関係に ",
          math(String.raw`S_\infty`),
          " を完全に決める。",
        ],
        [
          math(String.raw`\ell^n`),
          "・",
          math(String.raw`n`),
          "・定数の各係数（",
          math(String.raw`c,d,e`),
          "）は本命題では決まらない。そこには ",
          math(String.raw`G_0`),
          " が効く。",
        ],
        [
          "本命題は ",
          math(String.raw`d=2`),
          " に限る。",
        ],
        [
          "**新規性は主張しない。とくに (K6) は既出である。** Cuoco–Monsky, *Class numbers in ",
          math(String.raw`\mathbb{Z}_p^d`),
          "-extensions*, Math. Ann. **255** (1981), 235–258 の Definition 1.2 は ",
          math(String.raw`l_0(F)`),
          " を「",
          math(String.raw`F=p^{m_0}F_0`),
          " と書いたときの ",
          math(String.raw`\bar F_0`),
          " の、群の元 ",
          math(String.raw`\sigma`),
          " が ",
          math(String.raw`p`),
          " 冪でない（すなわち原始な）ものについての ",
          math(String.raw`\bar\sigma-1`),
          " 型既約因子の、重複込みの個数」と定義している。本論文の ",
          math(String.raw`\Gamma\cong\mathbb{Z}_\ell^2`),
          " の下で ",
          math(String.raw`\bar\sigma-1`),
          " は原始 ",
          math(String.raw`v`),
          " についての ",
          math(String.raw`\chi^{v}-1`),
          " に対応するから、これは (K4) の ",
          math(String.raw`\sum_{i=1}^{r}m_i`),
          " と同じ量である。したがって (K6) の等式は同論文 Theorem 1.7（",
          math(String.raw`\Sigma_n(F)=(m_0p^n+l_0n+O(1))p^{(d-1)n}`),
          "）が与える ",
          math(String.raw`n\ell^n`),
          " の係数そのものであり、1981 年から知られている。**本論文はこの式に新規性を主張しない。** ",
          "同定理は ",
          ref("paper_prop_D"),
          " が既に引用している。",
        ],
        [
          "**(K2) の同値も既出である。** Monsky, *Some invariants of ",
          math(String.raw`\mathbb{Z}_p^d`),
          "-extensions*, Math. Ann. **255** (1981), 229–233 の Lemma 2.3 は、",
          math(String.raw`d=2`),
          " のとき ",
          math(String.raw`\lambda(G_a)`),
          " が ",
          math(String.raw`(0,1)`),
          " の近傍で非有界であることと ",
          math(String.raw`X_1\mid\bar G`),
          " が同値だと述べている。特殊化 ",
          math(String.raw`z\mapsto(1+T)^{a},\ w\mapsto(1+T)^{b}`),
          " の下で ",
          math(String.raw`\bar{\tilde E}`),
          " は ",
          math(String.raw`\sum_m\bar A_m(a,b)\,T^m`),
          " へ写るので、",
          math(String.raw`\theta(a,b)=\infty`),
          " は ",
          math(String.raw`\bar G_a=0`),
          " に、有限な場合の ",
          math(String.raw`\theta(a,b)`),
          " は ",
          math(String.raw`\lambda(G_a)`),
          " に一致し、",
          math(String.raw`X_1\mid\bar G`),
          " は方向 ",
          math(String.raw`(0{:}1)`),
          " における (K2) の (iii) にあたる。",
          ref("paper_prop_J"),
          " (J1) により ",
          math(String.raw`\theta`),
          " は有限な点で局所定数なので、「近傍で非有界」と「その点で ",
          math(String.raw`\infty`),
          "」は同値である。**原論文本文を取得して確認した。**",
        ],
        [
          "**(K3)・(K4)・(K5)・(K7) は、読んだ範囲には見当たらなかった。** 読んだのは、",
          "Cuoco–Monsky (1981) の Introduction・§1 から §7・References（pp.235–258 の全ページ）、",
          "Monsky *Some invariants* (1981) の全文（pp.229–233）、および Cuoco, Compositio Math. **41** (1980), ",
          "415–437 の Introduction と Theorem 1.1 の周辺である（Cuoco–Monsky が p.248 で ",
          math(String.raw`m_0`),
          "・",
          math(String.raw`l_0`),
          " の詳細について指す先を辿った）。いずれも ",
          math(String.raw`l_0`),
          " を ",
          math(String.raw`\bar F_0`),
          " の素因子分解の言葉で**定義**するだけで、係数からそれを決める有限手続き（(K3)）も、",
          "点ごとの ",
          math(String.raw`j^*`),
          " の同定（(K4)）も述べていない。**読んでいないのは Cuoco の学位論文（Brandeis, 1979）であり、" +
            "そこに無いとは言えない。** なお (K3) は ",
          ref("paper_prop_F"),
          " を ",
          math(String.raw`d=2`),
          " へ特殊化したものであり、同命題も新規性を主張していない。",
        ],
        [
          "群環 ",
          math(String.raw`\mathbb{F}_\ell[\mathbb{Z}^2]`),
          " の増大イデアル ",
          math(String.raw`(\chi^{v}-1)`),
          " による分解そのものは標準的な道具である。",
        ],
      ]),
    ],
  },
]);
