/**
 * 論文本体 第 10 章: θ = ∞ の点集合 S_∞ の判定手続きと、n ℓ^n の係数の閉じた式（命題 K）。
 *
 * 命題 J (J6) は S_∞ の**候補**を有限個の有理点へ絞ったが、各候補で θ = ∞ かどうかの
 * **判定**は族についてしか完成していなかった（同命題の「限界」の 2 番目）。本章はそれを
 * 一般の塔について閉じ、その帰結として n ℓ^n の係数 b を bar tilde E の二項式因子の
 * 重複度として書く。根拠レポートは outputs/reports/cycle20_T3_s_infinity_decision.md。
 *
 * 本章の主張はすべて Z・F_ℓ・Q(ζ_{ℓ^M}) の中で閉じる（ℝ を使わない）。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_100_heading_s_infinity_decision",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/009_s_infinity_decision.ts", ordinal: 1 },
    title: { text: "θ = ∞ の判定手続きと、n ℓ^n の係数 = 二項式因子の重複度" },
    labels: [],
  },
  {
    id: "paper_101_theorem_s_infinity_decision",
    kind: "theorem",
    origin: { path: "structured-latex/content/009_s_infinity_decision.ts", ordinal: 2 },
    title: { text: "命題 K — S_∞ の判定手続きと、n ℓ^n の係数の閉じた式" },
    labels: ["paper_prop_K"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle20_T3_s_infinity"],
    lean: [
      "IntegrableLattice.SInfinity.BucketVanish",
      "IntegrableLattice.PropKW2Converse.dvd_of_psi_eq_zero",
      "IntegrableLattice.PropKW2Converse.psi_eq_zero_iff_dvd",
      "IntegrableLattice.LatticeSegmentLength.latticeLength_eq_zero_iff",
      "IntegrableLattice.LatticeSegmentLength.latticeLength_of_smul",
      "IntegrableLattice.LatticeSegmentLength.latticeLength_add_of_parallel",
      "IntegrableLattice.k5_argmin_unique_above",
      "IntegrableLattice.r0_add_one_comm",
      "IntegrableLattice.r0_empty_case",
      "IntegrableLattice.lambda_u_at_zero",
      "IntegrableLattice.lambda_u_eq_succ_log",
    ],
    statement: [
      paragraph([
        ref("paper_prop_J"),
        " の設定（",
        math(String.raw`\tilde E=\sum c_{pq}z^pw^q`),
        "、",
        math(String.raw`\bar{\tilde E}`),
        " はその ",
        math(String.raw`\bmod\ \ell`),
        " 還元、",
        math(String.raw`S=\mathrm{supp}(\bar{\tilde E})`),
        "、",
        math(String.raw`\chi^{(p,q)}=z^pw^q`),
        "、",
        math(String.raw`S_\infty=\{P\in\mathbb{P}^1(\mathbb{Z}_\ell):\theta(P)=\infty\}`),
        "）で、",
        math(String.raw`u=(a,b)\in\mathbb{Z}^2`),
        " を原始ベクトル、",
        math(String.raw`u^\perp=(b,-a)`),
        " とする。",
      ]),
      paragraph([
        "(K1 対応) 原始整数ベクトルの ",
        math(String.raw`\pm`),
        " 同一視類から ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " への写像 ",
        math(String.raw`\iota([u])=(a{:}b)`),
        " は単射で、像は ",
        math(String.raw`\mathbb{P}^1(\mathbb{Q})`),
        " である。さらに ",
        math(String.raw`\iota`),
        " は ",
        ref("paper_prop_G_infty"),
        " の例外直線の方向の集合を ",
        math(String.raw`S_\infty`),
        " へ全単射で移す。とくに ",
        math(String.raw`|S_\infty|`),
        " は例外直線の本数に等しい。",
        "すなわち、",
        math(String.raw`\mathbb{Z}^2`),
        " の直線として見る立場と ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " の点として見る立場は同一の有限集合を指している。",
      ]),
      paragraph([
        "(K2 判定条件の同一性) 原始 ",
        math(String.raw`u`),
        " について次は同値である: (i) ",
        math(String.raw`\theta(u)=\infty`),
        "、(ii) ",
        math(String.raw`\lambda(u)\ge1`),
        "、(iii) ",
        math(String.raw`(\chi^{u^\perp}-1)\mid\bar{\tilde E}`),
        "、(iv) すべての ",
        math(String.raw`\gamma\in\mathbb{Z}`),
        " で",
      ]),
      displayMath(String.raw`\sum_{\substack{(p,q)\in S\\ pa+qb=\gamma}}\bar c_{pq}=0 .`),
      paragraph([
        ref("paper_prop_G_infty"),
        " が使う判定 (iii) と ",
        ref("paper_prop_J"),
        " が使う判定 (iv) は同じ判定である。",
      ]),
      paragraph([
        "(K3 判定手続き) したがって次は ",
        math(String.raw`D`),
        " の係数だけからの有限手続きであり、",
        math(String.raw`S_\infty`),
        " を完全に決める（塔の値も円分体も使わない）。(1) ",
        math(String.raw`\bar{\tilde E}`),
        " と ",
        math(String.raw`S`),
        " を作る。(2) ",
        math(String.raw`S`),
        " の相異なる 2 点の差 ",
        math(String.raw`(\Delta p,\Delta q)`),
        " から候補 ",
        math(String.raw`u=\mathrm{prim}(\Delta q,-\Delta p)`),
        " を列挙する（高々 ",
        math(String.raw`\binom{|S|}{2}`),
        " 個）。(3) 各候補で (K2) の (iv) を判定する。",
        "計算量は ",
        math(String.raw`\mathbb{F}_\ell`),
        " 上 ",
        math(String.raw`O(|S|^3)`),
        " 回の演算である。",
      ]),
      paragraph([
        "(K4 ",
        math(String.raw`j^*`),
        " は重複度である) ",
        math(String.raw`\mathbb{F}_\ell[z^{\pm1},w^{\pm1}]`),
        " は UFD で、原始 ",
        math(String.raw`v`),
        " に対し ",
        math(String.raw`\chi^{v}-1`),
        " は素元、相異なる方向のものは非同伴である。よって",
      ]),
      displayMath(
        String.raw`\bar{\tilde E}=c\,\chi^{w_0}\prod_{i=1}^{r}\bigl(\chi^{v_i}-1\bigr)^{m_i}\cdot G_0,
        \qquad (\chi^{v}-1)\nmid G_0\ \ (\forall v\ \text{原始})`,
      ),
      paragraph([
        "が一意に定まる。このとき ",
        math(String.raw`P=\iota([u])\in S_\infty`),
        "、",
        math(String.raw`m_u`),
        " を ",
        math(String.raw`\chi^{u^\perp}-1`),
        " の重複度として",
      ]),
      displayMath(String.raw`e_j=\infty\ \ (j<m_u),\qquad e_{m_u}<\infty,\qquad\text{したがって}\quad j^*(P)=m_u`),
      paragraph([
        "が成り立つ。すなわち ",
        ref("paper_prop_J"),
        " (J4) の ",
        math(String.raw`j^*`),
        "（",
        math(String.raw`\ell`),
        " 進近傍の変形から定まる量）は、",
        math(String.raw`\bar{\tilde E}`),
        " の因数分解の重複度という代数的な量に等しい。",
      ]),
      paragraph([
        "(K5 仮定 (N) の解消) ",
        math(String.raw`\ell^{r}>e_{m_u}`),
        " ならば ",
        math(String.raw`\mathcal{E}(r)`),
        " の最小点は ",
        math(String.raw`j=m_u`),
        " ただ 1 つである。また相異なる ",
        math(String.raw`P=\iota([u]),P'=\iota([u'])`),
        " が ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{k})`),
        " で同じ点になるのは ",
        math(String.raw`\ell^{k}\mid\det(u,u')`),
        " のときに限る。ここで各 ",
        math(String.raw`P=\iota([u])\in S_\infty`),
        " に対し ",
        math(String.raw`\lambda_u`),
        " を ",
        math(String.raw`\ell^{\lambda}>e_{m_u}`),
        " を満たす最小の自然数 ",
        math(String.raw`\lambda`),
        " とする（",
        math(String.raw`\ell`),
        " の冪を ",
        math(String.raw`\ell^{0},\ell^{1},\ell^{2},\dots`),
        " と順に ",
        math(String.raw`e_{m_u}\in\mathbb{N}`),
        " と比べれば有限回で決まるので、実対数を経由しない）。したがって",
      ]),
      displayMath(
        String.raw`r_0:=\max\Bigl(1+\max_{P\neq P'}v_\ell\bigl(\det(u,u')\bigr),\ \max_{P}\lambda_u\Bigr)`,
      ),
      paragraph([
        "と置く。規約（書き落とせない）: 内側の 2 つの ",
        math(String.raw`\max`),
        " はどちらも ",
        math(String.raw`S_\infty`),
        " 上（前者は相異なる 2 点の対の上）を走るので空になりうる。空のときは ",
        math(String.raw`\max\emptyset:=0`),
        " と読む。",
        math(String.raw`S_\infty=\emptyset`),
        " は下の (K6) が ",
        math(String.raw`b=0`),
        "（型 II）として名指ししている場合そのものであり、",
        math(String.raw`|S_\infty|=1`),
        " のときは対が無いので前者だけが空になる。どちらの場合も分離すべき球や比べるべき最小点が存在せず、",
        math(String.raw`r_0`),
        " が課すべき条件が空なので、この読みで正しい。",
      ]),
      paragraph([
        "こう置けば ",
        ref("paper_prop_J"),
        " (J4) の仮定のうち「球の分離と ",
        math(String.raw`\mathrm{argmin}`),
        " の一意性」は自動的に満たされる。残る仮定は「レベルが十分深いところで ",
        math(String.raw`\hat\theta`),
        " を与える最小点が一意であること」だけになる。",
      ]),
      paragraph([
        "(K6 ",
        math(String.raw`n\ell^n`),
        " の係数) その残る仮定の下で、",
      ]),
      displayMath(
        String.raw`b=\sum_{P\in S_\infty}j^*(P)=\sum_{i=1}^{r}m_i
        \quad(=\ \bar{\tilde E}\ \text{の原始二項式部分の次数}),`,
      ),
      paragraph([
        "とくに ",
        math(String.raw`b=0`),
        " と「",
        math(String.raw`\bar{\tilde E}`),
        " が ",
        math(String.raw`\chi^{v}-1`),
        " の形の因子を持たない」と「型 II（",
        math(String.raw`n\ell^n`),
        " 項が出ない）」は同値である。",
        math(String.raw`b`),
        " は ",
        math(String.raw`D`),
        " の係数からの ",
        math(String.raw`\mathbb{F}_\ell`),
        " 上の有限計算だけで決まる。 ",
        ref("paper_prop_G_infty"),
        " が族について与えた閉形式の ",
        math(String.raw`b=2`),
        " は、その族で二項式部分の次数が 2 であること（因子 2 本 × 重複度 1、または 1 本 × 重複度 2）に対応する。",
      ]),
      paragraph([
        "(K6) は新しい主張ではない。 ここでの ",
        math(String.raw`b`),
        " は Cuoco–Monsky の ",
        math(String.raw`l_0`),
        " と定義から一致し、(K6) の等式は同論文 Theorem 1.7 が与える ",
        math(String.raw`n\ell^n`),
        " の係数そのものである。帰属は下の「限界」の末尾に書いた。",
      ]),
      paragraph([
        "(K7 a priori 上界) 格子多角形の格子周長（各辺の格子長の和）を ",
        math(String.raw`\mathrm{per}`),
        " と書くと",
      ]),
      displayMath(String.raw`b\ \le\ \tfrac12\,\mathrm{per}\bigl(\mathrm{Newt}(\bar{\tilde E})\bigr).`),
      paragraph([
        "すなわち ",
        math(String.raw`D`),
        " の Newton 多角形だけから ",
        math(String.raw`n\ell^n`),
        " 係数の上界が出る。等号が成り立つのは ",
        math(String.raw`G_0`),
        " が単項式のとき、すなわち ",
        math(String.raw`\bar{\tilde E}`),
        " が二項式に完全分解するときちょうどである。",
      ]),
      paragraph([
        "本命題に残る限界は次のとおりである。",
      ]),
      list([
        [
          "(K6) は ",
          ref("paper_prop_J"),
          " (J4) の残る仮定（",
          math(String.raw`\hat\theta`),
          " を与える最小点の一意性）を引き継ぐ。この仮定は ",
          math(String.raw`\ell=2`),
          " のトーラスで実際に破れており、",
          math(String.raw`\ell=3`),
          " でも破れる塔がある。破れる塔でも ",
          math(String.raw`b`),
          " は当たっているが、それは数値支持どまりであって証明ではない。",
        ],
        [
          "(K1)–(K5)・(K7) は仮定を持たない。とくに (K3) の判定手続きは、",
          math(String.raw`\hat\theta`),
          " の振る舞いとは無関係に ",
          math(String.raw`S_\infty`),
          " を完全に決める。",
        ],
        [
          math(String.raw`\ell^n`),
          "・",
          math(String.raw`n`),
          "・定数の各係数（",
          math(String.raw`c,d,e`),
          "）は本命題では決まらない。そこには ",
          math(String.raw`G_0`),
          " が効く。",
        ],
        [
          "本命題は ",
          math(String.raw`d=2`),
          " に限る。",
        ],
        [
          "新規性は主張しない。とくに (K6) は既出である。 Cuoco–Monsky, *Class numbers in ",
          math(String.raw`\mathbb{Z}_p^d`),
          "-extensions*, Math. Ann. 255 (1981), 235–258 の Definition 1.2 は ",
          math(String.raw`l_0(F)`),
          " を「",
          math(String.raw`F=p^{m_0}F_0`),
          " と書いたときの ",
          math(String.raw`\bar F_0`),
          " の、群の元 ",
          math(String.raw`\sigma`),
          " が ",
          math(String.raw`p`),
          " 冪でない（すなわち原始な）ものについての ",
          math(String.raw`\bar\sigma-1`),
          " 型既約因子の、重複込みの個数」と定義している。本論文の ",
          math(String.raw`\Gamma\cong\mathbb{Z}_\ell^2`),
          " の下で ",
          math(String.raw`\bar\sigma-1`),
          " は原始 ",
          math(String.raw`v`),
          " についての ",
          math(String.raw`\chi^{v}-1`),
          " に対応するから、これは (K4) の ",
          math(String.raw`\sum_{i=1}^{r}m_i`),
          " と同じ量である。したがって (K6) の等式は同論文 Theorem 1.7（",
          math(String.raw`\Sigma_n(F)=(m_0p^n+l_0n+O(1))p^{(d-1)n}`),
          "）が与える ",
          math(String.raw`n\ell^n`),
          " の係数そのものであり、1981 年から知られている。本論文はこの式に新規性を主張しない。 ",
          "同定理は ",
          ref("paper_prop_D"),
          " が既に引用している。",
        ],
        [
          "(K2) の同値も既出である。 Monsky, *Some invariants of ",
          math(String.raw`\mathbb{Z}_p^d`),
          "-extensions*, Math. Ann. 255 (1981), 229–233 の Lemma 2.3 は、",
          math(String.raw`d=2`),
          " のとき ",
          math(String.raw`\lambda(G_a)`),
          " が ",
          math(String.raw`(0,1)`),
          " の近傍で非有界であることと ",
          math(String.raw`X_1\mid\bar G`),
          " が同値だと述べている。特殊化 ",
          math(String.raw`z\mapsto(1+T)^{a},\ w\mapsto(1+T)^{b}`),
          " の下で ",
          math(String.raw`\bar{\tilde E}`),
          " は ",
          math(String.raw`\sum_m\bar A_m(a,b)\,T^m`),
          " へ写るので、",
          math(String.raw`\theta(a,b)=\infty`),
          " は ",
          math(String.raw`\bar G_a=0`),
          " に、有限な場合の ",
          math(String.raw`\theta(a,b)`),
          " は ",
          math(String.raw`\lambda(G_a)`),
          " に一致し、",
          math(String.raw`X_1\mid\bar G`),
          " は方向 ",
          math(String.raw`(0{:}1)`),
          " における (K2) の (iii) にあたる。",
          ref("paper_prop_J"),
          " (J1) により ",
          math(String.raw`\theta`),
          " は有限な点で局所定数なので、「近傍で非有界」と「その点で ",
          math(String.raw`\infty`),
          "」は同値である。原論文本文を取得して確認した。",
        ],
        [
          "(K3)・(K4)・(K5)・(K7) は、読んだ範囲には見当たらなかった。 読んだのは、",
          "Cuoco–Monsky (1981) の Introduction・§1 から §7・References（pp.235–258 の全ページ）、",
          "Monsky *Some invariants* (1981) の全文（pp.229–233）、および Cuoco, Compositio Math. 41 (1980), ",
          "415–437 の Introduction と Theorem 1.1 の周辺である（Cuoco–Monsky が p.248 で ",
          math(String.raw`m_0`),
          "・",
          math(String.raw`l_0`),
          " の詳細について指す先を辿った）。いずれも ",
          math(String.raw`l_0`),
          " を ",
          math(String.raw`\bar F_0`),
          " の素因子分解の言葉で定義するだけで、係数からそれを決める有限手続き（(K3)）も、",
          "点ごとの ",
          math(String.raw`j^*`),
          " の同定（(K4)）も述べていない。読んでいないのは Cuoco の学位論文（Brandeis, 1979）であり、" +
            "そこに無いとは言えない。 なお (K3) は ",
          ref("paper_prop_F"),
          " を ",
          math(String.raw`d=2`),
          " へ特殊化したものであり、同命題も新規性を主張していない。",
        ],
        [
          "群環 ",
          math(String.raw`\mathbb{F}_\ell[\mathbb{Z}^2]`),
          " の増大イデアル ",
          math(String.raw`(\chi^{v}-1)`),
          " による分解そのものは標準的な道具である。",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "本文に無い補題へ暗黙に依存しないために、途中で使う事実はすべてその主張をここで述べてから使う。 ",
        "使うのは ",
        math(String.raw`\mathbb{Z}`),
        " の gcd と ",
        math(String.raw`\ell`),
        " 付値、",
        math(String.raw`\mathbb{F}_\ell[z^{\pm1},w^{\pm1}]`),
        " の割り算、",
        math(String.raw`\mathbb{Z}[x]`),
        " の係数の ",
        math(String.raw`\ell`),
        " 付値、",
        math(String.raw`\mathbb{Z}^2`),
        " の整数線型代数だけであり、実数体へは一度も出ない。",
      ]),
      paragraph([
        "(K1) の証明。 ",
        math(String.raw`\iota([u])=\iota([u'])`),
        " とすると ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " の定義より ",
        math(String.raw`u'=cu`),
        " なる ",
        math(String.raw`c\in\mathbb{Z}_\ell^\times`),
        " があり、",
        math(String.raw`u`),
        " の少なくとも一方の成分が ",
        math(String.raw`0`),
        " でないので、その成分の比として ",
        math(String.raw`c\in\mathbb{Q}^\times`),
        " である。",
        math(String.raw`u,u'`),
        " がともに原始整数ベクトルなので ",
        math(String.raw`c`),
        " とその逆数はともに整数、よって ",
        math(String.raw`c=\pm1`),
        " で単射である。像については、",
        math(String.raw`(a{:}b)`),
        "（",
        math(String.raw`a,b\in\mathbb{Q}`),
        " 非同時 ",
        math(String.raw`0`),
        "）の分母を払い gcd で割れば原始整数ベクトルになるので、像はちょうど ",
        math(String.raw`\mathbb{P}^1(\mathbb{Q})`),
        " である。",
      ]),
      paragraph([
        ref("paper_prop_J"),
        " の (J1) が ",
        math(String.raw`\theta`),
        " を ",
        math(String.raw`\mathbb{Z}_\ell^2`),
        " 上へ延長したものは、",
        math(String.raw`\mathbb{Z}^2`),
        " の点では定義式そのもの（",
        math(String.raw`\mathrm{ord}_{x=0}\overline{\Phi_{(a,b)}}`),
        "）に一致するから、原始 ",
        math(String.raw`u\in\mathbb{Z}^2`),
        " について ",
        math(String.raw`\iota([u])\in S_\infty\iff\theta(u)=\infty`),
        " である。他方 ",
        ref("paper_prop_J"),
        " の (J6) より ",
        math(String.raw`S_\infty\subseteq\mathbb{P}^1(\mathbb{Q})`),
        " なので、",
        math(String.raw`S_\infty`),
        " の各点は原始整数ベクトルによる ",
        math(String.raw`\iota([u])`),
        " の形に一意に書け、その ",
        math(String.raw`u`),
        " は ",
        ref("paper_prop_G_infty"),
        " の例外直線の方向である。この有理性が無ければ、",
        math(String.raw`\mathbb{Z}^2`),
        " をすべて調べても ",
        math(String.raw`\mathbb{Z}_\ell\setminus\mathbb{Q}`),
        " 方向の取りこぼしを排除できない。判定手続きの完全性はここに依存している。",
      ]),
      paragraph([
        "(K2) の証明。 (i) ",
        math(String.raw`\iff`),
        " (ii) と (ii) ",
        math(String.raw`\iff`),
        " (iii) は ",
        ref("paper_prop_G_infty"),
        " の証明の補題 B・補題 C である。(iii) ",
        math(String.raw`\iff`),
        " (iv) を示す。同証明の ",
        math(String.raw`\bar\psi_u`),
        "（",
        math(String.raw`z\mapsto y^a,\ w\mapsto y^b`),
        "）について",
      ]),
      displayMath(
        String.raw`\bar\psi_u\bigl(\bar{\tilde E}\bigr)=\sum_{(p,q)\in S}\bar c_{pq}\,y^{\,pa+qb}
        =\sum_{\gamma\in\mathbb{Z}}\Bigl(\sum_{\substack{(p,q)\in S\\ pa+qb=\gamma}}\bar c_{pq}\Bigr)y^{\gamma}`,
      ),
      paragraph([
        "であり、",
        math(String.raw`\{y^{\gamma}\}`),
        " は ",
        math(String.raw`\mathbb{F}_\ell[y^{\pm1}]`),
        " の基底だから ",
        math(String.raw`\bar\psi_u(\bar{\tilde E})=0`),
        " と (iv) は同値である。他方 ",
        math(String.raw`\ker\bar\psi_u=(\chi^{u^\perp}-1)`),
        " なので ",
        math(String.raw`\bar\psi_u(\bar{\tilde E})=0`),
        " と (iii) も同値である。なお ",
        math(String.raw`u`),
        " が整数ベクトルなら ",
        math(String.raw`pa+qb\in\mathbb{Z}`),
        " なので、",
        ref("paper_prop_J"),
        " の (J6) が ",
        math(String.raw`\gamma\in\mathbb{Z}_\ell`),
        " を走らせているところを ",
        math(String.raw`\gamma\in\mathbb{Z}`),
        " に制限してよい。",
      ]),
      paragraph([
        "(K3) の証明。 完全性は ",
        ref("paper_prop_J"),
        " の (J6) の候補集合の包含と (K1) の対応（",
        math(String.raw`\mathbb{Z}_\ell\setminus\mathbb{Q}`),
        " 方向の取りこぼしが無いこと）による。健全性は (K2) による。停止性は候補が有限個で各判定が ",
        math(String.raw`S`),
        " の上の有限和であることによる。計算量は候補が ",
        math(String.raw`O(|S|^2)`),
        " 個、各判定が ",
        math(String.raw`O(|S|)`),
        " なので ",
        math(String.raw`O(|S|^3)`),
        " である。",
      ]),
      paragraph([
        "(K4) の証明。まず分解の一意性。 ",
        math(String.raw`\mathbb{F}_\ell[z^{\pm1},w^{\pm1}]`),
        " は UFD であり、原始 ",
        math(String.raw`v`),
        " に対し剰余環が ",
        math(String.raw`\mathbb{F}_\ell[y^{\pm1}]`),
        "（整域）なので ",
        math(String.raw`\chi^{v}-1`),
        " は素元である。また ",
        math(String.raw`\mathrm{Newt}(\chi^{v}-1)=[0,v]`),
        " なので、方向が違えば Newton 多面体が違い、非同伴である。したがって主張の分解が ",
        math(String.raw`v_i`),
        " を ",
        math(String.raw`\pm`),
        " 同一視して一意に定まる。",
      ]),
      paragraph([
        "次に ",
        math(String.raw`j^*=m_u`),
        " を示す。 ",
        math(String.raw`\det(u,n)=1`),
        " なる ",
        math(String.raw`n\in\mathbb{Z}^2`),
        " を取り、",
        math(String.raw`t:=(-n_2,n_1)`),
        " と置くと ",
        math(String.raw`\langle v,n\rangle=-1`),
        "、",
        math(String.raw`\langle t,n\rangle=0`),
        "、",
        math(String.raw`\det(v,t)=1`),
        " なので ",
        math(String.raw`(v,t)`),
        " は ",
        math(String.raw`\mathbb{Z}^2`),
        " の基底である（",
        math(String.raw`v=u^\perp`),
        "）。",
        math(String.raw`s:=\chi^{v}`),
        "、",
        math(String.raw`\tau:=\chi^{t}`),
        " と置くと、",
        math(String.raw`e_j`),
        " を定める変形（",
        math(String.raw`\chi^{(p,q)}\mapsto\chi^{(p,q)}(1+T)^{\langle(p,q),n\rangle}`),
        "）はこの座標で ",
        math(String.raw`s\mapsto s(1+T)^{-1}`),
        "、",
        math(String.raw`\tau\mapsto\tau`),
        " という",
        math(String.raw`s`),
        " だけのスケーリングになり、",
        math(String.raw`\bar\psi_u`),
        " は ",
        math(String.raw`s\mapsto1`),
        "、",
        math(String.raw`\tau\mapsto(1+x)^{\pm1}`),
        " である。",
      ]),
      paragraph([
        math(String.raw`\bar{\tilde E}=(s-1)^{m}G`),
        "（",
        math(String.raw`m=m_u`),
        "、",
        math(String.raw`(s-1)\nmid G`),
        "）と書いて代入すると",
      ]),
      displayMath(
        String.raw`\sum_{j}\psi_j(x)T^j
        =\bigl(-T\bigr)^{m}(1+T)^{-m}\,\bar\psi_u\Bigl(G\bigl(s(1+T)^{-1},\tau\bigr)\Bigr)`,
      ),
      paragraph([
        "となり、右辺の ",
        math(String.raw`T`),
        " に関する位数はちょうど ",
        math(String.raw`m`),
        "、",
        math(String.raw`T^{m}`),
        " の係数は ",
        math(String.raw`(-1)^{m}\bar\psi_u(G)`),
        " である。",
        math(String.raw`(s-1)\nmid G`),
        " と ",
        math(String.raw`\ker\bar\psi_u=(s-1)`),
        " より ",
        math(String.raw`\bar\psi_u(G)\neq0`),
        " なので ",
        math(String.raw`\psi_j=0\ (j<m)`),
        "、",
        math(String.raw`\psi_m\neq0`),
        "、すなわち ",
        math(String.raw`e_j=\infty\ (j<m)`),
        " かつ ",
        math(String.raw`e_{m}=\mathrm{ord}_{x=0}\bar\psi_u(G)<\infty`),
        " である。",
        math(String.raw`P\in S_\infty`),
        " より ",
        math(String.raw`m\ge1`),
        " なので ",
        math(String.raw`j^*(P)=m`),
        "。",
      ]),
      paragraph([
        "(K5) の証明。最小点の一意性: (K4) より ",
        math(String.raw`j<m_u`),
        " では項が無く、",
        math(String.raw`j>m_u`),
        " では ",
        math(String.raw`e_j+j\ell^{r}\ge(m_u+1)\ell^{r}=m_u\ell^{r}+\ell^{r}>m_u\ell^{r}+e_{m_u}`),
        "（最後に ",
        math(String.raw`\ell^{r}>e_{m_u}`),
        " を使った）なので、最小は ",
        math(String.raw`j=m_u`),
        " でのみ達成される。球の分離: 原始整数ベクトル ",
        math(String.raw`u\neq\pm u'`),
        " について ",
        math(String.raw`\iota([u])`),
        " と ",
        math(String.raw`\iota([u'])`),
        " が ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{k})`),
        " で同じ点になるのは ",
        math(String.raw`\ell^{k}\mid\det(u,u')`),
        " のときに限る（",
        math(String.raw`u'\equiv cu`),
        " なら行列式が消え、逆は ",
        math(String.raw`u`),
        " が ",
        math(String.raw`\bmod\ \ell`),
        " で ",
        math(String.raw`0`),
        " でないことから従う）。",
        math(String.raw`\det(u,u')\neq0`),
        " なので ",
        math(String.raw`k>v_\ell(\det(u,u'))`),
        " で分離する。主張の ",
        math(String.raw`r_0`),
        " はこの 2 つを同時に満たす。",
      ]),
      paragraph([
        "この式が実対数を含まないこと、および床関数を使った書き方と同じ値を与えること。 ",
        math(String.raw`\lambda_u`),
        " は「",
        math(String.raw`\ell^{\lambda}>e_{m_u}`),
        " を満たす ",
        math(String.raw`\lambda\in\mathbb{N}`),
        " の最小元」であり、",
        math(String.raw`\ell\ge2`),
        " より ",
        math(String.raw`\ell^{\lambda}`),
        " は ",
        math(String.raw`\lambda`),
        " について狭義単調増加で非有界だから、この集合は空でなく最小元を持つ。判定は ",
        math(String.raw`e_{m_u}\in\mathbb{N}`),
        " に対する ",
        math(String.raw`\ell`),
        " の冪との整数比較ひとつであり、実対数を経由しないので、この式は可算側で閉じている。",
      ]),
      paragraph([
        "床関数を使った書き方との一致は次のとおりである。",
        math(String.raw`e_{m_u}\ge1`),
        " のとき ",
        math(String.raw`t:=\bigl\lfloor\log_\ell e_{m_u}\bigr\rfloor`),
        " は ",
        math(String.raw`\ell^{t}\le e_{m_u}<\ell^{t+1}`),
        " を満たす唯一の自然数だから、",
        math(String.raw`\ell^{\lambda}>e_{m_u}`),
        " を満たす最小の ",
        math(String.raw`\lambda`),
        " は ",
        math(String.raw`t+1`),
        " である。したがって ",
        math(String.raw`\lambda_u=\bigl\lfloor\log_\ell e_{m_u}\bigr\rfloor+1`),
        " であり、",
      ]),
      displayMath(
        String.raw`\max\Bigl(1+\max_{P\neq P'}v_\ell\bigl(\det(u,u')\bigr),\ \max_{P}\lambda_u\Bigr)
        =1+\max\Bigl(\max_{P\neq P'}v_\ell\bigl(\det(u,u')\bigr),\ \max_{P}\bigl\lfloor\log_\ell e_{m_u}\bigr\rfloor\Bigr)`,
      ),
      paragraph([
        "となって、",
        math(String.raw`r_0`),
        " の値は変わらない（",
        math(String.raw`1`),
        " を加える操作が ",
        math(String.raw`\max`),
        " と可換であることを使った）。加える位置が違うので、どちらの量を定義に採るかで補正項の扱いが変わる点には注意を要する。 さらに新しい書き方は ",
        math(String.raw`e_{m_u}=0`),
        " でも意味を持ち ",
        math(String.raw`\lambda_u=0`),
        " を与えるのに対し、床関数を使った書き方は ",
        math(String.raw`\log_\ell 0`),
        " を含んで定義されない。",
      ]),
      paragraph([
        "(K6) の証明。 ",
        ref("paper_prop_J"),
        " の (J4) の後半の式に、(J6)（",
        math(String.raw`S_\infty`),
        " の有限性）、(K5)（仮定 (N) の解消）、(K1)（例外直線との対応）、(K4)（",
        math(String.raw`j^*=m_u`),
        "）を入れると ",
        math(String.raw`b=\sum_{P\in S_\infty}j^*(P)=\sum_{i=1}^{r}m_i`),
        " を得る。",
        math(String.raw`b=0`),
        " の場合は ",
        math(String.raw`S_\infty=\emptyset`),
        " で (J4) の前半（型 II）である。残る仮定は (J4) の「レベルが十分深いところで ",
        math(String.raw`\hat\theta`),
        " を与える最小点が一意」だけであり、それは限界に明示した。",
      ]),
      paragraph([
        "(K7) の証明。 分解に Newton 多面体の加法性（Ostrowski の定理）を使うと ",
        math(String.raw`\mathrm{Newt}(\bar{\tilde E})=\sum_i m_i\,[0,v_i]+\mathrm{Newt}(G_0)+w_0`),
        " である。格子周長は Minkowski 和について加法的であり（和の辺ベクトルの多重集合は各因子の辺ベクトルの多重集合の合併になる）、",
        math(String.raw`v_i`),
        " が原始なので ",
        math(String.raw`\mathrm{per}(m_i[0,v_i])=2m_i`),
        "、また ",
        math(String.raw`\mathrm{per}\ge0`),
        " だから ",
        math(String.raw`\mathrm{per}(\mathrm{Newt}(\bar{\tilde E}))\ge2\sum_im_i=2b`),
        " である。等号が成り立つのは ",
        math(String.raw`\mathrm{per}(\mathrm{Newt}(G_0))=0`),
        "、すなわち ",
        math(String.raw`G_0`),
        " が単項式のときちょうどである。",
      ]),
    ],
  },
]);
