/**
 * 論文本体 第 11 章: 消滅深度の桁枝再帰（命題 R）。
 *
 * 命題 J の (J2)（ファイバー Newton 公式）は最小点が一意でないとき θ を決めなかった。
 * その打ち消しは、展開を「w の Hasse 微分」ではなく「指数の ℓ 進第 0 桁」で分けると
 * 構造的に起こりえないことを示し、θ を完全に決める。あわせて (J3) の
 * hat θ を終結式ひとつで書き、命題 J の (J3) が置いていた最小点一意性の仮定を外す。
 * 根拠レポートは outputs/reports/cycle20_T3_cancellation_recursion.md。
 *
 * 本章の主張はすべて Z・F_ℓ・Q(ζ_{ℓ^M}) の中で閉じる（ℝ を使わない）。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_100_heading_theta_recursion",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/009_theta_recursion.ts", ordinal: 1 },
    title: { text: "打ち消しは起きない — 消滅深度の桁枝再帰と、終結式による付値" },
    labels: [],
  },
  {
    id: "paper_101_theorem_digit_branch",
    kind: "theorem",
    origin: { path: "structured-latex/content/009_theta_recursion.ts", ordinal: 2 },
    title: { text: "命題 R — 桁枝再帰による消滅深度の決定と、終結式による付値" },
    labels: ["paper_prop_R"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle20_T3_cancellation"],
    lean: [
      "IntegrableLattice.sigma_eq_of_max",
      "IntegrableLattice.sigma_ne_zero_of_lambda_ne_zero",
      "IntegrableLattice.PropRResultantValuation.associated_resultant_psi",
      "IntegrableLattice.PropRResultantValuation.padicValInt_eq_of_associated_pow",
      "IntegrableLattice.PropRResultantValuation.ordEll_kappa_of_level_decomposition",
      "IntegrableLattice.PropRResultantValuation.associated_resultant_psi_of_powerBasis",
      "IntegrableLattice.PropRResultantValuation.exists_ringHom_sub_one",
      "IntegrableLattice.PropRZellExponent.coeff_one_add_X_pow_congr",
      "IntegrableLattice.PropRZellExponent.coeff_zellPow_eq",
      "IntegrableLattice.PropRZellExponent.exists_coeff_ne_zero_of_sepAt",
      "IntegrableLattice.PropRZellExponent.exists_coeff_ne_zero_lt_pow_sep",
    ],
    statement: [
      paragraph([
        ref("paper_prop_J"),
        " の設定を引き継ぐ。",
        math(String.raw`\bar{\tilde E}=\sum\bar c_{pq}z^pw^q\in\mathbb{F}_\ell[z,w]`),
        " と原始的な ",
        math(String.raw`(a,b)\in\mathbb{Z}_\ell^2`),
        " に対し、指数 ",
        math(String.raw`\gamma=pa+qb\in\mathbb{Z}_\ell`),
        " の値ごとに項をまとめて",
      ]),
      displayMath(
        String.raw`\overline{\Phi_{(a,b)}}(x)=\sum_{\gamma}\mu_\gamma\,(1+x)^{\gamma},
        \qquad \mu_\gamma=\sum_{pa+qb=\gamma}\bar c_{pq},`,
      ),
      paragraph([
        "と書き、",
        math(String.raw`\mu_\gamma\neq0`),
        " なる ",
        math(String.raw`\gamma`),
        " 全体を ",
        math(String.raw`\mathcal{G}(a,b)`),
        " とする（",
        ref("paper_prop_J"),
        " の (J6) より ",
        math(String.raw`\theta(a,b)=\infty\iff\mathcal{G}(a,b)=\emptyset`),
        "）。",
      ]),
      paragraph([
        "(R1 桁枝分解) ",
        math(String.raw`c\in\{0,\dots,\ell-1\}`),
        " について ",
        math(String.raw`\mathcal{G}`),
        " の第 0 桁が ",
        math(String.raw`c`),
        " の元を集め、",
        math(String.raw`\gamma\mapsto(\gamma-c)/\ell`),
        " で押し下げた族を ",
        math(String.raw`\mathcal{G}_c`),
        " とすると、",
        math(String.raw`\mathbb{F}_\ell[[x]]`),
        " の中で",
      ]),
      displayMath(
        String.raw`\overline{\Phi_{(a,b)}}(x)=\sum_{c=0}^{\ell-1}(1+x)^{c}\,g_c(x^{\ell}),
        \qquad g_c(y)=\sum_{\gamma\in\mathcal{G}_c}\mu_{c+\ell\gamma}\,(1+y)^{\gamma}`,
      ),
      paragraph([
        "が成り立つ（",
        math(String.raw`(1+x)^{\ell}=1+x^{\ell}`),
        " による）。",
      ]),
      paragraph([
        "(R2 打ち消しは起きない) ",
        math(String.raw`d:=\min_c\mathrm{ord}_y\,g_c`),
        "、",
        math(String.raw`C:=\{c:\mathrm{ord}_y\,g_c=d\}`),
        "、",
        math(String.raw`\lambda_c:=`),
        " ",
        math(String.raw`g_c`),
        " の最低次係数 とすると、",
      ]),
      displayMath(
        String.raw`\theta(a,b)=\ell\,d+s^{*},\qquad
        s^{*}=\min\Bigl\{s\ge0:\ \sigma_s:=\sum_{c\in C}\lambda_c\binom{c}{s}\neq0\Bigr\},`,
      ),
      paragraph([
        "であり、",
        math(String.raw`s^{*}`),
        " は必ず存在して ",
        math(String.raw`s^{*}\le\ell-1`),
        " を満たす。実際 ",
        math(String.raw`0\le c,s\le\ell-1`),
        " の行列 ",
        math(String.raw`\bigl(\binom cs\bigr)_{c,s}`),
        " は ",
        math(String.raw`\mathbb{F}_\ell`),
        " 上で下三角かつ対角成分が ",
        math(String.raw`1`),
        " なので可逆であり、",
        math(String.raw`(\lambda_c)_{c\in C}\neq0`),
        " から ",
        math(String.raw`(\sigma_s)_{0\le s\le\ell-1}\neq0`),
        " が従う。したがって ",
        ref("paper_prop_J"),
        " の (J2) で ",
        math(String.raw`\theta`),
        " を決められなかった打ち消し（最小点が一意でない場合）は、この分解では構造的に起こらない。",
      ]),
      paragraph([
        "(R3 有限性と有効上界) ",
        math(String.raw`\mathrm{sep}(a,b):=\min\{t\ge0:\mathcal{G}\ \text{の元が}\ \bmod\ \ell^{t}\ \text{で相異なる}\}`),
        " と置くと、(R2) の再帰は深さ ",
        math(String.raw`\mathrm{sep}`),
        " で停止し、",
      ]),
      displayMath(String.raw`\mathcal{G}\neq\emptyset\ \Longrightarrow\ \theta(a,b)\le\ell^{\mathrm{sep}(a,b)}-1<\infty.`),
      paragraph([
        "さらに ",
        math(String.raw`\mathcal{G}`),
        " の元の差は ",
        math(String.raw`S=\mathrm{supp}(\bar{\tilde E})`),
        " の差ベクトル ",
        math(String.raw`\delta`),
        " の値 ",
        math(String.raw`\delta_1a+\delta_2b`),
        " なので、",
      ]),
      displayMath(
        String.raw`\theta(a,b)\ \le\ \ell^{\,1+\max_{\delta}v_\ell(\delta_1a+\delta_2b)}-1
        \qquad(\text{max は }\delta_1a+\delta_2b\neq0\text{ なる }\delta\text{ 上}),`,
      ),
      paragraph([
        "が成り立つ（そのような ",
        math(String.raw`\delta`),
        " が 1 つも無ければ ",
        math(String.raw`|\mathcal{G}|\le1`),
        " なので ",
        math(String.raw`\theta(a,b)=0`),
        " であり、この場合は max を取る必要がない）。",
      ]),
      paragraph([
        "すなわち ",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`P=(a{:}b)`),
        " が ",
        ref("paper_prop_J"),
        " の (J6) が与える ",
        math(String.raw`S_\infty`),
        " の候補点へ ",
        math(String.raw`\ell`),
        " 進的に近づくときにだけ大きくなり、その増大は候補点までの距離の逆数で抑えられる。",
        "これは ",
        ref("paper_prop_J"),
        " の (J1) が与える「有限なら局所定数」よりも強く、有効である。",
      ]),
      paragraph([
        "(R4 終結式による付値) ",
        math(String.raw`\Psi_M(x):=\Phi_{\ell^{M}}(1+x)\in\mathbb{Z}[x]`),
        "（",
        math(String.raw`\pi=\zeta_{\ell^{M}}-1`),
        " の最小多項式、モニック、次数 ",
        math(String.raw`\varphi(\ell^{M})`),
        "）と置く。",
        math(String.raw`E(\zeta^a,\zeta^b)\neq0`),
        " なら",
      ]),
      displayMath(
        String.raw`\hat\theta_{M}(a,b)=\varphi(\ell^{M})\,v_\ell\bigl(E(\zeta^a,\zeta^b)\bigr)
        =v_\ell\Bigl(\mathrm{Res}_x\bigl(\Psi_M,\ \Phi_{(a,b)}\bigr)\Bigr)`,
      ),
      paragraph([
        "である。これは ",
        math(String.raw`\ell`),
        " が ",
        math(String.raw`\mathbb{Q}(\zeta_{\ell^{M}})`),
        " で完全分岐（分岐指数 ",
        math(String.raw`\varphi(\ell^{M})`),
        "、剰余次数 ",
        math(String.raw`1`),
        "）であることと、終結式がノルム ",
        math(String.raw`N_{\mathbb{Q}(\zeta_{\ell^{M}})/\mathbb{Q}}\bigl(\Phi_{(a,b)}(\pi)\bigr)`),
        " に等しいことから従う。右辺は整数ひとつの ",
        math(String.raw`\ell`),
        " 進付値であり、",
        ref("paper_prop_J"),
        " の (J3) が置いていた「",
        math(String.raw`\min_m(\varphi(\ell^{M})v_\ell(A_m)+m)`),
        " の最小点が一意」という仮定を使わない。",
      ]),
      paragraph([
        "(R5 予言アルゴリズムの無仮定化) ",
        ref("paper_prop_J"),
        " の (J3) のレベル分解 ",
        math(String.raw`\Sigma_n=\sum_{M=1}^{n}\Theta_M`),
        "（仮定なしに成立）と (R4) を合わせると、",
        math(String.raw`E`),
        " がレベル ",
        math(String.raw`\le n`),
        " の 1 の冪根で消えない限り",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_\ell(\kappa_n)=\mu(\ell^{2n}-1)-2n+v_\ell(\kappa(X))
        +\sum_{M=1}^{n}\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{M})}
        v_\ell\bigl(\mathrm{Res}_x(\Psi_M,\Phi_P)\bigr)`,
      ),
      paragraph([
        "が 仮定なしに 成り立つ。右辺は ",
        math(String.raw`D`),
        " の係数からの整数計算だけで決まる（塔の値も円分体の計算も使わない）。",
      ]),
      paragraph([
        "本命題に残る限界は次のとおりである。",
      ]),
      list([
        [
          "(R2) が潰すのは ",
          ref("paper_prop_J"),
          " の (J2) の打ち消しであって、(J3) の最小点の tie ではない。両者は別の障害であり、",
          math(String.raw`\ell=2`),
          " のトーラスでレベル 3 の ",
          math(String.raw`\Theta_3`),
          " が (J3) の和 ",
          math(String.raw`40`),
          " と真値 ",
          math(String.raw`44`),
          " でずれるのは後者が原因である。後者を外すのは (R4) の役割である。",
        ],
        [
          "(R5) は ",
          math(String.raw`\mathrm{ord}_\ell(\kappa_n)`),
          " を各 ",
          math(String.raw`n`),
          " について決定するが、",
          math(String.raw`n`),
          " についての閉形式ではない（レベル ",
          math(String.raw`M`),
          " の項数は ",
          math(String.raw`(\ell+1)\ell^{M-1}`),
          " で増える）。閉形式は ",
          ref("paper_prop_J"),
          " の (J4)・(J5) や ",
          ref("paper_prop_G_infty"),
          " の側の問題として残る。",
        ],
        [
          "本命題は ",
          math(String.raw`d=2`),
          " に限る。",
        ],
        [
          "新規性は主張しない。 (R1)(R2) は岩澤代数 ",
          math(String.raw`\mathbb{F}_\ell[[\mathbb{Z}_\ell]]\cong\mathbb{F}_\ell[[x]]`),
          " において、有限台の測度の ",
          math(String.raw`\lambda`),
          " 不変量を台の ",
          math(String.raw`\ell`),
          " 進木に沿って計算する手続きであり、標準的な道具である可能性が高い。",
          "(R4) も終結式＝ノルムという標準事実の適用である。対応する文献命題は特定できていない。",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "本文に無い補題へ暗黙に依存しないために、途中で使う事実はすべてその主張をここで述べてから使う。 ",
        "使う道具は ",
        math(String.raw`\mathbb{F}_\ell`),
        " 上の Frobenius、",
        math(String.raw`\mathbb{F}_\ell`),
        " 上の線型代数、円分体 ",
        math(String.raw`\mathbb{Q}(\zeta_{\ell^{M}})`),
        " のノルムと分岐だけであり、実数体へは一度も出ない。",
      ]),
      paragraph([
        "(R1) の証明。 ",
        math(String.raw`\gamma\equiv c\ (\ell)`),
        " なる ",
        math(String.raw`\gamma`),
        " を ",
        math(String.raw`\gamma=c+\ell\gamma'`),
        " と書く。",
        math(String.raw`\mathbb{F}_\ell`),
        " 上 Frobenius により ",
        math(String.raw`(1+x)^{\ell}=1+x^{\ell}`),
        " なので",
      ]),
      displayMath(
        String.raw`(1+x)^{\gamma}=(1+x)^{c}\bigl((1+x)^{\ell}\bigr)^{\gamma'}
        =(1+x)^{c}\bigl(1+x^{\ell}\bigr)^{\gamma'}`,
      ),
      paragraph([
        "である（",
        math(String.raw`(1+y)^{\gamma'}=\sum_m\binom{\gamma'}{m}y^{m}`),
        " は ",
        ref("paper_prop_J"),
        " の (J1) により ",
        math(String.raw`\gamma'\in\mathbb{Z}_\ell`),
        " に対して well-defined である）。",
        math(String.raw`\gamma`),
        " を第 0 桁 ",
        math(String.raw`c`),
        " ごとにまとめ、",
        math(String.raw`y=x^{\ell}`),
        " を代入すれば主張の分解を得る。",
      ]),
      paragraph([
        "(R2) の証明。まず ",
        math(String.raw`s^{*}`),
        " の存在（これは帰納法に依らない）。",
        math(String.raw`0\le c,s\le\ell-1`),
        " では ",
        math(String.raw`\binom cs`),
        " は通常の整数二項係数の ",
        math(String.raw`\bmod\ \ell`),
        " であり、",
        math(String.raw`s>c`),
        " なら ",
        math(String.raw`0`),
        "、",
        math(String.raw`s=c`),
        " なら ",
        math(String.raw`1`),
        " である。したがって ",
        math(String.raw`B:=\bigl(\binom cs\bigr)_{0\le c,s\le\ell-1}`),
        " は下三角かつ対角成分 ",
        math(String.raw`1`),
        " の行列で可逆である。",
        math(String.raw`C\neq\emptyset`),
        " かつ ",
        math(String.raw`\lambda_c\neq0\ (c\in C)`),
        " より ",
        math(String.raw`\lambda=(\lambda_c)_c`),
        "（",
        math(String.raw`c\notin C`),
        " では ",
        math(String.raw`0`),
        " と置く）は零ベクトルでないので ",
        math(String.raw`\sigma=\lambda B\neq0`),
        "、すなわち ",
        math(String.raw`\sigma_s\neq0`),
        " なる ",
        math(String.raw`s\le\ell-1`),
        " が存在する。",
      ]),
      paragraph([
        "これは次の直和分解の言い換えである。 ",
        math(String.raw`\mathbb{F}_\ell[[x]]`),
        " は ",
        math(String.raw`\mathbb{F}_\ell[[x^{\ell}]]`),
        " 上、",
        math(String.raw`\{(1+x)^{c}\}_{0\le c\le\ell-1}`),
        " を基底とする階数 ",
        math(String.raw`\ell`),
        " の自由加群である（",
        math(String.raw`\{1,x,\dots,x^{\ell-1}\}`),
        " が基底であることは ",
        math(String.raw`x`),
        " 進展開を ",
        math(String.raw`\ell`),
        " 個の剰余類に分けるだけであり、",
        math(String.raw`(1+x)^{c}=\sum_{s=0}^{c}\binom csx^{s}`),
        " は下三角かつ対角成分 ",
        math(String.raw`1`),
        " の基底変換である）。(R1) は、この基底に関する ",
        math(String.raw`\overline{\Phi_{(a,b)}}`),
        " の成分がちょうど ",
        math(String.raw`g_c`),
        " だと言っている。直和分解の成分は互いに干渉しないので、打ち消しが構造的に起きない。",
      ]),
      paragraph([
        "次に等式。",
        math(String.raw`\mathrm{sep}(a,b)=:t`),
        " についての帰納法で示す。",
        math(String.raw`t=0`),
        " のときは ",
        math(String.raw`|\mathcal{G}|=1`),
        " で ",
        math(String.raw`\overline{\Phi_{(a,b)}}`),
        " が単元だから ",
        math(String.raw`\theta=0=\ell^{0}-1`),
        " である。",
        math(String.raw`t\ge1`),
        " とすると、枝 ",
        math(String.raw`c`),
        " の中では ",
        math(String.raw`\gamma_i\equiv\gamma_j\ (\ell^{t'})\iff\gamma_i'\equiv\gamma_j'\ (\ell^{t'-1})`),
        " なので押し下げた族の ",
        math(String.raw`\mathrm{sep}`),
        " は ",
        math(String.raw`\le t-1`),
        " であり、帰納法の仮定より ",
        math(String.raw`\mathrm{ord}_y\,g_c<\infty`),
        " かつ ",
        math(String.raw`\mathrm{ord}_y\,g_c\le\ell^{t-1}-1`),
        " である。",
      ]),
      paragraph([
        "(R1) より ",
        math(String.raw`c\in C`),
        " の項は ",
        math(String.raw`(1+x)^{c}\bigl(\lambda_cx^{\ell d}+O(x^{\ell(d+1)})\bigr)`),
        "、",
        math(String.raw`c\notin C`),
        " の項は ",
        math(String.raw`O(x^{\ell(d+1)})`),
        " である。",
        math(String.raw`0\le s\le\ell-1`),
        " なら ",
        math(String.raw`\ell d+s<\ell(d+1)`),
        " なので、",
        math(String.raw`x^{\ell d+s}`),
        " の係数に寄与するのは ",
        math(String.raw`c\in C`),
        " の ",
        math(String.raw`\lambda_cx^{\ell d}\cdot\binom csx^{s}`),
        " だけであり、",
      ]),
      displayMath(
        String.raw`\bigl[x^{\ell d+s}\bigr]\overline{\Phi_{(a,b)}}=\sum_{c\in C}\lambda_c\binom cs=\sigma_s
        \qquad(0\le s\le\ell-1)`,
      ),
      paragraph([
        "を得る。上で示したとおり ",
        math(String.raw`\sigma_{s^{*}}\neq0`),
        "（",
        math(String.raw`s^{*}\le\ell-1`),
        "）で、",
        math(String.raw`s<s^{*}`),
        " では ",
        math(String.raw`\sigma_s=0`),
        " だから ",
        math(String.raw`\theta(a,b)=\ell d+s^{*}`),
        " であり、最低次係数は ",
        math(String.raw`\sigma_{s^{*}}`),
        " である。",
      ]),
      paragraph([
        "(R3) の証明。 上の帰納法の最後に ",
        math(String.raw`\theta(a,b)=\ell d+s^{*}\le\ell(\ell^{t-1}-1)+(\ell-1)=\ell^{t}-1`),
        " が従うので、",
        math(String.raw`\mathcal{G}\neq\emptyset`),
        " なら ",
        math(String.raw`\theta(a,b)\le\ell^{\mathrm{sep}(a,b)}-1<\infty`),
        " である。この上界は達成される: ",
        math(String.raw`\mathcal{G}=\{0,1,\dots,\ell^{t}-1\}`),
        " で係数がすべて ",
        math(String.raw`1`),
        " のとき ",
        math(String.raw`\mathrm{sep}=t`),
        " であり、",
        math(String.raw`\mathbb{F}_\ell`),
        " 上 ",
        math(String.raw`\sum_{j=0}^{\ell^{t}-1}(1+x)^{j}=\frac{(1+x)^{\ell^{t}}-1}{x}=x^{\ell^{t}-1}`),
        " となって ",
        math(String.raw`\theta=\ell^{t}-1`),
        " である。",
      ]),
      paragraph([
        "後半は、",
        math(String.raw`\mathcal{G}`),
        " の相異なる 2 元の差がある ",
        math(String.raw`\delta\in S-S`),
        " について ",
        math(String.raw`\delta_1a+\delta_2b\ (\neq0)`),
        " に等しいことによる。したがって ",
        math(String.raw`\mathrm{sep}(a,b)\le1+\max_{\delta}v_\ell(\delta_1a+\delta_2b)`),
        " となり、前半の上界に代入すれば主張の式を得る。そのような ",
        math(String.raw`\delta`),
        " が 1 つも無ければ ",
        math(String.raw`|\mathcal{G}|\le1`),
        " なので ",
        math(String.raw`\theta(a,b)=0`),
        " である。",
      ]),
      paragraph([
        "(R3) が使っている仮定の範囲。 上の議論が ",
        ref("paper_prop_J"),
        " の (J1) から使うのは「",
        math(String.raw`\gamma\in\mathbb{Z}_\ell`),
        " に対し ",
        math(String.raw`\binom{\gamma}{m}\bmod\ell`),
        " が ",
        math(String.raw`\gamma`),
        " の有限桁で決まる」という ",
        math(String.raw`m<\ell^{L}`),
        " 側（Lucas の定理だけ）であって、",
        math(String.raw`m=\ell^{L}`),
        " ちょうどの段（",
        math(String.raw`A_1\equiv0`),
        " を要する段）は使わない。したがって (R1)–(R3) は ",
        math(String.raw`A_1\equiv0`),
        " に依存しない。",
      ]),
      paragraph([
        "(R4) の証明。 ",
        math(String.raw`K=\mathbb{Q}(\zeta_{\ell^{M}})`),
        "、",
        math(String.raw`\varphi=\varphi(\ell^{M})=[K:\mathbb{Q}]`),
        " とすると ",
        math(String.raw`\ell`),
        " は ",
        math(String.raw`K`),
        " で完全分岐し ",
        math(String.raw`\ell\mathcal{O}_K=(\pi)^{\varphi}`),
        "、剰余次数は ",
        math(String.raw`1`),
        " である。",
        math(String.raw`\Psi_M`),
        " はモニックでその根が ",
        math(String.raw`\pi`),
        " の共役全体だから、",
        math(String.raw`F\in\mathbb{Z}[x]`),
        " に対し",
      ]),
      displayMath(
        String.raw`\mathrm{Res}_x(\Psi_M,F)=\prod_{\sigma}F(\sigma\pi)=N_{K/\mathbb{Q}}\bigl(F(\pi)\bigr)\in\mathbb{Z}`,
      ),
      paragraph([
        "である。一般に ",
        math(String.raw`\alpha\in K^\times`),
        " について ",
        math(String.raw`v_\ell\bigl(N_{K/\mathbb{Q}}(\alpha)\bigr)=f\cdot v_{\mathfrak{l}}(\alpha)`),
        "（",
        math(String.raw`\mathfrak{l}`),
        " は ",
        math(String.raw`\ell`),
        " の上の唯一の素点、",
        math(String.raw`f=1`),
        "、",
        math(String.raw`v_{\mathfrak{l}}=\varphi\cdot v_\ell`),
        "）なので ",
        math(String.raw`v_\ell(N(\alpha))=\varphi\,v_\ell(\alpha)`),
        " である。",
        math(String.raw`F=\Phi_{(a,b)}`),
        " とすると ",
        math(String.raw`F(\pi)=\tilde E(\zeta^a,\zeta^b)`),
        " で、",
        math(String.raw`\tilde E`),
        " と ",
        math(String.raw`E`),
        " の違いは単項式（1 の冪根＝単元）だけだから付値が一致する。ノルムを直接取るので、最小点の同点の有無に関わらず等号である。",
      ]),
      paragraph([
        "(R5) の証明。 ",
        ref("paper_prop_J"),
        " の (J3) のレベル分解（仮定なしに成立）と (R4) を合わせるだけである。",
        ref("paper_prop_W"),
        " の証明にある積の公式から出る ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)=v_\ell(\kappa(X))-2n+\mu(\ell^{2n}-1)+\Sigma_n`),
        " に ",
        math(String.raw`\Sigma_n=\sum_{M=1}^{n}\Theta_M`),
        " と ",
        math(String.raw`\hat\theta_M(P)=v_\ell(\mathrm{Res}_x(\Psi_M,\Phi_P))`),
        " を入れれば主張の式を得る。残る前提は仮定 (H) と、",
        math(String.raw`E`),
        " がレベル ",
        math(String.raw`\le n`),
        " の 1 の冪根の組で消えないことだけで、どちらも総和公式それ自体が要求するものである。",
      ]),
    ],
  },
]);
