/**
 * 論文本体 第 11 章: 最小点の一意性の仮定を落とす（命題 Q）。
 *
 * 命題 K (K6) は n ℓ^n の係数 b = Σ j* を出したが、「レベルが十分深いところで
 * hat theta を与える最小点が一意である」という仮定が残っていた（同命題の限界）。
 * 本章はその仮定を落とす。着想は mod ℓ の因数分解を**整数へ持ち上げる**こと
 * （tilde E = B G + ℓ H）であり、これにより hat theta の評価が 2 項の付値の比較になる。
 * 比較が拮抗する点はレベルごとに O(1) 個しかないので、n ℓ^n の係数には効かない。
 *
 * 根拠レポート: outputs/reports/cycle21_T3_drop_assumption_B_star.md
 *   （**cycle 25 step 1 の訂正後の版**を正本とする。補題 Q5 の定数 c_1 は
 *   「2b < (ℓ-1)ℓ^c を満たす最小の自然数」であり、初稿の実対数による定義ではない）。
 *
 * 本章は **ℝ へ脱出する**。脱出は (Q4)（粗上界）ただ 1 箇所に隔離されており、
 * habitat / realEscape でそれを宣言している。b の値にも b の決定手続きにも ℝ は入らない。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_105_heading_drop_assumption",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/009c_drop_assumption_b_star.ts", ordinal: 1 },
    title: { text: "最小点の一意性の仮定を落とす — n ℓ^n の係数の無条件決定" },
    labels: [],
  },
  {
    id: "paper_106_theorem_drop_assumption",
    kind: "theorem",
    origin: { path: "structured-latex/content/009c_drop_assumption_b_star.ts", ordinal: 2 },
    title: { text: "命題 Q — 最小点の一意性の仮定なしに n ℓ^n の係数が決まること（明示誤差つき）" },
    labels: ["paper_prop_Q"],
    habitat: "mixed",
    realEscape:
      "(Q4)（粗上界 hat theta_M(P) ≤ φ(ℓ^M) log_ℓ C_0）の証明だけが、複素絶対値（アルキメデス素点）を使う。" +
      "役割は「悪い点」= レベルごとに O(1) 個の点の寄与を O(ℓ^M) で押さえることだけであり、" +
      "結論の値 b にも b の決定手続きにも入らない。(Q7) の定数 C に残る log_ℓ C_0 はこの 1 箇所に由来し、" +
      "誤差項の係数にしか現れない。ほかの (Q1)(Q2)(Q3)(Q5)(Q6)(Q8) は ℤ・F_ℓ・ℚ(ζ_{ℓ^M}) の中で閉じる。",
    verification: ["sagemath/check/cycle21_T3_b_star"],
    lean: [
      "IntegrableLattice.unique_min_of_val_seq",
      "IntegrableLattice.BG_dominates",
      "IntegrableLattice.sum_totient_pow",
    ],
    statement: [
      paragraph([
        ref("paper_prop_K"),
        " の設定を引き継ぐ。",
        math(String.raw`X`),
        " は有限連結 voltage 多重グラフ、",
        math(String.raw`D=\det L(z,w)`),
        "、",
        math(String.raw`\mu=v_\ell(\mathrm{content}\,D)`),
        "、",
        math(String.raw`E=\ell^{-\mu}D`),
        "、",
        math(String.raw`\tilde E=\sum_{(p,q)}c_{pq}z^{p}w^{q}\in\mathbb{Z}[z,w]`),
        "（",
        math(String.raw`E`),
        " に単項式を掛けて多項式にしたもの）、",
        math(String.raw`\kappa_n=\kappa(X_{\ell^n,\ell^n})`),
        " とし、仮定 (H)（全段連結）を通して置く。",
        math(String.raw`K_M=\mathbb{Q}(\zeta_{\ell^{M}})`),
        " の中で ",
        math(String.raw`\ell`),
        " の上の唯一の素点の付値 ",
        math(String.raw`v_{\mathfrak{l}}`),
        " を ",
        math(String.raw`v_{\mathfrak{l}}(\ell)=\varphi(\ell^{M})`),
        " と正規化し、原始 ",
        math(String.raw`\ell^{M}`),
        " 乗根 ",
        math(String.raw`\zeta`),
        " と ",
        math(String.raw`P=(a{:}b)\in\mathbb{P}^1(\mathbb{Z}/\ell^{M})`),
        " に対し指標 ",
        math(String.raw`\omega_P:z\mapsto\zeta^{a},\ w\mapsto\zeta^{b}`),
        "、",
        math(String.raw`\hat\theta_M(P)=v_{\mathfrak{l}}\bigl(\tilde E(\omega_P)\bigr)`),
        "、",
        math(String.raw`\Theta_M=\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{M})}\hat\theta_M(P)`),
        " と置く。",
      ]),
      paragraph([
        ref("paper_prop_K"),
        " の (K4) の一意分解",
      ]),
      displayMath(
        String.raw`\bar{\tilde E}=c\,\chi^{w_0}\prod_{i=1}^{r}\bigl(\chi^{v_i}-1\bigr)^{m_i}\cdot\bar G_0,
        \qquad c\in\mathbb{F}_\ell^\times,\quad(\chi^{v}-1)\nmid\bar G_0`,
      ),
      paragraph([
        "を取り（",
        math(String.raw`v_i`),
        " は原始ベクトル、",
        math(String.raw`\pm`),
        " 同一視）、",
        math(String.raw`b:=\sum_{i=1}^{r}m_i`),
        " と置く。",
        ref("paper_prop_K"),
        " の (K4)(K6) より ",
        math(String.raw`b=\sum_{P\in S_\infty}j^{*}(P)`),
        " である。",
      ]),
      paragraph([
        "(Q1 整数のままの分解) ",
        math(String.raw`B:=\prod_{i=1}^{r}\bigl(\chi^{v_i}-1\bigr)^{m_i}\in\mathbb{Z}[z^{\pm1},w^{\pm1}]`),
        " と置く（",
        math(String.raw`v_i`),
        " は整数ベクトルなので ",
        math(String.raw`B`),
        " は整数係数である）。",
        math(String.raw`\bar{\tilde E}/\bar B\in\mathbb{F}_\ell[z^{\pm1},w^{\pm1}]`),
        " の任意の持ち上げ ",
        math(String.raw`G\in\mathbb{Z}[z^{\pm1},w^{\pm1}]`),
        " を取ると",
      ]),
      displayMath(
        String.raw`H:=\frac{\tilde E-B\,G}{\ell}\ \in\ \mathbb{Z}[z^{\pm1},w^{\pm1}]`,
      ),
      paragraph([
        "であり、",
        math(String.raw`\bar G`),
        " は原始二項式因子 ",
        math(String.raw`\chi^{v}-1`),
        " をひとつも持たない。",
        "剰余体上の因数分解を整数へ持ち上げるのが本命題の着想であり、これによって深さは全部 ",
        "第 1 因子の側へ移る。 移した先が ",
        math(String.raw`B`),
        "、残るのが ",
        math(String.raw`G`),
        " である。",
      ]),
      paragraph([
        "(Q2 第 2 因子の側は一様に浅い) ",
        math(String.raw`\tilde G`),
        " を ",
        math(String.raw`G`),
        " に単項式を掛けて多項式にしたもの、",
        math(String.raw`\Phi^{G}_{(a,b)}(x)=\tilde G\bigl((1+x)^{a},(1+x)^{b}\bigr)`),
        "、",
        math(String.raw`\theta_G(P):=\mathrm{ord}_{x=0}\overline{\Phi^{G}_{(a,b)}}`),
        " と置く。このとき (1) ",
        math(String.raw`\theta_G(P)<\infty`),
        " が全ての ",
        math(String.raw`P\in\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " で成り立ち、したがって ",
        math(String.raw`\theta_G`),
        " は有界である（最大値を ",
        math(String.raw`\theta_G^{\max}`),
        " と書く）。(2) ",
        math(String.raw`\varphi(\ell^{M})>\theta_G^{\max}`),
        " なるレベル ",
        math(String.raw`M`),
        " のすべての点 ",
        math(String.raw`P`),
        " で ",
        math(String.raw`v_{\mathfrak{l}}\bigl(G(\omega_P)\bigr)=\theta_G(P)<\infty`),
        " である。",
      ]),
      paragraph([
        "(Q3 点ごとの等号) 標準内積を ",
        math(String.raw`\langle\cdot,\cdot\rangle`),
        " と書き、",
      ]),
      displayMath(
        String.raw`\rho_i(P):=\min\Bigl(v_\ell\bigl(\langle v_i,(a,b)\rangle\bigr),\ M\Bigr)\in\{0,1,\dots,M\},
        \qquad \beta_P:=\sum_{i=1}^{r}m_i\,\ell^{\rho_i(P)}`,
      ),
      paragraph([
        "と置く。",
        math(String.raw`\varphi(\ell^{M})>\theta_G^{\max}`),
        " とし、点 ",
        math(String.raw`P`),
        " が",
      ]),
      displayMath(String.raw`\beta_P+\theta_G^{\max}<\varphi(\ell^{M})`),
      paragraph([
        "を満たすならば（とくに全ての ",
        math(String.raw`i`),
        " で ",
        math(String.raw`\rho_i(P)<M`),
        "）、",
        math(String.raw`\hat\theta_M(P)=\beta_P+\theta_G(P)`),
        " が等号で成り立つ。この条件を満たす点を「良い点」、満たさない点を「悪い点」と呼ぶ。",
      ]),
      paragraph([
        "(Q4 粗上界。ここだけが実数体へ脱出する) ",
        math(String.raw`C_0:=\sum_{(p,q)}|c_{pq}|`),
        " と置く。",
        math(String.raw`\tilde E(\omega_P)\neq0`),
        " ならば",
      ]),
      displayMath(String.raw`\hat\theta_M(P)\ \le\ \varphi(\ell^{M})\,\log_\ell C_0 .`),
      paragraph([
        "本命題で非可算の世界へ出るのはこの 1 箇所だけである。 使うのは複素絶対値",
        "（アルキメデス素点）であり、下の「可算と非可算の分別」で隔離のされ方を明示する。",
      ]),
      paragraph([
        "(Q5 悪い点はレベルに依らず有限個) ",
        math(String.raw`\mathcal{B}_M:=\bigl\{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{M}):\beta_P+\theta_G^{\max}\ge\varphi(\ell^{M})\bigr\}`),
        " と置き、",
      ]),
      displayMath(
        String.raw`c_1:=\min\bigl\{\,c\in\mathbb{Z}_{\ge0}\ :\ 2b<(\ell-1)\,\ell^{c}\,\bigr\}`,
      ),
      paragraph([
        "と定める。",
        math(String.raw`\varphi(\ell^{M})\ge2\theta_G^{\max}`),
        " かつ ",
        math(String.raw`M>c_1`),
        " ならば ",
        math(String.raw`\lvert\mathcal{B}_M\rvert\le r\,\ell^{c_1}`),
        " であり、とくにこの個数は ",
        math(String.raw`M`),
        " に依らない。",
        "この定数の定義には実対数も切り上げも現れない。 実際 ",
        math(String.raw`\ell\ge2`),
        " なので ",
        math(String.raw`(\ell-1)\ell^{c}`),
        " は ",
        math(String.raw`c`),
        " について狭義単調増加で非有界であり、条件 ",
        math(String.raw`2b<(\ell-1)\ell^{c}`),
        " は整数の比較ひとつだから決定可能で、条件を満たす ",
        math(String.raw`c`),
        " の集合は空でない ",
        math(String.raw`\mathbb{Z}_{\ge0}`),
        " の部分集合として最小元を持つ。",
        math(String.raw`b=0`),
        " のときは ",
        math(String.raw`c=0`),
        " が ",
        math(String.raw`0<\ell-1`),
        " を満たすので ",
        math(String.raw`c_1=0`),
        " である。",
      ]),
      paragraph([
        "(Q6 数え上げ) 原始整数ベクトル ",
        math(String.raw`v`),
        " と ",
        math(String.raw`M\ge1`),
        " について",
      ]),
      displayMath(
        String.raw`\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{M})}\ell^{\rho_v(P)}
        =(M-1)\,\varphi(\ell^{M})+2\,\ell^{M}.`,
      ),
      paragraph([
        "(Q7 最小点の一意性の仮定なしに ",
        math(String.raw`n\ell^{n}`),
        " の係数が決まる) 仮定 (H) の下、",
        math(String.raw`\varphi(\ell^{M})\ge2\theta_G^{\max}`),
        " かつ ",
        math(String.raw`M>c_1`),
        " なる全ての ",
        math(String.raw`M`),
        " で",
      ]),
      displayMath(
        String.raw`\bigl|\,\Theta_M-b\,M\,\varphi(\ell^{M})\,\bigr|\ \le\ C\,\ell^{M},
        \qquad
        C:=b\bigl(3+r\,\ell^{c_1}\bigr)+\theta_G^{\max}\frac{\ell+1}{\ell}+r\,\ell^{c_1}\log_\ell C_0`,
      ),
      paragraph([
        "が成り立ち（",
        math(String.raw`C`),
        " は ",
        math(String.raw`M`),
        " に依らない明示定数である）、したがって",
      ]),
      displayMath(
        String.raw`\mathrm{ord}_\ell(\kappa_n)=\mu\bigl(\ell^{2n}-1\bigr)+b\,n\,\ell^{n}+O\bigl(\ell^{n}\bigr)`,
      ),
      paragraph([
        "である。",
        "すなわち、",
        ref("paper_prop_K"),
        " の (K6) に残っていた仮定「レベルが十分深いところで最小点が一意であること」は落ちる。",
        " 落ちる理由は、その仮定が破れうる点が (Q5) より ",
        math(String.raw`M`),
        " に依らず有限個しかなく、有限個の点は ",
        math(String.raw`O(\ell^{M})`),
        " しか動かせないので ",
        math(String.raw`M\ell^{M}`),
        " の係数に効かないことである。",
      ]),
      paragraph([
        "(Q8 ",
        math(String.raw`b=0`),
        " の場合) ",
        math(String.raw`b=0`),
        " と ",
        math(String.raw`r=0`),
        " は同値であり（(K4) の ",
        math(String.raw`m_i`),
        " は ",
        math(String.raw`\ge1`),
        " である）、このとき ",
        math(String.raw`B`),
        " は空積 ",
        math(String.raw`1`),
        "、全ての ",
        math(String.raw`P`),
        " で ",
        math(String.raw`\beta_P=0`),
        "、",
        math(String.raw`c_1=0`),
        "、",
        math(String.raw`\mathcal{B}_M=\emptyset`),
        " である。仮定 ",
        math(String.raw`M>c_1`),
        " は ",
        math(String.raw`M\ge1`),
        "（＝全てのレベル）になり、定数は ",
        math(String.raw`C=\theta_G^{\max}\frac{\ell+1}{\ell}`),
        " に退化して (Q7) は",
      ]),
      displayMath(String.raw`\lvert\Theta_M\rvert\ \le\ \theta_G^{\max}(\ell+1)\ell^{M-1}`),
      paragraph([
        "を与える。すなわち ",
        math(String.raw`n\ell^{n}`),
        " の項が消えて ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)=\mu(\ell^{2n}-1)+O(\ell^{n})`),
        " である。",
        "この場合は仮想ではない。 ",
        ref("paper_prop_M"),
        " の (M6)（",
        math(String.raw`S_\infty=\emptyset`),
        "）がまさにこの場合であり、そこでは誤差項の中身まで開いて ",
        math(String.raw`c=\frac{\ell}{\ell-1}A_{\mathrm{gen}}`),
        " が出る。両者は整合する。",
      ]),
      paragraph([
        "可算と非可算の分別",
      ]),
      list([
        [
          math(String.raw`b`),
          " の決定は ",
          math(String.raw`\bar{\tilde E}`),
          " の原始二項式因子の重複度の総和であり、有限体上の有限計算だけで済む（",
          ref("paper_prop_K"),
          " の (K3)）。可算・決定可能。",
        ],
        [
          math(String.raw`\hat\theta_M`),
          " の計算は整数終結式の ",
          math(String.raw`\ell`),
          " 進付値である（",
          ref("paper_prop_R"),
          " の (R4)）。整数の計算だけである。",
        ],
        [
          math(String.raw`\theta_G^{\max}`),
          " は ",
          math(String.raw`\mathbb{F}_\ell`),
          " 上の有限計算と ",
          ref("paper_prop_R"),
          " の (R3) 型の有効上界で押さえられる。可算。",
        ],
        [
          math(String.raw`c_1`),
          " は ",
          math(String.raw`\mathbb{Z}_{\ge0}`),
          " 上の決定可能な述語の最小元である。可算・決定可能。",
        ],
        [
          math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
          " は非可算だが、本命題の主張はすべて有限レベル ",
          math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{M})`),
          "（有限集合）への還元を経由する。非可算集合の元を個別に扱ってはいない。",
        ],
        [
          "実数体（アルキメデス素点）へ脱出するのは (Q4) ただ 1 箇所である。 その役割は ",
          math(String.raw`\mathcal{B}_M`),
          " の有限個の点の寄与を ",
          math(String.raw`O(\ell^{M})`),
          " で押さえることだけであり、",
          math(String.raw`b`),
          " の値にも ",
          math(String.raw`b`),
          " の決定手続きにも入ってこない。(Q7) の ",
          math(String.raw`C`),
          " に残る ",
          math(String.raw`\log_\ell C_0`),
          " は (Q4) 由来であり、誤差項の係数にしか現れない。",
        ],
      ]),
      paragraph([
        "限界",
      ]),
      list([
        [
          "本命題が与えるのは ",
          math(String.raw`n\ell^{n}`),
          " の係数までである。 ",
          math(String.raw`\ell^{n}`),
          " 以下の係数は誤差項 ",
          math(String.raw`O(\ell^{n})`),
          " の中に入っており、本命題は中身を開けていない。開けるのが ",
          ref("paper_prop_M"),
          " である。",
        ],
        [
          "落とした仮定が保証していたのは「最内側の有限個の点での付値の正確さ」であり、それは ",
          math(String.raw`\ell^{n}`),
          " 以下の係数にだけ効く。",
          math(String.raw`\mathcal{B}_M`),
          " の点での ",
          math(String.raw`\hat\theta_M(P)`),
          " の値そのものは本命題からは出ない。",
        ],
        [
          "新規性は主張しない。 (Q7) は Cuoco–Monsky, *Class numbers in ",
          math(String.raw`\mathbb{Z}_p^d`),
          "-extensions*, Math. Ann. 255 (1981), 235–258 の Definition 1.2 ＋ Theorem 1.7 そのものであり、",
          math(String.raw`b`),
          " は彼らの ",
          math(String.raw`l_0`),
          " に一致する。帰属は ",
          ref("paper_prop_K"),
          " の (K6) が既に書いている。",
        ],
        [
          "射程は、階数 2・仮定 (H)・voltage グラフのラプラシアン行列式型に限る。 ",
          ref("paper_prop_M"),
          " と同じ限定である。",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "証明が外から使う事実を、使う前にすべて述べる。 ",
        ref("paper_prop_K"),
        " の (K2)（",
        math(String.raw`\theta_F(u)=\infty\iff(\chi^{u^\perp}-1)\mid\bar F`),
        " という同値。証明が使うのは ",
        math(String.raw`\ker\bar\psi_u=(\chi^{u^\perp}-1)`),
        " だけなので、",
        math(String.raw`\bar F=\bar{\tilde E}`),
        " に限らず ",
        math(String.raw`0\neq\bar F\in\mathbb{F}_\ell[z^{\pm1},w^{\pm1}]`),
        " 一般で成り立つ）、(K3)(K4)(K6)、",
        ref("paper_prop_J"),
        " の (J1)（有限な点での局所定数性）と (J6)（指数の一次独立性）、",
        ref("paper_prop_R"),
        " の (R3)（有効上界）・(R4)（終結式による付値）・(R5)（",
        math(String.raw`\Sigma_n=\sum_{M=1}^{n}\Theta_M`),
        " と ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)=v_\ell(\kappa(X))-2n+\mu(\ell^{2n}-1)+\Sigma_n`),
        " が仮定なしに成り立つこと）である。さらに非アルキメデス的評価の等号",
        "（最小を達成する項がただ 1 つなら、和の付値はその最小値に等しい）を繰り返し使う。",
      ]),
      paragraph([
        "(Q1) の証明。 ",
        math(String.raw`\bar B\bar G=\bar{\tilde E}`),
        " なので ",
        math(String.raw`\tilde E-BG`),
        " の全係数が ",
        math(String.raw`\ell`),
        " で割れ、",
        math(String.raw`H\in\mathbb{Z}[z^{\pm1},w^{\pm1}]`),
        " である。",
        math(String.raw`\bar G=c\,\chi^{w_0}\bar G_0`),
        " であり、(K4) の分解の一意性から ",
        math(String.raw`\bar G_0`),
        " は ",
        math(String.raw`\chi^{v}-1`),
        " 型の因子を持たない。単項式 ",
        math(String.raw`\chi^{w_0}`),
        " と単元 ",
        math(String.raw`c`),
        " は素元 ",
        math(String.raw`\chi^{v}-1`),
        " で割れないので、",
        math(String.raw`\bar G`),
        " も持たない。",
      ]),
      paragraph([
        "(Q2)(1) の証明。 上に述べた (K2) の一般形を ",
        math(String.raw`\bar F=\bar G`),
        " に適用する。(Q1) より ",
        math(String.raw`\bar G`),
        " には ",
        math(String.raw`\chi^{u^\perp}-1`),
        " 型の因子が無いので、有理点では ",
        math(String.raw`\theta_G<\infty`),
        " である。無理点（",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)\setminus\mathbb{P}^1(\mathbb{Q})`),
        "）については ",
        ref("paper_prop_J"),
        " の (J6) の証明がそのまま ",
        math(String.raw`\bar G`),
        " に適用でき（使うのは指数の一次独立性だけである）、",
        math(String.raw`\theta_G=\infty`),
        " なら ",
        math(String.raw`P`),
        " は有理点である。よって至る所有限である。有界性は ",
        ref("paper_prop_J"),
        " の (J1) の局所定数性と ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " のコンパクト性による。",
      ]),
      paragraph([
        "(Q2)(2) の証明。 ",
        math(String.raw`\Phi^{G}=\sum_m A^{G}_m x^{m}`),
        "、",
        math(String.raw`\pi=\zeta-1`),
        " と置くと ",
        math(String.raw`v_{\mathfrak{l}}\bigl(A^{G}_m\pi^{m}\bigr)=\varphi(\ell^{M})\,v_\ell(A^{G}_m)+m`),
        " である。",
        math(String.raw`m<\theta_G(P)`),
        " では ",
        math(String.raw`\ell\mid A^{G}_m`),
        " なので値は ",
        math(String.raw`\ge\varphi(\ell^{M})>\theta_G^{\max}\ge\theta_G(P)`),
        "、",
        math(String.raw`m=\theta_G(P)`),
        " では値はちょうど ",
        math(String.raw`\theta_G(P)`),
        "、",
        math(String.raw`m>\theta_G(P)`),
        " では値は ",
        math(String.raw`>\theta_G(P)`),
        " である。したがって最小点は ",
        math(String.raw`m=\theta_G(P)`),
        " で一意であり、非アルキメデス的評価の等号から主張を得る。",
        "これが仮定ではなく定理になる理由は 1 行で言える。 深さは全部 (Q1) の第 1 因子の側へ移っており、",
        "残った側の深さはレベルに依らず有界なのに、比較の相手 ",
        math(String.raw`\varphi(\ell^{M})`),
        " はレベルとともにいくらでも大きくなるからである。",
      ]),
      paragraph([
        "(Q3) の証明。 まず第 1 因子の付値を求める。",
        math(String.raw`\chi^{v_i}(\omega_P)=\zeta^{\langle v_i,(a,b)\rangle}`),
        " であり、",
        math(String.raw`\rho:=\rho_i(P)<M`),
        " ならこれは原始 ",
        math(String.raw`\ell^{\,M-\rho}`),
        " 乗根なので ",
        math(String.raw`v_{\mathfrak{l}}\bigl(\chi^{v_i}(\omega_P)-1\bigr)=\varphi(\ell^{M})/\varphi(\ell^{\,M-\rho})=\ell^{\rho}`),
        " である（",
        math(String.raw`\rho_i(P)=M`),
        " なら ",
        math(String.raw`\chi^{v_i}(\omega_P)=1`),
        " で因子が ",
        math(String.raw`0`),
        " になる）。仮定 ",
        math(String.raw`\beta_P+\theta_G^{\max}<\varphi(\ell^{M})`),
        " の下では全ての ",
        math(String.raw`i`),
        " で ",
        math(String.raw`\rho_i(P)<M`),
        " である。実際 ある ",
        math(String.raw`i`),
        " で ",
        math(String.raw`\rho_i(P)=M`),
        " なら ",
        math(String.raw`\beta_P\ge m_i\ell^{M}\ge\ell^{M}>\varphi(\ell^{M})`),
        " となって仮定に反する。よって ",
        math(String.raw`B(\omega_P)\neq0`),
        " かつ ",
        math(String.raw`v_{\mathfrak{l}}\bigl(B(\omega_P)\bigr)=\beta_P`),
        " である。",
      ]),
      paragraph([
        "(Q1) の分解を ",
        math(String.raw`\omega_P`),
        " で評価すると ",
        math(String.raw`\tilde E(\omega_P)=B(\omega_P)G(\omega_P)+\ell\,H(\omega_P)`),
        " である。第 1 項の付値は上の計算と (Q2)(2) から ",
        math(String.raw`\beta_P+\theta_G(P)`),
        "（有限）、第 2 項の付値は ",
        math(String.raw`\varphi(\ell^{M})+v_{\mathfrak{l}}\bigl(H(\omega_P)\bigr)\ge\varphi(\ell^{M})`),
        " である（",
        math(String.raw`H(\omega_P)=0`),
        " なら ",
        math(String.raw`\infty`),
        "）。仮定より ",
        math(String.raw`\beta_P+\theta_G(P)\le\beta_P+\theta_G^{\max}<\varphi(\ell^{M})`),
        " と狭義に小さいので、非アルキメデス的評価により和の付値は小さいほうに一致する。",
        "ここには最小点の一意性の仮定が 1 つも入っていない。 使ったのは (Q1) の分解と (Q2) だけである。",
      ]),
      paragraph([
        "(Q4) の証明。ここが本命題で実数体を使う唯一の箇所である。 ",
        ref("paper_prop_R"),
        " の (R4) より ",
        math(String.raw`\hat\theta_M(P)=v_\ell\bigl(N_{K_M/\mathbb{Q}}(\tilde E(\omega_P))\bigr)`),
        " であり、右辺は ",
        math(String.raw`0`),
        " でない整数 ",
        math(String.raw`N`),
        " の ",
        math(String.raw`\ell`),
        " 進付値である。",
        math(String.raw`N=\prod_\sigma\sigma\bigl(\tilde E(\omega_P)\bigr)`),
        " で、各共役は ",
        math(String.raw`\sum_{(p,q)}c_{pq}\xi^{k_{pq}}`),
        "（",
        math(String.raw`\xi`),
        " は 1 の冪根）の形だから、複素絶対値は ",
        math(String.raw`\le C_0`),
        " である。よって ",
        math(String.raw`|N|\le C_0^{\varphi(\ell^{M})}`),
        " であり、",
        math(String.raw`|N|\ge1`),
        " なので ",
        math(String.raw`v_\ell(N)\le\log_\ell|N|\le\varphi(\ell^{M})\log_\ell C_0`),
        " を得る。複素絶対値を使ったのはこの一段だけであり、非アルキメデス的な議論だけでこの上界を得る道は見つかっていない。",
      ]),
      paragraph([
        "(Q5) の証明。まず ",
        math(String.raw`b=0`),
        " の場合を片付ける。 (K4) の ",
        math(String.raw`m_i`),
        " は ",
        math(String.raw`\ge1`),
        " なので ",
        math(String.raw`b=\sum_i m_i=0`),
        " と ",
        math(String.raw`r=0`),
        " は同値であり、このとき ",
        math(String.raw`B`),
        " は空積 ",
        math(String.raw`1`),
        "、したがって全ての ",
        math(String.raw`P`),
        " で ",
        math(String.raw`\beta_P=0`),
        " である。",
        math(String.raw`P\in\mathcal{B}_M`),
        " は ",
        math(String.raw`\theta_G^{\max}\ge\varphi(\ell^{M})`),
        " を要求するが、仮定 ",
        math(String.raw`\varphi(\ell^{M})\ge2\theta_G^{\max}`),
        " と合わせると ",
        math(String.raw`\theta_G^{\max}\ge2\theta_G^{\max}`),
        " すなわち ",
        math(String.raw`\theta_G^{\max}=0`),
        "、よって ",
        math(String.raw`0\ge\varphi(\ell^{M})\ge1`),
        " で矛盾する。ゆえに ",
        math(String.raw`\mathcal{B}_M=\emptyset`),
        " で、主張は ",
        math(String.raw`0\le r\ell^{c_1}=0`),
        " として成り立つ。",
      ]),
      paragraph([
        "以下 ",
        math(String.raw`b\ge1`),
        " とする。 ",
        math(String.raw`P\in\mathcal{B}_M`),
        " なら ",
        math(String.raw`\beta_P\ge\varphi(\ell^{M})-\theta_G^{\max}\ge\varphi(\ell^{M})/2`),
        " である。",
        math(String.raw`\rho_{\max}:=\max_i\rho_i(P)`),
        " と置く。ある ",
        math(String.raw`i`),
        " で ",
        math(String.raw`\rho_i(P)=M`),
        " なら ",
        math(String.raw`\rho_{\max}=M\ge M-c_1`),
        " で以下は自明なので、全ての ",
        math(String.raw`i`),
        " で ",
        math(String.raw`\rho_i(P)<M`),
        " とする。このとき ",
        math(String.raw`\beta_P\le b\,\ell^{\rho_{\max}}`),
        " なので ",
        math(String.raw`\ell^{\rho_{\max}}\ge\varphi(\ell^{M})/(2b)=\ell^{M-1}(\ell-1)/(2b)`),
        " である。",
        math(String.raw`c_1`),
        " の定義の狭義不等式 ",
        math(String.raw`2b<(\ell-1)\ell^{c_1}`),
        " より ",
        math(String.raw`(\ell-1)/(2b)>\ell^{-c_1}`),
        " だから",
      ]),
      displayMath(
        String.raw`\ell^{\rho_{\max}}\ >\ \ell^{M-1}\cdot\ell^{-c_1}=\ell^{\,M-c_1-1},`,
      ),
      paragraph([
        "すなわち ",
        math(String.raw`\rho_{\max}>M-c_1-1`),
        " であり、",
        math(String.raw`\rho_{\max}`),
        " は整数なので ",
        math(String.raw`\rho_{\max}\ge M-c_1`),
        " である。ここで使ったのは狭義不等式だけであって、対数も切り上げも使っていない。 したがって ",
        math(String.raw`\mathcal{B}_M\subseteq\bigcup_{i=1}^{r}\{P:\rho_i(P)\ge M-c_1\}`),
        " である。",
        math(String.raw`\rho\ge1`),
        " に対し ",
        math(String.raw`\{P:\rho_i(P)\ge\rho\}`),
        " は ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{M})\to\mathbb{P}^1(\mathbb{Z}/\ell^{\rho})`),
        " の 1 点のファイバーで、大きさは ",
        math(String.raw`\ell^{\,M-\rho}`),
        " である。",
        math(String.raw`\rho=M-c_1`),
        " と取れば（",
        math(String.raw`M>c_1`),
        " よりこれは ",
        math(String.raw`\ge1`),
        " である）大きさは ",
        math(String.raw`\ell^{c_1}`),
        " で、和を取って ",
        math(String.raw`\lvert\mathcal{B}_M\rvert\le r\ell^{c_1}`),
        " を得る。",
      ]),
      paragraph([
        "(Q6) の証明。 ",
        math(String.raw`\#\{P:\rho_v(P)\ge\rho\}=\ell^{\,M-\rho}`),
        "（",
        math(String.raw`1\le\rho\le M`),
        "）であり、",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{M})`),
        " の点数は ",
        math(String.raw`(\ell+1)\ell^{M-1}`),
        " である。よって ",
        math(String.raw`\#\{\rho_v=0\}=(\ell+1)\ell^{M-1}-\ell^{M-1}=\ell^{M}`),
        "、",
        math(String.raw`\#\{\rho_v=\rho\}=\varphi(\ell^{\,M-\rho})`),
        "（",
        math(String.raw`1\le\rho\le M-1`),
        "）、",
        math(String.raw`\#\{\rho_v=M\}=1`),
        " である。",
        math(String.raw`\varphi(\ell^{\,M-\rho})\ell^{\rho}=\varphi(\ell^{M})`),
        " が ",
        math(String.raw`1\le\rho\le M-1`),
        " の ",
        math(String.raw`M-1`),
        " 個すべてで成り立つので",
      ]),
      displayMath(
        String.raw`\sum_{P}\ell^{\rho_v(P)}=\ell^{M}\cdot1+(M-1)\varphi(\ell^{M})+1\cdot\ell^{M}
        =(M-1)\varphi(\ell^{M})+2\ell^{M}`,
      ),
      paragraph([
        "を得る。点数を ",
        math(String.raw`\ell^{M}`),
        " と数えると誤る。 射影直線の点数は ",
        math(String.raw`(\ell+1)\ell^{M-1}`),
        " である。",
      ]),
      paragraph([
        "(Q7) の証明。 点を ",
        math(String.raw`\mathcal{B}_M`),
        " とその外に分ける。(Q3) より",
      ]),
      displayMath(
        String.raw`\Theta_M=\sum_{P\notin\mathcal{B}_M}\bigl(\beta_P+\theta_G(P)\bigr)
        +\sum_{P\in\mathcal{B}_M}\hat\theta_M(P)`,
      ),
      paragraph([
        "である。(Q6) を各 ",
        math(String.raw`i`),
        " に使うと ",
        math(String.raw`\sum_{P}\beta_P=\sum_i m_i\bigl((M-1)\varphi(\ell^{M})+2\ell^{M}\bigr)=b(M-1)\varphi(\ell^{M})+2b\ell^{M}`),
        " であり、",
        math(String.raw`0\le\sum_{P\in\mathcal{B}_M}\beta_P\le\lvert\mathcal{B}_M\rvert\,b\,\ell^{M}`),
        " なので",
      ]),
      displayMath(
        String.raw`\Bigl|\sum_{P\notin\mathcal{B}_M}\beta_P-b\,M\,\varphi(\ell^{M})\Bigr|
        \le b\,\varphi(\ell^{M})+2b\ell^{M}+\lvert\mathcal{B}_M\rvert\,b\,\ell^{M}
        \le\bigl(3b+\lvert\mathcal{B}_M\rvert\,b\bigr)\ell^{M}`,
      ),
      paragraph([
        "を得る。残る 2 つは ",
        math(String.raw`0\le\sum_{P\notin\mathcal{B}_M}\theta_G(P)\le\theta_G^{\max}(\ell+1)\ell^{M-1}`),
        " と、(Q4) より ",
        math(String.raw`0\le\sum_{P\in\mathcal{B}_M}\hat\theta_M(P)\le\lvert\mathcal{B}_M\rvert\varphi(\ell^{M})\log_\ell C_0\le\lvert\mathcal{B}_M\rvert\ell^{M}\log_\ell C_0`),
        " である。ここで (Q4) を使うには ",
        math(String.raw`\mathcal{B}_M`),
        " の各点で ",
        math(String.raw`\tilde E(\omega_P)\neq0`),
        " が要る。これは仮定 (H) から従う——(H) は ",
        math(String.raw`X_{\ell^n,\ell^n}`),
        " の連結性すなわち ",
        math(String.raw`\kappa_n\neq0`),
        " を意味し、",
        ref("paper_prop_R"),
        " の (R5) の表示の右辺が有限であることと同値だから、",
        math(String.raw`\mathcal{B}_M`),
        " の点でも ",
        math(String.raw`\tilde E(\omega_P)\neq0`),
        " である。三角不等式で誤差評価を得る。仮定の下で (Q5) が ",
        math(String.raw`\lvert\mathcal{B}_M\rvert\le r\ell^{c_1}`),
        " を与えるので、これで置き換えてよく（",
        math(String.raw`\log_\ell C_0\ge0`),
        " に注意する。",
        math(String.raw`C_0=\sum|c_{pq}|\ge1`),
        " である）、",
        math(String.raw`C`),
        " は ",
        math(String.raw`M`),
        " に依らない定数になる。",
      ]),
      paragraph([
        "漸近形。 ",
        ref("paper_prop_R"),
        " の (R5) より ",
        math(String.raw`\Sigma_n=\sum_{M=1}^{n}\Theta_M`),
        " が仮定なしに成り立つ。上の誤差評価を仮定が満たされるレベル以上で足す（それ未満は有限個なので定数に吸収する）。",
        math(String.raw`\sum_{M=1}^{n}M\varphi(\ell^{M})=\sum_{M=1}^{n}M\bigl(\ell^{M}-\ell^{M-1}\bigr)`),
        " の ",
        math(String.raw`n\ell^{n}`),
        " 係数は ",
        math(String.raw`\frac{\ell}{\ell-1}\cdot\frac{\ell-1}{\ell}=1`),
        " であり、",
        math(String.raw`\sum_{M=1}^{n}\ell^{M}=O(\ell^{n})`),
        " である。よって ",
        math(String.raw`\Sigma_n=b\,n\ell^{n}+O(\ell^{n})`),
        " であり、これを ",
        ref("paper_prop_R"),
        " の (R5) の表示へ代入し ",
        math(String.raw`-2n+v_\ell(\kappa(X))=O(\ell^{n})`),
        " を誤差へ入れて主張を得る。",
      ]),
      paragraph([
        "(Q8) の証明。 ",
        math(String.raw`b=0`),
        " のときの各量の値は (Q5) の証明の第 1 段で見た。",
        math(String.raw`C`),
        " の式へ ",
        math(String.raw`b=0`),
        "、",
        math(String.raw`r=0`),
        " を代入すると ",
        math(String.raw`C=\theta_G^{\max}\frac{\ell+1}{\ell}`),
        " である。実際 ",
        math(String.raw`b=0`),
        " なら ",
        math(String.raw`\mathcal{B}_M=\emptyset`),
        " かつ全点で ",
        math(String.raw`\beta_P=0`),
        " なので ",
        math(String.raw`\Theta_M=\sum_{P}\theta_G(P)\le\theta_G^{\max}(\ell+1)\ell^{M-1}`),
        " であり、(Q7) の上界はこの自明な数え上げとちょうど一致する（",
        math(String.raw`C`),
        " の第 2 項がもともとこの項である）。漸近形は (Q7) で ",
        math(String.raw`b=0`),
        " と置けばよい。",
      ]),
    ],
  },
]);
