/**
 * 論文本体 第 11 章: 一般の塔の閉形式（5 係数すべて）と、係数の情報階層。
 *
 * 命題 K は n ℓ^n の係数 b までを一般の塔で決めたが、ℓ^n・n・定数の係数（c, d, e）は
 * 族でしか出ていなかった（同命題の「限界」の 3 番目）。本章はそこを閉じる。
 *
 * 根拠レポート:
 *   - 命題 M: outputs/reports/cycle21_T3_general_closed_form.md（定理 G1・G2・G3・G4、系 G5・G6）
 *     ただし同 report §5.3 の条件 2 は cycle 23 step 1 で訂正されている
 *     （M ≥ r♯ + max K + 1 → M ≥ r♯ + max K）。本文は**訂正後**を書く。
 *   - 命題 U: outputs/reports/cycle22_T3_coefficients_d_e.md（定理 D1–D6、命題 D1a）
 *
 * 本章の主張はすべて Z・F_ℓ・Q・Z[ζ_{ℓ^k}] の中で閉じる（ℝ を使わない）。捻り段データを
 * 取るために円分体 Q(ζ_{ℓ^k}) へ出るが、これは Q の有限次代数拡大であって可算であり、
 * 計算は Z[x]/Φ_{ℓ^k}(x) の整数演算とノルム（整数）だけで閉じる。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_110_heading_general_closed_form",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/010_general_closed_form.ts", ordinal: 1 },
    title: { text: "一般の塔の閉形式（5 係数すべて）と、係数の情報階層" },
    labels: [],
  },
  {
    id: "paper_111_theorem_general_closed_form",
    kind: "theorem",
    origin: { path: "structured-latex/content/010_general_closed_form.ts", ordinal: 2 },
    title: { text: "命題 M — 一般の塔の閉形式（5 係数すべてが D の係数からの有限計算で決まる）" },
    labels: ["paper_prop_M"],
    habitat: "Qbar",
    verification: [
      "sagemath/check/cycle21_T3_general_closed_form",
      "sagemath/check/cycle21_T3_b_star",
    ],
    statement: [
      paragraph([
        ref("paper_prop_K"),
        " の設定を引き継ぐ。",
        math(String.raw`X`),
        " は有限連結 voltage 多重グラフ、階数は 2（",
        math(String.raw`\Gamma\cong\mathbb{Z}_\ell^2`),
        "）、",
        math(String.raw`D=\det L(z,w)`),
        "、",
        math(String.raw`\mu=v_\ell(\mathrm{content}\,D)`),
        "、",
        math(String.raw`E=\ell^{-\mu}D`),
        "、",
        math(String.raw`\tilde E=z^{r}w^{s}E\in\mathbb{Z}[z,w]`),
        "、",
        math(String.raw`\kappa_n=\kappa(X_{\ell^n,\ell^n})`),
        " とし、仮定 **(H)**（全段連結）を通して置く。",
        ref("paper_prop_J"),
        " の ",
        math(String.raw`\theta`),
        "・",
        math(String.raw`\hat\theta_M`),
        "・",
        math(String.raw`\Theta_M=\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{M})}\hat\theta_M(P)`),
        " と、",
        ref("paper_prop_K"),
        " の ",
        math(String.raw`S_\infty`),
        "・",
        math(String.raw`j^{*}(P_0)`),
        "・",
        math(String.raw`e_{j^*}`),
        " を使う。",
      ]),
      paragraph([
        "**(M1 捻り段データ)** ",
        math(String.raw`P_0\in S_\infty`),
        " に対応する原始整数ベクトルを ",
        math(String.raw`u=(u_1,u_2)`),
        "、",
        math(String.raw`\det(u,\mathbf{e})=1`),
        " なる整数ベクトルを ",
        math(String.raw`\mathbf{e}`),
        "（拡張 Euclid で構成できる）、",
        math(String.raw`\eta`),
        " を原始 ",
        math(String.raw`\ell^{k}`),
        " 乗根、",
        math(String.raw`\mathcal{O}_k=\mathbb{Z}[\eta]`),
        " とする。",
      ]),
      displayMath(
        String.raw`\Phi^{[k]}_{u}(x):=\tilde E\bigl((1+x)^{u_1}\eta^{\mathbf{e}_1},\,(1+x)^{u_2}\eta^{\mathbf{e}_2}\bigr)
        =\sum_{m}A^{[k]}_m\,x^{m}\ \in\mathcal{O}_k[x]`,
      ),
      paragraph([
        "と置き（",
        math(String.raw`(1+x)`),
        " の負冪が出るときは単項式因子を落とす。単元なので付値を変えない）、",
      ]),
      displayMath(
        String.raw`\Lambda_k:=\min_m v_\ell\bigl(A^{[k]}_m\bigr),\qquad
        \theta^\sharp_k:=\min\bigl\{m:v_\ell(A^{[k]}_m)=\Lambda_k\bigr\},\qquad
        m^\sharp_k:=\min\bigl\{m<\theta^\sharp_k:A^{[k]}_m\neq0\bigr\}`,
      ),
      paragraph([
        "と定める（そのような ",
        math(String.raw`m`),
        " が無ければ ",
        math(String.raw`m^\sharp_k=\infty`),
        "）。",
        math(String.raw`v_\ell`),
        " は ",
        math(String.raw`v_\ell(\ell)=1`),
        " に正規化し、",
        math(String.raw`v_\ell(\alpha)=v_\ell\bigl(N_{\mathbb{Q}(\eta)/\mathbb{Q}}(\alpha)\bigr)/\varphi(\ell^{k})`),
        " で計算する（整数の付値ひとつ）。このとき:",
      ]),
      list([
        [
          math(String.raw`\Lambda_k,\theta^\sharp_k,m^\sharp_k`),
          " は深さ ",
          math(String.raw`k`),
          " の層のどの点を取っても同じである（Galois 共役で移り合い、",
          math(String.raw`\ell`),
          " の上の素点は 1 つだから）。",
        ],
        [
          math(String.raw`M\ge2k`),
          " かつ ",
          math(String.raw`\varphi(\ell^{M})>\bigl(\theta^\sharp_k-m^\sharp_k\bigr)\varphi(\ell^{k})`),
          " ならば、深さ ",
          math(String.raw`k`),
          " の層の**全点**で ",
          math(String.raw`\hat\theta_M(P)=\varphi(\ell^{M})\Lambda_k+\theta^\sharp_k`),
          " が成り立つ。",
        ],
        [
          math(String.raw`\varphi(\ell^{k})\Lambda_k\in\mathbb{Z}_{\ge1}`),
          "。とくに上の右辺は整数である。",
        ],
      ]),
      paragraph([
        "ここで層の定義を書く。深さ ",
        math(String.raw`k`),
        " の層とは、レベル ",
        math(String.raw`M`),
        " の点のうち ",
        math(String.raw`P_0`),
        " からの距離がちょうど ",
        math(String.raw`\ell^{-(M-k)}`),
        " のもの、すなわち ",
        math(String.raw`P=\bigl(u+\ell^{M-k}t\,\mathbf{e}\bigr)\bmod\ell^{M}`),
        "（",
        math(String.raw`t\in(\mathbb{Z}/\ell^{k})^{\times}`),
        "、",
        math(String.raw`k\ge1`),
        "）と ",
        math(String.raw`k=0`),
        "（1 点）である。点数は ",
        math(String.raw`k\ge1`),
        " で ",
        math(String.raw`\varphi(\ell^{k})`),
        "、",
        math(String.raw`k=0`),
        " で ",
        math(String.raw`1`),
        "。",
        "**(M1) の内容は、基点の近傍を見ることが 1 径数部分群を 1 の冪根で捻ることに等しく、" +
          "係数環を整数から円分整数へ広げると最小点の同点が解ける、ということである。**",
        " 捻る根は ",
        math(String.raw`\eta`),
        "、広げた係数環は ",
        math(String.raw`\mathcal{O}_k`),
        " であり、同点が起きるのは ",
        ref("paper_prop_J"),
        " の最小化を ",
        math(String.raw`\mathbb{Z}`),
        " 係数のまま行ったときである。",
      ]),
      paragraph([
        "**(M2 飽和深度の明示上界)** ",
        math(String.raw`K(P_0):=\max\bigl\{k\ge0:\ j^{*}\ell\ge(\ell-1)\ell^{k}\bigr\}`),
        " と置く（",
        math(String.raw`j^{*}\ge1`),
        " より常に定義され、",
        math(String.raw`K\ge0`),
        "）。深さ ",
        math(String.raw`k>K`),
        " の層では、",
        math(String.raw`M\ge\max\bigl(R'+k,\ k+\lceil\log_\ell(e_{j^*}+1)\rceil\bigr)`),
        " のとき",
      ]),
      displayMath(String.raw`\hat\theta_M(P)=\theta(P)=e_{j^*}+j^{*}\ell^{\,M-k},`),
      paragraph(["すなわち"]),
      displayMath(
        String.raw`\Lambda_k=\frac{j^{*}}{\varphi(\ell^{k})},\qquad\theta^\sharp_k=e_{j^*}`,
      ),
      paragraph([
        "である（",
        math(String.raw`R'(P_0)`),
        " は ",
        ref("paper_prop_K"),
        " (K5) の ",
        math(String.raw`r_0`),
        " 以上で ",
        math(String.raw`\mathrm{argmin}`),
        " が ",
        math(String.raw`j^{*}`),
        " で一意になる最小のレベル）。とくに ",
        math(String.raw`K=0`),
        " と ",
        math(String.raw`j^{*}\le\ell-2`),
        " は同値であり、",
        math(String.raw`\ell=2`),
        " では ",
        math(String.raw`j^{*}\ge1=\ell-1`),
        " なので必ず ",
        math(String.raw`K\ge1`),
        " である。",
        "**すなわち、飽和は 2 進の塔に固有の現象ではない。これがその正体である。** ",
        ref("paper_prop_G_ell2"),
        " が ",
        math(String.raw`\ell=2`),
        " 固有として挙げた飽和は、",
        math(String.raw`\ell-1`),
        " が最小であることの帰結にすぎない。",
        math(String.raw`\ell`),
        " が奇でも ",
        math(String.raw`j^{*}\ge\ell-1`),
        " の塔では同じことが起きる。",
      ]),
      paragraph([
        "**(M3 レベルごとの和の閉形式)** ",
        math(String.raw`r^\sharp:=\max\bigl(r_0,\ \max_{P_0}R'(P_0)\bigr)`),
        "、",
        math(String.raw`U:=\mathbb{P}^1(\mathbb{Z}_\ell)\setminus\bigcup_{P_0\in S_\infty}B(P_0,\ell^{-r^\sharp})`),
        " と置く。",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`U`),
        " 上有界で、その上界は ",
        math(String.raw`D`),
        " の係数から計算できる。",
        math(String.raw`\theta^{\max}_U`),
        " を最大値、",
        math(String.raw`L\ge r^\sharp`),
        " を ",
        math(String.raw`\ell^{L}\ge\theta^{\max}_U`),
        " なるレベルとして",
      ]),
      displayMath(
        String.raw`A_{\mathrm{gen}}:=\frac{1}{\ell^{L}}\sum_{P\in U\cap\mathbb{P}^1(\mathbb{Z}/\ell^{L})}\theta(P)\ \in\mathbb{Q}`,
      ),
      paragraph([
        "と置く（",
        math(String.raw`L`),
        " の取り方に依らない。",
        math(String.raw`L\to L+1`),
        " でファイバーが一様に ",
        math(String.raw`\ell`),
        " 個に分かれるから）。このとき、下の (M5) が与える明示的な ",
        math(String.raw`M^{*}`),
        " が存在して、",
        math(String.raw`M\ge M^{*}`),
        " で",
      ]),
      displayMath(String.raw`\Theta_M=\alpha\,M\ell^{M}+\beta\,\ell^{M}+\gamma`),
      paragraph([
        "が成り立つ。ここで",
      ]),
      displayMath(String.raw`\alpha=\frac{\ell-1}{\ell}\sum_{P_0\in S_\infty}j^{*}(P_0),`),
      displayMath(
        String.raw`\beta=A_{\mathrm{gen}}+\sum_{P_0\in S_\infty}\Bigl[\frac{e_{j^*}}{\ell^{\,r^\sharp}}
        -\frac{(\ell-1)\,j^{*}\,(K+r^\sharp)}{\ell}
        +\frac{\ell-1}{\ell}\Bigl(\Lambda_0+\sum_{k=1}^{K}\varphi(\ell^{k})\Lambda_k\Bigr)\Bigr],`,
      ),
      displayMath(
        String.raw`\gamma=\sum_{P_0\in S_\infty}\Bigl[-e_{j^*}\,\ell^{K}
        +\theta^\sharp_0+\sum_{k=1}^{K}\varphi(\ell^{k})\,\theta^\sharp_k\Bigr].`,
      ),
      paragraph([
        "**(M4 5 係数)** したがって ",
        math(String.raw`n\ge M^{*}-1`),
        " で ",
        ref("paper_prop_J"),
        " (J4) の 5 係数形 ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)=a\,\ell^{2n}+b\,n\ell^{n}+c\,\ell^{n}+d\,n+e`),
        " が成り立ち、",
      ]),
      displayMath(
        String.raw`a=\mu,\qquad b=\frac{\ell}{\ell-1}\,\alpha=\sum_{P_0\in S_\infty}j^{*}(P_0),\qquad
        c=\frac{\ell}{\ell-1}\,\beta-\frac{\ell}{(\ell-1)^2}\,\alpha,\qquad d=\gamma-2,`,
      ),
      displayMath(
        String.raw`e=v_\ell(\kappa(X))-\mu
        +\Bigl[\sum_{M=1}^{M^{*}-1}\Theta_M-\alpha\,\mathcal{S}_1(M^{*}\!-\!1)-\beta\,\mathcal{S}_0(M^{*}\!-\!1)-\gamma(M^{*}\!-\!1)\Bigr]
        +\frac{\ell}{(\ell-1)^2}\alpha-\frac{\ell}{\ell-1}\beta,`,
      ),
      paragraph([
        "ここで ",
        math(String.raw`\mathcal{S}_1(N)=\sum_{M=1}^{N}M\ell^{M}`),
        "、",
        math(String.raw`\mathcal{S}_0(N)=\sum_{M=1}^{N}\ell^{M}`),
        " である。",
        "**すなわち 5 係数すべてが、スペクトル多項式の係数からの有限計算で決まる。** ",
        "とくに ",
        math(String.raw`b=\sum j^{*}`),
        " は ",
        ref("paper_prop_J"),
        " (J4) が残していた仮定（",
        math(String.raw`\hat\theta`),
        " を与える最小点の一意性）**なしに**従う。飽和層 (M1) と非飽和層 (M2) の両方で一意性を",
        "仮定せずに**証明して**いるからである。",
      ]),
      paragraph([
        "**(M5 閉形式が成り立ち始めるレベルの明示形)** 次をすべて満たす最小の ",
        math(String.raw`M`),
        " を ",
        math(String.raw`M^{*}`),
        " と取ればよい。いずれも ",
        math(String.raw`D`),
        " の係数からの有限計算である。",
      ]),
      list([
        [
          math(String.raw`M\ge L`),
          "（",
          math(String.raw`A_{\mathrm{gen}}`),
          " が経由するレベル）。",
        ],
        [
          math(String.raw`M\ge r^\sharp+\max_{P_0}K(P_0)`),
          "。**この条件は「非飽和層の閉形式が成り立つこと」であって「非飽和層が空でないこと」ではない。** ",
          math(String.raw`M=r^\sharp+\max K`),
          " では非飽和層は空だが、和 ",
          math(String.raw`\sum_{s=K+1}^{M-r^\sharp}\varphi(\ell^{s})=\ell^{M-r^\sharp}-\ell^{K}`),
          " は両辺 ",
          math(String.raw`0`),
          " で成り立つので、閉形式はそのまま正しい。破れるのは ",
          math(String.raw`M<r^\sharp+\max K`),
          " からである。",
        ],
        [
          math(String.raw`\varphi(\ell^{M})>\theta^{\max}_U-2`),
          "（一般領域 ",
          math(String.raw`U`),
          " の分）。",
        ],
        [
          "各 ",
          math(String.raw`P_0`),
          "、各 ",
          math(String.raw`k\le K`),
          " で ",
          math(String.raw`M\ge2k`),
          " かつ ",
          math(String.raw`\varphi(\ell^{M})>(\theta^\sharp_k-m^\sharp_k)\varphi(\ell^{k})`),
          "（(M1)）。",
        ],
        [
          "各 ",
          math(String.raw`P_0`),
          " で ",
          math(String.raw`e_{j^*}+j^{*}\ell^{\,M-K-1}-2<\varphi(\ell^{M})`),
          "（(M2) の ",
          math(String.raw`k=K+1`),
          " の最外層。",
          math(String.raw`M=r^\sharp+\max K`),
          " ではこの層が無いので条件は空である）。",
        ],
      ]),
      paragraph([
        "**(M6 無限消滅深度の点が無い場合)** ",
        math(String.raw`S_\infty=\emptyset`),
        " かどうかは ",
        ref("paper_prop_K"),
        " (K3) で判定できる。この場合は ",
        math(String.raw`\alpha=\gamma=0`),
        "、",
        math(String.raw`\beta=A_{\mathrm{gen}}`),
        " で",
      ]),
      displayMath(
        String.raw`a=\mu,\quad b=0,\quad c=\frac{\ell}{\ell-1}A_{\mathrm{gen}}=\frac{\Theta_L}{\varphi(\ell^{L})},\quad d=-2,`,
      ),
      displayMath(
        String.raw`e=v_\ell(\kappa(X))-\mu+\sum_{M=1}^{M^{*}-1}\Theta_M
        -A_{\mathrm{gen}}\Bigl(\mathcal{S}_0(M^{*}\!-\!1)+\frac{\ell}{\ell-1}\Bigr).`,
      ),
      paragraph([
        "**限界（主張の一部として述べる）**",
      ]),
      list([
        [
          "**射程は、階数 2・仮定 (H)・voltage グラフのラプラシアン行列式型に限る。** 記号で書けば ",
          math(String.raw`d=2`),
          "（",
          math(String.raw`\Gamma\cong\mathbb{Z}_\ell^2`),
          "）であり、対象は ",
          math(String.raw`\det L`),
          " の形のものだけである。(M1) の捻りの考え方は階数 3 以上でも意味を持つが、",
          math(String.raw`\mathbb{P}^{d-1}`),
          " 上の層別が ",
          math(String.raw`\mathbb{P}^1`),
          " ほど単純でないため、そのままでは移らない。",
        ],
        [
          math(String.raw`M^{*}`),
          " は十分条件であって**鋭さを主張しない**。実測では多くの塔で ",
          math(String.raw`M^{*}`),
          " より小さい ",
          math(String.raw`M`),
          " から閉形式が成り立つ。したがって ",
          math(String.raw`n<M^{*}-1`),
          " での一致・不一致を本命題の検証に使ってはならない。",
        ],
        [
          math(String.raw`(\Lambda_k,\theta^\sharp_k)`),
          " を ",
          math(String.raw`\bar{\tilde E}\in\mathbb{F}_\ell[z,w]`),
          " の組合せ的なデータから読む式は**与えていない**。",
          ref("paper_prop_U"),
          " が示すとおり、それは原理的に不可能である。与えたのは「",
          math(String.raw`D`),
          " の係数からの有限計算で書く」という形である。",
        ],
        [
          math(String.raw`a\le\mu`),
          " という一般論は Cuoco–Monsky からの借り物のままである（本命題の枠内では ",
          math(String.raw`a=\mu`),
          " は ",
          ref("paper_prop_J"),
          " の展開から直接出るので、借りているのは一般論の側だけである）。",
        ],
        [
          "**新規性は主張しない。** ",
          math(String.raw`a=\mu`),
          " と ",
          math(String.raw`b=\sum j^{*}`),
          " は Cuoco–Monsky, *Class numbers in ",
          math(String.raw`\mathbb{Z}_p^d`),
          "-extensions*, Math. Ann. **255** (1981), 235–258 の Definition 1.1・1.2 と Theorem 1.7 であり、",
          ref("paper_prop_K"),
          " (K6) が既に帰属を書いている。",
          math(String.raw`c`),
          " については、Monsky, *Fine estimates for the growth of ",
          math(String.raw`e_n`),
          " in ",
          math(String.raw`\mathbb{Z}_p^d`),
          "-extensions* (1989) が同じ位置の定数 ",
          math(String.raw`\alpha^{*}`),
          " について「there is no easy description of ",
          math(String.raw`\alpha^{*}`),
          "」と書き、存在と（",
          math(String.raw`d=2`),
          " での）有理性しか示していない（Introduction, p.309；原文を取得して確認した）。",
          "本命題はその位置の量を上の限定された設定で明示するが、**文献調査は網羅的でない**。",
          "とくに (M1) の操作（",
          math(String.raw`\ell^{k}`),
          " 乗根の指標で捻って分解し各成分の付値を取る）は岩澤理論では標準的であり、",
          math(String.raw`\det L`),
          " 型のような具体的な対象に対して同じ計算が既になされている可能性は高い。",
        ],
        [
          math(String.raw`d`),
          "（",
          math(String.raw`n`),
          " の係数）と ",
          math(String.raw`e`),
          "（定数項）は、そもそも Monsky の主張の外側にある（",
          math(String.raw`d=2`),
          " では同論文の誤差項が ",
          math(String.raw`O(n)`),
          " なので、そこは開いていない）。",
        ],
      ]),
    ],
  },
  {
    id: "paper_112_theorem_coefficient_layers",
    kind: "theorem",
    origin: { path: "structured-latex/content/010_general_closed_form.ts", ordinal: 3 },
    title: { text: "命題 U — 係数の情報階層（どの追加情報が要るか）と、有限精度では決まらないこと" },
    labels: ["paper_prop_U"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle22_T3_coefficients_d_e"],
    statement: [
      paragraph([
        ref("paper_prop_M"),
        " の設定と記号を引き継ぐ。各 ",
        math(String.raw`P_0\in S_\infty`),
        " に対し",
      ]),
      displayMath(
        String.raw`\mathcal{L}(P_0):=\Lambda_0+\sum_{k=1}^{K}\varphi(\ell^{k})\,\Lambda_k,
        \qquad
        \mathcal{T}(P_0):=\theta^\sharp_0+\sum_{k=1}^{K}\varphi(\ell^{k})\,\theta^\sharp_k`,
      ),
      paragraph([
        "と置く。",
        ref("paper_prop_M"),
        " (M1) の 3 番目より ",
        math(String.raw`\varphi(\ell^{k})\Lambda_k\in\mathbb{Z}_{\ge1}`),
        "、また ",
        math(String.raw`\theta^\sharp_k\in\mathbb{Z}_{\ge0}`),
        " なので、",
        math(String.raw`\mathcal{L}(P_0)`),
        " と ",
        math(String.raw`\mathcal{T}(P_0)`),
        " はどちらも非負整数である。",
      ]),
      paragraph([
        "**(U1 付値側と位置側の分業)**",
      ]),
      displayMath(
        String.raw`d=\sum_{P_0\in S_\infty}\Bigl(\mathcal{T}(P_0)-e_{j^*}(P_0)\,\ell^{K(P_0)}\Bigr)-2,`,
      ),
      displayMath(
        String.raw`c=\frac{\ell}{\ell-1}A_{\mathrm{gen}}
        +\sum_{P_0\in S_\infty}\Bigl[\frac{e_{j^*}\,\ell^{\,1-r^\sharp}}{\ell-1}
        -j^{*}\Bigl(K+r^\sharp+\frac{1}{\ell-1}\Bigr)+\mathcal{L}(P_0)\Bigr].`,
      ),
      paragraph([
        "したがって、捻り段データの**付値側** ",
        math(String.raw`\Lambda_k`),
        " は ",
        math(String.raw`c`),
        " にだけ、**位置側** ",
        math(String.raw`\theta^\sharp_k`),
        " は ",
        math(String.raw`d`),
        " にだけ現れる。とくに ",
        math(String.raw`d`),
        " は ",
        math(String.raw`S_\infty`),
        " の各点の局所量 ",
        math(String.raw`(\mathcal{T},e_{j^*},K)`),
        " だけで決まり、大域平均 ",
        math(String.raw`A_{\mathrm{gen}}`),
        " も低レベルの過渡も ",
        math(String.raw`v_\ell(\kappa(X))`),
        " も使わない。よって ",
        math(String.raw`d`),
        " は**常に整数**である（",
        math(String.raw`c`),
        " と ",
        math(String.raw`e`),
        " は ",
        math(String.raw`13/3`),
        " のような非整数の有理数になりうる）。",
        math(String.raw`S_\infty=\emptyset`),
        " なら和が空で ",
        math(String.raw`d=-2`),
        "（",
        ref("paper_prop_M"),
        " (M6) と整合）。",
        "**すなわち「次数が下がるほど難しくなる」という素朴な順序は成り立たない。** 難しさの順序は",
        math(String.raw`a,b\ \prec\ d\ \prec\ c\ \prec\ e`),
        "である。",
      ]),
      paragraph([
        "**(U1a 飽和深度を大きめに取ってもよい)** ",
        math(String.raw`K'\ge K(P_0)`),
        " を任意に取り、上の和を ",
        math(String.raw`k\le K'`),
        " まで伸ばし ",
        math(String.raw`K`),
        " を ",
        math(String.raw`K'`),
        " に置き換えても ",
        math(String.raw`c,d`),
        " は変わらない。実際 ",
        math(String.raw`K\to K+1`),
        " では深さ ",
        math(String.raw`K+1`),
        " の層が ",
        ref("paper_prop_M"),
        " (M2) より非飽和なので ",
        math(String.raw`\Lambda_{K+1}=j^{*}/\varphi(\ell^{K+1})`),
        "、",
        math(String.raw`\theta^\sharp_{K+1}=e_{j^*}`),
        " であり、",
        math(String.raw`\mathcal{T}`),
        " の増分 ",
        math(String.raw`\varphi(\ell^{K+1})e_{j^*}`),
        " と ",
        math(String.raw`-e_{j^*}\ell^{K}\to-e_{j^*}\ell^{K+1}`),
        " の変化がちょうど相殺し、同様に ",
        math(String.raw`\mathcal{L}`),
        " の増分 ",
        math(String.raw`j^{*}`),
        " と ",
        math(String.raw`-j^{*}(K+r^\sharp+\frac{1}{\ell-1})`),
        " の変化が相殺する。あとは帰納法である。",
      ]),
      paragraph([
        "**(U2 定数項の分解)** ",
        math(String.raw`\Theta^{\mathrm{as}}_M:=\alpha M\ell^{M}+\beta\ell^{M}+\gamma`),
        " と置き、**過渡欠損**を",
      ]),
      displayMath(String.raw`T_{\mathrm{def}}:=\sum_{M\ge1}\bigl(\Theta_M-\Theta^{\mathrm{as}}_M\bigr)`),
      paragraph([
        "と定める。",
        ref("paper_prop_M"),
        " (M3) より ",
        math(String.raw`M\ge M^{*}`),
        " の項は ",
        math(String.raw`0`),
        " なのでこれは**有限和**であり、",
        math(String.raw`M^{*}`),
        " の取り方に依らない（",
        math(String.raw`M^{*}`),
        " 以上のどこで打ち切っても同じ値）。このとき",
      ]),
      displayMath(String.raw`e=v_\ell(\kappa(X))-a-c+T_{\mathrm{def}},`),
      paragraph(["したがって"]),
      displayMath(String.raw`c+e=v_\ell(\kappa(X))-a+T_{\mathrm{def}}.`),
      paragraph([
        "とくに ",
        math(String.raw`T_{\mathrm{def}}=0`),
        " と「閉形式が ",
        math(String.raw`n\ge0`),
        " から成り立つ」は同値である。",
        ref("paper_prop_M"),
        " (M4) の ",
        math(String.raw`e`),
        " の式の角括弧の正体がこの ",
        math(String.raw`T_{\mathrm{def}}`),
        " である。",
        math(String.raw`c`),
        " と ",
        math(String.raw`e`),
        " の**和**のほうが、それぞれより情報として浅い。",
      ]),
      paragraph([
        "**(U3 情報階層は 3 層である)** 以上より 5 係数は次の 3 層に分かれる。第 1 層（",
        math(String.raw`\bmod\ \ell`),
        "）は ",
        math(String.raw`\bar{\tilde E}`),
        " から読める量（content の付値、二項式因子の重複度、",
        math(String.raw`S_\infty`),
        "、",
        math(String.raw`j^{*}`),
        "、",
        math(String.raw`e_j`),
        "、",
        math(String.raw`K`),
        "、",
        math(String.raw`r^\sharp`),
        "、",
        math(String.raw`A_{\mathrm{gen}}`),
        "）であり、ここから ",
        math(String.raw`a`),
        " と ",
        math(String.raw`b`),
        " が決まる。第 2 層は第 1 層に捻り段データ ",
        math(String.raw`(\Lambda_k,\theta^\sharp_k)`),
        " を足したもので、ここから ",
        math(String.raw`c`),
        " と ",
        math(String.raw`d`),
        " が決まる。第 3 層は第 2 層に ",
        math(String.raw`v_\ell(\kappa(X))`),
        " と ",
        math(String.raw`T_{\mathrm{def}}`),
        " を足したもので、",
        math(String.raw`e`),
        " だけがこれを要する。",
        "**これが「どの追加情報が要るか」への答えである。** 以下 (U4)–(U6) は、この階層が本当に",
        "縮まないこと、すなわち第 2 層が第 1 層に還元されず、",
        math(String.raw`\ell`),
        " 進の固定桁数にも還元されないことを示す。",
      ]),
      paragraph([
        "**(U4 剰余体だけでは第 2 層は決まらない)** 切れ目は ",
        math(String.raw`b`),
        " と ",
        math(String.raw`(c,d,e)`),
        " の間にある。以下 ",
        math(String.raw`\ell=2`),
        "、",
        math(String.raw`p`),
        " を奇数とし、",
        math(String.raw`X_p`),
        " を 1 頂点 bouquet でループの voltage が ",
        math(String.raw`(1,0)`),
        " を ",
        math(String.raw`p`),
        " 本、",
        math(String.raw`(0,1)`),
        " を 1 本のものとする。このとき ",
        math(String.raw`\mu=0`),
        " であり ",
        math(String.raw`\bar{\tilde E}=z^2w+zw^2+z+w\in\mathbb{F}_2[z,w]`),
        " は奇数 ",
        math(String.raw`p`),
        " に依らない。したがって ",
        math(String.raw`S_\infty=\{(1{:}1),(1{:}-1)\}`),
        "、各点で ",
        math(String.raw`j^{*}=1`),
        "、",
        math(String.raw`e_{j^*}=2`),
        "、",
        math(String.raw`K=1`),
        "、",
        math(String.raw`r^\sharp=2`),
        "、",
        math(String.raw`A_{\mathrm{gen}}=2`),
        " も依らない。ところが各 ",
        math(String.raw`P_0\in S_\infty`),
        " で",
      ]),
      displayMath(
        String.raw`\Lambda_0=v_2(p+1),\quad\theta^\sharp_0=2,\qquad
        \Lambda_1=\min\bigl(2,\,v_2(p-1)\bigr),\qquad
        \theta^\sharp_1=\begin{cases}0&(p\equiv1\bmod4)\\ 2&(p\equiv3\bmod4)\end{cases}`,
      ),
      paragraph([
        "であり、(U1) より ",
        math(String.raw`d=2\theta^\sharp_1-6`),
        "、",
        math(String.raw`c=2\mathcal{L}-2`),
        "（",
        math(String.raw`\mathcal{L}=v_2(p+1)+\min(2,v_2(p-1))`),
        "）である。とくに ",
        math(String.raw`p=1`),
        " と ",
        math(String.raw`p=3`),
        " は ",
        math(String.raw`\bar{\tilde E}`),
        " も ",
        math(String.raw`\mu`),
        " も等しいのに",
      ]),
      displayMath(String.raw`(a,b,c,d,e)=(0,2,4,-6,-1)`),
      paragraph(["と"]),
      displayMath(String.raw`(a,b,c,d,e)=(0,2,4,-2,-4)`),
      paragraph([
        "で、",
        math(String.raw`d`),
        " と ",
        math(String.raw`e`),
        " が違う。**したがって、第 2 層の 3 係数はいずれも剰余体上の還元の関数ではない。** 記号で書けば ",
        math(String.raw`c,d,e`),
        " のいずれも ",
        math(String.raw`\bar{\tilde E}`),
        " の関数ではないということである。ここで反例に使ったのは**実在の voltage グラフ 2 本**であって ",
        math(String.raw`\tilde E`),
        " への人工的な摂動ではないので、「グラフに限れば ",
        math(String.raw`\bar{\tilde E}`),
        " から読める式があるかもしれない」という逃げ道も塞がっている。",
        "なおこの対では ",
        math(String.raw`\mathcal{L}`),
        " が偶然一致して ",
        math(String.raw`c`),
        " が同じになる。",
        math(String.raw`c`),
        " の反例と ",
        math(String.raw`d`),
        " の反例は独立に要る、ということである。",
      ]),
      paragraph([
        "**(U5 どんな固定精度でも足りない)** ",
        math(String.raw`\ell=2`),
        " とする。",
      ]),
      list([
        [
          "（",
          math(String.raw`c`),
          " の側）",
          math(String.raw`X_t`),
          " を 1 頂点 bouquet でループの voltage が ",
          math(String.raw`(1,0)`),
          "、",
          math(String.raw`(0,1)`),
          " 各 1 本と ",
          math(String.raw`(1,-1)`),
          " を ",
          math(String.raw`t`),
          " 本のものとする。任意の ",
          math(String.raw`N\ge2`),
          " に対し ",
          math(String.raw`t=2^{N+1}-1`),
          " と ",
          math(String.raw`t'=3\cdot2^{N}-1`),
          " は ",
          math(String.raw`\tilde E_{X_t}\equiv\tilde E_{X_{t'}}\pmod{2^{N}}`),
          "（したがって ",
          math(String.raw`\bar{\tilde E}`),
          " も ",
          math(String.raw`\mu`),
          " も同じ）でありながら ",
          math(String.raw`c`),
          " が ",
          math(String.raw`3`),
          " だけ違う。このとき ",
          math(String.raw`\theta^\sharp`),
          " は 4 箇所とも不変なので ",
          math(String.raw`d`),
          " は変わらない。",
        ],
        [
          "（",
          math(String.raw`d`),
          " の側）",
          math(String.raw`Y_{p,q,t}`),
          " を 1 頂点 bouquet でループの voltage が ",
          math(String.raw`(1,0)`),
          " を ",
          math(String.raw`p`),
          " 本、",
          math(String.raw`(0,1)`),
          " を ",
          math(String.raw`q`),
          " 本、",
          math(String.raw`(1,-1)`),
          " を ",
          math(String.raw`t`),
          " 本のものとする。任意の ",
          math(String.raw`N\ge1`),
          " に対し ",
          math(String.raw`t=1`),
          "、",
          math(String.raw`q=1+2^{N+2}`),
          "、",
          math(String.raw`p=2^{N+1}-1`),
          " と ",
          math(String.raw`p'=p+2^{N}`),
          " は ",
          math(String.raw`\tilde E_{Y_{p,q,t}}\equiv\tilde E_{Y_{p',q,t}}\pmod{2^{N}}`),
          " で、",
          math(String.raw`P_0=(0{:}1)`),
          " の ",
          math(String.raw`\Lambda_1`),
          " は ",
          math(String.raw`N+2`),
          " のまま**不変**なのに ",
          math(String.raw`\theta^\sharp_1`),
          " が ",
          math(String.raw`2`),
          " から ",
          math(String.raw`0`),
          " へ変わり、",
          math(String.raw`d`),
          " が ",
          math(String.raw`2`),
          " だけ違う。",
        ],
      ]),
      paragraph([
        "**したがって、剰余環へ落とす桁数をどれだけ固定しても、そこから第 2 層の係数を読む式は存在しない。** ",
        "落とす先を ",
        math(String.raw`\tilde E\bmod\ell^{N}`),
        " と書けば、",
        math(String.raw`c`),
        " を読む式も ",
        math(String.raw`d`),
        " を読む式も、どんな固定した ",
        math(String.raw`N`),
        " に対しても存在しないということである。しかも位置側（",
        math(String.raw`d`),
        "）の障害は付値側（",
        math(String.raw`c`),
        "）の障害の系ではない。2 番目の族では ",
        math(String.raw`\Lambda_1`),
        " が不変のまま ",
        math(String.raw`\theta^\sharp_1`),
        " だけが動いているからである。",
      ]),
      paragraph([
        "**(U6 逆向き — 精度が足りる条件)** 逆に ",
        math(String.raw`N\in\mathbb{Z}_{\ge1}`),
        " が",
      ]),
      displayMath(
        String.raw`N>\max_{P_0\in S_\infty}\ \max_{0\le k\le K(P_0)}\Lambda_k(P_0)`,
      ),
      paragraph([
        "を満たすならば、",
        math(String.raw`\tilde E\bmod\ell^{N}`),
        " が ",
        math(String.raw`(\Lambda_k,\theta^\sharp_k)_{k\le K}`),
        " を、したがって ",
        math(String.raw`c`),
        " と ",
        math(String.raw`d`),
        " を決める。実際 ",
        math(String.raw`\tilde E'=\tilde E+\ell^{N}h`),
        " と置くと ",
        math(String.raw`\Phi^{[k]}`),
        " は係数の ",
        math(String.raw`\mathcal{O}_k`),
        " 係数線形式なので ",
        math(String.raw`A'^{[k]}_m=A^{[k]}_m+\ell^{N}\beta_m`),
        " となり、**切り捨て付きの付値列** ",
        math(String.raw`\bigl(\min(v_\ell(A^{[k]}_m),N)\bigr)_m`),
        " が ",
        math(String.raw`\tilde E\bmod\ell^{N}`),
        " で決まる。上の条件より ",
        math(String.raw`\Lambda_k<N`),
        " なので、",
        math(String.raw`\Lambda_k`),
        " とその最小を最初に達成する添字 ",
        math(String.raw`\theta^\sharp_k`),
        " はこの列から読める。",
        "この条件は一見自己言及だが実用上は循環しない: 与えられた ",
        math(String.raw`N`),
        " で切り捨て付き付値列を計算し、最小値が ",
        math(String.raw`N`),
        " 未満であれば、その ",
        math(String.raw`N`),
        " が十分だったことがその計算自体から確認できる。",
        "**必要精度は各塔について有限かつ計算可能だが、塔を渡ると上に有界でない**（それが (U5)）。",
      ]),
      paragraph([
        "**限界（主張の一部として述べる）**",
      ]),
      list([
        [
          "**第 3 層が余計でないこと**（第 2 層と ",
          math(String.raw`v_\ell(\kappa(X))`),
          " をすべて知っても ",
          math(String.raw`e`),
          " が決まらないこと）は、そのような塔の組が存在するという**存在主張**であり、",
          "母集団の走査で見つけた実例で支えている（存在を示すには例で足りる）。一般の証明ではない。",
        ],
        [
          "(U6) は ",
          math(String.raw`c,d`),
          " についてのものである。",
          math(String.raw`e`),
          " には ",
          math(String.raw`T_{\mathrm{def}}`),
          " が入り、そこには低レベルの ",
          math(String.raw`\Theta_M`),
          " すなわちいくらでも深い付値が現れるので、",
          "**定数項の必要精度の明示形は与えていない。**",
        ],
        [
          "**射程は、階数 2・仮定 (H)・voltage グラフのラプラシアン行列式型に限る。** ",
          ref("paper_prop_M"),
          " と同じ限定であり、記号で書けば ",
          math(String.raw`d=2`),
          " かつ対象は ",
          math(String.raw`\det L`),
          " の形のものだけである。",
        ],
        [
          "**新規性は主張しない。** ",
          math(String.raw`\ell^{n}`),
          " 以下の係数が ",
          math(String.raw`\bmod\ \ell`),
          " では決まらないこと（",
          math(String.raw`\mu,\lambda`),
          " の下の項がより深い情報を要すること）は岩澤理論では標準的な認識である。",
          "本命題が足しているのは、その「より深い情報」が ",
          math(String.raw`\mathbb{Z}[\zeta_{\ell^{k}}]`),
          " 上の段データで**尽きる**という有限性と、",
          math(String.raw`\ell`),
          " 進の固定桁数では足りないことを反例で確定させた点である。",
        ],
      ]),
    ],
  },
]);
