/**
 * 論文本体 第 11 章: 一般の塔の閉形式（5 係数すべて）と、係数の情報階層。
 *
 * 命題 K は n ℓ^n の係数 b までを一般の塔で決めたが、ℓ^n・n・定数の係数（c, d, e）は
 * 族でしか出ていなかった（同命題の「限界」の 3 番目）。本章はそこを閉じる。
 *
 * 根拠レポート（**cycle 24 step 1 の訂正後の版**を正本とする）:
 *   - 命題 M: outputs/reports/cycle21_T3_general_closed_form.md（定理 G1・G2・G3・G4、系 G5・G6）
 *   - 命題 U: outputs/reports/cycle22_T3_coefficients_d_e.md（定理 D1–D6、命題 D1a）
 *
 * 本文へ運ぶにあたって、cycle 24 step 1 の訂正を**訂正後の形で**書いている:
 *   - 定理 G4 §5.3 の条件 2 は M ≥ r♯ + max K（初稿の +1 は 1 つ強すぎた）。→ (M5) の 2 番目
 *   - 定理 D2 の最後の一文（初稿は偽）は 3 分岐に直っている。→ (U2)
 *   - 定理 D3・D5 の min は A_m ≠ 0 の m に限る規約（v_ℓ(0) = +∞）。→ (M1)・(U4)・(U5)
 * さらに cycle 24 step 5 の Lean 検算が「読み方が本文に無い」と指摘した定理 G2 の条件 (3.2) を、
 * m♯_k = ∞ の場合の読み方まで書いた形で運んでいる（→ (M1) の 2 番目）。
 * 同 step が指摘したもう 1 件（補題 Q5 の定数 c_1 が b = 0 で未定義）は定理 Q 系のもので、
 * 本章は Q 系を運んでいないため本文には現れない。
 *
 * 本章の主張はすべて Z・F_ℓ・Q・Z[ζ_{ℓ^k}] の中で閉じる（ℝ を使わない）。捻り段データを
 * 取るために円分体 Q(ζ_{ℓ^k}) へ出るが、これは Q の有限次代数拡大であって可算であり、
 * 計算は Z[x]/Φ_{ℓ^k}(x) の整数演算とノルム（整数）だけで閉じる。飽和深度の判定に現れる
 * 「ℓ^λ ≥ e_{j*} + 1 なる最小の自然数 λ」も、実対数を経由せず ℓ の冪の比較だけで決まる。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "paper_110_heading_general_closed_form",
    kind: "heading",
    level: 1,
    origin: { path: "structured-latex/content/010_general_closed_form.ts", ordinal: 1 },
    title: { text: "一般の塔の閉形式（5 係数すべて）と、係数の情報階層" },
    labels: [],
  },
  {
    id: "paper_111_theorem_general_closed_form",
    kind: "theorem",
    origin: { path: "structured-latex/content/010_general_closed_form.ts", ordinal: 2 },
    title: { text: "命題 M — 一般の塔の閉形式（5 係数すべてが D の係数からの有限計算で決まる）" },
    labels: ["paper_prop_M"],
    habitat: "Qbar",
    verification: [
      "sagemath/check/cycle21_T3_general_closed_form",
      "sagemath/check/cycle21_T3_b_star",
    ],
    statement: [
      paragraph([
        ref("paper_prop_K"),
        " の設定を引き継ぐ。",
        math(String.raw`X`),
        " は有限連結 voltage 多重グラフ、階数は 2（",
        math(String.raw`\Gamma\cong\mathbb{Z}_\ell^2`),
        "）、",
        math(String.raw`D=\det L(z,w)`),
        "、",
        math(String.raw`\mu=v_\ell(\mathrm{content}\,D)`),
        "、",
        math(String.raw`E=\ell^{-\mu}D`),
        "、",
        math(String.raw`\tilde E=z^{r}w^{s}E\in\mathbb{Z}[z,w]`),
        "、",
        math(String.raw`\kappa_n=\kappa(X_{\ell^n,\ell^n})`),
        " とし、仮定 **(H)**（全段連結）を通して置く。",
        ref("paper_prop_J"),
        " の ",
        math(String.raw`\theta`),
        "・",
        math(String.raw`\hat\theta_M`),
        "・",
        math(String.raw`\Theta_M=\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{M})}\hat\theta_M(P)`),
        " と、",
        ref("paper_prop_K"),
        " の ",
        math(String.raw`S_\infty`),
        "・",
        math(String.raw`j^{*}(P_0)`),
        "・",
        math(String.raw`e_{j^*}`),
        " を使う。",
      ]),
      paragraph([
        "**(M1 捻り段データ)** ",
        math(String.raw`P_0\in S_\infty`),
        " に対応する原始整数ベクトルを ",
        math(String.raw`u=(u_1,u_2)`),
        "、",
        math(String.raw`\det(u,\mathbf{e})=1`),
        " なる整数ベクトルを ",
        math(String.raw`\mathbf{e}`),
        "（拡張 Euclid で構成できる）、",
        math(String.raw`\eta`),
        " を原始 ",
        math(String.raw`\ell^{k}`),
        " 乗根、",
        math(String.raw`\mathcal{O}_k=\mathbb{Z}[\eta]`),
        " とする。",
      ]),
      displayMath(
        String.raw`\Phi^{[k]}_{u}(x):=\tilde E\bigl((1+x)^{u_1}\eta^{\mathbf{e}_1},\,(1+x)^{u_2}\eta^{\mathbf{e}_2}\bigr)
        =\sum_{m}A^{[k]}_m\,x^{m}\ \in\mathcal{O}_k[x]`,
      ),
      paragraph([
        "と置き（",
        math(String.raw`(1+x)`),
        " の負冪が出るときは単項式因子を落とす。単元なので付値を変えない）、",
      ]),
      displayMath(
        String.raw`\Lambda_k:=\min_m v_\ell\bigl(A^{[k]}_m\bigr),\qquad
        \theta^\sharp_k:=\min\bigl\{m:v_\ell(A^{[k]}_m)=\Lambda_k\bigr\},\qquad
        m^\sharp_k:=\min\bigl\{m<\theta^\sharp_k:A^{[k]}_m\neq0\bigr\}`,
      ),
      paragraph([
        "と定める（そのような ",
        math(String.raw`m`),
        " が無ければ ",
        math(String.raw`m^\sharp_k=\infty`),
        "）。",
        "**規約（書き落とせない）**: ",
        math(String.raw`\Lambda_k`),
        " と ",
        math(String.raw`\theta^\sharp_k`),
        " の ",
        math(String.raw`\min`),
        " は ",
        math(String.raw`A^{[k]}_m\neq0`),
        " となる ",
        math(String.raw`m`),
        " についてのみ取る（",
        math(String.raw`v_\ell(0)=+\infty`),
        " の規約）。",
        math(String.raw`v_\ell(0)=0`),
        " と読む流儀（多くの計算機代数系と形式化ライブラリの既定）で読むと、下の (U4) の主役である ",
        math(String.raw`p=1`),
        " の塔で ",
        math(String.raw`\Lambda_1`),
        " が ",
        math(String.raw`2`),
        " ではなく ",
        math(String.raw`0`),
        " になり、",
        math(String.raw`c`),
        " の値が変わって結論が壊れる。",
        math(String.raw`v_\ell`),
        " は ",
        math(String.raw`v_\ell(\ell)=1`),
        " に正規化し、",
        math(String.raw`v_\ell(\alpha)=v_\ell\bigl(N_{\mathbb{Q}(\eta)/\mathbb{Q}}(\alpha)\bigr)/\varphi(\ell^{k})`),
        " で計算する（整数の付値ひとつ）。このとき:",
      ]),
      list([
        [
          math(String.raw`\Lambda_k,\theta^\sharp_k,m^\sharp_k`),
          " は深さ ",
          math(String.raw`k`),
          " の層のどの点を取っても同じである（Galois 共役で移り合い、",
          math(String.raw`\ell`),
          " の上の素点は 1 つだから）。",
        ],
        [
          math(String.raw`M\ge2k`),
          " かつ ",
          math(String.raw`\varphi(\ell^{M})>\bigl(\theta^\sharp_k-m^\sharp_k\bigr)\varphi(\ell^{k})`),
          " ならば、深さ ",
          math(String.raw`k`),
          " の層の**全点**で ",
          math(String.raw`\hat\theta_M(P)=\varphi(\ell^{M})\Lambda_k+\theta^\sharp_k`),
          " が成り立つ。ここで ",
          math(String.raw`m^\sharp_k=\infty`),
          " のとき（",
          math(String.raw`m<\theta^\sharp_k`),
          " に非零の係数が無いとき）は差 ",
          math(String.raw`\theta^\sharp_k-m^\sharp_k`),
          " を ",
          math(String.raw`-\infty`),
          " と読み、**この不等式は自動的に満たされる**（証明でこの差が使われるのは「",
          math(String.raw`m<\theta^\sharp_k`),
          " かつ ",
          math(String.raw`A^{[k]}_m\neq0`),
          " の項が最小を奪わない」を言うためであり、そのような ",
          math(String.raw`m`),
          " が無ければ条件は空だからである）。",
        ],
        [
          math(String.raw`\varphi(\ell^{k})\Lambda_k\in\mathbb{Z}_{\ge1}`),
          "。とくに上の右辺は整数である。",
        ],
      ]),
      paragraph([
        "ここで層の定義を書く。深さ ",
        math(String.raw`k`),
        " の層とは、レベル ",
        math(String.raw`M`),
        " の点のうち ",
        math(String.raw`P_0`),
        " からの距離がちょうど ",
        math(String.raw`\ell^{-(M-k)}`),
        " のもの、すなわち ",
        math(String.raw`P=\bigl(u+\ell^{M-k}t\,\mathbf{e}\bigr)\bmod\ell^{M}`),
        "（",
        math(String.raw`t\in(\mathbb{Z}/\ell^{k})^{\times}`),
        "、",
        math(String.raw`k\ge1`),
        "）と ",
        math(String.raw`k=0`),
        "（1 点）である。点数は ",
        math(String.raw`k\ge1`),
        " で ",
        math(String.raw`\varphi(\ell^{k})`),
        "、",
        math(String.raw`k=0`),
        " で ",
        math(String.raw`1`),
        "。",
        "**(M1) の内容は、基点の近傍を見ることが 1 径数部分群を 1 の冪根で捻ることに等しく、" +
          "係数環を整数から円分整数へ広げると最小点の同点が解ける、ということである。**",
        " 捻る根は ",
        math(String.raw`\eta`),
        "、広げた係数環は ",
        math(String.raw`\mathcal{O}_k`),
        " であり、同点が起きるのは ",
        ref("paper_prop_J"),
        " の最小化を ",
        math(String.raw`\mathbb{Z}`),
        " 係数のまま行ったときである。",
      ]),
      paragraph([
        "**(M2 飽和深度の明示上界)** ",
        math(String.raw`K(P_0):=\max\bigl\{k\ge0:\ j^{*}\ell\ge(\ell-1)\ell^{k}\bigr\}`),
        " と置く（",
        math(String.raw`j^{*}\ge1`),
        " より常に定義され、",
        math(String.raw`K\ge0`),
        "）。さらに ",
        math(String.raw`\lambda(P_0)`),
        " を ",
        math(String.raw`\ell^{\lambda}\ge e_{j^*}+1`),
        " を満たす最小の自然数とする（",
        math(String.raw`\ell`),
        " の冪を順に比べれば決まるので、実対数を経由しない。値は ",
        math(String.raw`\lceil\log_\ell(e_{j^*}+1)\rceil`),
        " に等しい）。深さ ",
        math(String.raw`k>K`),
        " の層では、",
        math(String.raw`M\ge\max\bigl(R'+k,\ k+\lambda\bigr)`),
        " のとき",
      ]),
      displayMath(String.raw`\hat\theta_M(P)=\theta(P)=e_{j^*}+j^{*}\ell^{\,M-k},`),
      paragraph(["すなわち"]),
      displayMath(
        String.raw`\Lambda_k=\frac{j^{*}}{\varphi(\ell^{k})},\qquad\theta^\sharp_k=e_{j^*}`,
      ),
      paragraph([
        "である（",
        math(String.raw`R'(P_0)`),
        " は ",
        ref("paper_prop_K"),
        " (K5) の ",
        math(String.raw`r_0`),
        " 以上で ",
        math(String.raw`\mathrm{argmin}`),
        " が ",
        math(String.raw`j^{*}`),
        " で一意になる最小のレベル）。とくに ",
        math(String.raw`K=0`),
        " と ",
        math(String.raw`j^{*}\le\ell-2`),
        " は同値であり、",
        math(String.raw`\ell=2`),
        " では ",
        math(String.raw`j^{*}\ge1=\ell-1`),
        " なので必ず ",
        math(String.raw`K\ge1`),
        " である。",
        "**すなわち、飽和は 2 進の塔に固有の現象ではない。これがその正体である。** ",
        ref("paper_prop_G_ell2"),
        " が ",
        math(String.raw`\ell=2`),
        " 固有として挙げた飽和は、",
        math(String.raw`\ell-1`),
        " が最小であることの帰結にすぎない。",
        math(String.raw`\ell`),
        " が奇でも ",
        math(String.raw`j^{*}\ge\ell-1`),
        " の塔では同じことが起きる。なお ",
        math(String.raw`K`),
        " は上界であって、",
        math(String.raw`k\le K`),
        " の層が必ず飽和すると言っているのではない（下の (U1a) のとおり、",
        math(String.raw`K`),
        " を大きめに取っても 5 係数の値は変わらない）。",
      ]),
      paragraph([
        "**(M3 レベルごとの和の閉形式)** ",
        math(String.raw`r^\sharp:=\max\bigl(r_0,\ \max_{P_0}R'(P_0)\bigr)`),
        "、",
        math(String.raw`U:=\mathbb{P}^1(\mathbb{Z}_\ell)\setminus\bigcup_{P_0\in S_\infty}B(P_0,\ell^{-r^\sharp})`),
        " と置く。",
        math(String.raw`\theta`),
        " は ",
        math(String.raw`U`),
        " 上有界で、その上界は ",
        math(String.raw`D`),
        " の係数から計算できる。",
        math(String.raw`\theta^{\max}_U`),
        " を最大値、",
        math(String.raw`L\ge r^\sharp`),
        " を ",
        math(String.raw`\ell^{L}\ge\theta^{\max}_U`),
        " なるレベルとして",
      ]),
      displayMath(
        String.raw`A_{\mathrm{gen}}:=\frac{1}{\ell^{L}}\sum_{P\in U\cap\mathbb{P}^1(\mathbb{Z}/\ell^{L})}\theta(P)\ \in\mathbb{Q}`,
      ),
      paragraph([
        "と置く（",
        math(String.raw`L`),
        " の取り方に依らない。",
        math(String.raw`L\to L+1`),
        " でファイバーが一様に ",
        math(String.raw`\ell`),
        " 個に分かれるから）。このとき、下の (M5) が与える明示的な ",
        math(String.raw`M^{*}`),
        " が存在して、",
        math(String.raw`M\ge M^{*}`),
        " で",
      ]),
      displayMath(String.raw`\Theta_M=\alpha\,M\ell^{M}+\beta\,\ell^{M}+\gamma`),
      paragraph([
        "が成り立つ。ここで",
      ]),
      displayMath(String.raw`\alpha=\frac{\ell-1}{\ell}\sum_{P_0\in S_\infty}j^{*}(P_0),`),
      displayMath(
        String.raw`\beta=A_{\mathrm{gen}}+\sum_{P_0\in S_\infty}\Bigl[\frac{e_{j^*}}{\ell^{\,r^\sharp}}
        -\frac{(\ell-1)\,j^{*}\,(K+r^\sharp)}{\ell}
        +\frac{\ell-1}{\ell}\Bigl(\Lambda_0+\sum_{k=1}^{K}\varphi(\ell^{k})\Lambda_k\Bigr)\Bigr],`,
      ),
      displayMath(
        String.raw`\gamma=\sum_{P_0\in S_\infty}\Bigl[-e_{j^*}\,\ell^{K}
        +\theta^\sharp_0+\sum_{k=1}^{K}\varphi(\ell^{k})\,\theta^\sharp_k\Bigr].`,
      ),
      paragraph([
        "**(M4 5 係数)** したがって ",
        math(String.raw`n\ge M^{*}-1`),
        " で ",
        ref("paper_prop_J"),
        " (J4) の 5 係数形 ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)=a\,\ell^{2n}+b\,n\ell^{n}+c\,\ell^{n}+d\,n+e`),
        " が成り立ち、",
      ]),
      displayMath(
        String.raw`a=\mu,\qquad b=\frac{\ell}{\ell-1}\,\alpha=\sum_{P_0\in S_\infty}j^{*}(P_0),\qquad
        c=\frac{\ell}{\ell-1}\,\beta-\frac{\ell}{(\ell-1)^2}\,\alpha,\qquad d=\gamma-2,`,
      ),
      displayMath(
        String.raw`e=v_\ell(\kappa(X))-\mu
        +\Bigl[\sum_{M=1}^{M^{*}-1}\Theta_M-\alpha\,\mathcal{S}_1(M^{*}\!-\!1)-\beta\,\mathcal{S}_0(M^{*}\!-\!1)-\gamma(M^{*}\!-\!1)\Bigr]
        +\frac{\ell}{(\ell-1)^2}\alpha-\frac{\ell}{\ell-1}\beta,`,
      ),
      paragraph([
        "ここで ",
        math(String.raw`\mathcal{S}_1(N)=\sum_{M=1}^{N}M\ell^{M}`),
        "、",
        math(String.raw`\mathcal{S}_0(N)=\sum_{M=1}^{N}\ell^{M}`),
        " である。",
        "**すなわち 5 係数すべてが、スペクトル多項式の係数からの有限計算で決まる。** ",
        "とくに ",
        math(String.raw`b=\sum j^{*}`),
        " は ",
        ref("paper_prop_J"),
        " (J4) が残していた仮定（",
        math(String.raw`\hat\theta`),
        " を与える最小点の一意性）**なしに**従う。飽和層 (M1) と非飽和層 (M2) の両方で一意性を",
        "仮定せずに**証明して**いるからである。",
      ]),
      paragraph([
        "**(M5 閉形式が成り立ち始めるレベルの明示形)** 次をすべて満たす最小の ",
        math(String.raw`M`),
        " を ",
        math(String.raw`M^{*}`),
        " と取ればよい。いずれも ",
        math(String.raw`D`),
        " の係数からの有限計算である。",
      ]),
      list([
        [
          math(String.raw`M\ge L`),
          "（",
          math(String.raw`A_{\mathrm{gen}}`),
          " が経由するレベル）。",
        ],
        [
          math(String.raw`M\ge r^\sharp+\max_{P_0}K(P_0)`),
          "。**この条件は「非飽和層の閉形式が成り立つこと」であって「非飽和層が空でないこと」ではない。** ",
          math(String.raw`M=r^\sharp+\max K`),
          " では非飽和層は空だが、和 ",
          math(String.raw`\sum_{s=K+1}^{M-r^\sharp}\varphi(\ell^{s})=\ell^{M-r^\sharp}-\ell^{K}`),
          " は両辺 ",
          math(String.raw`0`),
          " で成り立つので、閉形式はそのまま正しい。破れるのは ",
          math(String.raw`M<r^\sharp+\max K`),
          " からである。",
        ],
        [
          math(String.raw`\varphi(\ell^{M})>\theta^{\max}_U-2`),
          "（一般領域 ",
          math(String.raw`U`),
          " の分）。",
        ],
        [
          "各 ",
          math(String.raw`P_0`),
          "、各 ",
          math(String.raw`k\le K`),
          " で ",
          math(String.raw`M\ge2k`),
          " かつ ",
          math(String.raw`\varphi(\ell^{M})>(\theta^\sharp_k-m^\sharp_k)\varphi(\ell^{k})`),
          "（(M1)。",
          math(String.raw`m^\sharp_k=\infty`),
          " の層ではこの不等式は自動的に満たされる）。",
        ],
        [
          "各 ",
          math(String.raw`P_0`),
          " で ",
          math(String.raw`e_{j^*}+j^{*}\ell^{\,M-K-1}-2<\varphi(\ell^{M})`),
          "（(M2) の ",
          math(String.raw`k=K+1`),
          " の最外層。",
          math(String.raw`M=r^\sharp+\max K`),
          " ではこの層が無いので条件は空である）。",
        ],
      ]),
      paragraph([
        "**(M6 無限消滅深度の点が無い場合)** ",
        math(String.raw`S_\infty=\emptyset`),
        " かどうかは ",
        ref("paper_prop_K"),
        " (K3) で判定できる。この場合は ",
        math(String.raw`\alpha=\gamma=0`),
        "、",
        math(String.raw`\beta=A_{\mathrm{gen}}`),
        " で",
      ]),
      displayMath(
        String.raw`a=\mu,\quad b=0,\quad c=\frac{\ell}{\ell-1}A_{\mathrm{gen}}=\frac{\Theta_L}{\varphi(\ell^{L})},\quad d=-2,`,
      ),
      displayMath(
        String.raw`e=v_\ell(\kappa(X))-\mu+\sum_{M=1}^{M^{*}-1}\Theta_M
        -A_{\mathrm{gen}}\Bigl(\mathcal{S}_0(M^{*}\!-\!1)+\frac{\ell}{\ell-1}\Bigr).`,
      ),
      paragraph([
        "**実数体を使っていないことの明示**: 使ったのは (a) ",
        math(String.raw`\mathcal{O}_k=\mathbb{Z}[\zeta_{\ell^{k}}]`),
        "（",
        math(String.raw`\mathbb{Q}`),
        " の可算な代数拡大の整数環）の ",
        math(String.raw`\ell`),
        " の上の唯一の素点での付値（値は ",
        math(String.raw`N_{\mathbb{Q}(\eta)/\mathbb{Q}}`),
        " を取って ",
        math(String.raw`\mathbb{Z}`),
        " の ",
        math(String.raw`\ell`),
        " 進付値へ落として計算する）、(b) ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{M})`),
        " 上の有限和、(c) ",
        math(String.raw`\mathbb{Q}`),
        " 上の有理数演算だけである。また (M2) の ",
        math(String.raw`\lambda`),
        " も実対数を経由せず ",
        math(String.raw`\ell`),
        " の冪の比較だけで決まる。**したがって本命題は実数体へ脱出しない。**",
      ]),
      paragraph([
        "**限界（主張の一部として述べる）**",
      ]),
      list([
        [
          "**射程は、階数 2・仮定 (H)・voltage グラフのラプラシアン行列式型に限る。** 記号で書けば ",
          math(String.raw`d=2`),
          "（",
          math(String.raw`\Gamma\cong\mathbb{Z}_\ell^2`),
          "）であり、対象は ",
          math(String.raw`\det L`),
          " の形のものだけである。(M1) の捻りの考え方は階数 3 以上でも意味を持つが、",
          math(String.raw`\mathbb{P}^{d-1}`),
          " 上の層別が ",
          math(String.raw`\mathbb{P}^1`),
          " ほど単純でないため、そのままでは移らない。",
        ],
        [
          math(String.raw`M^{*}`),
          " は十分条件であって**鋭さを主張しない**。実測では多くの塔で ",
          math(String.raw`M^{*}`),
          " より小さい ",
          math(String.raw`M`),
          " から閉形式が成り立つ。したがって ",
          math(String.raw`n<M^{*}-1`),
          " での一致・不一致を本命題の検証に使ってはならない。",
        ],
        [
          math(String.raw`(\Lambda_k,\theta^\sharp_k)`),
          " を ",
          math(String.raw`\bar{\tilde E}\in\mathbb{F}_\ell[z,w]`),
          " の組合せ的なデータから読む式は**与えていない**。",
          ref("paper_prop_U"),
          " が示すとおり、それは原理的に不可能である。与えたのは「",
          math(String.raw`D`),
          " の係数からの有限計算で書く」という形である。",
        ],
        [
          math(String.raw`a\le\mu`),
          " という一般論は Cuoco–Monsky からの借り物のままである（本命題の枠内では ",
          math(String.raw`a=\mu`),
          " は ",
          ref("paper_prop_J"),
          " の展開から直接出るので、借りているのは一般論の側だけである）。",
        ],
        [
          "**新規性は主張しない。** ",
          math(String.raw`a=\mu`),
          " と ",
          math(String.raw`b=\sum j^{*}`),
          " は Cuoco–Monsky, *Class numbers in ",
          math(String.raw`\mathbb{Z}_p^d`),
          "-extensions*, Math. Ann. **255** (1981), 235–258 の Definition 1.1・1.2 と Theorem 1.7 であり、",
          ref("paper_prop_K"),
          " (K6) が既に帰属を書いている。",
          math(String.raw`c`),
          " については、Monsky, *Fine estimates for the growth of ",
          math(String.raw`e_n`),
          " in ",
          math(String.raw`\mathbb{Z}_p^d`),
          "-extensions* (1989) が同じ位置の定数 ",
          math(String.raw`\alpha^{*}`),
          " について「there is no easy description of ",
          math(String.raw`\alpha^{*}`),
          "」と書き、存在と（",
          math(String.raw`d=2`),
          " での）有理性しか示していない（Introduction, p.309；原文を取得して確認した）。",
          "本命題はその位置の量を上の限定された設定で明示するが、**文献調査は網羅的でない**。",
          "とくに (M1) の操作（",
          math(String.raw`\ell^{k}`),
          " 乗根の指標で捻って分解し各成分の付値を取る）は岩澤理論では標準的であり、",
          math(String.raw`\det L`),
          " 型のような具体的な対象に対して同じ計算が既になされている可能性は高い。",
        ],
        [
          math(String.raw`d`),
          "（",
          math(String.raw`n`),
          " の係数）と ",
          math(String.raw`e`),
          "（定数項）は、そもそも Monsky の主張の外側にある（",
          math(String.raw`d=2`),
          " では同論文の誤差項が ",
          math(String.raw`O(n)`),
          " なので、そこは開いていない）。",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "**証明が外から使う事実を、使う前にすべて主張として述べる。** 次の 5 つだけである。",
      ]),
      list([
        [
          "**(a 付値とレベル分解)** ",
          ref("paper_prop_R"),
          " の (R4)(R5)。原始 ",
          math(String.raw`\ell^{M}`),
          " 乗根 ",
          math(String.raw`\zeta`),
          " と点 ",
          math(String.raw`P=(a{:}b)`),
          " に対し指標 ",
          math(String.raw`\omega_P:z\mapsto\zeta^{a},\ w\mapsto\zeta^{b}`),
          " を取ると ",
          math(String.raw`\hat\theta_M(P)=\varphi(\ell^{M})\,v_\ell\bigl(\tilde E(\omega_P)\bigr)`),
          " であり、",
          math(String.raw`\Sigma_n=\sum_{M=1}^{n}\Theta_M`),
          " と ",
          math(String.raw`\mathrm{ord}_\ell(\kappa_n)=v_\ell(\kappa(X))-2n+\mu(\ell^{2n}-1)+\Sigma_n`),
          " が**仮定なしに**成り立つ。",
        ],
        [
          "**(b 桁定理)** ",
          ref("paper_prop_J"),
          " の (J1)。",
          math(String.raw`\theta(P)\le\ell^{L}`),
          " ならば ",
          math(String.raw`\theta(P)`),
          " は ",
          math(String.raw`P\bmod\ell^{L}`),
          " だけで決まる。",
          math(String.raw`m=\ell^{L}`),
          " ちょうどの段には ",
          math(String.raw`\bar A_1\equiv0`),
          " が要るが、これは ",
          math(String.raw`D(z,w)=D(z^{-1},w^{-1})`),
          " から無条件に従う（",
          ref("paper_prop_G"),
          " の (G6)）。**本命題が外から借りている唯一の非自明な点はこれである。**",
        ],
        [
          "**(c 消滅深度の有効上界)** ",
          ref("paper_prop_R"),
          " の (R3)。",
          math(String.raw`\theta(P)<\infty`),
          " なる点では ",
          math(String.raw`\theta(P)\le\ell^{\mathrm{sep}(P)}-1`),
          " であり、上界は ",
          math(String.raw`S=\mathrm{supp}(\bar{\tilde E})`),
          " の差ベクトルの付値から ",
          math(String.raw`D`),
          " の係数だけで計算できる。**コンパクト性ではなく有効な上界である。**",
        ],
        [
          "**(d ",
          math(String.raw`S_\infty`),
          " の記述)** ",
          ref("paper_prop_J"),
          " の (J6) と ",
          ref("paper_prop_K"),
          " の (K2)(K4)(K5)。",
          math(String.raw`S_\infty`),
          " は有限で ",
          math(String.raw`\mathbb{P}^1(\mathbb{Q})`),
          " に含まれ、",
          math(String.raw`P=\iota([u])\in S_\infty\iff(\chi^{u^\perp}-1)\mid\bar{\tilde E}`),
          "、",
          math(String.raw`j^{*}(P)=m_u`),
          "（重複度）である。さらに ",
          math(String.raw`r\ge r_0`),
          " では相異なる ",
          math(String.raw`P_0`),
          " の半径 ",
          math(String.raw`\ell^{-r}`),
          " の球が互いに素で、",
          math(String.raw`\Lambda(r)=\min_j\bigl(e_j+j\ell^{r}\bigr)`),
          " の最小点は ",
          math(String.raw`j=j^{*}`),
          " ただ 1 つである。",
        ],
        [
          "**(e 最低次)** ",
          ref("paper_prop_G"),
          " の (G6) から ",
          math(String.raw`\Phi_P\in\mathbb{Z}[x]`),
          " の最低次 ",
          math(String.raw`m_1`),
          " は ",
          math(String.raw`m_1\ge2`),
          " を満たす。",
        ],
      ]),
      paragraph([
        "**繰り返し使う原理も明示しておく（非アルキメデス的評価の等号）。** 付値 ",
        math(String.raw`v`),
        " をもつ体の中で ",
        math(String.raw`\alpha=\sum_m\alpha_m`),
        " と書けたとき、",
        math(String.raw`v(\alpha_m)`),
        " の最小を達成する ",
        math(String.raw`m`),
        " が**ただ 1 つ**ならば ",
        math(String.raw`v(\alpha)=\min_m v(\alpha_m)`),
        " である（最小が 2 つ以上で達成されるときは ",
        math(String.raw`\ge`),
        " しか言えない）。**以下の各段は、すべて「最小点が一意である」ことを示すことに帰着する。**",
      ]),
      paragraph([
        "**(M1) の証明。まず層の記述。** ",
        math(String.raw`\det(u,\mathbf{e})=1`),
        " より ",
        math(String.raw`\{u,\mathbf{e}\}`),
        " は ",
        math(String.raw`\mathbb{Z}^2`),
        " の基底である。",
        math(String.raw`g`),
        " を原始 ",
        math(String.raw`\ell^{M}`),
        " 乗根とすると ",
        math(String.raw`\eta:=g^{\ell^{M-k}}`),
        " は原始 ",
        math(String.raw`\ell^{k}`),
        " 乗根であり、",
        math(String.raw`(a,b)=u+\ell^{M-k}t\,\mathbf{e}`),
        " に対して",
      ]),
      displayMath(
        String.raw`\bigl(g^{a},g^{b}\bigr)=\bigl(g^{u_1}\eta^{t\mathbf{e}_1},\ g^{u_2}\eta^{t\mathbf{e}_2}\bigr)`,
      ),
      paragraph([
        "が成り立つ（",
        math(String.raw`M\ge2k`),
        " なら相異なる ",
        math(String.raw`t`),
        " は相異なる射影点を与えるので、層の点数は主張のとおりである）。",
        math(String.raw`\pi:=g-1`),
        " と置いて ",
        math(String.raw`g^{u_i}=(1+\pi)^{u_i}`),
        " と読めば、この点での ",
        math(String.raw`\tilde E`),
        " の値は ",
        math(String.raw`\Phi^{[k]}_{u}(\pi)`),
        " にほかならない。",
      ]),
      paragraph([
        "**1（層の全点で共通であること）。** ",
        math(String.raw`\sigma_t:\eta\mapsto\eta^{t}`),
        " は ",
        math(String.raw`\mathrm{Gal}\bigl(\mathbb{Q}(\eta)/\mathbb{Q}\bigr)`),
        " の元で ",
        math(String.raw`\mathbb{Z}`),
        " を固定し、",
        math(String.raw`\Phi^{[k]}_{u}`),
        " の係数を ",
        math(String.raw`t`),
        " 版の係数へ写す。",
        math(String.raw`\ell`),
        " の上の素点は 1 つなので ",
        math(String.raw`v_\ell`),
        " は Galois 不変であり、列 ",
        math(String.raw`\bigl(v_\ell(A^{[k]}_m)\bigr)_m`),
        " は ",
        math(String.raw`t`),
        " に依らない。したがって ",
        math(String.raw`\Lambda_k,\theta^\sharp_k,m^\sharp_k`),
        " も依らない。",
      ]),
      paragraph([
        "**2（条件の下での値）。** ",
        math(String.raw`\ell`),
        " は ",
        math(String.raw`\mathbb{Q}(g)/\mathbb{Q}`),
        " で完全分岐し ",
        math(String.raw`\pi`),
        " は素元なので ",
        math(String.raw`v_\ell(\pi)=1/\varphi(\ell^{M})`),
        " である。(a) より",
      ]),
      displayMath(
        String.raw`\hat\theta_M(P)=\varphi(\ell^{M})\,v_\ell\Bigl(\sum_m A^{[k]}_m\pi^{m}\Bigr),
        \qquad
        \varphi(\ell^{M})\,v_\ell\bigl(A^{[k]}_m\pi^{m}\bigr)=\varphi(\ell^{M})\,v_\ell\bigl(A^{[k]}_m\bigr)+m`,
      ),
      paragraph([
        "であり、右辺は ",
        math(String.raw`\mathbb{Z}\cup\{\infty\}`),
        " に値を取る。最小が ",
        math(String.raw`m=\theta^\sharp_k`),
        " で一意に達成されることを見る。",
      ]),
      list([
        [
          math(String.raw`m=\theta^\sharp_k`),
          " では値は ",
          math(String.raw`\varphi(\ell^{M})\Lambda_k+\theta^\sharp_k`),
          " である。",
        ],
        [
          math(String.raw`m>\theta^\sharp_k`),
          " では ",
          math(String.raw`v_\ell(A^{[k]}_m)\ge\Lambda_k`),
          " より値は ",
          math(String.raw`\ge\varphi(\ell^{M})\Lambda_k+m>\varphi(\ell^{M})\Lambda_k+\theta^\sharp_k`),
          " である。",
        ],
        [
          math(String.raw`m<\theta^\sharp_k`),
          " かつ ",
          math(String.raw`A^{[k]}_m=0`),
          " では値は ",
          math(String.raw`\infty`),
          " で、最小を奪わない。",
        ],
        [
          math(String.raw`m<\theta^\sharp_k`),
          " かつ ",
          math(String.raw`A^{[k]}_m\neq0`),
          " では、",
          math(String.raw`v_\ell`),
          " の値が ",
          math(String.raw`\tfrac{1}{\varphi(\ell^{k})}\mathbb{Z}`),
          " に入り ",
          math(String.raw`\Lambda_k`),
          " より真に大きいので ",
          math(String.raw`v_\ell(A^{[k]}_m)\ge\Lambda_k+\tfrac{1}{\varphi(\ell^{k})}`),
          "、したがって値は ",
          math(String.raw`\ge\varphi(\ell^{M})\Lambda_k+\tfrac{\varphi(\ell^{M})}{\varphi(\ell^{k})}+m^\sharp_k`),
          " である。これが ",
          math(String.raw`\varphi(\ell^{M})\Lambda_k+\theta^\sharp_k`),
          " より真に大きいことは",
        ],
      ]),
      displayMath(
        String.raw`\frac{\varphi(\ell^{M})}{\varphi(\ell^{k})}+m^\sharp_k\ >\ \theta^\sharp_k`,
      ),
      paragraph([
        "と同値である。**この和の形が、主張の条件が実際に使われている形である。** ",
        math(String.raw`m^\sharp_k`),
        " が有限なら移項して ",
        math(String.raw`\varphi(\ell^{M})>\bigl(\theta^\sharp_k-m^\sharp_k\bigr)\varphi(\ell^{k})`),
        " と書け、",
        math(String.raw`m^\sharp_k=\infty`),
        " なら左辺が ",
        math(String.raw`\infty`),
        " で自動的に真である（そもそもこの 4 番目の場合が空である）。**主張が置いた規約「差を ",
        math(String.raw`-\infty`),
        " と読む」は、この和の形と同じことを差の形で言い直したものである。**",
      ]),
      paragraph([
        "以上で最小点が一意なので、上の原理より深さ ",
        math(String.raw`k`),
        " の層の全点で ",
        math(String.raw`\hat\theta_M(P)=\varphi(\ell^{M})\Lambda_k+\theta^\sharp_k`),
        " が成り立つ。",
      ]),
      paragraph([
        "**3（整数性）。** ",
        math(String.raw`v_\ell`),
        " の値が ",
        math(String.raw`\tfrac{1}{\varphi(\ell^{k})}\mathbb{Z}`),
        " に入ることから ",
        math(String.raw`\varphi(\ell^{k})\Lambda_k\in\mathbb{Z}`),
        "。下限を見る。",
        math(String.raw`k\ge1`),
        " のとき ",
        math(String.raw`\mathcal{O}_k`),
        " の極大イデアルは ",
        math(String.raw`(\eta-1)`),
        " で剰余体は ",
        math(String.raw`\mathbb{F}_\ell`),
        "、剰余写像は ",
        math(String.raw`\eta\mapsto1`),
        " を誘導するので、",
        math(String.raw`A^{[k]}_m`),
        " の剰余は ",
        math(String.raw`\overline{\Phi_u}`),
        " の ",
        math(String.raw`m`),
        " 次係数 ",
        math(String.raw`\bar A_m(u)`),
        " に等しい。(d) より ",
        math(String.raw`P_0\in S_\infty`),
        " は ",
        math(String.raw`\overline{\Phi_u}\equiv0`),
        "、すなわち全ての ",
        math(String.raw`m`),
        " で ",
        math(String.raw`\bar A_m(u)=0`),
        " を意味するから ",
        math(String.raw`v_\ell(A^{[k]}_m)\ge\tfrac{1}{\varphi(\ell^{k})}`),
        "、よって ",
        math(String.raw`\varphi(\ell^{k})\Lambda_k\ge1`),
        "。",
        math(String.raw`k=0`),
        " では ",
        math(String.raw`\mathcal{O}_0=\mathbb{Z}`),
        "、",
        math(String.raw`\varphi(\ell^{0})=1`),
        " で同じ議論が ",
        math(String.raw`v_\ell(A_m)\ge1`),
        " を与える。",
      ]),
      paragraph([
        "**(M2) の証明。** ",
        math(String.raw`k>K`),
        " は ",
        math(String.raw`j^{*}\ell<(\ell-1)\ell^{k}`),
        "、すなわち（両辺が整数なので）",
        math(String.raw`(\ell-1)\ell^{k-1}-j^{*}\ge1`),
        " を意味する。",
        math(String.raw`r=M-k\ge R'`),
        " なので (d) より ",
        math(String.raw`\Lambda(r)`),
        " の最小点は ",
        math(String.raw`j=j^{*}`),
        " で一意になり、",
        math(String.raw`\theta(P)=e_{j^*}+j^{*}\ell^{\,M-k}`),
        " である。",
        math(String.raw`\Phi_P\in\mathbb{Z}[x]`),
        " の係数は ",
        math(String.raw`m<\theta(P)`),
        " で ",
        math(String.raw`v_\ell(A_m)\ge1`),
        "、",
        math(String.raw`m=\theta(P)`),
        " で ",
        math(String.raw`v_\ell(A_\theta)=0`),
        " である（",
        math(String.raw`\theta`),
        " の定義）。最小化 ",
        math(String.raw`\min_m\bigl(\varphi(\ell^{M})v_\ell(A_m)+m\bigr)`),
        " で ",
        math(String.raw`m=\theta(P)`),
        " が一意の最小点になる十分条件は ",
        math(String.raw`\theta(P)-m_1<\varphi(\ell^{M})`),
        " であり（(e) の ",
        math(String.raw`m_1\ge2`),
        " を使う）、",
      ]),
      displayMath(
        String.raw`\varphi(\ell^{M})-\theta(P)+m_1\ \ge\ (\ell-1)\ell^{M-1}-j^{*}\ell^{\,M-k}-e_{j^*}+2
        =\ell^{\,M-k}\bigl[(\ell-1)\ell^{k-1}-j^{*}\bigr]-e_{j^*}+2\ \ge\ \ell^{\,M-k}-e_{j^*}+2`,
      ),
      paragraph([
        "なので、",
        math(String.raw`\ell^{\,M-k}>e_{j^*}`),
        " ならば右辺は正である。",
        math(String.raw`\ell^{\,M-k}`),
        " と ",
        math(String.raw`e_{j^*}`),
        " はどちらも整数だから ",
        math(String.raw`\ell^{\,M-k}>e_{j^*}\iff\ell^{\,M-k}\ge e_{j^*}+1`),
        " であり、",
        math(String.raw`\lambda`),
        " の定義よりこれは ",
        math(String.raw`M\ge k+\lambda`),
        " と同値である。**判定は ",
        math(String.raw`\ell`),
        " の冪と整数との比較だけであり、実対数を経由しない。** よって ",
        math(String.raw`\hat\theta_M(P)=\theta(P)`),
        " である。",
      ]),
      paragraph([
        "これと (M1) の値を、両方が成り立つ 2 つ以上の ",
        math(String.raw`M`),
        " で比べる。",
        math(String.raw`\varphi(\ell^{M})\Lambda_k+\theta^\sharp_k=e_{j^*}+j^{*}\ell^{\,M-k}`),
        " が ",
        math(String.raw`M`),
        " について恒等的に成り立つので、",
        math(String.raw`\ell^{M}`),
        " の係数を比べて ",
        math(String.raw`\tfrac{\ell-1}{\ell}\Lambda_k=j^{*}\ell^{-k}`),
        "、すなわち ",
        math(String.raw`\Lambda_k=\tfrac{j^{*}\ell^{1-k}}{\ell-1}=\tfrac{j^{*}}{\varphi(\ell^{k})}`),
        "（",
        math(String.raw`\varphi(\ell^{k})=(\ell-1)\ell^{k-1}`),
        " による）、定数項を比べて ",
        math(String.raw`\theta^\sharp_k=e_{j^*}`),
        " を得る。最後に ",
        math(String.raw`K=0\iff j^{*}\ell<(\ell-1)\ell\iff j^{*}\le\ell-2`),
        " であり、",
        math(String.raw`\ell=2`),
        " では ",
        math(String.raw`j^{*}\ge1=\ell-1`),
        " なので ",
        math(String.raw`K\ge1`),
        " である。",
      ]),
      paragraph([
        "**(M3) の証明。まず ",
        math(String.raw`U`),
        " の上で ",
        math(String.raw`\theta`),
        " が有界であること。** ",
        math(String.raw`r^\sharp\ge r_0`),
        " なので (d) より球 ",
        math(String.raw`B(P_0,\ell^{-r^\sharp})`),
        " は互いに素であり、",
        math(String.raw`U`),
        " の上では ",
        math(String.raw`\theta<\infty`),
        " である。(c) の有効上界を ",
        math(String.raw`U`),
        " の上で取れば ",
        math(String.raw`\theta\le\theta^{\max}_U<\infty`),
        " で、上界は ",
        math(String.raw`D`),
        " の係数から計算できる。",
        math(String.raw`L\ge r^\sharp`),
        " を ",
        math(String.raw`\ell^{L}\ge\theta^{\max}_U`),
        " なるレベルとすると (b) より ",
        math(String.raw`\theta|_U`),
        " は ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{L})`),
        " を経由する。",
      ]),
      paragraph([
        "レベル ",
        math(String.raw`M\ge M^{*}`),
        " の ",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{M})`),
        " を 3 つに分ける。3 つは互いに素で全体を覆う（",
        math(String.raw`U`),
        " の外は ",
        math(String.raw`S_\infty`),
        " の各点の半径 ",
        math(String.raw`\ell^{-r^\sharp}`),
        " の球であり、その中は基点からの距離で層に分かれる）。",
      ]),
      paragraph([
        "**(a) ",
        math(String.raw`U`),
        " の部分。** ",
        math(String.raw`\theta\le\theta^{\max}_U`),
        " と (e) より ",
        math(String.raw`\theta-m_1\le\theta^{\max}_U-2<\varphi(\ell^{M})`),
        "（(M5) の 3 番目）なので、(M2) の証明と同じ評価で最小点が一意になり ",
        math(String.raw`\hat\theta_M=\theta`),
        " である。",
        math(String.raw`\mathbb{P}^1(\mathbb{Z}/\ell^{M})\to\mathbb{P}^1(\mathbb{Z}/\ell^{L})`),
        " のファイバーは一様に ",
        math(String.raw`\ell^{\,M-L}`),
        " 個なので、この部分の和は ",
        math(String.raw`\ell^{\,M-L}\cdot\ell^{L}A_{\mathrm{gen}}=A_{\mathrm{gen}}\ell^{M}`),
        " である。**ここからは ",
        math(String.raw`M\ell^{M}`),
        " の項も定数項も出ない。** 同じ計算は ",
        math(String.raw`L\to L+1`),
        " でファイバーが一様に ",
        math(String.raw`\ell`),
        " 個に分かれることを示すので、",
        math(String.raw`A_{\mathrm{gen}}`),
        " が ",
        math(String.raw`L`),
        " に依らないことも従う。",
      ]),
      paragraph([
        "**(b) 各 ",
        math(String.raw`P_0`),
        " の、深さ ",
        math(String.raw`K+1\le k\le M-r^\sharp`),
        " の層。** (M2) より非飽和で ",
        math(String.raw`\hat\theta_M=\theta=e_{j^*}+j^{*}\ell^{r}`),
        "（",
        math(String.raw`r=M-k`),
        "）、層の点数は ",
        math(String.raw`\varphi(\ell^{\,M-r})`),
        " である。",
        math(String.raw`\varphi(\ell^{\,M-r})\ell^{r}=\ell^{M}-\ell^{M-1}=\varphi(\ell^{M})`),
        " が ",
        math(String.raw`r`),
        " に依らないことと、望遠鏡和 ",
        math(String.raw`\sum_{s=K+1}^{M-r^\sharp}\varphi(\ell^{s})=\ell^{\,M-r^\sharp}-\ell^{K}`),
        " を使うと",
      ]),
      displayMath(
        String.raw`\sum_{r=r^\sharp}^{M-K-1}\varphi(\ell^{\,M-r})\bigl(e_{j^*}+j^{*}\ell^{r}\bigr)
        =e_{j^*}\bigl(\ell^{\,M-r^\sharp}-\ell^{K}\bigr)+j^{*}\varphi(\ell^{M})\bigl(M-K-r^\sharp\bigr)`,
      ),
      paragraph([
        "を得る。",
        math(String.raw`M\ell^{M}`),
        " の係数は ",
        math(String.raw`j^{*}\tfrac{\ell-1}{\ell}`),
        "、",
        math(String.raw`\ell^{M}`),
        " の係数は ",
        math(String.raw`e_{j^*}\ell^{-r^\sharp}-j^{*}(K+r^\sharp)\tfrac{\ell-1}{\ell}`),
        "、定数項は ",
        math(String.raw`-e_{j^*}\ell^{K}`),
        " である。**この等式は層が空のとき（",
        math(String.raw`M=r^\sharp+K`),
        "）でも両辺 ",
        math(String.raw`0`),
        " で成り立つ。**",
      ]),
      paragraph([
        "**(c) 各 ",
        math(String.raw`P_0`),
        " の、深さ ",
        math(String.raw`0\le k\le K`),
        " の層。** (M1) より ",
        math(String.raw`\hat\theta_M=\varphi(\ell^{M})\Lambda_k+\theta^\sharp_k`),
        " で、点数は ",
        math(String.raw`k=0`),
        " で ",
        math(String.raw`1`),
        "、",
        math(String.raw`k\ge1`),
        " で ",
        math(String.raw`\varphi(\ell^{k})`),
        " である。したがってこの部分の和は",
      ]),
      displayMath(
        String.raw`\varphi(\ell^{M})\Bigl(\Lambda_0+\sum_{k=1}^{K}\varphi(\ell^{k})\Lambda_k\Bigr)
        +\Bigl(\theta^\sharp_0+\sum_{k=1}^{K}\varphi(\ell^{k})\theta^\sharp_k\Bigr)`,
      ),
      paragraph([
        "であり、",
        math(String.raw`\ell^{M}`),
        " の係数は第 1 括弧の ",
        math(String.raw`\tfrac{\ell-1}{\ell}`),
        " 倍、定数項は第 2 括弧である。**ここからも ",
        math(String.raw`M\ell^{M}`),
        " の項は出ない。**",
      ]),
      paragraph([
        "(a)(b)(c) を足すと ",
        math(String.raw`\Theta_M=\alpha M\ell^{M}+\beta\ell^{M}+\gamma`),
        " が、主張の ",
        math(String.raw`\alpha,\beta,\gamma`),
        " について成り立つ。",
        math(String.raw`M`),
        " の 1 次の項はどの部分からも出ない。**これは書き落とせない点である**——もし ",
        math(String.raw`\delta M`),
        " の項があれば ",
        math(String.raw`\Sigma_n`),
        " に ",
        math(String.raw`n^{2}`),
        " が現れ、(M4) の 5 係数形そのものが壊れる。",
      ]),
      paragraph([
        "**(M4) の証明。** 等比・等差 × 等比の標準公式より",
      ]),
      displayMath(
        String.raw`\mathcal{S}_1(n)=\frac{\ell-(n+1)\ell^{n+1}+n\ell^{n+2}}{(\ell-1)^{2}},
        \qquad
        \mathcal{S}_0(n)=\frac{\ell^{n+1}-\ell}{\ell-1}`,
      ),
      paragraph([
        "である。",
        math(String.raw`\mathcal{S}_1`),
        " の分子のうち ",
        math(String.raw`n`),
        " を含む項は ",
        math(String.raw`n\ell^{n+2}-n\ell^{n+1}=n\ell^{n+1}(\ell-1)`),
        " なので、",
        math(String.raw`\mathcal{S}_1(n)`),
        " の ",
        math(String.raw`n\ell^{n}`),
        " 係数は ",
        math(String.raw`\tfrac{\ell}{\ell-1}`),
        "、",
        math(String.raw`\ell^{n}`),
        " 係数は ",
        math(String.raw`-\tfrac{\ell}{(\ell-1)^{2}}`),
        "、定数項は ",
        math(String.raw`\tfrac{\ell}{(\ell-1)^{2}}`),
        " である。同様に ",
        math(String.raw`\mathcal{S}_0(n)`),
        " の ",
        math(String.raw`\ell^{n}`),
        " 係数は ",
        math(String.raw`\tfrac{\ell}{\ell-1}`),
        "、定数項は ",
        math(String.raw`-\tfrac{\ell}{\ell-1}`),
        " である。(a) の ",
        math(String.raw`\Sigma_n=\sum_{M=1}^{n}\Theta_M`),
        " と (M3) より、",
        math(String.raw`n\ge M^{*}-1`),
        " で",
      ]),
      displayMath(
        String.raw`\Sigma_n=\sum_{M=1}^{M^{*}-1}\Theta_M
        +\alpha\bigl[\mathcal{S}_1(n)-\mathcal{S}_1(M^{*}\!-\!1)\bigr]
        +\beta\bigl[\mathcal{S}_0(n)-\mathcal{S}_0(M^{*}\!-\!1)\bigr]
        +\gamma\,\bigl(n-M^{*}\!+\!1\bigr)`,
      ),
      paragraph([
        "である。これを (a) の ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)=v_\ell(\kappa(X))-2n+\mu(\ell^{2n}-1)+\Sigma_n`),
        " へ代入し、",
        math(String.raw`\ell^{2n},\ n\ell^{n},\ \ell^{n},\ n,\ 1`),
        " の係数を読むと主張の ",
        math(String.raw`a,b,c,d,e`),
        " を得る（",
        math(String.raw`-2n`),
        " が ",
        math(String.raw`d=\gamma-2`),
        " の ",
        math(String.raw`-2`),
        " を、",
        math(String.raw`v_\ell(\kappa(X))-\mu`),
        " が ",
        math(String.raw`e`),
        " の先頭 2 項を与える）。",
      ]),
      paragraph([
        "**最小点の一意性の仮定が要らないこと。** (M3) の (a)(b) では最小点の一意性を仮定せず**証明して**使い、(c) では ",
        math(String.raw`\mathbb{Z}`),
        " 係数のままの最小化を経由せず (M1)（",
        math(String.raw`\mathcal{O}_k`),
        " の上での一意性）を使った。したがって ",
        math(String.raw`b=\tfrac{\ell}{\ell-1}\alpha=\sum_{P_0\in S_\infty}j^{*}(P_0)`),
        " は、",
        ref("paper_prop_J"),
        " の (J4) が置いていた仮定なしに成り立つ。**係数環を ",
        math(String.raw`\mathbb{Z}`),
        " から ",
        math(String.raw`\mathcal{O}_k`),
        " へ広げると、そのままでは起きていた最小点の同点が解ける。** これが (M1) の技術的な要点である。",
      ]),
      paragraph([
        "**(M5) の証明。** (M3) の証明が各条件をどこで使ったかを見ればよい。1 は (a) が ",
        math(String.raw`\theta|_U`),
        " の経由レベルを使うところ、3 は (a) の ",
        math(String.raw`\theta-m_1<\varphi(\ell^{M})`),
        " である。2 は (b) の望遠鏡和 ",
        math(String.raw`\sum_{s=K+1}^{M-r^\sharp}\varphi(\ell^{s})=\ell^{\,M-r^\sharp}-\ell^{K}`),
        " が成り立つ条件であり、これは ",
        math(String.raw`K\le M-r^\sharp`),
        " すなわち ",
        math(String.raw`M\ge r^\sharp+K`),
        " と同値である。4 は (M1) の適用条件そのもので、",
        math(String.raw`m^\sharp_k=\infty`),
        " の層では上で見たとおり自動的に満たされるから ",
        math(String.raw`M\ge2k`),
        " だけが残る。5 は (b) の最外層 ",
        math(String.raw`k=K+1`),
        " で (M2) の評価を成り立たせる条件である。いずれも ",
        math(String.raw`D`),
        " の係数からの有限計算だけで判定できる。",
      ]),
      paragraph([
        "**(M6) の証明。** ",
        math(String.raw`S_\infty=\emptyset`),
        " なら (M3) の (b)(c) が空で ",
        math(String.raw`U=\mathbb{P}^1(\mathbb{Z}_\ell)`),
        " なので ",
        math(String.raw`\alpha=\gamma=0`),
        "、",
        math(String.raw`\beta=A_{\mathrm{gen}}`),
        " である。",
        math(String.raw`M^{*}\le L`),
        " となるように ",
        math(String.raw`L`),
        " を取れば (a) の部分の議論から ",
        math(String.raw`\hat\theta_L=\theta`),
        " なので ",
        math(String.raw`\ell^{L}A_{\mathrm{gen}}=\sum_{P\in\mathbb{P}^1(\mathbb{Z}/\ell^{L})}\theta(P)=\Theta_L`),
        " であり、",
        math(String.raw`\tfrac{\ell}{\ell-1}\ell^{-L}=\tfrac{1}{\varphi(\ell^{L})}`),
        " から ",
        math(String.raw`c=\tfrac{\ell}{\ell-1}A_{\mathrm{gen}}=\tfrac{\Theta_L}{\varphi(\ell^{L})}`),
        " を得る。",
        math(String.raw`d=\gamma-2=-2`),
        " であり、",
        math(String.raw`e`),
        " は (M4) の式へ ",
        math(String.raw`\alpha=\gamma=0`),
        "、",
        math(String.raw`\beta=A_{\mathrm{gen}}`),
        " を代入すればよい。",
        math(String.raw`S_\infty=\emptyset`),
        " かどうかが判定できることは ",
        ref("paper_prop_K"),
        " の (K3) による。",
      ]),
    ],
  },
  {
    id: "paper_112_theorem_coefficient_layers",
    kind: "theorem",
    origin: { path: "structured-latex/content/010_general_closed_form.ts", ordinal: 3 },
    title: { text: "命題 U — 係数の情報階層（どの追加情報が要るか）と、有限精度では決まらないこと" },
    labels: ["paper_prop_U"],
    habitat: "Qbar",
    verification: ["sagemath/check/cycle22_T3_coefficients_d_e"],
    statement: [
      paragraph([
        ref("paper_prop_M"),
        " の設定と記号を引き継ぐ。各 ",
        math(String.raw`P_0\in S_\infty`),
        " に対し",
      ]),
      displayMath(
        String.raw`\mathcal{L}(P_0):=\Lambda_0+\sum_{k=1}^{K}\varphi(\ell^{k})\,\Lambda_k,
        \qquad
        \mathcal{T}(P_0):=\theta^\sharp_0+\sum_{k=1}^{K}\varphi(\ell^{k})\,\theta^\sharp_k`,
      ),
      paragraph([
        "と置く。",
        ref("paper_prop_M"),
        " (M1) の 3 番目より ",
        math(String.raw`\varphi(\ell^{k})\Lambda_k\in\mathbb{Z}_{\ge1}`),
        "、また ",
        math(String.raw`\theta^\sharp_k\in\mathbb{Z}_{\ge0}`),
        " なので、",
        math(String.raw`\mathcal{L}(P_0)`),
        " と ",
        math(String.raw`\mathcal{T}(P_0)`),
        " はどちらも非負整数である。**整数であると主張しているのは各項であって、",
        "付値そのものではない。** ",
        math(String.raw`\Lambda_k`),
        " 自身は一般に整数でない有理数であり、実際 ",
        ref("paper_prop_M"),
        " (M2) の非飽和層では ",
        math(String.raw`\Lambda_k=j^{*}/\varphi(\ell^{k})`),
        " である（",
        math(String.raw`k\ge1`),
        " でこれは一般に整数でない）。整数なのは ",
        math(String.raw`\varphi(\ell^{k})\Lambda_k`),
        " と ",
        math(String.raw`\theta^\sharp_k`),
        " である。とくに下の (U6) の条件 ",
        math(String.raw`N>\max\Lambda_k`),
        " は、整数 ",
        math(String.raw`N`),
        " と**この有理数**との比較であって、",
        math(String.raw`\varphi(\ell^{k})\Lambda_k`),
        " との比較ではない。",
      ]),
      paragraph([
        "**(U1 付値側と位置側の分業)**",
      ]),
      displayMath(
        String.raw`d=\sum_{P_0\in S_\infty}\Bigl(\mathcal{T}(P_0)-e_{j^*}(P_0)\,\ell^{K(P_0)}\Bigr)-2,`,
      ),
      displayMath(
        String.raw`c=\frac{\ell}{\ell-1}A_{\mathrm{gen}}
        +\sum_{P_0\in S_\infty}\Bigl[\frac{e_{j^*}\,\ell^{\,1-r^\sharp}}{\ell-1}
        -j^{*}\Bigl(K+r^\sharp+\frac{1}{\ell-1}\Bigr)+\mathcal{L}(P_0)\Bigr].`,
      ),
      paragraph([
        "したがって、捻り段データの**付値側** ",
        math(String.raw`\Lambda_k`),
        " は ",
        math(String.raw`c`),
        " にだけ、**位置側** ",
        math(String.raw`\theta^\sharp_k`),
        " は ",
        math(String.raw`d`),
        " にだけ現れる。とくに ",
        math(String.raw`d`),
        " は ",
        math(String.raw`S_\infty`),
        " の各点の局所量 ",
        math(String.raw`(\mathcal{T},e_{j^*},K)`),
        " だけで決まり、大域平均 ",
        math(String.raw`A_{\mathrm{gen}}`),
        " も低レベルの過渡も ",
        math(String.raw`v_\ell(\kappa(X))`),
        " も使わない。よって ",
        math(String.raw`d`),
        " は**常に整数**である（",
        math(String.raw`c`),
        " と ",
        math(String.raw`e`),
        " は ",
        math(String.raw`13/3`),
        " のような非整数の有理数になりうる）。",
        math(String.raw`S_\infty=\emptyset`),
        " なら和が空で ",
        math(String.raw`d=-2`),
        "（",
        ref("paper_prop_M"),
        " (M6) と整合）。",
        "**すなわち「次数が下がるほど難しくなる」という素朴な順序は成り立たない。** 難しさの順序は",
        math(String.raw`a,b\ \prec\ d\ \prec\ c\ \prec\ e`),
        "である。",
      ]),
      paragraph([
        "**(U1a 飽和深度を大きめに取ってもよい)** ",
        math(String.raw`K'\ge K(P_0)`),
        " を任意に取り、上の和を ",
        math(String.raw`k\le K'`),
        " まで伸ばし ",
        math(String.raw`K`),
        " を ",
        math(String.raw`K'`),
        " に置き換えても ",
        math(String.raw`c,d`),
        " は変わらない。実際 ",
        math(String.raw`K\to K+1`),
        " では深さ ",
        math(String.raw`K+1`),
        " の層が ",
        ref("paper_prop_M"),
        " (M2) より非飽和なので ",
        math(String.raw`\Lambda_{K+1}=j^{*}/\varphi(\ell^{K+1})`),
        "、",
        math(String.raw`\theta^\sharp_{K+1}=e_{j^*}`),
        " であり、",
        math(String.raw`\mathcal{T}`),
        " の増分 ",
        math(String.raw`\varphi(\ell^{K+1})e_{j^*}`),
        " と ",
        math(String.raw`-e_{j^*}\ell^{K}\to-e_{j^*}\ell^{K+1}`),
        " の変化がちょうど相殺し（",
        math(String.raw`\varphi(\ell^{K+1})-\ell^{K+1}+\ell^{K}=0`),
        "）、同様に ",
        math(String.raw`\mathcal{L}`),
        " の増分 ",
        math(String.raw`j^{*}`),
        " と ",
        math(String.raw`-j^{*}(K+r^\sharp+\frac{1}{\ell-1})`),
        " の変化が相殺する。あとは帰納法である。",
      ]),
      paragraph([
        "**(U2 定数項の分解)** ",
        math(String.raw`\Theta^{\mathrm{as}}_M:=\alpha M\ell^{M}+\beta\ell^{M}+\gamma`),
        " と置き、**過渡欠損**を",
      ]),
      displayMath(String.raw`T_{\mathrm{def}}:=\sum_{M\ge1}\bigl(\Theta_M-\Theta^{\mathrm{as}}_M\bigr)`),
      paragraph([
        "と定める。",
        ref("paper_prop_M"),
        " (M3) より ",
        math(String.raw`M\ge M^{*}`),
        " の項は ",
        math(String.raw`0`),
        " なのでこれは**有限和**であり、",
        math(String.raw`M^{*}`),
        " の取り方に依らない（",
        math(String.raw`M^{*}`),
        " 以上のどこで打ち切っても同じ値）。このとき",
      ]),
      displayMath(String.raw`e=v_\ell(\kappa(X))-a-c+T_{\mathrm{def}},`),
      paragraph(["したがって"]),
      displayMath(String.raw`c+e=v_\ell(\kappa(X))-a+T_{\mathrm{def}}.`),
      paragraph([
        "さらに ",
        math(String.raw`\delta_M:=\Theta_M-\Theta^{\mathrm{as}}_M`),
        "、",
        math(String.raw`S(n):=\sum_{M=1}^{n}\delta_M`),
        "（",
        math(String.raw`S(0)=0`),
        "）と置くと、閉形式との差はレベル ",
        math(String.raw`n`),
        " で ",
        math(String.raw`S(n)-T_{\mathrm{def}}`),
        " である。したがって次の 3 つが成り立つ。",
      ]),
      list([
        [
          "レベル ",
          math(String.raw`n`),
          " で閉形式が成り立つことと ",
          math(String.raw`S(n)=T_{\mathrm{def}}`),
          " は同値である。",
        ],
        [
          math(String.raw`T_{\mathrm{def}}=0`),
          " と同値なのは、**閉形式が最初のレベルで成り立つこと**、すなわち ",
          math(String.raw`n=0`),
          " で成り立つことである（",
          math(String.raw`S(0)=0`),
          " だから）。",
        ],
        [
          "**閉形式がすべてのレベルで成り立つこと**、すなわち全ての ",
          math(String.raw`n\ge0`),
          " で成り立つことと同値なのは、",
          math(String.raw`\Theta_M=\Theta^{\mathrm{as}}_M`),
          " が全ての ",
          math(String.raw`M\ge1`),
          " で成り立つこと（＝過渡が一切無いこと、",
          math(String.raw`\delta_M=0`),
          "）であり、これは ",
          math(String.raw`T_{\mathrm{def}}=0`),
          " より**真に強い**。",
        ],
      ]),
      paragraph([
        "3 番目の逆（",
        math(String.raw`T_{\mathrm{def}}=0`),
        " から全 ",
        math(String.raw`n\ge0`),
        "）は**言えない**。総和が ",
        math(String.raw`0`),
        " でも部分和 ",
        math(String.raw`S(n)`),
        " が ",
        math(String.raw`0`),
        " とは限らないからである。反例として ",
        math(String.raw`\Theta^{\mathrm{as}}\equiv0`),
        "、",
        math(String.raw`\Theta_1=1`),
        "、",
        math(String.raw`\Theta_2=-1`),
        "、",
        math(String.raw`\Theta_M=0\ (M\ge3)`),
        " を取ると ",
        math(String.raw`T_{\mathrm{def}}=0`),
        " だが ",
        math(String.raw`S(1)=1`),
        " で、",
        math(String.raw`n=1`),
        " では閉形式が ",
        math(String.raw`1`),
        " だけずれる。**ただしこの反例は射程が限定されている**: これは ",
        math(String.raw`\Theta`),
        " を任意に取った反例であり、実在の塔で ",
        math(String.raw`\delta_M`),
        " の符号が混ざる例は確認していない。 ",
        ref("paper_prop_M"),
        " (M4) の ",
        math(String.raw`e`),
        " の式の角括弧の正体がこの ",
        math(String.raw`T_{\mathrm{def}}`),
        " である。",
        math(String.raw`c`),
        " と ",
        math(String.raw`e`),
        " の**和**のほうが、それぞれより情報として浅い。",
      ]),
      paragraph([
        "**(U3 情報階層は 3 層である)** 以上より 5 係数は次の 3 層に分かれる。第 1 層（",
        math(String.raw`\bmod\ \ell`),
        "）は ",
        math(String.raw`\bar{\tilde E}`),
        " から読める量（content の付値、二項式因子の重複度、",
        math(String.raw`S_\infty`),
        "、",
        math(String.raw`j^{*}`),
        "、",
        math(String.raw`e_j`),
        "、",
        math(String.raw`K`),
        "、",
        math(String.raw`r^\sharp`),
        "、",
        math(String.raw`A_{\mathrm{gen}}`),
        "）であり、ここから ",
        math(String.raw`a`),
        " と ",
        math(String.raw`b`),
        " が決まる。第 2 層は第 1 層に捻り段データ ",
        math(String.raw`(\Lambda_k,\theta^\sharp_k)`),
        " を足したもので、ここから ",
        math(String.raw`c`),
        " と ",
        math(String.raw`d`),
        " が決まる。第 3 層は第 2 層に ",
        math(String.raw`v_\ell(\kappa(X))`),
        " と ",
        math(String.raw`T_{\mathrm{def}}`),
        " を足したもので、",
        math(String.raw`e`),
        " だけがこれを要する。",
        "**これが「どの追加情報が要るか」への答えである。** 以下 (U4)–(U6) は、この階層が本当に",
        "縮まないこと、すなわち第 2 層が第 1 層に還元されず、",
        math(String.raw`\ell`),
        " 進の固定桁数にも還元されないことを示す。",
      ]),
      paragraph([
        "**(U4 剰余体だけでは第 2 層は決まらない)** 切れ目は ",
        math(String.raw`b`),
        " と ",
        math(String.raw`(c,d,e)`),
        " の間にある。以下 ",
        math(String.raw`\ell=2`),
        "、",
        math(String.raw`p`),
        " を奇数とし、",
        math(String.raw`X_p`),
        " を 1 頂点 bouquet でループの voltage が ",
        math(String.raw`(1,0)`),
        " を ",
        math(String.raw`p`),
        " 本、",
        math(String.raw`(0,1)`),
        " を 1 本のものとする。このとき ",
        math(String.raw`\mu=0`),
        " であり ",
        math(String.raw`\bar{\tilde E}=z^2w+zw^2+z+w\in\mathbb{F}_2[z,w]`),
        " は奇数 ",
        math(String.raw`p`),
        " に依らない。したがって ",
        math(String.raw`S_\infty=\{(1{:}1),(1{:}-1)\}`),
        "、各点で ",
        math(String.raw`j^{*}=1`),
        "、",
        math(String.raw`e_{j^*}=2`),
        "、",
        math(String.raw`K=1`),
        "、",
        math(String.raw`r^\sharp=2`),
        "、",
        math(String.raw`A_{\mathrm{gen}}=2`),
        " も依らない。ところが各 ",
        math(String.raw`P_0\in S_\infty`),
        " で",
      ]),
      displayMath(
        String.raw`\Lambda_0=v_2(p+1),\quad\theta^\sharp_0=2,\qquad
        \Lambda_1=\min\bigl(2,\,v_2(p-1)\bigr),\qquad
        \theta^\sharp_1=\begin{cases}0&(p\equiv1\bmod4)\\ 2&(p\equiv3\bmod4)\end{cases}`,
      ),
      paragraph([
        "である。ここで ",
        math(String.raw`\min`),
        " は (M1) の規約どおり ",
        math(String.raw`A_m\neq0`),
        " となる ",
        math(String.raw`m`),
        " についてのみ取る（",
        math(String.raw`v_2(0)=+\infty`),
        "）。深さ ",
        math(String.raw`1`),
        " の係数は ",
        math(String.raw`A_0=A_1=4`),
        "、",
        math(String.raw`A_2=1-p`),
        " なので、**主役の片方は最後の係数が消える**: ",
        math(String.raw`p=1`),
        " では ",
        math(String.raw`A_2=0`),
        " であり、",
        math(String.raw`\Lambda_1=v_2(4)=2`),
        "、",
        math(String.raw`\theta^\sharp_1=0`),
        " である（",
        math(String.raw`p\equiv1\bmod4`),
        " の場合に含まれる）。この規約を落として ",
        math(String.raw`v_2(0)=0`),
        " と読むと ",
        math(String.raw`\Lambda_1=0`),
        " となり、下の値が出ない。(U1) より ",
        math(String.raw`d=2\theta^\sharp_1-6`),
        "、",
        math(String.raw`c=2\mathcal{L}-2`),
        "（",
        math(String.raw`\mathcal{L}=v_2(p+1)+\min(2,v_2(p-1))`),
        "）である。とくに ",
        math(String.raw`p=1`),
        " と ",
        math(String.raw`p=3`),
        " は ",
        math(String.raw`\bar{\tilde E}`),
        " も ",
        math(String.raw`\mu`),
        " も等しいのに",
      ]),
      displayMath(String.raw`(a,b,c,d,e)=(0,2,4,-6,-1)`),
      paragraph(["と"]),
      displayMath(String.raw`(a,b,c,d,e)=(0,2,4,-2,-4)`),
      paragraph([
        "で、",
        math(String.raw`d`),
        " と ",
        math(String.raw`e`),
        " が違う。**したがって、第 2 層の 3 係数はいずれも剰余体上の還元の関数ではない。** 記号で書けば ",
        math(String.raw`c,d,e`),
        " のいずれも ",
        math(String.raw`\bar{\tilde E}`),
        " の関数ではないということである。ここで反例に使ったのは**実在の voltage グラフ 2 本**であって ",
        math(String.raw`\tilde E`),
        " への人工的な摂動ではないので、「グラフに限れば ",
        math(String.raw`\bar{\tilde E}`),
        " から読める式があるかもしれない」という逃げ道も塞がっている。",
        "なおこの対では ",
        math(String.raw`\mathcal{L}`),
        " が偶然一致して ",
        math(String.raw`c`),
        " が同じになる。",
        math(String.raw`c`),
        " の反例と ",
        math(String.raw`d`),
        " の反例は独立に要る、ということである。",
      ]),
      paragraph([
        "**(U5 どんな固定精度でも足りない)** ",
        math(String.raw`\ell=2`),
        " とする。",
      ]),
      list([
        [
          "（",
          math(String.raw`c`),
          " の側）",
          math(String.raw`X_t`),
          " を 1 頂点 bouquet でループの voltage が ",
          math(String.raw`(1,0)`),
          "、",
          math(String.raw`(0,1)`),
          " 各 1 本と ",
          math(String.raw`(1,-1)`),
          " を ",
          math(String.raw`t`),
          " 本のものとする。任意の ",
          math(String.raw`N\ge2`),
          " に対し ",
          math(String.raw`t=2^{N+1}-1`),
          " と ",
          math(String.raw`t'=3\cdot2^{N}-1`),
          " は ",
          math(String.raw`\tilde E_{X_t}\equiv\tilde E_{X_{t'}}\pmod{2^{N}}`),
          "（したがって ",
          math(String.raw`\bar{\tilde E}`),
          " も ",
          math(String.raw`\mu`),
          " も同じ）でありながら ",
          math(String.raw`c`),
          " が ",
          math(String.raw`3`),
          " だけ違う。このとき ",
          math(String.raw`\theta^\sharp`),
          " は 4 箇所とも不変なので ",
          math(String.raw`d`),
          " は変わらない。",
        ],
        [
          "（",
          math(String.raw`d`),
          " の側）",
          math(String.raw`Y_{p,q,t}`),
          " を 1 頂点 bouquet でループの voltage が ",
          math(String.raw`(1,0)`),
          " を ",
          math(String.raw`p`),
          " 本、",
          math(String.raw`(0,1)`),
          " を ",
          math(String.raw`q`),
          " 本、",
          math(String.raw`(1,-1)`),
          " を ",
          math(String.raw`t`),
          " 本のものとする。",
          math(String.raw`P_0=(0{:}1)`),
          " の深さ ",
          math(String.raw`1`),
          " の係数は ",
          math(String.raw`A_0=A_1=4(p+t)`),
          "、",
          math(String.raw`A_2=t-q`),
          " であり、ここでも ",
          math(String.raw`\min`),
          " は ",
          math(String.raw`A_m\neq0`),
          " の ",
          math(String.raw`m`),
          " に限る（",
          math(String.raw`t=q`),
          " では ",
          math(String.raw`A_2=0`),
          " なので ",
          math(String.raw`\Lambda_1=v_2(4(p+t))`),
          "、",
          math(String.raw`\theta^\sharp_1=0`),
          "）。任意の ",
          math(String.raw`N\ge1`),
          " に対し ",
          math(String.raw`t=1`),
          "、",
          math(String.raw`q=1+2^{N+2}`),
          "、",
          math(String.raw`p=2^{N+1}-1`),
          " と ",
          math(String.raw`p'=p+2^{N}`),
          " を取ると（この具体化では ",
          math(String.raw`t\neq q`),
          " なので上の境界には触れない）、",
          math(String.raw`\tilde E_{Y_{p,q,t}}\equiv\tilde E_{Y_{p',q,t}}\pmod{2^{N}}`),
          " で、",
          math(String.raw`\Lambda_1`),
          " は ",
          math(String.raw`N+2`),
          " のまま**不変**なのに ",
          math(String.raw`\theta^\sharp_1`),
          " が ",
          math(String.raw`2`),
          " から ",
          math(String.raw`0`),
          " へ変わり、",
          math(String.raw`d`),
          " が ",
          math(String.raw`2`),
          " だけ違う。",
        ],
      ]),
      paragraph([
        "**したがって、剰余環へ落とす桁数をどれだけ固定しても、そこから第 2 層の係数を読む式は存在しない。** ",
        "落とす先を ",
        math(String.raw`\tilde E\bmod\ell^{N}`),
        " と書けば、",
        math(String.raw`c`),
        " を読む式も ",
        math(String.raw`d`),
        " を読む式も、どんな固定した ",
        math(String.raw`N`),
        " に対しても存在しないということである。しかも位置側（",
        math(String.raw`d`),
        "）の障害は付値側（",
        math(String.raw`c`),
        "）の障害の系ではない。2 番目の族では ",
        math(String.raw`\Lambda_1`),
        " が不変のまま ",
        math(String.raw`\theta^\sharp_1`),
        " だけが動いているからである。",
      ]),
      paragraph([
        "**(U6 逆向き — 精度が足りる条件)** 逆に ",
        math(String.raw`N\in\mathbb{Z}_{\ge1}`),
        " が",
      ]),
      displayMath(
        String.raw`N>\max_{P_0\in S_\infty}\ \max_{0\le k\le K(P_0)}\Lambda_k(P_0)`,
      ),
      paragraph([
        "を満たすならば、",
        math(String.raw`\tilde E\bmod\ell^{N}`),
        " が ",
        math(String.raw`(\Lambda_k,\theta^\sharp_k)_{k\le K}`),
        " を、したがって ",
        math(String.raw`c`),
        " と ",
        math(String.raw`d`),
        " を決める。実際 ",
        math(String.raw`\tilde E'=\tilde E+\ell^{N}h`),
        " と置くと ",
        math(String.raw`\Phi^{[k]}`),
        " は係数の ",
        math(String.raw`\mathcal{O}_k`),
        " 係数線形式なので ",
        math(String.raw`A'^{[k]}_m=A^{[k]}_m+\ell^{N}\beta_m`),
        " となり、**切り捨て付きの付値列** ",
        math(String.raw`\bigl(\min(v_\ell(A^{[k]}_m),N)\bigr)_m`),
        " が ",
        math(String.raw`\tilde E\bmod\ell^{N}`),
        " で決まる。上の条件より ",
        math(String.raw`\Lambda_k<N`),
        " なので、",
        math(String.raw`\Lambda_k`),
        " とその最小を最初に達成する添字 ",
        math(String.raw`\theta^\sharp_k`),
        " はこの列から読める。",
        "この条件は一見自己言及だが実用上は循環しない: 与えられた ",
        math(String.raw`N`),
        " で切り捨て付き付値列を計算し、最小値が ",
        math(String.raw`N`),
        " 未満であれば、その ",
        math(String.raw`N`),
        " が十分だったことがその計算自体から確認できる。",
        "**必要精度は各塔について有限かつ計算可能だが、塔を渡ると上に有界でない**（それが (U5)）。",
      ]),
      paragraph([
        "**限界（主張の一部として述べる）**",
      ]),
      list([
        [
          "**第 3 層が余計でないこと**（第 2 層と ",
          math(String.raw`v_\ell(\kappa(X))`),
          " をすべて知っても ",
          math(String.raw`e`),
          " が決まらないこと）は、そのような塔の組が存在するという**存在主張**であり、",
          "母集団の走査で見つけた実例で支えている（存在を示すには例で足りる）。一般の証明ではない。",
        ],
        [
          "(U6) は ",
          math(String.raw`c,d`),
          " についてのものである。",
          math(String.raw`e`),
          " には ",
          math(String.raw`T_{\mathrm{def}}`),
          " が入り、そこには低レベルの ",
          math(String.raw`\Theta_M`),
          " すなわちいくらでも深い付値が現れるので、",
          "**定数項の必要精度の明示形は与えていない。**",
        ],
        [
          "**射程は、階数 2・仮定 (H)・voltage グラフのラプラシアン行列式型に限る。** ",
          ref("paper_prop_M"),
          " と同じ限定であり、記号で書けば ",
          math(String.raw`d=2`),
          " かつ対象は ",
          math(String.raw`\det L`),
          " の形のものだけである。",
        ],
        [
          "**新規性は主張しない。** ",
          math(String.raw`\ell^{n}`),
          " 以下の係数が ",
          math(String.raw`\bmod\ \ell`),
          " では決まらないこと（",
          math(String.raw`\mu,\lambda`),
          " の下の項がより深い情報を要すること）は岩澤理論では標準的な認識である。",
          "本命題が足しているのは、その「より深い情報」が ",
          math(String.raw`\mathbb{Z}[\zeta_{\ell^{k}}]`),
          " 上の段データで**尽きる**という有限性と、",
          math(String.raw`\ell`),
          " 進の固定桁数では足りないことを反例で確定させた点である。",
        ],
      ]),
    ],
    proof: [
      paragraph([
        "**証明が外から使うのは ",
        ref("paper_prop_M"),
        " と ",
        ref("paper_prop_K"),
        " だけである。** 使う形をその都度明示する。",
      ]),
      paragraph([
        "**(U1) の証明。** ",
        math(String.raw`d`),
        " の式は ",
        ref("paper_prop_M"),
        " (M3) の ",
        math(String.raw`\gamma`),
        " と (M4) の ",
        math(String.raw`d=\gamma-2`),
        " を ",
        math(String.raw`\mathcal{T}`),
        " の記号で書き直したものにすぎない。",
        math(String.raw`c`),
        " の式は (M4) の ",
        math(String.raw`c=\tfrac{\ell}{\ell-1}\beta-\tfrac{\ell}{(\ell-1)^{2}}\alpha`),
        " へ (M3) の ",
        math(String.raw`\beta`),
        " と ",
        math(String.raw`\alpha`),
        " を代入して得る。実際",
      ]),
      displayMath(
        String.raw`\frac{\ell}{\ell-1}\beta=\frac{\ell}{\ell-1}A_{\mathrm{gen}}
        +\sum_{P_0\in S_\infty}\Bigl[\frac{e_{j^*}\,\ell^{\,1-r^\sharp}}{\ell-1}
        -j^{*}\bigl(K+r^\sharp\bigr)+\mathcal{L}(P_0)\Bigr],`,
      ),
      displayMath(
        String.raw`\frac{\ell}{(\ell-1)^{2}}\alpha
        =\frac{\ell}{(\ell-1)^{2}}\cdot\frac{\ell-1}{\ell}\sum_{P_0\in S_\infty}j^{*}
        =\frac{1}{\ell-1}\sum_{P_0\in S_\infty}j^{*}`,
      ),
      paragraph([
        "であり、差を取ると主張の ",
        math(String.raw`c`),
        " の式になる。分業と整数性は右辺を見れば読める。",
        math(String.raw`\Lambda_k`),
        " は ",
        math(String.raw`\mathcal{L}`),
        " を通じて ",
        math(String.raw`c`),
        " にだけ、",
        math(String.raw`\theta^\sharp_k`),
        " は ",
        math(String.raw`\mathcal{T}`),
        " を通じて ",
        math(String.raw`d`),
        " にだけ現れる。",
        math(String.raw`d`),
        " が整数であることは、冒頭で見た ",
        math(String.raw`\mathcal{T}\in\mathbb{Z}`),
        " と、",
        math(String.raw`e_{j^*}\in\mathbb{Z}`),
        "（",
        ref("paper_prop_J"),
        " の (J2) の ",
        math(String.raw`e_j`),
        " は ",
        math(String.raw`\mathrm{ord}_{x=0}`),
        " なので整数）、",
        math(String.raw`K\in\mathbb{Z}_{\ge0}`),
        " から従う。一方 ",
        math(String.raw`c`),
        " の式には分母 ",
        math(String.raw`\ell-1`),
        " をもつ 3 項 ",
        math(String.raw`\tfrac{\ell}{\ell-1}A_{\mathrm{gen}}`),
        "、",
        math(String.raw`\tfrac{e_{j^*}\ell^{\,1-r^\sharp}}{\ell-1}`),
        "、",
        math(String.raw`\tfrac{j^{*}}{\ell-1}`),
        " が入るので、",
        math(String.raw`c`),
        " は整数でない有理数になりうる。",
        math(String.raw`S_\infty=\emptyset`),
        " なら和が空で ",
        math(String.raw`d=-2`),
        " となり ",
        ref("paper_prop_M"),
        " (M6) と整合する。難しさの順序は (U3) が挙げる各層の入力データの包含関係そのものである。",
      ]),
      paragraph([
        "**(U1a) の証明。** ",
        math(String.raw`K'=K+1`),
        " の場合を示せば十分である（あとは帰納法）。深さ ",
        math(String.raw`K+1`),
        " の層は ",
        ref("paper_prop_M"),
        " (M2) より非飽和なので ",
        math(String.raw`\Lambda_{K+1}=j^{*}/\varphi(\ell^{K+1})`),
        "、",
        math(String.raw`\theta^\sharp_{K+1}=e_{j^*}`),
        " である。",
        math(String.raw`d`),
        " の式では ",
        math(String.raw`\mathcal{T}`),
        " が ",
        math(String.raw`\varphi(\ell^{K+1})e_{j^*}`),
        " だけ増え、",
        math(String.raw`-e_{j^*}\ell^{K}`),
        " が ",
        math(String.raw`-e_{j^*}\ell^{K+1}`),
        " になるので、変化は",
      ]),
      displayMath(
        String.raw`e_{j^*}\bigl(\varphi(\ell^{K+1})-\ell^{K+1}+\ell^{K}\bigr)
        =e_{j^*}\bigl((\ell^{K+1}-\ell^{K})-\ell^{K+1}+\ell^{K}\bigr)=0`,
      ),
      paragraph([
        "である。",
        math(String.raw`c`),
        " の式では ",
        math(String.raw`\mathcal{L}`),
        " が ",
        math(String.raw`\varphi(\ell^{K+1})\cdot\tfrac{j^{*}}{\varphi(\ell^{K+1})}=j^{*}`),
        " だけ増え、",
        math(String.raw`-j^{*}\bigl(K+r^\sharp+\tfrac{1}{\ell-1}\bigr)`),
        " が ",
        math(String.raw`-j^{*}\bigl(K+1+r^\sharp+\tfrac{1}{\ell-1}\bigr)`),
        " になるので、変化は ",
        math(String.raw`j^{*}-j^{*}=0`),
        " である。",
      ]),
      paragraph([
        "**(U2) の証明。まず ",
        math(String.raw`M^{*}`),
        " 非依存性。** ",
        ref("paper_prop_M"),
        " (M3) より ",
        math(String.raw`M\ge M^{*}`),
        " の項は ",
        math(String.raw`0`),
        " なので、",
        math(String.raw`M^{*}`),
        " 以上のどこで打ち切っても和は同じである。**次に ",
        math(String.raw`e`),
        " の式。** ",
        ref("paper_prop_M"),
        " (M4) の ",
        math(String.raw`e`),
        " の式の角括弧は",
      ]),
      displayMath(
        String.raw`\sum_{M=1}^{M^{*}-1}\Theta_M-\alpha\,\mathcal{S}_1(M^{*}\!-\!1)
        -\beta\,\mathcal{S}_0(M^{*}\!-\!1)-\gamma(M^{*}\!-\!1)
        =\sum_{M=1}^{M^{*}-1}\bigl(\Theta_M-\Theta^{\mathrm{as}}_M\bigr)=T_{\mathrm{def}}`,
      ),
      paragraph([
        "である（",
        math(String.raw`\mathcal{S}_1`),
        " と ",
        math(String.raw`\mathcal{S}_0`),
        " の定義をそのまま展開しただけである）。また ",
        ref("paper_prop_M"),
        " (M4) より ",
        math(String.raw`\tfrac{\ell}{(\ell-1)^{2}}\alpha-\tfrac{\ell}{\ell-1}\beta=-c`),
        " であり ",
        math(String.raw`\mu=a`),
        " なので、代入して ",
        math(String.raw`e=v_\ell(\kappa(X))-a-c+T_{\mathrm{def}}`),
        "、移項して ",
        math(String.raw`c+e`),
        " の式を得る。",
      ]),
      paragraph([
        "**3 つの同値。** ",
        math(String.raw`\delta_M`),
        " と ",
        math(String.raw`S(n)`),
        " を主張のとおり置く。",
        ref("paper_prop_R"),
        " の (R5) が与える ",
        math(String.raw`\mathrm{ord}_\ell(\kappa_n)`),
        " の表示は ",
        math(String.raw`\Sigma_n=\sum_{M=1}^{n}\Theta_M`),
        " で書かれているので、",
        math(String.raw`\Theta^{\mathrm{as}}`),
        " に ",
        ref("paper_prop_M"),
        " (M4) の計算をそのまま適用すると、レベル ",
        math(String.raw`n`),
        " における「実際の値」と「5 係数形の値（",
        math(String.raw`e`),
        " は上の式）」の差がちょうど ",
        math(String.raw`S(n)-T_{\mathrm{def}}`),
        " になる（",
        math(String.raw`n\ge0`),
        "）。したがってレベル ",
        math(String.raw`n`),
        " で閉形式が成り立つことと ",
        math(String.raw`S(n)=T_{\mathrm{def}}`),
        " は同値である。",
        math(String.raw`n=0`),
        " では ",
        math(String.raw`S(0)=0`),
        " なので 2 番目が出る。全ての ",
        math(String.raw`n\ge0`),
        " で成り立つことは ",
        math(String.raw`S`),
        " が定数 ",
        math(String.raw`T_{\mathrm{def}}`),
        " であることと同値で、これは ",
        math(String.raw`\delta_M=0`),
        "（全 ",
        math(String.raw`M\ge1`),
        "）と同値であり、このとき ",
        math(String.raw`T_{\mathrm{def}}=0`),
        " も従うので 2 番目より真に強い。逆向きが言えないことは主張に書いた反例が示す。**総和が ",
        math(String.raw`0`),
        " でも部分和が ",
        math(String.raw`0`),
        " とは限らない、というのが要点である。**",
      ]),
      paragraph([
        "**(U3) の証明。** (U1) より ",
        math(String.raw`c`),
        " と ",
        math(String.raw`d`),
        " は第 1 層のデータと ",
        math(String.raw`(\Lambda_k,\theta^\sharp_k)_{k\le K}`),
        " だけで書け、(U2) より ",
        math(String.raw`e`),
        " はさらに ",
        math(String.raw`v_\ell(\kappa(X))`),
        " と ",
        math(String.raw`T_{\mathrm{def}}`),
        " を要する。",
        math(String.raw`a=\mu`),
        " と ",
        math(String.raw`b=\sum j^{*}`),
        " が第 1 層で決まることは ",
        ref("paper_prop_K"),
        " の (K6) と ",
        ref("paper_prop_M"),
        " (M4) による。あとは (U4)(U5) が、第 2 層が第 1 層へも ",
        math(String.raw`\ell`),
        " 進の固定桁数へも還元されないことを示す。",
      ]),
      paragraph([
        "**(U4) の証明。まず第 1 層が ",
        math(String.raw`p`),
        " に依らないこと。** ",
        math(String.raw`D=p(2-z-z^{-1})+(2-w-w^{-1})`),
        " の係数は ",
        math(String.raw`2p+2,-p,-p,-1,-1`),
        " で content は ",
        math(String.raw`1`),
        "、よって ",
        math(String.raw`\mu=0`),
        "、",
        math(String.raw`E=D`),
        "、",
        math(String.raw`\tilde E=zwD`),
        " である。",
        math(String.raw`p`),
        " が奇数なら ",
        math(String.raw`\bmod\ 2`),
        " で ",
        math(String.raw`p\equiv1`),
        " なので ",
        math(String.raw`\bar{\tilde E}=z^{2}w+w+zw^{2}+z`),
        " となり、これは ",
        math(String.raw`p`),
        " に依らない。",
        ref("paper_prop_K"),
        " の (K2)(K3)(K4) が ",
        math(String.raw`\bar{\tilde E}`),
        " だけから決める量（",
        math(String.raw`S_\infty`),
        "、",
        math(String.raw`j^{*}`),
        "、",
        math(String.raw`e_j`),
        "）はすべて ",
        math(String.raw`p`),
        " に依らない。",
        math(String.raw`r^\sharp`),
        " については ",
        math(String.raw`\det\bigl((1,1),(1,-1)\bigr)=-2`),
        " より (K5) の ",
        math(String.raw`r_0=2`),
        " であり、",
        math(String.raw`j^{*}=1`),
        " が唯一の最小点なので ",
        math(String.raw`R'=r_0`),
        "、したがって ",
        math(String.raw`r^\sharp=2`),
        " である。",
      ]),
      paragraph([
        "**次に段データ。** ",
        math(String.raw`P_0=(1{:}1)`),
        " を取る（",
        math(String.raw`u=(1,1)`),
        " に対し ",
        math(String.raw`\det(u,\mathbf{e})=1`),
        " なる ",
        math(String.raw`\mathbf{e}=(0,1)`),
        "）。",
        math(String.raw`y:=1+x`),
        " と書く。",
        math(String.raw`k=0`),
        "（",
        math(String.raw`\eta=1`),
        "）では ",
        math(String.raw`\Phi_u(x)=D(y,y)=(p+1)(2-y-y^{-1})=-(p+1)x^{2}y^{-1}`),
        " で、",
        math(String.raw`y^{-1}`),
        " は単元だから ",
        math(String.raw`\Lambda_0=v_2(p+1)`),
        "、",
        math(String.raw`\theta^\sharp_0=2`),
        " である。",
        math(String.raw`k=1`),
        "（",
        math(String.raw`\eta=-1`),
        "）では ",
        math(String.raw`\Phi^{[1]}_u(x)=D(y,-y)=p(2-y-y^{-1})+(2+y+y^{-1})`),
        " で、単元 ",
        math(String.raw`y`),
        " を掛けて ",
        math(String.raw`(1-p)y^{2}+(2p+2)y+(1-p)`),
        "、",
        math(String.raw`y=1+x`),
        " を代入して",
      ]),
      displayMath(
        String.raw`A_0=(1-p)+(2p+2)+(1-p)=4,\qquad A_1=2(1-p)+(2p+2)=4,\qquad A_2=1-p`,
      ),
      paragraph([
        "を得る。よって ",
        math(String.raw`\Lambda_1=\min\bigl(v_2(4),v_2(1-p)\bigr)=\min\bigl(2,v_2(p-1)\bigr)`),
        " であり、最小を最初に達成する添字は ",
        math(String.raw`v_2(p-1)\ge2`),
        " なら ",
        math(String.raw`m=0`),
        "、",
        math(String.raw`v_2(p-1)=1`),
        " なら ",
        math(String.raw`m=2`),
        " である。",
        math(String.raw`p`),
        " は奇数なので ",
        math(String.raw`v_2(p-1)\ge1`),
        " であり、",
        math(String.raw`v_2(p-1)\ge2\iff p\equiv1\bmod4`),
        " である。",
        math(String.raw`p=1`),
        " では ",
        math(String.raw`A_2=0`),
        " なので、",
        ref("paper_prop_M"),
        " (M1) の規約により ",
        math(String.raw`\min`),
        " は ",
        math(String.raw`A_0,A_1`),
        " だけで取り、",
        math(String.raw`\Lambda_1=v_2(4)=2`),
        "、",
        math(String.raw`\theta^\sharp_1=0`),
        " である（",
        math(String.raw`p\equiv1\bmod4`),
        " の場合に含まれる）。",
        math(String.raw`P_0=(1{:}-1)`),
        " は ",
        math(String.raw`D`),
        " が ",
        math(String.raw`w\mapsto w^{-1}`),
        " で不変なことから同じ値になる。",
      ]),
      paragraph([
        "**最後に係数の値。** (U1) に代入する。",
        math(String.raw`|S_\infty|=2`),
        "、各点で ",
        math(String.raw`\mathcal{T}=\theta^\sharp_0+\varphi(2)\theta^\sharp_1=2+\theta^\sharp_1`),
        "、",
        math(String.raw`e_{j^*}\ell^{K}=2\cdot2=4`),
        " なので ",
        math(String.raw`d=2\bigl((2+\theta^\sharp_1)-4\bigr)-2=2\theta^\sharp_1-6`),
        " である。",
        math(String.raw`c`),
        " については ",
        math(String.raw`\ell=2`),
        "、",
        math(String.raw`r^\sharp=2`),
        "、",
        math(String.raw`A_{\mathrm{gen}}=2`),
        "、",
        math(String.raw`j^{*}=1`),
        "、",
        math(String.raw`K=1`),
        " より、点ごとの角括弧が ",
        math(String.raw`\tfrac{2\cdot2^{-1}}{1}-1\cdot(1+2+1)+\mathcal{L}=\mathcal{L}-3`),
        " となるので ",
        math(String.raw`c=2\cdot2+2(\mathcal{L}-3)=2\mathcal{L}-2`),
        " である。",
        math(String.raw`p=1`),
        " では ",
        math(String.raw`\theta^\sharp_1=0`),
        "、",
        math(String.raw`\mathcal{L}=1+2=3`),
        " なので ",
        math(String.raw`(c,d)=(4,-6)`),
        "、",
        math(String.raw`p=3`),
        " では ",
        math(String.raw`\theta^\sharp_1=2`),
        "、",
        math(String.raw`\mathcal{L}=2+1=3`),
        " なので ",
        math(String.raw`(c,d)=(4,-2)`),
        " である。",
        math(String.raw`e`),
        " は (U2) より ",
        math(String.raw`e=0-0-c+T_{\mathrm{def}}=-4+T_{\mathrm{def}}`),
        " であり、",
        math(String.raw`T_{\mathrm{def}}`),
        " の値 ",
        math(String.raw`3`),
        "（",
        math(String.raw`p=1`),
        "）と ",
        math(String.raw`0`),
        "（",
        math(String.raw`p=3`),
        "）は有限和なので有限計算で求まる（本命題に紐づけた数値検証で計算した）。よって ",
        math(String.raw`e=-1`),
        " と ",
        math(String.raw`e=-4`),
        " である。**この対では付値側の和が偶然一致するので第 3 の係数は同じになり、違うのは第 4 と第 5 の係数である。** ",
        "記号で書けば ",
        math(String.raw`\mathcal{L}`),
        " が一致して ",
        math(String.raw`c`),
        " が同じになり、",
        math(String.raw`d`),
        " と ",
        math(String.raw`e`),
        " が違うということである。",
      ]),
      paragraph([
        "**(U5) の証明。",
        math(String.raw`c`),
        " の側。** ",
        math(String.raw`D=(2-z-z^{-1})+(2-w-w^{-1})+t(2-zw^{-1}-z^{-1}w)`),
        " の係数は ",
        math(String.raw`4+2t,-1,-1,-1,-1,-t,-t`),
        " で content は ",
        math(String.raw`1`),
        "、よって ",
        math(String.raw`\mu=0`),
        " である。",
        math(String.raw`t`),
        " が奇数なら ",
        math(String.raw`\bmod\ 2`),
        " で ",
        math(String.raw`\bar{\tilde E}=z^{2}w+zw^{2}+z+w+z^{2}+w^{2}=(z+w)(z+1)(w+1)`),
        " であり、二項式因子はどれも重複度 ",
        math(String.raw`1`),
        " なので ",
        ref("paper_prop_K"),
        " の (K4) より ",
        math(String.raw`j^{*}=1`),
        "、",
        math(String.raw`S_\infty=\{(1{:}0),(0{:}1),(1{:}1)\}`),
        " である。段データは 4 通りの制限を計算すれば出る（",
        math(String.raw`y=1+x`),
        "、",
        math(String.raw`\eta=-1`),
        "）。",
      ]),
      list([
        [
          math(String.raw`P_0=(1{:}1)`),
          "、",
          math(String.raw`\mathbf{e}=(0,1)`),
          "、",
          math(String.raw`k=0`),
          ": ",
          math(String.raw`(z,w)=(y,y)`),
          " で ",
          math(String.raw`zw^{-1}=z^{-1}w=1`),
          " だから ",
          math(String.raw`\Phi_u=2(2-y-y^{-1})=-2x^{2}y^{-1}`),
          "。よって ",
          math(String.raw`\Lambda_0=1`),
          "、",
          math(String.raw`\theta^\sharp_0=2`),
          " で、どちらも ",
          math(String.raw`t`),
          " に依らない。",
        ],
        [
          math(String.raw`P_0=(1{:}1)`),
          "、",
          math(String.raw`k=1`),
          ": ",
          math(String.raw`(z,w)=(y,-y)`),
          " で ",
          math(String.raw`\Phi^{[1]}_u=(2-y-y^{-1})+(2+y+y^{-1})+t(2+1+1)=4(t+1)`),
          "、すなわち定数である。よって ",
          math(String.raw`\Lambda_1=2+v_2(t+1)`),
          "、",
          math(String.raw`\theta^\sharp_1=0`),
          "（",
          math(String.raw`t`),
          " に依らない）。",
        ],
        [
          math(String.raw`P_0=(0{:}1)`),
          "、",
          math(String.raw`\mathbf{e}=(-1,0)`),
          "、",
          math(String.raw`k=0`),
          ": ",
          math(String.raw`(z,w)=(1,y)`),
          " で ",
          math(String.raw`\Phi_u=(1+t)(2-y-y^{-1})`),
          "。よって ",
          math(String.raw`\Lambda_0=v_2(t+1)`),
          "、",
          math(String.raw`\theta^\sharp_0=2`),
          "。",
        ],
        [
          math(String.raw`P_0=(0{:}1)`),
          "、",
          math(String.raw`k=1`),
          ": ",
          math(String.raw`(z,w)=(-1,y)`),
          " で ",
          math(String.raw`\Phi^{[1]}_u=4+(2-y-y^{-1})+t(2+y+y^{-1})=(6+2t)+(t-1)(y+y^{-1})`),
          "。単元 ",
          math(String.raw`y`),
          " を掛けて ",
          math(String.raw`y=1+x`),
          " を代入すると ",
          math(String.raw`A_0=A_1=4(t+1)`),
          "、",
          math(String.raw`A_2=t-1`),
          " なので ",
          math(String.raw`\Lambda_1=\min\bigl(2+v_2(t+1),\,v_2(t-1)\bigr)`),
          " であり、",
          math(String.raw`\theta^\sharp_1`),
          " は ",
          math(String.raw`v_2(t-1)<2+v_2(t+1)`),
          " なら ",
          math(String.raw`2`),
          "、そうでなければ ",
          math(String.raw`0`),
          " である。",
        ],
      ]),
      paragraph([
        math(String.raw`P_0=(1{:}0)`),
        " は ",
        math(String.raw`D`),
        " が ",
        math(String.raw`z\leftrightarrow w`),
        " で不変なので ",
        math(String.raw`P_0=(0{:}1)`),
        " と同じである。さて ",
        math(String.raw`t=2^{N+1}-1`),
        "、",
        math(String.raw`t'=3\cdot2^{N}-1`),
        " とすると ",
        math(String.raw`t'-t=2^{N}`),
        " なので差は ",
        math(String.raw`2^{N}(2-zw^{-1}-z^{-1}w)`),
        " であり、係数はすべて ",
        math(String.raw`2^{N}`),
        " の倍数、すなわち ",
        math(String.raw`\tilde E_{X_t}\equiv\tilde E_{X_{t'}}\pmod{2^{N}}`),
        " である。",
        math(String.raw`\mu`),
        " はどちらも ",
        math(String.raw`0`),
        "、",
        math(String.raw`t,t'`),
        " とも奇数なので ",
        math(String.raw`\bar{\tilde E}`),
        " も一致する。",
        math(String.raw`v_2(t+1)=N+1`),
        "、",
        math(String.raw`v_2(t'+1)=N`),
        " であり、",
        math(String.raw`N\ge2`),
        " のとき ",
        math(String.raw`v_2(t-1)=v_2(2^{N+1}-2)=1`),
        "、",
        math(String.raw`v_2(t'-1)=v_2(3\cdot2^{N}-2)=1`),
        " である。したがって上の表より段データの変化は ",
        math(String.raw`\Lambda_1\bigl((1{:}1)\bigr)`),
        " が ",
        math(String.raw`N+3\to N+2`),
        "、",
        math(String.raw`\Lambda_0\bigl((0{:}1)\bigr)`),
        " と ",
        math(String.raw`\Lambda_0\bigl((1{:}0)\bigr)`),
        " が ",
        math(String.raw`N+1\to N`),
        " の 3 箇所だけである。",
        math(String.raw`(0{:}1),(1{:}0)`),
        " の ",
        math(String.raw`\Lambda_1`),
        " は ",
        math(String.raw`\min(\cdot,1)=1`),
        " で不変であり、",
        math(String.raw`\theta^\sharp`),
        " は 4 箇所とも不変である。",
        math(String.raw`K`),
        "、",
        math(String.raw`e_{j^*}`),
        "、",
        math(String.raw`r^\sharp`),
        "、",
        math(String.raw`A_{\mathrm{gen}}`),
        " は ",
        math(String.raw`\bar{\tilde E}`),
        " から決まるので不変である。(U1) の ",
        math(String.raw`c`),
        " の式で ",
        math(String.raw`\mathcal{L}`),
        " の係数は ",
        math(String.raw`1`),
        " なので、",
        math(String.raw`c`),
        " は ",
        math(String.raw`\sum_{P_0\in S_\infty}\mathcal{L}(P_0)`),
        " の減少分、すなわち ",
        math(String.raw`3`),
        " だけ減る。",
        math(String.raw`\theta^\sharp`),
        " が 4 箇所とも不変なので ",
        math(String.raw`d`),
        " は不変である。",
      ]),
      paragraph([
        "**",
        math(String.raw`d`),
        " の側。** ",
        math(String.raw`D=p(2-z-z^{-1})+q(2-w-w^{-1})+t(2-zw^{-1}-z^{-1}w)`),
        " とし、",
        math(String.raw`P_0=(0{:}1)`),
        "、",
        math(String.raw`u=(0,1)`),
        "、",
        math(String.raw`\mathbf{e}=(-1,0)`),
        "、",
        math(String.raw`\eta=-1`),
        "、",
        math(String.raw`y=1+x`),
        " とする。",
        math(String.raw`(z,w)=(-1,y)`),
        " を代入すると ",
        math(String.raw`z+z^{-1}\mapsto-2`),
        "、",
        math(String.raw`zw^{-1}+z^{-1}w\mapsto-(y+y^{-1})`),
        " なので",
      ]),
      displayMath(
        String.raw`\Phi^{[1]}_u(x)=4p+q\bigl(2-y-y^{-1}\bigr)+t\bigl(2+y+y^{-1}\bigr)
        =4p+2q+2t+(t-q)\bigl(y+y^{-1}\bigr)`,
      ),
      paragraph([
        "であり、単元 ",
        math(String.raw`y`),
        " を掛けて ",
        math(String.raw`y=1+x`),
        " を代入すると ",
        math(String.raw`A_0=A_1=4(p+t)`),
        "、",
        math(String.raw`A_2=t-q`),
        " を得る。具体化する。",
        math(String.raw`t=1`),
        "、",
        math(String.raw`p=2^{N+1}-1`),
        " より ",
        math(String.raw`p+t=2^{N+1}`),
        " で ",
        math(String.raw`v_2\bigl(4(p+t)\bigr)=N+3`),
        "、",
        math(String.raw`q=1+2^{N+2}`),
        " より ",
        math(String.raw`t-q=-2^{N+2}`),
        " で ",
        math(String.raw`v_2(t-q)=N+2`),
        " である。よって ",
        math(String.raw`\Lambda_1=N+2`),
        " で、最小を達成するのは ",
        math(String.raw`A_2`),
        " だけだから ",
        math(String.raw`\theta^\sharp_1=2`),
        " である。",
        math(String.raw`p'=p+2^{N}`),
        " では ",
        math(String.raw`p'+t=3\cdot2^{N}`),
        " で ",
        math(String.raw`v_2\bigl(4(p'+t)\bigr)=N+2`),
        " なので ",
        math(String.raw`\Lambda_1=\min(N+2,N+2)=N+2`),
        " は変わらないが、最小を**最初に**達成するのは ",
        math(String.raw`A_0`),
        " なので ",
        math(String.raw`\theta^\sharp_1=0`),
        " へ変わる。",
      ]),
      paragraph([
        math(String.raw`D`),
        " の差は ",
        math(String.raw`2^{N}(2-z-z^{-1})`),
        " で係数はすべて ",
        math(String.raw`2^{N}`),
        " の倍数、",
        math(String.raw`p,p'`),
        " とも奇数・",
        math(String.raw`q`),
        " も奇数・",
        math(String.raw`t=1`),
        " なので ",
        math(String.raw`\bar{\tilde E}`),
        " と ",
        math(String.raw`\mu`),
        " は不変であり、したがって ",
        math(String.raw`K`),
        "、",
        math(String.raw`e_{j^*}`),
        "、",
        math(String.raw`r^\sharp`),
        "、",
        math(String.raw`A_{\mathrm{gen}}`),
        " も不変である。残る 4 箇所の ",
        math(String.raw`\theta^\sharp`),
        " が不変であることも同じ計算で確かめられる。",
        math(String.raw`(0{:}1)`),
        " と ",
        math(String.raw`(1{:}0)`),
        " の ",
        math(String.raw`k=0`),
        " ではそれぞれ ",
        math(String.raw`\Phi_u=(q+t)(2-y-y^{-1})`),
        " と ",
        math(String.raw`\Phi_u=(p+t)(2-y-y^{-1})`),
        " なので ",
        math(String.raw`\theta^\sharp_0=2`),
        "。",
        math(String.raw`(1{:}0)`),
        " の ",
        math(String.raw`k=1`),
        " では ",
        math(String.raw`A_0=A_1=4(q+1)`),
        "（",
        math(String.raw`v_2=3`),
        "）と ",
        math(String.raw`A_2=1-p`),
        "、",
        math(String.raw`(1{:}1)`),
        " の ",
        math(String.raw`k=1`),
        " では ",
        math(String.raw`A_0=A_1=4(q+1)`),
        " と ",
        math(String.raw`A_2=q-p`),
        " であり、",
        math(String.raw`v_2(1-p)`),
        " も ",
        math(String.raw`v_2(q-p)`),
        " も ",
        math(String.raw`N=1`),
        " で ",
        math(String.raw`1`),
        "、",
        math(String.raw`p'`),
        " に取り替えると ",
        math(String.raw`2`),
        " になるが、いずれも ",
        math(String.raw`3`),
        " より小さいので最小は ",
        math(String.raw`A_2`),
        " で ",
        math(String.raw`\theta^\sharp_1=2`),
        " のまま不変である（",
        math(String.raw`N\ge2`),
        " では両方とも ",
        math(String.raw`1`),
        " である）。したがって (U1) より ",
        math(String.raw`d`),
        " の変化は ",
        math(String.raw`(0{:}1)`),
        " の ",
        math(String.raw`\theta^\sharp_1`),
        " の変化だけから来て ",
        math(String.raw`\varphi(2)\cdot(0-2)=-2`),
        " である。**",
        math(String.raw`\Lambda_1`),
        " が不変のまま位置だけが動いているので、この障害は付値側の障害の系ではない。**",
      ]),
      paragraph([
        "**(U6) の証明。** ",
        math(String.raw`\tilde E'=\tilde E+\ell^{N}h`),
        "（",
        math(String.raw`h\in\mathbb{Z}[z,w]`),
        "）と置く。",
        ref("paper_prop_M"),
        " (M1) の ",
        math(String.raw`\Phi^{[k]}`),
        " は ",
        math(String.raw`\tilde E`),
        " の係数の ",
        math(String.raw`\mathcal{O}_k`),
        " 係数線形式なので ",
        math(String.raw`A'^{[k]}_m=A^{[k]}_m+\ell^{N}\beta_m`),
        "（",
        math(String.raw`\beta_m\in\mathcal{O}_k`),
        "）である。",
        math(String.raw`v_\ell(\ell^{N}\beta_m)\ge N`),
        " なので、",
        math(String.raw`v_\ell(A^{[k]}_m)<N`),
        " なる ",
        math(String.raw`m`),
        " については非アルキメデス的評価の等号から ",
        math(String.raw`v_\ell(A'^{[k]}_m)=v_\ell(A^{[k]}_m)`),
        "、",
        math(String.raw`v_\ell(A^{[k]}_m)\ge N`),
        " なる ",
        math(String.raw`m`),
        " については ",
        math(String.raw`v_\ell(A'^{[k]}_m)\ge N`),
        " である。すなわち切り捨て付きの付値列 ",
        math(String.raw`\bigl(\min(v_\ell(A^{[k]}_m),N)\bigr)_m`),
        " は ",
        math(String.raw`\tilde E\bmod\ell^{N}`),
        " で決まる。条件より ",
        math(String.raw`\Lambda_k<N`),
        " なので ",
        math(String.raw`\Lambda_k`),
        " はこの列の最小値に等しく、",
        math(String.raw`\theta^\sharp_k`),
        " はその最小を最初に達成する添字だから、どちらもこの列から読める。",
        math(String.raw`K`),
        "、",
        math(String.raw`j^{*}`),
        "、",
        math(String.raw`e_{j^*}`),
        "、",
        math(String.raw`r^\sharp`),
        "、",
        math(String.raw`A_{\mathrm{gen}}`),
        " は第 1 層から決まるので、(U1) より ",
        math(String.raw`c`),
        " と ",
        math(String.raw`d`),
        " も決まる。",
        math(String.raw`N`),
        " を ",
        math(String.raw`1`),
        " ずつ上げれば必ず有限回で止まる（",
        ref("paper_prop_M"),
        " (M1) の 3 番目より ",
        math(String.raw`\Lambda_k<\infty`),
        "）。",
      ]),
    ],
  },
]);
