// 自動生成ファイル — 直接編集しない。
// 生成元: content/ の全ブロックの labels（と、翻訳ロケールにしか無いブロックの labels）
// 再生成: node <system>/codegen/structured-text-index/cli.ts --project <このディレクトリ>
//
// このユニオン型が「実在するラベル」の全体であり、ref() / ノートの targets は
// これ以外を受け付けない。存在しないラベルへの参照はコンパイル時に落ちる。

export const ALL_LABELS = [
  "claim_antichain_order_convex",
  "claim_collision_finite_decidability",
  "claim_collision_shift",
  "claim_covering_subset_one_step",
  "claim_dependency_transfer",
  "claim_down_set_boundary_outgoing",
  "claim_down_set_no_incoming_edge",
  "claim_down_set_order_convex",
  "claim_event_order_locally_finite",
  "claim_event_set_cardinality",
  "claim_eventual_periodicity",
  "claim_finite_propagation_boundary",
  "claim_fixed_iff_min_period_divides",
  "claim_fixed_point_count_decomposition",
  "claim_fixed_point_count_finite_decidability",
  "claim_flip_test_equivalence",
  "claim_global_flip_characterization",
  "claim_global_map_injective_iff_all_periodic",
  "claim_global_map_injective_iff_surjective",
  "claim_global_map_injectivity_finite_decidability",
  "claim_inverse_map_is_ca_iff_support_subset",
  "claim_inverse_support_finite_decidability",
  "claim_inverse_support_not_in_neighborhood_counterexample",
  "claim_iterate_collision_gives_eventual_period",
  "claim_iterate_collision_stabilizes_tails",
  "claim_iterate_composition_addition",
  "claim_iterate_map_collision_finite_representatives",
  "claim_iterate_monoid_finite_decidability",
  "claim_iterate_monoid_first_stable_equals_min_collision_start",
  "claim_iterate_monoid_generated_ideal_finite_chain_decidable",
  "claim_iterate_monoid_generated_ideals_comparable",
  "claim_iterate_monoid_idempotent_uniqueness_fails",
  "claim_iterate_monoid_idempotents_finite_decidability",
  "claim_iterate_monoid_minimal_period_divides_every_period",
  "claim_iterate_monoid_minimal_period_finite_decidability",
  "claim_iterate_monoid_period_propagates_after_collision_start",
  "claim_iterate_monoid_principal_ideal_equivalence_relation",
  "claim_iterate_monoid_tail_absorbs_composition",
  "claim_iterate_monoid_tail_equality_iff_collision_start",
  "claim_iterate_monoid_tail_finite_decidability",
  "claim_iterate_monoid_tail_is_principal_ideal",
  "claim_iterate_monoid_tails_descend",
  "claim_iterate_monoid_tails_strict_then_stable",
  "claim_iterate_powers_form_finite_commutative_monoid",
  "claim_min_preperiod_period_bound",
  "claim_min_preperiod_period_finite_decidability",
  "claim_minimal_inverse_neighborhood_finite_decidability",
  "claim_no_dependency_on_redundant_element",
  "claim_no_mutual_reachability",
  "claim_nonidentity_idempotent_not_forced",
  "claim_one_step_dependency_finite_decidability",
  "claim_one_step_equals_covering",
  "claim_one_step_subset_covering",
  "claim_one_step_subset_reachability",
  "claim_orbit_collision",
  "claim_order_convex_intersection",
  "claim_order_interval_finite",
  "claim_order_iso_not_time_preserving",
  "claim_path_time_increment_exact",
  "claim_path_time_strictly_increases",
  "claim_period_descends_to_min_preperiod",
  "claim_period_multiples",
  "claim_periodic_iff_min_preperiod_zero",
  "claim_periodicity_pair_iff_collision",
  "claim_positive_idempotent_iterate_exists",
  "claim_propagation_ball_finite",
  "claim_reachability_irreflexive",
  "claim_reachability_minimal",
  "claim_reachability_partial_order",
  "claim_reachability_transitive",
  "claim_representable_implies_support_subset",
  "claim_start_cell_in_propagation_ball",
  "claim_support_finite_decidability",
  "claim_support_invariance",
  "claim_support_is_minimum_representing_set",
  "claim_support_subset_implies_representable",
  "claim_time_slice_antichain",
  "claim_time_strictly_increases",
  "claim_up_set_order_convex",
  "def_antichain",
  "def_base_value_extension",
  "def_cardinality_notation",
  "def_covering_relation",
  "def_dependency_path",
  "def_dependency_source_set",
  "def_down_set",
  "def_essential_dependency",
  "def_essential_dependency_support",
  "def_event_set",
  "def_finite_ca",
  "def_finite_stage",
  "def_fixed_points_of_iterate",
  "def_flip_map",
  "def_global_map",
  "def_global_map_injective_surjective",
  "def_global_map_iterate",
  "def_incomparability",
  "def_inverse_cell_map_support",
  "def_inverse_global_map",
  "def_iterate_monoid",
  "def_iterate_monoid_collision_start",
  "def_iterate_monoid_generated_ideal",
  "def_iterate_monoid_generated_ideal_chain",
  "def_iterate_monoid_idempotent",
  "def_iterate_monoid_minimal_positive_period",
  "def_iterate_monoid_principal_ideal_equivalence",
  "def_iterate_monoid_tail",
  "def_local_rule_representable",
  "def_local_truth_table",
  "def_locally_finite_partial_order",
  "def_min_period",
  "def_min_preperiod",
  "def_negation_map",
  "def_one_step_boundary",
  "def_one_step_dependency",
  "def_orbit",
  "def_order_convex_subset",
  "def_order_interval",
  "def_partial_order",
  "def_periodic_points",
  "def_periodicity_pairs",
  "def_propagation_ball",
  "def_reachability",
  "def_redundant_extension",
  "def_reflexive_reachability",
  "def_restriction_map",
  "def_state_set",
  "def_time_interval",
  "def_time_slice",
  "def_up_set",
  "remark_causal_comparison_scope",
  "remark_causal_set_not_claimed",
  "remark_causal_set_source",
  "remark_inverse_map_locality_not_claimed",
  "remark_iterate_monoid_principal_ideal_external_name_deferred",
  "remark_iteration_not_claimed",
  "remark_local_rule_representation_scope",
  "remark_reversibility_not_claimed",
] as const

/** content/ に実在するラベル。相互参照はこの型の値しか指せない。 */
export type Label = (typeof ALL_LABELS)[number]

/**
 * 翻訳ロケールにしか無いブロックのラベル（locales.config.ts が理由つきで認めたもの）。
 * **原文はこれを指せない**。原文から指せば、原文の解決で未解決参照になる。
 */
export const TRANSLATION_ONLY_LABELS = [

] as const

export type TranslationOnlyLabel = (typeof TRANSLATION_ONLY_LABELS)[number]

/** 翻訳ロケールの content が使うラベル。原文のラベルに翻訳限定のものを足しただけ。 */
export type AnyLocaleLabel = Label | TranslationOnlyLabel
