

# This file was *autogenerated* from the file sagemath/check/049_claim_even_sector_fermions/check_02_anticommutator.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1en2 = RealNumber('1e-2')# =========================================================================
# check_02: anticommutator_of_check_psi
#
#   [psi^dagger_mu, psi^dagger_nu]_+ = 0
#   [psi^dagger_mu, psi_nu]_+        = delta^M_{(mu+nu, 1)} I
#   [psi_mu, psi_nu]_+               = 0
#
#  対になる添字が mu+nu = 1 (mod M) であること（008 章の mu+nu = 0 ではない）を
#  確かめるため、delta = 1 の場合と delta = 0 の場合を別々に集計する。
#  また、対照として「mu+nu = 0 (mod M) を対と誤った場合」に第 2 式が成り立たないことも示す。
# =========================================================================
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '_prelude.sage'))

print("=== check_02: anticommutator_of_check_psi ===")

ok_all = True
w_dd = w_dp_on = w_dp_off = w_pp = _sage_const_0 
worst_wrong = _sage_const_0    # 誤った対 (mu+nu = 0 mod M) を使ったときの残差の最大値

MU_RANGE_EXTRA = [_sage_const_0 , -_sage_const_1 ]   # mu ∈ Z 全体で成り立つことの確認用

for M in FERMI_M:
    O = SpinOps(M)
    Id = identity_matrix(CDF, O.d)
    for p in FERMI_PARAMS:
        P = coeffs(p['K1'], p['K2'])
        idx = list(range(_sage_const_1 , M + _sage_const_1 )) + MU_RANGE_EXTRA
        cache = {mu: psi_pair(O, mu, P) for mu in idx}
        for mu in idx:
            dm, pm = cache[mu]
            for nu in idx:
                dn, pn = cache[nu]
                d1 = delta_M(M, mu + nu, _sage_const_1 )
                w_dd = max(w_dd, opnorm(dm * dn + dn * dm))
                w_pp = max(w_pp, opnorm(pm * pn + pn * pm))
                res = opnorm(dm * pn + pn * dm - d1 * Id)
                if d1 == _sage_const_1 :
                    w_dp_on = max(w_dp_on, res)
                else:
                    w_dp_off = max(w_dp_off, res)
                # 誤った対の規則 delta^M_{(mu+nu, 0)} を使った場合の残差
                d0 = delta_M(M, mu + nu, _sage_const_0 )
                if d0 != d1:
                    worst_wrong = max(worst_wrong,
                                      opnorm(dm * pn + pn * dm - d0 * Id))

ok_all &= report("[psi^dagger_mu, psi^dagger_nu]_+ = 0", w_dd, TOL)
ok_all &= report("[psi_mu, psi_nu]_+ = 0", w_pp, TOL)
ok_all &= report("[psi^dagger_mu, psi_nu]_+ = I   (mu+nu = 1 mod M)", w_dp_on, TOL)
ok_all &= report("[psi^dagger_mu, psi_nu]_+ = 0   (mu+nu != 1 mod M)", w_dp_off, TOL)
print(f"  対照: 対を mu+nu = 0 (mod M) と誤ると残差 = {float(worst_wrong):.3e} "
      f"-> {'期待どおり不成立' if worst_wrong > _sage_const_1en2  else '判定不能'}")
ok_all &= (worst_wrong > _sage_const_1en2 )

print("check_02:", "PASS" if ok_all else "FAIL")

