

# This file was *autogenerated* from the file check_01_anticommutators.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0p0 = RealNumber('0.0')# ---------------------------------------------------------
# SageMath: checkpsi の反交換関係（対は mu + nu ≡ 1 (mod M)）
#
# 対象: structured-latex anticommutator_of_check_psi
#       （併せて def_check_fermi の周期性 checkpsi_{mu+M} = checkpsi_mu）
#
# (a) [checkpsi_mu^dagger, checkpsi_nu^dagger]_+ = 0
# (b) [checkpsi_mu^dagger, checkpsi_nu]_+       = delta^M_{(mu+nu, 1)} I
# (c) [checkpsi_mu, checkpsi_nu]_+              = 0
# (d) 添字の周期性: checkpsi_{mu+M} = checkpsi_mu, checkpsi^dagger_{mu+M} = checkpsi^dagger_mu
# (e) 共役添字の関係: gamma_2(theta~_{1-mu}) = gamma_2(-theta~_mu),
#     |gamma_2(theta~_{1-mu})| = |gamma_2(theta~_mu)|
# ---------------------------------------------------------
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '_prelude.sage'))

print("=== (a)(b)(c) checkpsi の反交換関係（mu, nu を広い範囲で走査）===")
ac_ok = True
for M in EVEN_M:
    O = SpinOps(M)
    Id = identity_matrix(CDF, O.d)
    for params in EVEN_PARAMS:
        K1v, K2v = RDF(params['K1']), RDF(params['K2'])
        F = {}
        for mu in range(_sage_const_1  - M, _sage_const_2  * M + _sage_const_1 ):
            F[mu] = fermions(O, K1v, K2v, mu)
        w = {'dd': _sage_const_0p0 , 'dn': _sage_const_0p0 , 'nn': _sage_const_0p0 }
        for mu in range(_sage_const_1  - M, M + _sage_const_1 ):
            for nu in range(_sage_const_1  - M, M + _sage_const_1 ):
                pdm, pm = F[mu]
                pdn, pn = F[nu]
                d = delta_M(mu + nu, _sage_const_1 , M)
                w['dd'] = max(w['dd'], opnorm(acomm(pdm, pdn)))
                w['dn'] = max(w['dn'], opnorm(acomm(pdm, pn) - d * Id))
                w['nn'] = max(w['nn'], opnorm(acomm(pm, pn)))
        worst = max(w.values())
        ok = worst <= TOL
        print(f"  M={M}, K1={params['K1']}, K2={params['K2']}: "
              f"[p+,p+]={w['dd']:.1e}, [p+,p]-delta={w['dn']:.1e}, [p,p]={w['nn']:.1e}"
              f"  -> {'PASS' if ok else 'FAIL'}")
        ac_ok = ok and ac_ok

print("=== (d) 添字の周期性 checkpsi_{mu+M} = checkpsi_mu ===")
per_ok = True
for M in EVEN_M:
    O = SpinOps(M)
    for params in EVEN_PARAMS:
        K1v, K2v = RDF(params['K1']), RDF(params['K2'])
        worst = _sage_const_0p0 
        for mu in range(_sage_const_1  - M, M + _sage_const_1 ):
            pd0, p0 = fermions(O, K1v, K2v, mu)
            pd1, p1 = fermions(O, K1v, K2v, mu + M)
            worst = max(worst, opnorm(pd1 - pd0), opnorm(p1 - p0))
            # gamma の周期性も確認
            worst = max(worst, abs(gamma_tilde(K1v, K2v, M, mu + M)
                                   - gamma_tilde(K1v, K2v, M, mu)))
        ok = worst <= TOL
        print(f"  M={M}, K1={params['K1']}, K2={params['K2']}: 最大残差 {worst:.1e}"
              f"  -> {'PASS' if ok else 'FAIL'}")
        per_ok = ok and per_ok

print("=== (e) 共役添字 1-mu の関係 ===")
conj_ok = True
for M in EVEN_M:
    for params in EVEN_PARAMS:
        K1v, K2v = RDF(params['K1']), RDF(params['K2'])
        worst = _sage_const_0p0 
        for mu in range(_sage_const_1  - M, M + _sage_const_1 ):
            t = th_tilde(M, mu)
            tc = th_tilde(M, _sage_const_1  - mu)
            # theta~_{1-mu} = -theta~_mu
            worst = max(worst, abs(CDF(tc) + CDF(t)))
            worst = max(worst, abs(gam2(K1v, K2v, tc) - gam2(K1v, K2v, -t)))
            worst = max(worst, abs(abs(gam2(K1v, K2v, tc)) - abs(gam2(K1v, K2v, t))))
            worst = max(worst, abs(gamma_tilde(K1v, K2v, M, _sage_const_1  - mu)
                                   - gamma_tilde(K1v, K2v, M, mu)))
        ok = worst <= TOL
        print(f"  M={M}, K1={params['K1']}, K2={params['K2']}: 最大残差 {worst:.1e}"
              f"  -> {'PASS' if ok else 'FAIL'}")
        conj_ok = ok and conj_ok

all_ok = ac_ok and per_ok and conj_ok
print("RESULT: PASS" if all_ok else "RESULT: FAIL")

