

# This file was *autogenerated* from the file check_04_G_second_derivative.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_24 = Integer(24); _sage_const_8 = Integer(8); _sage_const_201 = Integer(201); _sage_const_400 = Integer(400); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5)# ---------------------------------------------------------
# SageMath: G''(kappa) の対数発散（章 E の主定理の心臓部）
#   対象: structured-latex second_derivative_log_divergence
#
#   |G'(kappa)| <= 1/2
#   |G''(kappa) - (1/2pi) log(1/|kappa|)| <= 6/5   (0 < |kappa| <= 1/2)
#
# 本文の Step ごとに検証する（Step 1 の積分と微分の交換、Step 2 の折り返し、
# Step 3 の J, T への分解、Step 4/5/6 の各評価、Step 7 の総合）。
# ---------------------------------------------------------
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '_prelude.sage'))

all_ok = True
KAPPAS = [mp.mpf('0.5'), mp.mpf('0.3'), mp.mpf('0.1'), mp.mpf('0.03'),
          mp.mpf('1e-3'), mp.mpf('1e-6'), mp.mpf('1e-10')]

print("=== Step 1: (R5) の交換（G'' = (1/4pi) int d^2gamma/dkappa^2） ===")
w = mp.mpf(_sage_const_0 )
for kap in [mp.mpf('0.5'), mp.mpf('0.1'), mp.mpf('0.01')]:
    w = max(w, abs(G2(kap) - mp.diff(G, kap, _sage_const_2 )))
ok = w <= mp.mpf('1e-20')
print(f"  max |G''(積分形) - 数値 2 階微分| = {mp.nstr(w,_sage_const_3 )}  -> {'PASS' if ok else 'FAIL'}")
all_ok = ok and all_ok

print()
print("=== Step 1: |G'(kappa)| <= 1/2 ===")
mx = mp.mpf(_sage_const_0 )
for kap in KAPPAS:
    v = abs(mp.quad(lambda th: dgamma_dkappa(kap, th), [_sage_const_0 , PI, _sage_const_2  * PI]) / (_sage_const_4  * PI))
    mx = max(mx, v)
ok = mx <= mp.mpf(_sage_const_1 ) / _sage_const_2 
print(f"  max |G'| = {mp.nstr(mx, _sage_const_10 )}  -> {'PASS' if ok else 'FAIL'}")
all_ok = ok and all_ok

print()
print("=== Step 2/3: 折り返しと J, T への分解 ===")
w = mp.mpf(_sage_const_0 )
for kap in KAPPAS:
    J = mp.quad(lambda th: _sage_const_1  / mp.sqrt(S_of(kap, th) * (_sage_const_1  + S_of(kap, th))), [_sage_const_0 , PI])
    T = mp.quad(lambda th: mp.sinh(kap) ** _sage_const_2  * (_sage_const_1  + _sage_const_2  * S_of(kap, th))
                / (_sage_const_2  * mp.sqrt(S_of(kap, th) * (_sage_const_1  + S_of(kap, th)))) ** _sage_const_3 , [_sage_const_0 , PI])
    w = max(w, abs(_sage_const_2  * PI * G2(kap) - (mp.cosh(kap) / _sage_const_2  * J - T)))
ok = w <= mp.mpf('1e-25')
print(f"  max |2pi G'' - (cosh k /2) J + T| = {mp.nstr(w,_sage_const_3 )}  -> {'PASS' if ok else 'FAIL'}")
all_ok = ok and all_ok

print()
print("=== Step 4/5/6: 各段の評価（kappa <= 1/2） ===")
for kap in KAPPAS:
    d = mp.sinh(kap / _sage_const_2 )
    J = mp.quad(lambda th: _sage_const_1  / mp.sqrt(S_of(kap, th) * (_sage_const_1  + S_of(kap, th))), [_sage_const_0 , PI])
    T = mp.quad(lambda th: mp.sinh(kap) ** _sage_const_2  * (_sage_const_1  + _sage_const_2  * S_of(kap, th))
                / (_sage_const_2  * mp.sqrt(S_of(kap, th) * (_sage_const_1  + S_of(kap, th)))) ** _sage_const_3 , [_sage_const_0 , PI])
    R = J - _sage_const_2  * mp.log(PI / d)
    step6 = abs(mp.cosh(kap) * mp.log(PI / d) - mp.log(_sage_const_1  / kap))
    # Step 4 は R の上界（2 delta^2/pi^2 + B）と下界（-(pi/2)cosh(kappa/2)）を
    # 別々の項から取る（和を取らない）。その帰結が |R| <= 1.621。
    B = PI ** _sage_const_2  / (_sage_const_12  * (_sage_const_1  - PI ** _sage_const_2  / _sage_const_24 ) * (_sage_const_2  - PI ** _sage_const_2  / _sage_const_24 ))
    c4a = (-(PI / _sage_const_2 ) * mp.cosh(kap / _sage_const_2 ) <= R <= _sage_const_2  * d ** _sage_const_2  / PI ** _sage_const_2  + B)
    c4 = c4a and abs(R) <= mp.mpf('1.621')
    c5 = (_sage_const_0  <= T <= mp.mpf('3.614'))
    c6 = step6 <= mp.mpf('2.201')
    ok = c4 and c5 and c6
    print(f"  kappa={mp.nstr(kap,_sage_const_4 )}: |R|={mp.nstr(abs(R),_sage_const_8 )} (<=1.621 {int(c4)}), "
          f"(両側 {int(c4a)}), T={mp.nstr(T,_sage_const_8 )} (<=3.614 {int(c5)}), "
          f"Step6={mp.nstr(step6,_sage_const_8 )} (<=2.201 {int(c6)})  -> {'PASS' if ok else 'FAIL'}")
    all_ok = ok and all_ok

print()
print("=== Step 7: |G'' - (1/2pi) log(1/|kappa|)| <= 6/5（0 < |kappa| <= 1/2 を細かく走査） ===")
mx = mp.mpf(_sage_const_0 ); arg = None
for j in range(_sage_const_1 , _sage_const_201 ):
    kap = mp.mpf(j) / _sage_const_400 
    v = abs(G2(kap) - mp.log(_sage_const_1  / kap) / (_sage_const_2  * PI))
    if v > mx:
        mx = v; arg = kap
for kap in [mp.mpf('1e-3'), mp.mpf('1e-6'), mp.mpf('1e-10'), mp.mpf('1e-20')]:
    v = abs(G2(kap) - mp.log(_sage_const_1  / kap) / (_sage_const_2  * PI))
    if v > mx:
        mx = v; arg = kap
ok = mx <= mp.mpf(_sage_const_6 ) / _sage_const_5 
print(f"  max = {mp.nstr(mx, _sage_const_10 )}（kappa = {mp.nstr(arg, _sage_const_6 )}）  -> {'PASS' if ok else 'FAIL'}")
all_ok = ok and all_ok

print()
print("=== 偶関数性: G''(-kappa) = G''(kappa) ===")
w = max(abs(G2(kap) - G2(-kap)) for kap in KAPPAS)
ok = w <= mp.mpf('1e-25')
print(f"  max |G''(k) - G''(-k)| = {mp.nstr(w,_sage_const_3 )}  -> {'PASS' if ok else 'FAIL'}")
all_ok = ok and all_ok

print()
print("=== 発散すること: kappa -> 0 で G'' -> +infty ===")
prev = None
mono = True
for kap in [mp.mpf('1e-2'), mp.mpf('1e-4'), mp.mpf('1e-8'), mp.mpf('1e-16'), mp.mpf('1e-32')]:
    v = G2(kap)
    print(f"  kappa={mp.nstr(kap,_sage_const_4 )}: G'' = {mp.nstr(v, _sage_const_10 )}, "
          f"(1/2pi)log(1/kappa) = {mp.nstr(mp.log(_sage_const_1 /kap)/(_sage_const_2 *PI), _sage_const_10 )}")
    if prev is not None and v <= prev:
        mono = False
    prev = v
print(f"  単調に増大: {mono}  -> {'PASS' if mono else 'FAIL'}")
all_ok = mono and all_ok

print()
print("RESULT: PASS" if all_ok else "RESULT: FAIL")

