

# This file was *autogenerated* from the file check_01_submult.sage
from sage.all_cmdline import *   # import sage library

_sage_const_102 = Integer(102); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_30 = Integer(30); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_1en10 = RealNumber('1e-10'); _sage_const_10 = Integer(10); _sage_const_0p999 = RealNumber('0.999'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_1en12 = RealNumber('1e-12')# <matrix_norm_submultiplicativity>: ||AB|| <= ||A|| ||B||
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
rng = np.random.default_rng(int(_sage_const_102 ))
rep = CheckReport("matrix_norm_submultiplicativity")
def nrm(A):
    return float(np.sqrt(np.sum(np.abs(A)**_sage_const_2 )))
tight = _sage_const_0 
for n in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_8 ]:
    for _ in range(_sage_const_30 ):
        A = rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n))
        B = rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n))
        rep.truth(nrm(A@B) <= nrm(A)*nrm(B) + _sage_const_1en10 , f"n={n}: ||AB|| <= ||A|| ||B||")
    # ランク1どうしでは等号になる（評価が緩すぎないことの確認）
    for _ in range(_sage_const_10 ):
        u = rng.normal(size=(n,_sage_const_1 )) + _sage_const_1j *rng.normal(size=(n,_sage_const_1 ))
        v = rng.normal(size=(_sage_const_1 ,n)) + _sage_const_1j *rng.normal(size=(_sage_const_1 ,n))
        w = rng.normal(size=(n,_sage_const_1 )) + _sage_const_1j *rng.normal(size=(_sage_const_1 ,n)).T
        A = u @ v
        B = (v.conj().T) @ (v.conj())          # 像と核が合うように
        r = nrm(A@B)/(nrm(A)*nrm(B))
        if r > _sage_const_0p999 :
            tight += _sage_const_1 
    # 逆向きの不等式は成り立たない
    A = np.zeros((n,n), dtype=complex); A[_sage_const_0 ,_sage_const_0 ] = _sage_const_1p0 
    B = np.zeros((n,n), dtype=complex); B[n-_sage_const_1 ,n-_sage_const_1 ] = _sage_const_1p0 
    rep.truth(nrm(A@B) < nrm(A)*nrm(B) - _sage_const_1en12  or n == _sage_const_1 ,
              f"n={n}: 直交する像・核では真の不等号（||AB||=0 < 1）")
print(f"  等号に近い（比 > 0.999）事例: {tight} 件")
rep.finish()

