

# This file was *autogenerated* from the file check_01_nu_bijection.sage
from sage.all_cmdline import *   # import sage library

_sage_const_308 = Integer(308); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0j = ComplexNumber(0, '0')# <def_kronecker>: 添字写像 nu(I) = 1 + sum (i_k - 1) 2^{M-k} が全単射で、
# クロネッカー積の成分の定義式が numpy の kron と一致すること
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import math
import itertools
rng = np.random.default_rng(int(_sage_const_308 ))
rep = CheckReport("def_kronecker")
for M in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_5 ]:
    idxs = list(itertools.product([_sage_const_1 ,_sage_const_2 ], repeat=M))
    rep.truth(len(idxs) == _sage_const_2 **M, f"M={M}: #I_M = 2^M")
    nus = [_sage_const_1  + sum((I_[k]-_sage_const_1 )*_sage_const_2 **(M-_sage_const_1 -k) for k in range(M)) for I_ in idxs]
    rep.truth(sorted(nus) == list(range(_sage_const_1 , _sage_const_2 **M+_sage_const_1 )), f"M={M}: nu は {{1,...,2^M}} への全単射")
    # ベクトルのクロネッカー積の成分
    vs = [rng.normal(size=(_sage_const_2 ,)) + _sage_const_1j *rng.normal(size=(_sage_const_2 ,)) for _ in range(M)]
    kv = kron_list([v.reshape(_sage_const_2 ,_sage_const_1 ) for v in vs]).reshape(-_sage_const_1 )
    for I_ in idxs:
        nu = _sage_const_1  + sum((I_[k]-_sage_const_1 )*_sage_const_2 **(M-_sage_const_1 -k) for k in range(M))
        prod = _sage_const_1p0 +_sage_const_0j 
        for k in range(M):
            prod *= vs[k][I_[k]-_sage_const_1 ]
        rep.close(kv[nu-_sage_const_1 ], prod, f"M={M}: ベクトルの成分の定義式")
rep.finish()

