

# This file was *autogenerated* from the file probe_tmp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0p4 = RealNumber('0.4'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0p7 = RealNumber('0.7'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '_prelude.sage'))
for (M,K1v,K2v) in [(_sage_const_2 ,_sage_const_0p4 ,_sage_const_0p8 ),(_sage_const_3 ,_sage_const_0p4 ,_sage_const_0p8 ),(_sage_const_4 ,_sage_const_0p4 ,_sage_const_0p8 ),(_sage_const_3 ,_sage_const_0p7 ,_sage_const_0p3 ),(_sage_const_4 ,_sage_const_0p7 ,_sage_const_0p3 ),(_sage_const_5 ,_sage_const_0p4 ,_sage_const_0p8 )]:
    O=SpinOps(M); W=W_matrix(O,K1v,K2v); Pp,Pm=projectors(O)
    cp=rayleigh_sup(to_real(Pp*W*Pp)); cm=rayleigh_sup(to_real(Pm*W*Pm))
    g=gamma_fn(K1v,K2v); s2=RDF(sinh(_sage_const_2 *RDF(K2v))); pref=RDF((_sage_const_2 *s2)**(RDF(M)/_sage_const_2 ))
    def Lam(delta):
        return RDF(pref*exp(sum(g(th)/_sage_const_2  for th in theta_family(M,delta))))
    Vp=V_sym(O,K1v,K2v,_sage_const_1 ); Vm=V_sym(O,K1v,K2v,-_sage_const_1 )
    evp=sorted([RDF(CDF(z).real()) for z in Vp.eigenvalues()])
    evm=sorted([RDF(CDF(z).real()) for z in Vm.eigenvalues()])
    print(f"M={M} K1={K1v} K2={K2v}")
    print(f"   c+={cp:.10f}  Lam(1/2)={Lam(RDF(_sage_const_1 )/_sage_const_2 ):.10f}  maxEV(V+)={evp[-_sage_const_1 ]:.10f}")
    print(f"   c-={cm:.10f}  Lam(0)  ={Lam(RDF(_sage_const_0 )):.10f}  maxEV(V-)={evm[-_sage_const_1 ]:.10f}")

