

# This file was *autogenerated* from the file check_01_series.sage
from sage.all_cmdline import *   # import sage library

_sage_const_112 = Integer(112); _sage_const_60 = Integer(60); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_1 = Integer(1)# <brianhall_exc14>: e^{ad_X}(Y) の級数表示
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import math
rng = np.random.default_rng(int(_sage_const_112 ))
rep = CheckReport("brianhall_exc14")
NT = _sage_const_60 
for n in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    for trial in range(_sage_const_4 ):
        X = rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n))
        X = X/np.sqrt(np.sum(np.abs(X)**_sage_const_2 ))*_sage_const_1p0 
        Y = rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n))
        L = np.kron(X, np.eye(n)) - np.kron(np.eye(n), X.T)
        lhs = (_expm(L) @ Y.reshape(-_sage_const_1 )).reshape(n,n)
        rhs = np.zeros((n,n), dtype=complex); t = Y.copy()
        for m in range(NT+_sage_const_1 ):
            rhs = rhs + t/math.factorial(m); t = comm(X, t)
        rep.close(lhs, rhs, f"n={n} t={trial}: e^(ad_X)(Y) = sum (1/m!) ad_X^m(Y)")
        rep.close(lhs, _expm(X) @ Y @ _expm(-X), f"n={n} t={trial}: = exp(X) Y exp(-X)")
        # ad_X の行列表示が正しいこと
        rep.close((L @ Y.reshape(-_sage_const_1 )).reshape(n,n), comm(X,Y), f"n={n} t={trial}: ad_X の行列表示")
rep.finish()

