

# This file was *autogenerated* from the file sagemath/check/050_claim_even_sector_eigenvalues/check_03_Vprime_eigenvalues.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1en7 = RealNumber('1e-7'); _sage_const_1 = Integer(1); _sage_const_1en9 = RealNumber('1e-9')# =========================================================================
# check_03: eigenvalues_of_check_Vprime
#
#   g^(eps) := sum_{mu=1}^{M} gamma(theta~_mu)(eps_mu - 1/2)
#
#   (1) X^ Q^_eps = g^(eps) Q^_eps
#   (2) V^' Q^_eps = e^{g^(eps)} Q^_eps
#   (3) V^' の固有値の全体（重複度こみ 2^M 個）が { e^{g^(eps)} : eps in {0,1}^M } と一致する
#   (4) 固有値はすべて正の実数
#
#  注意（一次情報で確認した事実）: 相異なる eps が同じ固有値を与えることは実際に起こる。
#  periodicity_of_check_fermi (3) より gamma(theta~_{1-mu}) = gamma(theta~_mu)、すなわち
#  gamma(theta~_mu) = gamma(theta~_{M+1-mu}) なので、mu <-> M+1-mu で eps を入れ替えても
#  g^(eps) は変わらない。したがって「固有値がすべて相異なる」は**成り立たない**。
#  本文でもそう主張しない（単純性を主張するのは最大固有値だけ。check_06 で確認する）。
# =========================================================================
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '_prelude.sage'))

print("=== check_03: V^' の固有値 ===")

ok_all = True
w_XQ = _sage_const_0 
w_VQ = _sage_const_0 
w_spec = _sage_const_0 
min_imag_ok = True
min_pred = None
n_degenerate = _sage_const_0 

for M in EIG_M:
    O = SpinOps(M)
    for p in EIG_PARAMS:
        P = coeffs(p['K1'], p['K2'])
        ns = n_check_all(O, P)
        Vpr, Vpri, X = Vprime_check(O, P, ns)
        E = eps_list(M)
        pred = []
        for eps in E:
            Q = Q_check(O, eps, ns)
            g = g_of_eps(O, eps, P)
            w_XQ = max(w_XQ, opnorm(X * Q - CDF(g) * Q))
            w_VQ = max(w_VQ, opnorm(Vpr * Q - CDF(exp(g)) * Q))
            pred.append(RDF(exp(g)))
        # (3) Sage が数値的に出す固有値集合との一致（両方ソートして 1 対 1 比較）
        ev = Vpr.eigenvalues()
        for z in ev:
            min_imag_ok = min_imag_ok and (abs(CDF(z).imag()) < _sage_const_1en7 )
        got = sorted([RDF(CDF(z).real()) for z in ev])
        pred_sorted = sorted(pred)
        for a, b in zip(got, pred_sorted):
            w_spec = max(w_spec, abs(a - b) / abs(b))
        # (4) 正値性、および「相異なる eps で固有値が一致する例が実在する」ことの記録
        for v in pred_sorted:
            min_pred = v if min_pred is None else min(min_pred, v)
        for a, b in zip(pred_sorted, pred_sorted[_sage_const_1 :]):
            if (b - a) / b < _sage_const_1en9 :
                n_degenerate += _sage_const_1 

ok_all &= report("X^ Q^_eps = g^(eps) Q^_eps", w_XQ, TOL)
ok_all &= report("V^' Q^_eps = e^{g^(eps)} Q^_eps", w_VQ, TOL)
ok_all &= report("V^' の固有値集合 = { e^{g^(eps)} }（相対差）", w_spec, TOL)
print(f"  固有値の虚部が 0（実数）: {'PASS' if min_imag_ok else 'FAIL'}")
print(f"  固有値の全体最小 = {float(min_pred):.3e}  ->  "
      f"{'PASS（すべて正）' if min_pred > _sage_const_0  else 'FAIL'}")
print(f"  相異なる eps で固有値が一致した隣接ペアの個数 = {n_degenerate}"
      f"（>0 が正常。mu <-> M+1-mu の縮退。本文は「固有値がすべて相異なる」とは主張しない）")
ok_all &= min_imag_ok and (min_pred > _sage_const_0 )

print("check_03:", "PASS" if ok_all else "FAIL")

