# 対象ラベル: claim_cyclic_shift_adjacent_integer_sum
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_inverse_left_definition.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_inverse_left_remainder.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_inverse_left_cancel.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_inverse_left_representative.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_inverse_right_definition.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_inverse_right_remainder.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_inverse_right_cancel.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_inverse_right_representative.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_successor_definition.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_successor_remainder.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_successor_associate.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_successor_commute.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_successor_unassociate.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_successor_restore_remainder.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_successor_fold_definition.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_sum_successor.sage')
load('sagemath/check/cyclic-shift-adjacent-integer-sum/check_sum_reindex.sage')
print('RESULT: PASS')
