

# This file was *autogenerated* from the file lte_p2_complete.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_70 = Integer(70); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_15 = Integer(15); _sage_const_30 = Integer(30); _sage_const_11 = Integer(11)# cycle 8 / T1: LTE を p=2 も含め完全に検証(命題化のため)。
# p 奇, p∤c: v_p(c^L-1) = 0 (ord∤L) / v_p(c^ord-1)+v_p(L) (ord|L)。
# p=2, c 奇: v_2(c^L-1) = v_2(c-1) (L 奇) / v_2(c-1)+v_2(c+1)+v_2(L)-1 (L 偶)。

def v2_LTE(c,L):
    if c%_sage_const_2 ==_sage_const_0 : return None
    if L%_sage_const_2 ==_sage_const_1 : return ZZ(c-_sage_const_1 ).valuation(_sage_const_2 )
    return ZZ(c-_sage_const_1 ).valuation(_sage_const_2 )+ZZ(c+_sage_const_1 ).valuation(_sage_const_2 )+ZZ(L).valuation(_sage_const_2 )-_sage_const_1 

print("="*_sage_const_70 )
print("p=2 LTE 検証: v_2(c^L-1)")
print("="*_sage_const_70 )
allok=True
for c in [_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_9 ,_sage_const_15 ]:
    ok=all( (c**L-_sage_const_1 ).valuation(_sage_const_2 )==v2_LTE(c,L) for L in range(_sage_const_1 ,_sage_const_30 ) )
    allok=allok and ok
    print(f"  c={c}: v_2(c^L-1)=LTE 予測 (L=1..29): {ok}; v_2 列 L=1..10: {[(c**L-_sage_const_1 ).valuation(_sage_const_2 ) for L in range(_sage_const_1 ,_sage_const_11 )]}")
print(f"\n p=2 LTE 全 c で一致: {allok}")
print("="*_sage_const_70 )

