

# This file was *autogenerated* from the file check_01_center_and_injectivity.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_1en6 = RealNumber('1e-6')# <injectivity_of_T_up_to_scalar>, <center_of_multiplicative_group_is_scalar>
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import itertools
rng = np.random.default_rng(int(_sage_const_3 ))
rep = CheckReport("injectivity_of_T_up_to_scalar")
for M in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ]:
    n = _sage_const_2 **M
    gens = [Zop(m,M) for m in range(_sage_const_1 ,M+_sage_const_1 )] + [Yop(m,M) for m in range(_sage_const_1 ,M+_sage_const_1 )]
    blocks = [np.kron(g, np.eye(n)) - np.kron(np.eye(n), g.T) for g in gens]
    sv = np.linalg.svd(np.vstack(blocks), compute_uv=False)
    nullity = int(np.sum(sv < _sage_const_1en8 )) + (n*n - len(sv))
    print(f"  M={M}: [W,g]=0 の解空間の次元 = {nullity}")
    rep.truth(nullity == _sage_const_1 , f"M={M}: 乗法群の中心はスカラーのみ（次元 1）")
    for _ in range(_sage_const_3 ):
        g = _expm(rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n)))
        c = complex(rng.normal(), rng.normal())
        X = rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n))
        rep.close(T_conj(c*g, X), T_conj(g, X), f"M={M}: T_(cg) = T_g（⟸ 方向）")
        # ⟹ : T_g = T_{g'} ⟺ g^{-1}g' が中心 ⟺ スカラー。解空間が 1 次元であることが根拠。
        gp = c*g
        h = np.linalg.inv(g) @ gp
        rep.close(h, c*np.eye(n), f"M={M}: g^-1 g' はスカラー")
    # スカラーでない h では T が変わる
    for _ in range(_sage_const_3 ):
        g = _expm(rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n)))
        h = _expm(rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n)))
        if np.max(np.abs(h - (np.trace(h)/n)*np.eye(n))) < _sage_const_1en6 :
            continue
        X = rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n))
        rep.truth(np.max(np.abs(T_conj(g@h, X) - T_conj(g, X))) > _sage_const_1en8 ,
                  f"M={M}: スカラーでない倍率では T が変わる")
rep.finish()

