

# This file was *autogenerated* from the file check_01_periodicity.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_2 = Integer(2); _sage_const_2p0 = RealNumber('2.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_0p4407 = RealNumber('0.4407'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_1p1 = RealNumber('1.1'); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16)# <gamma2_theta_M_periodicity>: gamma_2(theta_M) = gamma_2(theta_{-M}) など
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np

def crit_K1(K2):
    """臨界条件 sinh(2K_1) sinh(2K_2) = 1 をちょうど満たす K_1。"""
    return float(np.arcsinh(_sage_const_1p0 /np.sinh(_sage_const_2 *K2))/_sage_const_2p0 )

CRIT_PARAMS = [{"K1": crit_K1(k2), "K2": k2} for k2 in [_sage_const_0p3 , _sage_const_0p4407 , _sage_const_0p6 , _sage_const_1p1 ]]
ALL_PARAMS = list(OP_TEST_PARAMS) + CRIT_PARAMS

rep = CheckReport("gamma2_theta_M_periodicity")
for M in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_8 ,_sage_const_16 ]:
    for p in ALL_PARAMS:
        K1,K2 = p['K1'],p['K2']
        thM, thmM = theta_mu_of(M,M), theta_mu_of(-M,M)
        rep.close(gamma2_of(thM,K1,K2), gamma2_of(thmM,K1,K2), f"M={M}: gamma_2(theta_M) = gamma_2(theta_-M)")
        rep.close(gamma2_of(-thM,K1,K2), gamma2_of(-thmM,K1,K2), f"M={M}: gamma_2(-theta_M) = gamma_2(-theta_-M)")
        rep.close(gamma1_of(thM,K1,K2), gamma1_of(thmM,K1,K2), f"M={M}: gamma_1 も同様")
        # theta_M = 2pi, theta_{-M} = -2pi なので cos/sin が一致するのが根拠
        rep.close(np.cos(thM), np.cos(thmM), f"M={M}: cos(2pi) = cos(-2pi)")
        rep.close(np.sin(thM), np.sin(thmM), f"M={M}: sin(2pi) = sin(-2pi)")
rep.finish()

