

# This file was *autogenerated* from the file check_01_product_rule.sage
from sage.all_cmdline import *   # import sage library

_sage_const_306 = Integer(306); _sage_const_2 = Integer(2); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0j = ComplexNumber(0, '0')# <kronecker_product_rule>: (1) 積の分解、(2) 単位行列、(3) ベクトルへの作用
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import math
rng = np.random.default_rng(int(_sage_const_306 ))
rep = CheckReport("kronecker_product_rule")
def r2(): return rng.normal(size=(_sage_const_2 ,_sage_const_2 )) + _sage_const_1j *rng.normal(size=(_sage_const_2 ,_sage_const_2 ))
def rv(): return rng.normal(size=(_sage_const_2 ,)) + _sage_const_1j *rng.normal(size=(_sage_const_2 ,))
for M in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_5 ]:
    for _ in range(_sage_const_5 ):
        As = [r2() for _ in range(M)]; Bs = [r2() for _ in range(M)]; vs = [rv() for _ in range(M)]
        rep.close(kron_list(As) @ kron_list(Bs), kron_list([As[k] @ Bs[k] for k in range(M)]),
                  f"M={M}: (1) 積の分解")
        rep.close(kron_list([I2]*M), np.eye(_sage_const_2 **M), f"M={M}: (2) 単位行列")
        lv = kron_list([v.reshape(_sage_const_2 ,_sage_const_1 ) for v in vs]).reshape(-_sage_const_1 )
        rv_ = kron_list([(As[k] @ vs[k]).reshape(_sage_const_2 ,_sage_const_1 ) for k in range(M)]).reshape(-_sage_const_1 )
        rep.close(kron_list(As) @ lv, rv_, f"M={M}: (3) ベクトルへの作用")
    # 添字づけ nu(I) = 1 + sum (i_k-1) 2^{M-k} が numpy の kron と一致すること
    import itertools
    As = [r2() for _ in range(M)]
    K = kron_list(As)
    for I_ in itertools.product([_sage_const_1 ,_sage_const_2 ], repeat=M):
        for J_ in itertools.product([_sage_const_1 ,_sage_const_2 ], repeat=M):
            nu_i = sum((I_[k]-_sage_const_1 )*_sage_const_2 **(M-_sage_const_1 -k) for k in range(M))
            nu_j = sum((J_[k]-_sage_const_1 )*_sage_const_2 **(M-_sage_const_1 -k) for k in range(M))
            prod = _sage_const_1p0 +_sage_const_0j 
            for k in range(M):
                prod *= As[k][I_[k]-_sage_const_1 , J_[k]-_sage_const_1 ]
            rep.close(K[nu_i, nu_j], prod, f"M={M}: 成分の定義式（nu による添字づけ）")
rep.finish()

