

# This file was *autogenerated* from the file check_01_arg_pi_split.sage
from sage.all_cmdline import *   # import sage library

_sage_const_301 = Integer(301); _sage_const_0 = Integer(0); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_60 = Integer(60); _sage_const_0p3 = RealNumber('0.3'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1en12 = RealNumber('1e-12'); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_1en7 = RealNumber('1e-7'); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3)# <range_of_args_of_multiple_of_complex_numbers>: arg(z1 z2) = pi のとき arg z1 + arg z2 = pi または 3pi
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import math
load(os.path.join(_dir, "_prelude.sage"))
rng = np.random.default_rng(int(_sage_const_301 ))
rep = CheckReport("range_of_args_of_multiple_of_complex_numbers")
c1 = c2 = _sage_const_0 
# arg(z1 z2) = pi となる組を作る: z2 = -t/z1 （t > 0 実数）とすれば z1 z2 = -t で arg = pi
for z1 in [z for z in sample_complex(rng) if abs(z) > _sage_const_1en9 ][:_sage_const_60 ]:
    for t in [_sage_const_0p3 , _sage_const_1p0 , _sage_const_2p5 ]:
        z2 = complex(-t,_sage_const_0 )/z1
        if abs(z2) < _sage_const_1en12 : continue
        if abs(arg_def(z1*z2) - math.pi) > _sage_const_1en8 : continue
        a1, a2 = arg_def(z1), arg_def(z2)
        ssum = a1 + a2
        if abs(ssum - math.pi) < _sage_const_1en7 :
            c1 += _sage_const_1 
            rep.truth(True, f"z1={z1}: 第1の場合 arg1+arg2 = pi")
        elif abs(ssum - _sage_const_3 *math.pi) < _sage_const_1en7 :
            c2 += _sage_const_1 
            rep.truth(True, f"z1={z1}: 第2の場合 arg1+arg2 = pi + 2pi")
        else:
            rep.truth(False, f"z1={z1}: arg1+arg2 = {ssum:.12f} がどちらの場合にも当てはまらない")
print(f"  第1の場合 {c1} 件、第2の場合 {c2} 件")
rep.truth(c1 > _sage_const_0  and c2 > _sage_const_0 , "両方の場合を実際に踏んでいる")
rep.finish()

