#!/usr/bin/env bash
# 本プロジェクトの主要定理が sorry に依存していないことを確認する。
#
# 使い方:
#   cd exact-solution-of-2d-ising-model/lean && ./scripts/check-no-sorry.sh
#
# 終了コード 0 = すべて sorry 非依存。1 = sorryAx への依存またはソース中の sorry を検出。
set -euo pipefail

cd "$(dirname "$0")/.."

# lake は elan 経由で入るため、非対話シェルの PATH に無いことがある。
# PATH に無ければ elan の既定インストール先を探す。
if ! command -v lake >/dev/null 2>&1; then
  if [ -x "$HOME/.elan/bin/lake" ]; then
    PATH="$HOME/.elan/bin:$PATH"
    export PATH
  else
    echo "NG: lake が見つからない（elan を導入し PATH を通すこと）" >&2
    exit 1
  fi
fi

status=0

# 1. ソース中に sorry / admit が残っていないか
if grep -rn --include='*.lean' -E '\bsorry\b|\badmit\b' Ising2D.lean Ising2D/; then
  echo "NG: ソース中に sorry / admit が残っている" >&2
  status=1
else
  echo "OK: ソース中に sorry / admit は無い"
fi

# 2. 主要定理の依存公理に sorryAx が含まれていないか
targets=(
  Ising2D.tensorPowBasis
  Ising2D.matTensorPowBasis
  Ising2D.tensorPowAlgEquiv
  Ising2D.toFinPowAlgEquiv
  Ising2D.E_mul_E
  Ising2D.one_eq_sum_E
  Ising2D.scalar_identity_commutes
  Ising2D.scalar_identity_commutes_fin
  Ising2D.Abstract.smul_one_commute
  Ising2D.Abstract.smul_one_sub_comm
  Ising2D.Abstract.centralizer_is_scalar_semiring
  Ising2D.Abstract.centralizer_is_scalar_commSemiring
  Ising2D.Abstract.single_mul_single_eq_ite
  Ising2D.Abstract.one_eq_sum_single
  Ising2D.matComm_mul_eq_matAcomm_sub_matAcomm
  Ising2D.centralizer_is_scalar
  Ising2D.centralizer_is_scalar_abstract
  Ising2D.matExp_units_conj
  Ising2D.Conjugation.T_mul
  Ising2D.Conjugation.T_one
  Ising2D.Conjugation.T_add
  Ising2D.Conjugation.T_comp
  Ising2D.Conjugation.TMonoidHom
  Ising2D.Conjugation.matrix_conj_mul
  Ising2D.Conjugation.matrix_conj_one
  Ising2D.Conjugation.matrix_conj_comp
  Ising2D.commutator_via_anticommutators
  Ising2D.lie_mul_eq_acomm_sub_acomm
  Ising2D.matrix_commutator_via_anticommutators
  Ising2D.sum_smul_mul_sum_smul
  Ising2D.acomm_sum_smul_left
  Ising2D.acomm_sum_smul
  Ising2D.siteOp_one
  Ising2D.siteOp_mul_same
  Ising2D.siteOp_mul_comm
  Ising2D.sigmaX_eq
  Ising2D.jw_eq_xString_mul
  Ising2D.Z_eq_xString_mul
  Ising2D.Y_eq_xString_mul
  Ising2D.xString_mul_self
  Ising2D.jw_mul_jw_same
  Ising2D.Z_mul_Y_same
  Ising2D.xString_succ_eq
  Ising2D.siteProd_smul_family
  Ising2D.siteProd_anticomm_of_single_site
  Ising2D.jw_sq
  Ising2D.jw_anticomm
  Ising2D.anticomm_Z_Z
  Ising2D.anticomm_Z_Y
  Ising2D.anticomm_Y_Y
  Ising2D.matrix_two_decomp
  Ising2D.siteProd_mem
  Ising2D.E_eq_siteProd
  Ising2D.Z_Y_generate_algebra
  Ising2D.acomm_ZY
  Ising2D.linearIndependent_of_clifford
  Ising2D.ZY_linearIndependent
  Ising2D.ZY_injective
  Ising2D.ZYSet_eq_range
  Ising2D.ZYSet_linearIndepOn
  Ising2D.expPhase_add
  Ising2D.expPhase_neg
  Ising2D.expPhase_natCast_mul
  Ising2D.expPhase_eq_zpow
  Ising2D.expPhase_eq_one_iff
  Ising2D.expPhase_sum
  Ising2D.dvd_sub_iff_eq
  Ising2D.hatZMinus_eq
  Ising2D.hatZPlus_eq_hatZMinus_sub
  Ising2D.expPhase_add_mul_natCast
  Ising2D.hatZ_periodic
  Ising2D.hatY_periodic
  Ising2D.hatZMinus_M_eq_neg_M
  Ising2D.hatY_M_eq_neg_M
  Ising2D.inverse_dft
  Ising2D.recover_Y
  Ising2D.recover_Z
  Ising2D.Y_eq_inverse_dft
  Ising2D.Z_eq_inverse_dft
  Ising2D.acomm_sum_smul_clifford
  Ising2D.acomm_sum_smul_zero
  Ising2D.acomm_Z_Z_clifford
  Ising2D.acomm_Y_Y_clifford
  Ising2D.expPhase_site_mul
  Ising2D.acomm_hatZ_hatZ_same
  Ising2D.acomm_hatZ_hatZ_opp
  Ising2D.acomm_hatZ_hatY
  Ising2D.acomm_hatY_hatZ
  Ising2D.acomm_hatY_hatY
  Ising2D.acomm_hatZPlus_hatZPlus
  Ising2D.acomm_hatZMinus_hatZMinus
  Ising2D.acomm_hatZPlus_hatZMinus
  Ising2D.nextSite
  Ising2D.nextSite_val_of_lt
  Ising2D.nextSite_val_of_last
  Ising2D.lastSign_of_last
  Ising2D.lastSign_of_not_last
  Ising2D.lastSign_one
  Ising2D.H1
  Ising2D.H2
  Ising2D.I_smul_H2_eq_sum_sigmaX
  Ising2D.V1
  Ising2D.V1half
  Ising2D.V2
  Ising2D.V1half_sq
  Ising2D.matExpUnits
  Ising2D.matExpUnits_val
  Ising2D.matExpUnits_inv
  Ising2D.smulUnits
  Ising2D.smulUnits_val
  Ising2D.V1Units
  Ising2D.V1halfUnits
  Ising2D.V1Units_val
  Ising2D.V1halfUnits_val
  Ising2D.isUnit_V1
  Ising2D.isUnit_V1half
  Ising2D.rpow_two_s2_ne_zero
  Ising2D.V2Units
  Ising2D.V2Units_val
  Ising2D.isUnit_V2
  Ising2D.TConj
  Ising2D.TConj_apply
  Ising2D.TConj_linear
  Ising2D.TConj_trans
  Ising2D.TV
  Ising2D.TV_apply
  Ising2D.TV_eq_TConj
  Ising2D.TV_linear
  Ising2D.TV_mul
  Ising2D.TV_one
  Ising2D.ActsBy
  Ising2D.ActsBy.comp
  Ising2D.ActsBy.eigen
  Ising2D.B1mat
  Ising2D.B2mat
  Ising2D.B1_mul_B2_mul_B1_eq_explicit
  Ising2D.B1_mul_B2_mul_B1_eq_AMat
  Ising2D.TV_hatZ_hatY_of_action
  "Ising2D.TV_hatZ_hatY_of_action'"
  Ising2D.gamma2_neg
  Ising2D.gamma1_neg
  Ising2D.AMat_eq
  Ising2D.gamma2_neg_eq_neg_conj
  Ising2D.gamma2_mul_gamma2_neg_eq_neg_normSq
  Ising2D.gamma2_neg_eq_zero_iff
  Ising2D.gamma2_add_int_mul_two_pi
  Ising2D.gamma2_add_two_pi
  Ising2D.thetaMu_neg
  Ising2D.thetaMu_add_int_mul
  Ising2D.gamma2_thetaMu_add_M
  Ising2D.gamma2_thetaMu_of_dvd
  Ising2D.gamma2_eq_zero_iff
  Ising2D.gamma2_eq_zero_iff_of_s2star_ne_zero
  Ising2D.sin_thetaMu_eq_zero_iff
  Ising2D.charPoly_expand
  Ising2D.charPoly_root
  Ising2D.charPoly_factor
  Ising2D.AMat_mulVec_eigen
  "Ising2D.AMat_mulVec_eigen'"
  Ising2D.AMat_mulVec_col_pos
  Ising2D.AMat_mulVec_col_neg
  Ising2D.AMat_of_gamma2_eq_zero
  Ising2D.det_AMat
  Ising2D.gamma2_mul_gamma2_neg
  Ising2D.det_AMat_eq_one
  Ising2D.gamma1_sq_eq_one_of_gamma2_eq_zero
  Ising2D.lambda_mul_lambda
  Ising2D.det_Pmat
  Ising2D.det_Pmat_ne_zero
  Ising2D.AMat_mul_Pmat
  Ising2D.AMat_eq_Pmat_mul_Dmat_mul_inv
  Ising2D.AMat_thetaMu_eq_Pmat_mul_Dmat_mul_inv
  Ising2D.acomm_lin2
  Ising2D.acomm_hatZMinus_hatY_lin2
  Ising2D.sqrtM
  Ising2D.sqrtM_ne_zero
  Ising2D.sqrtM_sq
  Ising2D.psiDag
  Ising2D.psi
  Ising2D.psiDag_eq
  Ising2D.psi_eq
  Ising2D.t_ne_zero
  Ising2D.gamma2_neg_mul_gamma2_neg_of_dvd
  Ising2D.t_sq_eq_of_dvd
  Ising2D.acomm_psiDag_psiDag
  Ising2D.acomm_psi_psi
  Ising2D.acomm_psiDag_psi
  Ising2D.Pmat_col_zero
  Ising2D.Pmat_col_one
  Ising2D.AMat_mulVec_Pmat_col_zero
  Ising2D.AMat_mulVec_Pmat_col_one
  Ising2D.Dmat_zero_zero
  Ising2D.Dmat_one_one
  Ising2D.TV_psiDag_of_action
  Ising2D.TV_psi_of_action
  Ising2D.TV_psiDag_psi_of_action
  Ising2D.Abstract.acomm_lincomb
  Ising2D.Abstract.acomm_lincomb_clifford
  Ising2D.Abstract.car_of_coeffs
  Ising2D.acomm_hatZMinus_hatY_lin2_of_abstract
  Ising2D.psi_eq_neg_coeff
  Ising2D.psi_coeff_identities
  Ising2D.acomm_psi_relations_of_car
  Ising2D.acomm_psiDag_psiDag_of_opposite_branch
  Ising2D.acomm_psiDag_psi_of_opposite_branch
  Ising2D.expPhase_congr
  Ising2D.hatZ_congr
  Ising2D.hatY_congr
  Ising2D.nextSite_val
  Ising2D.dvd_succ_sub_iff_eq_nextSite
  Ising2D.firstSign_nextSite
  Ising2D.H1_eq_hat_sum
  Ising2D.H2_eq_hat_sum
  Ising2D.H2_eq_hatZMinus_sum
  Ising2D.Abstract.lie_smul_left
  Ising2D.Abstract.lie_sum_smul_left
  Ising2D.Abstract.lie_mul_of_acomm_smul_one
  Ising2D.Abstract.lie_sum_smul_mul_of_acomm_smul_one
  Ising2D.Abstract.CliffordTriple.lie_sum_yz_z
  "Ising2D.Abstract.CliffordTriple.lie_sum_yz_z'"
  Ising2D.Abstract.CliffordTriple.lie_sum_yz_y
  Ising2D.Abstract.CliffordTriple.lie_sum_zy_z
  "Ising2D.Abstract.CliffordTriple.lie_sum_zy_z'"
  Ising2D.Abstract.CliffordTriple.lie_sum_zy_y
  Ising2D.expPhase_ne_zero
  Ising2D.deltaMod_neg
  Ising2D.deltaMod_succ_eq
  Ising2D.deltaMod_val_eq
  Ising2D.sum_deltaMod_select
  Ising2D.sum_hatY
  Ising2D.sum_expPhase_neg_smul_hatY
  Ising2D.hatCliffordTriple
  Ising2D.lie_H1_hatZ_same
  Ising2D.lie_H1_hatY
  Ising2D.lie_H1_hatZ_opp
  Ising2D.lie_H2_hatZMinus
  Ising2D.lie_H2_hatY
  Ising2D.lie_H2_hatZPlus
  Ising2D.Y_ne_zero
  Ising2D.lie_H1_hatZ_opp_ne_orig
  Ising2D.lie_H2_hatZPlus_ne_orig
  Ising2D.lie_H1Plus_hatZPlus
  Ising2D.lie_H1Minus_hatZMinus
  Ising2D.lie_H1Plus_hatY
  Ising2D.lie_H1Minus_hatY
  "Ising2D.lie_H2_hatZMinus'"
  "Ising2D.lie_H2_hatY'"
  "Ising2D.lie_H2_hatZPlus'"
  Ising2D.Abstract.sinhc
  Ising2D.Abstract.sinhc_zero
  Ising2D.Abstract.sinhc_of_ne_zero
  Ising2D.Abstract.mul_sinhc
  Ising2D.Abstract.hasSum_sinhc
  Ising2D.Abstract.lmulCLM
  Ising2D.Abstract.rmulCLM
  Ising2D.Abstract.adCLM
  Ising2D.Abstract.lmulCLM_apply
  Ising2D.Abstract.rmulCLM_apply
  Ising2D.Abstract.adCLM_apply
  Ising2D.Abstract.commute_lmulCLM_rmulCLM
  Ising2D.Abstract.lmulCLM_pow
  Ising2D.Abstract.rmulCLM_pow
  Ising2D.Abstract.exp_lmulCLM
  Ising2D.Abstract.exp_rmulCLM
  Ising2D.Abstract.exp_adCLM_apply
  Ising2D.Abstract.hasSum_exp_conj
  Ising2D.Abstract.exp_conj_eq_tsum
  Ising2D.Abstract.adCLM_sq_z
  Ising2D.Abstract.adCLM_sq_y
  Ising2D.Abstract.adCLM_pow_even
  Ising2D.Abstract.adCLM_pow_odd_z
  Ising2D.Abstract.adCLM_pow_odd_y
  Ising2D.Abstract.exp_conj_two_dim_z
  Ising2D.Abstract.exp_conj_two_dim_y
  Ising2D.adPow
  Ising2D.adPow_zero
  Ising2D.adPow_succ
  Ising2D.adPow_eq_adCLM
  Ising2D.hasSum_matExp_conj
  Ising2D.matExp_conj_eq_tsum
  Ising2D.matExpUnits_conj_eq_tsum
  Ising2D.matExp_conj_two_dim_z
  Ising2D.matExp_conj_two_dim_y
  Ising2D.Abstract.conj_smul_eq
  Ising2D.Abstract.twoDimConjMat
  Ising2D.Abstract.exp_conj_two_dim_actsBy
  Ising2D.expPhase_eq_exp_neg_thetaMu
  Ising2D.expPhase_neg_eq_exp_thetaMu
  Ising2D.B1mat_eq_twoDimConjMat
  Ising2D.B2mat_eq_twoDimConjMat
  Ising2D.actsBy_TConj_matExpUnits
  Ising2D.actsBy_TConj_smulUnits
  Ising2D.ad_V1half_hatZMinus
  Ising2D.ad_V1half_hatY
  Ising2D.actsBy_TConj_V1half
  Ising2D.ad_V2_hatZMinus
  Ising2D.ad_V2_hatY
  Ising2D.actsBy_TConj_V2
  Ising2D.TV_hatZ_hatY
  Ising2D.TV_psiDag
  Ising2D.TV_psi
  Ising2D.TV_psiDag_psi
  Ising2D.Abstract.acomm_sum_smul_clifford_left
  Ising2D.Abstract.linearIndependent_of_clifford_abstract
  Ising2D.smul_one_faithful_tensorPow
  Ising2D.ZY_linearIndependent_of_abstract
  Ising2D.Abstract.sum_zpow_primitiveRoot
  Ising2D.zetaM
  Ising2D.isPrimitiveRoot_zetaM
  Ising2D.zetaM_ne_zero
  Ising2D.expPhase_eq_zetaM_zpow
  Ising2D.expPhase_eq_zetaM_zpow_neg
  Ising2D.expPhase_sum_of_abstract
  Ising2D.Abstract.acomm_sum_smul_clifford_abstract
  Ising2D.Abstract.acomm_fourier_clifford_weights
  Ising2D.Abstract.acomm_fourier_clifford
  Ising2D.Abstract.acomm_fourier_clifford_flip
  Ising2D.hatZ_eq_weighted_zetaM
  Ising2D.hatY_eq_weighted_zetaM
  Ising2D.deltaMod_eq_ite_neg
  Ising2D.acomm_hatZ_hatZ_same_of_abstract
  Ising2D.acomm_hatY_hatY_of_abstract
  Ising2D.acomm_hatZPlus_hatZMinus_of_abstract
  Ising2D.Abstract.acomm_of_single_site
  Ising2D.Abstract.sq_eq_one_of_site_sq_eq_one
  Ising2D.Abstract.jwStr
  Ising2D.Abstract.acomm_jwStr
  Ising2D.Abstract.jwStr_sq
  Ising2D.siteProd_isSiteProd
  Ising2D.jwFamily_eq_jwStr
  Ising2D.jw_anticomm_of_abstract
  Ising2D.jw_sq_of_abstract
  Ising2D.anticomm_Z_Z_of_abstract
  Ising2D.anticomm_Z_Y_of_abstract
  Ising2D.anticomm_Y_Y_of_abstract
  Ising2D.Abstract.fin_dvd_sub_iff_eq
  Ising2D.Abstract.zpow_mul_add_natCast
  Ising2D.Abstract.transform_periodic
  Ising2D.Abstract.inverse_dft_abstract
  Ising2D.expPhase_eq_zetaM_zpow_freq
  Ising2D.hatZ_periodic_of_abstract
  Ising2D.hatY_periodic_of_abstract
  Ising2D.hatZMinus_M_eq_neg_M_of_abstract
  Ising2D.hatY_M_eq_neg_M_of_abstract
  Ising2D.inverse_dft_of_abstract
  Ising2D.recover_Y_of_abstract
  Ising2D.recover_Z_of_abstract
  Ising2D.configBasisIso
  Ising2D.sgn_configBasisIso
  Ising2D.Abstract.prod_entry_eq_zero_of_ne
  Ising2D.siteProd_diagonal
  Ising2D.sigmaZ_eq_diagonal
  Ising2D.sigmaZ_mulVec_basisVec
  Ising2D.sigmaZ_mulVec_basisVec_spin
  Ising2D.Abstract.map_exp_of_continuous
  Ising2D.exp_pi_apply
  Ising2D.matrixExp_diagonal
  Ising2D.matrixExp_diagonal_apply
  Ising2D.V1pauli_eq_diagonal
  Ising2D.V1pauli_eq_V1comp
  Ising2D.V1_component_equals_pauli
  Ising2D.exp_smul_pauliX
  Ising2D.exp_smul_pauliX_eq_cosh_add_sinh
  Ising2D.exp_neg_Kstar
  Ising2D.exp_Kstar
  Ising2D.sqrt_two_s2_mul_cosh_Kstar
  Ising2D.sqrt_two_s2_mul_sinh_Kstar
  Ising2D.two_by_two_transfer_identity
  Ising2D.exp_smul_sum_sigmaX
  Ising2D.V2_eq_V2pauli
  Ising2D.V2comp_eq_siteProd_twoByTwo
  Ising2D.V2pauli_eq_V2comp
  Ising2D.V2_component_equals_pauli
  Ising2D.Abstract.openW_snoc
  Ising2D.Abstract.pow_succ_apply_eq_sum
  Ising2D.Abstract.trace_pow_succ
  Ising2D.partitionFunction_eq_conf
  Ising2D.partitionFunctionC_eq_trace
  Ising2D.partition_function_in_pauli_form
  Ising2D.partition_function_in_pauli_form_V2
  Ising2D.Abstract.invProj_sq
  Ising2D.Abstract.invProj_mul_invProj_neg
  Ising2D.Abstract.invProj_add_invProj_neg
  Ising2D.Abstract.commute_invProj
  Ising2D.Abstract.pow_mul_proj
  Ising2D.Abstract.mul_pow_conj_left
  Ising2D.epsProj_sq
  Ising2D.epsProj_mul_epsProj_neg
  Ising2D.epsProj_add_epsProj_neg
  Ising2D.epsProj_mulVec_mem
  Ising2D.epsProj_mulVec_eq_self
  Ising2D.epsilon_commute_sigmaX
  Ising2D.epsilon_anticomm_sigmaZ
  Ising2D.epsilon_anticomm_sigmaY
  Ising2D.epsilon_commute_V1pauli
  Ising2D.epsilon_commute_V2pauli
  Ising2D.epsilon_commute_V1
  Ising2D.epsilon_commute_V1half
  Ising2D.commute_epsProj_of_commute_epsilon
  Ising2D.sector_replacement_of_V1
  Ising2D.sector_replacement_pow
  Ising2D.trace_eq_sector_sum
  Ising2D.trace_epsProj_sym_pow
  Ising2D.trace_epsProj_sym_pow_eq_plain
  Ising2D.partition_function_sector_decomposition
  Ising2D.Abstract.continuous_arcosh_comp
  Ising2D.Abstract.cosh_sub_le_cosh_mul_cosh_sub
  Ising2D.Abstract.one_le_cosh_mul_cosh_sub
  Ising2D.Abstract.abs_integral_sub_riemann_sum_le
  Ising2D.Abstract.abs_integral_sub_riemann_sum_le_modulus
  Ising2D.Abstract.tendsto_modulus_atTop
  Ising2D.Abstract.tendsto_riemann_sum
  Ising2D.Abstract.abs_log_div_sub_log_le_of_sandwich
  Ising2D.Abstract.log_rpow_mul_exp
  Ising2D.Abstract.tendsto_affine
  Ising2D.gamma1_lower_bound_all_theta
  Ising2D.gamma1R_ge_cosh_sub
  Ising2D.one_le_gamma1R
  Ising2D.gammaFn_nonneg
  Ising2D.cosh_gammaFn
  Ising2D.gamma_is_continuous
  Ising2D.gammaFn_periodic
  Ising2D.abs_log_Z_sub_log_c_le
  Ising2D.limit_of_log_Z_in_N_row
  Ising2D.riemann_sum_to_integral_error
  Ising2D.riemann_sum_to_integral
  Ising2D.riemann_sum_to_integral_indep_delta
  Ising2D.log_LambdaM
  Ising2D.inv_M_log_LambdaM
  Ising2D.onsager_free_energy_expression
  Ising2D.onsager_free_energy_expression_indep_delta
)

{
  echo "import Ising2D"
  for t in "${targets[@]}"; do
    echo "#print axioms $t"
  done
} > /tmp/ising2d_axiom_check.lean

out="$(lake env lean --stdin < /tmp/ising2d_axiom_check.lean)"
echo "$out"

if echo "$out" | grep -q 'sorryAx'; then
  echo "NG: sorryAx に依存している定理がある" >&2
  status=1
else
  echo "OK: 主要定理はいずれも sorryAx に依存していない"
fi

exit "$status"
