#!/usr/bin/env bash
# 本プロジェクトの主要定理が sorry に依存していないことを確認する。
#
# 使い方:
#   cd exact-solution-of-2d-ising-model/lean && ./scripts/check-no-sorry.sh
#
# 終了コード 0 = すべて sorry 非依存。1 = sorryAx への依存またはソース中の sorry を検出。
set -euo pipefail

cd "$(dirname "$0")/.."

# lake は elan 経由で入るため、非対話シェルの PATH に無いことがある。
# PATH に無ければ elan の既定インストール先を探す。
if ! command -v lake >/dev/null 2>&1; then
  if [ -x "$HOME/.elan/bin/lake" ]; then
    PATH="$HOME/.elan/bin:$PATH"
    export PATH
  else
    echo "NG: lake が見つからない（elan を導入し PATH を通すこと）" >&2
    exit 1
  fi
fi

status=0

# 1. ソース中に sorry / admit が残っていないか
if grep -rn --include='*.lean' -E '\bsorry\b|\badmit\b' Ising2D.lean Ising2D/; then
  echo "NG: ソース中に sorry / admit が残っている" >&2
  status=1
else
  echo "OK: ソース中に sorry / admit は無い"
fi

# 2. 主要定理の依存公理に sorryAx が含まれていないか
targets=(
  Ising2D.tensorPowBasis
  Ising2D.matTensorPowBasis
  Ising2D.NecSuf.matrix_eq_sum_smul_single
  Ising2D.NecSuf.sum_smul_single_apply
  Ising2D.NecSuf.linearIndependent_single
  Ising2D.NecSuf.matrixUnitBasis
  Ising2D.NecSuf.coe_matrixUnitBasis_eq_stdBasis
  Ising2D.NecSuf.basisOfLinearEquiv
  Ising2D.EBasis
  Ising2D.EBasis_apply
  Ising2D.coe_EBasis_eq_matrixUnitBasis
  Ising2D.matrix_eq_sum_E
  Ising2D.kroneckerTensorPowBasis
  Ising2D.kroneckerTensorPowBasis_apply
  Ising2D.tensorPowAlgEquiv
  Ising2D.toFinPowAlgEquiv
  Ising2D.E_mul_E
  Ising2D.one_eq_sum_E
  Ising2D.scalar_identity_commutes
  Ising2D.scalar_identity_commutes_fin
  Ising2D.NecSuf.smul_one_commute
  Ising2D.NecSuf.smul_one_sub_comm
  Ising2D.NecSuf.centralizer_is_scalar_semiring
  Ising2D.NecSuf.centralizer_is_scalar_commSemiring
  Ising2D.NecSuf.single_mul_single_eq_ite
  Ising2D.NecSuf.one_eq_sum_single
  Ising2D.matComm_mul_eq_matAcomm_sub_matAcomm
  Ising2D.centralizer_is_scalar
  Ising2D.centralizer_is_scalar_abstract
  Ising2D.matExp_units_conj
  Ising2D.Y_mul_Z_next_of_not_last
  Ising2D.epsilon_mul_Y_mul_Z_next_of_last
  Ising2D.sum_sigmaZ_sigmaZ_eq_jordanWigner
  Ising2D.V1pauli_eq_jordanWigner
  Ising2D.mulVec_mem_sector_of_commute_epsilon
  Ising2D.Y_mul_Z_next_mulVec_mem_sector
  Ising2D.V1JordanWigner_generator_mulVec_mem_sector
  Ising2D.V1fixed_generator_mulVec_mem_sector
  Ising2D.H1JordanWigner_mulVec_eq_H1
  Ising2D.V1_generators_mulVec_eq
  Ising2D.V1_generators_pow_mulVec_eq
  Ising2D.V1_generator_partialSums_mulVec_eq
  Ising2D.V1pauli_mulVec_eq_V1
  Ising2D.V1_restrictsOnSector_of_opposite_sign
  Ising2D.V1_restrictsOnEvenSector
  Ising2D.V1_restrictsOnOddSector
  Ising2D.Conjugation.T_mul
  Ising2D.Conjugation.T_one
  Ising2D.Conjugation.T_add
  Ising2D.Conjugation.T_comp
  Ising2D.Conjugation.TMonoidHom
  Ising2D.Conjugation.matrix_conj_mul
  Ising2D.Conjugation.matrix_conj_one
  Ising2D.Conjugation.matrix_conj_comp
  Ising2D.NecSuf.Conj.sandwich_comp
  Ising2D.NecSuf.Conj.sandwich_mul
  Ising2D.NecSuf.Conj.sandwich_one
  Ising2D.NecSuf.Conj.sandwich_add
  Ising2D.NecSuf.Conj.conjMonoidHom
  Ising2D.NecSuf.Conj.conjMulAut
  Ising2D.NecSuf.Conj.conjMulAutHom
  Ising2D.NecSuf.Conj.conjMonoidHom_comp
  Ising2D.NecSuf.Conj.conjRingHom
  Ising2D.NecSuf.Conj.conjRingAutHom
  Ising2D.NecSuf.Conj.sandwich_mul_needs_left_inv
  Ising2D.NecSuf.Conj.sandwich_one_needs_right_inv
  Ising2D.Conjugation.T_eq_conjMonoidHom
  Ising2D.Conjugation.matrix_conj_mul_of_necSuf
  Ising2D.Conjugation.matrix_conj_one_of_necSuf
  Ising2D.Conjugation.matrix_conj_comp_of_necSuf
  Ising2D.Conjugation.matrix_conj_add_of_necSuf
  Ising2D.Conjugation.matrixConjRingAutHom
  Ising2D.Conjugation.matrixConjRingAutHom_nonsingInvUnit
  Ising2D.commutator_via_anticommutators
  Ising2D.lie_mul_eq_acomm_sub_acomm
  Ising2D.matrix_commutator_via_anticommutators
  Ising2D.sum_smul_mul_sum_smul
  Ising2D.acomm_sum_smul_left
  Ising2D.acomm_sum_smul
  Ising2D.siteOp_one
  Ising2D.siteOp_mul_same
  Ising2D.siteOp_mul_comm
  Ising2D.sigmaX_eq
  Ising2D.jw_eq_xString_mul
  Ising2D.Z_eq_xString_mul
  Ising2D.Y_eq_xString_mul
  Ising2D.xString_mul_self
  Ising2D.jw_mul_jw_same
  Ising2D.Z_mul_Y_same
  Ising2D.xString_succ_eq
  Ising2D.siteProd_smul_family
  Ising2D.siteProd_anticomm_of_single_site
  Ising2D.jw_sq
  Ising2D.jw_anticomm
  Ising2D.anticomm_Z_Z
  Ising2D.anticomm_Z_Y
  Ising2D.anticomm_Y_Y
  Ising2D.matrix_two_decomp
  Ising2D.siteProd_mem
  Ising2D.E_eq_siteProd
  Ising2D.Z_Y_generate_algebra
  Ising2D.NecSuf.eq_top_of_span_eq_top
  Ising2D.NecSuf.eq_top_of_basis_mem
  Ising2D.NecSuf.map_mem_of_span_eq_top
  Ising2D.NecSuf.map_mem_of_mulSingle_mem
  Ising2D.NecSuf.map_mem_subalgebra_of_mulSingle_mem
  Ising2D.NecSuf.string_mem
  Ising2D.NecSuf.local_mem
  Ising2D.xString_mem_adjoin_of_necSuf
  Ising2D.sigma_mem_adjoin_of_necSuf
  Ising2D.span_pauli_eq_top
  Ising2D.siteOp_mem_adjoin_of_necSuf
  Ising2D.siteProd_mem_of_necSuf
  Ising2D.Z_Y_generate_algebra_of_necSuf
  Ising2D.acomm_ZY
  Ising2D.linearIndependent_of_clifford
  Ising2D.ZY_linearIndependent
  Ising2D.ZY_injective
  Ising2D.ZYSet_eq_range
  Ising2D.ZYSet_linearIndepOn
  Ising2D.expPhase_add
  Ising2D.expPhase_neg
  Ising2D.expPhase_natCast_mul
  Ising2D.expPhase_eq_zpow
  Ising2D.expPhase_eq_one_iff
  Ising2D.expPhase_sum
  Ising2D.dvd_sub_iff_eq
  Ising2D.hatZMinus_eq
  Ising2D.hatZPlus_eq_hatZMinus_sub
  Ising2D.expPhase_add_mul_natCast
  Ising2D.hatZ_periodic
  Ising2D.hatY_periodic
  Ising2D.hatZMinus_M_eq_neg_M
  Ising2D.hatY_M_eq_neg_M
  Ising2D.inverse_dft
  Ising2D.recover_Y
  Ising2D.recover_Z
  Ising2D.Y_eq_inverse_dft
  Ising2D.Z_eq_inverse_dft
  Ising2D.acomm_sum_smul_clifford
  Ising2D.acomm_sum_smul_zero
  Ising2D.acomm_Z_Z_clifford
  Ising2D.acomm_Y_Y_clifford
  Ising2D.expPhase_site_mul
  Ising2D.acomm_hatZ_hatZ_same
  Ising2D.acomm_hatZ_hatZ_opp
  Ising2D.acomm_hatZ_hatY
  Ising2D.acomm_hatY_hatZ
  Ising2D.acomm_hatY_hatY
  Ising2D.acomm_hatZPlus_hatZPlus
  Ising2D.acomm_hatZMinus_hatZMinus
  Ising2D.acomm_hatZPlus_hatZMinus
  Ising2D.nextSite
  Ising2D.nextSite_val_of_lt
  Ising2D.nextSite_val_of_last
  Ising2D.lastSign_of_last
  Ising2D.lastSign_of_not_last
  Ising2D.lastSign_one
  Ising2D.H1
  Ising2D.H2
  Ising2D.I_smul_H2_eq_sum_sigmaX
  Ising2D.V1
  Ising2D.V1half
  Ising2D.V2
  Ising2D.V1half_sq
  Ising2D.matExpUnits
  Ising2D.matExpUnits_val
  Ising2D.matExpUnits_inv
  Ising2D.smulUnits
  Ising2D.smulUnits_val
  Ising2D.V1Units
  Ising2D.V1halfUnits
  Ising2D.V1Units_val
  Ising2D.V1halfUnits_val
  Ising2D.isUnit_V1
  Ising2D.isUnit_V1half
  Ising2D.rpow_two_s2_ne_zero
  Ising2D.V2Units
  Ising2D.V2Units_val
  Ising2D.isUnit_V2
  Ising2D.TConj
  Ising2D.TConj_apply
  Ising2D.TConj_linear
  Ising2D.TConj_trans
  Ising2D.TV
  Ising2D.TV_apply
  Ising2D.TV_eq_TConj
  Ising2D.TV_linear
  Ising2D.TV_mul
  Ising2D.TV_one
  Ising2D.ActsBy
  Ising2D.ActsBy.comp
  Ising2D.ActsBy.eigen
  Ising2D.B1mat
  Ising2D.B2mat
  Ising2D.B1_mul_B2_mul_B1_eq_explicit
  Ising2D.B1_mul_B2_mul_B1_eq_AMat
  Ising2D.TV_hatZ_hatY_of_action
  "Ising2D.TV_hatZ_hatY_of_action'"
  Ising2D.gamma2_neg
  Ising2D.gamma1_neg
  Ising2D.AMat_eq
  Ising2D.gamma2_neg_eq_neg_conj
  Ising2D.gamma2_mul_gamma2_neg_eq_neg_normSq
  Ising2D.gamma2_neg_eq_zero_iff
  Ising2D.gamma2_add_int_mul_two_pi
  Ising2D.gamma2_add_two_pi
  Ising2D.thetaMu_neg
  Ising2D.thetaMu_add_int_mul
  Ising2D.gamma2_thetaMu_add_M
  Ising2D.gamma2_thetaMu_of_dvd
  Ising2D.gamma2_eq_zero_iff
  Ising2D.gamma2_eq_zero_iff_of_s2star_ne_zero
  Ising2D.sin_thetaMu_eq_zero_iff
  Ising2D.charPoly_expand
  Ising2D.charPoly_root
  Ising2D.charPoly_factor
  Ising2D.AMat_mulVec_eigen
  "Ising2D.AMat_mulVec_eigen'"
  Ising2D.AMat_mulVec_col_pos
  Ising2D.AMat_mulVec_col_neg
  Ising2D.AMat_of_gamma2_eq_zero
  Ising2D.det_AMat
  Ising2D.gamma2_mul_gamma2_neg
  Ising2D.det_AMat_eq_one
  Ising2D.gamma1_sq_eq_one_of_gamma2_eq_zero
  Ising2D.lambda_mul_lambda
  Ising2D.det_Pmat
  Ising2D.det_Pmat_ne_zero
  Ising2D.AMat_mul_Pmat
  Ising2D.AMat_eq_Pmat_mul_Dmat_mul_inv
  Ising2D.AMat_thetaMu_eq_Pmat_mul_Dmat_mul_inv
  Ising2D.acomm_lin2
  Ising2D.acomm_hatZMinus_hatY_lin2
  Ising2D.sqrtM
  Ising2D.sqrtM_ne_zero
  Ising2D.sqrtM_sq
  Ising2D.psiDag
  Ising2D.psi
  Ising2D.psiDag_eq
  Ising2D.psi_eq
  Ising2D.t_ne_zero
  Ising2D.gamma2_neg_mul_gamma2_neg_of_dvd
  Ising2D.t_sq_eq_of_dvd
  Ising2D.acomm_psiDag_psiDag
  Ising2D.acomm_psi_psi
  Ising2D.acomm_psiDag_psi
  Ising2D.Pmat_col_zero
  Ising2D.Pmat_col_one
  Ising2D.AMat_mulVec_Pmat_col_zero
  Ising2D.AMat_mulVec_Pmat_col_one
  Ising2D.Dmat_zero_zero
  Ising2D.Dmat_one_one
  Ising2D.TV_psiDag_of_action
  Ising2D.TV_psi_of_action
  Ising2D.TV_psiDag_psi_of_action
  Ising2D.NecSuf.acomm_lincomb
  Ising2D.NecSuf.acomm_lincomb_clifford
  Ising2D.NecSuf.car_of_coeffs
  Ising2D.acomm_hatZMinus_hatY_lin2_of_necSuf
  Ising2D.psi_eq_neg_coeff
  Ising2D.psi_coeff_identities
  Ising2D.acomm_psi_relations_of_car
  Ising2D.acomm_psiDag_psiDag_of_opposite_branch
  Ising2D.acomm_psiDag_psi_of_opposite_branch
  Ising2D.expPhase_congr
  Ising2D.hatZ_congr
  Ising2D.hatY_congr
  Ising2D.nextSite_val
  Ising2D.dvd_succ_sub_iff_eq_nextSite
  Ising2D.firstSign_nextSite
  Ising2D.H1_eq_hat_sum
  Ising2D.H2_eq_hat_sum
  Ising2D.H2_eq_hatZMinus_sum
  Ising2D.NecSuf.lie_smul_left
  Ising2D.NecSuf.lie_sum_smul_left
  Ising2D.NecSuf.lie_mul_of_acomm_smul_one
  Ising2D.NecSuf.lie_sum_smul_mul_of_acomm_smul_one
  Ising2D.NecSuf.CliffordTriple.lie_sum_yz_z
  "Ising2D.NecSuf.CliffordTriple.lie_sum_yz_z'"
  Ising2D.NecSuf.CliffordTriple.lie_sum_yz_y
  Ising2D.NecSuf.CliffordTriple.lie_sum_zy_z
  "Ising2D.NecSuf.CliffordTriple.lie_sum_zy_z'"
  Ising2D.NecSuf.CliffordTriple.lie_sum_zy_y
  Ising2D.expPhase_ne_zero
  Ising2D.deltaMod_neg
  Ising2D.deltaMod_succ_eq
  Ising2D.deltaMod_val_eq
  Ising2D.sum_deltaMod_select
  Ising2D.sum_hatY
  Ising2D.sum_expPhase_neg_smul_hatY
  Ising2D.hatCliffordTriple
  Ising2D.lie_H1_hatZ_same
  Ising2D.lie_H1_hatY
  Ising2D.lie_H1_hatZ_opp
  Ising2D.lie_H2_hatZMinus
  Ising2D.lie_H2_hatY
  Ising2D.lie_H2_hatZPlus
  Ising2D.Y_ne_zero
  Ising2D.lie_H1_hatZ_opp_ne_orig
  Ising2D.lie_H2_hatZPlus_ne_orig
  Ising2D.lie_H1Plus_hatZPlus
  Ising2D.lie_H1Minus_hatZMinus
  Ising2D.lie_H1Plus_hatY
  Ising2D.lie_H1Minus_hatY
  "Ising2D.lie_H2_hatZMinus'"
  "Ising2D.lie_H2_hatY'"
  "Ising2D.lie_H2_hatZPlus'"
  Ising2D.NecSuf.sinhc
  Ising2D.NecSuf.sinhc_zero
  Ising2D.NecSuf.sinhc_of_ne_zero
  Ising2D.NecSuf.mul_sinhc
  Ising2D.NecSuf.hasSum_sinhc
  Ising2D.NecSuf.lmulCLM
  Ising2D.NecSuf.rmulCLM
  Ising2D.NecSuf.adCLM
  Ising2D.NecSuf.lmulCLM_apply
  Ising2D.NecSuf.rmulCLM_apply
  Ising2D.NecSuf.adCLM_apply
  Ising2D.NecSuf.commute_lmulCLM_rmulCLM
  Ising2D.NecSuf.lmulCLM_pow
  Ising2D.NecSuf.rmulCLM_pow
  Ising2D.NecSuf.exp_lmulCLM
  Ising2D.NecSuf.exp_rmulCLM
  Ising2D.NecSuf.exp_adCLM_apply
  Ising2D.NecSuf.hasSum_exp_conj
  Ising2D.NecSuf.exp_conj_eq_tsum
  Ising2D.NecSuf.adCLM_sq_z
  Ising2D.NecSuf.adCLM_sq_y
  Ising2D.NecSuf.adCLM_pow_even
  Ising2D.NecSuf.adCLM_pow_odd_z
  Ising2D.NecSuf.adCLM_pow_odd_y
  Ising2D.NecSuf.exp_conj_two_dim_z
  Ising2D.NecSuf.exp_conj_two_dim_y
  Ising2D.adPow
  Ising2D.adPow_zero
  Ising2D.adPow_succ
  Ising2D.adPow_eq_adCLM
  Ising2D.hasSum_matExp_conj
  Ising2D.matExp_conj_eq_tsum
  Ising2D.matExpUnits_conj_eq_tsum
  Ising2D.matExp_conj_two_dim_z
  Ising2D.matExp_conj_two_dim_y
  Ising2D.NecSuf.conj_smul_eq
  Ising2D.NecSuf.twoDimConjMat
  Ising2D.NecSuf.exp_conj_two_dim_actsBy
  Ising2D.expPhase_eq_exp_neg_thetaMu
  Ising2D.expPhase_neg_eq_exp_thetaMu
  Ising2D.B1mat_eq_twoDimConjMat
  Ising2D.B2mat_eq_twoDimConjMat
  Ising2D.actsBy_TConj_matExpUnits
  Ising2D.actsBy_TConj_smulUnits
  Ising2D.ad_V1half_hatZMinus
  Ising2D.ad_V1half_hatY
  Ising2D.actsBy_TConj_V1half
  Ising2D.ad_V2_hatZMinus
  Ising2D.ad_V2_hatY
  Ising2D.actsBy_TConj_V2
  Ising2D.TV_hatZ_hatY
  Ising2D.TV_psiDag
  Ising2D.TV_psi
  Ising2D.TV_psiDag_psi
  Ising2D.NecSuf.acomm_sum_smul_clifford_left
  Ising2D.NecSuf.linearIndependent_of_clifford_necSuf
  Ising2D.smul_one_faithful_tensorPow
  Ising2D.ZY_linearIndependent_of_necSuf
  Ising2D.NecSuf.sum_zpow_primitiveRoot
  Ising2D.zetaM
  Ising2D.isPrimitiveRoot_zetaM
  Ising2D.zetaM_ne_zero
  Ising2D.expPhase_eq_zetaM_zpow
  Ising2D.expPhase_eq_zetaM_zpow_neg
  Ising2D.expPhase_sum_of_necSuf
  Ising2D.NecSuf.acomm_sum_smul_clifford_necSuf
  Ising2D.NecSuf.acomm_fourier_clifford_weights
  Ising2D.NecSuf.acomm_fourier_clifford
  Ising2D.NecSuf.acomm_fourier_clifford_flip
  Ising2D.hatZ_eq_weighted_zetaM
  Ising2D.hatY_eq_weighted_zetaM
  Ising2D.deltaMod_eq_ite_neg
  Ising2D.acomm_hatZ_hatZ_same_of_necSuf
  Ising2D.acomm_hatY_hatY_of_necSuf
  Ising2D.acomm_hatZPlus_hatZMinus_of_necSuf
  Ising2D.NecSuf.acomm_of_single_site
  Ising2D.NecSuf.sq_eq_one_of_site_sq_eq_one
  Ising2D.NecSuf.jwStr
  Ising2D.NecSuf.acomm_jwStr
  Ising2D.NecSuf.jwStr_sq
  Ising2D.siteProd_isSiteProd
  Ising2D.jwFamily_eq_jwStr
  Ising2D.jw_anticomm_of_necSuf
  Ising2D.jw_sq_of_necSuf
  Ising2D.anticomm_Z_Z_of_necSuf
  Ising2D.anticomm_Z_Y_of_necSuf
  Ising2D.anticomm_Y_Y_of_necSuf
  Ising2D.NecSuf.fin_dvd_sub_iff_eq
  Ising2D.NecSuf.zpow_mul_add_natCast
  Ising2D.NecSuf.transform_periodic
  Ising2D.NecSuf.inverse_dft_necSuf
  Ising2D.expPhase_eq_zetaM_zpow_freq
  Ising2D.hatZ_periodic_of_necSuf
  Ising2D.hatY_periodic_of_necSuf
  Ising2D.hatZMinus_M_eq_neg_M_of_necSuf
  Ising2D.hatY_M_eq_neg_M_of_necSuf
  Ising2D.inverse_dft_of_necSuf
  Ising2D.recover_Y_of_necSuf
  Ising2D.recover_Z_of_necSuf
  Ising2D.configBasisIso
  Ising2D.sgn_configBasisIso
  Ising2D.NecSuf.prod_entry_eq_zero_of_ne
  Ising2D.siteProd_diagonal
  Ising2D.sigmaZ_eq_diagonal
  Ising2D.sigmaZ_mulVec_basisVec
  Ising2D.sigmaZ_mulVec_basisVec_spin
  Ising2D.NecSuf.map_exp_of_continuous
  Ising2D.exp_pi_apply
  Ising2D.matrixExp_diagonal
  Ising2D.matrixExp_diagonal_apply
  Ising2D.V1pauli_eq_diagonal
  Ising2D.V1pauli_eq_V1comp
  Ising2D.V1_component_equals_pauli
  Ising2D.exp_smul_pauliX
  Ising2D.exp_smul_pauliX_eq_cosh_add_sinh
  Ising2D.exp_neg_Kstar
  Ising2D.exp_Kstar
  Ising2D.sqrt_two_s2_mul_cosh_Kstar
  Ising2D.sqrt_two_s2_mul_sinh_Kstar
  Ising2D.two_by_two_transfer_identity
  Ising2D.exp_smul_sum_sigmaX
  Ising2D.V2_eq_V2pauli
  Ising2D.V2comp_eq_siteProd_twoByTwo
  Ising2D.V2pauli_eq_V2comp
  Ising2D.V2_component_equals_pauli
  Ising2D.NecSuf.openW_snoc
  Ising2D.NecSuf.pow_succ_apply_eq_sum
  Ising2D.NecSuf.trace_pow_succ
  Ising2D.partitionFunction_eq_conf
  Ising2D.partitionFunctionC_eq_trace
  Ising2D.partition_function_in_pauli_form
  Ising2D.partition_function_in_pauli_form_V2
  Ising2D.NecSuf.invProj_sq
  Ising2D.NecSuf.invProj_mul_invProj_neg
  Ising2D.NecSuf.invProj_add_invProj_neg
  Ising2D.NecSuf.commute_invProj
  Ising2D.NecSuf.pow_mul_proj
  Ising2D.NecSuf.mul_pow_conj_left
  Ising2D.epsProj_sq
  Ising2D.epsProj_mul_epsProj_neg
  Ising2D.epsProj_add_epsProj_neg
  Ising2D.epsProj_mulVec_mem
  Ising2D.epsProj_mulVec_eq_self
  Ising2D.epsilon_commute_sigmaX
  Ising2D.epsilon_anticomm_sigmaZ
  Ising2D.epsilon_anticomm_sigmaY
  Ising2D.epsilon_commute_V1pauli
  Ising2D.epsilon_commute_V2pauli
  Ising2D.epsilon_commute_V1
  Ising2D.epsilon_commute_V1half
  Ising2D.commute_epsProj_of_commute_epsilon
  Ising2D.sector_replacement_of_V1
  Ising2D.sector_replacement_pow
  Ising2D.trace_eq_sector_sum
  Ising2D.trace_epsProj_sym_pow
  Ising2D.trace_epsProj_sym_pow_eq_plain
  Ising2D.partition_function_sector_decomposition
  Ising2D.NecSuf.continuous_arcosh_comp
  Ising2D.NecSuf.cosh_sub_le_cosh_mul_cosh_sub
  Ising2D.NecSuf.one_le_cosh_mul_cosh_sub
  Ising2D.NecSuf.abs_integral_sub_riemann_sum_le
  Ising2D.NecSuf.abs_integral_sub_riemann_sum_le_modulus
  Ising2D.NecSuf.tendsto_modulus_atTop
  Ising2D.NecSuf.tendsto_riemann_sum
  Ising2D.NecSuf.abs_log_div_sub_log_le_of_sandwich
  Ising2D.NecSuf.log_rpow_mul_exp
  Ising2D.NecSuf.tendsto_affine
  Ising2D.gamma1_lower_bound_all_theta
  Ising2D.gamma1R_ge_cosh_sub
  Ising2D.one_le_gamma1R
  Ising2D.gammaFn_nonneg
  Ising2D.cosh_gammaFn
  Ising2D.gamma_is_continuous
  Ising2D.gammaFn_periodic
  Ising2D.abs_log_Z_sub_log_c_le
  Ising2D.limit_of_log_Z_in_N_row
  Ising2D.riemann_sum_to_integral_error
  Ising2D.riemann_sum_to_integral
  Ising2D.riemann_sum_to_integral_indep_delta
  Ising2D.log_LambdaM
  Ising2D.inv_M_log_LambdaM
  Ising2D.onsager_free_energy_expression
  Ising2D.onsager_free_energy_expression_indep_delta
  Ising2D.NecSuf.bilin_quadratic_expand
  Ising2D.NecSuf.psd_cauchy_schwarz
  Ising2D.NecSuf.IsPsdPair.cs_ip
  Ising2D.NecSuf.IsPsdPair.cs_W
  Ising2D.NecSuf.IsPsdPair.rayleigh_bounds_operator_norm
  Ising2D.NecSuf.IsPsdPair.rayleigh_bounds_operator_norm_pow
  Ising2D.NecSuf.IsPsdPair.moment_split
  Ising2D.NecSuf.IsPsdPair.moment_nonneg
  Ising2D.NecSuf.IsPsdPair.moment_le_pow
  Ising2D.NecSuf.IsPsdPair.moment_log_convex
  Ising2D.NecSuf.IsPdPair.W_ker
  Ising2D.NecSuf.IsPdPair.pow_ne_zero_of_ne_zero
  Ising2D.NecSuf.IsPdPair.moment_pos
  Ising2D.NecSuf.IsPdPair.moment_ratio_le
  Ising2D.NecSuf.IsPdPair.moment_pow_le
  Ising2D.matBilin
  Ising2D.matBilin_apply
  Ising2D.matBilin_one_apply
  Ising2D.dotProduct_mulVec_comm
  Ising2D.mulVec_dotProduct_selfadjoint
  Ising2D.single_dotProduct_mulVec_single
  Ising2D.vecNormSq
  Ising2D.vecNorm
  Ising2D.vecNormSq_eq_sum
  Ising2D.vecNormSq_nonneg
  Ising2D.vecNormSq_eq_zero_iff
  Ising2D.vecNormSq_pos
  Ising2D.vecNormSq_smul
  Ising2D.vecNormSq_single
  Ising2D.vecNorm_nonneg
  Ising2D.vecNorm_sq
  Ising2D.mulVecLin_pow
  Ising2D.mulVecLin_pow_apply
  Ising2D.isPsdPair_of_matrix
  Ising2D.isPdPair_of_matrix
  Ising2D.psd_cauchy_schwarz
  Ising2D.psd_diag_nonneg
  Ising2D.psd_abs_entry_le
  Ising2D.psd_quad_le_normSq_mul_trace
  Ising2D.quad_smul
  Ising2D.rayleighSet
  Ising2D.rayleighSup
  Ising2D.rayleighSet_nonempty
  Ising2D.rayleighSet_bddAbove
  Ising2D.le_rayleighSup
  Ising2D.quad_le_rayleighSup_mul
  Ising2D.rayleighSup_nonneg
  Ising2D.rayleighSup_pos
  Ising2D.matBilin_one_mulVecLin_pow
  Ising2D.psd_of_pd
  Ising2D.necSuf_rayleigh_hyp
  Ising2D.rayleigh_bounds_operator_normSq
  Ising2D.rayleigh_bounds_operator_normSq_pow
  Ising2D.rayleigh_bounds_operator_norm
  Ising2D.rayleigh_bounds_operator_norm_pow
  Ising2D.IsSymm_pow
  Ising2D.psd_pow
  Ising2D.trace_pow_le
  Ising2D.quad_pow_le_trace_pow
  Ising2D.rayleighSup_pow_le_trace_pow
  Ising2D.trace_power_sandwich
  Ising2D.symTransfer
  Ising2D.symTransfer_pow_succ
  Ising2D.mul_pow_mul_eq
  Ising2D.trace_symTransfer_pow
  Ising2D.physicalV1halfC_eq_map
  Ising2D.physicalV2C_eq_map
  Ising2D.physicalSymTransferC_eq_map
  Ising2D.NecSuf.sandwich_mul_proj_eq
  Ising2D.physicalSymTransferR_map_mul_epsProj_eq_Vsym
  Ising2D.symTransfer_isSymm
  Ising2D.mulVec_eq_zero_iff_of_isUnit
  Ising2D.symTransfer_posDef
  Ising2D.symTransfer_entry_pos
  Ising2D.diagExp
  Ising2D.diagExp_isSymm
  Ising2D.diagExp_entry_pos
  Ising2D.diagExp_mul_self
  Ising2D.diagExp_isUnit
  Ising2D.diagExp_posDef
  Ising2D.matExp_isSymm
  Ising2D.matExp_posDef
  Ising2D.partition_function_sandwich
  Ising2D.sectorSet
  Ising2D.sectorRayleighSup
  Ising2D.sector_invariant
  Ising2D.sector_orthogonal
  Ising2D.sector_smul
  Ising2D.sectorSet_subset
  Ising2D.sectorSet_bddAbove
  Ising2D.sectorRayleighSup_le
  Ising2D.sector_quad_le
  Ising2D.projPlus
  Ising2D.projMinus
  Ising2D.proj_add_eq_one
  Ising2D.projPlus_mulVec_eigen
  Ising2D.projMinus_mulVec_eigen
  Ising2D.sector_decomposition_of_rayleigh_sup
  # --- 009 章（転送行列 V の固有値）---
  Ising2D.NecSuf.num_mul_num
  Ising2D.NecSuf.ann_mul_cre
  Ising2D.NecSuf.commute_cre_num
  Ising2D.NecSuf.commute_ann_num
  Ising2D.NecSuf.commute_num_num
  Ising2D.NecSuf.tau_num_mul_add_self
  Ising2D.NecSuf.projOn_mul_self
  Ising2D.NecSuf.projOn_mul_projOn_of_ne
  Ising2D.NecSuf.sum_projOn
  Ising2D.NecSuf.num_mul_projOn
  Ising2D.NecSuf.two_pow_smul_tau_projOn
  Ising2D.NecSuf.pow_mul_eq_of_mul_eq_smul
  Ising2D.NecSuf.exp_mul_eq_of_mul_eq_smul
  Ising2D.trace_eq_sum_diag
  Ising2D.trace_linear
  Ising2D.trace_cyclic
  Ising2D.trace_one_eq_card
  Ising2D.trace_conj
  Ising2D.trace_of_idempotent
  Ising2D.isCompl_range_ker_of_idempotent
  Ising2D.trace_one_tensorPow
  Ising2D.tensorPow_two_torsion_free
  Ising2D.FermiSetup.acomm_cre_cre
  Ising2D.FermiSetup.acomm_ann_ann
  Ising2D.FermiSetup.acomm_cre_ann
  Ising2D.FermiSetup.cre_sq
  Ising2D.FermiSetup.ann_sq
  Ising2D.FermiSetup.ann_mul_cre
  Ising2D.FermiSetup.nOp_mul_self
  Ising2D.FermiSetup.commute_cre_nOp
  Ising2D.FermiSetup.commute_ann_nOp
  Ising2D.FermiSetup.commute_nOp_nOp
  Ising2D.FermiSetup.Qproj_mul_self
  Ising2D.FermiSetup.Qproj_mul_Qproj_of_ne
  Ising2D.FermiSetup.sum_Qproj
  Ising2D.FermiSetup.nOp_mul_Qproj
  Ising2D.FermiSetup.two_pow_mul_trace_Qproj
  Ising2D.FermiSetup.card_I_le
  Ising2D.FermiSetup.trace_Qproj
  Ising2D.FermiSetup.finrank_range_Qproj
  Ising2D.FermiSetup.sum_Qproj_mulVec
  Ising2D.FermiSetup.eq_zero_of_sum_eq_zero
  Ising2D.FermiSetup.Xop_mul_Qproj
  Ising2D.FermiSetup.Vprime_mul_Qproj
  Ising2D.FermiSetup.Vprime_mulVec_of_mem_range
  Ising2D.FermiSetup.Vprime_mul_Vprime_neg
  Ising2D.FermiSetup.Vprime_neg_mul_Vprime
  Ising2D.FermiSetup.sum_exp_gval
  Ising2D.FermiSetup.trace_Vprime
  Ising2D.FermiSetup.trace_Vprime_inv
  Ising2D.FermiSetup.trace_Vprime_pos
  Ising2D.Z_transpose
  Ising2D.Z_conjTranspose
  Ising2D.Y_transpose
  Ising2D.Y_conjTranspose
  Ising2D.S1_isHermitian
  Ising2D.S1_transpose
  Ising2D.S2_isHermitian
  Ising2D.S2_transpose
  Ising2D.entries_real_of_isHermitian_of_transpose
  Ising2D.posDef_smul_of_pos
  Ising2D.posDef_exp_of_isHermitian
  Ising2D.Vmat_posDef
  Ising2D.trace_Vmat_pos
  Ising2D.Uflip_mul_inv
  Ising2D.UflipInv_mul
  Ising2D.Uflip_conj_Z
  Ising2D.Uflip_conj_Y
  Ising2D.Uflip_conj_H1
  Ising2D.Uflip_conj_H2
  Ising2D.Uflip_conj_S1
  Ising2D.Uflip_conj_S2
  Ising2D.Uflip_conj_matExp
  Ising2D.VmatInv_mul_Vmat
  Ising2D.Vmat_mul_VmatInv
  Ising2D.trace_Vmat
  Ising2D.trace_exp_neg_eq_tau
  Ising2D.trace_VmatInv
  Ising2D.constant_c_value
  Ising2D.Vmat_mul_Qproj
  Ising2D.bigLambda_pos
  Ising2D.bigLambda_le_max
  Ising2D.bigLambda_min_le
  Ising2D.bigLambda_max_mul_min
  Ising2D.NecSuf.pow_half_eq_neg_one
  Ising2D.NecSuf.sq_isPrimitiveRoot
  Ising2D.NecSuf.zpow_mul_natCast
  Ising2D.NecSuf.sum_zpow_primitiveRoot_zero_based
  Ising2D.NecSuf.sum_zpow_antiperiodic
  Ising2D.NecSuf.inverse_dft_antiperiodic
  Ising2D.NecSuf.acomm_antiperiodic_fourier_clifford
  Ising2D.lie_H2_hatZMinus_eq
  Ising2D.lie_H2_hatZPlus_eq
  Ising2D.lie_H2_hatZPlus_ne_lie_H2_hatZMinus
  Ising2D.lie_H2_hatZPlus_ne_hatZMinus
  Ising2D.expPhase_zpow
  Ising2D.expPhase_two_mul
  Ising2D.expPhase_two_mul_half
  Ising2D.checkPhase_eq_exp
  Ising2D.checkPhase_M
  Ising2D.checkPhase_period
  Ising2D.expPhase_sum_zero_based
  Ising2D.antiperiodic_exp_sum
  Ising2D.sum_checkPhase
  Ising2D.antiperiodic_exp_sum_dvd
  Ising2D.antiperiodic_exp_sum_not_dvd
  Ising2D.checkZ
  Ising2D.checkY
  Ising2D.checkPhase_antiperiodic
  Ising2D.checkZ_period
  Ising2D.checkY_period
  Ising2D.checkPhase_congr
  Ising2D.thetaTilde_one_sub
  Ising2D.checkPhase_one_sub
  Ising2D.thetaTilde_ne
  Ising2D.thetaTilde_pos
  Ising2D.thetaTilde_lt_two_pi
  Ising2D.checkIndex_conj
  Ising2D.conj_index_self_iff
  Ising2D.thetaTilde_of_self_conj
  Ising2D.dvd_add_sub_one_iff
  Ising2D.deltaMod_add_one_eq
  Ising2D.thetaTilde_conj
  Ising2D.checkPhase_conj
  Ising2D.checkZ_conj
  Ising2D.checkY_conj
  Ising2D.acomm_checkZ_checkZ
  Ising2D.acomm_checkY_checkY
  Ising2D.acomm_checkZ_checkY
  Ising2D.acomm_checkZ_checkZ_of_mem
  Ising2D.acomm_checkY_checkY_of_mem
  Ising2D.expPhase_nextSite
  Ising2D.H2_eq_check_sum
  Ising2D.H1Plus_eq_check_sum
  Ising2D.lie_H1Plus_checkZ
  Ising2D.lie_H1Plus_checkY
  Ising2D.lie_H2_checkZ
  Ising2D.lie_H2_checkY
  Ising2D.inverse_dft_check
  Ising2D.recover_checkZ
  Ising2D.recover_checkY
  Ising2D.Z_eq_inverse_dft_check
  Ising2D.Y_eq_inverse_dft_check
  Ising2D.checkZ_checkY_generate_algebra
  Ising2D.isPrimitiveRoot_expPhase_one
  Ising2D.isPrimitiveRoot_expPhase_neg_one
  Ising2D.antiperiodic_exp_sum_of_necSuf
  Ising2D.checkPhase_M_of_necSuf
  Ising2D.checkZ_period_of_necSuf
  Ising2D.checkY_period_of_necSuf
  Ising2D.acomm_checkZ_checkZ_of_necSuf
  Ising2D.acomm_checkY_checkY_of_necSuf
  Ising2D.inverse_dft_check_of_necSuf
  Ising2D.recover_checkZ_of_necSuf
  Ising2D.recover_checkY_of_necSuf
  Ising2D.NecSuf.permMat_mulVec
  Ising2D.NecSuf.permMat_mulVec_single
  Ising2D.NecSuf.permMat_isSymm
  Ising2D.NecSuf.permMat_mul_self
  Ising2D.NecSuf.permMat_mulVec_absVec
  Ising2D.NecSuf.vecNormSq_absVec
  Ising2D.NecSuf.abs_quad_le_quad_absVec
  Ising2D.NecSuf.quad_le_quad_absVec
  Ising2D.NecSuf.sectorSet_pos_nonempty
  Ising2D.NecSuf.sectorSet_neg_nonempty
  Ising2D.NecSuf.sectorRayleighSup_neg_le_pos
  Ising2D.NecSuf.rayleighSup_eq_sectorRayleighSup_pos
  Ising2D.flipConf_involutive
  Ising2D.flipConf_ne_self
  Ising2D.epsilon_apply
  Ising2D.epsilon_eq_ofReal_epsilonR
  Ising2D.epsilon_mulVec_basisVec
  Ising2D.epsilonR_entry_zero_or_one
  Ising2D.epsilonR_row_sum
  Ising2D.epsilonR_col_sum
  Ising2D.epsilonR_mulVec_apply
  Ising2D.epsilonR_mulVec_single
  Ising2D.epsilonR_mulVec_oddUnit
  Ising2D.vecNormSq_oddUnit
  Ising2D.sectorSet_neg_nonempty_epsilonR
  Ising2D.epsilonR_mulVec_absVec
  Ising2D.vecNormSq_absVec_eq
  Ising2D.quad_le_quad_absVec_epsilonR
  Ising2D.exists_even_sector_unit_ge
  Ising2D.quad_le_sectorRayleighSup_pos
  Ising2D.c_minus_le_c_plus
  Ising2D.c_minus_le_c_plus_symTransfer
  Ising2D.c_equals_c_plus
  Ising2D.c_equals_c_plus_symTransfer
  Ising2D.rayleighSup_eq_of_sectorRayleighSup_pos_eq
  Ising2D.rayleighSup_attained_in_even_sector
  Ising2D.rayleighSup_mem_rayleighSet
  Ising2D.NecSuf.lie_creAnn_cre
  Ising2D.NecSuf.lie_creAnn_ann
  Ising2D.NecSuf.lie_carHam_cre
  Ising2D.NecSuf.lie_carHam_ann
  Ising2D.NecSuf.exp_conj_of_ad_eigen
  Ising2D.NecSuf.exp_conj_of_lie_eigen
  Ising2D.gamma1_add_int_mul_two_pi
  Ising2D.thetaTilde_add_int_mul
  Ising2D.gamma1_thetaTilde_conj
  Ising2D.gamma2_thetaTilde_conj
  Ising2D.gamma2_neg_thetaTilde_conj
  Ising2D.checkR_sq
  Ising2D.checkR_conj
  Ising2D.checkPsiDag_eq
  Ising2D.checkPsi_eq
  Ising2D.checkPsi_car
  Ising2D.acomm_checkPsiDag_checkPsiDag
  Ising2D.acomm_checkPsiDag_checkPsi
  Ising2D.acomm_checkPsi_checkPsi
  Ising2D.AMat_mulVec_checkPsiDag_coeff
  Ising2D.AMat_mulVec_checkPsi_coeff
  Ising2D.TVPlus_checkPsiDag_of_action
  Ising2D.TVPlus_checkPsi_of_action
  Ising2D.TVPlus_checkPsiDag_psi_of_action
  Ising2D.checkIdx_rev
  Ising2D.isUnit_checkVprime
  Ising2D.matExp_conj_eigen
  Ising2D.lie_checkX_checkPsiDag
  Ising2D.lie_checkX_checkPsi
  Ising2D.TCheckVprime_checkPsiDag
  Ising2D.TCheckVprime_checkPsi
  Ising2D.eq_on_checkZY_of_eq_on_checkPsi
  Ising2D.TVPlus_eq_TCheckVprime_on_checkZY
  Ising2D.TConj_eq_of_eq_on_checkZY
  Ising2D.TVPlus_eq_TCheckVprime
  Ising2D.exists_smul_of_TConj_eq
  Ising2D.VPlus_eq_smul_checkVprime
  Ising2D.VPlus
  Ising2D.isUnit_VPlus
  Ising2D.V1halfPlus_sq
  Ising2D.TVPlus_eq_TConj
  Ising2D.nesting_H1Plus_checkZ_even
  Ising2D.nesting_H1Plus_checkZ_odd
  Ising2D.nesting_H1Plus_checkY_even
  Ising2D.nesting_H1Plus_checkY_odd
  Ising2D.nesting_H2_checkZ_even
  Ising2D.nesting_H2_checkZ_odd
  Ising2D.nesting_H2_checkY_even
  Ising2D.nesting_H2_checkY_odd
  Ising2D.conversion_H1Plus_checkZ_even
  Ising2D.conversion_H1Plus_checkZ_odd
  Ising2D.conversion_H1Plus_checkY_even
  Ising2D.conversion_H1Plus_checkY_odd
  Ising2D.conversion_H2_checkZ_even
  Ising2D.conversion_H2_checkZ_odd
  Ising2D.conversion_H2_checkY_even
  Ising2D.conversion_H2_checkY_odd
  Ising2D.extract_taylor_H1Plus_checkZ
  Ising2D.extract_taylor_H1Plus_checkY
  Ising2D.extract_taylor_H2_checkZ
  Ising2D.extract_taylor_H2_checkY
  Ising2D.TConj_V1halfPlus_checkZ
  Ising2D.TConj_V1halfPlus_checkY
  Ising2D.TConj_V2_checkZ
  Ising2D.TConj_V2_checkY
  Ising2D.linearity_of_T_on_check
  Ising2D.actsBy_TConj_V1halfPlus
  Ising2D.actsBy_TConj_V2_check
  Ising2D.factorization_of_A_theta_general
  Ising2D.factorization_of_A_thetaTilde
  Ising2D.NecSuf.actsBy_sandwich
  Ising2D.NecSuf.actsBy_TV_sandwich
  Ising2D.TVPlus_checkZ_checkY
  Ising2D.TVPlus_checkZ_checkY_components
  Ising2D.TV_hatZ_hatY_via_sandwich
  Ising2D.NecSuf.cos_eq_neg_one_of_sin_eq_zero_of_odd
  Ising2D.NecSuf.mul_of_eq_neg_conj
  Ising2D.NecSuf.sq_absOf_eq_neg_mul
  Ising2D.NecSuf.sq_I_mul_absOf_eq_mul
  Ising2D.NecSuf.skew2_charPoly_factor
  Ising2D.NecSuf.skew2_mulVec
  Ising2D.NecSuf.eq_conj_of_mul_eq
  Ising2D.NecSuf.gamma_det_identity
  Ising2D.NecSuf.sinh_arcosh_of_sq
  Ising2D.NecSuf.exp_arcosh_of_sq
  Ising2D.NecSuf.exp_neg_arcosh_of_sq
  Ising2D.AMat_thetaTilde_eq
  Ising2D.thetaTilde_mul_M
  Ising2D.gamma2_thetaTilde_ne_zero
  Ising2D.cos_thetaTilde_eq_neg_one_of_sin_eq_zero
  Ising2D.gamma2_neg_thetaTilde_ne_zero
  Ising2D.gamma2_thetaTilde_ne_zero_checkIndex
  Ising2D.gamma2_neg_thetaTilde_eq
  Ising2D.gamma2_mul_gamma2_neg_eq_neg_absSq
  Ising2D.sq_absGamma2
  Ising2D.sq_I_absGamma2
  Ising2D.absGamma2_thetaTilde_pos
  Ising2D.charPoly_factor_thetaTilde
  Ising2D.AMat_mulVec_eigen_pos
  Ising2D.AMat_mulVec_eigen_neg
  Ising2D.lambdaPlusR_ne_lambdaMinusR
  Ising2D.checkPmat_eq_Pmat
  Ising2D.checkDmat_eq_Dmat
  Ising2D.checkT_sq
  Ising2D.det_checkPmat
  Ising2D.det_checkPmat_ne_zero
  Ising2D.AMat_mul_checkPmat
  Ising2D.AMat_thetaTilde_eq_checkPmat_mul_checkDmat_mul_inv
  Ising2D.det_AMat_thetaTilde_eq_one
  Ising2D.det_AMat_thetaTilde_eq_one_of_necSuf
  Ising2D.gamma1R_sq_thetaTilde
  Ising2D.lambda_mul_lambda_thetaTilde
  Ising2D.one_lt_gamma1R_thetaTilde
  Ising2D.cosh_gammaTilde
  Ising2D.gammaTilde_pos
  Ising2D.sinh_gammaTilde
  Ising2D.lambdaPlusR_eq_exp
  Ising2D.lambdaMinusR_eq_exp
  Ising2D.lambda_separation
  # --- 020 章（臨界点での比熱の対数発散）---
  Ising2D.NecSuf.sinh_le_mul_cosh
  Ising2D.NecSuf.exp_le_inv_one_sub
  Ising2D.NecSuf.cosh_le_inv_one_sub_sq_div_two
  Ising2D.NecSuf.one_add_sq_div_two_le_cosh
  Ising2D.NecSuf.log_one_add_le
  Ising2D.NecSuf.log_le_div_exp_one
  Ising2D.NecSuf.mul_log_inv_le
  Ising2D.NecSuf.log_two_mul_le_arsinh
  Ising2D.NecSuf.arsinh_le_log_two_mul_add
  Ising2D.NecSuf.abs_sub_bounds_of_deriv_bounds
  Ising2D.NecSuf.abs_sub_le_of_abs_deriv_le
  Ising2D.NecSuf.sqrt_quad_pos
  Ising2D.NecSuf.le_sqrt_quad
  Ising2D.NecSuf.hasDerivAt_quad
  Ising2D.NecSuf.integral_inv_sqrt_quad
  Ising2D.NecSuf.integral_inv_pow_three_half
  Ising2D.NecSuf.integral_inv_pow_three_half_le
  Ising2D.NecSuf.inv_sqrt_diff_bound
  Ising2D.NecSuf.hasDerivAt_integral_of_continuousOn
  Ising2D.cosh_add_formula
  Ising2D.cosh_sub_formula
  Ising2D.sinh_add_formula
  Ising2D.sinh_sub_formula
  Ising2D.cosh_eq_one_add_two_sinh_half_sq
  Ising2D.sinh_eq_two_sinh_half_mul_cosh_half
  Ising2D.sinh_strictMono
  Ising2D.sinh_injective_real
  Ising2D.arsinh_eq_log_form
  Ising2D.sinh_arsinh_eq
  Ising2D.sinh_eq_iff_eq_arsinh
  Ising2D.hasDerivAt_arsinh_form
  Ising2D.self_le_sinh_of_nonneg
  Ising2D.sinh_le_mul_cosh_of_nonneg
  Ising2D.cosh_addition_and_half_angle_five
  Ising2D.kappaP
  Ising2D.AP
  Ising2D.AP_pos
  Ising2D.one_sub_cos_eq
  Ising2D.gamma1R_eq_cosh_kappa_add
  Ising2D.Sparam
  Ising2D.Sparam_nonneg
  Ising2D.sinh_half_gammaFn_sq
  Ising2D.gammaFn_eq_two_arsinh
  Ising2D.Sparam_even
  Ising2D.KStar
  Ising2D.sinh_two_KStar
  Ising2D.sinh_two_mul_sinh_two_KStar
  Ising2D.KStar_pos
  Ising2D.critical_point_iff_kappa_zero
  Ising2D.isoParam
  Ising2D.AP_isoParam
  Ising2D.kappaK
  Ising2D.kappaP_isoParam
  Ising2D.gammaFn_isoParam
  Ising2D.sqrt_two_bounds
  Ising2D.cosh_02_bounds
  Ising2D.sinh_02_bounds
  Ising2D.Kc
  Ising2D.sinh_two_Kc
  Ising2D.cosh_two_Kc
  Ising2D.Kc_gt_tenth
  Ising2D.Kc_pos
  Ising2D.kappaDeriv
  Ising2D.kappaSecond
  Ising2D.kappaK_eq
  Ising2D.hasDerivAt_kappaK
  Ising2D.hasDerivAt_kappaDeriv
  Ising2D.kappaK_Kc
  Ising2D.kappaK_eq_zero_iff
  Ising2D.Dnbhd
  Ising2D.Dnbhd_convex
  Ising2D.pos_of_mem_Dnbhd
  Ising2D.sinh_two_K_bounds
  Ising2D.kappaDeriv_bounds
  Ising2D.abs_kappaSecond_le
  Ising2D.interior_Dnbhd
  Ising2D.mem_Dnbhd_of_mem_interior
  Ising2D.Kc_mem_Dnbhd
  Ising2D.deriv_kappaK_on
  Ising2D.continuousOn_kappaK
  Ising2D.differentiableOn_kappaK
  Ising2D.abs_kappaK_bounds
  Ising2D.kappaDerivSq
  Ising2D.hasDerivAt_kappaDerivSq
  Ising2D.kappaDerivSq_Kc
  Ising2D.abs_deriv_kappaDerivSq_le
  Ising2D.continuousOn_kappaDerivSq
  Ising2D.differentiableOn_kappaDerivSq
  Ising2D.abs_kappaDerivSq_sub_le
  Ising2D.Sfun
  Ising2D.Qfun
  Ising2D.gammaK
  Ising2D.dgammaK
  Ising2D.d2gammaK
  Ising2D.Sfun_nonneg
  Ising2D.Sfun_pos_of_ne_zero
  Ising2D.Qfun_pos_of_ne_zero
  Ising2D.sqrt_Qfun_pos
  Ising2D.gammaK_nonneg
  Ising2D.sinh_half_gammaK
  Ising2D.cosh_half_gammaK
  Ising2D.sinh_gammaK
  Ising2D.cosh_gammaK
  Ising2D.hasDerivAt_Sfun
  Ising2D.hasDerivAt_Qfun
  Ising2D.hasDerivAt_gammaK
  Ising2D.dgammaK_eq_sinh_div_sinh
  Ising2D.hasDerivAt_dgammaK
  Ising2D.d2gammaK_eq
  Ising2D.sinh_sq_div_four_le_Qfun
  Ising2D.abs_dgammaK_le_one
  Ising2D.continuous_Sfun
  Ising2D.continuous_Qfun
  Ising2D.continuous_gammaK
  Ising2D.continuousOn_dgammaK
  Ising2D.continuousOn_d2gammaK
  Ising2D.continuous_Sfun_fixed
  Ising2D.continuous_Qfun_fixed
  Ising2D.continuous_sqrtQfun_fixed
  Ising2D.continuous_gammaK_fixed
  Ising2D.continuous_dgammaK_fixed
  Ising2D.continuous_d2gammaK_fixed
  Ising2D.c0
  Ising2D.c0_bounds
  Ising2D.c0_pos
  Ising2D.c0_le_one
  Ising2D.elementary_sine_bounds_cube
  Ising2D.elementary_sine_bounds_linear
  Ising2D.integral_inv_sqrt_pi
  Ising2D.arsinh_log_bounds
  Ising2D.integral_inv_sqrt_pi_bounds
  Ising2D.integral_inv_pow_three_half_pi
  Ising2D.Bconst
  Ising2D.Bconst_le
  Ising2D.Bconst_nonneg
  Ising2D.continuous_sineIntegrand
  Ising2D.continuous_quadIntegrand
  Ising2D.sine_integral_two_sided
  Ising2D.Gfun
  Ising2D.Gfirst
  Ising2D.Gsecond
  Ising2D.isOpen_ne_zero
  Ising2D.hasDerivAt_Gfun
  Ising2D.hasDerivAt_Gfirst
  Ising2D.abs_Gfirst_le
  Ising2D.Sfun_two_pi_sub
  Ising2D.d2gammaK_two_pi_sub
  Ising2D.integral_fold
  Ising2D.Jint
  Ising2D.Iint
  Ising2D.Tint
  Ising2D.continuous_Jintegrand
  Ising2D.continuous_Iintegrand
  Ising2D.continuous_Tintegrand
  Ising2D.integral_d2gammaK_eq
  Ising2D.Sfun_le_cosh_sq
  Ising2D.inv_sqrt_diff_S_Q
  Ising2D.abs_Jint_sub_Iint
  Ising2D.coshgamma_div_sinhgamma_cube_le
  Ising2D.inv_pow_three_half_mono
  Ising2D.Tint_le
  Ising2D.two_pi_mul_Gsecond
  Ising2D.step6_bound
  Ising2D.second_derivative_log_divergence_pos
  Ising2D.Sfun_neg
  Ising2D.d2gammaK_neg
  Ising2D.Gsecond_neg
  Ising2D.second_derivative_log_divergence
  Ising2D.Gsecond_ge
  Ising2D.checkR_eq_absGamma2
  Ising2D.checkPsiDag_eq_checkPmat_col
  Ising2D.checkPsi_eq_checkPmat_col
  Ising2D.gamma1R_thetaTilde_conj
  Ising2D.gammaTilde_conj
  Ising2D.gammaTildeC_conj
  Ising2D.gamma2_thetaTilde_ne_zero_of_checkIndex
  Ising2D.gamma1_add_checkR_eq_exp
  Ising2D.gamma1_sub_checkR_eq_exp
  "Ising2D.checkPsi_car'"
  Ising2D.TCheckVprime_checkPsi_pair
  "Ising2D.TVPlus_eq_TCheckVprime'"
  "Ising2D.VPlus_eq_smul_checkVprime'"
  Ising2D.sinh_two_K2_pos
  Ising2D.TVPlus_actsBy_checkZY
  Ising2D.VPlus_eq_smul_checkVprime_of_dual
  # --- 018 章（偶セクターの完結：Onsager の厳密解）---
  Ising2D.NecSuf.anticomm_sum_smul
  Ising2D.NecSuf.commute_parity_num
  Ising2D.NecSuf.commute_parity_projOn
  Ising2D.NecSuf.num_mul_cre
  Ising2D.NecSuf.projOn_insert_mul_cre
  Ising2D.NecSuf.cre_mul_projOn_ne_zero
  Ising2D.NecSuf.noncommProd_mul_of_mul_eq_smul
  Ising2D.NecSuf.star_projOn
  Ising2D.NecSuf.smul_left_cancel_of_ne_zero
  Ising2D.NecSuf.sum_powerset_signed_exp
  Ising2D.CheckFermi
  Ising2D.CheckFermi.nOp
  Ising2D.CheckFermi.nOp_def
  Ising2D.CheckFermi.acomm_cre_ann_self
  Ising2D.CheckFermi.cre_sq
  Ising2D.CheckFermi.ann_sq
  Ising2D.CheckFermi.ann_mul_cre
  Ising2D.CheckFermi.nOp_mul_self
  Ising2D.CheckFermi.commute_cre_nOp
  Ising2D.CheckFermi.commute_ann_nOp
  Ising2D.CheckFermi.commute_nOp_nOp
  Ising2D.CheckFermi.Qproj
  Ising2D.CheckFermi.Qproj_mul_self
  Ising2D.CheckFermi.Qproj_mul_Qproj_of_ne
  Ising2D.CheckFermi.sum_Qproj
  Ising2D.CheckFermi.nOp_mul_Qproj
  Ising2D.CheckFermi.trace_Qproj
  Ising2D.CheckFermi.Qproj_ne_zero
  Ising2D.CheckFermi.epsilon_anticomm_cre
  Ising2D.CheckFermi.epsilon_anticomm_ann
  Ising2D.CheckFermi.commute_epsilon_nOp
  Ising2D.CheckFermi.commute_epsilon_Qproj
  Ising2D.CheckFermi.ann_conjTranspose
  Ising2D.CheckFermi.nOp_conjTranspose
  Ising2D.CheckFermi.Qproj_conjTranspose
  Ising2D.epsilon_anticomm_checkZ
  Ising2D.epsilon_anticomm_checkY
  Ising2D.IsCheckMode
  Ising2D.epsilon_anticomm_of_isCheckMode
  Ising2D.matrix_eq_of_mulVec_eq
  Ising2D.smul_cancel_of_matrix_ne_zero
  Ising2D.CheckFermi.Qproj_eq
  Ising2D.CheckFermi.Qproj_mulVec_of_mem_range
  Ising2D.CheckFermi.finrank_range_Qproj
  Ising2D.CheckFermi.exists_Qproj_generator
  Ising2D.CheckFermi.exists_eta
  Ising2D.CheckFermi.eta
  Ising2D.CheckFermi.eta_mem
  Ising2D.CheckFermi.epsilon_mul_Qproj
  Ising2D.CheckFermi.eta_unique
  Ising2D.CheckFermi.eta_insert
  Ising2D.CheckFermi.eta_univ_eq_aux
  Ising2D.CheckFermi.eta_eq_eta_univ_mul
  Ising2D.CheckFermi.parityFactor
  Ising2D.CheckFermi.commute_parityFactor
  Ising2D.CheckFermi.parityProd
  Ising2D.CheckFermi.parityFactor_mul_Qproj
  Ising2D.CheckFermi.parityProd_mul_Qproj
  Ising2D.CheckFermi.eq_of_mul_Qproj_eq
  Ising2D.CheckFermi.epsilon_eq_parityProd
  Ising2D.checkLambda
  Ising2D.checkLambda_pos
  Ising2D.checkLambda_le_univ
  Ising2D.checkLambda_lt_univ
  Ising2D.VPlusData
  Ising2D.VPlusData.lamMax
  Ising2D.VPlusData.lamMax_pos
  Ising2D.VPlusData.checkLambda_le_lamMax
  Ising2D.VPlusData.epsilon_mul_V_mul_Qproj
  Ising2D.VPlusData.trace_epsilon_mul_V_eq_sum
  Ising2D.VPlusData.traceFactor
  Ising2D.VPlusData.traceFactor_pos
  Ising2D.VPlusData.trace_epsilon_mul_V
  Ising2D.VPlusData.eta_univ_eq_one_of_trace_pos
  Ising2D.expPhase_conj
  Ising2D.checkPhase_conj_star
  Ising2D.checkZ_conjTranspose
  Ising2D.checkY_conjTranspose
  Ising2D.VPlusData.eta_univ_eq_one
  Ising2D.VPlusData.eta_eq_sign
  Ising2D.VPlusData.epsilon_eq_parityProd_of_trace_pos
  Ising2D.VPlusData.epsilon_mul_Qproj_univ
  Ising2D.VPlusData.mem_evenSector_of_mem_range_univ
  Ising2D.cvec
  Ising2D.cvec_ne_zero
  Ising2D.star_cvec
  Ising2D.cvec_mulVec
  Ising2D.cvec_dotProduct
  Ising2D.cvec_smul
  Ising2D.star_dotProduct_self
  Ising2D.EvenSectorBridge
  Ising2D.EvenSectorBridge.quad_Qproj
  Ising2D.EvenSectorBridge.sum_quad_Qproj
  Ising2D.EvenSectorBridge.quad_Vr_eq_sum
  Ising2D.EvenSectorBridge.quad_le_lamMax
  Ising2D.EvenSectorBridge.reVec
  Ising2D.EvenSectorBridge.cvec_reVec_add
  Ising2D.EvenSectorBridge.reVec_eigen
  Ising2D.EvenSectorBridge.exists_real_max_eigenvector
  Ising2D.EvenSectorBridge.c_plus_equals_lamMax
  Ising2D.EvenSectorBridge.exists_maximizer
  Ising2D.EvenSectorBridge.lamMax_eq_LambdaM
  Ising2D.EvenSectorBridge.rayleighSup_eq_LambdaM
  Ising2D.onsager_limit_in_N_row
  Ising2D.onsager_limit_in_M
  Ising2D.onsager_exact_solution
  Ising2D.NecSuf.acomm_cre_ann_comp
  Ising2D.NecSuf.two_pow_smul_tau_noncommProd
  Ising2D.NecSuf.const_eq_of_trace_ratio
  Ising2D.NecSuf.sum_weight_lt_of_ne_univ
  Ising2D.NecSuf.sum_weight_le_univ
  Ising2D.NecSuf.sum_weight_empty_le
  Ising2D.NecSuf.eq_proj_of_eigen
  Ising2D.NecSuf.mul_exp_eq_of_mul_eq_smul
  Ising2D.CheckIdx.card
  Ising2D.conjIdx_involutive
  Ising2D.CheckFermiSetup.acomm_cre_ann
  Ising2D.CheckFermiSetup.cre_sq
  Ising2D.CheckFermiSetup.ann_sq
  Ising2D.CheckFermiSetup.ann_mul_cre
  Ising2D.CheckFermiSetup.nOp_mul_self
  Ising2D.CheckFermiSetup.commute_cre_nOp
  Ising2D.CheckFermiSetup.commute_ann_nOp
  Ising2D.CheckFermiSetup.commute_nOp_nOp
  Ising2D.CheckFermiSetup.trace_nOpProd
  Ising2D.CheckFermiSetup.trace_nOp
  Ising2D.CheckFermiSetup.trace_nOpProd_univ
  Ising2D.CheckFermiSetup.Qproj_mul_self
  Ising2D.CheckFermiSetup.Qproj_mul_Qproj_of_ne
  Ising2D.CheckFermiSetup.sum_Qproj
  Ising2D.CheckFermiSetup.nOp_mul_Qproj
  Ising2D.CheckFermiSetup.trace_Qproj
  Ising2D.CheckFermiSetup.finrank_range_Qproj
  Ising2D.CheckFermiSetup.sum_Qproj_mulVec
  Ising2D.CheckFermiSetup.eq_zero_of_sum_eq_zero
  Ising2D.CheckFermiSetup.Xop_mul_Qproj
  Ising2D.CheckFermiSetup.Qproj_mul_Xop
  Ising2D.CheckFermiSetup.Vprime_mul_Qproj
  Ising2D.CheckFermiSetup.Qproj_mul_Vprime
  Ising2D.CheckFermiSetup.Vprime_mulVec_of_mem_range
  Ising2D.CheckFermiSetup.trace_Vprime
  Ising2D.CheckFermiSetup.trace_Vprime_inv
  Ising2D.CheckFermiSetup.trace_Vprime_pos
  Ising2D.VPlus_posDef
  Ising2D.VPlusInv_posDef
  Ising2D.trace_VPlus_pos
  Ising2D.trace_VPlusInv_pos
  Ising2D.trace_VPlus
  Ising2D.trace_VPlusInv
  Ising2D.VPlusInv_eq
  Ising2D.constant_c_value_even_sector
  Ising2D.VPlus_mul_Qproj
  Ising2D.Qproj_mul_VPlus
  Ising2D.VPlus_mulVec_of_mem_range
  Ising2D.checkBigLambda_pos
  Ising2D.checkBigLambda_le_max
  Ising2D.checkBigLambda_min_le
  Ising2D.checkBigLambda_lt_max
  Ising2D.checkBigLambda_max_mul_min
  Ising2D.cos_thetaTilde_lt_one
  Ising2D.one_lt_gamma1R_thetaTilde_checkIndex
  Ising2D.gammaFn_thetaTilde_pos
  Ising2D.sum_checkIdx
  Ising2D.tagPoint_half_eq_thetaTilde
  Ising2D.checkBigLambda_univ_eq_LambdaM
  Ising2D.checkBigLambda_lt_max_of_gammaFn
  Ising2D.eq_Qproj_univ_mulVec_of_eigen
  Ising2D.finrank_range_Qproj_univ
  Ising2D.VPlus_eq_Vmat
  Ising2D.star_checkQ
  Ising2D.star_two_mul_sqrtM
  Ising2D.star_checkP
  Ising2D.checkPsiDag_conjTranspose
  Ising2D.checkFermiOf
  Ising2D.checkFermiOf_cre
  Ising2D.checkFermiOf_ann
  Ising2D.checkFermiOf_nOp
  Ising2D.finCheckIdxEquiv
  Ising2D.finCheckIdxEquiv_val
  Ising2D.checkFermiSetupOf
  Ising2D.checkFermiSetupOf_Xop
  Ising2D.checkFermiSetupOf_Vprime
  Ising2D.star_ofReal_self
  Ising2D.VPlus_eq_smul_checkVprime_const
  Ising2D.checkGam
  Ising2D.checkGam_pos
  Ising2D.checkGval
  Ising2D.checkX_mul_Qproj
  Ising2D.checkVprime_mul_Qproj
  Ising2D.vPlusDataOf
  Ising2D.vPlusDataOf_V
  Ising2D.vPlusDataOf_C
  Ising2D.vPlusDataOf_gam
  Ising2D.sum_checkGam
  Ising2D.EvenSectorClosureInput
  Ising2D.rayleighSup_eq_LambdaM_of_input
  Ising2D.onsager_exact_solution_unconditional
  # --- 020 章（比熱の対数発散：章の到達点）---
  Ising2D.gammaFn_isoParam_eq_gammaK
  Ising2D.integral_gammaFn_isoParam
  Ising2D.onsager_free_energy_isoParam
  Ising2D.onsager_exact_solution_isoParam
  Ising2D.hasDerivAt_logTerm
  Ising2D.hasDerivAt_logTermDeriv
  Ising2D.hasDerivAt_fFun
  Ising2D.hasDerivAt_fFirst
  Ising2D.eventually_hasDerivAt_fFun
  Ising2D.hasDerivAt_deriv_fFun
  Ising2D.deriv_deriv_fFun
  Ising2D.abs_logTerm_second_le
  Ising2D.abs_Gfirst_mul_kappaSecond_le
  Ising2D.abs_Gsecond_le
  Ising2D.abs_kappaDerivSq_sub_mul_Gsecond_le
  Ising2D.abs_sixteen_Gsecond_sub_le
  Ising2D.abs_fSecond_sub_le
  Ising2D.specific_heat_log_divergence
  Ising2D.fSecond_ge
  Ising2D.log_474_le
  Ising2D.abs_log_kappa_sub_log_dist_le
  Ising2D.specific_heat_log_divergence_dist
  Ising2D.tendsto_log_inv_dist_atTop
  Ising2D.specific_heat_ratio_tendsto
  Ising2D.NecSuf.idem_of_ortho_of_sum_eq_one
  Ising2D.NecSuf.iSupIndep_range_proj
  Ising2D.NecSuf.iSup_range_proj_eq_top
  Ising2D.NecSuf.isInternal_range_proj
  Ising2D.NecSuf.eigen_of_mem_range_proj
  Ising2D.NecSuf.collectedBasis_eigen
  Ising2D.NecSuf.toMatrix_collectedBasis_eq_diagonal
  Ising2D.NecSuf.isInternal_range_matrix_proj
  Ising2D.NecSuf.exists_eigenBasis_of_matrix_proj
  Ising2D.NecSuf.exists_conj_diagonal_of_matrix_proj
  Ising2D.FermiSetup.isInternal_range_Qproj
  Ising2D.FermiSetup.iSup_range_Qproj_eq_top
  Ising2D.FermiSetup.iSupIndep_range_Qproj
  Ising2D.FermiSetup.exists_eigenBasis_Vprime
  Ising2D.FermiSetup.exists_conj_diagonal_Vprime
  Ising2D.FermiSetup.exists_conj_diagonal_Vmat
  Ising2D.CheckFermiSetup.isInternal_range_Qproj
  Ising2D.CheckFermiSetup.iSup_range_Qproj_eq_top
  Ising2D.CheckFermiSetup.iSupIndep_range_Qproj
  Ising2D.CheckFermiSetup.exists_eigenBasis_Vprime
  Ising2D.CheckFermiSetup.exists_conj_diagonal_Vprime
  Ising2D.exists_eigenBasis_VPlus
  Ising2D.exists_conj_diagonal_VPlus
)

# 生成する一時ファイルは worktree ごとに別名にする。
# 固定パス（/tmp/…）だと、複数の worktree で同時に走らせたとき互いに上書きし、
# 別ブランチの target 一覧を検査してしまう（実際に誤検出が起きた）。
axiom_check_file="$(mktemp -t ising2d_axiom_check.XXXXXX.lean)"
trap 'rm -f "$axiom_check_file"' EXIT

{
  echo "import Ising2D"
  for t in "${targets[@]}"; do
    echo "#print axioms $t"
  done
} > "$axiom_check_file"

out="$(lake env lean --stdin < "$axiom_check_file")"
echo "$out"

if echo "$out" | grep -q 'sorryAx'; then
  echo "NG: sorryAx に依存している定理がある" >&2
  status=1
else
  echo "OK: 主要定理はいずれも sorryAx に依存していない"
fi

exit "$status"
