/-
2次元 Ising 模型の厳密解（Λ・Fisher 零点の立場）の形式検証の入口。

人手証明の正本は `structured-latex/content/`。ここに置く証明は次の 2 本立てにする。
  具体版      : `Ising2DLambda.<章名>`        人手証明と 1 対 1 に対応させる
  必要十分版  : `Ising2DLambda.NecSuf.<章名>` 同じ手順のまま仮定だけ必要十分にする
規約は `lean/README.md` を正本とする。

住処の規約: 人手証明のブロックが可算な住処を宣言しているなら、対応する具体版に
`ℝ` / `ℂ` を出さない（数え上げは `ℕ`、分配多項式は `Polynomial ℤ`）。
非可算を宣言したブロックの証明だけが `ℝ` / `ℂ` を使ってよく、
その場合はファイル冒頭に人手証明の `realEscape` と同じ理由を書く。

現状: 章「分配多項式」の定義 4 件と主張 3 件
（人手証明のラベル `claim_configuration_partition`・`claim_coefficient_representation`・
`claim_coefficient_sum`）、および章「有限系の自由エントロピー」の定義 4 件と主張 5 件
（`claim_rational_exponent_well_defined`・`claim_value_at_rational_is_positive`・
`claim_log_additive`・`claim_log_power`・`claim_free_entropy_at_one`）、
および章「転送行列」の定義 11 件と主張 6 件・定理 1 件
（`claim_edge_row_partition`・`claim_broken_bond_row_decomposition`・
`claim_rows_bijection`・`claim_transfer_weight_product`・`claim_matrix_pow_entry`・
`claim_closed_walk_bijection`・`theorem_partition_polynomial_is_trace`）、
および章「固有値の代数性」の定義 15 件と主張 19 件・定理 1 件
（`claim_row_config_order_linear`・`claim_permutation_sign_values`・`claim_permutation_sign_mul`・
`claim_permutation_moves_two`・`claim_determinant_diagonal`・ℤ[x][t] の次数の 4 主張・
特性多項式の 3 主張・巡回シフトの 5 主張・シフト行列の 2 主張と
`theorem_shift_matrix_commutes`）を形式化済み。
-/
import Ising2DLambda.PartitionPolynomial.Basic
import Ising2DLambda.PartitionPolynomial.CoefficientSum
import Ising2DLambda.NecSuf.PartitionPolynomial.CoefficientSum
import Ising2DLambda.PartitionPolynomial.CoefficientSumFromNecSuf
import Ising2DLambda.PartitionPolynomial.CoefficientRepresentation
import Ising2DLambda.NecSuf.PartitionPolynomial.CoefficientRepresentation
import Ising2DLambda.PartitionPolynomial.CoefficientRepresentationFromNecSuf
import Ising2DLambda.FreeEntropy.Basic
import Ising2DLambda.FreeEntropy.RationalExponent
import Ising2DLambda.NecSuf.FreeEntropy.RationalExponent
import Ising2DLambda.FreeEntropy.RationalExponentFromNecSuf
import Ising2DLambda.FreeEntropy.ValuePositive
import Ising2DLambda.NecSuf.FreeEntropy.ValuePositive
import Ising2DLambda.FreeEntropy.ValuePositiveFromNecSuf
import Ising2DLambda.FreeEntropy.Additivity
import Ising2DLambda.NecSuf.FreeEntropy.Additivity
import Ising2DLambda.FreeEntropy.AdditivityFromNecSuf
import Ising2DLambda.FreeEntropy.AtOne
import Ising2DLambda.TransferMatrix.Basic
import Ising2DLambda.TransferMatrix.RowDecomposition
import Ising2DLambda.NecSuf.TransferMatrix.RowDecomposition
import Ising2DLambda.TransferMatrix.RowDecompositionFromNecSuf
import Ising2DLambda.TransferMatrix.WeightProduct
import Ising2DLambda.NecSuf.TransferMatrix.WeightProduct
import Ising2DLambda.TransferMatrix.WeightProductFromNecSuf
import Ising2DLambda.TransferMatrix.PowerEntry
import Ising2DLambda.NecSuf.TransferMatrix.PowerEntry
import Ising2DLambda.TransferMatrix.PowerEntryFromNecSuf
import Ising2DLambda.TransferMatrix.Trace
import Ising2DLambda.NecSuf.TransferMatrix.Trace
import Ising2DLambda.TransferMatrix.TraceFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.RowConfigOrder
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.RowConfigOrder
import Ising2DLambda.AlgebraicEigenvalue.RowConfigOrderFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.PermutationSign
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.PermutationSign
import Ising2DLambda.AlgebraicEigenvalue.PermutationSignFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.Determinant
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.Determinant
import Ising2DLambda.AlgebraicEigenvalue.DeterminantFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.SecondPolynomial
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.SecondPolynomial
import Ising2DLambda.AlgebraicEigenvalue.SecondPolynomialFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.CharacteristicPolynomial
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.CharacteristicPolynomial
import Ising2DLambda.AlgebraicEigenvalue.CharacteristicPolynomialFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.RowConfigShift
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.RowConfigShift
import Ising2DLambda.AlgebraicEigenvalue.RowConfigShiftFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.ShiftMatrix
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.ShiftMatrix
import Ising2DLambda.AlgebraicEigenvalue.ShiftMatrixFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.ShiftMatrixOrder
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.ShiftMatrixOrder
import Ising2DLambda.AlgebraicEigenvalue.ShiftMatrixOrderFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.RowShiftPeriod
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.RowShiftPeriod
import Ising2DLambda.AlgebraicEigenvalue.RowShiftPeriodFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.RowShiftOrbit
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.RowShiftOrbit
import Ising2DLambda.AlgebraicEigenvalue.RowShiftOrbitFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.RowShiftOrbitPartition
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.RowShiftOrbitPartition
import Ising2DLambda.AlgebraicEigenvalue.RowShiftOrbitPartitionFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharTerm
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.ShiftCharTerm
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharTermFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitRestriction
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitRestriction
import Ising2DLambda.AlgebraicEigenvalue.OrbitRestrictionFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitGluing
import Ising2DLambda.AlgebraicEigenvalue.OrbitGluing
import Ising2DLambda.AlgebraicEigenvalue.OrbitGluingFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.CrossOrbitInversions
import Ising2DLambda.AlgebraicEigenvalue.CrossOrbitInversions
import Ising2DLambda.AlgebraicEigenvalue.CrossOrbitInversionsFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.InversionOrbitDecomposition
import Ising2DLambda.AlgebraicEigenvalue.InversionOrbitDecomposition
import Ising2DLambda.AlgebraicEigenvalue.InversionOrbitDecompositionFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.RowConfigMin
import Ising2DLambda.AlgebraicEigenvalue.RowConfigMin
import Ising2DLambda.AlgebraicEigenvalue.RowConfigMinFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrientedOrbitPairs
import Ising2DLambda.AlgebraicEigenvalue.OrientedOrbitPairs
import Ising2DLambda.AlgebraicEigenvalue.OrientedOrbitPairsFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitPermutationSign
import Ising2DLambda.AlgebraicEigenvalue.OrbitPermutationSign
import Ising2DLambda.AlgebraicEigenvalue.OrbitPermutationSignFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitTermFactorization
import Ising2DLambda.AlgebraicEigenvalue.OrbitTermFactorization
import Ising2DLambda.AlgebraicEigenvalue.OrbitTermFactorizationFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.ShiftCharSum
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharSum
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharSumFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitFamilySum
import Ising2DLambda.AlgebraicEigenvalue.OrbitFamilySum
import Ising2DLambda.AlgebraicEigenvalue.OrbitFamilySumFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitFamilyInsert
import Ising2DLambda.AlgebraicEigenvalue.OrbitFamilyInsert
import Ising2DLambda.AlgebraicEigenvalue.OrbitFamilyInsertFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitFamilyDistributive
import Ising2DLambda.AlgebraicEigenvalue.OrbitFamilyDistributive
import Ising2DLambda.AlgebraicEigenvalue.OrbitFamilyDistributiveFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.ShiftCharOrbitProduct
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharOrbitProduct
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharOrbitProductFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitBijectionIdOrShift
import Ising2DLambda.AlgebraicEigenvalue.OrbitBijectionIdOrShift
import Ising2DLambda.AlgebraicEigenvalue.OrbitBijectionIdOrShiftFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitPermutationSignValues
import Ising2DLambda.AlgebraicEigenvalue.OrbitPermutationSignValues
import Ising2DLambda.AlgebraicEigenvalue.OrbitPermutationSignValuesFromNecSuf
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitTransposition
import Ising2DLambda.AlgebraicEigenvalue.OrbitTransposition
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionSign
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitTranspositionSign
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionSignFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionComposite
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitTranspositionComposite
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionCompositeFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.RowShiftIterateDistinct
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.RowShiftIterateDistinct
import Ising2DLambda.AlgebraicEigenvalue.RowShiftIterateDistinctFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionCompositeValues
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitTranspositionCompositeValues
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionCompositeValuesFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionCompositeIsShift
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitTranspositionCompositeIsShift
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionCompositeIsShiftFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionCompositeSign
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitTranspositionCompositeSign
import Ising2DLambda.AlgebraicEigenvalue.OrbitTranspositionCompositeSignFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitShiftRestrictionSign
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitShiftRestrictionSign
import Ising2DLambda.AlgebraicEigenvalue.OrbitShiftRestrictionSignFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitPermutationSignMul
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitPermutationSignMul
import Ising2DLambda.AlgebraicEigenvalue.OrbitPermutationSignMulFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitFactorZero
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitFactorZero
import Ising2DLambda.AlgebraicEigenvalue.OrbitFactorZeroFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitFixedIffCardOne
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitFixedIffCardOne
import Ising2DLambda.AlgebraicEigenvalue.OrbitFixedIffCardOneFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharDiagonalEntry
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.ShiftCharDiagonalEntry
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharDiagonalEntryFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitIdentityFactor
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitIdentityFactor
import Ising2DLambda.AlgebraicEigenvalue.OrbitIdentityFactorFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitShiftRestrictionFactor
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitShiftRestrictionFactor
import Ising2DLambda.AlgebraicEigenvalue.OrbitShiftRestrictionFactorFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitSumTwoTerms
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitSumTwoTerms
import Ising2DLambda.AlgebraicEigenvalue.OrbitSumTwoTermsFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.PowerSumTelescope
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.PowerSumTelescope
import Ising2DLambda.AlgebraicEigenvalue.PowerSumTelescopeFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitSumDividesPowL
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitSumDividesPowL
import Ising2DLambda.AlgebraicEigenvalue.OrbitSumDividesPowLFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.ProdPairEqPowCard
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.ProdPairEqPowCard
import Ising2DLambda.AlgebraicEigenvalue.ProdPairEqPowCardFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharDvdPowL
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.ShiftCharDvdPowL
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharDvdPowLFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharOrbitFactorization
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.ShiftCharOrbitFactorization
import Ising2DLambda.AlgebraicEigenvalue.ShiftCharOrbitFactorizationFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.RootOfUnity
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.RootOfUnity
import Ising2DLambda.AlgebraicEigenvalue.RootOfUnityFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.OrbitFactorRoot
import Ising2DLambda.NecSuf.AlgebraicEigenvalue.OrbitFactorRoot
import Ising2DLambda.AlgebraicEigenvalue.OrbitFactorRootFromNecSuf
import Ising2DLambda.AlgebraicEigenvalue.SecondEvaluationProd
import Ising2DLambda.AlgebraicEigenvalue.SecondEvaluationProdFromNecSuf
