

# This file was *autogenerated* from the file check_01_mat_mult.sage
from sage.all_cmdline import *   # import sage library

_sage_const_219 = Integer(219); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_8 = Integer(8); _sage_const_25 = Integer(25); _sage_const_1j = ComplexNumber(0, '1')# <mat_mult>: mat(Aa, Ab) = A mat(a,b)
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
load(os.path.join(_dir, "_prelude.sage"))
import numpy as np
import math
rng = np.random.default_rng(int(_sage_const_219 ))
rep = CheckReport("mat_mult")
for n in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_8 ]:
    for _ in range(_sage_const_25 ):
        A = rng.normal(size=(n,n)) + _sage_const_1j *rng.normal(size=(n,n))
        a = rng.normal(size=(n,)) + _sage_const_1j *rng.normal(size=(n,))
        b = rng.normal(size=(n,)) + _sage_const_1j *rng.normal(size=(n,))
        lhs = np.column_stack([A@a, A@b])          # mat(Aa, Ab)
        rhs = A @ np.column_stack([a, b])          # A mat(a,b)
        rep.close(lhs, rhs, f"n={n}: mat(Aa,Ab) = A mat(a,b)")
rep.finish()

