

# This file was *autogenerated* from the file check_01_euler.sage
from sage.all_cmdline import *   # import sage library

_sage_const_213 = Integer(213); _sage_const_0p0 = RealNumber('0.0'); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1p0 = RealNumber('1.0'); _sage_const_10p0 = RealNumber('10.0'); _sage_const_5 = Integer(5); _sage_const_40 = Integer(40); _sage_const_0 = Integer(0); _sage_const_2j = ComplexNumber(0, '2'); _sage_const_1j = ComplexNumber(0, '1')# <euler_formula_cos_sin>: cos t = (e^{it}+e^{-it})/2, sin t = (e^{it}-e^{-it})/(2i)
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
load(os.path.join(_dir, "_prelude.sage"))
import numpy as np
import math
rng = np.random.default_rng(int(_sage_const_213 ))
rep = CheckReport("euler_formula_cos_sin")
ts = [_sage_const_0p0 , math.pi/_sage_const_6 , math.pi/_sage_const_4 , math.pi/_sage_const_3 , math.pi/_sage_const_2 , math.pi, _sage_const_3 *math.pi/_sage_const_2 , _sage_const_2 *math.pi, -_sage_const_1p0 , _sage_const_10p0 ]      + [float(rng.normal()*_sage_const_5 ) for _ in range(_sage_const_40 )]
for t in ts:
    e_p = complex(math.cos(t), math.sin(t))     # e^{it}（定義側は cos/sin で作る）
    e_m = complex(math.cos(-t), math.sin(-t))
    rep.close((e_p+e_m)/_sage_const_2 , complex(math.cos(t),_sage_const_0 ), f"t={t:.6f}: cos の表示")
    rep.close((e_p-e_m)/(_sage_const_2j ), complex(math.sin(t),_sage_const_0 ), f"t={t:.6f}: sin の表示")
    # 独立経路: numpy の complex exp
    rep.close(np.exp(_sage_const_1j *t), e_p, f"t={t:.6f}: e^{{it}} = cos t + i sin t")
rep.finish()

