

# This file was *autogenerated* from the file check_01_existence_uniqueness.sage
from sage.all_cmdline import *   # import sage library

_sage_const_202 = Integer(202); _sage_const_0p0 = RealNumber('0.0'); _sage_const_1en12 = RealNumber('1e-12'); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_0p25 = RealNumber('0.25'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_10p0 = RealNumber('10.0'); _sage_const_1e6 = RealNumber('1e6'); _sage_const_1e12 = RealNumber('1e12'); _sage_const_10 = Integer(10); _sage_const_40 = Integer(40); _sage_const_0 = Integer(0); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_1en7 = RealNumber('1e-7'); _sage_const_1en5 = RealNumber('1e-5')# <sqrt_nonnegative_existence_uniqueness>: 非負実数の平方根の存在・一意性
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
load(os.path.join(_dir, "_prelude.sage"))
import numpy as np
import math
rng = np.random.default_rng(int(_sage_const_202 ))
rep = CheckReport("sqrt_nonnegative_existence_uniqueness")
xs = [_sage_const_0p0 , _sage_const_1en12 , _sage_const_1en6 , _sage_const_0p25 , _sage_const_1p0 , _sage_const_2p0 , _sage_const_10p0 , _sage_const_1e6 , _sage_const_1e12 ] + [abs(float(rng.normal()))*_sage_const_10  for _ in range(_sage_const_40 )]
for x in xs:
    y = sqrt_nonneg(x)           # 二分法で構成（存在）
    rep.truth(y >= _sage_const_0 , f"x={x:.6e}: y >= 0")
    rep.close(y*y, x, f"x={x:.6e}: y^2 = x（存在）")
    # 一意性: y' >= 0 かつ y'^2 = x なら y' = y
    for pert in [_sage_const_1en9 , _sage_const_1en7 , _sage_const_1en5 ]:
        yp = y + pert
        if yp >= _sage_const_0 :
            rep.truth(abs(yp*yp - x) > _sage_const_0  or x == _sage_const_0 , f"x={x:.6e}: y+{pert} は y^2=x を満たさない（一意性）")
    # 負の候補は R_{>=0} に属さない
    rep.truth(-y <= _sage_const_0 , f"x={x:.6e}: -y は非負ではない（値域の指定が効く）")
rep.finish()

