

# This file was *autogenerated* from the file check_01_duality.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_2 = Integer(2); _sage_const_2p0 = RealNumber('2.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_0p4407 = RealNumber('0.4407'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_1p1 = RealNumber('1.1'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_1p3 = RealNumber('1.3'); _sage_const_3p0 = RealNumber('3.0'); _sage_const_0p5 = RealNumber('0.5')# <duality_c2_star_eq_s2_star_c2>: s_2^* = 1/s_2, c_2^* = c_2/s_2, c_2^* = s_2^* c_2
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np

def crit_K1(K2):
    """臨界条件 sinh(2K_1) sinh(2K_2) = 1 をちょうど満たす K_1。"""
    return float(np.arcsinh(_sage_const_1p0 /np.sinh(_sage_const_2 *K2))/_sage_const_2p0 )

CRIT_PARAMS = [{"K1": crit_K1(k2), "K2": k2} for k2 in [_sage_const_0p3 , _sage_const_0p4407 , _sage_const_0p6 , _sage_const_1p1 ]]
ALL_PARAMS = list(OP_TEST_PARAMS) + CRIT_PARAMS

rep = CheckReport("duality_c2_star_eq_s2_star_c2")
for K2 in [_sage_const_0p05 ,_sage_const_0p1 ,_sage_const_0p2 ,_sage_const_0p3 ,_sage_const_0p4407 ,_sage_const_0p6 ,_sage_const_0p9 ,_sage_const_1p3 ,_sage_const_2p0 ,_sage_const_3p0 ]:
    K2s = K_star(K2)
    c2,s2 = c_of(K2),s_of(K2)
    c2s,s2s = c_of(K2s),s_of(K2s)
    rep.close(s2s, _sage_const_1p0 /s2, f"K2={K2}: s_2^* = 1/s_2")
    rep.close(c2s, c2/s2, f"K2={K2}: c_2^* = c_2/s_2")
    rep.close(c2s, s2s*c2, f"K2={K2}: c_2^* = s_2^* c_2")
    rep.close(s2*s2s, _sage_const_1p0 , f"K2={K2}: sinh(2K_2) sinh(2K_2^*) = 1（双対の定義）")
    rep.close(K2s, -_sage_const_0p5 *np.log(np.tanh(K2)), f"K2={K2}: K_2^* = -1/2 log(tanh K_2)")
rep.finish()

