/-
`integrable-lattice` プロジェクトの Lean 4 + mathlib4 による形式検証。

対応する人手証明は `integrable-lattice/outputs/paper-plans/002_R_Lambda_duality.md` §2
「現時点で厳密に確定している部分命題」の命題 A, B, C, N, L, T, V, W である。
どの命題がどこまで形式化されているか（および形式化できなかった理由）は
`integrable-lattice/lean/README.md` の「形式化の現状」表を正本とする。

**新規性は主張しない。** ここで形式化した命題はいずれも既知内容の再框であり、
Lean 化もその一部である。
-/
import IntegrableLattice.PropL
import IntegrableLattice.PropA
import IntegrableLattice.PropV
import IntegrableLattice.PropC
import IntegrableLattice.PropCPeriod
import IntegrableLattice.PropB
import IntegrableLattice.PropBTracePeriod
import IntegrableLattice.PropN
import IntegrableLattice.PropT
import IntegrableLattice.PropW
import IntegrableLattice.PropCTracePeriod
import IntegrableLattice.DigitTheorem
import IntegrableLattice.BouquetClosedForm
import IntegrableLattice.TowerTypeCoefficients
import IntegrableLattice.DigitBranchRecursion
import IntegrableLattice.SInfinityDecision
import IntegrableLattice.EllTwoClosedForm
import IntegrableLattice.DropAssumptionBStar
import IntegrableLattice.GeneralTowerClosedForm
import IntegrableLattice.CoefficientsDE
import IntegrableLattice.Cycle24Corrections
import IntegrableLattice.Cycle25Corrections
import IntegrableLattice.Cycle26ProofSteps
import IntegrableLattice.Cycle27ProofSteps
import IntegrableLattice.PropWStarDifferent
import IntegrableLattice.PropFFiniteSupport
import IntegrableLattice.ExtremumNonempty
import IntegrableLattice.TracePeriodAssembly
import IntegrableLattice.PeriodicPointResultant
import IntegrableLattice.DualityPAdicFiniteL
import IntegrableLattice.WStarElementaryDivisors
import IntegrableLattice.WStarIntegralDescent
import IntegrableLattice.MultigraphLaplacian
import IntegrableLattice.CauchyBinet
import IntegrableLattice.CrudeArchimedeanBound
import IntegrableLattice.IncidenceUnimodular
import IntegrableLattice.CyclotomicValuationQ4a
import IntegrableLattice.PropQLaurentLift
import IntegrableLattice.KirchhoffCounting
