/**
 * 章「トーラス上の Kac--Ward 行列式」に紐づく検算・観察ノート。
 * 検算は証明ではなく、一般化できない有限標本を本文へ混ぜない。
 */

import { defineNotes, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineNotes([
  {
    id: "note_kac_ward_definition_determinants_even_subgraph_square_observation",
    targets: ["def_kac_ward_determinants"],
    title: { text: "行列式は符号付き偶部分グラフ多項式の平方（観察と経路の確定）" },
    body: [
      paragraph([
        "検証水準の計算として、一辺 ", math(String.raw`L=2,3`),
        " の周期正方格子で四つの Kac--Ward 行列式 ",
        math(String.raw`\det\bigl(I-x\,M^{a,b}\bigr)`),
        " を円分体 ", math(String.raw`\mathbb Q(\zeta_8)`),
        " 係数の多項式として厳密に計算し、全頂点の次数が偶数である台の辺の部分集合",
        "（偶部分グラフ）", math(String.raw`A`), " の切断線偶奇 ",
        math(String.raw`(h(A),v(A))`), " に符号 ",
        math(String.raw`(-1)^{c\,h+d\,v+e\,hv}`), "（", math(String.raw`c,d,e\in\{0,1\}`),
        " の全 8 候補）を付けた多項式の平方と比較した",
        "（sagemath/check/torus-kac-ward-even-subgraph-square）。",
      ]),
      paragraph([
        "結果、四つのスピン構造すべてで等式",
      ]),
      displayMath(String.raw`\det\bigl(I-x\,M^{a,b}\bigr)
=\Bigl(\sum_{A}(-1)^{(1+a)h(A)+(1+b)v(A)+h(A)v(A)}\,x^{|A|}\Bigr)^{2}`),
      paragraph([
        "が成り立った。スピン構造 ", math(String.raw`(0,1)`), " と ",
        math(String.raw`(1,0)`), " では二つの符号候補の平方が一致するが、これは正方トーラスの",
        "軸対称によりホモロジー類 ", math(String.raw`(1,0)`), " と ",
        math(String.raw`(0,1)`),
        " の類別和が多項式として一致するためで、等式の一意性とは矛盾しない。",
      ]),
      paragraph([
        "この観察により、一般の ", math(String.raw`L`), " で証明すべき候補は",
        "「行列式＝符号付き偶部分グラフ多項式の平方」という行列式レベルの恒等式である。",
        "ただし多項式全体の一致だけから、置換展開の個々の両向き項が相殺するか、平方の交差項へ",
        "どのように対応するかは決まらない。この項ごとの対応は一般の恒等式の証明で別に示す必要がある。",
        "反復分解（接触対数の整礎帰納）は、この恒等式の証明の中で各閉路の回転位相符号を",
        "確定するために使う。これは有限標本（", math(String.raw`L=2,3`),
        "）の観察であり、一般の ", math(String.raw`L`), " についてはまだ何も証明していない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_definition_cyclic_total_turning_vertex_simple_observation",
    targets: ["def_cyclic_total_turning"],
    title: { text: "頂点単純閉路の循環総回転数（証明前の有限標本観察）" },
    body: [
      paragraph([
        "検証水準の計算として、一辺 ", math(String.raw`L=2,3,4`),
        " の周期正方格子で、通過の頂点が相異なる（接触対数零の）閉じた非後退辺列を",
        "全列挙し（基点と向きを区別した数え上げで全 ", math(String.raw`373{,}716`),
        " 本）、循環総回転数 ", math(String.raw`t_{\circ}(\gamma)`),
        " と切断線偶奇 ", math(String.raw`(h(\gamma)\bmod2,\ v(\gamma)\bmod2)`),
        " を突き合わせた（sagemath/check/vertex-simple-cycle-turning）。",
      ]),
      paragraph([
        "結果、次の離散 Whitney の言明が例外なく成り立った。切断線偶奇が ",
        math(String.raw`(0,0)`), " の頂点単純閉路（", math(String.raw`73{,}616`),
        " 本）は ", math(String.raw`t_{\circ}(\gamma)\in\{+4,-4\}`),
        "。切断線偶奇が ", math(String.raw`(0,0)`), " 以外の頂点単純閉路（",
        math(String.raw`300{,}100`), " 本）は ", math(String.raw`t_{\circ}(\gamma)=0`),
        "。この観察は本文の「頂点単純閉路の循環総回転数は切断線偶奇で決まる」で",
        "一般の一辺長について証明済みである。",
      ]),
      paragraph([
        "整数巻き付きベクトルが零の場合は、本文の平面持ち上げと有限セルの二重計数により一般の ",
        math(String.raw`L`), " で ", math(String.raw`t_{\circ}(\gamma)\in\{+4,-4\}`),
        " が証明された。したがって、この場合の回転位相は ",
        math(String.raw`\zeta_8^{\,t_{\circ}(\gamma)}=-1`),
        " である。零でない原始的巻き付きの場合の ",
        math(String.raw`t_{\circ}(\gamma)=0`), " と回転位相 ",
        math(String.raw`+1`),
        " も周期単純路の一側閉包と三周期比較により証明済みである。有限標本（",
        math(String.raw`L=2,3,4`), "）の観察は証明された二場合の両方を検査している。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_parallel_separated_staircases_direct_closure_counterexample",
    targets: ["claim_parallel_separated_staircases_disjoint"],
    title: { text: "二本の反復横断階段を対応点へ結ぶ直接閉包は単純にならない" },
    body: [
      paragraph([
        "周期持ち上げの一周期分と、その横断平行移動を、両端から出した同じ反復横断階段で結ぶ候補は、",
        "既存の分離補題だけでは単純閉路にならない。反例は一辺 ", math(String.raw`L=2`),
        " のトーラス上の頂点列 ",
        math(String.raw`((0,0),(0,1),(1,1),(1,0),(0,0))`),
        " である。この閉路の平面持ち上げの一周期分は",
      ]),
      displayMath(String.raw`(0,0),(0,1),(1,1),(1,0),(2,0)`),
      paragraph([
        "となり、巻き付き数は ", math(String.raw`(w_{\mathrm h},w_{\mathrm v})=(0,1)`),
        "、正の横断階段は左向きである。横断幅を超える二回の平行移動で直接閉包すると、",
        "合成列には、左側の接続階段と平行移動後の持ち上げの交点 ", math(String.raw`(0,-1)`),
        " が二度現れる。したがって「二つの周期持ち上げが互いに交わらないこと」と",
        "「二本の階段が互いに交わらないこと」だけでは、階段と反対側の持ち上げとの交差を排除できない。",
      ]),
      paragraph([
        "この候補は採用しない。閉包を完成させるには、反対側の持ち上げも終点以外で避ける接続路を別に構成し、",
        "その後に四つの部分の交差を組ごとに検査する必要がある。反例は整数格子の有限列だけで完結し、",
        "実数体も複素数体も用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_periodic_lift_closure_turning_difference_cancellation",
    targets: ["def_periodic_lift_closure_cycle", "def_cyclic_total_turning"],
    title: { text: "周期数を増やした閉包の回転数差では持ち上げの回転数を取り出せない" },
    body: [
      paragraph([
        "周期数 ", math(String.raw`c`), " の閉包と周期数 ", math(String.raw`c+1`),
        " の閉包の循環総回転数を比較する候補は採用しない。接続階段の向きの有限語を ",
        math(String.raw`A`), "、周期持ち上げ一周期分の向きの巡回語を ", math(String.raw`P`),
        " とし、向きを全て反転して順序を逆にした語をそれぞれ ",
        math(String.raw`\overline A,\overline P`), " と書く。閉包の向きの巡回語は、",
      ]),
      displayMath(String.raw`A\,P^{c}\,\overline A\,\overline P^{c}`),
      paragraph([
        "の形である。周期数を一つ増やすと、順向きの周期語 ", math(String.raw`P`),
        " と逆向きの周期語 ", math(String.raw`\overline P`),
        " が一つずつ同時に挿入される。巡回語の回転数和を ", math(String.raw`T`),
        " と書くと、巡回の開始位置をずらしても有限和は変わらず、逆向きでは各回転の符号が反転するので",
      ]),
      displayMath(String.raw`T(P)+T(\overline P)=T(P)-T(P)=0`),
      paragraph([
        "となる。したがって閉包の循環総回転数の差は、元の ", math(String.raw`T(P)`),
        " の値にかかわらず零であり、この差から ", math(String.raw`T(P)=0`),
        " を導くことはできない。SageMath の有限全列挙でも、一辺 ", math(String.raw`L=1,2,3`),
        " の全対象について周期数 ", math(String.raw`c=1,2,3`),
        " の閉包の循環総回転数が一致し、追加された順向き・逆向きの一周期の和が零になることを整数だけで確認した",
        "（sagemath/check/periodic-lift-closure-cycle）。次は、逆向きの周期持ち上げを同時に追加しない一側閉包を構成し、",
        "周期数の差に一周期分だけが残る形へ変える必要がある。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_doubled_edge_fiber_phase_reduction_unlocked_residual_noncancellation",
    targets: ["claim_doubled_edge_fiber_phase_reduction", "def_unswitchable_standard_pair_subset"],
    title: { text: "切り替え可能接触を持つ残余は符号反転対合で相殺できない" },
    body: [
      paragraph([
        "標準対が切り替え不能な残余 ", math(String.raw`\mathcal R_L`),
        " のうち、別の切り替え可能な接触対を持つ部分について、平滑化と両立する接触対の選択規則を",
        "作って符号反転対合で相殺する候補は採用しない。理由は二つある。第一に、切り替え可能な接触対の",
        "辞書式最小を選ぶ規則は平滑化と両立しない。一辺 ", math(String.raw`L=2`),
        " のこの部分 ", math(String.raw`17{,}925`), " 個を厳密に列挙したところ、辞書式最小の",
        "切り替え可能対での平滑化が標準対を切り替え可能へ変えて残余から出すものが ",
        math(String.raw`4{,}638`), " 個、平滑化後に辞書式最小の切り替え可能対が変わるものが ",
        math(String.raw`7{,}935`), " 個あった。",
      ]),
      paragraph([
        "第二に、選択規則の作り方に依らず、相殺そのものが不可能である。ファイバーを保ち",
        "位相寄与の符号を反転する不動点の無い対合がこの部分の上に存在すれば、その位相寄与の総和は",
        "各ファイバー×スピン構造で零になるはずである。ところが一辺 ", math(String.raw`L=2`),
        " の厳密和は、この部分が空でない ", math(String.raw`1{,}288`), " 組中 ",
        math(String.raw`380`), " 組で非零であり、残余 ", math(String.raw`\mathcal R_L`),
        " 全体の総和も ", math(String.raw`1{,}028`), " 組で非零である",
        "（sagemath/check/unlocked-residual-phase-noncancellation）。したがって残余は相殺の対象ではなく、",
        "回転差が正負四の二集合と合わせて、符号付き偶部分グラフ多項式の平方の項と数え上げで",
        "対応づけるべき寄与として扱う。この検算は有限集合の比較と円分体 ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の厳密和だけで完結し、実数体は用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_def_fiber_phase_weight_signed_selection_sum_fiberwise_equality",
    targets: ["def_fiber_phase_weight", "def_signed_selection_sum"],
    title: { text: "一辺二では置換ファイバー位相和と偶部分グラフ選択和が添字ごとに一致する" },
    body: [
      paragraph([
        "一般の平方恒等式で目標にすべき対応を確定するため、一辺 ", math(String.raw`L=2`),
        " の全非後退置換を反転対の辺集合 ", math(String.raw`D`), " と単純通過の辺集合 ",
        math(String.raw`E`), " で層別し、置換側の位相和 ",
        math(String.raw`\mathcal K^{a,b}_L(D,E)`), " と偶部分グラフ対側の符号付き選択和 ",
        math(String.raw`\mathcal U^{a,b}_L(D,E)`), " を定義から直接比較した。全 ",
        math(String.raw`609`), " ファイバーと四つのスピン構造、合計 ",
        math(String.raw`2{,}436`), " 件で",
      ]),
      displayMath(String.raw`\mathcal K^{a,b}_L(D,E)=\mathcal U^{a,b}_L(D,E)`),
      paragraph([
        "が成立した（sagemath/check/kac-ward-fiber-signed-selection-equality）。したがって、",
        "多項式全体の係数をまとめて比較するだけでなく、接触の無い置換、回転差が正負四の置換、",
        "残余を合わせた位相和を、同じ ", math(String.raw`(D,E)`),
        " の選択集合と数え上げで対応づければ平方恒等式へ合成できる。これは一般の ",
        math(String.raw`L`), " に対する証明ではなく、次に構成すべきファイバーごとの全単射または",
        "符号付き数え上げの目標を固定する厳密観察である。計算は有限集合、整数、円分体 ",
        math(String.raw`\mathbb Q(\zeta_8)`), " だけで閉じ、実数体は用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_def_fiber_phase_weight_signed_selection_sum_part_decomposition",
    targets: ["def_fiber_phase_weight", "def_signed_selection_sum"],
    title: { text: "一辺二では簡約四部分の位相和がすべて有理整数に落ち回転差二部分は相等である" },
    body: [
      paragraph([
        "一般の数え上げの形を絞るため、一辺 ", math(String.raw`L=2`),
        " の各ファイバー位相和を、位相反転部分集合 ", math(String.raw`\mathcal B_L`),
        " の零和で簡約した後に残る四部分（接触の無い置換、回転差 ", math(String.raw`-4`),
        " の置換、回転差 ", math(String.raw`4`), " の置換、残余 ", math(String.raw`\mathcal R_L`),
        "）へ分解し、全 ", math(String.raw`609`), " ファイバー×四スピン構造 ",
        math(String.raw`2{,}436`), " 組で各部分の位相和を ",
        math(String.raw`\mathbb Q(\zeta_8)`),
        " の厳密和として計算した（sagemath/check/kac-ward-fiber-phase-part-decomposition）。",
        "三つの観察を得た。第一に、四部分の位相和 ", math(String.raw`2{,}436\times4`),
        " 個はすべて有理整数に落ちた。第二に、回転差 ", math(String.raw`-4`), " と ",
        math(String.raw`4`), " の二部分の位相和は全組で互いに等しかった",
        "（標準対平滑化が両集合を交換し位相寄与を保存することと整合する）。",
        "第三に、接触の無い部分だけで ", math(String.raw`\mathcal U^{a,b}_L(D,E)`),
        " に一致するのは ", math(String.raw`1{,}052`), " 組に留まり、残余の位相和が非零の ",
        math(String.raw`1{,}028`), " 組と回転差二部分の和が非零の ", math(String.raw`464`),
        " 組が残りを埋めた。したがって一般の ", math(String.raw`L`),
        " で立てるべき言明は、円分体の値ではなく整数値の三つの符号付き数え上げ",
        "（接触の無い部分、回転差 ", math(String.raw`4`),
        " の部分の二倍、残余）の和が ", math(String.raw`\mathcal U^{a,b}_L(D,E)`),
        " に等しい、という形になる。これは一般の証明ではなく目標の形を固定する厳密観察である。",
        "計算は有限集合、整数、円分体だけで閉じ、実数体は用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_contact_smoothing_same_pair_involution_lexicographic_choice_counterexample",
    targets: ["claim_contact_smoothing_same_pair_involution"],
    title: { text: "辞書式最小の切り替え可能接触対は平滑化で保たれない" },
    body: [
      paragraph([
        "切り替え可能な接触対全体を向き付き辺の固定した辞書式順序で並べ、最小の対を選ぶ規則は、",
        "符号反転対合の標準対として採用しない。同じ対での平滑化は対合であるが、平滑化によって",
        "その対と一辺だけを共有する別の接触対の切り替え可能性が変わり得るため、最小の対そのものは保存されない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の全非後退置換 ", math(String.raw`30{,}784`),
        " 個を厳密に列挙したところ、切り替え可能な接触対を持つ置換は ", math(String.raw`29{,}905`),
        " 個あり、そのうち ", math(String.raw`7{,}935`),
        " 個で、辞書式最小対による平滑化の前後に選ばれる対が異なった",
        "（sagemath/check/lexicographic-switchable-contact-choice-counterexample）。",
        "したがって、次に定める標準対は単なる最小化ではなく、平滑化の前後で同じ局所データを選ぶ規則でなければならない。",
        "この検算は有限集合の比較だけで完結し、実数体も複素数体も用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_path_reversal_contact_pair_preservation_standard_classification_counterexample",
    targets: [
      "claim_path_reversal_contact_pair_preservation",
      "def_standard_turning_difference_subsets",
      "def_unswitchable_standard_pair_subset",
    ],
    title: { text: "標準接触対に依存する分類は経路反転で保たれない" },
    body: [
      paragraph([
        "接触対全体の全単射と各接触対の切り替え可能性の保存から、固定した辞書式順序で選ぶ標準接触対に",
        "依存する分類まで保存されるとは限らない。経路反転が誘導する全単射 ",
        math(String.raw`\Psi_{\varphi}`),
        " は接触対の辞書式順序を保たないからである。したがって、接触の無い部分・回転差が正負四の二部分・残余を",
        "そのまま経路反転軌道の重みに使う経路は採用しない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の全非後退置換 ", math(String.raw`30{,}784`),
        " 個を厳密に列挙すると、接触の無い ", math(String.raw`49`), " 個は全て保たれた。一方、残余から位相反転部分へ ",
        math(String.raw`1{,}416`), " 個、残余から回転差 ", math(String.raw`-4`), " と ",
        math(String.raw`4`), " の部分へそれぞれ ", math(String.raw`384`), " 個と ",
        math(String.raw`520`), " 個が移った。位相反転部分から回転差 ", math(String.raw`-4`),
        " へ移るものも ", math(String.raw`136`), " 個あり、回転差 ", math(String.raw`-4`),
        " から ", math(String.raw`4`), " へ移るものは ", math(String.raw`1{,}548`),
        " 個あった（sagemath/check/path-reversal-standard-classification-counterexample）。",
        "これは一般の非保存定理ではなく、候補経路を排除する有限反例である。次は接触対の順序に依らない分類を構成する。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_weighted_path_reversal_selection_orbit_sums_sign_bijection_counterexample",
    targets: [
      "claim_path_reversal_fixed_point_no_single_traversal",
      "claim_weighted_path_reversal_selection_orbit_sums",
    ],
    title: { text: "経路反転軌道と選択補集合軌道の符号保存対応は存在しない" },
    body: [
      paragraph([
        "単純通過辺集合 ", math(String.raw`E`), " が空でなければ、経路反転軌道と選択補集合軌道は",
        "どちらも全て二元である。しかし、この元数の一致だけでは、両軌道族の間に符号を保つ全単射が存在するとは限らない。",
        "そのような全単射が存在すれば、各ファイバー・スピン構造・符号について、両側の元数は一致しなければならない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の ", math(String.raw`E\ne\varnothing`),
        " である全ファイバーを四つのスピン構造と二つの符号について厳密に列挙すると、符号別元数が一致しない組は ",
        math(String.raw`2{,}744`), " 件あった。置換側が ", math(String.raw`2`), " 元、選択側が ",
        math(String.raw`0`), " 元である最初の例は、反転対の辺集合 ",
        math(String.raw`D=\{h(1,1)\}`), "、単純通過辺集合 ",
        math(String.raw`E=\{v(0,0),v(0,1),v(1,0),v(1,1)\}`),
        "、スピン構造 ", math(String.raw`(a,b)=(0,0)`), "、符号 ", math(String.raw`+1`), " であった",
        "（sagemath/check/path-reversal-selection-sign-bijection-counterexample）。",
        "従って経路反転軌道全体と選択補集合軌道全体の間に符号と重みを保つ全単射を構成する経路は採用しない。",
        "符号付き総和の一致は、既存の切り替え平滑化による相殺を残したまま直接示す必要がある。",
        "これは一般の不存在定理ではなく、候補経路を排除する有限反例である。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_fully_unswitchable_contacts_witness_doubled_edges_fiber_phase_sums",
    targets: [
      "claim_fully_unswitchable_contacts_witness_doubled_edges",
      "claim_weighted_path_reversal_selection_orbit_sums",
    ],
    title: { text: "三分類の部分和はファイバー単位では選択和に一致しない" },
    body: [
      paragraph([
        "ファイバー位相和を順序に依らない三分類（接触なし・切り替え可能対あり・全対切り替え不能）の部分和 ",
        math(String.raw`S_Z,S_X,S_Y`),
        " へ分けると、既知のファイバー一致により各ファイバー・スピン構造で ",
        math(String.raw`S_Z+S_X+S_Y`), " は選択和 ", math(String.raw`U`),
        " に等しい。しかし各部分和が単独でファイバー単位に零（または ", math(String.raw`U`),
        "）になるとは限らない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の全 ", math(String.raw`609`),
        " ファイバーと四つのスピン構造の ", math(String.raw`2{,}436`),
        " 組を厳密に列挙すると、", math(String.raw`S_X\ne0`), " が ", math(String.raw`736`),
        " 組、", math(String.raw`S_Y\ne0`), " が ", math(String.raw`648`), " 組、",
        math(String.raw`S_Z\ne U`), " が ", math(String.raw`1{,}384`), " 組あった。",
        math(String.raw`S_Y\ne0`), " の最初の例は ", math(String.raw`D=\{v(0,1)\}`), "、",
        math(String.raw`E=\{h(0,1),h(1,1),v(0,0),v(1,1)\}`), "、",
        math(String.raw`(a,b)=(0,0)`), " で ", math(String.raw`S_Y=-2`), " である",
        "（sagemath/check/fully-unswitchable-fiber-phase-sums）。",
        "したがって、切り替え可能部分も全対切り替え不能な残余も、各部分を保つ固定ファイバー内の符号反転対合だけでは消えない。",
        "ただし、切り替え可能な接触の平滑化は ",
        ref("claim_switchable_contact_smoothing_preserves_fiber"), " により反転対の辺集合 ",
        math(String.raw`D`), " と単純通過の辺集合 ", math(String.raw`E`),
        " を保つ。この有限観察だけから、異なるファイバーを結ぶ縮約帰納の存在は従わない。",
        "この検算は有限集合の数え上げと ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_fully_unswitchable_contacts_witness_doubled_edges_splice_reduction_counterexample",
    targets: ["claim_fully_unswitchable_contacts_witness_doubled_edges"],
    title: { text: "反転対の二方向を巡回から抜く縮約候補は非後退性を保たない" },
    body: [
      paragraph([
        "完全切り替え不能な残余の各接触が指す反転対の辺について、その二方向を置換の巡回から同時に抜き、",
        "各方向の直前の辺を直後の辺へつないで、抜いた二方向を固定点へ戻す縮約候補を調べた。",
        "一辺 ", math(String.raw`L=2`), " で、同じ置換と同じ反転対の重複を除いた ",
        math(String.raw`2{,}912`), " 件の縮約後は全て置換だったが、非後退置換だったのは ",
        math(String.raw`32`), " 件だけであり、反転対の辺集合 ", math(String.raw`D`),
        " だけを一辺減らして単純通過の辺集合 ", math(String.raw`E`),
        " を保つものは一件も無かった（sagemath/check/doubled-edge-splice-reduction）。",
        "従ってこの直接除去は ", math(String.raw`|D|`),
        " に関する一段の縮約には使えない。別の局所操作か、個々の置換ではなくファイバー位相和どうしを結ぶ関係が必要である。",
        "検算は有限集合と有限写像の等号・所属判定だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_selection_sum_affine_character",
    targets: [
      "def_signed_selection_sum",
      "claim_selection_sum_signed_count",
      "claim_selection_even_subgraph_action_character",
      "claim_selection_even_subgraph_action_simply_transitive",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "選択集合は偶部分グラフの作用による文字和として扱える" },
    body: [
      paragraph([
        "互いに素な辺集合 ", math(String.raw`D,E\subseteq E_L`), " が ",
        math(String.raw`\operatorname{Even}_L(E)`), " を満たすとする。",
        "選択集合 ", math(String.raw`\mathcal C_L(D,E)`), " が空でなければ、",
        math(String.raw`E`), " に含まれる偶部分グラフ ", math(String.raw`H`),
        " は対称差 ", math(String.raw`C\mapsto C\mathbin\triangle H`),
        " によりこの選択集合へ単純推移的に作用する。この作用による選択符号の指数差は",
      ]),
      displayMath(String.raw`\vartheta^{a,b}_L(D,E;C\mathbin\triangle H)-\vartheta^{a,b}_L(D,E;C)
\equiv \varepsilon_{L,\mathrm h}(E)\varepsilon_{L,\mathrm v}(H)
+\varepsilon_{L,\mathrm v}(E)\varepsilon_{L,\mathrm h}(H)\pmod 2`),
      paragraph([
        "であり、右辺は ", math(String.raw`H`), " の文字である。選択集合が空なら選択和は零である。",
        "空でない場合、この文字が非自明なら選択和は零、",
        "自明なら全ての選択が同じ符号を持ち、選択和はその符号と選択集合の元数の積になる。",
        "一辺二の全ファイバーで、単純推移性・指数差・二場合の和を検査する",
        "（sagemath/check/selection-sum-affine-character）。これは選択和を三分類と独立な一つの文字和へまとめ、",
        "ファイバー位相和全体と直接比較する一般証明の部品になる。検算は有限集合、",
        math(String.raw`\mathbb F_2`), " の算術、", math(String.raw`\mathbb Z`),
        " の有限和だけで完結し、浮動小数点は使わない。作用が選択集合を保つことと指数差の文字は、",
        "一般の ", math(String.raw`L`),
        " で本文の主張（偶部分グラフの対称差は選択集合を保ち符号指数を文字だけ動かす）として示した。",
        "単純推移性と選択和の評価も一般の ", math(String.raw`L`),
        " で本文へ命題化した。これらの Lean 二版は未着手である。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_fully_unswitchable_contacts_witness_doubled_edges_same_support_aggregation",
    targets: ["claim_fully_unswitchable_contacts_witness_doubled_edges"],
    title: { text: "台固定の集約でも三分類の部分和は消えない（全分解の実現は成立）" },
    body: [
      paragraph([
        "選択和の側は偶部分グラフ対 ", math(String.raw`(P,Q)`), " の ",
        math(String.raw`P\cap Q=D`), "、", math(String.raw`P\triangle Q=E`),
        " による分類であり、和集合 ", math(String.raw`P\cup Q=D\cup E`),
        " はファイバーをまたいで共有される。そこで一辺 ", math(String.raw`L=2`),
        " の全ファイバーを台 ", math(String.raw`F=D\cup E`),
        " で束ね、ファイバーは保たず台だけを保つ相殺の単位が成立するかを調べた",
        "（sagemath/check/same-support-fiber-phase-sums）。",
        "台は ", math(String.raw`104`), " 個、四スピン構造で ", math(String.raw`416`),
        " 組である。まず、台の分解 ", math(String.raw`F=D\sqcup E`),
        "（", math(String.raw`E`), " は偶）のうち非後退置換が一つも無い分解は零件であり、",
        "一辺二では全ての分解がファイバーとして実現される。一方、台で集約した三分類の部分和は ",
        math(String.raw`\textstyle\sum S_X\ne0`), " が ", math(String.raw`132`), " 組、",
        math(String.raw`\textstyle\sum S_Y\ne0`), " が ", math(String.raw`248`), " 組、",
        math(String.raw`\textstyle\sum S_Z\ne\sum U`), " が ", math(String.raw`380`),
        " 組あった。従って、固定ファイバー内でも台固定の集約でも、切り替え可能部分と",
        "全対切り替え不能な残余は単独では消えず、分類を保つ符号反転対合は固定ファイバーまたは",
        "台固定の相殺単位では存在しない。一般の辺長の証明は、三分類を混ぜてファイバー位相和の全体と",
        "選択和を直接結ぶ数え上げとして構成する必要がある。",
        "検算は有限集合の数え上げと ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_sum_character_evaluation_fiber_phase_part_vanishing",
    targets: [
      "claim_selection_sum_character_evaluation",
      "claim_fully_unswitchable_contacts_witness_doubled_edges",
    ],
    title: { text: "文字による消滅は三分類の各部分ごとに成立する（一辺二の全数観察）" },
    body: [
      paragraph([
        "選択和の文字評価は、選択集合が空か文字が非自明なら選択和が零であることを与える。",
        "ファイバー位相和の側で同じ消滅がどの粒度で起きるかを、一辺 ",
        math(String.raw`L=2`), " の全ファイバー×四スピン構造の ", math(String.raw`2{,}436`),
        " 組で調べた（sagemath/check/fiber-phase-character-vanishing）。種別は、選択集合が空 ",
        math(String.raw`768`), " 組、文字が非自明 ", math(String.raw`192`),
        " 組、文字が自明 ", math(String.raw`1{,}476`), " 組である。",
        "空と非自明文字の全 ", math(String.raw`960`),
        " 組で、三分類（接触なし・切り替え可能対あり・全対切り替え不能）の部分和 ",
        math(String.raw`S_Z,S_X,S_Y`),
        " は全て個別に零であり、非零の部分和は自明文字の組にしか現れない（",
        math(String.raw`S_Z\ne0`), " が ", math(String.raw`92`), " 組、",
        math(String.raw`S_X\ne0`), " が ", math(String.raw`736`), " 組、",
        math(String.raw`S_Y\ne0`), " が ", math(String.raw`648`), " 組）。",
        "従って一辺二では、文字が強制する ", math(String.raw`\mathcal K^{a,b}_L(D,E)=0`),
        " は三分類の各部分ごとに成立しており、一般の辺長でこの消滅を示す文字和・符号反転構造は",
        "部分ごとに探してよい。一方、自明文字の組では ", math(String.raw`S_Z=U`),
        " が ", math(String.raw`1{,}384`),
        " 組で破れるため、非零の値の同定は三分類を混ぜた全体で行う。",
        "検算は ", math(String.raw`\mathbb Z`), " と ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_oriented_edge_conjugation_counterexample",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_path_reversal_fiber_preserving_involution",
    ],
    title: { text: "偶部分グラフ上の向き反転共役は置換側の文字作用にならない（一辺二の全数反例）" },
    body: [
      paragraph([
        "単純通過辺集合 ", math(String.raw`E`), " に含まれる偶部分グラフ ",
        math(String.raw`H`), " に対し、", math(String.raw`H`),
        " の各辺で二つの向きだけを交換する対合を ", math(String.raw`\rho_H`),
        " とする。選択側の対称差作用に対応する最も直接的な候補として、置換を ",
        math(String.raw`\rho_H\circ\varphi\circ\rho_H`),
        " へ送る共役を一辺二で全数検査した（sagemath/check/even-subgraph-oriented-edge-conjugation）。",
        "全 ", math(String.raw`78{,}752`), " 組で反転対辺集合 ", math(String.raw`D`),
        " と単純通過辺集合 ", math(String.raw`E`), " は保たれたが、",
        math(String.raw`43{,}664`), " 組で非後退性が壊れた。非後退性を保った像でも、期待する文字と",
        "位相寄与の比が一致しないものが四スピン構造を合わせて ", math(String.raw`7{,}680`),
        " 件あった。従って、この共役は空・非自明文字のファイバー位相和を消す作用には使わない。",
        "次は向き付き辺を個別に反転するのではなく、各頂点の入出接続を偶部分グラフに沿って",
        "組み替える作用を調べる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_vertex_rewiring_counterexample",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "頂点の入出接続の組み替えも一様な文字作用にならない（一辺二の全数反例）" },
    body: [
      paragraph([
        "向き付き辺の個別反転の次の候補として、単純通過辺集合 ", math(String.raw`E`),
        " に含まれる偶部分グラフ ", math(String.raw`H`),
        " に沿って各頂点の入出接続を組み替える族を一辺二で全数検査した",
        "（sagemath/check/even-subgraph-vertex-rewiring）。",
        math(String.raw`H`), " の外どうしの遷移は保ち、", math(String.raw`H`),
        " 上の歩道の向き付き辺は全て逆向きへ差し替え、各頂点で残った到着と出発を",
        "直ちに引き返さない任意の全単射で結び直す。巻き付き文字が非自明（",
        math(String.raw`\chi_E(H)=-1`), "）な全 ", math(String.raw`13{,}568`),
        " 組で、各頂点の残った到着と出発の個数は常に釣り合い、非後退置換になる結び直しが",
        "常に存在した（候補総数 ", math(String.raw`38{,}016`),
        "）。しかし四スピン構造すべてで位相寄与の比が ", math(String.raw`-1`),
        " になる候補を持つ組は ", math(String.raw`11{,}904`), " に留まり、",
        math(String.raw`1{,}664`), " 組ではどの候補も位相比 ", math(String.raw`-1`),
        " を実現しない。最初の例は ", math(String.raw`D=\varnothing`), "、",
        math(String.raw`E=\{h(1,0),h(1,1),v(0,1),v(1,1)\}`), "、",
        math(String.raw`H=\{h(1,0),h(1,1)\}`),
        " である。従って、固定した ", math(String.raw`H`),
        " に対する置換ごとの局所的な組み替えでは一様な文字作用は構成できない。",
        "次は、置換ごとに組み替えに使う偶部分グラフを変える割り当て、",
        "または軌道構造まで使う大域的な対応を調べる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
]);
