/**
 * 章「トーラス上の Kac--Ward 行列式」に紐づく検算・観察ノート。
 * 検算は証明ではなく、一般化できない有限標本を本文へ混ぜない。
 */

import { defineNotes, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineNotes([
  {
    id: "note_kac_ward_definition_determinants_even_subgraph_square_observation",
    targets: ["def_kac_ward_determinants"],
    title: { text: "行列式は符号付き偶部分グラフ多項式の平方（観察と経路の確定）" },
    body: [
      paragraph([
        "検証水準の計算として、一辺 ", math(String.raw`L=2,3`),
        " の周期正方格子で四つの Kac--Ward 行列式 ",
        math(String.raw`\det\bigl(I-x\,M^{a,b}\bigr)`),
        " を円分体 ", math(String.raw`\mathbb Q(\zeta_8)`),
        " 係数の多項式として厳密に計算し、全頂点の次数が偶数である台の辺の部分集合",
        "（偶部分グラフ）", math(String.raw`A`), " の切断線偶奇 ",
        math(String.raw`(h(A),v(A))`), " に符号 ",
        math(String.raw`(-1)^{c\,h+d\,v+e\,hv}`), "（", math(String.raw`c,d,e\in\{0,1\}`),
        " の全 8 候補）を付けた多項式の平方と比較した",
        "（sagemath/check/torus-kac-ward-even-subgraph-square）。",
      ]),
      paragraph([
        "結果、四つのスピン構造すべてで等式",
      ]),
      displayMath(String.raw`\det\bigl(I-x\,M^{a,b}\bigr)
=\Bigl(\sum_{A}(-1)^{(1+a)h(A)+(1+b)v(A)+h(A)v(A)}\,x^{|A|}\Bigr)^{2}`),
      paragraph([
        "が成り立った。スピン構造 ", math(String.raw`(0,1)`), " と ",
        math(String.raw`(1,0)`), " では二つの符号候補の平方が一致するが、これは正方トーラスの",
        "軸対称によりホモロジー類 ", math(String.raw`(1,0)`), " と ",
        math(String.raw`(0,1)`),
        " の類別和が多項式として一致するためで、等式の一意性とは矛盾しない。",
      ]),
      paragraph([
        "この観察により、一般の ", math(String.raw`L`), " で証明すべき候補は",
        "「行列式＝符号付き偶部分グラフ多項式の平方」という行列式レベルの恒等式である。",
        "ただし多項式全体の一致だけから、置換展開の個々の両向き項が相殺するか、平方の交差項へ",
        "どのように対応するかは決まらない。この項ごとの対応は一般の恒等式の証明で別に示す必要がある。",
        "反復分解（接触対数の整礎帰納）は、この恒等式の証明の中で各閉路の回転位相符号を",
        "確定するために使う。これは有限標本（", math(String.raw`L=2,3`),
        "）の観察であり、一般の ", math(String.raw`L`), " についてはまだ何も証明していない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_definition_cyclic_total_turning_vertex_simple_observation",
    targets: ["def_cyclic_total_turning"],
    title: { text: "頂点単純閉路の循環総回転数（証明前の有限標本観察）" },
    body: [
      paragraph([
        "検証水準の計算として、一辺 ", math(String.raw`L=2,3,4`),
        " の周期正方格子で、通過の頂点が相異なる（接触対数零の）閉じた非後退辺列を",
        "全列挙し（基点と向きを区別した数え上げで全 ", math(String.raw`373{,}716`),
        " 本）、循環総回転数 ", math(String.raw`t_{\circ}(\gamma)`),
        " と切断線偶奇 ", math(String.raw`(h(\gamma)\bmod2,\ v(\gamma)\bmod2)`),
        " を突き合わせた（sagemath/check/vertex-simple-cycle-turning）。",
      ]),
      paragraph([
        "結果、次の離散 Whitney の言明が例外なく成り立った。切断線偶奇が ",
        math(String.raw`(0,0)`), " の頂点単純閉路（", math(String.raw`73{,}616`),
        " 本）は ", math(String.raw`t_{\circ}(\gamma)\in\{+4,-4\}`),
        "。切断線偶奇が ", math(String.raw`(0,0)`), " 以外の頂点単純閉路（",
        math(String.raw`300{,}100`), " 本）は ", math(String.raw`t_{\circ}(\gamma)=0`),
        "。この観察は本文の「頂点単純閉路の循環総回転数は切断線偶奇で決まる」で",
        "一般の一辺長について証明済みである。",
      ]),
      paragraph([
        "整数巻き付きベクトルが零の場合は、本文の平面持ち上げと有限セルの二重計数により一般の ",
        math(String.raw`L`), " で ", math(String.raw`t_{\circ}(\gamma)\in\{+4,-4\}`),
        " が証明された。したがって、この場合の回転位相は ",
        math(String.raw`\zeta_8^{\,t_{\circ}(\gamma)}=-1`),
        " である。零でない原始的巻き付きの場合の ",
        math(String.raw`t_{\circ}(\gamma)=0`), " と回転位相 ",
        math(String.raw`+1`),
        " も周期単純路の一側閉包と三周期比較により証明済みである。有限標本（",
        math(String.raw`L=2,3,4`), "）の観察は証明された二場合の両方を検査している。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_parallel_separated_staircases_direct_closure_counterexample",
    targets: ["claim_parallel_separated_staircases_disjoint"],
    title: { text: "二本の反復横断階段を対応点へ結ぶ直接閉包は単純にならない" },
    body: [
      paragraph([
        "周期持ち上げの一周期分と、その横断平行移動を、両端から出した同じ反復横断階段で結ぶ候補は、",
        "既存の分離補題だけでは単純閉路にならない。反例は一辺 ", math(String.raw`L=2`),
        " のトーラス上の頂点列 ",
        math(String.raw`((0,0),(0,1),(1,1),(1,0),(0,0))`),
        " である。この閉路の平面持ち上げの一周期分は",
      ]),
      displayMath(String.raw`(0,0),(0,1),(1,1),(1,0),(2,0)`),
      paragraph([
        "となり、巻き付き数は ", math(String.raw`(w_{\mathrm h},w_{\mathrm v})=(0,1)`),
        "、正の横断階段は左向きである。横断幅を超える二回の平行移動で直接閉包すると、",
        "合成列には、左側の接続階段と平行移動後の持ち上げの交点 ", math(String.raw`(0,-1)`),
        " が二度現れる。したがって「二つの周期持ち上げが互いに交わらないこと」と",
        "「二本の階段が互いに交わらないこと」だけでは、階段と反対側の持ち上げとの交差を排除できない。",
      ]),
      paragraph([
        "この候補は採用しない。閉包を完成させるには、反対側の持ち上げも終点以外で避ける接続路を別に構成し、",
        "その後に四つの部分の交差を組ごとに検査する必要がある。反例は整数格子の有限列だけで完結し、",
        "実数体も複素数体も用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_periodic_lift_closure_turning_difference_cancellation",
    targets: ["def_periodic_lift_closure_cycle", "def_cyclic_total_turning"],
    title: { text: "周期数を増やした閉包の回転数差では持ち上げの回転数を取り出せない" },
    body: [
      paragraph([
        "周期数 ", math(String.raw`c`), " の閉包と周期数 ", math(String.raw`c+1`),
        " の閉包の循環総回転数を比較する候補は採用しない。接続階段の向きの有限語を ",
        math(String.raw`A`), "、周期持ち上げ一周期分の向きの巡回語を ", math(String.raw`P`),
        " とし、向きを全て反転して順序を逆にした語をそれぞれ ",
        math(String.raw`\overline A,\overline P`), " と書く。閉包の向きの巡回語は、",
      ]),
      displayMath(String.raw`A\,P^{c}\,\overline A\,\overline P^{c}`),
      paragraph([
        "の形である。周期数を一つ増やすと、順向きの周期語 ", math(String.raw`P`),
        " と逆向きの周期語 ", math(String.raw`\overline P`),
        " が一つずつ同時に挿入される。巡回語の回転数和を ", math(String.raw`T`),
        " と書くと、巡回の開始位置をずらしても有限和は変わらず、逆向きでは各回転の符号が反転するので",
      ]),
      displayMath(String.raw`T(P)+T(\overline P)=T(P)-T(P)=0`),
      paragraph([
        "となる。したがって閉包の循環総回転数の差は、元の ", math(String.raw`T(P)`),
        " の値にかかわらず零であり、この差から ", math(String.raw`T(P)=0`),
        " を導くことはできない。SageMath の有限全列挙でも、一辺 ", math(String.raw`L=1,2,3`),
        " の全対象について周期数 ", math(String.raw`c=1,2,3`),
        " の閉包の循環総回転数が一致し、追加された順向き・逆向きの一周期の和が零になることを整数だけで確認した",
        "（sagemath/check/periodic-lift-closure-cycle）。次は、逆向きの周期持ち上げを同時に追加しない一側閉包を構成し、",
        "周期数の差に一周期分だけが残る形へ変える必要がある。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_doubled_edge_fiber_phase_reduction_unlocked_residual_noncancellation",
    targets: ["claim_doubled_edge_fiber_phase_reduction", "def_unswitchable_standard_pair_subset"],
    title: { text: "切り替え可能接触を持つ残余は符号反転対合で相殺できない" },
    body: [
      paragraph([
        "標準対が切り替え不能な残余 ", math(String.raw`\mathcal R_L`),
        " のうち、別の切り替え可能な接触対を持つ部分について、平滑化と両立する接触対の選択規則を",
        "作って符号反転対合で相殺する候補は採用しない。理由は二つある。第一に、切り替え可能な接触対の",
        "辞書式最小を選ぶ規則は平滑化と両立しない。一辺 ", math(String.raw`L=2`),
        " のこの部分 ", math(String.raw`17{,}925`), " 個を厳密に列挙したところ、辞書式最小の",
        "切り替え可能対での平滑化が標準対を切り替え可能へ変えて残余から出すものが ",
        math(String.raw`4{,}638`), " 個、平滑化後に辞書式最小の切り替え可能対が変わるものが ",
        math(String.raw`7{,}935`), " 個あった。",
      ]),
      paragraph([
        "第二に、選択規則の作り方に依らず、相殺そのものが不可能である。ファイバーを保ち",
        "位相寄与の符号を反転する不動点の無い対合がこの部分の上に存在すれば、その位相寄与の総和は",
        "各ファイバー×スピン構造で零になるはずである。ところが一辺 ", math(String.raw`L=2`),
        " の厳密和は、この部分が空でない ", math(String.raw`1{,}288`), " 組中 ",
        math(String.raw`380`), " 組で非零であり、残余 ", math(String.raw`\mathcal R_L`),
        " 全体の総和も ", math(String.raw`1{,}028`), " 組で非零である",
        "（sagemath/check/unlocked-residual-phase-noncancellation）。したがって残余は相殺の対象ではなく、",
        "回転差が正負四の二集合と合わせて、符号付き偶部分グラフ多項式の平方の項と数え上げで",
        "対応づけるべき寄与として扱う。この検算は有限集合の比較と円分体 ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の厳密和だけで完結し、実数体は用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_def_fiber_phase_weight_signed_selection_sum_fiberwise_equality",
    targets: ["def_fiber_phase_weight", "def_signed_selection_sum"],
    title: { text: "一辺二では置換ファイバー位相和と偶部分グラフ選択和が添字ごとに一致する" },
    body: [
      paragraph([
        "一般の平方恒等式で目標にすべき対応を確定するため、一辺 ", math(String.raw`L=2`),
        " の全非後退置換を反転対の辺集合 ", math(String.raw`D`), " と単純通過の辺集合 ",
        math(String.raw`E`), " で層別し、置換側の位相和 ",
        math(String.raw`\mathcal K^{a,b}_L(D,E)`), " と偶部分グラフ対側の符号付き選択和 ",
        math(String.raw`\mathcal U^{a,b}_L(D,E)`), " を定義から直接比較した。全 ",
        math(String.raw`609`), " ファイバーと四つのスピン構造、合計 ",
        math(String.raw`2{,}436`), " 件で",
      ]),
      displayMath(String.raw`\mathcal K^{a,b}_L(D,E)=\mathcal U^{a,b}_L(D,E)`),
      paragraph([
        "が成立した（sagemath/check/kac-ward-fiber-signed-selection-equality）。したがって、",
        "多項式全体の係数をまとめて比較するだけでなく、接触の無い置換、回転差が正負四の置換、",
        "残余を合わせた位相和を、同じ ", math(String.raw`(D,E)`),
        " の選択集合と数え上げで対応づければ平方恒等式へ合成できる。これは一般の ",
        math(String.raw`L`), " に対する証明ではなく、次に構成すべきファイバーごとの全単射または",
        "符号付き数え上げの目標を固定する厳密観察である。計算は有限集合、整数、円分体 ",
        math(String.raw`\mathbb Q(\zeta_8)`), " だけで閉じ、実数体は用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_def_fiber_phase_weight_signed_selection_sum_part_decomposition",
    targets: ["def_fiber_phase_weight", "def_signed_selection_sum"],
    title: { text: "一辺二では簡約四部分の位相和がすべて有理整数に落ち回転差二部分は相等である" },
    body: [
      paragraph([
        "一般の数え上げの形を絞るため、一辺 ", math(String.raw`L=2`),
        " の各ファイバー位相和を、位相反転部分集合 ", math(String.raw`\mathcal B_L`),
        " の零和で簡約した後に残る四部分（接触の無い置換、回転差 ", math(String.raw`-4`),
        " の置換、回転差 ", math(String.raw`4`), " の置換、残余 ", math(String.raw`\mathcal R_L`),
        "）へ分解し、全 ", math(String.raw`609`), " ファイバー×四スピン構造 ",
        math(String.raw`2{,}436`), " 組で各部分の位相和を ",
        math(String.raw`\mathbb Q(\zeta_8)`),
        " の厳密和として計算した（sagemath/check/kac-ward-fiber-phase-part-decomposition）。",
        "三つの観察を得た。第一に、四部分の位相和 ", math(String.raw`2{,}436\times4`),
        " 個はすべて有理整数に落ちた。第二に、回転差 ", math(String.raw`-4`), " と ",
        math(String.raw`4`), " の二部分の位相和は全組で互いに等しかった",
        "（標準対平滑化が両集合を交換し位相寄与を保存することと整合する）。",
        "第三に、接触の無い部分だけで ", math(String.raw`\mathcal U^{a,b}_L(D,E)`),
        " に一致するのは ", math(String.raw`1{,}052`), " 組に留まり、残余の位相和が非零の ",
        math(String.raw`1{,}028`), " 組と回転差二部分の和が非零の ", math(String.raw`464`),
        " 組が残りを埋めた。したがって一般の ", math(String.raw`L`),
        " で立てるべき言明は、円分体の値ではなく整数値の三つの符号付き数え上げ",
        "（接触の無い部分、回転差 ", math(String.raw`4`),
        " の部分の二倍、残余）の和が ", math(String.raw`\mathcal U^{a,b}_L(D,E)`),
        " に等しい、という形になる。これは一般の証明ではなく目標の形を固定する厳密観察である。",
        "計算は有限集合、整数、円分体だけで閉じ、実数体は用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_contact_smoothing_same_pair_involution_lexicographic_choice_counterexample",
    targets: ["claim_contact_smoothing_same_pair_involution"],
    title: { text: "辞書式最小の切り替え可能接触対は平滑化で保たれない" },
    body: [
      paragraph([
        "切り替え可能な接触対全体を向き付き辺の固定した辞書式順序で並べ、最小の対を選ぶ規則は、",
        "符号反転対合の標準対として採用しない。同じ対での平滑化は対合であるが、平滑化によって",
        "その対と一辺だけを共有する別の接触対の切り替え可能性が変わり得るため、最小の対そのものは保存されない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の全非後退置換 ", math(String.raw`30{,}784`),
        " 個を厳密に列挙したところ、切り替え可能な接触対を持つ置換は ", math(String.raw`29{,}905`),
        " 個あり、そのうち ", math(String.raw`7{,}935`),
        " 個で、辞書式最小対による平滑化の前後に選ばれる対が異なった",
        "（sagemath/check/lexicographic-switchable-contact-choice-counterexample）。",
        "したがって、次に定める標準対は単なる最小化ではなく、平滑化の前後で同じ局所データを選ぶ規則でなければならない。",
        "この検算は有限集合の比較だけで完結し、実数体も複素数体も用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_path_reversal_contact_pair_preservation_standard_classification_counterexample",
    targets: [
      "claim_path_reversal_contact_pair_preservation",
      "def_standard_turning_difference_subsets",
      "def_unswitchable_standard_pair_subset",
    ],
    title: { text: "標準接触対に依存する分類は経路反転で保たれない" },
    body: [
      paragraph([
        "接触対全体の全単射と各接触対の切り替え可能性の保存から、固定した辞書式順序で選ぶ標準接触対に",
        "依存する分類まで保存されるとは限らない。経路反転が誘導する全単射 ",
        math(String.raw`\Psi_{\varphi}`),
        " は接触対の辞書式順序を保たないからである。したがって、接触の無い部分・回転差が正負四の二部分・残余を",
        "そのまま経路反転軌道の重みに使う経路は採用しない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の全非後退置換 ", math(String.raw`30{,}784`),
        " 個を厳密に列挙すると、接触の無い ", math(String.raw`49`), " 個は全て保たれた。一方、残余から位相反転部分へ ",
        math(String.raw`1{,}416`), " 個、残余から回転差 ", math(String.raw`-4`), " と ",
        math(String.raw`4`), " の部分へそれぞれ ", math(String.raw`384`), " 個と ",
        math(String.raw`520`), " 個が移った。位相反転部分から回転差 ", math(String.raw`-4`),
        " へ移るものも ", math(String.raw`136`), " 個あり、回転差 ", math(String.raw`-4`),
        " から ", math(String.raw`4`), " へ移るものは ", math(String.raw`1{,}548`),
        " 個あった（sagemath/check/path-reversal-standard-classification-counterexample）。",
        "これは一般の非保存定理ではなく、候補経路を排除する有限反例である。次は接触対の順序に依らない分類を構成する。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_weighted_path_reversal_selection_orbit_sums_sign_bijection_counterexample",
    targets: [
      "claim_path_reversal_fixed_point_no_single_traversal",
      "claim_weighted_path_reversal_selection_orbit_sums",
    ],
    title: { text: "経路反転軌道と選択補集合軌道の符号保存対応は存在しない" },
    body: [
      paragraph([
        "単純通過辺集合 ", math(String.raw`E`), " が空でなければ、経路反転軌道と選択補集合軌道は",
        "どちらも全て二元である。しかし、この元数の一致だけでは、両軌道族の間に符号を保つ全単射が存在するとは限らない。",
        "そのような全単射が存在すれば、各ファイバー・スピン構造・符号について、両側の元数は一致しなければならない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の ", math(String.raw`E\ne\varnothing`),
        " である全ファイバーを四つのスピン構造と二つの符号について厳密に列挙すると、符号別元数が一致しない組は ",
        math(String.raw`2{,}744`), " 件あった。置換側が ", math(String.raw`2`), " 元、選択側が ",
        math(String.raw`0`), " 元である最初の例は、反転対の辺集合 ",
        math(String.raw`D=\{h(1,1)\}`), "、単純通過辺集合 ",
        math(String.raw`E=\{v(0,0),v(0,1),v(1,0),v(1,1)\}`),
        "、スピン構造 ", math(String.raw`(a,b)=(0,0)`), "、符号 ", math(String.raw`+1`), " であった",
        "（sagemath/check/path-reversal-selection-sign-bijection-counterexample）。",
        "従って経路反転軌道全体と選択補集合軌道全体の間に符号と重みを保つ全単射を構成する経路は採用しない。",
        "符号付き総和の一致は、既存の切り替え平滑化による相殺を残したまま直接示す必要がある。",
        "これは一般の不存在定理ではなく、候補経路を排除する有限反例である。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_fully_unswitchable_contacts_witness_doubled_edges_fiber_phase_sums",
    targets: [
      "claim_fully_unswitchable_contacts_witness_doubled_edges",
      "claim_weighted_path_reversal_selection_orbit_sums",
    ],
    title: { text: "三分類の部分和はファイバー単位では選択和に一致しない" },
    body: [
      paragraph([
        "ファイバー位相和を順序に依らない三分類（接触なし・切り替え可能対あり・全対切り替え不能）の部分和 ",
        math(String.raw`S_Z,S_X,S_Y`),
        " へ分けると、既知のファイバー一致により各ファイバー・スピン構造で ",
        math(String.raw`S_Z+S_X+S_Y`), " は選択和 ", math(String.raw`U`),
        " に等しい。しかし各部分和が単独でファイバー単位に零（または ", math(String.raw`U`),
        "）になるとは限らない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の全 ", math(String.raw`609`),
        " ファイバーと四つのスピン構造の ", math(String.raw`2{,}436`),
        " 組を厳密に列挙すると、", math(String.raw`S_X\ne0`), " が ", math(String.raw`736`),
        " 組、", math(String.raw`S_Y\ne0`), " が ", math(String.raw`648`), " 組、",
        math(String.raw`S_Z\ne U`), " が ", math(String.raw`1{,}384`), " 組あった。",
        math(String.raw`S_Y\ne0`), " の最初の例は ", math(String.raw`D=\{v(0,1)\}`), "、",
        math(String.raw`E=\{h(0,1),h(1,1),v(0,0),v(1,1)\}`), "、",
        math(String.raw`(a,b)=(0,0)`), " で ", math(String.raw`S_Y=-2`), " である",
        "（sagemath/check/fully-unswitchable-fiber-phase-sums）。",
        "したがって、切り替え可能部分も全対切り替え不能な残余も、各部分を保つ固定ファイバー内の符号反転対合だけでは消えない。",
        "ただし、切り替え可能な接触の平滑化は ",
        ref("claim_switchable_contact_smoothing_preserves_fiber"), " により反転対の辺集合 ",
        math(String.raw`D`), " と単純通過の辺集合 ", math(String.raw`E`),
        " を保つ。この有限観察だけから、異なるファイバーを結ぶ縮約帰納の存在は従わない。",
        "この検算は有限集合の数え上げと ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_fully_unswitchable_contacts_witness_doubled_edges_splice_reduction_counterexample",
    targets: ["claim_fully_unswitchable_contacts_witness_doubled_edges"],
    title: { text: "反転対の二方向を巡回から抜く縮約候補は非後退性を保たない" },
    body: [
      paragraph([
        "完全切り替え不能な残余の各接触が指す反転対の辺について、その二方向を置換の巡回から同時に抜き、",
        "各方向の直前の辺を直後の辺へつないで、抜いた二方向を固定点へ戻す縮約候補を調べた。",
        "一辺 ", math(String.raw`L=2`), " で、同じ置換と同じ反転対の重複を除いた ",
        math(String.raw`2{,}912`), " 件の縮約後は全て置換だったが、非後退置換だったのは ",
        math(String.raw`32`), " 件だけであり、反転対の辺集合 ", math(String.raw`D`),
        " だけを一辺減らして単純通過の辺集合 ", math(String.raw`E`),
        " を保つものは一件も無かった（sagemath/check/doubled-edge-splice-reduction）。",
        "従ってこの直接除去は ", math(String.raw`|D|`),
        " に関する一段の縮約には使えない。別の局所操作か、個々の置換ではなくファイバー位相和どうしを結ぶ関係が必要である。",
        "検算は有限集合と有限写像の等号・所属判定だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_selection_sum_affine_character",
    targets: [
      "def_signed_selection_sum",
      "claim_selection_sum_signed_count",
      "claim_selection_even_subgraph_action_character",
      "claim_selection_even_subgraph_action_simply_transitive",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "選択集合は偶部分グラフの作用による文字和として扱える" },
    body: [
      paragraph([
        "互いに素な辺集合 ", math(String.raw`D,E\subseteq E_L`), " が ",
        math(String.raw`\operatorname{Even}_L(E)`), " を満たすとする。",
        "選択集合 ", math(String.raw`\mathcal C_L(D,E)`), " が空でなければ、",
        math(String.raw`E`), " に含まれる偶部分グラフ ", math(String.raw`H`),
        " は対称差 ", math(String.raw`C\mapsto C\mathbin\triangle H`),
        " によりこの選択集合へ単純推移的に作用する。この作用による選択符号の指数差は",
      ]),
      displayMath(String.raw`\vartheta^{a,b}_L(D,E;C\mathbin\triangle H)-\vartheta^{a,b}_L(D,E;C)
\equiv \varepsilon_{L,\mathrm h}(E)\varepsilon_{L,\mathrm v}(H)
+\varepsilon_{L,\mathrm v}(E)\varepsilon_{L,\mathrm h}(H)\pmod 2`),
      paragraph([
        "であり、右辺は ", math(String.raw`H`), " の文字である。選択集合が空なら選択和は零である。",
        "空でない場合、この文字が非自明なら選択和は零、",
        "自明なら全ての選択が同じ符号を持ち、選択和はその符号と選択集合の元数の積になる。",
        "一辺二の全ファイバーで、単純推移性・指数差・二場合の和を検査する",
        "（sagemath/check/selection-sum-affine-character）。これは選択和を三分類と独立な一つの文字和へまとめ、",
        "ファイバー位相和全体と直接比較する一般証明の部品になる。検算は有限集合、",
        math(String.raw`\mathbb F_2`), " の算術、", math(String.raw`\mathbb Z`),
        " の有限和だけで完結し、浮動小数点は使わない。作用が選択集合を保つことと指数差の文字は、",
        "一般の ", math(String.raw`L`),
        " で本文の主張（偶部分グラフの対称差は選択集合を保ち符号指数を文字だけ動かす）として示した。",
        "単純推移性と選択和の評価も一般の ", math(String.raw`L`),
        " で本文へ命題化した。これらの Lean 二版は未着手である。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_fully_unswitchable_contacts_witness_doubled_edges_same_support_aggregation",
    targets: ["claim_fully_unswitchable_contacts_witness_doubled_edges"],
    title: { text: "台固定の集約でも三分類の部分和は消えない（全分解の実現は成立）" },
    body: [
      paragraph([
        "選択和の側は偶部分グラフ対 ", math(String.raw`(P,Q)`), " の ",
        math(String.raw`P\cap Q=D`), "、", math(String.raw`P\triangle Q=E`),
        " による分類であり、和集合 ", math(String.raw`P\cup Q=D\cup E`),
        " はファイバーをまたいで共有される。そこで一辺 ", math(String.raw`L=2`),
        " の全ファイバーを台 ", math(String.raw`F=D\cup E`),
        " で束ね、ファイバーは保たず台だけを保つ相殺の単位が成立するかを調べた",
        "（sagemath/check/same-support-fiber-phase-sums）。",
        "台は ", math(String.raw`104`), " 個、四スピン構造で ", math(String.raw`416`),
        " 組である。まず、台の分解 ", math(String.raw`F=D\sqcup E`),
        "（", math(String.raw`E`), " は偶）のうち非後退置換が一つも無い分解は零件であり、",
        "一辺二では全ての分解がファイバーとして実現される。一方、台で集約した三分類の部分和は ",
        math(String.raw`\textstyle\sum S_X\ne0`), " が ", math(String.raw`132`), " 組、",
        math(String.raw`\textstyle\sum S_Y\ne0`), " が ", math(String.raw`248`), " 組、",
        math(String.raw`\textstyle\sum S_Z\ne\sum U`), " が ", math(String.raw`380`),
        " 組あった。従って、固定ファイバー内でも台固定の集約でも、切り替え可能部分と",
        "全対切り替え不能な残余は単独では消えず、分類を保つ符号反転対合は固定ファイバーまたは",
        "台固定の相殺単位では存在しない。一般の辺長の証明は、三分類を混ぜてファイバー位相和の全体と",
        "選択和を直接結ぶ数え上げとして構成する必要がある。",
        "検算は有限集合の数え上げと ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_sum_character_evaluation_fiber_phase_part_vanishing",
    targets: [
      "claim_selection_sum_character_evaluation",
      "claim_fully_unswitchable_contacts_witness_doubled_edges",
    ],
    title: { text: "文字による消滅は三分類の各部分ごとに成立する（一辺二の全数観察）" },
    body: [
      paragraph([
        "選択和の文字評価は、選択集合が空か文字が非自明なら選択和が零であることを与える。",
        "ファイバー位相和の側で同じ消滅がどの粒度で起きるかを、一辺 ",
        math(String.raw`L=2`), " の全ファイバー×四スピン構造の ", math(String.raw`2{,}436`),
        " 組で調べた（sagemath/check/fiber-phase-character-vanishing）。種別は、選択集合が空 ",
        math(String.raw`768`), " 組、文字が非自明 ", math(String.raw`192`),
        " 組、文字が自明 ", math(String.raw`1{,}476`), " 組である。",
        "空と非自明文字の全 ", math(String.raw`960`),
        " 組で、三分類（接触なし・切り替え可能対あり・全対切り替え不能）の部分和 ",
        math(String.raw`S_Z,S_X,S_Y`),
        " は全て個別に零であり、非零の部分和は自明文字の組にしか現れない（",
        math(String.raw`S_Z\ne0`), " が ", math(String.raw`92`), " 組、",
        math(String.raw`S_X\ne0`), " が ", math(String.raw`736`), " 組、",
        math(String.raw`S_Y\ne0`), " が ", math(String.raw`648`), " 組）。",
        "従って一辺二では、文字が強制する ", math(String.raw`\mathcal K^{a,b}_L(D,E)=0`),
        " は三分類の各部分ごとに成立しており、一般の辺長でこの消滅を示す文字和・符号反転構造は",
        "部分ごとに探してよい。一方、自明文字の組では ", math(String.raw`S_Z=U`),
        " が ", math(String.raw`1{,}384`),
        " 組で破れるため、非零の値の同定は三分類を混ぜた全体で行う。",
        "検算は ", math(String.raw`\mathbb Z`), " と ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_oriented_edge_conjugation_counterexample",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_path_reversal_fiber_preserving_involution",
    ],
    title: { text: "偶部分グラフ上の向き反転共役は置換側の文字作用にならない（一辺二の全数反例）" },
    body: [
      paragraph([
        "単純通過辺集合 ", math(String.raw`E`), " に含まれる偶部分グラフ ",
        math(String.raw`H`), " に対し、", math(String.raw`H`),
        " の各辺で二つの向きだけを交換する対合を ", math(String.raw`\rho_H`),
        " とする。選択側の対称差作用に対応する最も直接的な候補として、置換を ",
        math(String.raw`\rho_H\circ\varphi\circ\rho_H`),
        " へ送る共役を一辺二で全数検査した（sagemath/check/even-subgraph-oriented-edge-conjugation）。",
        "全 ", math(String.raw`78{,}752`), " 組で反転対辺集合 ", math(String.raw`D`),
        " と単純通過辺集合 ", math(String.raw`E`), " は保たれたが、",
        math(String.raw`43{,}664`), " 組で非後退性が壊れた。非後退性を保った像でも、期待する文字と",
        "位相寄与の比が一致しないものが四スピン構造を合わせて ", math(String.raw`7{,}680`),
        " 件あった。従って、この共役は空・非自明文字のファイバー位相和を消す作用には使わない。",
        "次は向き付き辺を個別に反転するのではなく、各頂点の入出接続を偶部分グラフに沿って",
        "組み替える作用を調べる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_vertex_rewiring_counterexample",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "頂点の入出接続の組み替えも一様な文字作用にならない（一辺二の全数反例）" },
    body: [
      paragraph([
        "向き付き辺の個別反転の次の候補として、単純通過辺集合 ", math(String.raw`E`),
        " に含まれる偶部分グラフ ", math(String.raw`H`),
        " に沿って各頂点の入出接続を組み替える族を一辺二で全数検査した",
        "（sagemath/check/even-subgraph-vertex-rewiring）。",
        math(String.raw`H`), " の外どうしの遷移は保ち、", math(String.raw`H`),
        " 上の歩道の向き付き辺は全て逆向きへ差し替え、各頂点で残った到着と出発を",
        "直ちに引き返さない任意の全単射で結び直す。巻き付き文字が非自明（",
        math(String.raw`\chi_E(H)=-1`), "）な全 ", math(String.raw`13{,}568`),
        " 組で、各頂点の残った到着と出発の個数は常に釣り合い、非後退置換になる結び直しが",
        "常に存在した（候補総数 ", math(String.raw`38{,}016`),
        "）。しかし四スピン構造すべてで位相寄与の比が ", math(String.raw`-1`),
        " になる候補を持つ組は ", math(String.raw`11{,}904`), " に留まり、",
        math(String.raw`1{,}664`), " 組ではどの候補も位相比 ", math(String.raw`-1`),
        " を実現しない。最初の例は ", math(String.raw`D=\varnothing`), "、",
        math(String.raw`E=\{h(1,0),h(1,1),v(0,1),v(1,1)\}`), "、",
        math(String.raw`H=\{h(1,0),h(1,1)\}`),
        " である。従って、固定した ", math(String.raw`H`),
        " に対する置換ごとの局所的な組み替えでは一様な文字作用は構成できない。",
        "次は、置換ごとに組み替えに使う偶部分グラフを変える割り当て、",
        "または軌道構造まで使う大域的な対応を調べる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_global_rewiring_matching",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "置換ごとに偶部分グラフを選ぶ大域的組み替えは完全マッチングを持つ（一辺二の全数観察）" },
    body: [
      paragraph([
        "固定した偶部分グラフに対する一様な頂点組み替えは全置換で位相を反転しなかったが、",
        "置換ごとに使う偶部分グラフを変えてよい大域的な対応を一辺 ", math(String.raw`L=2`),
        " で調べた（sagemath/check/even-subgraph-global-rewiring-matching）。巻き付き文字が非自明な各ファイバーで、",
        "四スピン構造すべての位相寄与を反転する頂点組み替え候補を辺とする二部グラフを作った。",
        "全 ", math(String.raw`64`), " ファイバー、置換 ", math(String.raw`5{,}248`),
        " 個の全てで完全マッチングが存在し、合計 ", math(String.raw`2{,}624`), " 対を得た。",
        "従って一辺二では、置換ごとに偶部分グラフと組み替えを選べば、四スピン構造に共通する",
        "符号反転対合を構成できる。次はこの有限マッチングが選ぶ偶部分グラフと局所接続の規則を抽出し、",
        "一般の辺長で定義できる大域対応へ持ち上げる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_fiberwise_uniform_matching",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "ファイバーごとに固定した偶部分グラフでは覆えないものが残る（一辺二の全数観察）" },
    body: [
      paragraph([
        "置換ごとに偶部分グラフを選ぶ大域的組み替えの完全マッチングを、どこまで単純化",
        "できるかを一辺 ", math(String.raw`L=2`),
        " で調べた（sagemath/check/even-subgraph-fiberwise-uniform-matching）。",
        "巻き付き文字が非自明な各ファイバーで、", math(String.raw`E`), " に含まれ ",
        math(String.raw`\chi_E(H)=-1`), " となる偶部分グラフ ", math(String.raw`H`),
        " を一つ固定し、そのファイバーの全置換が ", math(String.raw`H`),
        " に沿う頂点組み替えの中に四スピン構造すべてで位相寄与を反転する候補を持つか（一様被覆）を",
        "検査した。全 ", math(String.raw`64`), " ファイバー中 ", math(String.raw`48`),
        " には一様被覆する ", math(String.raw`H`),
        " が存在し、その全てで候補対だけの完全マッチングも成立した。しかし残り ",
        math(String.raw`16`), " ファイバー（最初の例は ", math(String.raw`D=\varnothing`), "、",
        math(String.raw`E=\{h(1,0),h(1,1),v(0,1),v(1,1)\}`),
        "）には一様被覆する ", math(String.raw`H`),
        " が存在しない。従って大域対応の規則は「ファイバーごとに偶部分グラフを一つ選ぶ」までは",
        "単純化できない。従って、検査した頂点組み替え候補族の中では、これらのファイバーを覆うために",
        "置換ごとに偶部分グラフを変える必要がある。",
        "次は覆えない ", math(String.raw`16`),
        " ファイバーで置換ごとの割り当てがどの構造（軌道分解・接触対の配置）に従うかを調べる。",
        "検算は有限集合・有限写像と ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_uncovered_fiber_structure",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "単一の偶部分グラフで覆えないファイバーでは軌道分解が必ず変わる（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、置換ごとに偶部分グラフを変える頂点組み替え候補が",
        "従う構造を調べた（sagemath/check/even-subgraph-uncovered-fiber-structure）。対象となる ",
        math(String.raw`2{,}816`), " 置換の符号反転候補を、元と像の軌道長の多重集合が一致する辺へ",
        "制限すると、辺は一つも残らなかった。従って検査した候補族による大域対応は軌道分解を",
        "保存する規則にはできない。接触対が属する二軌道の長さの組と、切り替え可能接触対が属する",
        "二軌道の長さの組をさらに固定しても同じであり、接触対配置を同じ軌道長の組の間で保つ規則にも",
        "できない。次は、候補が軌道をどのように分裂・合併するかを調べる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_orbit_splitting",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "覆えないファイバーの候補は一軌道の二分裂か二軌道の合併に限られる（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、符号反転候補が軌道分解をどう変えるかを調べた",
        "（sagemath/check/even-subgraph-orbit-splitting）。各候補辺（元の置換 ",
        math(String.raw`\varphi`), " と像の置換 ", math(String.raw`\psi`), " の対）について、",
        math(String.raw`\psi`), " の動く向き付き辺を（", math(String.raw`E`),
        " 上で向きが反転した分は反転写像で）", math(String.raw`\varphi`),
        " の動く向き付き辺集合へ全単射に引き戻し、二つの軌道分割の重なり二部グラフの連結成分を",
        "分類した。全 ", math(String.raw`4{,}608`),
        " 辺で非自明成分はちょうど一個であり、その形は一つの軌道が二つへ分裂するもの（",
        math(String.raw`4{,}096`), " 辺）か、二つの軌道が一つへ合併するもの（",
        math(String.raw`512`), " 辺）のどちらかに限られる。成分内で軌道長の総和は保存され、",
        "他の軌道は全て不変である。分裂で生じる短い側の軌道長は ",
        math(String.raw`2,4,6`), " のいずれかで、長さ ", math(String.raw`2`),
        " の軌道が生じる分裂が ", math(String.raw`3{,}456`),
        " 辺と大半を占める。従って覆えないファイバーの大域対応の規則は、軌道全体の組み替えでは",
        "なく、一つの軌道の局所的な切断または二つの軌道の局所的な接合として探せる。",
        "検算は有限集合の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_local_cut_join",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "軌道の分裂・合併で変わる後続遷移は一つまたは二つの頂点に局在する（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、像の置換を元の置換の動く向き付き辺集合へ",
        "引き戻して後続辺の違いを調べた（sagemath/check/even-subgraph-orbit-local-cut-join）。",
        "全 ", math(String.raw`4{,}608`), " 候補辺のうち ", math(String.raw`2{,}816`),
        " 本は一つの頂点で二本の後続遷移を変更し、", math(String.raw`1{,}792`),
        " 本は二つの頂点でそれぞれ二本の後続遷移を変更する。それ以外の頂点から出る遷移は",
        "変わらない。元の一軌道の中だけで変更する ",
        math(String.raw`4{,}096`), " 本が二分裂を、異なる二軌道にまたがる交換を含む ",
        math(String.raw`512`), " 本が合併を起こす。従って一般の辺長へ持ち上げる候補は、",
        "一つまたは二つの頂点で二本ずつの後続遷移を変更する局所操作として探せる。検算は有限集合と",
        "有限写像の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_swap_rule",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "局所変更の交換形だけでは候補を一意に選べない（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、局所変更の交換形と置換ごとの候補数を調べた",
        "（sagemath/check/even-subgraph-orbit-swap-rule）。一頂点で二本の後続遷移が変わる ",
        math(String.raw`2{,}816`), " 本は、すべて二本の元の後続を交換する。二頂点で二本ずつ変わる ",
        math(String.raw`1{,}792`), " 本は、各頂点の新しい後続対が他方の元の後続対に丸ごと一致する",
        "交差交換ではない。すべての候補で、各頂点の新しい後続対は自身の元の後続を一本と",
        "他方の元の後続を一本含む。候補元となる置換 ", math(String.raw`2{,}624`),
        " 個のうち、候補が一本だけのものは ", math(String.raw`640`), " 個、二本あるものは ",
        math(String.raw`1{,}984`), " 個だった。一頂点交換の候補数も零本・一本・二本に分かれる。",
        "従って局所形だけでは置換ごとの候補を一意に選べない。次は二頂点変更で交換される",
        "一本ずつを区別する配置と、二候補の間を分ける規則を調べる。検算は有限集合と有限写像の",
        "等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_candidate_discrimination",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "所属の型と軌道形では候補を区別できない（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、二頂点変更の受け渡しの配置と、二候補を分ける",
        "不変量を調べた（sagemath/check/even-subgraph-orbit-candidate-discrimination）。",
        "二頂点変更 ", math(String.raw`1{,}792`), " 本の各頂点では、二本の変更到着のうち",
        "ちょうど一本が同じ頂点のもう一方の元の後続を受け取り（交差到着）、もう一本が",
        "他方の頂点の元の後続を受け取る（受領到着）。（交差到着, 受領到着, 輸出後続, ",
        "受領後続）の基底辺の所属（反転対の辺集合 ", math(String.raw`D`), "・単純通過の辺集合 ",
        math(String.raw`E`), "・その外）の型は 4 種にちょうど ", math(String.raw`896`),
        " 頂点ずつ分かれ、外の辺は一度も現れないが、交差到着と受領到着が同所属になる頂点が全 ",
        math(String.raw`3{,}584`), " 頂点中 ", math(String.raw`1{,}792`),
        " あるため、所属の型だけでは交差と受領を区別できない。候補を二本持つ ",
        math(String.raw`1{,}984`), " 置換の二候補を（変更頂点数, 軌道変化の形）で比べると ",
        math(String.raw`1{,}056`), " 対は同形であり、この不変量でも二候補を区別できない。",
        "合併は合併としか対にならず、一頂点と二頂点の混合対は分裂だけに現れる。また一頂点変更 ",
        math(String.raw`2{,}816`), " 本はすべて長さ ", math(String.raw`2`),
        " の軌道を切り出す分裂である。従って候補を分ける規則は、所属の型と軌道形より細かい",
        "配置（切断点の位置・受け渡す辺の同定）まで見る必要がある。検算は有限集合と有限写像の",
        "等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_cut_location",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "二候補の大部分は切断・接合する頂点の位置で区別できる（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、候補を二本持つ ", math(String.raw`1{,}984`),
        " 置換の二候補を、変更頂点・変更到着辺・変更後続の順に比較した",
        "（sagemath/check/even-subgraph-orbit-cut-location）。変更頂点集合が異なるものは ",
        math(String.raw`1{,}792`), " 個であり、粗い軌道形では区別できなかった候補を含む大部分は、",
        "切断・接合する頂点の位置まで見れば区別できる。残る ", math(String.raw`192`),
        " 個では、変更する向き付き到着辺の集合、基底辺の多重集合、元の動く向き付き辺集合へ",
        "引き戻した変更後続の対応まで二候補で全て一致した。従ってこの比較で捉える局所操作としては",
        "二候補を区別できず、像側の向きを元側へ戻す前にだけ違いが残る。",
        "次は、位置が異なる二候補から平行移動や回転に依存せず一方を選び、その選択が候補辺の",
        "両端で一致する規則を調べる。検算は有限集合と有限写像の等号だけで完結し、",
        "浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_translation_stabilizer",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "二候補の選択に平行移動の対称性の障害は無い（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーについて、非自明な平行移動（",
        math(String.raw`3`), " 通り）が ", math(String.raw`(D,E)`),
        " を固定するかを全数で調べた",
        "（sagemath/check/even-subgraph-orbit-translation-stabilizer）。どのファイバーも",
        "固定されず、従って ", math(String.raw`(D,E,\varphi)`),
        " を固定する非自明な平行移動は存在せず、候補を二本持つ ", math(String.raw`1{,}984`),
        " 置換のどれについても二候補を入れ替える平行移動はない。すなわち、平行移動と可換な",
        "選択規則が二候補から一方を選ぶことを妨げる対称性の障害は無い。さらに覆えない ",
        math(String.raw`16`), " ファイバーの集合は平行移動で閉じ、大きさ ",
        math(String.raw`4`), " の軌道がちょうど ", math(String.raw`4`),
        " 本に分かれる。ただし、この検算は異なるファイバー間で候補辺集合が平行移動と可換であることを",
        "確かめていないので、代表での選択を残りへ延長できるとは結論しない。次は候補辺集合の",
        "平行移動共変性を調べる。",
        "検算は有限集合と有限写像の等号だけで完結し、浮動小数点は使わない。",
      ]),
      paragraph([
        "続く全数検査では、記録済み候補辺集合が一致したのはファイバーと非自明な平行移動の全 ",
        math(String.raw`48`), " 組中 ", math(String.raw`20`), " 組だけだった。移動した候補辺 ",
        math(String.raw`13{,}824`), " 本はすべて移動先でも符号反転候補として有効だが、そのうち延べ ",
        math(String.raw`3{,}584`), " 本が記録済みの移動先候補辺集合に含まれない。従って非共変性は",
        "候補の幾何ではなく、各偶部分グラフについて最初に見つかった候補だけを記録する縮約に由来する。",
        "次は全ての有効候補を保持した共変な候補辺集合を作り直す。",
      ]),
      paragraph([
        "全ての位相反転候補を保持して重複だけを除いた集合を作り直すと、全 ",
        math(String.raw`48`), " 組で平行移動と可換になった",
        "（sagemath/check/even-subgraph-orbit-all-phase-edges）。候補元は ",
        math(String.raw`2{,}624`), " 置換、異なる候補辺は ", math(String.raw`6{,}400`),
        " 本であり、候補数は一本が ", math(String.raw`640`), " 個、二本が ",
        math(String.raw`768`), " 個、三本が ", math(String.raw`640`), " 個、四本が ",
        math(String.raw`576`), " 個である。一頂点変更は縮約前後で同じ ",
        math(String.raw`2{,}816`), " 本だったが、二頂点変更は ",
        math(String.raw`1{,}792`), " 本から ", math(String.raw`3{,}584`),
        " 本へ、二軌道の合併は ", math(String.raw`512`), " 本から ",
        math(String.raw`1{,}024`), " 本へ増えた。従って縮約は二頂点変更と合併の候補を",
        "半分落としていた。以後はこの共変な全候補集合の上で選択規則を調べる。",
        "検算は有限集合・有限写像と ", math(String.raw`\mathbb{Q}(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
      paragraph([
        "共変な全候補集合では、全 ", math(String.raw`6{,}400`),
        " 本の候補辺のどれについても逆向き辺（終点を始点とする候補辺）は集合に含まれず、",
        "候補関係は完全に反対称である",
        "（sagemath/check/even-subgraph-orbit-locality-selection）。候補元 ",
        math(String.raw`2{,}624`), " 置換の一頂点変更の候補の本数は零本が ",
        math(String.raw`576`), " 個、一本が ", math(String.raw`1{,}280`),
        " 個、二本が ", math(String.raw`768`),
        " 個であり、一頂点候補が一意な ", math(String.raw`1{,}280`),
        " 個のうち選んだ先が候補元でないものが ", math(String.raw`640`),
        " 個、選んだ先が候補元だが別の置換を選ぶものが ", math(String.raw`640`),
        " 個で、互いに選び合う対は零である。局在頂点数と軌道変化は平行移動で不変なので",
        "この規則は平行移動と可換だが、両端の一致する選択にはならない。候補関係が",
        "反対称である以上、両端の一致は逆向き辺の相互選択ではなく、候補辺を無向対として",
        "重複なく選ぶこととして問う必要がある。次は選んだ先が別の置換を選ぶ ",
        math(String.raw`640`), " 個の衝突の構造を調べる。",
      ]),
      paragraph([
        "一意な一頂点候補による選択辺 ", math(String.raw`1{,}280`),
        " 本を無向化すると、接する置換は ", math(String.raw`1{,}456`),
        " 個で、連結成分は長さ ", math(String.raw`4`), " の道 ",
        math(String.raw`32`), " 個と、中心から四本の長さ ", math(String.raw`2`),
        " の腕が出る木 ", math(String.raw`144`),
        " 個からなる森である（sagemath/check/even-subgraph-orbit-locality-collision）。",
        "各腕の向きは外端から中間点を経て中心へ向かい、衝突する ",
        math(String.raw`640`),
        " 本はすべて二段目で一意選択を持たない中心へ達する。二段で変更する頂点は全て異なる。",
        "各成分の頂点数は奇数なので、一意な一頂点候補だけからなるこの森には完全マッチングが無い。",
        "従って残りの一頂点候補または二頂点変更候補も必要である。次は各中心に入る腕と、",
        "同じ成分の頂点に接する残りの候補辺の配置を比較する。",
      ]),
      paragraph([
        "衝突森の全 ", math(String.raw`176`),
        " 中心は位相反転候補を一本も持たない置換である",
        "（sagemath/check/even-subgraph-orbit-collision-forest-context）。残りの候補対 ",
        math(String.raw`5{,}120`),
        " 本はどの成分の内部にも一本も残らず、成分に接するものは全て成分の外へ出る。",
        "内訳は、成分から森の外の頂点へ出るものが一頂点変更 ", math(String.raw`1{,}504`),
        " 本・二頂点変更の分裂 ", math(String.raw`1{,}280`), " 本・合併 ",
        math(String.raw`512`), " 本、異なる二成分を結ぶ二頂点変更の分裂が ",
        math(String.raw`640`), " 本、森に触れないものが一頂点変更 ",
        math(String.raw`32`), " 本・二頂点変更の分裂 ", math(String.raw`640`),
        " 本・合併 ", math(String.raw`512`),
        " 本である。外へ出る残候補は道の成分で ", math(String.raw`8`),
        " 本、木の成分で ", math(String.raw`30`),
        " 本と一定であり、各中心には成分の外から候補辺がちょうど ",
        math(String.raw`2`),
        " 本入る。従って奇数頂点の各成分を対で覆うには成分の外と対にする辺が少なくとも一本要る。",
        "各中心には外から入る候補辺が二本ある。次はこの外部辺の相手の",
        "配置から、平行移動と可換な無向対の選択規則を探す。",
      ]),
      paragraph([
        "未被覆の ", math(String.raw`16`),
        " ファイバーは、平行移動による大きさ ", math(String.raw`4`),
        " の軌道を ", math(String.raw`4`),
        " 本なす（sagemath/check/even-subgraph-orbit-translation-covariant-matching）。",
        "各軌道の代表ファイバーで共変な全候補グラフの完全マッチングを一つ構成し、",
        "平行移動で残りへ運ぶと、全 ", math(String.raw`2{,}816`),
        " 置換が ", math(String.raw`1{,}408`),
        " 対へ重複なく分かれた。選ばれた対は全て位相反転候補であり、",
        math(String.raw`16`), " ファイバーと ", math(String.raw`4`),
        " 平行移動の全 ", math(String.raw`64`),
        " 組でマッチングの像が移動先のマッチングと一致した。従って一辺二では、",
        "局所規則に限らなければ、平行移動と可換な符号反転完全マッチングが存在する。",
        "一般の辺長ではファイバーの平行移動作用が自由とは限らないので、次は固定部分を持つ",
        "軌道でも代表上のマッチングを矛盾なく運べる条件を切り出す。",
      ]),
      paragraph([
        "代表上の完全マッチングを軌道へ運べる条件は、固定部分群による不変性である",
        "（sagemath/check/even-subgraph-orbit-transport-stabilizer-condition）。",
        "有限群がファイバーを移し候補グラフを同型で移すとき、代表 ",
        math(String.raw`r`), " の完全マッチング ", math(String.raw`M`),
        " の運搬 ", math(String.raw`g\cdot r\mapsto g\cdot M`),
        " が well-defined であることは、", math(String.raw`M`),
        " が固定部分群 ", math(String.raw`\mathrm{Stab}(r)`),
        " の全元で不変であることと同値である。実際、運搬が well-defined なら恒等元と固定部分群の元を比較して不変性を得る。",
        math(String.raw`g\cdot r=h\cdot r`), " なら ",
        math(String.raw`h^{-1}g\in\mathrm{Stab}(r)`), " なので、逆に固定部分群不変性から ",
        math(String.raw`g\cdot M=h\cdot(h^{-1}g)\cdot M=h\cdot M`),
        " を得て運搬は well-defined になる。そのとき運んだ族は候補辺だけの",
        "完全マッチングで群の全元と可換になる。逆に共変な族はこの運搬に限るので、",
        "共変族の存在は代表の候補グラフに固定部分群不変な完全マッチングが存在することと",
        "同値である。固定部分群が非自明な有限の実例では、各ファイバーが完全マッチングを",
        "二つ持つのに不変なものが無く共変族が存在しないことがあるため、",
        "各ファイバーの完全マッチングの存在だけでは足りない。一辺二の未被覆 ",
        math(String.raw`16`),
        " ファイバーでは平行移動の固定部分群が自明なのでこの条件は空であり、",
        "前段の運搬がそのまま通る。次はこの条件を一般の辺長の平行移動作用へ",
        "適用するため、未被覆ファイバーの固定部分群の非自明性を辺長ごとに調べる。",
        "三つの有限例の全数検査はこの一般証明そのものではなく、不変マッチングが存在する場合と存在しない場合、および自由作用の場合を具体化する検算である。",
      ]),
    ],
  },
]);
