/**
 * 章「トーラス上の Kac--Ward 行列式」に紐づく検算・観察ノート。
 * 検算は証明ではなく、一般化できない有限標本を本文へ混ぜない。
 */

import { defineNotes, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineNotes([
  {
    id: "note_kac_ward_definition_determinants_even_subgraph_square_observation",
    targets: ["def_kac_ward_determinants"],
    title: { text: "行列式は符号付き偶部分グラフ多項式の平方（観察と経路の確定）" },
    body: [
      paragraph([
        "検証水準の計算として、一辺 ", math(String.raw`L=2,3`),
        " の周期正方格子で四つの Kac--Ward 行列式 ",
        math(String.raw`\det\bigl(I-x\,M^{a,b}\bigr)`),
        " を円分体 ", math(String.raw`\mathbb Q(\zeta_8)`),
        " 係数の多項式として厳密に計算し、全頂点の次数が偶数である台の辺の部分集合",
        "（偶部分グラフ）", math(String.raw`A`), " の切断線偶奇 ",
        math(String.raw`(h(A),v(A))`), " に符号 ",
        math(String.raw`(-1)^{c\,h+d\,v+e\,hv}`), "（", math(String.raw`c,d,e\in\{0,1\}`),
        " の全 8 候補）を付けた多項式の平方と比較した",
        "（sagemath/check/torus-kac-ward-even-subgraph-square）。",
      ]),
      paragraph([
        "結果、四つのスピン構造すべてで等式",
      ]),
      displayMath(String.raw`\det\bigl(I-x\,M^{a,b}\bigr)
=\Bigl(\sum_{A}(-1)^{(1+a)h(A)+(1+b)v(A)+h(A)v(A)}\,x^{|A|}\Bigr)^{2}`),
      paragraph([
        "が成り立った。スピン構造 ", math(String.raw`(0,1)`), " と ",
        math(String.raw`(1,0)`), " では二つの符号候補の平方が一致するが、これは正方トーラスの",
        "軸対称によりホモロジー類 ", math(String.raw`(1,0)`), " と ",
        math(String.raw`(0,1)`),
        " の類別和が多項式として一致するためで、等式の一意性とは矛盾しない。",
      ]),
      paragraph([
        "この観察により、一般の ", math(String.raw`L`), " で証明すべき候補は",
        "「行列式＝符号付き偶部分グラフ多項式の平方」という行列式レベルの恒等式である。",
        "ただし多項式全体の一致だけから、置換展開の個々の両向き項が相殺するか、平方の交差項へ",
        "どのように対応するかは決まらない。この項ごとの対応は一般の恒等式の証明で別に示す必要がある。",
        "反復分解（接触対数の整礎帰納）は、この恒等式の証明の中で各閉路の回転位相符号を",
        "確定するために使う。これは有限標本（", math(String.raw`L=2,3`),
        "）の観察であり、一般の ", math(String.raw`L`), " についてはまだ何も証明していない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_definition_cyclic_total_turning_vertex_simple_observation",
    targets: ["def_cyclic_total_turning"],
    title: { text: "頂点単純閉路の循環総回転数（証明前の有限標本観察）" },
    body: [
      paragraph([
        "検証水準の計算として、一辺 ", math(String.raw`L=2,3,4`),
        " の周期正方格子で、通過の頂点が相異なる（接触対数零の）閉じた非後退辺列を",
        "全列挙し（基点と向きを区別した数え上げで全 ", math(String.raw`373{,}716`),
        " 本）、循環総回転数 ", math(String.raw`t_{\circ}(\gamma)`),
        " と切断線偶奇 ", math(String.raw`(h(\gamma)\bmod2,\ v(\gamma)\bmod2)`),
        " を突き合わせた（sagemath/check/vertex-simple-cycle-turning）。",
      ]),
      paragraph([
        "結果、次の離散 Whitney の言明が例外なく成り立った。切断線偶奇が ",
        math(String.raw`(0,0)`), " の頂点単純閉路（", math(String.raw`73{,}616`),
        " 本）は ", math(String.raw`t_{\circ}(\gamma)\in\{+4,-4\}`),
        "。切断線偶奇が ", math(String.raw`(0,0)`), " 以外の頂点単純閉路（",
        math(String.raw`300{,}100`), " 本）は ", math(String.raw`t_{\circ}(\gamma)=0`),
        "。この観察は本文の「頂点単純閉路の循環総回転数は切断線偶奇で決まる」で",
        "一般の一辺長について証明済みである。",
      ]),
      paragraph([
        "整数巻き付きベクトルが零の場合は、本文の平面持ち上げと有限セルの二重計数により一般の ",
        math(String.raw`L`), " で ", math(String.raw`t_{\circ}(\gamma)\in\{+4,-4\}`),
        " が証明された。したがって、この場合の回転位相は ",
        math(String.raw`\zeta_8^{\,t_{\circ}(\gamma)}=-1`),
        " である。零でない原始的巻き付きの場合の ",
        math(String.raw`t_{\circ}(\gamma)=0`), " と回転位相 ",
        math(String.raw`+1`),
        " も周期単純路の一側閉包と三周期比較により証明済みである。有限標本（",
        math(String.raw`L=2,3,4`), "）の観察は証明された二場合の両方を検査している。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_parallel_separated_staircases_direct_closure_counterexample",
    targets: ["claim_parallel_separated_staircases_disjoint"],
    title: { text: "二本の反復横断階段を対応点へ結ぶ直接閉包は単純にならない" },
    body: [
      paragraph([
        "周期持ち上げの一周期分と、その横断平行移動を、両端から出した同じ反復横断階段で結ぶ候補は、",
        "既存の分離補題だけでは単純閉路にならない。反例は一辺 ", math(String.raw`L=2`),
        " のトーラス上の頂点列 ",
        math(String.raw`((0,0),(0,1),(1,1),(1,0),(0,0))`),
        " である。この閉路の平面持ち上げの一周期分は",
      ]),
      displayMath(String.raw`(0,0),(0,1),(1,1),(1,0),(2,0)`),
      paragraph([
        "となり、巻き付き数は ", math(String.raw`(w_{\mathrm h},w_{\mathrm v})=(0,1)`),
        "、正の横断階段は左向きである。横断幅を超える二回の平行移動で直接閉包すると、",
        "合成列には、左側の接続階段と平行移動後の持ち上げの交点 ", math(String.raw`(0,-1)`),
        " が二度現れる。したがって「二つの周期持ち上げが互いに交わらないこと」と",
        "「二本の階段が互いに交わらないこと」だけでは、階段と反対側の持ち上げとの交差を排除できない。",
      ]),
      paragraph([
        "この候補は採用しない。閉包を完成させるには、反対側の持ち上げも終点以外で避ける接続路を別に構成し、",
        "その後に四つの部分の交差を組ごとに検査する必要がある。反例は整数格子の有限列だけで完結し、",
        "実数体も複素数体も用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_periodic_lift_closure_turning_difference_cancellation",
    targets: ["def_periodic_lift_closure_cycle", "def_cyclic_total_turning"],
    title: { text: "周期数を増やした閉包の回転数差では持ち上げの回転数を取り出せない" },
    body: [
      paragraph([
        "周期数 ", math(String.raw`c`), " の閉包と周期数 ", math(String.raw`c+1`),
        " の閉包の循環総回転数を比較する候補は採用しない。接続階段の向きの有限語を ",
        math(String.raw`A`), "、周期持ち上げ一周期分の向きの巡回語を ", math(String.raw`P`),
        " とし、向きを全て反転して順序を逆にした語をそれぞれ ",
        math(String.raw`\overline A,\overline P`), " と書く。閉包の向きの巡回語は、",
      ]),
      displayMath(String.raw`A\,P^{c}\,\overline A\,\overline P^{c}`),
      paragraph([
        "の形である。周期数を一つ増やすと、順向きの周期語 ", math(String.raw`P`),
        " と逆向きの周期語 ", math(String.raw`\overline P`),
        " が一つずつ同時に挿入される。巡回語の回転数和を ", math(String.raw`T`),
        " と書くと、巡回の開始位置をずらしても有限和は変わらず、逆向きでは各回転の符号が反転するので",
      ]),
      displayMath(String.raw`T(P)+T(\overline P)=T(P)-T(P)=0`),
      paragraph([
        "となる。したがって閉包の循環総回転数の差は、元の ", math(String.raw`T(P)`),
        " の値にかかわらず零であり、この差から ", math(String.raw`T(P)=0`),
        " を導くことはできない。SageMath の有限全列挙でも、一辺 ", math(String.raw`L=1,2,3`),
        " の全対象について周期数 ", math(String.raw`c=1,2,3`),
        " の閉包の循環総回転数が一致し、追加された順向き・逆向きの一周期の和が零になることを整数だけで確認した",
        "（sagemath/check/periodic-lift-closure-cycle）。次は、逆向きの周期持ち上げを同時に追加しない一側閉包を構成し、",
        "周期数の差に一周期分だけが残る形へ変える必要がある。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_doubled_edge_fiber_phase_reduction_unlocked_residual_noncancellation",
    targets: ["claim_doubled_edge_fiber_phase_reduction", "def_unswitchable_standard_pair_subset"],
    title: { text: "切り替え可能接触を持つ残余は符号反転対合で相殺できない" },
    body: [
      paragraph([
        "標準対が切り替え不能な残余 ", math(String.raw`\mathcal R_L`),
        " のうち、別の切り替え可能な接触対を持つ部分について、平滑化と両立する接触対の選択規則を",
        "作って符号反転対合で相殺する候補は採用しない。理由は二つある。第一に、切り替え可能な接触対の",
        "辞書式最小を選ぶ規則は平滑化と両立しない。一辺 ", math(String.raw`L=2`),
        " のこの部分 ", math(String.raw`17{,}925`), " 個を厳密に列挙したところ、辞書式最小の",
        "切り替え可能対での平滑化が標準対を切り替え可能へ変えて残余から出すものが ",
        math(String.raw`4{,}638`), " 個、平滑化後に辞書式最小の切り替え可能対が変わるものが ",
        math(String.raw`7{,}935`), " 個あった。",
      ]),
      paragraph([
        "第二に、選択規則の作り方に依らず、相殺そのものが不可能である。ファイバーを保ち",
        "位相寄与の符号を反転する不動点の無い対合がこの部分の上に存在すれば、その位相寄与の総和は",
        "各ファイバー×スピン構造で零になるはずである。ところが一辺 ", math(String.raw`L=2`),
        " の厳密和は、この部分が空でない ", math(String.raw`1{,}288`), " 組中 ",
        math(String.raw`380`), " 組で非零であり、残余 ", math(String.raw`\mathcal R_L`),
        " 全体の総和も ", math(String.raw`1{,}028`), " 組で非零である",
        "（sagemath/check/unlocked-residual-phase-noncancellation）。したがって残余は相殺の対象ではなく、",
        "回転差が正負四の二集合と合わせて、符号付き偶部分グラフ多項式の平方の項と数え上げで",
        "対応づけるべき寄与として扱う。この検算は有限集合の比較と円分体 ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の厳密和だけで完結し、実数体は用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_def_fiber_phase_weight_signed_selection_sum_fiberwise_equality",
    targets: ["def_fiber_phase_weight", "def_signed_selection_sum"],
    title: { text: "一辺二では置換ファイバー位相和と偶部分グラフ選択和が添字ごとに一致する" },
    body: [
      paragraph([
        "一般の平方恒等式で目標にすべき対応を確定するため、一辺 ", math(String.raw`L=2`),
        " の全非後退置換を反転対の辺集合 ", math(String.raw`D`), " と単純通過の辺集合 ",
        math(String.raw`E`), " で層別し、置換側の位相和 ",
        math(String.raw`\mathcal K^{a,b}_L(D,E)`), " と偶部分グラフ対側の符号付き選択和 ",
        math(String.raw`\mathcal U^{a,b}_L(D,E)`), " を定義から直接比較した。全 ",
        math(String.raw`609`), " ファイバーと四つのスピン構造、合計 ",
        math(String.raw`2{,}436`), " 件で",
      ]),
      displayMath(String.raw`\mathcal K^{a,b}_L(D,E)=\mathcal U^{a,b}_L(D,E)`),
      paragraph([
        "が成立した（sagemath/check/kac-ward-fiber-signed-selection-equality）。したがって、",
        "多項式全体の係数をまとめて比較するだけでなく、接触の無い置換、回転差が正負四の置換、",
        "残余を合わせた位相和を、同じ ", math(String.raw`(D,E)`),
        " の選択集合と数え上げで対応づければ平方恒等式へ合成できる。これは一般の ",
        math(String.raw`L`), " に対する証明ではなく、次に構成すべきファイバーごとの全単射または",
        "符号付き数え上げの目標を固定する厳密観察である。計算は有限集合、整数、円分体 ",
        math(String.raw`\mathbb Q(\zeta_8)`), " だけで閉じ、実数体は用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_def_fiber_phase_weight_signed_selection_sum_part_decomposition",
    targets: ["def_fiber_phase_weight", "def_signed_selection_sum"],
    title: { text: "一辺二では簡約四部分の位相和がすべて有理整数に落ち回転差二部分は相等である" },
    body: [
      paragraph([
        "一般の数え上げの形を絞るため、一辺 ", math(String.raw`L=2`),
        " の各ファイバー位相和を、位相反転部分集合 ", math(String.raw`\mathcal B_L`),
        " の零和で簡約した後に残る四部分（接触の無い置換、回転差 ", math(String.raw`-4`),
        " の置換、回転差 ", math(String.raw`4`), " の置換、残余 ", math(String.raw`\mathcal R_L`),
        "）へ分解し、全 ", math(String.raw`609`), " ファイバー×四スピン構造 ",
        math(String.raw`2{,}436`), " 組で各部分の位相和を ",
        math(String.raw`\mathbb Q(\zeta_8)`),
        " の厳密和として計算した（sagemath/check/kac-ward-fiber-phase-part-decomposition）。",
        "三つの観察を得た。第一に、四部分の位相和 ", math(String.raw`2{,}436\times4`),
        " 個はすべて有理整数に落ちた。第二に、回転差 ", math(String.raw`-4`), " と ",
        math(String.raw`4`), " の二部分の位相和は全組で互いに等しかった",
        "（標準対平滑化が両集合を交換し位相寄与を保存することと整合する）。",
        "第三に、接触の無い部分だけで ", math(String.raw`\mathcal U^{a,b}_L(D,E)`),
        " に一致するのは ", math(String.raw`1{,}052`), " 組に留まり、残余の位相和が非零の ",
        math(String.raw`1{,}028`), " 組と回転差二部分の和が非零の ", math(String.raw`464`),
        " 組が残りを埋めた。したがって一般の ", math(String.raw`L`),
        " で立てるべき言明は、円分体の値ではなく整数値の三つの符号付き数え上げ",
        "（接触の無い部分、回転差 ", math(String.raw`4`),
        " の部分の二倍、残余）の和が ", math(String.raw`\mathcal U^{a,b}_L(D,E)`),
        " に等しい、という形になる。これは一般の証明ではなく目標の形を固定する厳密観察である。",
        "計算は有限集合、整数、円分体だけで閉じ、実数体は用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_contact_smoothing_same_pair_involution_lexicographic_choice_counterexample",
    targets: ["claim_contact_smoothing_same_pair_involution"],
    title: { text: "辞書式最小の切り替え可能接触対は平滑化で保たれない" },
    body: [
      paragraph([
        "切り替え可能な接触対全体を向き付き辺の固定した辞書式順序で並べ、最小の対を選ぶ規則は、",
        "符号反転対合の標準対として採用しない。同じ対での平滑化は対合であるが、平滑化によって",
        "その対と一辺だけを共有する別の接触対の切り替え可能性が変わり得るため、最小の対そのものは保存されない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の全非後退置換 ", math(String.raw`30{,}784`),
        " 個を厳密に列挙したところ、切り替え可能な接触対を持つ置換は ", math(String.raw`29{,}905`),
        " 個あり、そのうち ", math(String.raw`7{,}935`),
        " 個で、辞書式最小対による平滑化の前後に選ばれる対が異なった",
        "（sagemath/check/lexicographic-switchable-contact-choice-counterexample）。",
        "したがって、次に定める標準対は単なる最小化ではなく、平滑化の前後で同じ局所データを選ぶ規則でなければならない。",
        "この検算は有限集合の比較だけで完結し、実数体も複素数体も用いない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_path_reversal_contact_pair_preservation_standard_classification_counterexample",
    targets: [
      "claim_path_reversal_contact_pair_preservation",
      "def_standard_turning_difference_subsets",
      "def_unswitchable_standard_pair_subset",
    ],
    title: { text: "標準接触対に依存する分類は経路反転で保たれない" },
    body: [
      paragraph([
        "接触対全体の全単射と各接触対の切り替え可能性の保存から、固定した辞書式順序で選ぶ標準接触対に",
        "依存する分類まで保存されるとは限らない。経路反転が誘導する全単射 ",
        math(String.raw`\Psi_{\varphi}`),
        " は接触対の辞書式順序を保たないからである。したがって、接触の無い部分・回転差が正負四の二部分・残余を",
        "そのまま経路反転軌道の重みに使う経路は採用しない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の全非後退置換 ", math(String.raw`30{,}784`),
        " 個を厳密に列挙すると、接触の無い ", math(String.raw`49`), " 個は全て保たれた。一方、残余から位相反転部分へ ",
        math(String.raw`1{,}416`), " 個、残余から回転差 ", math(String.raw`-4`), " と ",
        math(String.raw`4`), " の部分へそれぞれ ", math(String.raw`384`), " 個と ",
        math(String.raw`520`), " 個が移った。位相反転部分から回転差 ", math(String.raw`-4`),
        " へ移るものも ", math(String.raw`136`), " 個あり、回転差 ", math(String.raw`-4`),
        " から ", math(String.raw`4`), " へ移るものは ", math(String.raw`1{,}548`),
        " 個あった（sagemath/check/path-reversal-standard-classification-counterexample）。",
        "これは一般の非保存定理ではなく、候補経路を排除する有限反例である。次は接触対の順序に依らない分類を構成する。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_weighted_path_reversal_selection_orbit_sums_sign_bijection_counterexample",
    targets: [
      "claim_path_reversal_fixed_point_no_single_traversal",
      "claim_weighted_path_reversal_selection_orbit_sums",
    ],
    title: { text: "経路反転軌道と選択補集合軌道の符号保存対応は存在しない" },
    body: [
      paragraph([
        "単純通過辺集合 ", math(String.raw`E`), " が空でなければ、経路反転軌道と選択補集合軌道は",
        "どちらも全て二元である。しかし、この元数の一致だけでは、両軌道族の間に符号を保つ全単射が存在するとは限らない。",
        "そのような全単射が存在すれば、各ファイバー・スピン構造・符号について、両側の元数は一致しなければならない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の ", math(String.raw`E\ne\varnothing`),
        " である全ファイバーを四つのスピン構造と二つの符号について厳密に列挙すると、符号別元数が一致しない組は ",
        math(String.raw`2{,}744`), " 件あった。置換側が ", math(String.raw`2`), " 元、選択側が ",
        math(String.raw`0`), " 元である最初の例は、反転対の辺集合 ",
        math(String.raw`D=\{h(1,1)\}`), "、単純通過辺集合 ",
        math(String.raw`E=\{v(0,0),v(0,1),v(1,0),v(1,1)\}`),
        "、スピン構造 ", math(String.raw`(a,b)=(0,0)`), "、符号 ", math(String.raw`+1`), " であった",
        "（sagemath/check/path-reversal-selection-sign-bijection-counterexample）。",
        "従って経路反転軌道全体と選択補集合軌道全体の間に符号と重みを保つ全単射を構成する経路は採用しない。",
        "符号付き総和の一致は、既存の切り替え平滑化による相殺を残したまま直接示す必要がある。",
        "これは一般の不存在定理ではなく、候補経路を排除する有限反例である。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_fully_unswitchable_contacts_witness_doubled_edges_fiber_phase_sums",
    targets: [
      "claim_fully_unswitchable_contacts_witness_doubled_edges",
      "claim_weighted_path_reversal_selection_orbit_sums",
    ],
    title: { text: "三分類の部分和はファイバー単位では選択和に一致しない" },
    body: [
      paragraph([
        "ファイバー位相和を順序に依らない三分類（接触なし・切り替え可能対あり・全対切り替え不能）の部分和 ",
        math(String.raw`S_Z,S_X,S_Y`),
        " へ分けると、既知のファイバー一致により各ファイバー・スピン構造で ",
        math(String.raw`S_Z+S_X+S_Y`), " は選択和 ", math(String.raw`U`),
        " に等しい。しかし各部分和が単独でファイバー単位に零（または ", math(String.raw`U`),
        "）になるとは限らない。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " の全 ", math(String.raw`609`),
        " ファイバーと四つのスピン構造の ", math(String.raw`2{,}436`),
        " 組を厳密に列挙すると、", math(String.raw`S_X\ne0`), " が ", math(String.raw`736`),
        " 組、", math(String.raw`S_Y\ne0`), " が ", math(String.raw`648`), " 組、",
        math(String.raw`S_Z\ne U`), " が ", math(String.raw`1{,}384`), " 組あった。",
        math(String.raw`S_Y\ne0`), " の最初の例は ", math(String.raw`D=\{v(0,1)\}`), "、",
        math(String.raw`E=\{h(0,1),h(1,1),v(0,0),v(1,1)\}`), "、",
        math(String.raw`(a,b)=(0,0)`), " で ", math(String.raw`S_Y=-2`), " である",
        "（sagemath/check/fully-unswitchable-fiber-phase-sums）。",
        "したがって、切り替え可能部分も全対切り替え不能な残余も、各部分を保つ固定ファイバー内の符号反転対合だけでは消えない。",
        "ただし、切り替え可能な接触の平滑化は ",
        ref("claim_switchable_contact_smoothing_preserves_fiber"), " により反転対の辺集合 ",
        math(String.raw`D`), " と単純通過の辺集合 ", math(String.raw`E`),
        " を保つ。この有限観察だけから、異なるファイバーを結ぶ縮約帰納の存在は従わない。",
        "この検算は有限集合の数え上げと ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_fully_unswitchable_contacts_witness_doubled_edges_splice_reduction_counterexample",
    targets: ["claim_fully_unswitchable_contacts_witness_doubled_edges"],
    title: { text: "反転対の二方向を巡回から抜く縮約候補は非後退性を保たない" },
    body: [
      paragraph([
        "完全切り替え不能な残余の各接触が指す反転対の辺について、その二方向を置換の巡回から同時に抜き、",
        "各方向の直前の辺を直後の辺へつないで、抜いた二方向を固定点へ戻す縮約候補を調べた。",
        "一辺 ", math(String.raw`L=2`), " で、同じ置換と同じ反転対の重複を除いた ",
        math(String.raw`2{,}912`), " 件の縮約後は全て置換だったが、非後退置換だったのは ",
        math(String.raw`32`), " 件だけであり、反転対の辺集合 ", math(String.raw`D`),
        " だけを一辺減らして単純通過の辺集合 ", math(String.raw`E`),
        " を保つものは一件も無かった（sagemath/check/doubled-edge-splice-reduction）。",
        "従ってこの直接除去は ", math(String.raw`|D|`),
        " に関する一段の縮約には使えない。別の局所操作か、個々の置換ではなくファイバー位相和どうしを結ぶ関係が必要である。",
        "検算は有限集合と有限写像の等号・所属判定だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_selection_sum_affine_character",
    targets: [
      "def_signed_selection_sum",
      "claim_selection_sum_signed_count",
      "claim_selection_even_subgraph_action_character",
      "claim_selection_even_subgraph_action_simply_transitive",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "選択集合は偶部分グラフの作用による文字和として扱える" },
    body: [
      paragraph([
        "互いに素な辺集合 ", math(String.raw`D,E\subseteq E_L`), " が ",
        math(String.raw`\operatorname{Even}_L(E)`), " を満たすとする。",
        "選択集合 ", math(String.raw`\mathcal C_L(D,E)`), " が空でなければ、",
        math(String.raw`E`), " に含まれる偶部分グラフ ", math(String.raw`H`),
        " は対称差 ", math(String.raw`C\mapsto C\mathbin\triangle H`),
        " によりこの選択集合へ単純推移的に作用する。この作用による選択符号の指数差は",
      ]),
      displayMath(String.raw`\vartheta^{a,b}_L(D,E;C\mathbin\triangle H)-\vartheta^{a,b}_L(D,E;C)
\equiv \varepsilon_{L,\mathrm h}(E)\varepsilon_{L,\mathrm v}(H)
+\varepsilon_{L,\mathrm v}(E)\varepsilon_{L,\mathrm h}(H)\pmod 2`),
      paragraph([
        "であり、右辺は ", math(String.raw`H`), " の文字である。選択集合が空なら選択和は零である。",
        "空でない場合、この文字が非自明なら選択和は零、",
        "自明なら全ての選択が同じ符号を持ち、選択和はその符号と選択集合の元数の積になる。",
        "一辺二の全ファイバーで、単純推移性・指数差・二場合の和を検査する",
        "（sagemath/check/selection-sum-affine-character）。これは選択和を三分類と独立な一つの文字和へまとめ、",
        "ファイバー位相和全体と直接比較する一般証明の部品になる。検算は有限集合、",
        math(String.raw`\mathbb F_2`), " の算術、", math(String.raw`\mathbb Z`),
        " の有限和だけで完結し、浮動小数点は使わない。作用が選択集合を保つことと指数差の文字は、",
        "一般の ", math(String.raw`L`),
        " で本文の主張（偶部分グラフの対称差は選択集合を保ち符号指数を文字だけ動かす）として示した。",
        "単純推移性と選択和の評価も一般の ", math(String.raw`L`),
        " で本文へ命題化した。これらの Lean 二版は未着手である。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_fully_unswitchable_contacts_witness_doubled_edges_same_support_aggregation",
    targets: ["claim_fully_unswitchable_contacts_witness_doubled_edges"],
    title: { text: "台固定の集約でも三分類の部分和は消えない（全分解の実現は成立）" },
    body: [
      paragraph([
        "選択和の側は偶部分グラフ対 ", math(String.raw`(P,Q)`), " の ",
        math(String.raw`P\cap Q=D`), "、", math(String.raw`P\triangle Q=E`),
        " による分類であり、和集合 ", math(String.raw`P\cup Q=D\cup E`),
        " はファイバーをまたいで共有される。そこで一辺 ", math(String.raw`L=2`),
        " の全ファイバーを台 ", math(String.raw`F=D\cup E`),
        " で束ね、ファイバーは保たず台だけを保つ相殺の単位が成立するかを調べた",
        "（sagemath/check/same-support-fiber-phase-sums）。",
        "台は ", math(String.raw`104`), " 個、四スピン構造で ", math(String.raw`416`),
        " 組である。まず、台の分解 ", math(String.raw`F=D\sqcup E`),
        "（", math(String.raw`E`), " は偶）のうち非後退置換が一つも無い分解は零件であり、",
        "一辺二では全ての分解がファイバーとして実現される。一方、台で集約した三分類の部分和は ",
        math(String.raw`\textstyle\sum S_X\ne0`), " が ", math(String.raw`132`), " 組、",
        math(String.raw`\textstyle\sum S_Y\ne0`), " が ", math(String.raw`248`), " 組、",
        math(String.raw`\textstyle\sum S_Z\ne\sum U`), " が ", math(String.raw`380`),
        " 組あった。従って、固定ファイバー内でも台固定の集約でも、切り替え可能部分と",
        "全対切り替え不能な残余は単独では消えず、分類を保つ符号反転対合は固定ファイバーまたは",
        "台固定の相殺単位では存在しない。一般の辺長の証明は、三分類を混ぜてファイバー位相和の全体と",
        "選択和を直接結ぶ数え上げとして構成する必要がある。",
        "検算は有限集合の数え上げと ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_sum_character_evaluation_fiber_phase_part_vanishing",
    targets: [
      "claim_selection_sum_character_evaluation",
      "claim_fully_unswitchable_contacts_witness_doubled_edges",
    ],
    title: { text: "文字による消滅は三分類の各部分ごとに成立する（一辺二の全数観察）" },
    body: [
      paragraph([
        "選択和の文字評価は、選択集合が空か文字が非自明なら選択和が零であることを与える。",
        "ファイバー位相和の側で同じ消滅がどの粒度で起きるかを、一辺 ",
        math(String.raw`L=2`), " の全ファイバー×四スピン構造の ", math(String.raw`2{,}436`),
        " 組で調べた（sagemath/check/fiber-phase-character-vanishing）。種別は、選択集合が空 ",
        math(String.raw`768`), " 組、文字が非自明 ", math(String.raw`192`),
        " 組、文字が自明 ", math(String.raw`1{,}476`), " 組である。",
        "空と非自明文字の全 ", math(String.raw`960`),
        " 組で、三分類（接触なし・切り替え可能対あり・全対切り替え不能）の部分和 ",
        math(String.raw`S_Z,S_X,S_Y`),
        " は全て個別に零であり、非零の部分和は自明文字の組にしか現れない（",
        math(String.raw`S_Z\ne0`), " が ", math(String.raw`92`), " 組、",
        math(String.raw`S_X\ne0`), " が ", math(String.raw`736`), " 組、",
        math(String.raw`S_Y\ne0`), " が ", math(String.raw`648`), " 組）。",
        "従って一辺二では、文字が強制する ", math(String.raw`\mathcal K^{a,b}_L(D,E)=0`),
        " は三分類の各部分ごとに成立しており、一般の辺長でこの消滅を示す文字和・符号反転構造は",
        "部分ごとに探してよい。一方、自明文字の組では ", math(String.raw`S_Z=U`),
        " が ", math(String.raw`1{,}384`),
        " 組で破れるため、非零の値の同定は三分類を混ぜた全体で行う。",
        "検算は ", math(String.raw`\mathbb Z`), " と ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_oriented_edge_conjugation_counterexample",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_path_reversal_fiber_preserving_involution",
    ],
    title: { text: "偶部分グラフ上の向き反転共役は置換側の文字作用にならない（一辺二の全数反例）" },
    body: [
      paragraph([
        "単純通過辺集合 ", math(String.raw`E`), " に含まれる偶部分グラフ ",
        math(String.raw`H`), " に対し、", math(String.raw`H`),
        " の各辺で二つの向きだけを交換する対合を ", math(String.raw`\rho_H`),
        " とする。選択側の対称差作用に対応する最も直接的な候補として、置換を ",
        math(String.raw`\rho_H\circ\varphi\circ\rho_H`),
        " へ送る共役を一辺二で全数検査した（sagemath/check/even-subgraph-oriented-edge-conjugation）。",
        "全 ", math(String.raw`78{,}752`), " 組で反転対辺集合 ", math(String.raw`D`),
        " と単純通過辺集合 ", math(String.raw`E`), " は保たれたが、",
        math(String.raw`43{,}664`), " 組で非後退性が壊れた。非後退性を保った像でも、期待する文字と",
        "位相寄与の比が一致しないものが四スピン構造を合わせて ", math(String.raw`7{,}680`),
        " 件あった。従って、この共役は空・非自明文字のファイバー位相和を消す作用には使わない。",
        "次は向き付き辺を個別に反転するのではなく、各頂点の入出接続を偶部分グラフに沿って",
        "組み替える作用を調べる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_vertex_rewiring_counterexample",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "頂点の入出接続の組み替えも一様な文字作用にならない（一辺二の全数反例）" },
    body: [
      paragraph([
        "向き付き辺の個別反転の次の候補として、単純通過辺集合 ", math(String.raw`E`),
        " に含まれる偶部分グラフ ", math(String.raw`H`),
        " に沿って各頂点の入出接続を組み替える族を一辺二で全数検査した",
        "（sagemath/check/even-subgraph-vertex-rewiring）。",
        math(String.raw`H`), " の外どうしの遷移は保ち、", math(String.raw`H`),
        " 上の歩道の向き付き辺は全て逆向きへ差し替え、各頂点で残った到着と出発を",
        "直ちに引き返さない任意の全単射で結び直す。巻き付き文字が非自明（",
        math(String.raw`\chi_E(H)=-1`), "）な全 ", math(String.raw`13{,}568`),
        " 組で、各頂点の残った到着と出発の個数は常に釣り合い、非後退置換になる結び直しが",
        "常に存在した（候補総数 ", math(String.raw`38{,}016`),
        "）。しかし四スピン構造すべてで位相寄与の比が ", math(String.raw`-1`),
        " になる候補を持つ組は ", math(String.raw`11{,}904`), " に留まり、",
        math(String.raw`1{,}664`), " 組ではどの候補も位相比 ", math(String.raw`-1`),
        " を実現しない。最初の例は ", math(String.raw`D=\varnothing`), "、",
        math(String.raw`E=\{h(1,0),h(1,1),v(0,1),v(1,1)\}`), "、",
        math(String.raw`H=\{h(1,0),h(1,1)\}`),
        " である。従って、固定した ", math(String.raw`H`),
        " に対する置換ごとの局所的な組み替えでは一様な文字作用は構成できない。",
        "次は、置換ごとに組み替えに使う偶部分グラフを変える割り当て、",
        "または軌道構造まで使う大域的な対応を調べる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_global_rewiring_matching",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "置換ごとに偶部分グラフを選ぶ大域的組み替えは完全マッチングを持つ（一辺二の全数観察）" },
    body: [
      paragraph([
        "固定した偶部分グラフに対する一様な頂点組み替えは全置換で位相を反転しなかったが、",
        "置換ごとに使う偶部分グラフを変えてよい大域的な対応を一辺 ", math(String.raw`L=2`),
        " で調べた（sagemath/check/even-subgraph-global-rewiring-matching）。巻き付き文字が非自明な各ファイバーで、",
        "四スピン構造すべての位相寄与を反転する頂点組み替え候補を辺とする二部グラフを作った。",
        "全 ", math(String.raw`64`), " ファイバー、置換 ", math(String.raw`5{,}248`),
        " 個の全てで完全マッチングが存在し、合計 ", math(String.raw`2{,}624`), " 対を得た。",
        "従って一辺二では、置換ごとに偶部分グラフと組み替えを選べば、四スピン構造に共通する",
        "符号反転対合を構成できる。次はこの有限マッチングが選ぶ偶部分グラフと局所接続の規則を抽出し、",
        "一般の辺長で定義できる大域対応へ持ち上げる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_fiberwise_uniform_matching",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "ファイバーごとに固定した偶部分グラフでは覆えないものが残る（一辺二の全数観察）" },
    body: [
      paragraph([
        "置換ごとに偶部分グラフを選ぶ大域的組み替えの完全マッチングを、どこまで単純化",
        "できるかを一辺 ", math(String.raw`L=2`),
        " で調べた（sagemath/check/even-subgraph-fiberwise-uniform-matching）。",
        "巻き付き文字が非自明な各ファイバーで、", math(String.raw`E`), " に含まれ ",
        math(String.raw`\chi_E(H)=-1`), " となる偶部分グラフ ", math(String.raw`H`),
        " を一つ固定し、そのファイバーの全置換が ", math(String.raw`H`),
        " に沿う頂点組み替えの中に四スピン構造すべてで位相寄与を反転する候補を持つか（一様被覆）を",
        "検査した。全 ", math(String.raw`64`), " ファイバー中 ", math(String.raw`48`),
        " には一様被覆する ", math(String.raw`H`),
        " が存在し、その全てで候補対だけの完全マッチングも成立した。しかし残り ",
        math(String.raw`16`), " ファイバー（最初の例は ", math(String.raw`D=\varnothing`), "、",
        math(String.raw`E=\{h(1,0),h(1,1),v(0,1),v(1,1)\}`),
        "）には一様被覆する ", math(String.raw`H`),
        " が存在しない。従って大域対応の規則は「ファイバーごとに偶部分グラフを一つ選ぶ」までは",
        "単純化できない。従って、検査した頂点組み替え候補族の中では、これらのファイバーを覆うために",
        "置換ごとに偶部分グラフを変える必要がある。",
        "次は覆えない ", math(String.raw`16`),
        " ファイバーで置換ごとの割り当てがどの構造（軌道分解・接触対の配置）に従うかを調べる。",
        "検算は有限集合・有限写像と ", math(String.raw`\mathbb Q(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_uncovered_fiber_structure",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "単一の偶部分グラフで覆えないファイバーでは軌道分解が必ず変わる（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、置換ごとに偶部分グラフを変える頂点組み替え候補が",
        "従う構造を調べた（sagemath/check/even-subgraph-uncovered-fiber-structure）。対象となる ",
        math(String.raw`2{,}816`), " 置換の符号反転候補を、元と像の軌道長の多重集合が一致する辺へ",
        "制限すると、辺は一つも残らなかった。従って検査した候補族による大域対応は軌道分解を",
        "保存する規則にはできない。接触対が属する二軌道の長さの組と、切り替え可能接触対が属する",
        "二軌道の長さの組をさらに固定しても同じであり、接触対配置を同じ軌道長の組の間で保つ規則にも",
        "できない。次は、候補が軌道をどのように分裂・合併するかを調べる。検算は有限集合・有限写像と ",
        math(String.raw`\mathbb Q(\zeta_8)`), " の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_orbit_splitting",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "覆えないファイバーの候補は一軌道の二分裂か二軌道の合併に限られる（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、符号反転候補が軌道分解をどう変えるかを調べた",
        "（sagemath/check/even-subgraph-orbit-splitting）。各候補辺（元の置換 ",
        math(String.raw`\varphi`), " と像の置換 ", math(String.raw`\psi`), " の対）について、",
        math(String.raw`\psi`), " の動く向き付き辺を（", math(String.raw`E`),
        " 上で向きが反転した分は反転写像で）", math(String.raw`\varphi`),
        " の動く向き付き辺集合へ全単射に引き戻し、二つの軌道分割の重なり二部グラフの連結成分を",
        "分類した。全 ", math(String.raw`4{,}608`),
        " 辺で非自明成分はちょうど一個であり、その形は一つの軌道が二つへ分裂するもの（",
        math(String.raw`4{,}096`), " 辺）か、二つの軌道が一つへ合併するもの（",
        math(String.raw`512`), " 辺）のどちらかに限られる。成分内で軌道長の総和は保存され、",
        "他の軌道は全て不変である。分裂で生じる短い側の軌道長は ",
        math(String.raw`2,4,6`), " のいずれかで、長さ ", math(String.raw`2`),
        " の軌道が生じる分裂が ", math(String.raw`3{,}456`),
        " 辺と大半を占める。従って覆えないファイバーの大域対応の規則は、軌道全体の組み替えでは",
        "なく、一つの軌道の局所的な切断または二つの軌道の局所的な接合として探せる。",
        "検算は有限集合の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_local_cut_join",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "軌道の分裂・合併で変わる後続遷移は一つまたは二つの頂点に局在する（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、像の置換を元の置換の動く向き付き辺集合へ",
        "引き戻して後続辺の違いを調べた（sagemath/check/even-subgraph-orbit-local-cut-join）。",
        "全 ", math(String.raw`4{,}608`), " 候補辺のうち ", math(String.raw`2{,}816`),
        " 本は一つの頂点で二本の後続遷移を変更し、", math(String.raw`1{,}792`),
        " 本は二つの頂点でそれぞれ二本の後続遷移を変更する。それ以外の頂点から出る遷移は",
        "変わらない。元の一軌道の中だけで変更する ",
        math(String.raw`4{,}096`), " 本が二分裂を、異なる二軌道にまたがる交換を含む ",
        math(String.raw`512`), " 本が合併を起こす。従って一般の辺長へ持ち上げる候補は、",
        "一つまたは二つの頂点で二本ずつの後続遷移を変更する局所操作として探せる。検算は有限集合と",
        "有限写像の等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_swap_rule",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "局所変更の交換形だけでは候補を一意に選べない（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、局所変更の交換形と置換ごとの候補数を調べた",
        "（sagemath/check/even-subgraph-orbit-swap-rule）。一頂点で二本の後続遷移が変わる ",
        math(String.raw`2{,}816`), " 本は、すべて二本の元の後続を交換する。二頂点で二本ずつ変わる ",
        math(String.raw`1{,}792`), " 本は、各頂点の新しい後続対が他方の元の後続対に丸ごと一致する",
        "交差交換ではない。すべての候補で、各頂点の新しい後続対は自身の元の後続を一本と",
        "他方の元の後続を一本含む。候補元となる置換 ", math(String.raw`2{,}624`),
        " 個のうち、候補が一本だけのものは ", math(String.raw`640`), " 個、二本あるものは ",
        math(String.raw`1{,}984`), " 個だった。一頂点交換の候補数も零本・一本・二本に分かれる。",
        "従って局所形だけでは置換ごとの候補を一意に選べない。次は二頂点変更で交換される",
        "一本ずつを区別する配置と、二候補の間を分ける規則を調べる。検算は有限集合と有限写像の",
        "等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_candidate_discrimination",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "所属の型と軌道形では候補を区別できない（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、二頂点変更の受け渡しの配置と、二候補を分ける",
        "不変量を調べた（sagemath/check/even-subgraph-orbit-candidate-discrimination）。",
        "二頂点変更 ", math(String.raw`1{,}792`), " 本の各頂点では、二本の変更到着のうち",
        "ちょうど一本が同じ頂点のもう一方の元の後続を受け取り（交差到着）、もう一本が",
        "他方の頂点の元の後続を受け取る（受領到着）。（交差到着, 受領到着, 輸出後続, ",
        "受領後続）の基底辺の所属（反転対の辺集合 ", math(String.raw`D`), "・単純通過の辺集合 ",
        math(String.raw`E`), "・その外）の型は 4 種にちょうど ", math(String.raw`896`),
        " 頂点ずつ分かれ、外の辺は一度も現れないが、交差到着と受領到着が同所属になる頂点が全 ",
        math(String.raw`3{,}584`), " 頂点中 ", math(String.raw`1{,}792`),
        " あるため、所属の型だけでは交差と受領を区別できない。候補を二本持つ ",
        math(String.raw`1{,}984`), " 置換の二候補を（変更頂点数, 軌道変化の形）で比べると ",
        math(String.raw`1{,}056`), " 対は同形であり、この不変量でも二候補を区別できない。",
        "合併は合併としか対にならず、一頂点と二頂点の混合対は分裂だけに現れる。また一頂点変更 ",
        math(String.raw`2{,}816`), " 本はすべて長さ ", math(String.raw`2`),
        " の軌道を切り出す分裂である。従って候補を分ける規則は、所属の型と軌道形より細かい",
        "配置（切断点の位置・受け渡す辺の同定）まで見る必要がある。検算は有限集合と有限写像の",
        "等号だけで完結し、浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_cut_location",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "二候補の大部分は切断・接合する頂点の位置で区別できる（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーで、候補を二本持つ ", math(String.raw`1{,}984`),
        " 置換の二候補を、変更頂点・変更到着辺・変更後続の順に比較した",
        "（sagemath/check/even-subgraph-orbit-cut-location）。変更頂点集合が異なるものは ",
        math(String.raw`1{,}792`), " 個であり、粗い軌道形では区別できなかった候補を含む大部分は、",
        "切断・接合する頂点の位置まで見れば区別できる。残る ", math(String.raw`192`),
        " 個では、変更する向き付き到着辺の集合、基底辺の多重集合、元の動く向き付き辺集合へ",
        "引き戻した変更後続の対応まで二候補で全て一致した。従ってこの比較で捉える局所操作としては",
        "二候補を区別できず、像側の向きを元側へ戻す前にだけ違いが残る。",
        "次は、位置が異なる二候補から平行移動や回転に依存せず一方を選び、その選択が候補辺の",
        "両端で一致する規則を調べる。検算は有限集合と有限写像の等号だけで完結し、",
        "浮動小数点は使わない。",
      ]),
    ],
  },
  {
    id: "note_kac_ward_claim_selection_even_subgraph_action_character_translation_stabilizer",
    targets: [
      "claim_selection_even_subgraph_action_character",
      "claim_selection_sum_character_evaluation",
    ],
    title: { text: "二候補の選択に平行移動の対称性の障害は無い（一辺二の全数観察）" },
    body: [
      paragraph([
        "単一の偶部分グラフでは覆えない一辺 ", math(String.raw`L=2`), " の ",
        math(String.raw`16`), " ファイバーについて、非自明な平行移動（",
        math(String.raw`3`), " 通り）が ", math(String.raw`(D,E)`),
        " を固定するかを全数で調べた",
        "（sagemath/check/even-subgraph-orbit-translation-stabilizer）。どのファイバーも",
        "固定されず、従って ", math(String.raw`(D,E,\varphi)`),
        " を固定する非自明な平行移動は存在せず、候補を二本持つ ", math(String.raw`1{,}984`),
        " 置換のどれについても二候補を入れ替える平行移動はない。すなわち、平行移動と可換な",
        "選択規則が二候補から一方を選ぶことを妨げる対称性の障害は無い。さらに覆えない ",
        math(String.raw`16`), " ファイバーの集合は平行移動で閉じ、大きさ ",
        math(String.raw`4`), " の軌道がちょうど ", math(String.raw`4`),
        " 本に分かれる。ただし、この検算は異なるファイバー間で候補辺集合が平行移動と可換であることを",
        "確かめていないので、代表での選択を残りへ延長できるとは結論しない。次は候補辺集合の",
        "平行移動共変性を調べる。",
        "検算は有限集合と有限写像の等号だけで完結し、浮動小数点は使わない。",
      ]),
      paragraph([
        "続く全数検査では、記録済み候補辺集合が一致したのはファイバーと非自明な平行移動の全 ",
        math(String.raw`48`), " 組中 ", math(String.raw`20`), " 組だけだった。移動した候補辺 ",
        math(String.raw`13{,}824`), " 本はすべて移動先でも符号反転候補として有効だが、そのうち延べ ",
        math(String.raw`3{,}584`), " 本が記録済みの移動先候補辺集合に含まれない。従って非共変性は",
        "候補の幾何ではなく、各偶部分グラフについて最初に見つかった候補だけを記録する縮約に由来する。",
        "次は全ての有効候補を保持した共変な候補辺集合を作り直す。",
      ]),
      paragraph([
        "全ての位相反転候補を保持して重複だけを除いた集合を作り直すと、全 ",
        math(String.raw`48`), " 組で平行移動と可換になった",
        "（sagemath/check/even-subgraph-orbit-all-phase-edges）。候補元は ",
        math(String.raw`2{,}624`), " 置換、異なる候補辺は ", math(String.raw`6{,}400`),
        " 本であり、候補数は一本が ", math(String.raw`640`), " 個、二本が ",
        math(String.raw`768`), " 個、三本が ", math(String.raw`640`), " 個、四本が ",
        math(String.raw`576`), " 個である。一頂点変更は縮約前後で同じ ",
        math(String.raw`2{,}816`), " 本だったが、二頂点変更は ",
        math(String.raw`1{,}792`), " 本から ", math(String.raw`3{,}584`),
        " 本へ、二軌道の合併は ", math(String.raw`512`), " 本から ",
        math(String.raw`1{,}024`), " 本へ増えた。従って縮約は二頂点変更と合併の候補を",
        "半分落としていた。以後はこの共変な全候補集合の上で選択規則を調べる。",
        "検算は有限集合・有限写像と ", math(String.raw`\mathbb{Q}(\zeta_8)`),
        " の等号だけで完結し、浮動小数点は使わない。",
      ]),
      paragraph([
        "共変な全候補集合では、全 ", math(String.raw`6{,}400`),
        " 本の候補辺のどれについても逆向き辺（終点を始点とする候補辺）は集合に含まれず、",
        "候補関係は完全に反対称である",
        "（sagemath/check/even-subgraph-orbit-locality-selection）。候補元 ",
        math(String.raw`2{,}624`), " 置換の一頂点変更の候補の本数は零本が ",
        math(String.raw`576`), " 個、一本が ", math(String.raw`1{,}280`),
        " 個、二本が ", math(String.raw`768`),
        " 個であり、一頂点候補が一意な ", math(String.raw`1{,}280`),
        " 個のうち選んだ先が候補元でないものが ", math(String.raw`640`),
        " 個、選んだ先が候補元だが別の置換を選ぶものが ", math(String.raw`640`),
        " 個で、互いに選び合う対は零である。局在頂点数と軌道変化は平行移動で不変なので",
        "この規則は平行移動と可換だが、両端の一致する選択にはならない。候補関係が",
        "反対称である以上、両端の一致は逆向き辺の相互選択ではなく、候補辺を無向対として",
        "重複なく選ぶこととして問う必要がある。次は選んだ先が別の置換を選ぶ ",
        math(String.raw`640`), " 個の衝突の構造を調べる。",
      ]),
      paragraph([
        "一意な一頂点候補による選択辺 ", math(String.raw`1{,}280`),
        " 本を無向化すると、接する置換は ", math(String.raw`1{,}456`),
        " 個で、連結成分は長さ ", math(String.raw`4`), " の道 ",
        math(String.raw`32`), " 個と、中心から四本の長さ ", math(String.raw`2`),
        " の腕が出る木 ", math(String.raw`144`),
        " 個からなる森である（sagemath/check/even-subgraph-orbit-locality-collision）。",
        "各腕の向きは外端から中間点を経て中心へ向かい、衝突する ",
        math(String.raw`640`),
        " 本はすべて二段目で一意選択を持たない中心へ達する。二段で変更する頂点は全て異なる。",
        "各成分の頂点数は奇数なので、一意な一頂点候補だけからなるこの森には完全マッチングが無い。",
        "従って残りの一頂点候補または二頂点変更候補も必要である。次は各中心に入る腕と、",
        "同じ成分の頂点に接する残りの候補辺の配置を比較する。",
      ]),
      paragraph([
        "衝突森の全 ", math(String.raw`176`),
        " 中心は位相反転候補を一本も持たない置換である",
        "（sagemath/check/even-subgraph-orbit-collision-forest-context）。残りの候補対 ",
        math(String.raw`5{,}120`),
        " 本はどの成分の内部にも一本も残らず、成分に接するものは全て成分の外へ出る。",
        "内訳は、成分から森の外の頂点へ出るものが一頂点変更 ", math(String.raw`1{,}504`),
        " 本・二頂点変更の分裂 ", math(String.raw`1{,}280`), " 本・合併 ",
        math(String.raw`512`), " 本、異なる二成分を結ぶ二頂点変更の分裂が ",
        math(String.raw`640`), " 本、森に触れないものが一頂点変更 ",
        math(String.raw`32`), " 本・二頂点変更の分裂 ", math(String.raw`640`),
        " 本・合併 ", math(String.raw`512`),
        " 本である。外へ出る残候補は道の成分で ", math(String.raw`8`),
        " 本、木の成分で ", math(String.raw`30`),
        " 本と一定であり、各中心には成分の外から候補辺がちょうど ",
        math(String.raw`2`),
        " 本入る。従って奇数頂点の各成分を対で覆うには成分の外と対にする辺が少なくとも一本要る。",
        "各中心には外から入る候補辺が二本ある。次はこの外部辺の相手の",
        "配置から、平行移動と可換な無向対の選択規則を探す。",
      ]),
      paragraph([
        "未被覆の ", math(String.raw`16`),
        " ファイバーは、平行移動による大きさ ", math(String.raw`4`),
        " の軌道を ", math(String.raw`4`),
        " 本なす（sagemath/check/even-subgraph-orbit-translation-covariant-matching）。",
        "各軌道の代表ファイバーで共変な全候補グラフの完全マッチングを一つ構成し、",
        "平行移動で残りへ運ぶと、全 ", math(String.raw`2{,}816`),
        " 置換が ", math(String.raw`1{,}408`),
        " 対へ重複なく分かれた。選ばれた対は全て位相反転候補であり、",
        math(String.raw`16`), " ファイバーと ", math(String.raw`4`),
        " 平行移動の全 ", math(String.raw`64`),
        " 組でマッチングの像が移動先のマッチングと一致した。従って一辺二では、",
        "局所規則に限らなければ、平行移動と可換な符号反転完全マッチングが存在する。",
        "一般の辺長ではファイバーの平行移動作用が自由とは限らないので、次は固定部分を持つ",
        "軌道でも代表上のマッチングを矛盾なく運べる条件を切り出す。",
      ]),
      paragraph([
        "代表上の完全マッチングを軌道へ運べる条件は、固定部分群による不変性である",
        "（sagemath/check/even-subgraph-orbit-transport-stabilizer-condition）。",
        "有限群がファイバーを移し候補グラフを同型で移すとき、代表 ",
        math(String.raw`r`), " の完全マッチング ", math(String.raw`M`),
        " の運搬 ", math(String.raw`g\cdot r\mapsto g\cdot M`),
        " が well-defined であることは、", math(String.raw`M`),
        " が固定部分群 ", math(String.raw`\mathrm{Stab}(r)`),
        " の全元で不変であることと同値である。実際、運搬が well-defined なら恒等元と固定部分群の元を比較して不変性を得る。",
        math(String.raw`g\cdot r=h\cdot r`), " なら ",
        math(String.raw`h^{-1}g\in\mathrm{Stab}(r)`), " なので、逆に固定部分群不変性から ",
        math(String.raw`g\cdot M=h\cdot(h^{-1}g)\cdot M=h\cdot M`),
        " を得て運搬は well-defined になる。そのとき運んだ族は候補辺だけの",
        "完全マッチングで群の全元と可換になる。逆に共変な族はこの運搬に限るので、",
        "共変族の存在は代表の候補グラフに固定部分群不変な完全マッチングが存在することと",
        "同値である。固定部分群が非自明な有限の実例では、各ファイバーが完全マッチングを",
        "二つ持つのに不変なものが無く共変族が存在しないことがあるため、",
        "各ファイバーの完全マッチングの存在だけでは足りない。一辺二の未被覆 ",
        math(String.raw`16`),
        " ファイバーでは平行移動の固定部分群が自明なのでこの条件は空であり、",
        "前段の運搬がそのまま通る。次はこの条件を一般の辺長の平行移動作用へ",
        "適用するため、未被覆ファイバーの固定部分群の非自明性を辺長ごとに調べる。",
        "三つの有限例の全数検査はこの一般証明そのものではなく、不変マッチングが存在する場合と存在しない場合、および自由作用の場合を具体化する検算である。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L`), " のトーラスの非零平行移動 ",
        math(String.raw`(a,b)`), " の位数を ", math(String.raw`m`),
        " とする。この平行移動は水平辺と垂直辺の各集合へ自由に作用するので、",
        "全ての基底辺軌道の長さは ", math(String.raw`m`), " である。従ってファイバー ",
        math(String.raw`(D,E)`), " が固定されるなら ", math(String.raw`D`), " と ",
        math(String.raw`E`), " はそれぞれ辺軌道の和であり、",
        math(String.raw`m\mid |D|`), " かつ ", math(String.raw`m\mid |E|`),
        " が必要である（sagemath/check/translation-fiber-stabilizer-orbit-divisibility）。",
        "辺長二から八までの全非零平行移動で軌道長と位数の一致を検査した。特に素数辺長では ",
        math(String.raw`L\mid |D|,|E|`), " が必要になる。ただし十分ではない。",
        "一辺二の未被覆ファイバーは全てこの可除条件を満たす一方、実際の固定部分群は自明だった。",
        "次は一般の辺長の候補で、辺数による除外後に ", math(String.raw`D,E`),
        " が辺軌道の和そのものかを調べる。",
      ]),
      paragraph([
        "固定されるファイバー鍵は、軌道の和で尽くされる",
        "（sagemath/check/translation-fixed-fiber-orbit-sum-count）。一辺二の全 ",
        math(String.raw`881`), " 鍵（", math(String.raw`D,E`), " 互いに素・",
        math(String.raw`E`), " 偶部分グラフ）では、各非零平行移動の固定鍵の集合が",
        "「各辺軌道を ", math(String.raw`D`), "・", math(String.raw`E`),
        "・どちらでもない、の三択で割り当て ", math(String.raw`E`),
        " が偶部分グラフになるもの」と全数一致した。個数は軸方向で各 ",
        math(String.raw`45`), "、対角で ", math(String.raw`41`),
        " であり、可除条件だけを満たす ", math(String.raw`441`),
        " 鍵の真部分集合である。一般の辺長でも固定鍵は軌道割当の列挙で数えられ、一辺三の対角で ",
        math(String.raw`189`), "（可除条件だけなら ", math(String.raw`299{,}187`),
        "）、一辺四の対角で ", math(String.raw`881`), "、一辺五では方向により ",
        math(String.raw`4{,}149`), " と ", math(String.raw`3{,}969`),
        " だった。同じ位数でも方向で個数が違うのは偶部分グラフ条件が軌道の幾何に依存するためである。",
        "任意の一辺 ", math(String.raw`L\ge 2`), " と非零平行移動について、一つの辺軌道 ",
        math(String.raw`O`), " を取り ", math(String.raw`(D,E)=(O,\varnothing)`),
        " とすれば非自明な固定鍵になる。従って固定鍵は全ての辺長で非自明に存在するので、",
        "一般の辺長への持ち上げでは固定部分群が",
        "非自明な軌道の運搬条件を避けて通れない。次は固定鍵のうち単一の偶部分グラフで",
        "覆えないものが実際に現れるかを、小さい辺長の未被覆判定と突き合わせて調べる。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L=2`), " では、単一の偶部分グラフで一様被覆できない ",
        math(String.raw`16`), " ファイバーと、非零平行移動で固定されるファイバーの交わりは",
        "三方向とも空だった（sagemath/check/translation-fixed-uncovered-fiber-intersection）。",
        "固定の数え上げは実際に置換を持つ全 ", math(String.raw`609`),
        " ファイバー鍵の上で行い、固定鍵は二つの軸方向で各 ", math(String.raw`35`),
        "、対角方向で ", math(String.raw`37`), " あるが、未被覆ファイバーは全て平行移動作用が自由である。",
        "従って一辺二の未被覆ファイバーで得た共変マッチングだけから、固定部分群が非自明な",
        "一般の辺長へ規則を延長することはできない。次は固定鍵の候補グラフを直接調べる。",
      ]),
      paragraph([
        "固定部分群が非自明で一様被覆検査の対象になる鍵の候補グラフには、固定部分群不変な完全マッチングが無い",
        "（sagemath/check/translation-fixed-fiber-invariant-matching）。一辺 ",
        math(String.raw`L=2`), " で固定部分群が非自明な鍵は ", math(String.raw`89`),
        " 個あり、うち ", math(String.raw`81`),
        " 個は有効な偶部分グラフを持たず一様被覆検査の対象外である",
        "（対角方向の固定鍵 ", math(String.raw`37`), " 個は全て対象外）。対象に入る",
        "軸方向固定の ", math(String.raw`8`), " 鍵（固定部分群の位数 ", math(String.raw`2`),
        "、ファイバーの大きさ ", math(String.raw`32`), " が ", math(String.raw`4`),
        " 個・", math(String.raw`288`), " が ", math(String.raw`4`),
        " 個）では、位相反転候補辺の完全マッチングは存在するのに、固定部分群で不変な",
        "ものが一つも無い。判定は、不変な完全マッチングの対の両端で点別固定部分群が",
        "一致することから、頂点軌道の商二部グラフの完全マッチングとの一対一対応で行い、",
        "存在しない側は商の完全マッチングの不在で確定した。従って一辺二の時点で、",
        "平行移動群全体と可換な符号反転完全マッチング族は位相反転候補辺からは作れない。",
        "共変性の要求は固定部分群が自明な軌道に限るか、この ", math(String.raw`8`),
        " 鍵で候補辺以外の構造を使う必要がある。次はこの ", math(String.raw`8`),
        " 鍵の商グラフでどの頂点軌道が孤立するかを調べ、共変性を課す部分群を絞る。",
      ]),
      paragraph([
        "商二部グラフで孤立する負位相側の頂点軌道は、固定部分群が置換を点別に固定する軌道と",
        "ちょうど一致する。ファイバーの大きさが ", math(String.raw`32`),
        " の四鍵では正側 ", math(String.raw`4`), " 軌道・負側 ", math(String.raw`8`),
        " 軌道が孤立し、大きさが ", math(String.raw`288`),
        " の四鍵では負側の点別固定 ", math(String.raw`24`),
        " 軌道だけが孤立する。巻き付き文字が非自明な全 ", math(String.raw`64`),
        " 鍵のうち二つの軸平行移動は各 ", math(String.raw`4`),
        " 鍵を固定するが、対角平行移動 ", math(String.raw`(1,1)`),
        " が固定する鍵は零である。従って対角部分群の作用は自由で、各軌道の代表の",
        "完全マッチングを運べば対角部分群と可換な族を作れる。一方、各軸部分群には",
        "孤立軌道を持つ固定鍵がある。よって一辺二で位相反転候補辺だけを使える非自明な",
        "平行移動部分群は対角部分群に絞られる",
        "（sagemath/check/translation-fixed-fiber-invariant-matching）。次はこの対角共変族を",
        "実際に構成し、選択和の文字評価へ合成する。",
      ]),
      paragraph([
        "対角共変族は実在する（sagemath/check/translation-diagonal-covariant-matching）。",
        "一様被覆検査の対象全 ", math(String.raw`64`),
        " 鍵の上で対角平行移動部分群 ", math(String.raw`\{(0,0),(1,1)\}`),
        " の作用は自由で、対角軌道 ", math(String.raw`32`),
        " 個の各代表に全候補辺の完全マッチングを構成して ", math(String.raw`(1,1)`),
        " で運ぶと、", math(String.raw`64`),
        " 鍵全てで候補辺だけの完全マッチング（対の総数 ", math(String.raw`2{,}624`),
        "）になり、族は対角部分群と可換である。候補関係は非対称なので、",
        "正負両側の置換から候補辺を集めて二部グラフを作る必要がある。合成として、",
        "各鍵の四つのねじれ位相和は対ごとの相殺で全て零になるので、巻き付き文字が",
        "非自明な全ファイバーの選択和への寄与は四スピン構造すべてで消える。",
        "軸方向固定の ", math(String.raw`8`),
        " 鍵も対角部分群では自由軌道に入り、この構成で覆われる。",
        "次は一般の辺長で、対角部分群に対応する部分群の固定鍵が零になるかを",
        "小さい辺長で判定する。",
      ]),
      paragraph([
        "対角平行移動で固定され、かつ選択文字が非自明な鍵の有無は辺長の偶奇で変わる",
        "（sagemath/check/translation-diagonal-fixed-nontrivial-character）。",
        "対角平行移動の辺軌道の和として書ける鍵を一辺二から八まで全数検査すると、",
        "偶数辺長では該当する鍵が零だったが、奇数辺長では全基底辺集合を単純通過辺集合とする",
        math(String.raw`(D,E)=(\varnothing,E_L)`),
        " の一鍵が該当した。従って一辺二の自由作用は一般には持ち上がらず、一辺三で既に破れる。",
        "一方、観察した範囲で障害は奇数辺長のこの一鍵だけに集中する。次はこの全辺鍵で、",
        "位相反転候補辺に対角部分群不変な完全マッチングが存在する条件を調べる。",
      ]),
      paragraph([
        "奇数辺長の全辺鍵では、対角固定置換の位相ベクトルの数え上げに障害は現れない",
        "（sagemath/check/translation-diagonal-full-key-fixed-permutation-phase）。",
        "不変なマッチングは固定置換を固定置換同士で対にするしかないので、固定置換の",
        "位相ベクトルの多重集合が符号反転で不変であることが必要条件になる。全辺鍵の",
        "ファイバーは氷型配向（各頂点で入 ", math(String.raw`2`),
        " 出 ", math(String.raw`2`),
        "）と各頂点の入辺から出辺への全単射の組と一対一に対応し、対角固定置換は一辺三・五・七で",
        math(String.raw`80,\ 1{,}088,\ 16{,}640`),
        " 個ある。三つの辺長すべてで多重集合は符号反転不変で、四つのねじれ位相和も零だった。",
        "従って対角部分群の障害はこの水準では検出されない。次は固定置換の間の位相反転候補辺を",
        "構成し、固定置換だけの部分グラフに完全マッチングがあるかを判定する。",
      ]),
      paragraph([
        "一辺三では、前段の頂点組み替え候補だけからなる対角固定置換の部分グラフに",
        "完全マッチングは無い",
        "（sagemath/check/translation-diagonal-full-key-fixed-permutation-matching）。",
        "固定置換 ", math(String.raw`80`), " 個は正負位相側に各 ", math(String.raw`40`),
        " 個あり、候補辺は重複を除いて ", math(String.raw`368`),
        " 本で両側に孤立点は無い。しかし最大マッチングは ", math(String.raw`16`),
        " 対に留まり、未対応の正側頂点から交互路で得る Hall 集合は ",
        math(String.raw`|S|=32`), "、", math(String.raw`|N(S)|=8`),
        " である。従って位相ベクトルの多重集合が符号反転不変であるという必要条件は",
        "十分ではない。次は Hall 障害を担う固定置換の局所形を分類し、候補族を拡張するか",
        "別の相殺構造へ移るかを判定する。",
      ]),
      paragraph([
        "Hall 障害は頂点組み替え候補という局所機構の配向水準の集中に由来し、",
        "相殺構造そのものは固定置換の位相ベクトルの直接対で生き残る",
        "（sagemath/check/translation-diagonal-full-key-hall-structure）。",
        "一辺三の固定置換 ", math(String.raw`80`),
        " 個を不変氷型配向（", math(String.raw`10`), " 個、各 ", math(String.raw`8`),
        " 置換）で分類すると、各配向は正負位相に ", math(String.raw`4+4`),
        " で分かれる。候補辺が使える偶部分グラフ ", math(String.raw`H`),
        "（対角不変・巻き付き文字非自明）は ", math(String.raw`8`),
        " 個で全て使用済みなので、この候補族は拡張できない。配向水準の候補グラフは",
        "次数 ", math(String.raw`8`), " の枢軸配向 ", math(String.raw`2`),
        " 個と次数 ", math(String.raw`2`), " の周辺配向 ", math(String.raw`8`),
        " 個の二重星形で、Hall 集合 ", math(String.raw`S`),
        " は周辺配向の正側全員、", math(String.raw`N(S)`),
        " は枢軸配向の負側全員と一致する。一方、位相ベクトルは二値 ",
        math(String.raw`\{v_0,-v_0\}`), "（", math(String.raw`v_0=(1,-1,-1,1)`),
        "、各 ", math(String.raw`40`),
        " 個）に退化しており、正側は全員 ", math(String.raw`v_0`),
        "、負側は全員 ", math(String.raw`-v_0`),
        " を持つ。従って正側と負側の任意の全単射が四位相を反転する対を与え、",
        "固定点上ではどの全単射も対角平行移動と自明に可換である。整列順の全単射 ",
        math(String.raw`40`),
        " 対を構成し全対の位相反転を検証した。次はこの直接対を非固定軌道の",
        "運搬マッチングと合成し、一辺三の全辺鍵ファイバー全体に対角共変な",
        "符号反転完全マッチングが存在するかを判定する。",
      ]),
      paragraph([
        "一辺三の全辺鍵ファイバー全体には、対角共変な位相反転完全マッチングが存在する",
        "（sagemath/check/translation-diagonal-full-key-covariant-matching）。固定置換 ",
        math(String.raw`80`), " 個には前段の直接対 ", math(String.raw`40`),
        " 対を使う。残る置換は大きさ ", math(String.raw`3`),
        " の自由軌道 ", math(String.raw`25{,}232`),
        " 個に分かれ、位相ベクトル ", math(String.raw`v_0=(1,-1,-1,1)`),
        " と ", math(String.raw`-v_0`), " を持つ軌道が各 ",
        math(String.raw`12{,}616`),
        " 個ある。反対位相の軌道を整列順に対にして代表上の対を平行移動で運ぶと、",
        "固定点の対と合わせて全 ", math(String.raw`75{,}776`),
        " 置換を ", math(String.raw`37{,}888`),
        " 対へ分けられる。全対の位相反転、一回被覆、対角共変性、四位相和の零を",
        "等号 assert で検証した。これは頂点組み替え候補だけに限定しない相殺である。",
        "次は同じ固定点と自由軌道の分解を一般の奇数辺長へ持ち上げられるかを判定する。",
      ]),
      paragraph([
        "全辺鍵の位相ベクトルは符号公式で書ける",
        "（sagemath/check/translation-diagonal-full-key-phase-sign-formula）。",
        "置換 ", math(String.raw`\varphi`), " の位相寄与は、巡回ごとの符号の積 ",
        math(String.raw`(-1)^{c(\varphi)}`), "（", math(String.raw`c`),
        " は巡回数）、回転積の積 ", math(String.raw`(-1)^{T(\varphi)}`),
        "（非後退な閉歩道の四半回転の和は ", math(String.raw`4`),
        " の倍数なので各回転積は ", math(String.raw`\pm1`), "。", math(String.raw`T`),
        " は総回転数）、ねじれ ", math(String.raw`(a,b)`),
        " の縫い目寄与（動く辺集合が全基底辺を各一度ずつ使うので合計 ",
        math(String.raw`(L,L)`), " 本、成分ごとに ",
        math(String.raw`(-1)^{aL+bL}`), "）の三つの積に分解される。従って ",
        math(String.raw`\varepsilon(\varphi)=(-1)^{c(\varphi)+T(\varphi)}`),
        " として、位相ベクトルは奇数辺長で ",
        math(String.raw`\varepsilon(\varphi)\cdot(1,-1,-1,1)`),
        "、偶数辺長で ", math(String.raw`\varepsilon(\varphi)\cdot(1,1,1,1)`),
        " に等しい。一辺三の二値性は偶然ではなく全ての奇数辺長で成り立つ。",
        "一辺二・三の全ファイバーと一辺三・五・七の対角固定置換で公式との一致を",
        "等号 assert で固定した。", math(String.raw`\varepsilon`),
        " の分布は一辺三の全ファイバーで各 ", math(String.raw`37{,}888`),
        "、固定置換の層で一辺三・五・七が各 ", math(String.raw`40,\ 544,\ 8{,}320`),
        " と均衡した（一辺二の全ファイバーは ", math(String.raw`160`), " 対 ",
        math(String.raw`128`),
        " で不均衡だが、偶数辺長は文字が自明なので均衡は要らない）。",
        "従って対角共変な位相反転完全マッチングの一般の奇数辺長への持ち上げは、",
        math(String.raw`\varepsilon`),
        " の個数が軌道サイズの各層で均衡すること、とくにファイバー全体で ",
        math(String.raw`\sum_\varphi\varepsilon(\varphi)=0`),
        " となることへ帰着した。次はこの数え上げの均衡を一般の奇数辺長で示す",
        "構造（符号を反転する明示的な対合など）を探す。",
      ]),
      paragraph([
        "奇数辺長の全辺鍵ファイバーでは、局所対応の交換により ",
        math(String.raw`\varepsilon`), " の総和が零になる",
        "（sagemath/check/translation-full-key-local-pairing-involution）。",
        "氷型配向の頂点で入辺二本が反対方向なら直線型、そうでなければ曲がり型と呼ぶ。",
        "全頂点が直線型なら各頂点は水平二辺が入る型または垂直二辺が入る型であり、",
        "隣接頂点ごとに型が反転する。しかし奇数周期ではこの交互配置は閉じないので、",
        "曲がり型頂点が少なくとも一つある。辞書式最小の曲がり型頂点で入辺二本から",
        "出辺二本への対応を交換すると、配向と選択頂点を保つ不動点のない対合になる。",
        "二像の交換は置換の巡回数の偶奇を反転し、曲がり型の四つの局所方向配置では",
        "交換前後の四半回転和が等しいので総回転数は変わらない。従って ",
        math(String.raw`\varepsilon(\varphi)=(-1)^{c(\varphi)+T(\varphi)}`),
        " は反転し、", math(String.raw`\sum_\varphi\varepsilon(\varphi)=0`),
        " を得る。局所六配置と一辺三の全 ", math(String.raw`75{,}776`),
        " 置換で対合性・ファイバー保存・符号反転を等号 assert で固定した。",
        "この辞書式選択は対角平行移動と可換とは限らないため、次は安定化群の各軌道で",
        "曲がり型頂点を一括交換する形へ持ち上げ、軌道サイズの各層の均衡を示す。",
      ]),
      paragraph([
        "部分群固定集合の一括交換対合により、", math(String.raw`\varepsilon`),
        " の均衡は安定化群位数の各層へ持ち上がる",
        "（sagemath/check/translation-full-key-stabilizer-orbit-involution）。",
        "奇数辺長 ", math(String.raw`L`), " の約数 ", math(String.raw`d`),
        " ごとに位数 ", math(String.raw`d`), " の部分群 ", math(String.raw`H_d`),
        " を固定し、", math(String.raw`H_d`), "-固定集合 ", math(String.raw`F_d`),
        " の上で辞書式最小の曲がり型頂点の ", math(String.raw`H_d`),
        "-軌道（大きさちょうど ", math(String.raw`d`),
        "。対角平行移動は頂点に自由に作用する）を一括交換すると、交換集合が ",
        math(String.raw`H_d`), "-不変なので ", math(String.raw`F_d`),
        " で閉じ、不動点のない対合になる。互換 ", math(String.raw`d`),
        " 個の合成で巡回数の偶奇が ", math(String.raw`d`), " 回反転し、",
        math(String.raw`d`), " が奇数なので ", math(String.raw`\varepsilon`),
        " は反転する。従って各 ", math(String.raw`d\mid L`), " で ",
        math(String.raw`\sum_{\varphi\in F_d}\varepsilon(\varphi)=0`),
        " となり、正確な安定化群位数の層 ",
        math(String.raw`E_d=F_d\setminus\bigcup_{d<d'\mid L}F_{d'}`),
        " でも約数束の Möbius 反転で均衡する。", math(String.raw`\varepsilon`),
        " は平行移動不変なので各軌道サイズの層で正負の軌道が同数になり、正確な",
        "安定化群が等しい反対符号の代表を対にして ",
        math(String.raw`g\cdot r\mapsto g\cdot r'`),
        " と運べば、対角共変な符号反転完全マッチングが一般の奇数辺長で得られる。",
        "一方、置換ごとに自分の安定化群の軌道を交換する操作は対合にならない",
        "（一辺三では固定置換の単頂点交換像 ", math(String.raw`80`),
        " 個で安定化群が保存されない）。部分群を先に固定することが構成の要である。",
        "一辺三の ", math(String.raw`F_3`), "（", math(String.raw`80`),
        " 置換）と一辺五の ", math(String.raw`F_5`), "（", math(String.raw`1{,}088`),
        " 置換）の対合性、一辺三の正確な層の均衡（位数 ", math(String.raw`1`),
        " で各 ", math(String.raw`37{,}848`), "、位数 ", math(String.raw`3`),
        " で各 ", math(String.raw`40`), "）、運んだ ", math(String.raw`37{,}888`),
        " 対の一回被覆・対角共変性・符号反転を等号 assert で固定した。",
        "次はこの共変マッチングを ", math(String.raw`\mathcal K=\mathcal U`),
        " と平方恒等式の合成へつなぐ。",
      ]),
      paragraph([
        "奇数辺長の全辺鍵では、置換側と選択側の寄与がともに零になり、平方恒等式の",
        "同じ次数の項で一致する",
        "（sagemath/check/translation-full-key-square-identity-composition）。",
        "全辺鍵 ", math(String.raw`(D,E)=(\varnothing,E_L)`), " では、前段の対角共変な",
        "符号反転完全マッチングにより四つのスピン構造の位相寄与が対ごとに相殺するので ",
        math(String.raw`\mathcal K^{a,b}_L(\varnothing,E_L)=0`), " である。選択側では奇数辺長ゆえに ",
        math(String.raw`E_L`), " の巻き付き偶奇が ", math(String.raw`(1,1)`), " であり、",
        "水平一周閉路 ", math(String.raw`H_0\subseteq E_L`), " の巻き付き偶奇は ",
        math(String.raw`(1,0)`), " なので ",
        math(String.raw`\chi_{E_L}(H_0)=(-1)^{1\cdot0+1\cdot1}=-1`), " となる。",
        ref("claim_selection_sum_character_evaluation"), " により ",
        math(String.raw`\mathcal U^{a,b}_L(\varnothing,E_L)=0`), " であり、従ってこの添字では ",
        math(String.raw`\mathcal K=\mathcal U=0`), " が成り立つ。",
        ref("claim_kac_ward_determinant_fiber_stratified_phase_sum"), " と ",
        ref("claim_signed_even_subgraph_square_stratified"), " の二つの層別で、この添字は同じ次数 ",
        math(String.raw`2\lvert D\rvert+\lvert E\rvert=2L^2`), " の項を与え、係数は両側とも零になる。",
        "これは平方恒等式の全辺鍵だけを閉じるものであり、ほかの添字の同定はまだ示していない。",
        "一辺三では全 ", math(String.raw`75{,}776`), " 置換の ", math(String.raw`37{,}888`),
        " 対と全 ", math(String.raw`1{,}024`), " 選択を定義から検査し、四位相の両係数が零、",
        "次数が ", math(String.raw`18`), " で一致することを等号 assert で固定した。",
        "次は全辺鍵以外の平行移動軌道について、置換マッチングと選択文字の零和を同じ添字で対応づける。",
      ]),
      paragraph([
        "非自明な選択文字を持つ鍵は、全辺鍵を除き全て対角部分群の自由軌道に入る",
        "（sagemath/check/translation-nonfull-key-orbit-freeness）。",
        "鍵 ", math(String.raw`(D,E)`), " の選択文字の非自明性は ", math(String.raw`E`),
        " だけで決まる。一辺三の偶部分グラフ（巡回空間の ",
        math(String.raw`2^{10}=1{,}024`), " 個）のうち非自明な文字を持つものは ",
        math(String.raw`346`), " 個で、非自明性は対角平行移動 ", math(String.raw`(1,1)`),
        " と可換（軌道上で一定）である。対角固定の非自明文字の偶部分グラフは全辺集合 ",
        math(String.raw`E_L`), " ただ一つなので、全辺鍵 ",
        math(String.raw`(\varnothing,E_L)`),
        " 以外の非自明文字鍵は全て大きさちょうど ", math(String.raw`3`),
        " の自由な対角軌道に入る。鍵の総数は ",
        math(String.raw`\sum_E 2^{18-\lvert E\rvert}=148{,}033`),
        "、固定鍵は全辺鍵の ", math(String.raw`1`), " 個、自由軌道は ",
        math(String.raw`49{,}344`), " 個である。従って全辺鍵以外の非自明文字鍵では ",
        math(String.raw`\mathcal U^{a,b}_L(D,E)=0`),
        " が文字評価から軌道ごとに一括で従い（",
        ref("claim_selection_sum_character_evaluation"), "。文字は軌道上で一定）、",
        math(String.raw`\mathcal K^{a,b}_L(D,E)=0`),
        " は軌道代表一つでの符号反転完全マッチングを自由作用で運べば軌道全体へ広がる",
        "（位相寄与は平行移動共役で不変。一辺二の全鍵と一辺三の全辺鍵で等号 assert 済み）。",
        "素数の奇数辺長では全ての非零対角平行移動が同じ部分群を生成するので、",
        "固定鍵の分類は既存の一辺八までの検査と合わせて一辺五・七も覆う。",
        "最初の未検査は一辺九（真部分群 ", math(String.raw`(3,3)`),
        " の固定集合）である。残る課題は自由軌道の代表での相殺の構成である。",
      ]),
      paragraph([
        "自由軌道の代表鍵での相殺は、交差する水平・垂直の非可縮一周路を単純通過辺集合とする場合には、",
        "一意な局所交換で構成できる",
        "（sagemath/check/translation-crossing-cycles-local-involution）。一辺三で単純通過辺集合 ",
        math(String.raw`E`), " を第 ", math(String.raw`0`), " 行の水平一周路と第 ",
        math(String.raw`0`), " 列の垂直一周路の和とし、反転対辺集合 ", math(String.raw`D`),
        " を補集合の全部分集合に走らせた。実在する全 ", math(String.raw`1{,}442`),
        " 鍵・全 ", math(String.raw`5{,}768`), " 動辺配向のそれぞれに、二本の入方向と",
        "二本の出方向が同じ曲がり二方向になる頂点がちょうど一つある。この頂点の二つの局所全単射を",
        "交換すると、回転位相とねじれ符号を保ち、置換符号だけが反転する。従って全 ",
        math(String.raw`10{,}570{,}752`), " 置換は ", math(String.raw`5{,}285{,}376`),
        " 対へ分かれる。次は任意の非自明文字の偶部分グラフについて、この局所方向型の頂点が",
        "存在する条件を決めるか、存在しない場合の別の局所対合を構成する。",
      ]),
      paragraph([
        "一辺三では、任意の非自明文字の偶部分グラフの全ての均衡配向に曲がり型の次数 ",
        math(String.raw`4`), " 頂点が存在し、局所交換の対合が全ての非自明文字鍵で閉じる",
        "（sagemath/check/translation-nontrivial-key-curved-vertex-involution）。",
        "二本の像の交換で回転数を変えずに完全対合できる局所方向型は、二本の入方向と",
        "二本の出方向が同じ曲がり二方向である四型に限る。反転対辺は同じ頂点へ入方向 ",
        math(String.raw`d`), " と出方向 ", math(String.raw`d+2`),
        " を同時に与えるが、曲がり二方向の対 ", math(String.raw`\{c,c+1\}`),
        " はこの二方向を同時に含めないので、曲がり型頂点は ", math(String.raw`E`),
        " の次数 ", math(String.raw`4`), " 頂点の曲がり配向に限り、",
        math(String.raw`D`), " に依存しない。非自明文字の偶部分グラフ全 ",
        math(String.raw`346`), " 個の均衡配向は合計 ", math(String.raw`2{,}956`),
        " 個で、その全てに曲がり型頂点がある。ファイバーの置換の単純通過部分は ",
        math(String.raw`E`), " の均衡配向を誘導するので、任意の ", math(String.raw`D`),
        " についてファイバーの全置換が曲がり型頂点を持ち、辞書式最小の曲がり型頂点での",
        "局所交換は動辺集合と総回転数を保ち巡回数の偶奇だけを反転する不動点のない対合になる（",
        math(String.raw`D=\varnothing`), " の全ファイバー ", math(String.raw`115{,}688`),
        " 置換と、閉路状の反転対を付けた ", math(String.raw`696`),
        " 置換の全展開で検証した）。従って一辺三では全ての非自明文字鍵で四つのねじれの ",
        math(String.raw`\mathcal K^{a,b}_3(D,E)=0`),
        " が直接従い、軌道代表からの運搬は不要になった。文字評価による ",
        math(String.raw`\mathcal U^{a,b}_3(D,E)=0`),
        "（", ref("claim_selection_sum_character_evaluation"),
        "）と合わせ、一辺三の非自明文字鍵は平方恒等式の両側で消える。",
        "次は一般の辺長で、非自明文字の偶部分グラフの全ての均衡配向に曲がり型頂点が",
        "存在すること（曲がり型にならない次数 ", math(String.raw`4`),
        " 配置は水平二辺が入り垂直二辺が出る交差二型に限るので、その排除）を証明する。",
      ]),
      paragraph([
        "一般の辺長でも、非自明な選択文字は全ての均衡配向に曲がり型頂点を強制する",
        "（sagemath/check/translation-nontrivial-character-forces-curved-vertex）。",
        "曲がり型頂点が無いと仮定し、任意の偶部分グラフ ", math(String.raw`H\subseteq E`),
        " とその補集合 ", math(String.raw`K:=E\setminus H`), " を取る。",
        math(String.raw`H`), " と ", math(String.raw`K`),
        " が横断する頂点では、一方が水平二辺、他方が垂直二辺を取る。曲がり型が無いので",
        "局所配向は水平二辺が入り垂直二辺が出る型またはその逆であり、",
        math(String.raw`H`), " の入次数と出次数の差は横断頂点だけで ",
        math(String.raw`+2`), " または ", math(String.raw`-2`), "、ほかでは零になる。",
        "有限有向辺集合では入次数と出次数の総和が等しいため、二種の横断頂点は同数であり、",
        "横断頂点数は偶数である。一方、その偶奇はトーラスの交差形式 ",
        math(String.raw`\varepsilon_{\mathrm h}(H)\varepsilon_{\mathrm v}(K)+\varepsilon_{\mathrm v}(H)\varepsilon_{\mathrm h}(K)`),
        " に等しい。", math(String.raw`E=H\mathbin\triangle K`),
        " と交差形式の交代性により、これは選択文字の指数 ",
        math(String.raw`\varepsilon_{\mathrm h}(E)\varepsilon_{\mathrm v}(H)+\varepsilon_{\mathrm v}(E)\varepsilon_{\mathrm h}(H)`),
        " に等しい。従って全ての ", math(String.raw`H\subseteq E`),
        " で文字は ", math(String.raw`1`), " となって自明である。対偶により、非自明文字を持つ ",
        math(String.raw`E`), " の全ての均衡配向には曲がり型頂点が存在する。",
        "一辺三の互いに素な偶部分グラフ対 ", math(String.raw`8{,}589`),
        " 組で交差偶奇の式を、交差型頂点の局所偶部分集合 ", math(String.raw`16`),
        " 件で入出差の分類を等号 assert した。次はこの存在定理と局所交換を合成し、",
        "一般の辺長の全ての非自明文字鍵で ",
        math(String.raw`\mathcal K^{a,b}_L(D,E)=\mathcal U^{a,b}_L(D,E)=0`),
        " を閉じる。",
      ]),
      paragraph([
        "存在定理と局所交換の合成により、一般の辺長 ", math(String.raw`L`),
        " の全ての非自明文字鍵 ", math(String.raw`(D,E)`), " で四つのねじれの ",
        math(String.raw`\mathcal K^{a,b}_L(D,E)=\mathcal U^{a,b}_L(D,E)=0`),
        " が閉じる（sagemath/check/translation-nontrivial-key-general-composition）。",
        "選択側は文字評価そのものである（",
        ref("claim_selection_sum_character_evaluation"),
        "。非自明文字の選択和は辺長によらず零）。置換側は五段の合成である。",
        "ファイバーの各置換は各頂点での非後退局所全単射の積であり、反転対辺は各端点へ",
        "入と出を一本ずつ与えるので、単純通過部分は ", math(String.raw`E`),
        " の均衡配向を誘導する（辺長に依存しない）。非自明文字の ", math(String.raw`E`),
        " の全ての均衡配向には曲がり型の次数 ", math(String.raw`4`),
        " 頂点が存在する（前段の一般証明）。曲がり型頂点は ", math(String.raw`E`),
        " の次数 ", math(String.raw`4`), " 頂点の曲がり配向に限り ",
        math(String.raw`D`), " に依存しない（記号的・局所的）。曲がり型頂点の",
        "非後退局所全単射はちょうど ", math(String.raw`2`),
        " つで、交換は両位置を入れ替える互換であり四半回転和を保つ（記号的・局所的）。",
        "従って辞書式最小の曲がり型頂点での交換は、動辺集合（ゆえに曲がり型頂点集合と",
        "辞書式最小の選択、ねじれ符号の積）と総回転数を保ち、巡回数の偶奇だけを反転する",
        "不動点のない対合になり、位相ベクトルが反転してファイバーの位相和は四つのねじれ",
        "全てで零になる。局所的事実は辺長に依存せず、存在定理は一般証明済みなので、",
        "合成は全ての辺長で成立する。検算では一辺四の偶部分グラフ ",
        math(String.raw`2^{17}=131{,}072`), " 個の文字を全数調査して非自明 ",
        math(String.raw`50{,}320`), " 個を確定し、辺数 ", math(String.raw`8`),
        " 以下の非自明文字が交差一周路対 ", math(String.raw`16`),
        " 個に限ることを確かめ、その全ての ", math(String.raw`D=\varnothing`),
        " ファイバー（", math(String.raw`128`),
        " 置換）と閉路状反転対のファイバー（", math(String.raw`696`),
        " 置換）、一辺五の交差一周路対（", math(String.raw`8`), " 置換と ",
        math(String.raw`696`),
        " 置換）を全展開して、対ごとの位相ベクトル反転・位相和の零・選択和の零を",
        "等号 assert した。これで平方恒等式の層別項のうち非自明文字の添字は一般の",
        "辺長で両側とも零になり、残るのは自明文字の添字の同定である。",
      ]),
      paragraph([
        "自明文字で選択集合が非空な添字では、選択和の絶対値をさらに有限グラフの",
        "巡回階数まで具体化できる。", math(String.raw`E`), " の非孤立頂点集合を ",
        math(String.raw`V(E)`), "、非空連結成分数を ", math(String.raw`c(E)`),
        " とすると、", math(String.raw`E`), " に含まれる偶部分グラフは ",
        math(String.raw`\mathbb F_2`), " 巡回空間なので",
      ]),
      displayMath(String.raw`\left|\mathcal U^{a,b}_L(D,E)\right|
=2^{\lvert E\rvert-\lvert V(E)\rvert+c(E)}`),
      paragraph([
        "となる。一般のファイバー等式で同定すべき置換側の位相和も、同じ符号と",
        "絶対値を持つ必要がある。一辺二では選択集合が非空で文字が自明な ",
        math(String.raw`369`), " ファイバー、四ねじれを含む ",
        math(String.raw`1{,}476`), " 件についてこの値を直接検査した",
        "（sagemath/check/trivial-character-fiber-magnitude）。巡回階数 ",
        math(String.raw`0,1,2,5`),
        " のファイバーはそれぞれ ", math(String.raw`32,320,16,1`),
        " 個で、絶対値は ", math(String.raw`1,2,4,32`),
        " だった。これは一般証明ではなく、次に置換側で構成すべき符号付き数え上げの",
        "値を固定する有限観察である。",
      ]),
      paragraph([
        "置換側の類別の候補として、ファイバーの各置換の単純通過部分が誘導する ",
        math(String.raw`E`), " の均衡配向を、ファイバーの辞書式最小置換の配向と",
        "比較する写像を検査した。二つの均衡配向の不一致辺集合は各頂点で偶数次数",
        "なので、常に ", math(String.raw`E`), " の ", math(String.raw`\mathbb F_2`),
        " 巡回空間の元である（一辺二の全 ", math(String.raw`18{,}880`),
        " 置換で検査）。巡回階数 ", math(String.raw`2`), " 以下の ",
        math(String.raw`368`), " ファイバーでは類が巡回空間の全 ",
        math(String.raw`2^{\lvert E\rvert-\lvert V(E)\rvert+c(E)}`),
        " 元をちょうど尽くし、四ねじれそれぞれで各類の位相和が共通値 ",
        math(String.raw`\mathcal K^{a,b}_L(D,E)/2^{\text{階数}}\in\{+1,-1\}`),
        " に等しい。しかし ", math(String.raw`E`), " が全 ", math(String.raw`8`),
        " 辺の階数 ", math(String.raw`5`), " のファイバーだけは、類が誘導された",
        "均衡配向 ", math(String.raw`18`), " 個に対応して巡回空間 ",
        math(String.raw`32`), " 元を尽くさず、位相和が零の類 ",
        math(String.raw`16`), " 個と ",
        math(String.raw`\mathcal K^{a,b}_L(D,E)/2`), " の類 ", math(String.raw`2`),
        " 個に分かれる（sagemath/check/trivial-character-fiber-orientation-classes）。",
        "従って一般の数え上げは、巡回空間そのものではなく誘導された均衡配向の類を",
        "単位に組む必要がある。これも有限観察であり、次は均衡配向の類ごとの位相和を",
        "配向の局所データ（曲がり・直進の頂点型）で書く一般式を構成する。",
      ]),
      paragraph([
        "均衡配向を固定した類の位相和は、頂点ごとの局所遷移行列式の積へ分解できる。",
        "動辺を固定順序から終点・始点ごとの順序へ並べ替える符号を ",
        math(String.raw`\eta(D,E,o)\in\{+1,-1\}`), "、頂点 ", math(String.raw`v`),
        " へ入る動辺と出る動辺の間の局所遷移行列を ",
        math(String.raw`R_v^{a,b}(D,E,o)`), " とすると、配向 ", math(String.raw`o`),
        " の類の位相和は",
      ]),
      displayMath(String.raw`(-1)^{\lvert 2D\sqcup E\rvert}\eta(D,E,o)
\prod_v\det R_v^{a,b}(D,E,o)`),
      paragraph([
        "である。巡回ごとの負号の積を置換符号へ直し、遷移行列を頂点ごとの対角",
        "ブロックへ並べ替えた式である。一辺二の自明文字・選択非空ファイバーの",
        "均衡配向類 ", math(String.raw`754`), " 件と四ねじれについて、類の直接和と",
        "局所行列式積の一致を検査した。さらに単純通過辺が次数 ", math(String.raw`4`),
        " となる頂点では、入方向が隣り合う曲がり型の局所行列式は零、入方向が",
        "向かい合う直進型の絶対値は ", math(String.raw`2`), " になる。従って曲がり型を",
        "持つ類は零和となり、持たない類の絶対値は ",
        math(String.raw`2^{s(o)}`), "（", math(String.raw`s(o)`),
        " は直進型の次数 ", math(String.raw`4`), " 頂点数）になる。局所型数",
        math(String.raw`(曲がり,直進)=(0,0),(0,4),(4,0)`), " の分布はそれぞれ ",
        math(String.raw`736,2,16`), " 類であり、全辺ファイバーの零和 ",
        math(String.raw`16`), " 類と半値 ", math(String.raw`2`),
        " 類を局所型だけで説明する",
        "（sagemath/check/trivial-character-orientation-local-factor）。次はこの局所",
        "行列式の型分類を一般の辺長へ持ち上げ、自明文字の類和を選択和へ同定する。",
      ]),
      paragraph([
        "局所行列式の型分類は辺長に依存しない。局所遷移行列の成分は入る動辺と",
        "出る動辺の方向差（四半回転数の ", math(String.raw`\zeta_8`), " 冪）だけで",
        "決まり、継ぎ目のねじれ符号は列全体への ", math(String.raw`\pm1`),
        " 倍として掛かって行列式を ", math(String.raw`\pm1`),
        " 倍にしかしないからである。一つの頂点の四つの枠に「無し・二重辺・",
        "単純入・単純出」を割り当てた釣り合い非空局所配置は全部で ",
        math(String.raw`69`), " 件あり、行列式は次のとおり分類される。",
        "曲がり型（四枠単純・入方向が隣接。", math(String.raw`4`), " 件）は零。",
        "直進型（四枠単純・入方向が対向。", math(String.raw`2`), " 件）は ",
        math(String.raw`\pm2\zeta_8^2`), "。単純辺が無く二重辺が奇数本の配置（",
        math(String.raw`8`), " 件）も零だが、これはその頂点で単純次数が零のため、",
        "選択集合が非空な鍵では二重次数の偶数性に反して実現しない。残りの ",
        math(String.raw`55`), " 件は全て ", math(String.raw`\pm\zeta_8^t`),
        "（絶対値 ", math(String.raw`1`), "）である。従って任意の辺長の",
        "選択非空・自明文字の鍵の均衡配向類について、位相和が零になるのは",
        "曲がり型の次数 ", math(String.raw`4`), " 頂点を持つ類にちょうど限られ、",
        "持たない類の位相和の絶対値は ", math(String.raw`2^{s(o)}`),
        " である（sagemath/check/orientation-local-determinant-type-classification）。",
        "次は曲がり型を持たない均衡配向の数え上げと符号を選択和の ",
        math(String.raw`\pm2^{|E|-|V(E)|+c(E)}`), " へ同定する。",
      ]),
      paragraph([
        "一辺二では、この同定に必要な重み付き数と符号を全ファイバーで固定した。",
        "曲がり型頂点を持たない均衡配向 ", math(String.raw`o`), " に、局所行列式の",
        "絶対値 ", math(String.raw`2^{s(o)}`), " を重みとして付けると、",
      ]),
      displayMath(String.raw`\sum_{o:\,\text{曲がり型なし}}2^{s(o)}
=2^{\lvert E\rvert-\lvert V(E)\rvert+c(E)}
=\lvert\mathcal C_L(D,E)\rvert`),
      paragraph([
        "となった。さらに四つのねじれそれぞれで、曲がり型を持たない全配向類の",
        "位相和は同符号で、その符号は選択和 ",
        math(String.raw`\mathcal U_L^{a,b}(D,E)`), " の符号と一致した。従って零和の",
        "曲がり型類を除いた総和は選択和そのものになる",
        "（sagemath/check/trivial-character-curved-free-orientation-weight）。",
        "これは一辺二の有限観察であり、一般の辺長での重み付き全単射と符号の同定は",
        "まだ証明していない。次は重み ", math(String.raw`2^{s(o)}`),
        " を局所選択として展開し、選択集合との全単射を構成する。",
      ]),
      paragraph([
        "局所選択展開の最初の候補として、トレイル台写像を検査し、全単射に",
        "届かない反例を固定した。曲がり型なし配向 ", math(String.raw`o`),
        " と直進型頂点の部分集合 ", math(String.raw`S`), " の対に対し、",
        math(String.raw`E`), " の各辺を ", math(String.raw`o`),
        " の向きに向け、次数 ", math(String.raw`2`),
        " の頂点では一意の出辺へ、直進型頂点では ", math(String.raw`S`),
        " に属せば左折・属さなければ右折の出辺へつなぐと ", math(String.raw`E`),
        " は閉トレイルへ分割される。各トレイルの台は各頂点で偶数次数である。",
        "辞書式最小の辺を向き ", math(String.raw`0`),
        " で通るトレイルの台の合併を ", math(String.raw`C(o,S)`),
        " とすると、これは常に巡回空間の元であり、直進型頂点を持たない階数 ",
        math(String.raw`2`), " 以下の全 ", math(String.raw`368`),
        " ファイバーでは巡回空間への全単射になる（", math(String.raw`E`),
        " はサイクルの直和で、トレイルは成分、", math(String.raw`C`),
        " は成分の向きの符号化）。しかし全辺・階数 ", math(String.raw`5`),
        " のファイバーでは、", math(String.raw`S`), " の元数が奇数だと ",
        math(String.raw`E`), " 全体が ", math(String.raw`1`),
        " 本のトレイルになり、", math(String.raw`C`), " が空集合または ",
        math(String.raw`E`), " へ潰れて（", math(String.raw`8`), " 対 ",
        math(String.raw`1`), " の衝突が ", math(String.raw`2`),
        " つ）、像は ", math(String.raw`18`), " 個で ", math(String.raw`32`),
        " に届かない",
        "（sagemath/check/curved-free-selection-trail-map-counterexample）。",
        "トレイルの台の合併は左右選択の奇偶を保存しないので、一般の構成は",
        "選択の情報を辺集合へ落とす前に保つ別の対応（たとえば配向差と選択ビットを",
        "別々に符号化する対応）を要する。次はその対応を構成する。",
      ]),
      paragraph([
        "一辺二では、配向と局所選択を別々のビットとして保つことで、全 ",
        math(String.raw`369`), " ファイバーを覆う全単射を構成できた。直進型頂点を",
        "持たない ", math(String.raw`368`), " ファイバーでは前のトレイル台写像を使う。",
        "唯一の全辺ファイバーでは、二つの曲がり型なし均衡配向の辞書式順位を ",
        math(String.raw`1`), " ビット、四つの直進型頂点の局所選択を ",
        math(String.raw`4`), " ビットとして保ち、辞書式に定めた巡回空間の ",
        math(String.raw`5`), " 元の基底の係数へ別々に渡す。選択集合の辞書式最小元との",
        "対称差を取ると、合計 ", math(String.raw`768`), " 対が各ファイバーの選択集合を",
        "ちょうど一度ずつ尽くした",
        "（sagemath/check/curved-free-selection-separated-bit-bijection）。",
        "ただし全辺ファイバーの座標化は有限列挙の辞書式順序に依存する。次は一般の",
        "辺長で、配向差と局所選択ビットから巡回空間の基底係数を列挙に頼らず取り出す",
        "規則を構成する。",
      ]),
      paragraph([
        "配向側の座標は、列挙に頼らず成分ごとに取れる。一辺二・一辺三のトーラスの",
        "全偶部分グラフ（", math(String.raw`32`), " 個と ", math(String.raw`1{,}024`),
        " 個）で、各連結成分の曲がり型なし均衡配向は ", math(String.raw`0`),
        " 個か ", math(String.raw`2`),
        " 個であり、", math(String.raw`2`),
        " 個のときは互いの全反転である。従って ", math(String.raw`E`),
        " 全体の曲がり型なし均衡配向は ", math(String.raw`0`), " 個か ",
        math(String.raw`2^{c(E)}`),
        " 個で、二つの配向の不一致辺集合は常に成分の辺集合の合併になる。",
        "また次数勘定の等式 ", math(String.raw`|E|-|V(E)|=n_4(E)`),
        "（", math(String.raw`n_4`), " は次数 ", math(String.raw`4`),
        " の頂点数）から、巡回空間の階数 ", math(String.raw`|E|-|V(E)|+c(E)`),
        " は ", math(String.raw`c(E)+n_4(E)`),
        " に分解し、成分の指示元 ", math(String.raw`c(E)`),
        " 本は巡回空間の一次独立な元である。一辺三で曲がり型なし配向を持たない",
        "非空偶部分グラフは ", math(String.raw`346`),
        " 個で、非自明文字の偶部分グラフの個数 ", math(String.raw`346`),
        " に一致する（非自明文字が曲がり型頂点を強制する定理の逆向きは、",
        "一辺二・一辺三の全数では同値）",
        "（sagemath/check/curved-free-orientation-component-structure）。",
        "残るのは直進型頂点の局所選択ビットから、巡回空間の残り ",
        math(String.raw`n_4`), " 次元の係数を列挙に頼らず取り出す規則である。",
      ]),
      paragraph([
        "残りの座標も、巡回空間の全元を列挙せずに取れる。まず各連結成分の辺指示元を",
        "先頭に置く。辺の固定順序に従う Kruskal 森を作り、各非森辺が定める基本閉路を",
        "順に走査して、先行する元との階数を増やすものだけを加える。基本閉路は巡回空間の",
        "基底なので、これは成分指示元を保った決定的な基底拡張になる。巡回階数が ",
        math(String.raw`c(E)+n_4(E)`), " であることから、追加される基底元はちょうど ",
        math(String.raw`n_4(E)`), " 本である。そこで次数 ", math(String.raw`4`),
        " 頂点を固定順序に並べ、各頂点の局所選択ビットを追加基底元の係数へ順に渡す。",
        "成分反転ビットを先頭の ", math(String.raw`c(E)`), " 係数へ渡す規則と合わせて、",
        "全 ", math(String.raw`c(E)+n_4(E)`), " ビットが巡回空間の係数列を一度ずつ尽くす",
        "（sagemath/check/curved-free-selection-spanning-forest-coordinates）。一辺二では ",
        math(String.raw`23`), " グラフ・", math(String.raw`80`), " 係数列、一辺三では ",
        math(String.raw`677`), " グラフ・", math(String.raw`3{,}136`),
        " 係数列で検査した。基底拡張そのものは一般の有限偶グラフに通用する。残るのは、",
        "各成分の曲がり型なし配向が一般の辺長でも全反転対になることと、この全単射で",
        "位相和の符号が選択和の符号に一致することの証明である。",
      ]),
      paragraph([
        "前者は一般の辺長で証明できる。任意の辺長のトーラスの偶部分グラフ ",
        math(String.raw`E`), "（各頂点の次数は ", math(String.raw`2`), " か ",
        math(String.raw`4`), "）の任意の連結成分 ", math(String.raw`K`),
        " について、曲がり型なし均衡配向の集合は、空であるか、ある配向とその全反転の",
        "ちょうど ", math(String.raw`2`),
        " 元集合である。第一の核は局所決定性である。頂点 ", math(String.raw`v`),
        " に接続する ", math(String.raw`K`), " の辺 ", math(String.raw`e`),
        " の向き（", math(String.raw`v`), " へ入るか ", math(String.raw`v`),
        " から出るか）を一つ与えると、", math(String.raw`v`),
        " での局所状態は一意に決まる。次数 ", math(String.raw`2`),
        " なら均衡（入 ", math(String.raw`1`), " 出 ", math(String.raw`1`),
        "）から他辺の向きが決まる。次数 ", math(String.raw`4`),
        " の頂点はトーラスでは水平二辺と垂直二辺を持ち、曲がり型なしの条件は",
        "入辺二本が同軸であることを要求する。", math(String.raw`e`),
        " が入なら入辺は ", math(String.raw`e`), " の軸の二本、", math(String.raw`e`),
        " が出なら、入辺二本の軸が ", math(String.raw`e`), " の軸だとすると ",
        math(String.raw`e`),
        " 自身が入辺になり矛盾するので、入辺は他軸の二本に限る。第二の核は全反転の",
        "保存である。入と出の交換は均衡性を保ち、入辺二本が同軸なら交換後の入辺",
        "（元の出辺）二本も残りの同軸二本なので曲がり型なし性も保ち、辺が一本でも",
        "あれば元の配向と異なる。第三の核は辺連結性による伝播である。",
        math(String.raw`K`), " の任意の二辺は頂点を共有する辺の列で結ばれるので、",
        "固定した最小辺の向き ", math(String.raw`2`),
        " 通りそれぞれから、局所決定性の帰納で全辺の向きが一意に決まる。従って",
        "曲がり型なし均衡配向は高々 ", math(String.raw`2`),
        " 個で、非空なら全反転の対によりちょうど ", math(String.raw`2`),
        " 個であり、二つの配向の不一致辺集合は成分全体になる。系として、",
        math(String.raw`E`), " 全体の曲がり型なし均衡配向は ", math(String.raw`0`),
        " 個か ", math(String.raw`2^{c(E)}`),
        " 個で、成分反転ビットによる座標化は任意の辺長で成立する。局所決定性と",
        "全反転の交換は局所状態の記号的列挙（軸列 ", math(String.raw`4`),
        " 種・スロットと向きの固定 ", math(String.raw`20`),
        " 件）で、伝播は一辺二・一辺三の全偶部分グラフの相異なる成分（",
        math(String.raw`29`), " 個と ", math(String.raw`934`),
        " 個）で総当たり列挙との集合一致として検査した",
        "（sagemath/check/curved-free-orientation-full-reversal-pair）。",
        "残るのは、生成森座標の全単射で位相和の符号が選択和の符号に一致することの",
        "証明である。",
      ]),
      paragraph([
        "生成森座標を生の置換へ直接持ち上げる符号対応は成立しない。一辺二で、",
        "曲がり型なし均衡配向を誘導する各置換から直進型頂点での左折・右折を読み取り、",
        "成分反転ビットと合わせて生成森基底の係数へ移した。対応する選択集合の項と",
        "置換の位相寄与を四つのねじれで比較すると、全 ",
        math(String.raw`74{,}496`), " 件中 ", math(String.raw`35{,}712`),
        " 件で符号が異なった",
        "（sagemath/check/curved-free-selection-spanning-forest-sign）。従って符号の同定は、",
        "局所遷移行列式の展開前の置換ではなく、相殺を済ませた配向類の局所行列式和を",
        "単位に組まなければならない。次は曲がり型なし配向類の局所行列式和の符号を、",
        "自明な選択文字の共通符号へ直接同定する。",
      ]),
      paragraph([
        "配向類の和を単位に組むと符号は一様になる。自明文字で選択集合が非空な鍵 ",
        math(String.raw`(D,E)`),
        " について、曲がり型なし均衡配向を置換の列挙に頼らず局所決定性の伝播で構成し",
        "（各成分の最小辺の向き ", math(String.raw`2`),
        " 通りから全反転対の定理の帰納で全辺へ延ばす）、各配向類の位相和を",
        "分解済みの局所遷移行列式の積の公式で計算した。構成した配向は成分ごとの向き ",
        math(String.raw`2^{c(E)}`),
        " 個を尽くし、一辺二では置換ファイバーが誘導する曲がり型なし配向の集合に",
        "一致する。選択和の各項 ",
        math(String.raw`w(D\cup C)\,w(D\cup(E\setminus C))`),
        " は全て同じ符号を持ち、全ての曲がり型なし配向類の局所行列式和は、",
        "四つのねじれそれぞれで共通符号 ", math(String.raw`\times\,2^{n_4(E)}`),
        " という同一の値になる（成分反転で不変）。一辺二の全 ",
        math(String.raw`369`), " ファイバー鍵（値の検査 ", math(String.raw`2{,}952`),
        " 件）と、一辺三の ", math(String.raw`D=\varnothing`),
        " の自明文字 ", math(String.raw`677`), " 鍵（選択項 ",
        math(String.raw`12{,}544`), " 項、値の検査 ", math(String.raw`6{,}088`),
        " 件）の全数で検査した",
        "（sagemath/check/curved-free-class-sum-selection-sign）。一辺三では、",
        "非空偶部分グラフで曲がり型なし配向が存在することと文字が自明なことの",
        "同値も全数で照合した。一般の辺長では、配向類の局所行列式和が選択項の",
        "共通符号に一致することの証明が残る。次はこの同定を、局所行列式の因子と",
        "継ぎ目符号・並べ替え符号の積として一般の辺長で証明する。",
      ]),
      paragraph([
        "この同定のうち、四つのねじれへの依存は一般の辺長で分離できる。",
        math(String.raw`A:=D\cup C`), "、",
        math(String.raw`B:=D\cup(E\setminus C)`), " と置くと ",
        math(String.raw`A\mathbin\triangle B=E`), " なので、巻き付き偶奇の対称差加法性により、",
      ]),
      displayMath(String.raw`\begin{aligned}
\frac{w^{a,b}_L(A)w^{a,b}_L(B)}{w^{0,0}_L(A)w^{0,0}_L(B)}
&=(-1)^{a(\varepsilon_{L,\mathrm h}(A)+\varepsilon_{L,\mathrm h}(B))
+b(\varepsilon_{L,\mathrm v}(A)+\varepsilon_{L,\mathrm v}(B))}
&&\bigl(\because\ \text{符号重みの定義と }\mathbb Z\text{ の四則}\bigr)\\
&=(-1)^{a\varepsilon_{L,\mathrm h}(E)+b\varepsilon_{L,\mathrm v}(E)}
&&\bigl(\because\ \blkref{claim_winding_parity_symmetric_difference_additivity}\bigr).
\end{aligned}`),
      paragraph([
        "一方、配向類の局所遷移行列では、スピン構造 ", math(String.raw`(a,b)`),
        " の継ぎ目符号は出る動辺の列全体へ掛かる。各局所行列式から列ごとに括り出すと、",
        "全動辺集合 ", math(String.raw`2D\sqcup o(E)`), " にわたる積になる。",
        math(String.raw`D`), " の各辺は二つの向きで現れ、反転しても切断線偶奇は変わらないため、",
        "その寄与は二乗されて ", math(String.raw`1`), " になる。",
        math(String.raw`E`), " の各辺は配向 ", math(String.raw`o`),
        " が選んだ一方向だけで現れ、反転によらない切断線偶奇の和は ",
        math(String.raw`\varepsilon_{L,\mathrm h}(E),\varepsilon_{L,\mathrm v}(E)`), " である。従って",
      ]),
      displayMath(String.raw`\mathcal L^{a,b}_L(D,E,o)
=(-1)^{a\varepsilon_{L,\mathrm h}(E)+b\varepsilon_{L,\mathrm v}(E)}
\mathcal L^{0,0}_L(D,E,o)
\qquad\bigl(\because\ \text{局所行列式の列ごとの継ぎ目符号の括り出し}\bigr)`),
      paragraph([
        "となる。ここで ", math(String.raw`\mathcal L^{a,b}_L(D,E,o)`),
        " は配向類の局所行列式和である。動辺の並べ替え符号と ",
        math(String.raw`(-1)^{\lvert2D\sqcup E\rvert}`),
        " はスピン構造に依らないので比から消える。よって配向類の和と選択項は同じ継ぎ目文字を受け、",
        "符号同定は未ねじれ ", math(String.raw`(a,b)=(0,0)`),
        " の場合だけを証明すれば四つ全てへ移る。有限検算では一辺二の全対象と一辺三の ",
        math(String.raw`D=\varnothing`), " の対象でこの比を照合した",
        "（sagemath/check/curved-free-class-sum-seam-twist-factor）。残る一般証明は、",
        "未ねじれの局所回転因子と動辺の並べ替え符号の積を、選択項の共通符号へ同定する部分である。",
      ]),
      paragraph([
        "同定の標的である選択項の共通符号は、一般の辺長で閉じた式を持つ。",
        math(String.raw`A:=D\cup C`), " と置くと、任意の鍵と任意の選択集合 ",
        math(String.raw`C`), " について、巻き付き偶奇 ",
        math(String.raw`\varepsilon_{L,\mathrm h},\varepsilon_{L,\mathrm v}\in\{0,1\}`),
        " の対称差加法性だけから",
      ]),
      displayMath(String.raw`\begin{aligned}
w^{a,b}_L(A)\,w^{a,b}_L(A\mathbin\triangle E)
&=(-1)^{(1+a)\varepsilon_{L,\mathrm h}(E)+(1+b)\varepsilon_{L,\mathrm v}(E)
+\varepsilon_{L,\mathrm h}(E)\varepsilon_{L,\mathrm v}(E)}
\cdot(-1)^{\langle A,E\rangle}
&&\bigl(\because\ \blkref{claim_winding_parity_symmetric_difference_additivity}
\text{ と }\mathbb F_2\text{ の分配則}\bigr)
\end{aligned}`),
      paragraph([
        "が成り立つ。ここで ",
        math(String.raw`\langle A,E\rangle:=\varepsilon_{L,\mathrm h}(A)\varepsilon_{L,\mathrm v}(E)
+\varepsilon_{L,\mathrm h}(E)\varepsilon_{L,\mathrm v}(A)\in\{0,1\}`),
        " は巻き付きベクトルの交差対である。導出は指数の ", math(String.raw`\mathbb F_2`),
        " 計算一つで済む: 一次の項は ",
        math(String.raw`\varepsilon(A)+\varepsilon(A\mathbin\triangle E)=\varepsilon(E)`),
        " へ落ち、積の項は ",
        math(String.raw`\varepsilon_{\mathrm h}(A)\varepsilon_{\mathrm v}(A)
+(\varepsilon_{\mathrm h}(A)+\varepsilon_{\mathrm h}(E))(\varepsilon_{\mathrm v}(A)+\varepsilon_{\mathrm v}(E))
=\varepsilon_{\mathrm h}(E)\varepsilon_{\mathrm v}(E)+\langle A,E\rangle`),
        " へ落ちる。選択集合を巡回空間の元 ", math(String.raw`z`),
        " だけ動かすと交差対は ", math(String.raw`\langle z,E\rangle`),
        " だけ変わるので、選択文字が自明な鍵ではどの基本閉路とも交差対が零になり、",
        "選択項は ", math(String.raw`C`), " に依らない共通符号",
      ]),
      displayMath(String.raw`(-1)^{(1+a)\varepsilon_{L,\mathrm h}(E)+(1+b)\varepsilon_{L,\mathrm v}(E)
+\varepsilon_{L,\mathrm h}(E)\varepsilon_{L,\mathrm v}(E)}
\cdot(-1)^{\langle D\cup C_0,\,E\rangle}
\qquad(C_0\text{ は任意の一つの選択集合})`),
      paragraph([
        "を持つ。逆に文字が非自明なら ", math(String.raw`\langle z,E\rangle=1`),
        " の基本閉路 ", math(String.raw`z`), " があり、",
        math(String.raw`C\mapsto C\mathbin\triangle z`),
        " が選択項の符号を反転する不動点なしの対合になって選択和が零になる",
        "（文字による消滅のもう一つの導出）。一辺二の選択非空 ",
        math(String.raw`417`), " 鍵の恒等式 ", math(String.raw`4{,}096`),
        " 件と、一辺三の ", math(String.raw`D=\varnothing`),
        " の全偶部分グラフの恒等式 ", math(String.raw`34{,}352`),
        " 件・自明文字 ", math(String.raw`677`), " 鍵の共通符号・非自明文字 ",
        math(String.raw`346`), " 鍵の対合消滅 ", math(String.raw`21{,}808`),
        " 件を全数で検査した（sagemath/check/selection-common-sign-closed-formula）。",
        "残る一般証明は、未ねじれの配向類の局所行列式和 ",
        math(String.raw`\mathcal L^{0,0}_L(D,E,o)`),
        " の符号がこの閉じた式に一致することの証明である。",
      ]),
      paragraph([
        "未ねじれの符号同定は、一つの偶奇恒等式へ還元できる。曲がり型のない均衡配向 ",
        math(String.raw`o`), " に対し、動辺の固定順序から終点別の行順序へ移す置換の",
        "反転数偶奇を ", math(String.raw`r(o)`), "、始点別の列順序へ移す置換の",
        "反転数偶奇を ", math(String.raw`c(o)`), " とする。局所行列式の積を ",
        math(String.raw`2^{n_4(E)}`), " で割った値は ", math(String.raw`1`),
        " または ", math(String.raw`-1`), " なので、それを ",
        math(String.raw`(-1)^{q(o)}`), " と書く。局所行列式への分解式から",
      ]),
      displayMath(String.raw`\mathcal L^{0,0}_L(D,E,o)
=2^{n_4(E)}(-1)^{\lvert2D\sqcup o(E)\rvert+r(o)+c(o)+q(o)}
\qquad\bigl(\because\ \blkref{claim_kac_ward_determinant_fiber_stratified_phase_sum}
\text{ と局所行列式の積への分解}\bigr)`),
      paragraph([
        "を得る。従って残る一般証明は、任意の選択集合 ", math(String.raw`C_0`),
        " に対する一つの ", math(String.raw`\mathbb F_2`), " 恒等式",
      ]),
      displayMath(String.raw`\lvert2D\sqcup o(E)\rvert+r(o)+c(o)+q(o)
\equiv \varepsilon_{L,\mathrm h}(E)+\varepsilon_{L,\mathrm v}(E)
+\varepsilon_{L,\mathrm h}(E)\varepsilon_{L,\mathrm v}(E)
+\langle D\cup C_0,E\rangle\pmod 2`),
      paragraph([
        "だけである。左辺の四因子を別々に計算し、局所行列式和の再構成と右辺との一致を、",
        "一辺二の全対象と一辺三の ", math(String.raw`D=\varnothing`),
        " の自明文字対象で検査した",
        "（sagemath/check/curved-free-class-sign-parity-reduction）。交差対項 ",
        math(String.raw`\langle D\cup C_0,E\rangle`),
        " は、一辺三の ", math(String.raw`D=\varnothing`),
        " の自明文字対象では選択集合が巡回空間の元になるため恒等的に零である。",
        "巻き付き偶奇が非零の自明文字 ", math(String.raw`E`), " に二重辺 ",
        math(String.raw`D=\{d\}`),
        " を付けた一辺三の鍵で、交差対が ", math(String.raw`1`), " の ",
        math(String.raw`336`), " 件と ", math(String.raw`0`), " の ",
        math(String.raw`324`), " 件の両方でも恒等式が成り立つことを検査した",
        "（sagemath/check/parity-identity-doubled-edge-crossing）。次はこの偶奇恒等式を、",
        "辺ごとの寄与とトーラスの二つの切断線の寄与へ分けて一般に証明する。",
      ]),
      paragraph([
        "二つの並べ替え符号は、有向辺対ごとの反転指示値へ展開できる。動辺の固定順序を ",
        math(String.raw`\vec e_1<\cdots<\vec e_m`), "、終点別の行順序の鍵を ",
        math(String.raw`R(\vec e):=(\operatorname{tgt}(\vec e),\vec e)`),
        "、始点別の列順序の鍵を ",
        math(String.raw`C(\vec e):=(\operatorname{src}(\vec e),\vec e)`), " と置けば、",
      ]),
      displayMath(String.raw`\begin{aligned}
r(o)
&\equiv\sum_{1\le i<j\le m}[R(\vec e_i)>R(\vec e_j)]\pmod 2
&&\bigl(\because\ \text{反転数の定義}\bigr)\\
c(o)
&\equiv\sum_{1\le i<j\le m}[C(\vec e_i)>C(\vec e_j)]\pmod 2
&&\bigl(\because\ \text{反転数の定義}\bigr)
\end{aligned}`),
      paragraph([
        "となる。各和を、少なくとも一方の辺が基本領域の水平または垂直の切断線を通る辺対と、",
        "どちらも切断線を通らない内部辺対へ分ける。また ", math(String.raw`q(o)`),
        " は、全頂点の局所行列式の積から従来どおり求める。従って左辺は、動辺数、内部辺対、",
        "切断線辺対、局所位相の四寄与へ分かれる。この分解前後の一致と標的の巻き付き・交差対の式との一致を、",
        "一辺二の全対象、一辺三の ", math(String.raw`D=\varnothing`),
        " の自明文字対象、二重辺を持つ一辺三の対象で検査する",
        "（sagemath/check/parity-identity-pair-and-seam-decomposition）。残る一般証明は、",
        "内部辺対と局所位相の合成、および二本の切断線に触れる辺対の和が",
        "巻き付き偶奇と交差対を与えることの二つに分かれる。",
      ]),
      paragraph([
        "ただし内部側の合成偶奇（動辺数＋内部辺対の反転和＋局所位相の ",
        math(String.raw`\mathbb F_2`), " 和）は、鍵 ",
        math(String.raw`(D,E)`), " だけでは決まらない。一辺二では ",
        math(String.raw`8`), " 鍵、一辺三の ", math(String.raw`D=\varnothing`),
        " の自明文字では ", math(String.raw`21`),
        " 鍵で、同じ鍵の曲がり型なし均衡配向の間でこの偶奇の値が異なる。値が配向に",
        "よらず一定の鍵に限っても、", math(String.raw`E`),
        " の巻き付き偶奇と切断線に触れる辺数の偶奇・その二項係数の偶奇が全て同じで",
        "値が異なる鍵の組が存在する",
        "（sagemath/check/parity-identity-interior-orientation-dependence）。",
        "従って一般証明は、内部寄与を配向と独立な不変量として切断線寄与から分離する",
        "形では組めず、成分反転で内部側の変化と切断線側の変化が相殺することを示して",
        "任意の一つの配向での評価へ帰着させる形で組む。",
      ]),
      paragraph([
        "この帰着に必要な変化の相殺は、有限系の全成分反転で成立する。曲がり型なし",
        "均衡配向 ", math(String.raw`o`), " の辺連結成分 ", math(String.raw`K`),
        " を全反転した配向を ", math(String.raw`o^K`), " とする。動辺数は変わらず、",
        "内部側（動辺数＋内部辺対＋局所位相）の変化と切断線辺対の変化が ",
        math(String.raw`\mathbb F_2`), " で等しいため、両者は全体で相殺する。",
        "一辺二の全対象と一辺三の ", math(String.raw`D=\varnothing`),
        " の自明文字対象について、全ての曲がり型なし均衡配向と全ての成分反転で検査した",
        "（sagemath/check/parity-identity-component-reversal-cancellation）。",
      ]),
      paragraph([
        "帰着の標準形には、各辺連結成分の最小辺の向きを ", math(String.raw`0`),
        " に固定した曲がり型なし均衡配向を選ぶ。全反転対の定理から標準形は各鍵で",
        "一意に存在する。任意の曲がり型なし均衡配向は、標準形との不一致辺集合が",
        "成分の合併になり、その成分を一つずつ全反転する列で標準形へ到達する。",
        "成分反転は偶奇恒等式の左辺を変えないので、恒等式の成立は標準形での評価",
        "一つに帰着し、標準形での左辺は標的 ",
        math(String.raw`\varepsilon_{L,\mathrm h}(E)+\varepsilon_{L,\mathrm v}(E)
+\varepsilon_{L,\mathrm h}(E)\varepsilon_{L,\mathrm v}(E)
+\langle D\cup C_0,E\rangle`),
        " に一致する。標準形の一意存在・差集合の成分合併性・反転列の到達・",
        "標準形での恒等式を、一辺二の全対象と一辺三の ",
        math(String.raw`D=\varnothing`), " の自明文字対象で検査した",
        "（sagemath/check/parity-identity-standard-orientation-reduction）。",
      ]),
      paragraph([
        "ただし標準形を選んでも、四寄与は巻き付き偶奇二つと交差対だけから",
        "個別には決まらない。同じ三つ組に複数の四寄与の組が属する反例があり、",
        "一辺二では該当する三つ組が ", math(String.raw`7`), " 類、一辺三では ",
        math(String.raw`4`), " 類ある。四寄与の異なる組は一辺二で ",
        math(String.raw`8`), " 種類、一辺三で ", math(String.raw`12`),
        " 種類現れる。一方、その総和は全件で標的の位相式に",
        "一致する（sagemath/check/parity-identity-standard-contributions-not-topological）。",
        "従って一般証明には、標準形の幾何を記録する追加統計を導入し、",
        "四寄与の途中で相殺する規則が必要である。",
      ]),
      paragraph([
        "その追加統計は、鍵から大域的に計算できる偶奇の線型結合では足りない。鍵 ",
        math(String.raw`(D,E)`),
        " から機械的に計算できる幾何統計 ", math(String.raw`15`),
        " 本（辺数・二重辺数・巻き付き偶奇・交差対・成分数・頂点数・次数 ",
        math(String.raw`4`),
        " 頂点数の各偶奇とその積）を候補基底に並べ、四寄与とその二寄与和が ",
        math(String.raw`\mathbb F_2`),
        " 線型結合で書けるかを一辺二の全鍵と一辺三の ",
        math(String.raw`D=\varnothing`),
        " の自明文字鍵の全データで解くと、書けるのは動辺数（",
        math(String.raw`=|E|`),
        " の偶奇）と総和（標的の位相式）だけで、残る三寄与と三通りの二寄与和は",
        "いずれも書けない",
        "（sagemath/check/parity-identity-standard-form-statistics）。",
        "従って、少なくともこの候補基底だけから四寄与を個別に復元する経路は使えない。",
        "次に、辺対ごとの寄与を逐次相殺する局所対応を調べる。",
      ]),
      paragraph([
        "その対応を同じ頂点に接する辺だけで組むことはできない。標準形配向について、",
        "終点順序と始点順序の反転指示値の和が ", math(String.raw`1`),
        " になる有向辺対を全て取り出すと、端点を共有しない対が一辺二で ",
        math(String.raw`868`), " 対、一辺三で ", math(String.raw`5{,}340`),
        " 対現れる（sagemath/check/parity-identity-pair-locality）。",
        "従って、寄与する切断線対と内部対を直接対応させる規則は、",
        "離れた辺対も扱う必要がある。次は非共有端点対を相対座標で分類する。",
      ]),
      paragraph([
        "その相対座標分類の結果は次のとおりである。反転指示値の和は二つの有向辺だけで",
        "決まる関数なので、端点を共有しない有向辺対を相対座標の類（二辺の種類・向きと",
        "位置の差ベクトル mod ", math(String.raw`L`),
        "）で分類すると、各類はちょうど一つの対角平行移動軌道になる。寄与は類の上で",
        "一定ではない（混在する類が一辺三で ", math(String.raw`28`),
        "、一辺七で ", math(String.raw`268`),
        "）ので、相対座標だけによる対ごとの直接対応は組めない。一方、平行移動不変量は",
        "軌道合計の偶奇であり、辺長が偶数（", math(String.raw`L=2,4,6`),
        "）では全ての類で偶、辺長が奇数（", math(String.raw`L=3,5,7`),
        "）では奇の類が ", math(String.raw`20,\ 80,\ 172`),
        " 個現れ、それらは水平と垂直の混合対か同じ列内の逆向き垂直対に限る",
        "（同種で同じ向きの対の類は全て偶）。全配置が寄与する類は、辺長 ",
        math(String.raw`3`),
        " 以上では同じ列の逆向き垂直対（相対座標 ", math(String.raw`(0,j)`),
        "、", math(String.raw`j\neq 0`),
        "）にちょうど一致する（sagemath/check/parity-identity-pair-translation-orbit）。",
        "この分類は全有向辺対の上のものなので、鍵の動辺対への適用には動辺集合による",
        "制限を別に扱う必要がある。",
      ]),
      paragraph([
        "動辺集合で制限した非共有端点対の和も、軌道項と座標切断横断項へ正確に分かれる。",
        "各平行移動軌道の辞書式最小の辺対を代表に取ると、その軌道に属する動辺対の寄与の",
        "総和は、代表の寄与と動辺対数の積、終点二つの座標切断横断数、始点二つの座標切断",
        "横断数の三項の和に等しい。これは、二点を同時に平行移動したときの辞書式順序の",
        "変化が、最初に異なる座標で mod ", math(String.raw`L`),
        " の切断を片方だけが横切ることに等しいためである。標準形配向について一辺二の ",
        math(String.raw`369`), " 鍵・動辺対 ", math(String.raw`2{,}952`),
        " と、一辺三の ", math(String.raw`677`), " 鍵・動辺対 ",
        math(String.raw`14{,}472`),
        " で軌道ごとに検査した。一辺三では切断補正が奇になる軌道・鍵の組が ",
        math(String.raw`3{,}374`),
        " 件あるので、軌道代表の寄与だけでは制限和を復元できない",
        "（sagemath/check/parity-identity-active-pair-orbit-cut-decomposition）。",
        "次は共有端点対の寄与と局所位相を合わせ、この切断横断項と標的の巻き付き偶奇・",
        "交差対を結ぶ。",
      ]),
      paragraph([
        "共有端点対の寄与と局所位相は、頂点ごとの局所量へまとまる。端点を共有する",
        "動辺対の反転指示値を共有頂点（二つ共有する対は辞書式最小の共有頂点）へ",
        "割り付け、その頂点の局所行列式と合わせた頂点量 ",
        math(String.raw`w(v)=\det_v\cdot(-1)^{v\text{ へ割り付けた寄与和}}`),
        " を作ると、",
        math(String.raw`w(v)`),
        " は「四つの辺スロットの動辺の出入り」と「四つの切断隣接旗（行・列が ",
        math(String.raw`0`), " か ", math(String.raw`L-1`),
        " か）」の署名だけで決まり、鍵にも位置にも依らない（一辺二は旗つき署名 ",
        math(String.raw`160`), " 類・一辺三は ", math(String.raw`116`),
        " 類で混在零）。切断隣接旗を落とした局所配置だけでは決まらない",
        "（一辺三では全 ", math(String.raw`14`),
        " 署名が混在）。頂点量の積と非共有端点対の和・動辺数から従来の符号指数が",
        "再構成されることも全鍵で確かめた",
        "（sagemath/check/parity-identity-incident-pair-vertex-locality）。",
        "従って偶奇恒等式の左辺は、切断隣接旗つき署名で決まる頂点局所量と、",
        "非共有端点対の軌道項・座標切断横断項へ完全に局所化された。旗が全て零の",
        "内部署名は一辺三の中央頂点だけから得ており、一般の辺長での規則の同一性は",
        "未検査である。次は切断に触れる項（旗つき頂点量の切断依存部分と座標切断",
        "横断項）を標的の巻き付き偶奇・交差対へ同定する。",
      ]),
      paragraph([
        "切断依存部分だけを取り出す最初の基準は位相量への同定に届かなかった。",
        "同じ局所配置を一辺五の内部頂点へ移した頂点量を基準値とし、実際の頂点量との",
        "符号差を全頂点で足して、非共有端点対の座標切断横断項を加えた。この切断依存項と",
        "残る切断非依存項の和は標的の巻き付き偶奇・交差対の式に一致する。しかし同じ",
        "巻き付き偶奇と交差対を持つ鍵の中でも二項はともに値を変える",
        "（sagemath/check/parity-identity-cut-contribution-topological）。従って、局所配置を",
        "固定した内部頂点の値を引くだけでは切断依存項を位相量へ同定できない。次は二項を",
        "分離せず、切断を横切る辺を動かすときの両者の同時変化を追う。",
      ]),
      paragraph([
        "切断を横切る辺を動かす基本変形（プラケットとの対称差 ",
        math(String.raw`E\mapsto E\triangle P`),
        "）では、頂点項と非共有端点対項の和の変化が近傍だけで決まる。鍵と変形後の鍵の",
        "標準形配向での動辺数・頂点項・非共有端点対項・標的指数の四つの mod ",
        math(String.raw`2`),
        " 変化を全鍵で計算すると、変化の恒等式「動辺数＋頂点項＋対項＝標的指数」は毎回",
        "成り立ち、プラケットの切断旗（行・列が mod ", math(String.raw`L`),
        " で巻き戻るか）と近傍の ", math(String.raw`E,D`),
        " の入り方で分類すれば、二項の和の変化・動辺数の変化・標的指数の変化は全て",
        "分類ごとに一定になる（混在零。一辺二 ", math(String.raw`120`),
        " 変形・一辺三 ", math(String.raw`4{,}914`),
        " 変形、切断に接する変形はそれぞれ ", math(String.raw`90`),
        "・", math(String.raw`2{,}730`),
        "）。一辺三では二項への割り方だけが近傍で決まらない（混在 ",
        math(String.raw`16`),
        " 類）ので、二項は分離せず和として扱う",
        "（sagemath/check/parity-identity-plaquette-deformation）。",
      ]),
      paragraph([
        "ただし、この局所変形則で任意の鍵を切断に接しない代表へ運ぶことはできない。",
        "固定した反転対 ", math(String.raw`D`),
        " ごとに許された鍵をプラケット対称差で結ぶと、一辺三・",
        math(String.raw`D=\varnothing`),
        " では四成分が巻き付き偶奇の四類に一致し、切断辺数零の代表を持つのは",
        "零巻き付きの一成分だけである。さらに一辺二では、零巻き付き ",
        math(String.raw`94`), " 成分のうち ", math(String.raw`48`),
        " 成分にも切断辺数零の代表が無い。従って障害は非零巻き付きだけでなく、",
        math(String.raw`D`),
        " を固定し、曲がり型なし配向を持つ鍵に留める制約からも生じる",
        "（sagemath/check/parity-identity-plaquette-reduction）。次は切断辺を全て消す代わりに、",
        "各巻き付き類と ", math(String.raw`D`),
        " の制約に適合する標準代表を選び、その代表値を直接評価する。",
      ]),
      paragraph([
        "標準代表の最初の候補は直線ループの合併（行ループ＝一つの行の水平辺全部、",
        "列ループ＝一つの列の垂直辺全部の合併）である。直線合併を含む成分では、",
        "代表の四項（動辺数・頂点項・非共有端点対項・標的指数）は行集合・列集合の",
        "位置に依らず、行数・列数（一辺二ではさらに反転対 ", math(String.raw`D`),
        "）だけで決まる（一辺二 ", math(String.raw`105`),
        " 署名・一辺三 ", math(String.raw`7`),
        " 署名で混在零）。一辺三（", math(String.raw`D=\varnothing`),
        "）では直線合併の頂点項・対項は常に零で、動辺数と標的指数は行数と列数の和の",
        "偶奇に一致する。しかし一辺三の巻き付き ", math(String.raw`(1,1)`),
        " の成分は直線合併を含まない（行ループと列ループの合併は非自明文字なので",
        "許される鍵に入らない）。一辺二では ", math(String.raw`324`),
        " 成分のうち直線合併を含むのは ", math(String.raw`108`),
        " 成分だけで、含まない ", math(String.raw`216`),
        " 成分は四つの巻き付き類全てに現れる（", math(String.raw`48,\ 52,\ 52,\ 64`),
        "）。従って直線ループの合併だけでは標準代表系に足りない",
        "（sagemath/check/parity-identity-standard-representative）。次は直線合併を",
        "含まない成分の代表族（交差一周路型や ", math(String.raw`D`),
        " に適合した最小鍵）を特定する。",
      ]),
      paragraph([
        "直線合併を含まない成分では、辺数最小、その中で辞書式最小の代表を選ぶ。",
        "一辺二の未被覆 ", math(String.raw`216`),
        " 成分では全ての代表が四辺からなる連結な単純閉路であり、",
        math(String.raw`|D|=0,1,2,3,4`),
        " の全てが現れる。一辺三の未被覆成分は一つで、その代表は巻き付き偶奇 ",
        math(String.raw`(1,1)`),
        " の六辺単純閉路であり、四項（動辺数・頂点項・非共有端点対項・標的指数）は ",
        math(String.raw`(0,0,1,1)`),
        " になる。従って一辺二・三では、直線ループの合併と、反転対 ",
        math(String.raw`D`),
        " と互いに素で許される鍵をなす単一の単純閉路、という二族で全成分を覆う",
        "（sagemath/check/parity-identity-minimal-standard-representatives）。次は一般の辺長で ",
        math(String.raw`D`),
        " に適合する単純閉路代表の存在条件を記述し、その四項を閉路の方向列から評価する。",
      ]),
      paragraph([
        math(String.raw`E`),
        " が単一の単純閉路である鍵の全て（一辺二 ", math(String.raw`320`),
        " 鍵・一辺三 ", math(String.raw`312`),
        " 鍵）で、四項を方向列由来の統計（定数・", math(String.raw`|E|`),
        "・水平辺数・垂直辺数・巻き付き偶奇二つとその積・角の個数の半分・行 ",
        math(String.raw`0`), " と列 ", math(String.raw`0`),
        " の角の個数・", math(String.raw`|D|`),
        "・選択文字対の項）の ", math(String.raw`\mathbb F_2`),
        " 線型結合として解くと、一辺三（", math(String.raw`D=\varnothing`),
        "）では四項の全てが書け、角の統計は不要で、動辺数 ", math(String.raw`=|E|`),
        "、頂点項 ",
        math(String.raw`=1+|E|+\varepsilon_{\mathrm h}\varepsilon_{\mathrm v}`),
        "、対項 ", math(String.raw`=1+|E|`),
        "、標的指数 ",
        math(String.raw`=|E|+\varepsilon_{\mathrm h}\varepsilon_{\mathrm v}`),
        "（すべて mod ", math(String.raw`2`),
        "）が全鍵で成り立つ。一辺二では動辺数（常に ", math(String.raw`0`),
        "）と標的指数は書けるが、頂点項と非共有端点対項は ", math(String.raw`D`),
        " が動くため候補統計では書けない",
        "（sagemath/check/parity-identity-simple-cycle-key-terms）。従って ",
        math(String.raw`D=\varnothing`),
        " の側は方向列統計だけで閉じる見込みがあり、", math(String.raw`D\neq\varnothing`),
        " の側は ", math(String.raw`D`),
        " と閉路の相対配置を読む統計の追加が要る。次は一般の辺長で ",
        math(String.raw`D`),
        " に適合する単純閉路代表の存在条件を記述する。",
      ]),
      paragraph([
        "一辺 ", math(String.raw`L\ge2`), " で、互いに素な辺集合 ",
        math(String.raw`D,E\subseteq E_L`), " を取り、", math(String.raw`E`),
        " が空でない連結 ", math(String.raw`2`),
        " 正則辺集合、すなわち単一の単純閉路であるとする。辺集合 ",
        math(String.raw`F`), " の奇次数頂点集合を ",
        math(String.raw`\partial F:=\{v\in V_L\mid d_F(v)\equiv1\pmod2\}`),
        " と書けば、選択集合が非空となる必要十分条件は",
      ]),
      displayMath(String.raw`\mathcal C_L(D,E)\ne\varnothing
\quad\Longleftrightarrow\quad
\partial D\subseteq V(E)`),
      paragraph([
        "である。実際、選択 ", math(String.raw`C`), " があれば ",
        math(String.raw`\partial(D\cup C)=\varnothing`), " と ",
        math(String.raw`D\cap C=\varnothing`), " から ",
        math(String.raw`\partial D=\partial C\subseteq V(E)`),
        " である。逆に ", math(String.raw`\partial D\subseteq V(E)`),
        " なら、握手補題により ", math(String.raw`|\partial D|`),
        " は偶数である。閉路を一周し、各頂点で前後二辺の選択の排他的論理和をその頂点の ",
        math(String.raw`\partial D`),
        " への所属に一致させて順に決めると、一周後の整合条件はこの偶数性そのものであり、",
        math(String.raw`\partial C=\partial D`), " を満たす選択を得る。さらに ",
        math(String.raw`E\setminus C`),
        " も解であり、二解の対称差は連結な単純閉路の偶部分グラフなので、空集合か ",
        math(String.raw`E`),
        " 全体に限る。従って選択集合は非空なら、この補集合対のちょうど二元からなる",
        "（sagemath/check/simple-cycle-selector-existence）。この条件は一般の辺長で有限集合の",
        "所属判定だけにより決定できる。次はこの条件を満たす単純閉路を各プラケット変形成分で",
        "選べる条件を調べる。",
      ]),
      paragraph([
        "固定した反転対 ", math(String.raw`D`),
        " ごとのプラケット変形成分の全てについて、単一の単純閉路である代表の有無を",
        "全数で調べた。一辺三（", math(String.raw`D=\varnothing`),
        "）では四成分の全てが単純閉路代表を含む。一辺二では ", math(String.raw`324`),
        " 成分中 ", math(String.raw`287`),
        " 成分が含み、含まない ", math(String.raw`37`),
        " 成分は全て巻き付き偶奇が零で、うち ", math(String.raw`27`),
        " 成分は空集合の ", math(String.raw`E`),
        " を含み、残る ", math(String.raw`10`),
        " 成分の ", math(String.raw`E`),
        " は全て辺連結成分二つ以上である。どの成分も単純閉路の代表か直線ループの",
        "合併の代表を含むので、この二族で代表系は完成し、単純閉路の代表は選択集合の",
        "存在条件 ", math(String.raw`\partial D\subseteq V(E)`),
        " を満たす（sagemath/check/simple-cycle-component-coverage）。次は一辺二で",
        "方向列統計に不足した頂点項・非共有端点対項を、", math(String.raw`D`),
        " と閉路の相対配置を読む統計で書く。",
      ]),
      paragraph([
        "一辺二の単純閉路鍵全 ", math(String.raw`320`),
        " 件について、各頂点に接する上下左右の基底辺が反転対 ",
        math(String.raw`D`), " と単純閉路 ", math(String.raw`E`),
        " のどちらに属するか、および切断への隣接を局所署名として記録した。現れる署名は ",
        math(String.raw`124`), " 種、署名ごとの頂点数の偶奇からなる統計行列の階数は ",
        math(String.raw`89`), " であり、頂点項はその像に属する。得られた一つの表示は ",
        math(String.raw`46`), " 種の署名の個数の偶奇の和である。一辺二では動辺数が常に",
        "偶数なので、非共有端点対項も標的指数とこの頂点項の和で決まる",
        "（sagemath/check/parity-identity-simple-cycle-relative-configuration）。",
        "これは有限列挙による表示の存在確認であり、次は選ばれた署名の共通条件を取り出して、",
        "一般の辺長でも読める頂点ごとの閉じた符号公式へ縮約する。",
      ]),
      paragraph([
        "署名の成分——各頂点の上下左右のスロットの ", math(String.raw`D`),
        " 所属 ", math(String.raw`d_s`), "・", math(String.raw`E`),
        " 所属 ", math(String.raw`e_s`),
        " と切断隣接旗四つ——を ", math(String.raw`\mathbb F_2`),
        " 変数とみなし、次数 ", math(String.raw`k`),
        " 以下の単項式全体を特徴量として頂点項の頂点和表示を解いた。次数 ",
        math(String.raw`1,2`),
        " では切断旗を入れても解が無く、次数 ", math(String.raw`3`),
        " で初めて解ける。支持台を核ベクトルで縮めた表示は ",
        math(String.raw`16`),
        " 項で、次数 ", math(String.raw`3`),
        " の項は全て上・下・左スロットの所属変数一つずつの積、切断旗は ",
        math(String.raw`e_{\mathrm{up}}\cdot\mathrm{row0}`), " と ",
        math(String.raw`e_{\mathrm{left}}\cdot\mathrm{col0}`),
        " の二項にだけ現れる",
        "（sagemath/check/parity-identity-simple-cycle-local-sign-formula）。",
        "頂点項は二スロットの相関では書けず三スロットの相関を要する。次はこの式が",
        "一般の辺長の単純閉路鍵でも成り立つかを、一辺三以上の ",
        math(String.raw`D\ne\varnothing`),
        " を含む鍵の族で検査し、成り立つ形へ整える。",
      ]),
      paragraph([
        "この ", math(String.raw`16`),
        " 項式を一辺三の自明文字単純閉路と、選択集合が非空で ",
        math(String.raw`1\le |D|\le2`),
        " である全 ", math(String.raw`6{,}453`),
        " 鍵へ代入すると、", math(String.raw`3{,}246`),
        " 鍵で頂点項と一致しなかった。従って一辺二で得た式は重複隣接に依存し、",
        "一般辺長の公式にはならない",
        "（sagemath/check/parity-identity-simple-cycle-local-sign-formula-extension）。",
        "次は一辺二と一辺三を同時に満たす局所特徴を解く。",
      ]),
      paragraph([
        "一辺二の全 ", math(String.raw`320`),
        " 鍵と一辺三の全対象鍵（", math(String.raw`D=\varnothing`),
        " の ", math(String.raw`312`), " 件と選択集合が非空の ",
        math(String.raw`1\le|D|\le2`), " の ", math(String.raw`6{,}453`),
        " 件）を一つの ", math(String.raw`\mathbb F_2`),
        " 線型系に載せると、奇数回現れる署名の集合が等しく頂点項が異なる",
        "直接衝突は無い（相異なる奇署名集合 ", math(String.raw`7{,}084`),
        " 種）が、現れる署名 ", math(String.raw`274`),
        " 種に値を自由に割り当てても線型系（階数 ", math(String.raw`246`),
        "）に解が無い。従って上下左右のスロットの所属と切断隣接旗の ",
        math(String.raw`12`),
        " 変数の関数の頂点和では、両辺長の頂点項を同時に書けない",
        "（sagemath/check/parity-identity-simple-cycle-joint-local-sign-formula）。",
        "頂点署名は基底辺の所属しか見ないため、一辺二で対向スロットが同じ",
        "基底辺を指す重複隣接の情報が落ちている。次は署名に重複隣接旗を",
        "加えて同時に解けるかを検査する。",
      ]),
      paragraph([
        "対向スロットが同じ無向端点対を持つことを表す重複隣接旗二つを",
        "署名へ加えると、一辺二と一辺三の署名は分離する。しかし現れる署名 ",
        math(String.raw`394`), " 種・階数 ", math(String.raw`323`),
        " の合同線型系に解は無い。辺長ごとに分けると、一辺二は署名 ",
        math(String.raw`124`), " 種・階数 ", math(String.raw`89`),
        " で解を持つ一方、一辺三は署名 ", math(String.raw`270`),
        " 種・階数 ", math(String.raw`234`),
        " で単独でも解を持たない",
        "（sagemath/check/parity-identity-simple-cycle-joint-duplicate-adjacency）。",
        "従って不足は重複隣接の識別ではなく、", math(String.raw`D\ne\varnothing`),
        " の鍵で閉路上を伝播する選択情報を頂点局所署名が持たないことにある。",
        "次は選択集合の局所所属を署名へ加えて検査する。",
      ]),
    ],
  },
]);
