

# This file was *autogenerated* from the file check_01_inverse.sage
from sage.all_cmdline import *   # import sage library

_sage_const_212 = Integer(212); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_0p0 = RealNumber('0.0'); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_2 = Integer(2); _sage_const_1p0 = RealNumber('1.0')# <inverse_of_sqrt_cc> と <sqrt_cc_of_inverse>: sqrt(1/z) と 1/sqrt(z) の関係
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
load(os.path.join(_dir, "_prelude.sage"))
import numpy as np
import math
rng = np.random.default_rng(int(_sage_const_212 ))
rep = CheckReport("inverse_of_sqrt_cc / sqrt_cc_of_inverse")
zs = [z for z in sample_complex(rng) if abs(z) > _sage_const_1en8 ]
c0 = cp = _sage_const_0 
for z in zs:
    a = arg_def(z)
    lhs = sqrt_def(_sage_const_1 /z)
    rhs = _sage_const_1 /sqrt_def(z)
    # arg z = 0 かどうかで分岐が変わるが、arg が 0 の「すぐ上」（例 2e-15）だと
    # 1/z の arg が 2pi の「すぐ下」になり、倍精度ではどちらの分岐か定まらない。
    # 境界は分離して「± のいずれかに一致する」ことだけを見る。
    if a == _sage_const_0p0 :
        # arg z = 0 ちょうど（正の実数）。第1の場合。
        c0 += _sage_const_1 
        rep.close(lhs, rhs, f"z={z} arg=0: sqrt(1/z) = 1/sqrt z")
        rep.close(_sage_const_1 /sqrt_def(z), rhs, f"z={z}: (sqrt z)^{{-1}} = 1/sqrt z")
        continue
    if a < _sage_const_1en9  or a > _sage_const_2 *math.pi - _sage_const_1en9 :
        # arg が 0 の「すぐ上」/「2pi のすぐ下」。1/z の arg が反対側の境界に来るため
        # 倍精度ではどちらの分岐か定まらない。± のいずれかに一致することだけを見る。
        ok = (abs(lhs - rhs) < _sage_const_1en8 *max(_sage_const_1p0 ,abs(rhs))) or (abs(lhs + rhs) < _sage_const_1en8 *max(_sage_const_1p0 ,abs(rhs)))
        rep.truth(ok, f"境界 z={z} arg={a:.3e}: ± のいずれかに一致")
        rep.close(_sage_const_1 /sqrt_def(z), rhs, f"z={z}: (sqrt z)^{{-1}} = 1/sqrt z")
        continue
    else:
        cp += _sage_const_1 
        rep.close(lhs, -rhs, f"z={z} 0<arg<2pi: sqrt(1/z) = -1/sqrt z")
    # <sqrt_cc_of_inverse> は同じ内容を (sqrt z)^{-1} の側から述べたもの
    rep.close(_sage_const_1 /sqrt_def(z), rhs, f"z={z}: (sqrt z)^{{-1}} = 1/sqrt z")
print(f"  arg=0 の場合 {c0} 件、0<arg<2pi の場合 {cp} 件")
rep.truth(c0 > _sage_const_0  and cp > _sage_const_0 , "両方の場合を踏んでいる")
rep.finish()

