/**
 * 章「既存因果構造との比較」: 前章までで得た組 (E_τ, ⪯_τ, D_τ) について、
 * 外部の因果構造と比較するときに使う順序側の性質だけを確定する。
 *
 * - 区間の有限性（順序の言葉だけで述べた有限性）
 * - 一段依存関係が順序の被覆関係として復元できること（保存される構造）
 * - 順序を保つ全単射が時刻写像を保つとは限らないこと（失われる情報。反例）
 *
 * 文献が「causal set」等の名で定める公理系との同定は、一次文献の定義を確認した後の
 * 層で行い、この章では行わない（二次情報に基づく同定を記さない）。
 * 物理的な意味（因果・光円錐・時空）はここへ持ち込まない。
 * 使う ℕ の構造は前章までと同じく大小比較・後者・等号だけである。ℝ/ℂ は現れない。
 * 文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "causal_structure_comparison_heading",
    kind: "heading",
    level: 1,
    title: { text: "既存因果構造との比較" },
    labels: [],
  },

  {
    id: "causal_structure_comparison_remark_scope",
    kind: "remark",
    title: { text: "この章の範囲" },
    labels: ["remark_causal_comparison_scope"],
    habitat: "finite",
    statement: [
      paragraph([
        "この章では、イベント集合 ",
        math(String.raw`E_\tau`),
        "（",
        ref("def_event_set"),
        "）、反射的到達可能関係 ",
        math(String.raw`\preceq_\tau`),
        "（",
        ref("def_ca_reflexive_reachability"),
        "）、一段依存関係 ",
        math(String.raw`D_\tau`),
        "（",
        ref("def_one_step_dependency"),
        "）だけから述べられる性質を確定する。",
        "外部の文献が固有の名で定める因果構造の公理系との同定は、",
        "その一次文献の定義を確認してから別の層で行い、この章では行わない。",
        "なお ",
        math(String.raw`C_\tau`),
        " は ",
        math(String.raw`D_\tau`),
        " を含む最小の推移的関係であり（",
        ref("claim_reachability_minimal"),
        "）、",
        math(String.raw`\preceq_\tau`),
        " は ",
        math(String.raw`C_\tau`),
        " から定義される（",
        ref("def_ca_reflexive_reachability"),
        "）から、順序側の対象は ",
        math(String.raw`D_\tau`),
        " から定まる。この章の被覆関係の claim は、その逆向き、すなわち ",
        math(String.raw`D_\tau`),
        " が順序側から復元できることを与える。",
      ]),
    ],
  },

  {
    id: "causal_structure_comparison_definition_order_interval",
    kind: "definition",
    title: { text: "区間" },
    labels: ["def_order_interval"],
    habitat: "finite",
    statement: [
      paragraph([
        ref("claim_reachability_partial_order"), " による有限半順序を ",
        ref("def_finite_poset_interval"), " に特殊化する。有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）と ",
        math(String.raw`\tau\in\mathbb{N}`),
        " と ",
        math(String.raw`a,b\in E_\tau`),
        " に対し、集合",
      ]),
      displayMath(
        String.raw`I_\tau(a,b):=\bigl\{\,c\in E_\tau\ \bigm|\ a\preceq_\tau c\ \text{かつ}\ c\preceq_\tau b\,\bigr\}`,
      ),
      paragraph([
        "と書く（",
        math(String.raw`\preceq_\tau`),
        " は ",
        ref("def_ca_reflexive_reachability"),
        "）。これは有限半順序の区間である。時間区間 ",
        math(String.raw`[0,\tau]_{\mathbb{N}}`),
        "（",
        ref("def_finite_index_interval"),
        "）とは別の対象なので、記号は ",
        math(String.raw`I_\tau(a,b)`),
        " を使い、角括弧による区間記法を使い回さない。",
      ]),
    ],
  },

  {
    id: "causal_structure_comparison_claim_interval_finite",
    kind: "claim",
    title: { text: "区間は有限である" },
    labels: ["claim_order_interval_finite"],
    habitat: "N",
    statement: [
      paragraph([
        "任意の ",
        math(String.raw`a,b\in E_\tau`),
        " について、区間 ",
        math(String.raw`I_\tau(a,b)`),
        "（",
        ref("def_order_interval"),
        "）は有限集合であり、元の個数は ",
        math(String.raw`|I_\tau(a,b)|\leq(\tau+1)\cdot|V|`),
        " を満たす（",
        math(String.raw`|\cdot|`),
        " は ",
        ref("def_cardinality_notation"),
        "、",
        math(String.raw`\leq`),
        " と ",
        math(String.raw`\cdot`),
        " は ",
        math(String.raw`\mathbb{N}`),
        " の大小比較と乗法）。",
      ]),
    ],
    proof: [
      paragraph([
        ref("def_order_interval"), " より ",
        math(String.raw`I_\tau(a,b)\subseteq E_\tau`),
        " である。",
        ref("claim_event_set_cardinality"),
        " より ",
        math(String.raw`E_\tau`),
        " は有限集合で ",
        math(String.raw`|E_\tau|=(\tau+1)\cdot|V|`),
        " である。有限集合の部分集合は有限であり、その元の個数は全体の元の個数以下なので、",
        math(String.raw`I_\tau(a,b)`),
        " は有限集合で ",
        math(String.raw`|I_\tau(a,b)|\leq|E_\tau|=(\tau+1)\cdot|V|`),
        " である。個数の比較はいずれも ",
        math(String.raw`\mathbb{N}`),
        " の元の間で行われ、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "causal_structure_comparison_definition_finite_relation_covering",
    kind: "definition",
    title: { text: "有限関係の被覆関係" },
    labels: ["def_finite_relation_covering"],
    habitat: "finite",
    statement: [
      paragraph(["有限集合 ", math(String.raw`X`), " と二項関係 ", math(String.raw`Q\subseteq X\times X`), " に対し、"]),
      displayMath(String.raw`\operatorname{Cov}(Q):=\{\,(a,b)\in Q\mid\text{どの }c\in X\text{ も }(a,c)\in Q\text{ かつ }(c,b)\in Q\text{ を満たさない}\,\}`),
      paragraph(["と定め、", math(String.raw`Q`), " の被覆関係と呼ぶ。"]),
    ],
  },

  {
    id: "causal_structure_comparison_definition_covering_relation",
    kind: "definition",
    title: { text: "被覆関係" },
    labels: ["def_covering_relation"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）と ",
        math(String.raw`\tau\in\mathbb{N}`),
        " に対し、", ref("def_ca_reachability"), " の有限関係 ",
        math(String.raw`C_\tau`), " を ", ref("def_finite_relation_covering"),
        " に特殊化し、集合",
      ]),
      displayMath(
        String.raw`\lessdot_\tau\ :=\ \bigl\{\,(a,b)\in C_\tau\ \bigm|\ \text{どの}\ c\in E_\tau\ \text{も}\ (a,c)\in C_\tau\ \text{かつ}\ (c,b)\in C_\tau\ \text{を満たさない}\,\bigr\}`,
      ),
      paragraph([
        "と書く。",
        math(String.raw`\lessdot_\tau`),
        " は ",
        math(String.raw`E_\tau`),
        " と ",
        math(String.raw`C_\tau`),
        " だけから定義されており、局所真理値表を参照しない。",
        math(String.raw`\lessdot_\tau=\operatorname{Cov}(C_\tau)`),
        " であり、", math(String.raw`\lessdot_\tau\subseteq C_\tau`),
        " は ", ref("def_finite_relation_covering"), " の条件そのものである。",
      ]),
    ],
  },

  {
    id: "causal_structure_comparison_claim_one_step_subset_covering",
    kind: "claim",
    title: { text: "一段依存関係は被覆関係に含まれる" },
    labels: ["claim_one_step_subset_covering"],
    habitat: "N",
    statement: [
      paragraph([
        math(String.raw`D_\tau\subseteq\ \lessdot_\tau`),
        " が成り立つ（",
        math(String.raw`D_\tau`),
        " は ",
        ref("def_one_step_dependency"),
        "、",
        math(String.raw`\lessdot_\tau`),
        " は ",
        ref("def_covering_relation"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`(a,b)\in D_\tau`),
        " を任意に取り、",
        math(String.raw`a=(s,u)`),
        "、",
        math(String.raw`b=(t,v)`),
        " と成分を書く（",
        ref("def_event_set"),
        "）。",
        ref("def_one_step_dependency"),
        " より ",
        math(String.raw`t=s+1`),
        " である。まず ",
        ref("claim_one_step_subset_reachability"),
        " より ",
        math(String.raw`(a,b)\in C_\tau`),
        " である。",
      ]),
      paragraph([
        "次に、",
        math(String.raw`(a,c)\in C_\tau`),
        " かつ ",
        math(String.raw`(c,b)\in C_\tau`),
        " を満たす ",
        math(String.raw`c\in E_\tau`),
        " が存在すると仮定して矛盾を導く。",
        math(String.raw`c=(r,w)`),
        " と成分を書く。",
        math(String.raw`(a,c)\in C_\tau`),
        " より ",
        math(String.raw`a`),
        " から ",
        math(String.raw`c`),
        " への依存経路が存在し（",
        ref("def_ca_reachability"),
        "）、",
        ref("claim_path_time_strictly_increases"),
        " より ",
        math(String.raw`s<r`),
        " である。同様に ",
        math(String.raw`(c,b)\in C_\tau`),
        " と ",
        ref("claim_path_time_strictly_increases"),
        " より ",
        math(String.raw`r<t`),
        " である。",
        math(String.raw`\mathbb{N}`),
        " の大小比較の性質「",
        math(String.raw`s<r`),
        " と ",
        math(String.raw`s+1\leq r`),
        " は同値」より ",
        math(String.raw`s+1\leq r`),
        " であり、",
        math(String.raw`t=s+1`),
        " を ",
        math(String.raw`r<t`),
        " へ代入して ",
        math(String.raw`r<s+1`),
        " である。",
        math(String.raw`\mathbb{N}`),
        " の大小比較の推移性（",
        math(String.raw`s+1\leq r`),
        " かつ ",
        math(String.raw`r<s+1`),
        "）より ",
        math(String.raw`s+1<s+1`),
        " となるが、",
        math(String.raw`\mathbb{N}`),
        " の大小比較は非反射的なので矛盾である。",
      ]),
      paragraph([
        "よってそのような ",
        math(String.raw`c`),
        " は存在せず、",
        ref("def_covering_relation"),
        " の条件がすべて満たされるので ",
        math(String.raw`(a,b)\in\ \lessdot_\tau`),
        " である。",
      ]),
    ],
  },

  {
    id: "causal_structure_comparison_claim_covering_subset_one_step",
    kind: "claim",
    title: { text: "被覆関係は一段依存関係に含まれる" },
    labels: ["claim_covering_subset_one_step"],
    habitat: "N",
    statement: [
      paragraph([
        math(String.raw`\lessdot_\tau\ \subseteq D_\tau`),
        " が成り立つ（",
        math(String.raw`\lessdot_\tau`),
        " は ",
        ref("def_covering_relation"),
        "、",
        math(String.raw`D_\tau`),
        " は ",
        ref("def_one_step_dependency"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`(a,b)\in\ \lessdot_\tau`),
        " を任意に取る。",
        ref("def_covering_relation"),
        " より ",
        math(String.raw`(a,b)\in C_\tau`),
        " なので、",
        math(String.raw`a`),
        " から ",
        math(String.raw`b`),
        " への長さ ",
        math(String.raw`n\geq1`),
        " の依存経路 ",
        math(String.raw`(n,p)`),
        " が存在する（",
        ref("def_ca_reachability"),
        "、",
        ref("def_ca_dependency_path"),
        "）。",
        math(String.raw`n=1`),
        " か ",
        math(String.raw`n\geq2`),
        " かで場合を分ける。",
      ]),
      paragraph([
        math(String.raw`n\geq2`),
        " の場合: ",
        math(String.raw`c:=p(1)\in E_\tau`),
        " と置く。",
        math(String.raw`p`),
        " の ",
        math(String.raw`[0,1]_{\mathbb{N}}`),
        " への制限は、",
        ref("def_ca_dependency_path"),
        " の条件（",
        math(String.raw`\bigl(p(0),p(1)\bigr)\in D_\tau`),
        "）を満たすので、",
        math(String.raw`a`),
        " から ",
        math(String.raw`c`),
        " への長さ ",
        math(String.raw`1`),
        " の依存経路であり、",
        ref("def_ca_reachability"),
        " より ",
        math(String.raw`(a,c)\in C_\tau`),
        " である。また写像 ",
        math(String.raw`q:[0,n-1]_{\mathbb{N}}\to E_\tau`),
        " を ",
        math(String.raw`q(i):=p(i+1)`),
        " で定めると、すべての ",
        math(String.raw`i\in[0,n-2]_{\mathbb{N}}`),
        " について ",
        math(String.raw`\bigl(q(i),q(i+1)\bigr)=\bigl(p(i+1),p(i+2)\bigr)\in D_\tau`),
        "（",
        ref("def_ca_dependency_path"),
        " の ",
        math(String.raw`p`),
        " の条件）であり、",
        math(String.raw`n-1\geq1`),
        " なので、組 ",
        math(String.raw`(n-1,q)`),
        " は ",
        math(String.raw`c`),
        " から ",
        math(String.raw`b`),
        " への依存経路である。よって ",
        ref("def_ca_reachability"),
        " より ",
        math(String.raw`(c,b)\in C_\tau`),
        " である。この ",
        math(String.raw`c`),
        " は ",
        ref("def_covering_relation"),
        " の「どの ",
        math(String.raw`c\in E_\tau`),
        " も満たさない」という条件に矛盾する。よって ",
        math(String.raw`n\geq2`),
        " ではない。",
      ]),
      paragraph([
        math(String.raw`n=1`),
        " の場合: ",
        ref("def_ca_dependency_path"),
        " の条件より ",
        math(String.raw`\bigl(p(0),p(1)\bigr)\in D_\tau`),
        " であり、",
        math(String.raw`p(0)=a`),
        "、",
        math(String.raw`p(1)=b`),
        " なので ",
        math(String.raw`(a,b)\in D_\tau`),
        " である。",
      ]),
    ],
  },

  {
    id: "causal_structure_comparison_claim_one_step_equals_covering",
    kind: "claim",
    title: { text: "一段依存関係は被覆関係と一致する" },
    labels: ["claim_one_step_equals_covering"],
    habitat: "finite",
    statement: [
      paragraph([
        math(String.raw`D_\tau=\ \lessdot_\tau`),
        " が成り立つ（",
        math(String.raw`D_\tau`),
        " は ",
        ref("def_one_step_dependency"),
        "、",
        math(String.raw`\lessdot_\tau`),
        " は ",
        ref("def_covering_relation"),
        "）。",
        ref("def_covering_relation"),
        " は ",
        math(String.raw`E_\tau`),
        " と ",
        math(String.raw`C_\tau`),
        " だけを参照するので、この等号は、一段依存関係が組 ",
        math(String.raw`(E_\tau,C_\tau)`),
        " だけから復元できることを与える。",
      ]),
    ],
    proof: [
      paragraph([
        "集合の等号を両包含で示す。",
        math(String.raw`D_\tau\subseteq\ \lessdot_\tau`),
        " は ",
        ref("claim_one_step_subset_covering"),
        " である。",
        math(String.raw`\lessdot_\tau\ \subseteq D_\tau`),
        " は ",
        ref("claim_covering_subset_one_step"),
        " である。",
      ]),
    ],
  },

  {
    id: "causal_structure_comparison_claim_order_iso_not_time_preserving",
    kind: "claim",
    title: { text: "順序を保つ全単射は時刻写像を保つとは限らない" },
    labels: ["claim_order_iso_not_time_preserving"],
    habitat: "N",
    statement: [
      paragraph([
        "次を満たす有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）、",
        math(String.raw`\tau\in\mathbb{N}`),
        "、全単射 ",
        math(String.raw`\sigma:E_\tau\to E_\tau`),
        " が存在する: すべての ",
        math(String.raw`a,b\in E_\tau`),
        " について ",
        math(String.raw`a\preceq_\tau b`),
        " と ",
        math(String.raw`\sigma(a)\preceq_\tau\sigma(b)`),
        " が同値であり（",
        math(String.raw`\preceq_\tau`),
        " は ",
        ref("def_ca_reflexive_reachability"),
        "）、かつ、第 1 成分（時刻）が ",
        math(String.raw`\sigma`),
        " で変わるイベント、すなわち ",
        math(String.raw`a=(s,u)\in E_\tau`),
        " であって ",
        math(String.raw`\sigma(a)`),
        " の第 1 成分が ",
        math(String.raw`s`),
        " と異なるものが存在する。したがって、イベントの時刻は組 ",
        math(String.raw`(E_\tau,\preceq_\tau)`),
        " だけからは定まらない。",
      ]),
    ],
    proof: [
      paragraph([
        "具体的に構成する。",
        math(String.raw`V:=\{v\}`),
        "（1 元集合）、",
        math(String.raw`N(v):=\{v\}`),
        " と置くと ",
        math(String.raw`(V,N)`),
        " は有限舞台である（",
        ref("def_finite_stage"),
        "）。",
        math(String.raw`f_v:A^{N(v)}\to A`),
        " を、すべての ",
        math(String.raw`x\in A^{N(v)}`),
        " について ",
        math(String.raw`f_v(x):=0`),
        " と定める（",
        math(String.raw`A=\{0,1\}`),
        " は ",
        ref("def_state_set"),
        "）。",
        math(String.raw`\tau:=1`),
        " と置く。",
      ]),
      paragraph([
        "まず ",
        math(String.raw`\operatorname{supp}(f_v)=\emptyset`),
        " を示す。",
        math(String.raw`w\in\operatorname{supp}(f_v)`),
        " と仮定すると、",
        ref("def_essential_dependency_support"),
        " と ",
        ref("def_essential_dependency"),
        " より、",
        math(String.raw`f_v(x)\neq f_v(x')`),
        " を満たす ",
        math(String.raw`x,x'\in A^{N(v)}`),
        " が存在する。しかし ",
        math(String.raw`f_v`),
        " の定義より ",
        math(String.raw`f_v(x)=0`),
        " かつ ",
        math(String.raw`f_v(x')=0`),
        " なので、",
        math(String.raw`A`),
        " の元の等号より ",
        math(String.raw`f_v(x)=f_v(x')`),
        " となり矛盾である。よって ",
        math(String.raw`\operatorname{supp}(f_v)=\emptyset`),
        " である。",
      ]),
      paragraph([
        "次に ",
        math(String.raw`D_\tau=\emptyset`),
        " を示す。",
        math(String.raw`\bigl((s,u),(t,v)\bigr)\in D_\tau`),
        " と仮定すると、",
        ref("def_one_step_dependency"),
        " より ",
        math(String.raw`u\in\operatorname{supp}(f_v)=\emptyset`),
        " となるが、空集合に元は存在しないので矛盾である。さらに ",
        math(String.raw`C_\tau=\emptyset`),
        " である: ",
        math(String.raw`(a,b)\in C_\tau`),
        " と仮定すると依存経路 ",
        math(String.raw`(n,p)`),
        " が存在し（",
        ref("def_ca_reachability"),
        "）、",
        math(String.raw`n\geq1`),
        " なので ",
        ref("def_ca_dependency_path"),
        " の条件より ",
        math(String.raw`\bigl(p(0),p(1)\bigr)\in D_\tau=\emptyset`),
        " となり矛盾である。よって ",
        ref("def_ca_reflexive_reachability"),
        " より、すべての ",
        math(String.raw`a,b\in E_\tau`),
        " について ",
        math(String.raw`a\preceq_\tau b`),
        " と ",
        math(String.raw`a=b`),
        " は同値である。",
      ]),
      paragraph([
        ref("def_event_set"),
        " より ",
        math(String.raw`E_\tau=[0,1]_{\mathbb{N}}\times\{v\}=\{(0,v),(1,v)\}`),
        " である。写像 ",
        math(String.raw`\sigma:E_\tau\to E_\tau`),
        " を ",
        math(String.raw`\sigma\bigl((0,v)\bigr):=(1,v)`),
        "、",
        math(String.raw`\sigma\bigl((1,v)\bigr):=(0,v)`),
        " と定める。",
        math(String.raw`\sigma\circ\sigma`),
        " は恒等写像なので ",
        math(String.raw`\sigma`),
        " は全単射である。",
      ]),
      paragraph([
        "順序の保存を示す。任意の ",
        math(String.raw`a,b\in E_\tau`),
        " について、",
        math(String.raw`a\preceq_\tau b`),
        " は ",
        math(String.raw`a=b`),
        " と同値（上で示した）であり、",
        math(String.raw`a=b`),
        " ならば写像の値の等号より ",
        math(String.raw`\sigma(a)=\sigma(b)`),
        "、逆に ",
        math(String.raw`\sigma(a)=\sigma(b)`),
        " ならば ",
        math(String.raw`\sigma\circ\sigma`),
        " が恒等写像であることより ",
        math(String.raw`a=b`),
        " なので、",
        math(String.raw`a=b`),
        " と ",
        math(String.raw`\sigma(a)=\sigma(b)`),
        " は同値である。",
        math(String.raw`\sigma(a)=\sigma(b)`),
        " は ",
        math(String.raw`\sigma(a)\preceq_\tau\sigma(b)`),
        " と同値（上で示した同値を ",
        math(String.raw`\sigma(a),\sigma(b)`),
        " へ適用）なので、",
        math(String.raw`a\preceq_\tau b`),
        " と ",
        math(String.raw`\sigma(a)\preceq_\tau\sigma(b)`),
        " は同値である。",
      ]),
      paragraph([
        "最後に、",
        math(String.raw`a:=(0,v)`),
        " と置くと ",
        math(String.raw`\sigma(a)=(1,v)`),
        " の第 1 成分は ",
        math(String.raw`1`),
        " であり、",
        math(String.raw`\mathbb{N}`),
        " の元の等号として ",
        math(String.raw`1\neq0`),
        " なので、第 1 成分が ",
        math(String.raw`\sigma`),
        " で変わるイベントが存在する。以上ですべての条件が構成した組で満たされた。",
      ]),
    ],
  },
]);
