/**
 * 章「依存順序から得る部分構造」: 前章までで得たイベント集合 E_τ と
 * 反射的到達可能関係 ⪯_τ（部分順序）だけから内在的に定義できる部分構造
 * （順序凸部分集合・下方集合・上方集合・非比較関係・反鎖・時刻切片・一段境界）を
 * 定義し、それらの間の基本的な包含・閉性を示す。
 *
 * 物理的な意味（因果・光円錐・時空・地平面など）はここへ持ち込まない。
 * 既存の因果構造（causal set 等）との比較は、このカタログが揃った後の別の対象で行う。
 * 使う ℕ の構造は前章までと同じく大小比較だけである。ℝ/ℂ は現れない。
 * 文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "dependency_order_substructures_heading",
    kind: "heading",
    level: 1,
    title: { text: "依存順序から得る部分構造" },
    labels: [],
  },

  {
    id: "dependency_order_substructures_definition_order_convex",
    kind: "definition",
    title: { text: "順序凸部分集合" },
    labels: ["def_order_convex_subset"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限集合 ", math(String.raw`X`), " とその上の部分順序 ",
        math(String.raw`R\subseteq X\times X`), "（", ref("def_partial_order"),
        "）に対し、", math(String.raw`a\preceq_R b`), " を ",
        math(String.raw`(a,b)\in R`), " の略記とする。部分集合 ",
        math(String.raw`K\subseteq X`),
        " が",
        "順序凸",
        "であるとは、すべての ",
        math(String.raw`a,c\in K`),
        " とすべての ",
        math(String.raw`b\in X`),
        " について、",
        math(String.raw`a\preceq_R b`),
        " かつ ",
        math(String.raw`b\preceq_R c`),
        " ならば ",
        math(String.raw`b\in K`),
        " が成り立つことをいう（",
        math(String.raw`\preceq_R`),
        " は上の部分順序である）。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_claim_order_convex_subset_finite",
    kind: "claim",
    title: { text: "有限半順序の順序凸部分集合は有限である" },
    labels: ["claim_order_convex_subset_finite"],
    habitat: "finite",
    statement: [paragraph([
      ref("def_order_convex_subset"), " の順序凸部分集合 ", math(String.raw`K\subseteq X`),
      " は有限集合である。",
    ])],
    proof: [paragraph(["有限集合の部分集合は有限なのである。"])],
  },

  {
    id: "dependency_order_substructures_definition_down_set",
    kind: "definition",
    title: { text: "下方集合" },
    labels: ["def_down_set"],
    habitat: "finite",
    statement: [
      paragraph([
        "部分集合 ",
        math(String.raw`J\subseteq X`),
        " が",
        "下方集合",
        "であるとは、すべての ",
        math(String.raw`a\in J`),
        " とすべての ",
        math(String.raw`b\in X`),
        " について、",
        math(String.raw`b\preceq_R a`),
        " ならば ",
        math(String.raw`b\in J`),
        " が成り立つことをいう（",
        math(String.raw`\preceq_R`),
        " は ",
        ref("def_partial_order"),
        "）。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_definition_up_set",
    kind: "definition",
    title: { text: "上方集合" },
    labels: ["def_up_set"],
    habitat: "finite",
    statement: [
      paragraph([
        "部分集合 ",
        math(String.raw`U\subseteq X`),
        " が",
        "上方集合",
        "であるとは、すべての ",
        math(String.raw`a\in U`),
        " とすべての ",
        math(String.raw`b\in X`),
        " について、",
        math(String.raw`a\preceq_R b`),
        " ならば ",
        math(String.raw`b\in U`),
        " が成り立つことをいう（",
        math(String.raw`\preceq_R`),
        " は ",
        ref("def_partial_order"),
        "）。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_claim_down_set_order_convex",
    kind: "claim",
    title: { text: "下方集合は順序凸である" },
    labels: ["claim_down_set_order_convex"],
    habitat: "finite",
    statement: [
      paragraph([
        "任意の下方集合 ",
        math(String.raw`J\subseteq X`),
        "（",
        ref("def_down_set"),
        "）は順序凸（",
        ref("def_order_convex_subset"),
        "）である。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`a,c\in J`),
        "、",
        math(String.raw`b\in X`),
        "、",
        math(String.raw`a\preceq_R b`),
        "、",
        math(String.raw`b\preceq_R c`),
        " とする。",
        math(String.raw`b\preceq_R c`),
        " かつ ",
        math(String.raw`c\in J`),
        " なので、",
        ref("def_down_set"),
        " より ",
        math(String.raw`b\in J`),
        " である。よって ",
        ref("def_order_convex_subset"),
        " の条件が成り立つ（仮定 ",
        math(String.raw`a\preceq_R b`),
        " はこの証明では使わない）。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_claim_up_set_order_convex",
    kind: "claim",
    title: { text: "上方集合は順序凸である" },
    labels: ["claim_up_set_order_convex"],
    habitat: "finite",
    statement: [
      paragraph([
        "任意の上方集合 ",
        math(String.raw`U\subseteq X`),
        "（",
        ref("def_up_set"),
        "）は順序凸（",
        ref("def_order_convex_subset"),
        "）である。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`a,c\in U`),
        "、",
        math(String.raw`b\in X`),
        "、",
        math(String.raw`a\preceq_R b`),
        "、",
        math(String.raw`b\preceq_R c`),
        " とする。",
        math(String.raw`a\preceq_R b`),
        " かつ ",
        math(String.raw`a\in U`),
        " なので、",
        ref("def_up_set"),
        " より ",
        math(String.raw`b\in U`),
        " である。よって ",
        ref("def_order_convex_subset"),
        " の条件が成り立つ（仮定 ",
        math(String.raw`b\preceq_R c`),
        " はこの証明では使わない）。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_claim_order_convex_intersection",
    kind: "claim",
    title: { text: "順序凸部分集合の共通部分は順序凸である" },
    labels: ["claim_order_convex_intersection"],
    habitat: "finite",
    statement: [
      paragraph([
        math(String.raw`K_1,K_2\subseteq X`),
        " がともに順序凸（",
        ref("def_order_convex_subset"),
        "）ならば、共通部分 ",
        math(String.raw`K_1\cap K_2`),
        " も順序凸である。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`a,c\in K_1\cap K_2`),
        "、",
        math(String.raw`b\in X`),
        "、",
        math(String.raw`a\preceq_R b`),
        "、",
        math(String.raw`b\preceq_R c`),
        " とする。共通部分の定義より ",
        math(String.raw`a,c\in K_1`),
        " なので、",
        math(String.raw`K_1`),
        " の順序凸性（",
        ref("def_order_convex_subset"),
        "）より ",
        math(String.raw`b\in K_1`),
        " である。同じ仮定に ",
        math(String.raw`K_2`),
        " の順序凸性（",
        ref("def_order_convex_subset"),
        "）を適用して ",
        math(String.raw`b\in K_2`),
        " である。共通部分の定義より ",
        math(String.raw`b\in K_1\cap K_2`),
        " である。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_definition_incomparability",
    kind: "definition",
    title: { text: "非比較関係" },
    labels: ["def_incomparability"],
    habitat: "finite",
    statement: [
      paragraph(["集合"]),
      displayMath(
        String.raw`\perp_R\ :=\ \bigl\{\,(a,b)\in X\times X\ \bigm|\ a\not\preceq_R b\ \text{かつ}\ b\not\preceq_R a\,\bigr\}`,
      ),
      paragraph([
        "を",
        "非比較関係",
        "と呼ぶ（",
        math(String.raw`\preceq_R`),
        " は ",
        ref("def_partial_order"),
        "）。定義の 2 条件は ",
        math(String.raw`a`),
        " と ",
        math(String.raw`b`),
        " の入れ替えで互いに移り合うので、",
        math(String.raw`(a,b)\in\ \perp_R`),
        " と ",
        math(String.raw`(b,a)\in\ \perp_R`),
        " は同値である。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_definition_antichain",
    kind: "definition",
    title: { text: "反鎖" },
    labels: ["def_antichain"],
    habitat: "finite",
    statement: [
      paragraph([
        "部分集合 ",
        math(String.raw`K\subseteq X`),
        " が",
        "反鎖",
        "であるとは、すべての ",
        math(String.raw`a,b\in K`),
        " について、",
        math(String.raw`a\neq b`),
        " ならば ",
        math(String.raw`(a,b)\in\ \perp_R`),
        " が成り立つことをいう（",
        math(String.raw`\perp_R`),
        " は ",
        ref("def_incomparability"),
        "。等号は直積集合 ",
        math(String.raw`X`),
        " の元の等号）。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_claim_antichain_order_convex",
    kind: "claim",
    title: { text: "反鎖は順序凸である" },
    labels: ["claim_antichain_order_convex"],
    habitat: "finite",
    statement: [
      paragraph([
        "任意の反鎖 ",
        math(String.raw`K\subseteq X`),
        "（",
        ref("def_antichain"),
        "）は順序凸（",
        ref("def_order_convex_subset"),
        "）である。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`a,c\in K`),
        "、",
        math(String.raw`b\in X`),
        "、",
        math(String.raw`a\preceq_R b`),
        "、",
        math(String.raw`b\preceq_R c`),
        " とする。",
        math(String.raw`a=c`),
        " か否かで場合を分ける。",
      ]),
      paragraph([
        math(String.raw`a\neq c`),
        " の場合: ",
        math(String.raw`\preceq_R`),
        " の推移性（",
        ref("def_partial_order"),
        "）より ",
        math(String.raw`a\preceq_R c`),
        " である。一方、",
        math(String.raw`a,c\in K`),
        " かつ ",
        math(String.raw`a\neq c`),
        " なので、",
        ref("def_antichain"),
        " より ",
        math(String.raw`(a,c)\in\ \perp_R`),
        "、すなわち ",
        ref("def_incomparability"),
        " より ",
        math(String.raw`a\not\preceq_R c`),
        " である。これは矛盾なので、この場合は起こらない。",
      ]),
      paragraph([
        math(String.raw`a=c`),
        " の場合: ",
        math(String.raw`b\preceq_R c`),
        " の ",
        math(String.raw`c`),
        " を等しい元 ",
        math(String.raw`a`),
        " で置き換えて ",
        math(String.raw`b\preceq_R a`),
        " である。",
        math(String.raw`a\preceq_R b`),
        " と合わせて、",
        math(String.raw`\preceq_R`),
        " の反対称性（",
        ref("def_partial_order"),
        "）より ",
        math(String.raw`b=a`),
        " であり、",
        math(String.raw`a\in K`),
        " なので ",
        math(String.raw`b\in K`),
        " である。",
      ]),
      paragraph([
        "起こりうる場合はいずれも ",
        math(String.raw`b\in K`),
        " を与えるので、",
        ref("def_order_convex_subset"),
        " の条件が成り立つ。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_remark_ca_specialization",
    kind: "remark",
    title: { text: "依存順序への特殊化" },
    labels: ["remark_dependency_order_tools_specialization"],
    habitat: "finite",
    statement: [paragraph([
      ref("claim_reachability_partial_order"), " を用い、", ref("def_order_convex_subset"),
      " から ", ref("def_antichain"), " までの有限半順序の道具を ",
      math(String.raw`X:=E_\tau`), "、", math(String.raw`R:=\preceq_\tau`),
      " と特殊化する。以下の時刻切片と一段境界は、この特殊化に CA の時刻と一段依存を加えた対象である。",
    ])],
  },

  {
    id: "dependency_order_substructures_definition_time_slice",
    kind: "definition",
    title: { text: "時刻切片" },
    labels: ["def_time_slice"],
    habitat: "finite",
    statement: [
      paragraph([
        math(String.raw`t\in[0,\tau]_{\mathbb{N}}`),
        "（",
        ref("def_finite_index_interval"),
        "）に対し、集合",
      ]),
      displayMath(
        String.raw`E_\tau^{(t)}:=\bigl\{\,(s,v)\in E_\tau\ \bigm|\ s=t\,\bigr\}`,
      ),
      paragraph([
        "を時刻 ",
        math(String.raw`t`),
        " の",
        "時刻切片",
        "と呼ぶ（",
        math(String.raw`E_\tau`),
        " は ",
        ref("def_event_set"),
        "。等号は ",
        math(String.raw`\mathbb{N}`),
        " の元の等号）。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_claim_time_slice_antichain",
    kind: "claim",
    title: { text: "時刻切片は反鎖である" },
    labels: ["claim_time_slice_antichain"],
    habitat: "N",
    statement: [
      paragraph([
        "任意の ",
        math(String.raw`t\in[0,\tau]_{\mathbb{N}}`),
        " について、時刻切片 ",
        math(String.raw`E_\tau^{(t)}`),
        "（",
        ref("def_time_slice"),
        "）は反鎖（",
        ref("def_antichain"),
        "）である。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`a,b\in E_\tau^{(t)}`),
        "、",
        math(String.raw`a\neq b`),
        " とする。",
        ref("def_time_slice"),
        " より ",
        math(String.raw`a=(t,u)`),
        "、",
        math(String.raw`b=(t,v)`),
        " と成分を書ける（",
        math(String.raw`u,v\in V`),
        "）。",
      ]),
      paragraph([
        math(String.raw`(a,b)\in\ \preceq_\tau`),
        " と仮定して矛盾を導く。",
        ref("def_ca_reflexive_reachability"),
        " より ",
        math(String.raw`a=b`),
        " または ",
        math(String.raw`(a,b)\in C_\tau`),
        " である。前者は仮定 ",
        math(String.raw`a\neq b`),
        " に矛盾する。後者なら、",
        ref("def_ca_reachability"),
        " より ",
        math(String.raw`a`),
        " から ",
        math(String.raw`b`),
        " への依存経路が存在し、",
        ref("claim_path_time_strictly_increases"),
        " より ",
        math(String.raw`t<t`),
        " となるが、",
        math(String.raw`\mathbb{N}`),
        " の大小比較は非反射的（",
        math(String.raw`t<t`),
        " は成り立たない）なので矛盾である。よって ",
        math(String.raw`(a,b)\notin\ \preceq_\tau`),
        " である。",
      ]),
      paragraph([
        math(String.raw`a`),
        " と ",
        math(String.raw`b`),
        " を入れ替えて同じ論証を行うと ",
        math(String.raw`(b,a)\notin\ \preceq_\tau`),
        " である。よって ",
        ref("def_incomparability"),
        " より ",
        math(String.raw`(a,b)\in\ \perp_\tau`),
        " であり、",
        ref("def_antichain"),
        " の条件が成り立つ。比較はいずれも ",
        math(String.raw`\mathbb{N}`),
        " の元の間で行われ、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_definition_one_step_boundary",
    kind: "definition",
    title: { text: "一段境界" },
    labels: ["def_one_step_boundary"],
    habitat: "finite",
    statement: [
      paragraph([
        "部分集合 ",
        math(String.raw`K\subseteq E_\tau`),
        " に対し、集合",
      ]),
      displayMath(
        String.raw`\partial K:=\bigl\{\,a\in K\ \bigm|\ \exists\,b\in E_\tau\setminus K,\ (a,b)\in D_\tau\ \text{または}\ (b,a)\in D_\tau\,\bigr\}`,
      ),
      paragraph([
        "を ",
        math(String.raw`K`),
        " の",
        "一段境界",
        "と呼ぶ（",
        math(String.raw`D_\tau`),
        " は ",
        ref("def_one_step_dependency"),
        "）。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_claim_one_step_boundary_finite",
    kind: "claim",
    title: { text: "一段境界は有限である" },
    labels: ["claim_one_step_boundary_finite"],
    habitat: "finite",
    statement: [paragraph([
      ref("def_one_step_boundary"), " の一段境界 ", math(String.raw`\partial K`),
      " は有限集合である。",
    ])],
    proof: [paragraph([
      math(String.raw`\partial K\subseteq K`), " であり、", math(String.raw`K`),
      " は有限集合なのである。",
    ])],
  },

  {
    id: "dependency_order_substructures_claim_down_set_no_incoming_edge",
    kind: "claim",
    title: { text: "下方集合には外から入る一段依存が存在しない" },
    labels: ["claim_down_set_no_incoming_edge"],
    habitat: "finite",
    statement: [
      paragraph([
        "任意の下方集合 ",
        math(String.raw`J\subseteq E_\tau`),
        "（",
        ref("def_down_set"),
        "）について、",
        math(String.raw`a\in J`),
        "、",
        math(String.raw`b\in E_\tau\setminus J`),
        "、",
        math(String.raw`(b,a)\in D_\tau`),
        " を満たす組 ",
        math(String.raw`(a,b)`),
        " は存在しない（",
        math(String.raw`D_\tau`),
        " は ",
        ref("def_one_step_dependency"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`a\in J`),
        "、",
        math(String.raw`b\in E_\tau\setminus J`),
        "、",
        math(String.raw`(b,a)\in D_\tau`),
        " と仮定して矛盾を導く。",
        ref("claim_one_step_subset_reachability"),
        " より ",
        math(String.raw`(b,a)\in C_\tau`),
        " である。",
        ref("def_ca_reflexive_reachability"),
        " より ",
        math(String.raw`b\preceq_\tau a`),
        " である。",
        math(String.raw`a\in J`),
        " なので、",
        ref("def_down_set"),
        " より ",
        math(String.raw`b\in J`),
        " となるが、これは ",
        math(String.raw`b\in E_\tau\setminus J`),
        " に矛盾する。よって仮定した組は存在しない。",
      ]),
    ],
  },

  {
    id: "dependency_order_substructures_claim_down_set_boundary_outgoing",
    kind: "claim",
    title: { text: "下方集合の一段境界は外向きの一段依存だけで定まる" },
    labels: ["claim_down_set_boundary_outgoing"],
    habitat: "finite",
    statement: [
      paragraph([
        "任意の下方集合 ",
        math(String.raw`J\subseteq E_\tau`),
        "（",
        ref("def_down_set"),
        "）について、",
      ]),
      displayMath(
        String.raw`\partial J=\bigl\{\,a\in J\ \bigm|\ \exists\,b\in E_\tau\setminus J,\ (a,b)\in D_\tau\,\bigr\}`,
      ),
      paragraph([
        "が成り立つ（",
        math(String.raw`\partial J`),
        " は ",
        ref("def_one_step_boundary"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        "右辺の集合を ",
        math(String.raw`B`),
        " と書き、両方向の包含で示す。",
      ]),
      paragraph([
        math(String.raw`B\subseteq\partial J`),
        ": ",
        math(String.raw`a\in B`),
        " とすると、ある ",
        math(String.raw`b\in E_\tau\setminus J`),
        " について ",
        math(String.raw`(a,b)\in D_\tau`),
        " なので、",
        ref("def_one_step_boundary"),
        " の選言の前者が成り立ち ",
        math(String.raw`a\in\partial J`),
        " である。",
      ]),
      paragraph([
        math(String.raw`\partial J\subseteq B`),
        ": ",
        math(String.raw`a\in\partial J`),
        " とすると、",
        ref("def_one_step_boundary"),
        " より、ある ",
        math(String.raw`b\in E_\tau\setminus J`),
        " について ",
        math(String.raw`(a,b)\in D_\tau`),
        " または ",
        math(String.raw`(b,a)\in D_\tau`),
        " である。後者は ",
        ref("claim_down_set_no_incoming_edge"),
        " より起こらない。よって前者が成り立ち、",
        math(String.raw`a\in B`),
        " である。",
      ]),
    ],
  },
]);
