/**
 * 章「本質的依存台」: 局所真理値表（有限集合 S 上の 2 値関数）が、S のどの元に
 * 本質的に依存するかを定義し、それが一点反転の有限検査と同値であること、
 * したがって真理値表から有限回の比較で決定できることを示す。
 *
 * 物理的な意味（因果・光円錐など）はここへ持ち込まない。舞台・状態集合・真理値表という
 * 有限データから内在的に定義できる対象だけを扱う（docs/マニフェスト.md）。
 * 用語は docs/2値セルオートマトンの定義と呼び名.md に従う。近傍 N(v) は順序のない
 * 有限集合なので、「座標」ではなく「S の元」と呼ぶ。
 *
 * どの章にも ℝ/ℂ は現れない。文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "essential_dependency_definition_cardinality_notation",
    kind: "definition",
    title: { text: "有限集合の元の個数の記法" },
    labels: ["def_cardinality_notation"],
    habitat: "N",
    statement: [
      paragraph([
        "有限集合 ",
        math(String.raw`X`),
        " に対し ",
        math(String.raw`|X|`),
        " でその元の個数（",
        math(String.raw`\mathbb{N}`),
        " の元）を表す。この記法をこれ以外の意味（絶対値・ノルム）では使わない。",
      ]),
    ],
  },

  {
    id: "essential_dependency_definition_state_set",
    kind: "definition",
    title: { text: "状態集合" },
    labels: ["def_state_set"],
    habitat: "finite",
    statement: [
      paragraph([
        math(String.raw`A:=\{0,1\}`),
        " と置く。",
        math(String.raw`A`),
        " は 2 元集合であり、加法・乗法・順序などの構造は入れない",
        "（構造を入れるときは名前に付ける、という呼び名の規約に従う）。",
      ]),
    ],
  },

  {
    id: "essential_dependency_definition_local_truth_table",
    kind: "definition",
    title: { text: "局所真理値表" },
    labels: ["def_local_truth_table"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限集合 ",
        math(String.raw`S`),
        " と写像 ",
        math(String.raw`f:A^S\to A`),
        " の組 ",
        math(String.raw`(S,f)`),
        " を",
        "局所真理値表",
        "と呼ぶ。ここで ",
        math(String.raw`A^S:=\{x\mid x:S\to A\}`),
        "（",
        math(String.raw`S`),
        " から ",
        math(String.raw`A`),
        " への写像全体。",
        math(String.raw`A`),
        " は ",
        ref("def_state_set"),
        "）であり、",
        math(String.raw`|A^S|=2^{|S|}\in\mathbb{N}`),
        "（有限集合の間の写像の個数。",
        math(String.raw`|X|`),
        " は ",
        ref("def_cardinality_notation"),
        "）なので ",
        math(String.raw`A^S`),
        " は有限集合、",
        math(String.raw`f`),
        " は有限データである。",
      ]),
      paragraph([
        "2 値セルオートマトンの各セル ",
        math(String.raw`v`),
        " の局所規則 ",
        math(String.raw`f_v:A^{N(v)}\to A`),
        " は、",
        math(String.raw`S=N(v)`),
        "（順序のない有限集合）と取った局所真理値表である。",
        "以下の議論は ",
        math(String.raw`S`),
        " の順序・番号付けを一切使わないので、最小の定義（構造を仮定しない 2 値セルオートマトン）の",
        "まま適用できる。",
      ]),
    ],
  },

  {
    id: "essential_dependency_definition_negation_map",
    kind: "definition",
    title: { text: "2 元集合の入れ替え写像" },
    labels: ["def_negation_map"],
    habitat: "finite",
    statement: [
      paragraph([
        "写像 ",
        math(String.raw`\nu:A\to A`),
        " を ",
        math(String.raw`\nu(0):=1`),
        "、",
        math(String.raw`\nu(1):=0`),
        " で定める（",
        math(String.raw`A`),
        " は ",
        ref("def_state_set"),
        "）。",
        math(String.raw`A`),
        " に代数構造を入れずに済ませるため、",
        math(String.raw`1-x`),
        " のような演算では書かず、値の場合分けで定義する。",
        "各 ",
        math(String.raw`a\in A`),
        " について ",
        math(String.raw`A\setminus\{a\}=\{\nu(a)\}`),
        " が成り立つ（",
        math(String.raw`a=0,1`),
        " の 2 通りを定義に代入して確かめられる）。",
      ]),
    ],
  },

  {
    id: "essential_dependency_definition_flip_map",
    kind: "definition",
    title: { text: "一点反転写像" },
    labels: ["def_flip_map"],
    habitat: "finite",
    statement: [
      paragraph([
        "局所真理値表 ",
        math(String.raw`(S,f)`),
        "（",
        ref("def_local_truth_table"),
        "）と ",
        math(String.raw`w\in S`),
        " に対し、写像 ",
        math(String.raw`\varphi_w:A^S\to A^S`),
        " を",
      ]),
      displayMath(String.raw`(\varphi_w x)(u):=\begin{cases}
\nu\bigl(x(w)\bigr) & (u=w)\\
x(u) & (u\in S\setminus\{w\})
\end{cases}\qquad(x\in A^S,\ u\in S)`),
      paragraph([
        "で定める（",
        math(String.raw`\nu`),
        " は ",
        ref("def_negation_map"),
        "）。",
        math(String.raw`\varphi_w x`),
        " を、",
        math(String.raw`x`),
        " の ",
        math(String.raw`w`),
        " での値だけを入れ替えた入力と呼ぶ。",
      ]),
    ],
  },

  {
    id: "essential_dependency_definition_essential_dependency",
    kind: "definition",
    title: { text: "本質的依存" },
    labels: ["def_essential_dependency"],
    habitat: "finite",
    statement: [
      paragraph([
        "局所真理値表 ",
        math(String.raw`(S,f)`),
        "（",
        ref("def_local_truth_table"),
        "）が ",
        math(String.raw`w\in S`),
        " に",
        "本質的に依存する",
        "とは、",
      ]),
      displayMath(
        String.raw`\exists\,x,x'\in A^S:\ \Bigl(\forall\,u\in S\setminus\{w\}:\ x(u)=x'(u)\Bigr)\ \text{かつ}\ f(x)\neq f(x')`,
      ),
      paragraph([
        "が成り立つことをいう。すなわち、",
        math(String.raw`w`),
        " 以外のすべての元で一致する 2 つの入力であって、",
        math(String.raw`f`),
        " の値が異なるものが存在することである。等号・不等号はいずれも有限集合 ",
        math(String.raw`A`),
        " の元の比較である。",
      ]),
    ],
  },

  {
    id: "essential_dependency_definition_support",
    kind: "definition",
    title: { text: "本質的依存台" },
    labels: ["def_essential_dependency_support"],
    habitat: "finite",
    statement: [
      paragraph([
        "局所真理値表 ",
        math(String.raw`(S,f)`),
        " に対し、",
      ]),
      displayMath(
        String.raw`\operatorname{supp}(f):=\{\,w\in S\mid f\ \text{が}\ w\ \text{に本質的に依存する}\,\}\subseteq S`,
      ),
      paragraph([
        "を ",
        math(String.raw`f`),
        " の",
        "本質的依存台",
        "と呼ぶ（本質的依存は ",
        ref("def_essential_dependency"),
        "）。",
        math(String.raw`S`),
        " が有限集合なので ",
        math(String.raw`\operatorname{supp}(f)`),
        " も有限集合である。",
      ]),
    ],
  },

  {
    id: "essential_dependency_claim_flip_test_equivalence",
    kind: "claim",
    title: { text: "本質的依存は一点反転の検査と同値である" },
    labels: ["claim_flip_test_equivalence"],
    habitat: "finite",
    verification: ["sagemath/check/essential-dependency-support"],
    statement: [
      paragraph([
        "局所真理値表 ",
        math(String.raw`(S,f)`),
        "（",
        ref("def_local_truth_table"),
        "）と ",
        math(String.raw`w\in S`),
        " について、次の 2 条件は同値である。",
      ]),
      displayMath(
        String.raw`f\ \text{が}\ w\ \text{に本質的に依存する}\iff\exists\,x\in A^S:\ f(x)\neq f(\varphi_w x)`,
      ),
      paragraph([
        "（本質的依存は ",
        ref("def_essential_dependency"),
        "、",
        math(String.raw`\varphi_w`),
        " は ",
        ref("def_flip_map"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`(\Leftarrow)`),
        "　",
        math(String.raw`f(x)\neq f(\varphi_w x)`),
        " を満たす ",
        math(String.raw`x\in A^S`),
        " を取り、",
        math(String.raw`x':=\varphi_w x`),
        " と置く。",
        ref("def_flip_map"),
        " の場合分けの下段より、すべての ",
        math(String.raw`u\in S\setminus\{w\}`),
        " で ",
        math(String.raw`x'(u)=(\varphi_w x)(u)=x(u)`),
        " であり、仮定より ",
        math(String.raw`f(x)\neq f(x')`),
        " である。よって ",
        ref("def_essential_dependency"),
        " の存在文を ",
        math(String.raw`(x,x')`),
        " が満たす。",
      ]),
      paragraph([
        math(String.raw`(\Rightarrow)`),
        "　",
        ref("def_essential_dependency"),
        " の存在文を満たす ",
        math(String.raw`x,x'\in A^S`),
        " を取る。すなわち、すべての ",
        math(String.raw`u\in S\setminus\{w\}`),
        " で ",
        math(String.raw`x(u)=x'(u)`),
        " かつ ",
        math(String.raw`f(x)\neq f(x')`),
        " である。まず ",
        math(String.raw`x(w)\neq x'(w)`),
        " を示す。仮に ",
        math(String.raw`x(w)=x'(w)`),
        " とすると、すべての ",
        math(String.raw`u\in S`),
        " で ",
        math(String.raw`x(u)=x'(u)`),
        "（",
        math(String.raw`u=w`),
        " の場合が仮定、",
        math(String.raw`u\neq w`),
        " の場合が上の一致）となり、写像の外延性より ",
        math(String.raw`x=x'`),
        "、したがって ",
        math(String.raw`f(x)=f(x')`),
        " となって ",
        math(String.raw`f(x)\neq f(x')`),
        " に矛盾する。ゆえに ",
        math(String.raw`x(w)\neq x'(w)`),
        "、すなわち ",
        math(String.raw`x'(w)\in A\setminus\{x(w)\}`),
        " である。",
      ]),
      paragraph([
        ref("def_negation_map"),
        " より ",
        math(String.raw`A\setminus\{x(w)\}=\{\nu(x(w))\}`),
        " なので ",
        math(String.raw`x'(w)=\nu(x(w))`),
        " である。したがって、すべての ",
        math(String.raw`u\in S`),
        " で",
      ]),
      displayMath(String.raw`x'(u)=\begin{cases}
\nu\bigl(x(w)\bigr) & (u=w)\\
x(u) & (u\in S\setminus\{w\})
\end{cases}
=(\varphi_w x)(u)\qquad(\because\ \blkref{def_flip_map})`),
      paragraph([
        "であり、写像の外延性より ",
        math(String.raw`x'=\varphi_w x`),
        " である。ゆえに ",
        math(String.raw`f(x)\neq f(x')=f(\varphi_w x)`),
        " となり、右辺の存在文を ",
        math(String.raw`x`),
        " が満たす。",
      ]),
      paragraph([
        "以上は有限集合の元の比較と写像の値の計算だけからなり、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "essential_dependency_claim_finite_decidability",
    kind: "claim",
    title: { text: "本質的依存台は真理値表から有限回の比較で決定できる" },
    labels: ["claim_support_finite_decidability"],
    habitat: "finite",
    verification: [
      "sagemath/check/essential-dependency-support",
      "sagemath/check/elementary-ca-finite-calibration",
    ],
    statement: [
      paragraph([
        "局所真理値表 ",
        math(String.raw`(S,f)`),
        "（",
        ref("def_local_truth_table"),
        "）について、",
        math(String.raw`\operatorname{supp}(f)`),
        "（",
        ref("def_essential_dependency_support"),
        "）は、",
        math(String.raw`f`),
        " の真理値表の値の比較を高々 ",
        math(String.raw`|S|\cdot 2^{|S|}`),
        " 回（各比較は 2 元集合 ",
        math(String.raw`A`),
        " の元の等号検査）行うことで決定できる。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`w\in S`),
        " を固定する。",
        ref("claim_flip_test_equivalence"),
        " より、",
        math(String.raw`w\in\operatorname{supp}(f)`),
        " は",
      ]),
      displayMath(String.raw`\exists\,x\in A^S:\ f(x)\neq f(\varphi_w x)`),
      paragraph([
        "と同値である。",
        math(String.raw`|A^S|=2^{|S|}\in\mathbb{N}`),
        "（",
        ref("def_local_truth_table"),
        "）なので、この存在文は有限集合 ",
        math(String.raw`A^S`),
        " の元を走る有限個の条件の論理和であり、各条件 ",
        math(String.raw`f(x)\neq f(\varphi_w x)`),
        " は真理値表に書かれた 2 つの値（",
        math(String.raw`A`),
        " の元）の等号検査 1 回で判定できる。よって ",
        math(String.raw`w\in\operatorname{supp}(f)`),
        " は高々 ",
        math(String.raw`2^{|S|}`),
        " 回の比較で決定できる。",
      ]),
      paragraph([
        math(String.raw`w`),
        " は ",
        math(String.raw`|S|`),
        " 個の元を走るので、",
        math(String.raw`\operatorname{supp}(f)`),
        " 全体は高々 ",
        math(String.raw`|S|\cdot 2^{|S|}`),
        " 回の比較で決定できる。回数はいずれも ",
        math(String.raw`\mathbb{N}`),
        " の元であり、実数体も複素数体も現れない。",
      ]),
    ],
  },
]);
