/**
 * 章「有限伝播境界」: 有限近傍（各セルの本質的依存台が有限であること）だけから、
 * 一つのイベント (t,v) に到達可能なイベント（依存元）が、時刻ごとの伝播球の
 * 有限合併に含まれることを示す。依存経路に沿って時刻がちょうど 1 ずつ増えることを
 * 先に示し、経路の長さを時刻差で拘束することで、依存元の個数の上界を
 * 伝播球の個数の和として与える。
 *
 * 使う ℕ の構造は前二章と同じく大小比較・後者（+1）に、個数の和の比較を加えた
 * ものだけである。物理的な意味（因果・光円錐・時空など）はここへ持ち込まない。
 * ℝ/ℂ は現れない。文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "finite_propagation_boundary_claim_path_time_increment_exact",
    kind: "claim",
    title: { text: "依存経路に沿って時刻はちょうど 1 ずつ増える" },
    labels: ["claim_path_time_increment_exact"],
    verification: ["sagemath/check/finite-propagation-boundary"],
    habitat: "N",
    statement: [
      paragraph([
        "任意の依存経路 ",
        math(String.raw`(n,p)`),
        "（",
        ref("def_ca_dependency_path"),
        "）について、",
        math(String.raw`p(0)=(s,u)`),
        "、",
        math(String.raw`p(n)=(t,v)`),
        " と成分を書くと ",
        math(String.raw`t=s+n`),
        " が成り立つ（等号は ",
        math(String.raw`\mathbb{N}`),
        " の元の等号、",
        math(String.raw`+`),
        " は ",
        math(String.raw`\mathbb{N}`),
        " の加法）。これは ",
        ref("claim_path_time_strictly_increases"),
        " の不等式 ",
        math(String.raw`s<t`),
        " を等式へ精密化したものである。",
      ]),
    ],
    proof: [
      paragraph([
        "経路の長さ ",
        math(String.raw`n\geq1`),
        " についての数学的帰納法で示す。各イベント ",
        math(String.raw`p(i)\in E_\tau`),
        " の第 1 成分（時刻。",
        ref("def_event_set"),
        "）を ",
        math(String.raw`t_i\in\mathbb{N}`),
        " と書く。示すことは ",
        math(String.raw`t_n=t_0+n`),
        " である。",
      ]),
      paragraph([
        "基底（",
        math(String.raw`n=1`),
        "）: ",
        math(String.raw`\bigl(p(0),p(1)\bigr)\in D_\tau`),
        "（",
        ref("def_ca_dependency_path"),
        "）なので、",
        ref("def_one_step_dependency"),
        " の条件 ",
        math(String.raw`t=s+1`),
        " より ",
        math(String.raw`t_1=t_0+1`),
        " である。",
      ]),
      paragraph([
        "帰納段（",
        math(String.raw`n\geq2`),
        "）: 長さ ",
        math(String.raw`n-1`),
        " について主張が成り立つと仮定する。",
        math(String.raw`p`),
        " の ",
        math(String.raw`[0,n-1]_{\mathbb{N}}`),
        " への制限は長さ ",
        math(String.raw`n-1`),
        " の依存経路なので（",
        ref("claim_path_time_strictly_increases"),
        " の証明の帰納段と同じ確認）、帰納法の仮定より ",
        math(String.raw`t_{n-1}=t_0+(n-1)`),
        " である。また ",
        math(String.raw`\bigl(p(n-1),p(n)\bigr)\in D_\tau`),
        "（",
        ref("def_ca_dependency_path"),
        "）なので、",
        ref("def_one_step_dependency"),
        " の条件 ",
        math(String.raw`t=s+1`),
        " より ",
        math(String.raw`t_n=t_{n-1}+1`),
        " である。二つの等式を代入して",
      ]),
      displayMath(String.raw`\begin{aligned}
t_n&=t_{n-1}+1\qquad(\because\ \blkref{def_one_step_dependency}\ \text{の条件}\ t=s+1)\\
&=\bigl(t_0+(n-1)\bigr)+1\qquad(\because\ \text{帰納法の仮定})\\
&=t_0+n\qquad(\because\ \mathbb{N}\ \text{の加法の結合則と}\ (n-1)+1=n)
\end{aligned}`),
      paragraph([
        "計算はすべて ",
        math(String.raw`\mathbb{N}`),
        " の元の間で行われ、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "finite_propagation_boundary_definition_propagation_ball",
    kind: "definition",
    title: { text: "伝播球" },
    labels: ["def_propagation_ball"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）に対し、各 ",
        math(String.raw`v\in V`),
        " と ",
        math(String.raw`n\in\mathbb{N}`),
        "、",
        math(String.raw`n\geq1`),
        " に、",
        math(String.raw`V`),
        " の部分集合 ",
        math(String.raw`B_n(v)`),
        " を ",
        math(String.raw`n`),
        " についての再帰で定める:",
      ]),
      displayMath(
        String.raw`B_1(v):=\operatorname{supp}(f_v),\qquad B_{n+1}(v):=\bigcup_{u\in\operatorname{supp}(f_v)}B_n(u)`,
      ),
      paragraph([
        math(String.raw`B_n(v)`),
        " を ",
        math(String.raw`v`),
        " の深さ ",
        math(String.raw`n`),
        " の",
        "伝播球",
        "と呼ぶ（",
        math(String.raw`\operatorname{supp}`),
        " は ",
        ref("def_essential_dependency_support"),
        "。合併は ",
        math(String.raw`V`),
        " の部分集合の合併である）。再帰の各段は、有限集合 ",
        math(String.raw`\operatorname{supp}(f_v)`),
        " の元 ",
        math(String.raw`u`),
        " ごとに既に定まった ",
        math(String.raw`B_n(u)`),
        " を合併するだけなので、",
        math(String.raw`B_n(v)`),
        " はすべての ",
        math(String.raw`n\geq1`),
        "、",
        math(String.raw`v\in V`),
        " について定まる。",
      ]),
    ],
  },

  {
    id: "finite_propagation_boundary_claim_propagation_ball_finite",
    kind: "claim",
    title: { text: "伝播球は有限であり個数は再帰的に抑えられる" },
    labels: ["claim_propagation_ball_finite"],
    verification: ["sagemath/check/finite-propagation-boundary"],
    habitat: "N",
    statement: [
      paragraph([
        "各 ",
        math(String.raw`v\in V`),
        "、",
        math(String.raw`n\geq1`),
        " について、伝播球 ",
        math(String.raw`B_n(v)`),
        "（",
        ref("def_propagation_ball"),
        "）は有限集合であり、",
        math(String.raw`|B_1(v)|=|\operatorname{supp}(f_v)|`),
        " かつ",
      ]),
      displayMath(
        String.raw`|B_{n+1}(v)|\ \leq\ \sum_{u\in\operatorname{supp}(f_v)}|B_n(u)|`,
      ),
      paragraph([
        "が成り立つ（",
        math(String.raw`|X|`),
        " は ",
        ref("def_cardinality_notation"),
        "、和は ",
        math(String.raw`\mathbb{N}`),
        " の有限和、",
        math(String.raw`\leq`),
        " は ",
        math(String.raw`\mathbb{N}`),
        " の大小比較）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`n`),
        " についての数学的帰納法で有限性を示す。基底: ",
        math(String.raw`B_1(v)=\operatorname{supp}(f_v)`),
        "（",
        ref("def_propagation_ball"),
        "）は有限集合 ",
        math(String.raw`N(v)`),
        " の部分集合なので有限である（",
        ref("def_essential_dependency_support"),
        " より ",
        math(String.raw`\operatorname{supp}(f_v)\subseteq N(v)`),
        "、",
        math(String.raw`N(v)`),
        " の有限性は ",
        ref("def_finite_stage"),
        "）。個数の等式 ",
        math(String.raw`|B_1(v)|=|\operatorname{supp}(f_v)|`),
        " は定義の等号による。",
      ]),
      paragraph([
        "帰納段: すべての ",
        math(String.raw`u\in V`),
        " について ",
        math(String.raw`B_n(u)`),
        " が有限であると仮定する。",
        math(String.raw`B_{n+1}(v)`),
        " は有限集合 ",
        math(String.raw`\operatorname{supp}(f_v)`),
        " で添字づけられた有限集合の合併なので有限である（",
        ref("def_propagation_ball"),
        "。有限個の有限集合の合併は有限）。個数については、有限個の有限集合の合併の元の個数は個数の和以下である（和の法則。重複があれば真に小さい）ことより",
      ]),
      displayMath(
        String.raw`|B_{n+1}(v)|=\Bigl|\bigcup_{u\in\operatorname{supp}(f_v)}B_n(u)\Bigr|\ \leq\ \sum_{u\in\operatorname{supp}(f_v)}|B_n(u)|`,
      ),
      paragraph([
        "が成り立つ。個数と和はいずれも ",
        math(String.raw`\mathbb{N}`),
        " の元であり、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "finite_propagation_boundary_claim_start_cell_in_ball",
    kind: "claim",
    title: { text: "依存経路の始点セルは伝播球に属する" },
    labels: ["claim_start_cell_in_propagation_ball"],
    verification: ["sagemath/check/finite-propagation-boundary"],
    habitat: "finite",
    statement: [
      paragraph([
        "任意の依存経路 ",
        math(String.raw`(n,p)`),
        "（",
        ref("def_ca_dependency_path"),
        "）について、",
        math(String.raw`p(0)=(s,u)`),
        "、",
        math(String.raw`p(n)=(t,v)`),
        " と成分を書くと ",
        math(String.raw`u\in B_n(v)`),
        " が成り立つ（",
        math(String.raw`B_n(v)`),
        " は ",
        ref("def_propagation_ball"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        "「長さ ",
        math(String.raw`n`),
        " のすべての依存経路について、終点のセルを ",
        math(String.raw`v`),
        "、始点のセルを ",
        math(String.raw`u`),
        " と書くと ",
        math(String.raw`u\in B_n(v)`),
        "」を、",
        math(String.raw`n\geq1`),
        " についての数学的帰納法で示す。",
      ]),
      paragraph([
        "基底（",
        math(String.raw`n=1`),
        "）: ",
        math(String.raw`\bigl(p(0),p(1)\bigr)=\bigl((s,u),(t,v)\bigr)\in D_\tau`),
        "（",
        ref("def_ca_dependency_path"),
        "）なので、",
        ref("def_one_step_dependency"),
        " の条件より ",
        math(String.raw`u\in\operatorname{supp}(f_v)`),
        " である。",
        ref("def_propagation_ball"),
        " より ",
        math(String.raw`B_1(v)=\operatorname{supp}(f_v)`),
        " なので ",
        math(String.raw`u\in B_1(v)`),
        " である。",
      ]),
      paragraph([
        "帰納段（",
        math(String.raw`n\geq2`),
        "）: 長さ ",
        math(String.raw`n-1`),
        " について主張が成り立つと仮定する。",
        math(String.raw`p(n-1)=(t',w)`),
        " と成分を書く。",
        math(String.raw`\bigl(p(n-1),p(n)\bigr)\in D_\tau`),
        "（",
        ref("def_ca_dependency_path"),
        "）なので、",
        ref("def_one_step_dependency"),
        " の条件より ",
        math(String.raw`w\in\operatorname{supp}(f_v)`),
        " である。",
        math(String.raw`p`),
        " の ",
        math(String.raw`[0,n-1]_{\mathbb{N}}`),
        " への制限は、",
        math(String.raw`p(0)=(s,u)`),
        " から ",
        math(String.raw`p(n-1)=(t',w)`),
        " への長さ ",
        math(String.raw`n-1`),
        " の依存経路なので（",
        ref("claim_path_time_strictly_increases"),
        " の証明の帰納段と同じ確認）、帰納法の仮定より ",
        math(String.raw`u\in B_{n-1}(w)`),
        " である。",
        ref("def_propagation_ball"),
        " より ",
        math(String.raw`B_n(v)=\bigcup_{u'\in\operatorname{supp}(f_v)}B_{n-1}(u')`),
        " であり、",
        math(String.raw`w\in\operatorname{supp}(f_v)`),
        " なので ",
        math(String.raw`B_{n-1}(w)\subseteq B_n(v)`),
        "（合併は各被合併集合を含む）である。よって ",
        math(String.raw`u\in B_n(v)`),
        " である。",
      ]),
      paragraph([
        "議論はすべて有限集合の所属と合併の中で行われ、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "finite_propagation_boundary_definition_dependency_source_set",
    kind: "definition",
    title: { text: "依存元集合" },
    labels: ["def_dependency_source_set"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）、",
        math(String.raw`\tau\in\mathbb{N}`),
        " とイベント ",
        math(String.raw`(t,v)\in E_\tau`),
        "（",
        ref("def_event_set"),
        "）に対し、集合",
      ]),
      displayMath(
        String.raw`P_\tau(t,v):=\bigl\{\,a\in E_\tau\ \bigm|\ \bigl(a,(t,v)\bigr)\in C_\tau\,\bigr\}`,
      ),
      paragraph([
        "を ",
        math(String.raw`(t,v)`),
        " の",
        "依存元集合",
        "と呼ぶ（",
        math(String.raw`C_\tau`),
        " は ", ref("def_ca_reachability"), "）。",
      ]),
    ],
  },

  {
    id: "finite_propagation_boundary_claim_dependency_source_set_finite",
    kind: "claim",
    title: { text: "依存元集合は有限である" },
    labels: ["claim_dependency_source_set_finite"],
    habitat: "finite",
    statement: [paragraph([
      ref("def_dependency_source_set"), " の集合 ", math(String.raw`P_\tau(t,v)`),
      " は有限集合である。",
    ])],
    proof: [paragraph([
      math(String.raw`P_\tau(t,v)\subseteq E_\tau`), "（", math(String.raw`\because`), " ",
      ref("def_dependency_source_set"), "）であり、", ref("claim_event_set_cardinality"),
      " より ", math(String.raw`E_\tau`), " は有限集合なのである。",
    ])],
  },

  {
    id: "finite_propagation_boundary_claim_finite_propagation_boundary",
    kind: "claim",
    title: { text: "依存元集合は伝播球の有限合併に含まれる" },
    labels: ["claim_finite_propagation_boundary"],
    verification: ["sagemath/check/finite-propagation-boundary"],
    habitat: "N",
    statement: [
      paragraph([
        "任意のイベント ",
        math(String.raw`(t,v)\in E_\tau`),
        " について、",
      ]),
      displayMath(
        String.raw`P_\tau(t,v)\ \subseteq\ \bigcup_{n\in[1,t]_{\mathbb{N}}}\bigl(\{t-n\}\times B_n(v)\bigr)`,
      ),
      paragraph([
        "が成り立つ（",
        math(String.raw`P_\tau(t,v)`),
        " は ",
        ref("def_dependency_source_set"),
        "、",
        math(String.raw`B_n(v)`),
        " は ",
        ref("def_propagation_ball"),
        "、",
        math(String.raw`[1,t]_{\mathbb{N}}:=\{n\in\mathbb{N}\mid 1\leq n\leq t\}`),
        "、",
        math(String.raw`t-n`),
        " は ",
        math(String.raw`n\leq t`),
        " の下での ",
        math(String.raw`\mathbb{N}`),
        " の減法）。したがって",
      ]),
      displayMath(
        String.raw`|P_\tau(t,v)|\ \leq\ \sum_{n\in[1,t]_{\mathbb{N}}}|B_n(v)|`,
      ),
      paragraph([
        "であり、特に ",
        math(String.raw`t=0`),
        " のとき ",
        math(String.raw`[1,0]_{\mathbb{N}}`),
        " は空なので ",
        math(String.raw`P_\tau(0,v)=\emptyset`),
        " である。右辺の上界は時刻ごとの伝播球の個数だけで書かれ、舞台全体の大きさ ",
        math(String.raw`|V|`),
        " にも ",
        math(String.raw`\tau`),
        " にも依存しない。",
      ]),
    ],
    proof: [
      paragraph([
        "包含を示す。",
        math(String.raw`a=(s,u)\in P_\tau(t,v)`),
        " とする。",
        ref("def_dependency_source_set"),
        " より ",
        math(String.raw`\bigl(a,(t,v)\bigr)\in C_\tau`),
        " なので、",
        ref("def_ca_reachability"),
        " より ",
        math(String.raw`a`),
        " から ",
        math(String.raw`(t,v)`),
        " への長さ ",
        math(String.raw`n`),
        " の依存経路が存在する。",
        ref("claim_path_time_increment_exact"),
        " より ",
        math(String.raw`t=s+n`),
        " である。",
        math(String.raw`s\in\mathbb{N}`),
        " より ",
        math(String.raw`s\geq0`),
        " なので ",
        math(String.raw`n\leq t`),
        " であり、依存経路の定義（",
        ref("def_ca_dependency_path"),
        "）より ",
        math(String.raw`n\geq1`),
        " なので ",
        math(String.raw`n\in[1,t]_{\mathbb{N}}`),
        " である。",
        math(String.raw`t=s+n`),
        " を ",
        math(String.raw`s`),
        " について解くと ",
        math(String.raw`s=t-n`),
        "（",
        math(String.raw`n\leq t`),
        " の下での ",
        math(String.raw`\mathbb{N}`),
        " の減法）である。また ",
        ref("claim_start_cell_in_propagation_ball"),
        " より ",
        math(String.raw`u\in B_n(v)`),
        " である。よって ",
        math(String.raw`a=(t-n,u)\in\{t-n\}\times B_n(v)`),
        " であり、",
        math(String.raw`a`),
        " は右辺の合併に属する。",
      ]),
      paragraph(["個数の上界は次の比較で得られる。"]),
      displayMath(String.raw`\begin{aligned}
|P_\tau(t,v)|
&\leq\Bigl|\bigcup_{n\in[1,t]_{\mathbb{N}}}\bigl(\{t-n\}\times B_n(v)\bigr)\Bigr|\qquad(\because\ \text{部分集合の個数は全体の個数以下。上の包含})\\
&\leq\sum_{n\in[1,t]_{\mathbb{N}}}\bigl|\{t-n\}\times B_n(v)\bigr|\qquad(\because\ \text{有限個の有限集合の合併の個数は個数の和以下})\\
&=\sum_{n\in[1,t]_{\mathbb{N}}}|B_n(v)|\qquad(\because\ \text{一元集合との直積の個数は個数に等しい（積の法則）})
\end{aligned}`),
      paragraph([
        math(String.raw`t=0`),
        " のときは ",
        math(String.raw`[1,0]_{\mathbb{N}}=\emptyset`),
        " なので合併は空集合であり、上の包含より ",
        math(String.raw`P_\tau(0,v)\subseteq\emptyset`),
        "、すなわち ",
        math(String.raw`P_\tau(0,v)=\emptyset`),
        " である。個数と和はいずれも ",
        math(String.raw`\mathbb{N}`),
        " の元であり、実数体も複素数体も現れない。",
      ]),
    ],
  },
]);
