/**
 * 章「逆写像の局所性」: 章「大域写像の可逆性の有限決定」の remark が残した問い
 * 「単射な大域写像の逆写像は再び局所規則から定まるか」を扱う。
 *
 * - 単射な大域写像 F : A^V → A^V の逆写像 F^{-1} と、その各セルの値写像 (F^{-1})_v : A^V → A を定義する
 * - (F^{-1})_v の本質的依存台は、章「本質的依存台の有限決定」の走査で有限決定できる
 * - 反例: 5 セルの舞台と一様な局所真理値表（初等 CA 規則 45）で F は単射だが、
 *   全てのセル v について supp((F^{-1})_v) は近傍 N(v) に収まらない
 *
 * 肯定命題「逆写像は順写像と同じ近傍の局所規則から定まる」は偽であり、反例を主張として保存する。
 * 舞台の族にわたる依存台の非有界性は観察に留め、主張しない。
 * 全て有限集合の等号だけを使い、ℝ/ℂ は現れない。文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "inverse_map_locality_heading",
    kind: "heading",
    level: 1,
    title: { text: "逆写像の局所性" },
    labels: [],
  },

  {
    id: "inverse_map_locality_definition_inverse_map",
    kind: "definition",
    title: { text: "単射な大域写像の逆写像" },
    labels: ["def_inverse_global_map"],
    habitat: "finite",
    statement: [
      paragraph([
        "大域写像 ",
        math(String.raw`F:A^{V}\to A^{V}`),
        "（",
        ref("def_global_map"),
        "）が単射（",
        ref("def_finite_self_map_injective_surjective"),
        "）であるとする。このとき ",
        ref("claim_finite_self_map_injective_iff_surjective"),
        " より ",
        math(String.raw`F`),
        " は全射であり、各 ",
        math(String.raw`z\in A^{V}`),
        " について ",
        math(String.raw`F\,y=z`),
        " を満たす ",
        math(String.raw`y\in A^{V}`),
        " が存在し（全射性）、かつ一意である（単射性）。この一意な ",
        math(String.raw`y`),
        " を ",
        math(String.raw`F^{-1}(z)`),
        " と書き、写像 ",
        math(String.raw`F^{-1}:A^{V}\to A^{V}`),
        " を",
        "逆写像",
        "と呼ぶ。定義より全ての ",
        math(String.raw`z\in A^{V}`),
        " について ",
        math(String.raw`F(F^{-1}(z))=z`),
        "、全ての ",
        math(String.raw`y\in A^{V}`),
        " について ",
        math(String.raw`F^{-1}(F\,y)=y`),
        "（",
        math(String.raw`F\,y=F\,y`),
        " を満たす元の一意性）が成り立つ。",
      ]),
    ],
  },

  {
    id: "inverse_map_locality_definition_inverse_cell_map_support",
    kind: "definition",
    title: { text: "逆写像の各セルの値写像とその本質的依存台" },
    labels: ["def_inverse_cell_map_support"],
    habitat: "finite",
    statement: [
      paragraph([
        "単射な大域写像 ",
        math(String.raw`F`),
        " と ",
        math(String.raw`v\in V`),
        " について、写像",
      ]),
      displayMath(
        String.raw`(F^{-1})_{v}:A^{V}\to A,\qquad (F^{-1})_{v}(z):=\bigl(F^{-1}(z)\bigr)(v)`,
      ),
      paragraph([
        "を逆写像の ",
        math(String.raw`v`),
        " での値写像と呼ぶ（",
        math(String.raw`F^{-1}`),
        " は ",
        ref("def_inverse_global_map"),
        "）。組 ",
        math(String.raw`(V,(F^{-1})_{v})`),
        " は局所真理値表（",
        ref("def_local_truth_table"),
        "、",
        math(String.raw`S=V`),
        "）であるから、その本質的依存台 ",
        math(String.raw`\operatorname{supp}\bigl((F^{-1})_{v}\bigr)\subseteq V`),
        " が ",
        ref("def_essential_dependency_support"),
        " により定まる。同じく組 ",
        math(String.raw`(V,\ f_{v}\circ\rho^{V}_{N(v)})`),
        " の本質的依存台 ",
        math(String.raw`\operatorname{supp}\bigl(f_{v}\circ\rho^{V}_{N(v)}\bigr)\subseteq V`),
        " を順写像の ",
        math(String.raw`v`),
        " での本質的依存台と呼ぶ（",
        ref("claim_global_flip_characterization"),
        " より、これは ",
        math(String.raw`u\in\operatorname{supp}(f_{v})`),
        " なる ",
        math(String.raw`u\in V`),
        " の集合に等しい）。",
      ]),
    ],
  },

  {
    id: "inverse_map_locality_claim_inverse_support_finite_decidability",
    kind: "claim",
    title: { text: "逆写像の本質的依存台は有限個の等号検査で決定できる" },
    labels: ["claim_inverse_support_finite_decidability"],
    habitat: "N",
    statement: [
      paragraph([
        "単射な大域写像 ",
        math(String.raw`F`),
        " と ",
        math(String.raw`v\in V`),
        " について、",
        math(String.raw`\operatorname{supp}\bigl((F^{-1})_{v}\bigr)`),
        " は、",
        math(String.raw`F^{-1}`),
        " の値の表（",
        math(String.raw`2^{|V|}`),
        " 個の ",
        math(String.raw`z\in A^{V}`),
        " に対する ",
        math(String.raw`F^{-1}(z)`),
        "）が与えられれば、高々 ",
        math(String.raw`|V|\cdot 2^{|V|}`),
        " 回の ",
        math(String.raw`A`),
        " の元の等号検査で決定できる。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`(V,(F^{-1})_{v})`),
        " は局所真理値表である（",
        ref("def_inverse_cell_map_support"),
        "）。",
        ref("claim_support_finite_decidability"),
        " を局所真理値表 ",
        math(String.raw`(S,f)=(V,(F^{-1})_{v})`),
        " に適用すると、",
        math(String.raw`\operatorname{supp}\bigl((F^{-1})_{v}\bigr)`),
        " は高々 ",
        math(String.raw`|S|\cdot 2^{|S|}=|V|\cdot 2^{|V|}`),
        " 回の ",
        math(String.raw`A`),
        " の元の等号検査で決定できる。各検査で比較する値 ",
        math(String.raw`(F^{-1})_{v}(x)=\bigl(F^{-1}(x)\bigr)(v)`),
        " は、仮定した ",
        math(String.raw`F^{-1}`),
        " の値の表から読み取れる。",
      ]),
    ],
  },

  {
    id: "inverse_map_locality_claim_counterexample_rule45",
    kind: "claim",
    title: { text: "反例: 逆写像の本質的依存台が近傍に収まらない単射な大域写像" },
    labels: ["claim_inverse_support_not_in_neighborhood_counterexample"],
    habitat: "finite",
    statement: [
      paragraph([
        "次の有限舞台と局所真理値表を取る。",
        math(String.raw`V:=\{0,1,2,3,4\}`),
        "（5 元集合。整数の演算・剰余類は使わない）。写像 ",
        math(String.raw`\ell,r:V\to V`),
        " を表",
      ]),
      displayMath(
        String.raw`\begin{array}{c|ccccc} v & 0&1&2&3&4\\ \hline \ell(v) & 4&0&1&2&3\\ r(v) & 1&2&3&4&0 \end{array}`,
      ),
      paragraph([
        "で定め、近傍を ",
        math(String.raw`N(v):=\{\ell(v),v,r(v)\}`),
        " とする（",
        ref("def_finite_stage"),
        "）。写像 ",
        math(String.raw`g:A\times A\times A\to A`),
        " を表",
      ]),
      displayMath(
        String.raw`\begin{array}{c|cccccccc} (a,b,c) & 000&001&010&011&100&101&110&111\\ \hline g(a,b,c) & 1&0&1&1&0&1&0&0 \end{array}`,
      ),
      paragraph([
        "で定め、各 ",
        math(String.raw`v\in V`),
        " の局所真理値表を ",
        math(String.raw`f_{v}:A^{N(v)}\to A`),
        "、",
        math(String.raw`f_{v}(x):=g\bigl(x(\ell(v)),x(v),x(r(v))\bigr)`),
        " とする（",
        ref("def_finite_ca"),
        "）。以下、配位 ",
        math(String.raw`y\in A^{V}`),
        " を 5 文字の列 ",
        math(String.raw`y(0)\,y(1)\,y(2)\,y(3)\,y(4)`),
        " で書く。このとき、",
      ]),
      paragraph([
        "(1) 大域写像 ",
        math(String.raw`F`),
        "（",
        ref("def_global_map"),
        "）は単射である。",
      ]),
      paragraph([
        "(2) 全ての ",
        math(String.raw`v\in V`),
        " について ",
        math(String.raw`V\setminus N(v)\subseteq\operatorname{supp}\bigl((F^{-1})_{v}\bigr)`),
        "。特に ",
        math(String.raw`\operatorname{supp}\bigl((F^{-1})_{v}\bigr)\not\subseteq N(v)`),
        " であり、",
        math(String.raw`\operatorname{supp}\bigl((F^{-1})_{v}\bigr)\not\subseteq\operatorname{supp}\bigl(f_{v}\circ\rho^{V}_{N(v)}\bigr)`),
        " である（後者は ",
        math(String.raw`N(v)`),
        " の部分集合だから）。",
      ]),
      paragraph([
        "したがって「単射な大域写像の逆写像の各セルの値は、順写像と同じ近傍 ",
        math(String.raw`N(v)`),
        " 上の値だけで定まる」は一般には成り立たない。",
      ]),
    ],
    proof: [
      paragraph([
        "(1) ",
        math(String.raw`A^{V}`),
        " の 32 個の配位 ",
        math(String.raw`y`),
        " と ",
        math(String.raw`F\,y`),
        "（各 ",
        math(String.raw`v`),
        " について ",
        math(String.raw`(F\,y)(v)=g(y(\ell(v)),y(v),y(r(v)))`),
        "、",
        math(String.raw`\because`),
        " ",
        ref("def_global_map"),
        " と ",
        math(String.raw`f_{v}`),
        " の定義）を全て書き下すと次の表になる（左が ",
        math(String.raw`y`),
        "、右が ",
        math(String.raw`F\,y`),
        "）。",
      ]),
      displayMath(
        String.raw`\begin{array}{cc|cc|cc|cc}
00000 & 11111 & 01000 & 01011 & 10000 & 10110 & 11000 & 10010 \\
00001 & 01101 & 01001 & 11001 & 10001 & 00101 & 11001 & 00001 \\
00010 & 11010 & 01010 & 01110 & 10010 & 10011 & 11010 & 10111 \\
00011 & 01010 & 01011 & 11110 & 10011 & 00010 & 11011 & 00110 \\
00100 & 10101 & 01100 & 01001 & 10100 & 11100 & 11100 & 10000 \\
00101 & 00111 & 01101 & 11011 & 10101 & 01111 & 11101 & 00011 \\
00110 & 10100 & 01110 & 01000 & 10110 & 11101 & 11110 & 10001 \\
00111 & 00100 & 01111 & 11000 & 10111 & 01100 & 11111 & 00000
\end{array}`,
      ),
      paragraph([
        "右列に現れる 32 個の配位は互いに相異なる（有限個の 5 文字列の等号検査）。よって ",
        math(String.raw`F\,y=F\,y'`),
        " ならば表の同じ行であり ",
        math(String.raw`y=y'`),
        "。すなわち ",
        math(String.raw`F`),
        " は単射である（",
        ref("def_finite_self_map_injective_surjective"),
        "）。",
      ]),
      paragraph([
        "(2) ",
        math(String.raw`F`),
        " は単射なので ",
        math(String.raw`F^{-1}`),
        " が定まり（",
        ref("def_inverse_global_map"),
        "）、上の表を右から左へ読めば ",
        math(String.raw`F^{-1}`),
        " の値の表になる。",
        ref("claim_flip_test_equivalence"),
        " を局所真理値表 ",
        math(String.raw`(V,(F^{-1})_{v})`),
        " に適用すると、",
        math(String.raw`u\in\operatorname{supp}((F^{-1})_{v})`),
        " は「ある ",
        math(String.raw`z\in A^{V}`),
        " について ",
        math(String.raw`(F^{-1}(z))(v)\neq(F^{-1}(\varphi_{u}z))(v)`),
        "」と同値である（",
        math(String.raw`\varphi_{u}`),
        " は ",
        ref("def_flip_map"),
        "）。各 ",
        math(String.raw`v\in V`),
        " と各 ",
        math(String.raw`u\in V\setminus N(v)`),
        "（各 ",
        math(String.raw`v`),
        " につき 2 個、計 10 組）について、その証人 ",
        math(String.raw`z`),
        " と、表から読んだ ",
        math(String.raw`F^{-1}(z)`),
        "・",
        math(String.raw`F^{-1}(\varphi_{u}z)`),
        " を次に挙げる。",
      ]),
      displayMath(
        String.raw`\begin{array}{cc|cc|cc}
v & u & z & F^{-1}(z) & \varphi_{u}z & F^{-1}(\varphi_{u}z) \\ \hline
0 & 2 & 00000 & 11111 & 00100 & 00111 \\
0 & 3 & 00100 & 00111 & 00110 & 11011 \\
1 & 3 & 00000 & 11111 & 00010 & 10011 \\
1 & 4 & 00010 & 10011 & 00011 & 11101 \\
2 & 0 & 00001 & 11001 & 10001 & 11110 \\
2 & 4 & 00000 & 11111 & 00001 & 11001 \\
3 & 0 & 00000 & 11111 & 10000 & 11100 \\
3 & 1 & 10000 & 11100 & 11000 & 01111 \\
4 & 1 & 00000 & 11111 & 01000 & 01110 \\
4 & 2 & 01000 & 01110 & 01100 & 10111
\end{array}`,
      ),
      paragraph([
        "各行で ",
        math(String.raw`\varphi_{u}z`),
        " は ",
        math(String.raw`z`),
        " の ",
        math(String.raw`u`),
        " の位置の値だけを入れ替えたものであり（",
        ref("def_flip_map"),
        "）、",
        math(String.raw`F^{-1}(z)`),
        " と ",
        math(String.raw`F^{-1}(\varphi_{u}z)`),
        " の ",
        math(String.raw`v`),
        " の位置の値は異なる（",
        math(String.raw`A`),
        " の元の等号検査。例えば 1 行目は ",
        math(String.raw`(F^{-1}(00000))(0)=1\neq0=(F^{-1}(00100))(0)`),
        "）。よって各組 ",
        math(String.raw`(v,u)`),
        " で ",
        math(String.raw`u\in\operatorname{supp}((F^{-1})_{v})`),
        " が成り立ち、",
        math(String.raw`V\setminus N(v)\subseteq\operatorname{supp}((F^{-1})_{v})`),
        " である。",
        math(String.raw`V\setminus N(v)`),
        " は空でない（各 ",
        math(String.raw`v`),
        " で 2 元）ので ",
        math(String.raw`\operatorname{supp}((F^{-1})_{v})\not\subseteq N(v)`),
        "。",
        math(String.raw`\operatorname{supp}(f_{v}\circ\rho^{V}_{N(v)})\subseteq N(v)`),
        " は ",
        ref("claim_no_dependency_on_redundant_element"),
        "（",
        math(String.raw`N(v)\subseteq V`),
        " の冗長拡大は ",
        math(String.raw`V\setminus N(v)`),
        " の元に本質的に依存しない）による。",
      ]),
    ],
  },

  {
    id: "inverse_map_locality_remark_not_claimed",
    kind: "remark",
    title: { text: "本章で主張しないこと" },
    labels: ["remark_inverse_map_locality_not_claimed"],
    habitat: "finite",
    statement: [
      paragraph([
        "本章の反例は 5 セルの一つの舞台と一つの局所真理値表についての有限の主張である。",
        "SageMath 層の探索（巡回舞台のセル数 1 から 7、一様な初等 CA 規則 256 個の全数検査）では、",
        "上の例で ",
        math(String.raw`\operatorname{supp}((F^{-1})_{v})=V`),
        "（5 元全体）となること、および ",
        math(String.raw`\mathbb{F}_{2}`),
        " 上の和 ",
        math(String.raw`x_{\ell(v)}+x_{v}+x_{r(v)}`),
        " に相当する規則 150 で逆写像の依存台の元の個数がセル数 4, 5, 7 でそれぞれ 3, 3, 5 となることが",
        "観察されたが、「舞台の族にわたって逆写像の依存台の個数が有界でない」という一般の主張は",
        "本章では証明せず、主張しない。無限舞台、非一様な規則、および逆写像が別の（より大きい）近傍の",
        "局所規則から定まるか否かも主張しない。「可逆」「時間反転」「情報保存」といった名前は本章の主張には現れない。",
      ]),
    ],
  },
]);
