/**
 * 章「依存台による局所規則の表現」: 章「逆写像の局所性」の反例が残した問い
 * 「単射な大域写像の逆写像は、どの近傍を取れば 2 値セルオートマトンの大域写像として書けるか」を扱う。
 *
 * - 写像 g : A^V → A が部分集合 S ⊆ V 上の局所規則で表せる（g = h ∘ ρ^V_S となる h がある）ことを定義する
 * - 表せるなら supp(g) ⊆ S（前章の依存台不変性）、逆に supp(g) ⊆ S なら g = (g ∘ ι^V_S) ∘ ρ^V_S（有限帰納法）
 * - よって supp(g) は g を表せる添字集合の中で最小である
 * - 単射な大域写像 F の逆写像 F^{-1} が近傍 N' の 2 値 CA の大域写像として書けるための必要十分条件は
 *   全ての v で supp((F^{-1})_v) ⊆ N'(v) であり、最小の近傍は v ↦ supp((F^{-1})_v)。これは有限決定できる
 *
 * 全て有限集合の等号と有限集合上の帰納法だけを使い、ℝ/ℂ は現れない。文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "local_rule_representation_definition_representable",
    kind: "definition",
    title: { text: "部分集合上の局所規則による表現" },
    labels: ["def_local_rule_representable"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限集合 ",
        math(String.raw`V`),
        "、その部分集合 ",
        math(String.raw`S\subseteq V`),
        "、写像 ",
        math(String.raw`g:A^{V}\to A`),
        "（組 ",
        math(String.raw`(V,g)`),
        " は局所真理値表 ",
        ref("def_local_truth_table"),
        "）に対し、",
        math(String.raw`g`),
        " が ",
        math(String.raw`S`),
        " 上の局所規則で表せる",
        "とは、",
      ]),
      displayMath(
        String.raw`\exists\,h:A^{S}\to A:\ \forall\,y\in A^{V}:\ g(y)=h\bigl(\rho^{V}_{S}\,y\bigr)`,
      ),
      paragraph([
        "が成り立つことをいう（",
        math(String.raw`\rho^{V}_{S}`),
        " は ",
        ref("def_restriction_map"),
        "）。すなわち ",
        math(String.raw`g`),
        " が局所真理値表 ",
        math(String.raw`(S,h)`),
        " の ",
        math(String.raw`V`),
        " への冗長拡大 ",
        math(String.raw`h\circ\rho^{V}_{S}`),
        "（",
        ref("def_redundant_extension"),
        "）に等しいことである。",
        math(String.raw`A^{S}\to A`),
        " なる写像は有限個なので、この存在量化は有限個の等号検査で決定できる。",
      ]),
    ],
  },

  {
    id: "local_rule_representation_claim_representable_implies_support_subset",
    kind: "claim",
    title: { text: "局所規則で表せるなら本質的依存台はその添字集合に含まれる" },
    labels: ["claim_representable_implies_support_subset"],
    habitat: "finite",
    statement: [
      paragraph([
        math(String.raw`g:A^{V}\to A`),
        " が ",
        math(String.raw`S\subseteq V`),
        " 上の局所規則で表せる（",
        ref("def_local_rule_representable"),
        "）ならば ",
        math(String.raw`\operatorname{supp}(g)\subseteq S`),
        " である（",
        math(String.raw`\operatorname{supp}(g)\subseteq V`),
        " は ",
        ref("def_essential_dependency_support"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        "仮定より ",
        math(String.raw`h:A^{S}\to A`),
        " で ",
        math(String.raw`g=h\circ\rho^{V}_{S}`),
        "（写像の外延性）となるものを取る。",
      ]),
      displayMath(String.raw`\begin{aligned}
\operatorname{supp}(g)
&=\operatorname{supp}\bigl(h\circ\rho^{V}_{S}\bigr)\qquad(\because\ g=h\circ\rho^{V}_{S})\\
&=\operatorname{supp}(h)\qquad(\because\ \blkref{claim_support_invariance}\ \text{で}\ T=V)\\
&\subseteq S\qquad(\because\ \blkref{def_essential_dependency_support}\ \text{で}\ (S,h))
\end{aligned}`),
    ],
  },

  {
    id: "local_rule_representation_claim_support_subset_implies_representable",
    kind: "claim",
    title: { text: "本質的依存台が添字集合に含まれるなら基準値延長で局所規則が得られる" },
    labels: ["claim_support_subset_implies_representable"],
    habitat: "finite",
    statement: [
      paragraph([
        math(String.raw`g:A^{V}\to A`),
        " と ",
        math(String.raw`S\subseteq V`),
        " が ",
        math(String.raw`\operatorname{supp}(g)\subseteq S`),
        " を満たすならば、全ての ",
        math(String.raw`y\in A^{V}`),
        " について",
      ]),
      displayMath(
        String.raw`g(y)=\bigl(g\circ\iota^{V}_{S}\bigr)\bigl(\rho^{V}_{S}\,y\bigr)`,
      ),
      paragraph([
        "が成り立つ（",
        math(String.raw`\iota^{V}_{S}:A^{S}\to A^{V}`),
        " は ",
        ref("def_base_value_extension"),
        "）。特に ",
        math(String.raw`g`),
        " は ",
        math(String.raw`h:=g\circ\iota^{V}_{S}:A^{S}\to A`),
        " により ",
        math(String.raw`S`),
        " 上の局所規則で表せる（",
        ref("def_local_rule_representable"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        "各 ",
        math(String.raw`y\in A^{V}`),
        " に対し、有限集合 ",
        math(String.raw`D(y):=\{\,u\in V\setminus S\mid y(u)\neq 0\,\}\subseteq V\setminus S`),
        " を置く（",
        math(String.raw`0\in A`),
        " は ",
        ref("def_state_set"),
        " の元、",
        math(String.raw`\neq`),
        " は ",
        math(String.raw`A`),
        " の元の比較）。主張 ",
        math(String.raw`g(y)=g\bigl(\iota^{V}_{S}(\rho^{V}_{S}\,y)\bigr)`),
        " を、",
        math(String.raw`|D(y)|=k`),
        " についての ",
        math(String.raw`\mathbb{N}`),
        " 上の帰納法で示す。",
      ]),
      paragraph([
        "（底 ",
        math(String.raw`k=0`),
        "）",
        math(String.raw`D(y)=\varnothing`),
        " なので、全ての ",
        math(String.raw`u\in V\setminus S`),
        " で ",
        math(String.raw`y(u)=0`),
        " である。各 ",
        math(String.raw`u\in V`),
        " について",
      ]),
      displayMath(String.raw`\begin{aligned}
\bigl(\iota^{V}_{S}(\rho^{V}_{S}\,y)\bigr)(u)
&=\begin{cases}(\rho^{V}_{S}\,y)(u)&(u\in S)\\ 0&(u\in V\setminus S)\end{cases}
\qquad(\because\ \blkref{def_base_value_extension})\\
&=\begin{cases}y(u)&(u\in S)\\ 0&(u\in V\setminus S)\end{cases}
\qquad(\because\ \blkref{def_restriction_map})\\
&=y(u)\qquad(\because\ u\in V\setminus S\ \text{では}\ y(u)=0)
\end{aligned}`),
      paragraph([
        "であるから、写像の外延性より ",
        math(String.raw`\iota^{V}_{S}(\rho^{V}_{S}\,y)=y`),
        "、したがって ",
        math(String.raw`g(y)=g\bigl(\iota^{V}_{S}(\rho^{V}_{S}\,y)\bigr)`),
        " である。",
      ]),
      paragraph([
        "（帰納段）",
        math(String.raw`|D(y)|=k+1`),
        " とし、",
        math(String.raw`|D(y')|=k`),
        " なる全ての ",
        math(String.raw`y'\in A^{V}`),
        " で主張が成り立つと仮定する。",
        math(String.raw`D(y)\neq\varnothing`),
        " なので ",
        math(String.raw`w\in D(y)`),
        " を一つ取る。",
        math(String.raw`w\in V\setminus S`),
        " かつ ",
        math(String.raw`y(w)\neq 0`),
        " であり、",
        math(String.raw`A=\{0,1\}`),
        " より ",
        math(String.raw`y(w)=1`),
        "、",
        math(String.raw`\nu(y(w))=\nu(1)=0`),
        "（",
        ref("def_negation_map"),
        "）。局所真理値表 ",
        math(String.raw`(V,g)`),
        " の一点反転写像 ",
        math(String.raw`\varphi_w:A^{V}\to A^{V}`),
        "（",
        ref("def_flip_map"),
        "）で ",
        math(String.raw`y':=\varphi_w\,y`),
        " と置く。",
        math(String.raw`y'(w)=\nu(y(w))=0`),
        " と、",
        math(String.raw`u\in V\setminus\{w\}`),
        " で ",
        math(String.raw`y'(u)=y(u)`),
        " から、",
        math(String.raw`D(y')=D(y)\setminus\{w\}`),
        "、よって ",
        math(String.raw`|D(y')|=k`),
        " である。また ",
        math(String.raw`w\notin S`),
        " と ",
        math(String.raw`\operatorname{supp}(g)\subseteq S`),
        " より ",
        math(String.raw`w\notin\operatorname{supp}(g)`),
        "、すなわち ",
        math(String.raw`g`),
        " は ",
        math(String.raw`w`),
        " に本質的に依存しない（",
        ref("def_essential_dependency_support"),
        "）。",
        math(String.raw`y`),
        " と ",
        math(String.raw`y'`),
        " は ",
        math(String.raw`V\setminus\{w\}`),
        " 上で一致するので、",
        ref("def_essential_dependency"),
        " の否定から ",
        math(String.raw`g(y)=g(y')`),
        " である。さらに各 ",
        math(String.raw`u\in S`),
        " について ",
        math(String.raw`u\neq w`),
        "（",
        math(String.raw`w\notin S`),
        "）なので",
      ]),
      displayMath(String.raw`\begin{aligned}
(\rho^{V}_{S}\,y')(u)
&=y'(u)\qquad(\because\ \blkref{def_restriction_map})\\
&=y(u)\qquad(\because\ \blkref{def_flip_map}\ \text{の下段},\ u\neq w)\\
&=(\rho^{V}_{S}\,y)(u)\qquad(\because\ \blkref{def_restriction_map})
\end{aligned}`),
      paragraph([
        "であり、写像の外延性より ",
        math(String.raw`\rho^{V}_{S}\,y'=\rho^{V}_{S}\,y`),
        "。以上を合わせて",
      ]),
      displayMath(String.raw`\begin{aligned}
g(y)
&=g(y')\qquad(\because\ w\notin\operatorname{supp}(g),\ \blkref{def_essential_dependency})\\
&=g\bigl(\iota^{V}_{S}(\rho^{V}_{S}\,y')\bigr)\qquad(\because\ \text{帰納法の仮定},\ |D(y')|=k)\\
&=g\bigl(\iota^{V}_{S}(\rho^{V}_{S}\,y)\bigr)\qquad(\because\ \rho^{V}_{S}\,y'=\rho^{V}_{S}\,y)
\end{aligned}`),
      paragraph([
        "となり帰納段が成り立つ。",
        math(String.raw`|D(y)|\le|V\setminus S|`),
        " は有限なので、",
        math(String.raw`\mathbb{N}`),
        " 上の帰納法により全ての ",
        math(String.raw`y\in A^{V}`),
        " で主張が成り立つ。最後に ",
        math(String.raw`\bigl(g\circ\iota^{V}_{S}\bigr)(\rho^{V}_{S}\,y)=g\bigl(\iota^{V}_{S}(\rho^{V}_{S}\,y)\bigr)`),
        " は合成の定義である。",
      ]),
    ],
  },

  {
    id: "local_rule_representation_claim_support_is_minimum",
    kind: "claim",
    title: { text: "本質的依存台は局所規則で表せる添字集合の最小元である" },
    labels: ["claim_support_is_minimum_representing_set"],
    habitat: "finite",
    statement: [
      paragraph([
        math(String.raw`g:A^{V}\to A`),
        " と ",
        math(String.raw`S\subseteq V`),
        " について、",
        math(String.raw`g`),
        " が ",
        math(String.raw`S`),
        " 上の局所規則で表せる（",
        ref("def_local_rule_representable"),
        "）ことと ",
        math(String.raw`\operatorname{supp}(g)\subseteq S`),
        " は同値である。特に ",
        math(String.raw`g`),
        " は ",
        math(String.raw`\operatorname{supp}(g)`),
        " 上の局所規則で表せ、",
        math(String.raw`\operatorname{supp}(g)`),
        " は ",
        math(String.raw`g`),
        " を表せる ",
        math(String.raw`V`),
        " の部分集合全体の（包含に関する）最小元である。",
      ]),
    ],
    proof: [
      paragraph([
        "同値の（$\Rightarrow$）は ",
        ref("claim_representable_implies_support_subset"),
        "、（$\Leftarrow$）は ",
        ref("claim_support_subset_implies_representable"),
        " である。",
        math(String.raw`S=\operatorname{supp}(g)`),
        " は ",
        math(String.raw`\operatorname{supp}(g)\subseteq\operatorname{supp}(g)`),
        " を満たすので（$\Leftarrow$）により表せる。",
        math(String.raw`g`),
        " を表せる任意の ",
        math(String.raw`S`),
        " は（$\Rightarrow$）により ",
        math(String.raw`\operatorname{supp}(g)\subseteq S`),
        " を満たすので、",
        math(String.raw`\operatorname{supp}(g)`),
        " は最小元である。",
      ]),
    ],
  },

  {
    id: "local_rule_representation_claim_inverse_map_is_ca_iff",
    kind: "claim",
    title: { text: "逆写像が別の近傍の 2 値セルオートマトンになるための必要十分条件" },
    labels: ["claim_inverse_map_is_ca_iff_support_subset"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台 ",
        math(String.raw`(V,N)`),
        " 上の 2 値セルオートマトンの大域写像 ",
        math(String.raw`F`),
        "（",
        ref("def_global_map"),
        "）が単射であるとし、",
        math(String.raw`F^{-1}`),
        " をその逆写像（",
        ref("def_inverse_global_map"),
        "）、",
        math(String.raw`(F^{-1})_v`),
        " をその ",
        math(String.raw`v`),
        " での値写像（",
        ref("def_inverse_cell_map_support"),
        "）とする。写像 ",
        math(String.raw`N':V\to\mathcal{P}(V)`),
        "（",
        math(String.raw`(V,N')`),
        " は有限舞台 ",
        ref("def_finite_neighborhood_system"),
        "）について、次の二つは同値である。",
      ]),
      paragraph([
        "(1) 有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N'),(f'_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）で、その大域写像 ",
        math(String.raw`F'`),
        " が ",
        math(String.raw`F'=F^{-1}`),
        " を満たすものが存在する。",
      ]),
      paragraph([
        "(2) 全ての ",
        math(String.raw`v\in V`),
        " について ",
        math(String.raw`\operatorname{supp}\bigl((F^{-1})_v\bigr)\subseteq N'(v)`),
        "。",
      ]),
      paragraph([
        "さらに (2) が成り立つとき、(1) の局所規則として ",
        math(String.raw`f'_v:=(F^{-1})_v\circ\iota^{V}_{N'(v)}`),
        " が取れる。",
      ]),
    ],
    proof: [
      paragraph([
        "（(1)$\Rightarrow$(2)）",
        math(String.raw`F'=F^{-1}`),
        " なる ",
        math(String.raw`\bigl((V,N'),(f'_v)_{v\in V}\bigr)`),
        " を取る。各 ",
        math(String.raw`v\in V`),
        " と ",
        math(String.raw`z\in A^{V}`),
        " について",
      ]),
      displayMath(String.raw`\begin{aligned}
(F^{-1})_v(z)
&=\bigl(F^{-1}(z)\bigr)(v)\qquad(\because\ \blkref{def_inverse_cell_map_support})\\
&=(F'\,z)(v)\qquad(\because\ F'=F^{-1})\\
&=f'_v\bigl(\rho^{V}_{N'(v)}\,z\bigr)\qquad(\because\ \blkref{def_global_map})
\end{aligned}`),
      paragraph([
        "であるから、",
        math(String.raw`(F^{-1})_v`),
        " は ",
        math(String.raw`h:=f'_v`),
        " により ",
        math(String.raw`N'(v)`),
        " 上の局所規則で表せる（",
        ref("def_local_rule_representable"),
        "）。よって ",
        ref("claim_representable_implies_support_subset"),
        " より ",
        math(String.raw`\operatorname{supp}((F^{-1})_v)\subseteq N'(v)`),
        " である。",
      ]),
      paragraph([
        "（(2)$\Rightarrow$(1)）各 ",
        math(String.raw`v\in V`),
        " で ",
        math(String.raw`f'_v:=(F^{-1})_v\circ\iota^{V}_{N'(v)}:A^{N'(v)}\to A`),
        " と置き、",
        math(String.raw`\bigl((V,N'),(f'_v)_{v\in V}\bigr)`),
        " の大域写像を ",
        math(String.raw`F'`),
        " とする。各 ",
        math(String.raw`z\in A^{V}`),
        " と ",
        math(String.raw`v\in V`),
        " について",
      ]),
      displayMath(String.raw`\begin{aligned}
(F'\,z)(v)
&=f'_v\bigl(\rho^{V}_{N'(v)}\,z\bigr)\qquad(\because\ \blkref{def_global_map})\\
&=\bigl((F^{-1})_v\circ\iota^{V}_{N'(v)}\bigr)\bigl(\rho^{V}_{N'(v)}\,z\bigr)\qquad(\because\ f'_v\ \text{の定義})\\
&=(F^{-1})_v(z)\qquad(\because\ \blkref{claim_support_subset_implies_representable},\ \operatorname{supp}((F^{-1})_v)\subseteq N'(v))\\
&=\bigl(F^{-1}(z)\bigr)(v)\qquad(\because\ \blkref{def_inverse_cell_map_support})
\end{aligned}`),
      paragraph([
        "であるから、写像の外延性より ",
        math(String.raw`F'\,z=F^{-1}(z)`),
        "、再び外延性より ",
        math(String.raw`F'=F^{-1}`),
        " である。",
      ]),
    ],
  },

  {
    id: "local_rule_representation_claim_minimal_inverse_neighborhood",
    kind: "claim",
    title: { text: "逆写像の最小近傍は各セルの本質的依存台であり有限決定できる" },
    labels: ["claim_minimal_inverse_neighborhood_finite_decidability"],
    habitat: "N",
    statement: [
      paragraph([
        ref("claim_inverse_map_is_ca_iff_support_subset"),
        " の設定で、",
        math(String.raw`N^{\ast}(v):=\operatorname{supp}\bigl((F^{-1})_v\bigr)`),
        "（",
        math(String.raw`v\in V`),
        "）と置く。",
        math(String.raw`(V,N^{\ast})`),
        " は (1) を満たす有限舞台であり、(1) を満たす任意の ",
        math(String.raw`(V,N')`),
        " について全ての ",
        math(String.raw`v\in V`),
        " で ",
        math(String.raw`N^{\ast}(v)\subseteq N'(v)`),
        " である。さらに ",
        math(String.raw`N^{\ast}`),
        " は、各 ",
        math(String.raw`v\in V`),
        " について高々 ",
        math(String.raw`|V|\cdot 2^{|V|}`),
        " 回の ",
        math(String.raw`A`),
        " の元の等号検査で決定できる（",
        math(String.raw`|V|,\ 2^{|V|}\in\mathbb{N}`),
        "。個数は ",
        ref("def_cardinality_notation"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`N^{\ast}`),
        " は各 ",
        math(String.raw`v`),
        " で ",
        math(String.raw`\operatorname{supp}((F^{-1})_v)\subseteq N^{\ast}(v)`),
        " を満たすので、",
        ref("claim_inverse_map_is_ca_iff_support_subset"),
        " の (2)$\Rightarrow$(1) により (1) を満たす。",
        math(String.raw`(V,N')`),
        " が (1) を満たすなら、同 claim の (1)$\Rightarrow$(2) により全ての ",
        math(String.raw`v`),
        " で ",
        math(String.raw`N^{\ast}(v)=\operatorname{supp}((F^{-1})_v)\subseteq N'(v)`),
        " である。各 ",
        math(String.raw`v`),
        " での ",
        math(String.raw`\operatorname{supp}((F^{-1})_v)`),
        " の決定は ",
        ref("claim_inverse_support_finite_decidability"),
        " そのものであり、等号検査回数の上界 ",
        math(String.raw`|V|\cdot 2^{|V|}`),
        " もそこで示されている。",
      ]),
    ],
  },

  {
    id: "local_rule_representation_remark_scope",
    kind: "remark",
    title: { text: "この章で主張しないこと" },
    labels: ["remark_local_rule_representation_scope"],
    habitat: "finite",
    statement: [
      paragraph([
        "この章は、逆写像が「ある近傍の 2 値セルオートマトン」として書けることと、その最小近傍が有限決定できることだけを述べる。",
        "最小近傍 ",
        math(String.raw`N^{\ast}`),
        " が順写像の近傍 ",
        math(String.raw`N`),
        " から得られる量（例えば ",
        math(String.raw`N`),
        " の反復合成）で抑えられるかは主張しない。章「逆写像の局所性」の反例では全ての ",
        math(String.raw`v`),
        " で ",
        math(String.raw`N^{\ast}(v)\not\subseteq N(v)`),
        " であった。舞台の族にわたる ",
        math(String.raw`|N^{\ast}(v)|`),
        " の振る舞いも主張しない。",
      ]),
    ],
  },
]);
