/**
 * 章「周期点の個数」: 前章「最小前周期と最小周期」の続き。
 * 各 n ≥ 1 について n 回反復の不動点集合 Fix_n(F) と、その個数 Z_n(F) ∈ ℕ を定義し、
 * 周期点集合 Per(F) を Fix_n の和として定める。
 *
 * - y ∈ Per(F) ⟺ μ(y) = 0（最小前周期が 0）
 * - y ∈ Fix_n(F) ⟺ μ(y) = 0 かつ π(y) が n を割り切る（除法の原理と π(y) の最小性）
 * - Z_n(F) は最小周期ごとの個数の和へ分解される
 * - Fix_n(F) の所属は F^n y = y という 1 回の元の等号で決まり、Z_n(F) は |X| 回の等号検査で決まる
 *
 * 使う ℕ の構造は加法・乗法・大小比較・等号・除法の原理・整列性だけである。
 * 「分配関数」「トレース」等の統計力学・線形代数の名前は使わず、Z_n は個数としてだけ定義する。
 * ℝ/ℂ は現れない。文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "periodic_point_count_heading",
    kind: "heading",
    level: 1,
    title: { text: "周期点の個数" },
    labels: [],
  },

  {
    id: "periodic_point_count_definition_fixed_points_of_iterate",
    kind: "definition",
    title: { text: "反復の不動点集合とその個数" },
    labels: ["def_fixed_points_of_iterate"],
    habitat: "N",
    statement: [
      paragraph([
        "各 ",
        math(String.raw`n\in\mathbb{N}`),
        "、",
        math(String.raw`n\ge 1`),
        " に対し、",
      ]),
      displayMath(
        String.raw`\mathrm{Fix}_{n}(F):=\{\,y\in X\ :\ F^{n}\,y=y\,\},\qquad Z_{n}(F):=|\mathrm{Fix}_{n}(F)|\in\mathbb{N}`,
      ),
      paragraph([
        "と定める（",
        math(String.raw`F^{n}`),
        " は ",
        ref("def_global_map_iterate"),
        "）。", math(String.raw`Z_{n}(F)`), " はその元の個数である。",
      ]),
    ],
  },

  {
    id: "periodic_point_count_definition_periodic_points",
    kind: "definition",
    title: { text: "周期点集合" },
    labels: ["def_periodic_points"],
    habitat: "finite",
    statement: [
      paragraph(["集合"]),
      displayMath(
        String.raw`\mathrm{Per}(F):=\{\,y\in X\ :\ \exists n\in\mathbb{N}\,(\,n\ge 1\ \text{かつ}\ F^{n}\,y=y\,)\,\}`,
      ),
      paragraph([
        "を ",
        math(String.raw`F`),
        " の周期点集合と呼ぶ。定義により ",
        math(String.raw`y\in\mathrm{Per}(F)`),
        " ",
        math(String.raw`\iff`),
        " ある ",
        math(String.raw`n\ge 1`),
        " について ",
        math(String.raw`y\in\mathrm{Fix}_{n}(F)`),
        "（",
        ref("def_fixed_points_of_iterate"),
        "）。",
      ]),
    ],
  },

  {
    id: "periodic_point_count_claim_periodic_iff_min_preperiod_zero",
    kind: "claim",
    title: { text: "周期点であることは最小前周期が 0 であることと同値である" },
    labels: ["claim_periodic_iff_min_preperiod_zero"],
    habitat: "N",
    statement: [
      paragraph([
        "各 ",
        math(String.raw`y\in X`),
        " について、",
        math(String.raw`y\in\mathrm{Per}(F)`),
        " ",
        math(String.raw`\iff`),
        " ",
        math(String.raw`\mu(y)=0`),
        "（",
        math(String.raw`\mu`),
        " は ",
        ref("def_min_preperiod"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        "（",
        math(String.raw`\Rightarrow`),
        "）",
        math(String.raw`y\in\mathrm{Per}(F)`),
        " とし、",
        ref("def_periodic_points"),
        " により ",
        math(String.raw`n\ge 1`),
        "、",
        math(String.raw`F^{n}\,y=y`),
        " を取る。",
        math(String.raw`F^{0}\,y=y`),
        "（",
        ref("def_global_map_iterate"),
        "）なので ",
        math(String.raw`F^{0+n}\,y=F^{0}\,y`),
        "（",
        math(String.raw`0+n=n`),
        " は ",
        math(String.raw`\mathbb{N}`),
        " の加法の単位元）。",
        ref("claim_periodicity_pair_iff_collision"),
        " により ",
        math(String.raw`(0,n)\in P(y)`),
        "。よって ",
        math(String.raw`0\in I(y)`),
        " であり、",
        ref("def_min_preperiod"),
        " の最小性により ",
        math(String.raw`\mu(y)\le 0`),
        "。",
        math(String.raw`\mu(y)\in\mathbb{N}`),
        " なので ",
        math(String.raw`\mu(y)=0`),
        "。",
      ]),
      paragraph([
        "（",
        math(String.raw`\Leftarrow`),
        "）",
        math(String.raw`\mu(y)=0`),
        " とする。",
        ref("def_min_period"),
        " により ",
        math(String.raw`(\mu(y),\pi(y))=(0,\pi(y))\in P(y)`),
        "、",
        math(String.raw`\pi(y)\ge 1`),
        "。",
        ref("claim_periodicity_pair_iff_collision"),
        " により ",
        math(String.raw`F^{0+\pi(y)}\,y=F^{0}\,y`),
        "、すなわち ",
        math(String.raw`F^{\pi(y)}\,y=y`),
        "（",
        math(String.raw`0+\pi(y)=\pi(y)`),
        "、",
        math(String.raw`F^{0}\,y=y`),
        "）。",
        math(String.raw`n:=\pi(y)`),
        " が ",
        ref("def_periodic_points"),
        " の存在文の証人であり、",
        math(String.raw`y\in\mathrm{Per}(F)`),
        "。",
      ]),
    ],
  },

  {
    id: "periodic_point_count_claim_fixed_iff_min_period_divides",
    kind: "claim",
    title: { text: "反復の不動点であることは最小前周期が 0 で最小周期が回数を割り切ることと同値である" },
    labels: ["claim_fixed_iff_min_period_divides"],
    habitat: "N",
    statement: [
      paragraph([
        "各 ",
        math(String.raw`y\in X`),
        " と ",
        math(String.raw`n\in\mathbb{N}`),
        "、",
        math(String.raw`n\ge 1`),
        " について、",
        math(String.raw`y\in\mathrm{Fix}_{n}(F)`),
        " ",
        math(String.raw`\iff`),
        " （",
        math(String.raw`\mu(y)=0`),
        " かつ ある ",
        math(String.raw`k\in\mathbb{N}`),
        " について ",
        math(String.raw`n=k\,\pi(y)`),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        "（",
        math(String.raw`\Leftarrow`),
        "）",
        math(String.raw`\mu(y)=0`),
        "、",
        math(String.raw`n=k\,\pi(y)`),
        " とする。",
        ref("claim_periodic_iff_min_preperiod_zero"),
        " の証明の（",
        math(String.raw`\Leftarrow`),
        "）と同じく ",
        math(String.raw`F^{0+\pi(y)}\,y=F^{0}\,y`),
        "。",
      ]),
      displayMath(String.raw`\begin{aligned}
F^{n}\,y
&=F^{0+k\,\pi(y)}\,y\qquad(\because\ n=k\,\pi(y),\ 0+n=n)\\
&=F^{0}\,y\qquad(\because\ \blkref{claim_period_multiples}\ \text{を } i:=0,\ q:=\pi(y),\ k \text{ に適用})\\
&=y\qquad(\because\ \blkref{def_global_map_iterate})
\end{aligned}`),
      paragraph([
        "よって ",
        math(String.raw`y\in\mathrm{Fix}_{n}(F)`),
        "（",
        ref("def_fixed_points_of_iterate"),
        "）。",
      ]),
      paragraph([
        "（",
        math(String.raw`\Rightarrow`),
        "）",
        math(String.raw`y\in\mathrm{Fix}_{n}(F)`),
        " とする。",
        math(String.raw`n\ge 1`),
        " と ",
        math(String.raw`F^{n}\,y=y`),
        " から ",
        math(String.raw`y\in\mathrm{Per}(F)`),
        "（",
        ref("def_periodic_points"),
        "）、したがって ",
        ref("claim_periodic_iff_min_preperiod_zero"),
        " により ",
        math(String.raw`\mu(y)=0`),
        "。",
        math(String.raw`q:=\pi(y)\ge 1`),
        " と略記する。",
        math(String.raw`\mathbb{N}`),
        " の除法の原理により ",
        math(String.raw`k,r\in\mathbb{N}`),
        " で ",
        math(String.raw`n=k\,q+r`),
        "、",
        math(String.raw`r<q`),
        " を満たすものが取れる。",
        math(String.raw`r=0`),
        " を示せば ",
        math(String.raw`n=k\,q`),
        " である。",
        math(String.raw`r\ge 1`),
        " と仮定して矛盾を導く。",
      ]),
      displayMath(String.raw`\begin{aligned}
F^{r}\,y
&=F^{0+r}\,y\qquad(\because\ 0+r=r)\\
&=F^{k\,q+r}\,y\qquad(\because\ \blkref{claim_collision_shift}\ \text{を } F^{k\,q}y=F^{0}y\ (\text{上の }(\Leftarrow)\text{ の計算で } n:=kq) \text{ と } r \text{ に適用})\\
&=F^{n}\,y\qquad(\because\ n=k\,q+r)\\
&=y\qquad(\because\ y\in\mathrm{Fix}_{n}(F))
\end{aligned}`),
      paragraph([
        "よって ",
        math(String.raw`F^{0+r}\,y=F^{0}\,y`),
        " かつ ",
        math(String.raw`r\ge 1`),
        " なので、",
        ref("claim_periodicity_pair_iff_collision"),
        " により ",
        math(String.raw`(0,r)\in P(y)`),
        "。",
        math(String.raw`\mu(y)=0`),
        " なので ",
        ref("def_min_period"),
        " の最小性により ",
        math(String.raw`\pi(y)\le r`),
        "。これは ",
        math(String.raw`r<q=\pi(y)`),
        " と矛盾する（",
        math(String.raw`\mathbb{N}`),
        " の大小関係）。ゆえに ",
        math(String.raw`r=0`),
        "、",
        math(String.raw`n=k\,\pi(y)`),
        "。",
      ]),
    ],
  },

  {
    id: "periodic_point_count_claim_count_decomposition",
    kind: "claim",
    title: { text: "反復の不動点の個数は最小周期ごとの個数の和である" },
    labels: ["claim_fixed_point_count_decomposition"],
    habitat: "N",
    statement: [
      paragraph([
        "各 ",
        math(String.raw`d\in\mathbb{N}`),
        "、",
        math(String.raw`d\ge 1`),
        " に対し ",
        math(String.raw`C_{d}(F):=\{\,y\in X\ :\ \mu(y)=0\ \text{かつ}\ \pi(y)=d\,\}`),
        " と置く。各 ",
        math(String.raw`n\ge 1`),
        " について",
      ]),
      displayMath(
        String.raw`Z_{n}(F)=\sum_{d\in[1,n]_{\mathbb{N}},\ \exists k\in\mathbb{N}\,(n=k\,d)}|C_{d}(F)|`,
      ),
      paragraph([
        "。ここで和は ",
        math(String.raw`n`),
        " を割り切る ",
        math(String.raw`d\in[1,n]_{\mathbb{N}}`),
        " にわたる有限和である。",
      ]),
    ],
    proof: [
      paragraph([
        ref("claim_fixed_iff_min_period_divides"),
        " により、",
        math(String.raw`\mathrm{Fix}_{n}(F)`),
        " は ",
        math(String.raw`\mu(y)=0`),
        " かつ ",
        math(String.raw`\pi(y)`),
        " が ",
        math(String.raw`n`),
        " を割り切る ",
        math(String.raw`y`),
        " の全体である。",
        math(String.raw`n=k\,\pi(y)`),
        "、",
        math(String.raw`n\ge 1`),
        " なら ",
        math(String.raw`k\ge 1`),
        " であり、",
        math(String.raw`\pi(y)\le k\,\pi(y)=n`),
        "（",
        math(String.raw`\mathbb{N}`),
        " の乗法の単調性）なので ",
        math(String.raw`\pi(y)\in[1,n]_{\mathbb{N}}`),
        "。したがって",
      ]),
      displayMath(
        String.raw`\mathrm{Fix}_{n}(F)=\bigcup_{d\in[1,n]_{\mathbb{N}},\ \exists k\,(n=k\,d)}C_{d}(F)`,
      ),
      paragraph([
        "であり、",
        math(String.raw`d\neq d'`),
        " なら ",
        math(String.raw`C_{d}(F)\cap C_{d'}(F)=\emptyset`),
        "（",
        math(String.raw`\pi(y)`),
        " は ",
        ref("def_min_period"),
        " により ",
        math(String.raw`y`),
        " ごとに一意なので、同じ ",
        math(String.raw`y`),
        " が二つの ",
        math(String.raw`d`),
        " に属さない）。互いに素な有限個の有限集合の和の個数は個数の和である（有限集合の元の数え上げ）ので、",
        ref("def_fixed_points_of_iterate"),
        " により ",
        math(String.raw`Z_{n}(F)=\sum_{d}|C_{d}(F)|`),
        "。",
      ]),
    ],
  },

  {
    id: "periodic_point_count_claim_finite_decidability",
    kind: "claim",
    title: { text: "反復の不動点の個数は有限回の元の等号検査で決まる" },
    labels: ["claim_fixed_point_count_finite_decidability"],
    habitat: "N",
    statement: [
      paragraph([
        "各 ",
        math(String.raw`n\ge 1`),
        " について、",
        math(String.raw`y\in\mathrm{Fix}_{n}(F)`),
        " かどうかは元の等号 ",
        math(String.raw`F^{n}\,y=y`),
        " の 1 回の検査で決まり、",
        math(String.raw`Z_{n}(F)`),
        " は ",
        math(String.raw`|X|`),
        " 回の元の等号検査で決まる。",
      ]),
    ],
    proof: [
      paragraph([
        ref("def_fixed_points_of_iterate"),
        " により ",
        math(String.raw`y\in\mathrm{Fix}_{n}(F)`),
        " ",
        math(String.raw`\iff`),
        " ",
        math(String.raw`F^{n}\,y=y`),
        " であり、右辺は有限集合 ",
        math(String.raw`X`),
        " の二元の等号 1 回である（",
        math(String.raw`F^{n}\,y`),
        " は ",
        ref("def_global_map_iterate"),
        " の再帰で有限回の ",
        math(String.raw`F`),
        " の適用として計算される）。",
        math(String.raw`Z_{n}(F)`),
        " は ",
        math(String.raw`X`),
        " の全 ",
        math(String.raw`|X|`),
        " 元についてこの検査を行い、成り立った元を数えた個数である。",
      ]),
    ],
  },
]);
