/**
 * 章「自己写像の可逆性の有限決定」: 前章「周期点の個数」の続き。
 * 有限集合上の自己写像 F : X → X について、単射・全射・全元が周期点であることを定義し、
 * それらが互いに同値であること、および有限個の等号検査で決定できることを示す。
 *
 * - F が単射 ⟺ F が全射（像の個数の数え上げ。X が有限であることだけを使う）
 * - F が単射 ⟺ 全ての y ∈ X について μ(y) = 0（最小前周期の最小性と反復の帰納的定義）
 * - 単射性は |X| 個の元それぞれの最小前周期の有限決定に帰着する
 *
 * 「可逆」「時間反転」「情報保存」等の物理的名称は使わず、写像の単射・全射としてだけ述べる。
 * 使う ℕ の構造は加法・大小比較・等号・整列性だけである。ℝ/ℂ は現れない。
 * 文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "reversibility_finite_decidability_heading",
    kind: "heading",
    level: 1,
    title: { text: "自己写像の可逆性の有限決定" },
    labels: [],
  },

  {
    id: "reversibility_finite_decidability_definition_injective_surjective",
    kind: "definition",
    title: { text: "自己写像の単射性・全射性・像" },
    labels: ["def_finite_self_map_injective_surjective"],
    habitat: "finite",
    statement: [
      paragraph([
        "自己写像 ",
        math(String.raw`F:X\to X`),
        "（",
        ref("def_finite_self_map_iterate"),
        " の直前で固定したもの）について、",
      ]),
      displayMath(
        String.raw`\mathrm{Im}(F):=\{\,F\,y\ :\ y\in X\,\}\subseteq X`,
      ),
      paragraph([
        "を像と呼ぶ。",
        math(String.raw`F`),
        " が単射であるとは、全ての ",
        math(String.raw`y,y'\in X`),
        " について ",
        math(String.raw`F\,y=F\,y'\Rightarrow y=y'`),
        " が成り立つことをいう。",
        math(String.raw`F`),
        " が全射であるとは ",
        math(String.raw`\mathrm{Im}(F)=X`),
        " が成り立つことをいう。",
      ]),
    ],
  },

  {
    id: "reversibility_finite_decidability_claim_image_finite",
    kind: "claim",
    title: { text: "有限自己写像の像は有限集合である" },
    labels: ["claim_finite_self_map_image_finite"],
    habitat: "finite",
    statement: [
      paragraph([
        math(String.raw`\mathrm{Im}(F)`), " は有限集合であり、",
        math(String.raw`|\mathrm{Im}(F)|\in\mathbb N`), " が定まる。",
      ]),
    ],
    proof: [
      paragraph([
        ref("def_finite_self_map_injective_surjective"), " より ",
        math(String.raw`\mathrm{Im}(F)\subseteq X`), " である。",
        ref("def_finite_self_map"), " より ", math(String.raw`X`),
        " は有限集合なので、その部分集合 ", math(String.raw`\mathrm{Im}(F)`), " も有限集合である。",
      ]),
    ],
  },

  {
    id: "reversibility_finite_decidability_claim_injective_iff_surjective",
    kind: "claim",
    title: { text: "有限集合上では単射性と全射性は同値である" },
    labels: ["claim_finite_self_map_injective_iff_surjective"],
    habitat: "N",
    statement: [
      paragraph([
        math(String.raw`F`),
        " が単射である ",
        math(String.raw`\iff`),
        " ",
        math(String.raw`F`),
        " が全射である。",
      ]),
    ],
    proof: [
      paragraph([
        "まず、",
        math(String.raw`|\mathrm{Im}(F)|\le|X|`),
        " である（",
        math(String.raw`\mathrm{Im}(F)\subseteq X`),
        " と、有限集合の部分集合の元の個数は全体の元の個数以下であること）。",
        "また、",
        math(String.raw`|\mathrm{Im}(F)|=|X|`),
        " ならば ",
        math(String.raw`\mathrm{Im}(F)=X`),
        " である（有限集合 ",
        math(String.raw`X`),
        " の部分集合で元の個数が等しいものは全体に一致する）。逆に ",
        math(String.raw`\mathrm{Im}(F)=X`),
        " ならば ",
        math(String.raw`|\mathrm{Im}(F)|=|X|`),
        " である（等しい集合の元の個数は等しい）。",
      ]),
      paragraph([
        "（",
        math(String.raw`\Rightarrow`),
        "）",
        math(String.raw`F`),
        " が単射であるとする。写像 ",
        math(String.raw`y\mapsto F\,y`),
        " は ",
        math(String.raw`X`),
        " から ",
        math(String.raw`\mathrm{Im}(F)`),
        " への全射であり（",
        ref("def_finite_self_map_injective_surjective"),
        " の像の定義）、単射でもあるので、",
        math(String.raw`X`),
        " と ",
        math(String.raw`\mathrm{Im}(F)`),
        " の間の全単射である。よって ",
        math(String.raw`|\mathrm{Im}(F)|=|X|`),
        "（有限集合の間に全単射があれば元の個数が等しい）。前段により ",
        math(String.raw`\mathrm{Im}(F)=X`),
        "、すなわち ",
        math(String.raw`F`),
        " は全射である。",
      ]),
      paragraph([
        "（",
        math(String.raw`\Leftarrow`),
        "）",
        math(String.raw`F`),
        " が全射であるとし、",
        math(String.raw`F`),
        " が単射でないと仮定して矛盾を導く。単射でないので、",
        math(String.raw`y_{0}\neq y_{1}`),
        "、",
        math(String.raw`F\,y_{0}=F\,y_{1}`),
        " を満たす ",
        math(String.raw`y_{0},y_{1}\in X`),
        " が存在する（",
        ref("def_finite_self_map_injective_surjective"),
        " の単射の定義の否定）。",
        math(String.raw`B:=X\setminus\{y_{1}\}`),
        " とおくと ",
        math(String.raw`|B|=|X|-1`),
        "（有限集合から元を 1 個除いた集合の元の個数）。各 ",
        math(String.raw`y\in X`),
        " について、",
        math(String.raw`y\ne y_{1}`),
        " なら ",
        math(String.raw`y\in B`),
        " かつ ",
        math(String.raw`F\,y=F\,y`),
        "、",
        math(String.raw`y=y_{1}`),
        " なら ",
        math(String.raw`y_{0}\in B`),
        " かつ ",
        math(String.raw`F\,y=F\,y_{1}=F\,y_{0}`),
        "。よって ",
        math(String.raw`\mathrm{Im}(F)=\{\,F\,y\ :\ y\in B\,\}`),
        "（両包含。",
        math(String.raw`\supseteq`),
        " は ",
        math(String.raw`B\subseteq X`),
        " から）。",
        "写像 ",
        math(String.raw`B\to\mathrm{Im}(F)`),
        "、",
        math(String.raw`y\mapsto F\,y`),
        " は全射なので ",
        math(String.raw`|\mathrm{Im}(F)|\le|B|`),
        "（有限集合からの全射の終域の元の個数は始域の元の個数以下）。したがって ",
        math(String.raw`|\mathrm{Im}(F)|\le|X|-1<|X|`),
        "。一方、全射性により ",
        math(String.raw`|\mathrm{Im}(F)|=|X|`),
        "（前段）。",
        math(String.raw`|X|<|X|`),
        " となり ",
        math(String.raw`\mathbb{N}`),
        " の大小関係の非反射性に矛盾する。ゆえに ",
        math(String.raw`F`),
        " は単射である。",
      ]),
    ],
  },

  {
    id: "reversibility_finite_decidability_claim_injective_iff_all_periodic",
    kind: "claim",
    title: { text: "単射性は全ての元の最小前周期が 0 であることと同値である" },
    labels: ["claim_finite_self_map_injective_iff_all_periodic"],
    habitat: "N",
    statement: [
      paragraph([
        math(String.raw`F`),
        " が単射である ",
        math(String.raw`\iff`),
        " 全ての ",
        math(String.raw`y\in X`),
        " について ",
        math(String.raw`\mu(y)=0`),
        "（",
        math(String.raw`\mu`),
        " は ",
        ref("def_min_preperiod"),
        "）。",
        ref("claim_periodic_iff_min_preperiod_zero"),
        " により、右辺は ",
        math(String.raw`\mathrm{Per}(F)=X`),
        " と言い換えられる。",
      ]),
    ],
    proof: [
      paragraph([
        "（",
        math(String.raw`\Rightarrow`),
        "）",
        math(String.raw`F`),
        " を単射とし、",
        math(String.raw`y\in X`),
        " を任意に取る。",
        math(String.raw`\mu(y)\ge 1`),
        " と仮定して矛盾を導く。",
        ref("def_min_period"),
        " により ",
        math(String.raw`(\mu(y),\pi(y))\in P(y)`),
        "、",
        math(String.raw`\pi(y)\ge 1`),
        " であり、",
        ref("claim_periodicity_pair_iff_collision"),
        " により ",
        math(String.raw`F^{\mu(y)+\pi(y)}\,y=F^{\mu(y)}\,y`),
        "。",
        math(String.raw`\mu(y)\ge 1`),
        " なので ",
        math(String.raw`m:=\mu(y)-1\in\mathbb{N}`),
        " が定まり ",
        math(String.raw`\mu(y)=m+1`),
        "（",
        math(String.raw`\mathbb{N}`),
        " の減法）。",
        math(String.raw`\mu(y)+\pi(y)=(m+\pi(y))+1`),
        "（",
        math(String.raw`\mathbb{N}`),
        " の加法の結合性と可換性）。",
        ref("def_finite_self_map_iterate"),
        " により ",
        math(String.raw`F^{(m+\pi(y))+1}\,y=F\,(F^{m+\pi(y)}\,y)`),
        "、",
        math(String.raw`F^{m+1}\,y=F\,(F^{m}\,y)`),
        "。よって ",
        math(String.raw`F\,(F^{m+\pi(y)}\,y)=F\,(F^{m}\,y)`),
        "。",
        math(String.raw`F`),
        " の単射性（",
        ref("def_finite_self_map_injective_surjective"),
        "）により ",
        math(String.raw`F^{m+\pi(y)}\,y=F^{m}\,y`),
        "。",
        ref("claim_periodicity_pair_iff_collision"),
        " により ",
        math(String.raw`(m,\pi(y))\in P(y)`),
        "、よって ",
        math(String.raw`m\in I(y)`),
        "。",
        ref("def_min_preperiod"),
        " の最小性により ",
        math(String.raw`\mu(y)\le m=\mu(y)-1`),
        "、これは ",
        math(String.raw`\mathbb{N}`),
        " の大小関係に矛盾する。ゆえに ",
        math(String.raw`\mu(y)=0`),
        "。",
      ]),
      paragraph([
        "（",
        math(String.raw`\Leftarrow`),
        "）全ての ",
        math(String.raw`y\in X`),
        " について ",
        math(String.raw`\mu(y)=0`),
        " とする。",
        math(String.raw`F`),
        " が全射であることを示す。",
        math(String.raw`y\in X`),
        " を任意に取る。",
        ref("claim_periodic_iff_min_preperiod_zero"),
        " により ",
        math(String.raw`y\in\mathrm{Per}(F)`),
        " であり、",
        ref("def_periodic_points"),
        " により ",
        math(String.raw`n\ge 1`),
        "、",
        math(String.raw`F^{n}\,y=y`),
        " を満たす ",
        math(String.raw`n\in\mathbb{N}`),
        " が存在する。",
        math(String.raw`n\ge 1`),
        " なので ",
        math(String.raw`k:=n-1\in\mathbb{N}`),
        "、",
        math(String.raw`n=k+1`),
        "。",
        ref("def_finite_self_map_iterate"),
        " により ",
        math(String.raw`F^{k+1}\,y=F\,(F^{k}\,y)`),
        "。よって ",
        math(String.raw`y=F\,(F^{k}\,y)`),
        " であり、",
        math(String.raw`z:=F^{k}\,y\in X`),
        " が ",
        math(String.raw`y=F\,z`),
        " を満たすので ",
        math(String.raw`y\in\mathrm{Im}(F)`),
        "（",
        ref("def_finite_self_map_injective_surjective"),
        "）。",
        math(String.raw`y`),
        " は任意なので ",
        math(String.raw`X\subseteq\mathrm{Im}(F)`),
        "、",
        math(String.raw`\mathrm{Im}(F)\subseteq X`),
        " と合わせて ",
        math(String.raw`\mathrm{Im}(F)=X`),
        "、すなわち ",
        math(String.raw`F`),
        " は全射である。",
        ref("claim_finite_self_map_injective_iff_surjective"),
        " により ",
        math(String.raw`F`),
        " は単射である。",
      ]),
    ],
  },

  {
    id: "reversibility_finite_decidability_claim_finite_decidability",
    kind: "claim",
    title: { text: "単射性・全射性は有限個の等号検査で決定できる" },
    labels: ["claim_finite_self_map_injectivity_finite_decidability"],
    habitat: "N",
    statement: [
      paragraph([
        math(String.raw`F`),
        " が単射であるか否か（",
        ref("claim_finite_self_map_injective_iff_surjective"),
        " により、全射であるか否かと同じ）は、次のいずれの手続きでも有限回の元の等号検査で決定できる。",
      ]),
      paragraph([
        "（像の走査）",
        math(String.raw`X`),
        " の全ての元の対 ",
        math(String.raw`(y,y')`),
        "（",
        math(String.raw`|X|^{2}`),
        " 個）について ",
        math(String.raw`F\,y=F\,y'`),
        " と ",
        math(String.raw`y=y'`),
        " の等号を検査し、",
        math(String.raw`F\,y=F\,y'`),
        " かつ ",
        math(String.raw`y\ne y'`),
        " となる対が一つもないとき、かつそのときに限り単射である。",
      ]),
      paragraph([
        "（最小前周期の走査）",
        math(String.raw`X`),
        " の全ての元 ",
        math(String.raw`y`),
        "（",
        math(String.raw`|X|`),
        " 個）について ",
        math(String.raw`\mu(y)`),
        " を ",
        ref("claim_min_preperiod_period_finite_decidability"),
        " の有限走査で求め、全て ",
        math(String.raw`0`),
        " であるとき、かつそのときに限り単射である。",
      ]),
    ],
    proof: [
      paragraph([
        "（像の走査）",
        ref("def_finite_self_map_injective_surjective"),
        " の単射の定義は、",
        math(String.raw`X\times X`),
        " 上の全称文「",
        math(String.raw`F\,y=F\,y'\Rightarrow y=y'`),
        "」である。",
        math(String.raw`X\times X`),
        " は有限集合（元の個数 ",
        math(String.raw`|X|^{2}`),
        "、",
        "）なので、この全称文は有限個の含意の連言であり、各含意は 2 回の元の等号検査で決まる。",
        "「反例となる対が存在しない」ことは、この全称文の言い換えである。",
      ]),
      paragraph([
        "（最小前周期の走査）",
        ref("claim_finite_self_map_injective_iff_all_periodic"),
        " により、単射性は ",
        math(String.raw`X`),
        " 上の全称文「",
        math(String.raw`\mu(y)=0`),
        "」と同値である。",
        math(String.raw`X`),
        " は有限集合なので、この全称文は ",
        math(String.raw`|X|`),
        " 個の等号 ",
        math(String.raw`\mu(y)=0`),
        " の連言であり、各 ",
        math(String.raw`\mu(y)`),
        " は ",
        ref("claim_min_preperiod_period_finite_decidability"),
        " により有限回の元の等号検査で定まる。",
      ]),
    ],
  },

  {
    id: "reversibility_finite_decidability_remark_not_claimed",
    kind: "remark",
    title: { text: "本章で主張しないこと" },
    labels: ["remark_reversibility_not_claimed"],
    habitat: "finite",
    statement: [
      paragraph([
        "本章は有限集合 ", math(String.raw`X`),
        " 上の自己写像だけを扱う。無限集合上での単射性と全射性の関係、",
        "および単射性を自己写像の有限表から ", math(String.raw`|X|`),
        " 個の元を走査せずに判定できるか否かは、主張しない。",
        "「可逆」「時間反転」「情報保存」といった名前は本章の主張には現れない。",
      ]),
    ],
  },

  {
    id: "reversibility_finite_decidability_remark_ca_inverse_locality",
    kind: "remark",
    title: { text: "二値セルオートマトンへの特殊化で主張しないこと" },
    labels: ["remark_reversibility_ca_inverse_locality_not_claimed"],
    habitat: "finite",
    statement: [
      paragraph([
        "二値セルオートマトンへの特殊化では、逆写像 ", math(String.raw`F^{-1}`),
        " が同じ局所実現制限の下で大域写像になるか否かを、この章の有限自己写像論だけからは主張しない。",
      ]),
    ],
  },
]);
