/**
 * 章「時間展開上の直接依存」: 有限舞台の 2 値セルオートマトンと有限時間区間から、
 * イベント（時刻とセルの組）の有限集合と、一段の直接依存関係を定義する。
 *
 * 依存関係の定義には近傍 N(v) そのものではなく本質的依存台 supp(f_v) を使う。
 * その正当化は前二章から従う: 大域写像の値 (Fy)(v) が u での一点反転で変わりうることと
 * u ∈ supp(f_v) が同値である（本章の claim）。冗長な近傍の元は依存関係に現れない。
 *
 * 物理的な意味（因果・光円錐・時空など）はここへ持ち込まない。時間は ℕ の元による
 * 番号付けであり、順序と後者（+1）以外の構造は使わない。どの章にも ℝ/ℂ は現れない。
 * 文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "finite_layered_relation_definition_finite_stage",
    kind: "definition",
    title: { text: "有限舞台" },
    labels: ["def_finite_stage"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限集合 ",
        math(String.raw`V`),
        " と、各 ",
        math(String.raw`v\in V`),
        " に部分集合 ",
        math(String.raw`N(v)\subseteq V`),
        " を対応させる写像 ",
        math(String.raw`N`),
        " の組 ",
        math(String.raw`(V,N)`),
        " を",
        "有限舞台",
        "と呼ぶ。",
        math(String.raw`N(v)`),
        " を ",
        math(String.raw`v`),
        " の",
        "近傍",
        "と呼ぶ。",
        math(String.raw`N(v)`),
        " は順序のない集合であり、番号付け・グラフ構造・群構造は仮定しない。",
      ]),
    ],
  },

  {
    id: "time_expansion_dependency_definition_finite_ca",
    kind: "definition",
    title: { text: "有限舞台上の 2 値セルオートマトン" },
    labels: ["def_finite_ca"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台 ",
        math(String.raw`(V,N)`),
        "（",
        ref("def_finite_stage"),
        "）と、各 ",
        math(String.raw`v\in V`),
        " に与えた写像 ",
        math(String.raw`f_v:A^{N(v)}\to A`),
        " の族 ",
        math(String.raw`(f_v)_{v\in V}`),
        " の組 ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        " を",
        "有限舞台上の 2 値セルオートマトン",
        "と呼ぶ。各組 ",
        math(String.raw`(N(v),f_v)`),
        " は局所真理値表（",
        ref("def_local_truth_table"),
        "）である。",
      ]),
    ],
  },

  {
    id: "time_expansion_dependency_definition_global_map",
    kind: "definition",
    title: { text: "大域写像" },
    labels: ["def_global_map"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）に対し、写像 ",
        math(String.raw`F:A^{V}\to A^{V}`),
        " を",
      ]),
      displayMath(
        String.raw`(F\,y)(v):=f_v\bigl(\rho^{V}_{N(v)}\,y\bigr)\qquad(y\in A^{V},\ v\in V)`,
      ),
      paragraph([
        "で定め、",
        "大域写像",
        "と呼ぶ（",
        math(String.raw`\rho^{V}_{N(v)}:A^{V}\to A^{N(v)}`),
        " は ",
        math(String.raw`T=V`),
        "、",
        math(String.raw`S=N(v)`),
        " と取った制限写像 ",
        ref("def_restriction_map"),
        "。",
        math(String.raw`N(v)\subseteq V`),
        " は ",
        ref("def_finite_stage"),
        " による）。各 ",
        math(String.raw`v\in V`),
        " について、写像 ",
        math(String.raw`y\mapsto(F\,y)(v)`),
        " は冗長拡大 ",
        math(String.raw`f_v\circ\rho^{V}_{N(v)}:A^{V}\to A`),
        "（",
        ref("def_redundant_extension"),
        " で ",
        math(String.raw`T=V`),
        "、",
        math(String.raw`S=N(v)`),
        " と取ったもの）に等しい。すなわち組 ",
        math(String.raw`(V,\ f_v\circ\rho^{V}_{N(v)})`),
        " は ",
        math(String.raw`V`),
        " を添字集合とする局所真理値表である。",
      ]),
    ],
  },

  {
    id: "time_expansion_dependency_claim_global_flip_characterization",
    kind: "claim",
    title: { text: "大域写像の一点反転による変化は本質的依存台で特徴づけられる" },
    labels: ["claim_global_flip_characterization"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）と ",
        math(String.raw`u,v\in V`),
        " について、次の 2 条件は同値である。",
      ]),
      displayMath(
        String.raw`\exists\,y\in A^{V}:\ (F\,y)(v)\neq\bigl(F(\varphi_u\,y)\bigr)(v)\iff u\in\operatorname{supp}(f_v)`,
      ),
      paragraph([
        "（",
        math(String.raw`F`),
        " は ",
        ref("def_global_map"),
        "、",
        math(String.raw`\varphi_u`),
        " は局所真理値表 ",
        math(String.raw`(V,\ f_v\circ\rho^{V}_{N(v)})`),
        " に対する一点反転写像 ",
        ref("def_flip_map"),
        "、",
        math(String.raw`\operatorname{supp}`),
        " は ",
        ref("def_essential_dependency_support"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        "各 ",
        math(String.raw`y\in A^{V}`),
        " について",
      ]),
      displayMath(String.raw`(F\,y)(v)=\bigl(f_v\circ\rho^{V}_{N(v)}\bigr)(y)\qquad(\because\ \blkref{def_global_map})`),
      displayMath(String.raw`\bigl(F(\varphi_u\,y)\bigr)(v)=\bigl(f_v\circ\rho^{V}_{N(v)}\bigr)(\varphi_u\,y)\qquad(\because\ \blkref{def_global_map})`),
      paragraph([
        "である。したがって左辺の条件は",
      ]),
      displayMath(
        String.raw`\exists\,y\in A^{V}:\ \bigl(f_v\circ\rho^{V}_{N(v)}\bigr)(y)\neq\bigl(f_v\circ\rho^{V}_{N(v)}\bigr)(\varphi_u\,y)`,
      ),
      paragraph([
        "と同値である。",
        ref("claim_flip_test_equivalence"),
        " を局所真理値表 ",
        math(String.raw`(V,\ f_v\circ\rho^{V}_{N(v)})`),
        "（",
        ref("def_global_map"),
        " の後段）と ",
        math(String.raw`u\in V`),
        " に適用すると、この条件は ",
        math(String.raw`f_v\circ\rho^{V}_{N(v)}`),
        " が ",
        math(String.raw`u`),
        " に本質的に依存することと同値であり、",
        ref("def_essential_dependency_support"),
        " よりそれは ",
        math(String.raw`u\in\operatorname{supp}\bigl(f_v\circ\rho^{V}_{N(v)}\bigr)`),
        " と同値である。",
        ref("claim_support_invariance"),
        " を ",
        math(String.raw`S=N(v)`),
        "、",
        math(String.raw`T=V`),
        " に適用すると ",
        math(String.raw`\operatorname{supp}\bigl(f_v\circ\rho^{V}_{N(v)}\bigr)=\operatorname{supp}(f_v)`),
        " なので、それは ",
        math(String.raw`u\in\operatorname{supp}(f_v)`),
        " と同値である。以上は有限集合の元の比較と写像の値の計算だけからなり、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "finite_layered_relation_definition_index_interval",
    kind: "definition",
    title: { text: "自然数の有限初期区間" },
    labels: ["def_finite_index_interval"],
    habitat: "N",
    statement: [
      paragraph([
        math(String.raw`\tau\in\mathbb{N}`),
        " に対し、",
      ]),
      displayMath(String.raw`[0,\tau]_{\mathbb{N}}:=\{\,t\in\mathbb{N}\mid t\leq\tau\,\}=\{0,1,\dots,\tau\}`),
      paragraph([
        "を自然数の有限初期区間と呼ぶ。",
        math(String.raw`t\leq\tau`),
        " は ",
        math(String.raw`\mathbb{N}`),
        " の大小比較である。この定義に使う ",
        math(String.raw`\mathbb{N}`),
        " の構造は、大小比較と後者 ",
        math(String.raw`t\mapsto t+1`),
        " だけである。添字 ",
        math(String.raw`\mathbb{N}`),
        " は区間の母集合を表す。実数区間と同形の無添字記法は使わない。",
      ]),
    ],
  },

  {
    id: "time_expansion_dependency_definition_event_set",
    kind: "definition",
    title: { text: "イベント集合" },
    labels: ["def_event_set"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）と ",
        math(String.raw`\tau\in\mathbb{N}`),
        " に対し、直積集合",
      ]),
      displayMath(String.raw`E_\tau:=[0,\tau]_{\mathbb{N}}\times V=\{\,(t,v)\mid t\in[0,\tau]_{\mathbb{N}},\ v\in V\,\}`),
      paragraph([
        "をイベント集合",
        "、その元 ",
        math(String.raw`(t,v)`),
        " を",
        "イベント",
        "と呼ぶ。このとき自然数の有限初期区間を時間の添字集合として読む（",
        math(String.raw`[0,\tau]_{\mathbb{N}}`),
        " は ",
        ref("def_finite_index_interval"),
        "）。第 1 成分 ",
        math(String.raw`t\in\mathbb{N}`),
        " を時刻、第 2 成分 ",
        math(String.raw`v\in V`),
        " をセルと呼ぶ。",
      ]),
    ],
  },

  {
    id: "time_expansion_dependency_claim_event_set_cardinality",
    kind: "claim",
    title: { text: "イベント集合は有限である" },
    labels: ["claim_event_set_cardinality"],
    habitat: "N",
    statement: [
      paragraph([
        "イベント集合 ",
        math(String.raw`E_\tau`),
        "（",
        ref("def_event_set"),
        "）は有限集合であり、",
        math(String.raw`|E_\tau|=(\tau+1)\cdot|V|\in\mathbb{N}`),
        " である（",
        math(String.raw`|X|`),
        " は ",
        ref("def_cardinality_notation"),
        "）。",
      ]),
    ],
    proof: [
      displayMath(String.raw`\begin{aligned}
|E_\tau|
&=|[0,\tau]_{\mathbb{N}}\times V|\qquad(\because\ \blkref{def_event_set})\\
&=|[0,\tau]_{\mathbb{N}}|\cdot|V|\qquad(\because\ \text{有限集合の直積の元の個数は個数の積（積の法則）})\\
&=(\tau+1)\cdot|V|\qquad(\because\ [0,\tau]_{\mathbb{N}}=\{0,1,\dots,\tau\}\ \text{の元は}\ \tau+1\ \text{個。}\blkref{def_finite_index_interval})
\end{aligned}`),
      paragraph([
        math(String.raw`[0,\tau]_{\mathbb{N}}`),
        " と ",
        math(String.raw`V`),
        " はいずれも有限集合（",
        ref("def_finite_index_interval"),
        " と ",
        ref("def_finite_stage"),
        "）なので、その直積 ",
        math(String.raw`E_\tau`),
        " も有限集合であり、上の個数は ",
        math(String.raw`\mathbb{N}`),
        " の元である。実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "time_expansion_dependency_definition_one_step_dependency",
    kind: "definition",
    title: { text: "一段依存関係" },
    labels: ["def_one_step_dependency"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台上の 2 値セルオートマトン ",
        math(String.raw`\bigl((V,N),(f_v)_{v\in V}\bigr)`),
        "（",
        ref("def_finite_ca"),
        "）と ",
        math(String.raw`\tau\in\mathbb{N}`),
        " に対し、集合",
      ]),
      displayMath(
        String.raw`D_\tau:=\bigl\{\,\bigl((s,u),(t,v)\bigr)\in E_\tau\times E_\tau\ \bigm|\ t=s+1\ \text{かつ}\ u\in\operatorname{supp}(f_v)\,\bigr\}`,
      ),
      paragraph([
        "を",
        "一段依存関係",
        "と呼び、",
        math(String.raw`\bigl((s,u),(t,v)\bigr)\in D_\tau`),
        " のとき「イベント ",
        math(String.raw`(t,v)`),
        " はイベント ",
        math(String.raw`(s,u)`),
        " に",
        "直接依存する",
        "」と読む（",
        math(String.raw`E_\tau`),
        " は ",
        ref("def_event_set"),
        "、",
        math(String.raw`\operatorname{supp}`),
        " は ",
        ref("def_essential_dependency_support"),
        "。等号 ",
        math(String.raw`t=s+1`),
        " は ",
        math(String.raw`\mathbb{N}`),
        " の元の等号である）。",
        ref("def_essential_dependency_support"),
        " より ",
        math(String.raw`\operatorname{supp}(f_v)\subseteq N(v)`),
        " なので、条件 ",
        math(String.raw`u\in\operatorname{supp}(f_v)`),
        " は ",
        math(String.raw`u\in N(v)`),
        " を含意する。",
      ]),
      paragraph([
        "条件に近傍への所属 ",
        math(String.raw`u\in N(v)`),
        " ではなく本質的依存台への所属 ",
        math(String.raw`u\in\operatorname{supp}(f_v)`),
        " を採る根拠は ",
        ref("claim_global_flip_characterization"),
        " である: ",
        math(String.raw`u\in\operatorname{supp}(f_v)`),
        " は、",
        math(String.raw`u`),
        " での一点反転で大域写像の ",
        math(String.raw`v`),
        " での値が変わる入力が存在することと同値であり、",
        ref("claim_support_invariance"),
        " により冗長な近傍の元の追加・削除で変わらない。",
      ]),
    ],
  },

  {
    id: "time_expansion_dependency_claim_one_step_dependency_finite_decidability",
    kind: "claim",
    title: { text: "一段依存関係は有限集合であり真理値表から有限回の比較で決定できる" },
    labels: ["claim_one_step_dependency_finite_decidability"],
    habitat: "N",
    statement: [
      paragraph([
        "一段依存関係 ",
        math(String.raw`D_\tau`),
        "（",
        ref("def_one_step_dependency"),
        "）は有限集合である。さらに、各組 ",
        math(String.raw`\bigl((s,u),(t,v)\bigr)\in E_\tau\times E_\tau`),
        " について、その ",
        math(String.raw`D_\tau`),
        " への所属は、",
        math(String.raw`\mathbb{N}`),
        " の元の等号検査 1 回と、",
        math(String.raw`f_v`),
        " の真理値表の値の比較高々 ",
        math(String.raw`|N(v)|\cdot 2^{|N(v)|}`),
        " 回で決定できる。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`D_\tau`),
        " は有限集合 ",
        math(String.raw`E_\tau\times E_\tau`),
        " の部分集合（",
        ref("def_one_step_dependency"),
        "）なので有限集合である（",
        math(String.raw`E_\tau`),
        " の有限性は ",
        ref("claim_event_set_cardinality"),
        "、有限集合の直積と部分集合は有限）。",
      ]),
      paragraph([
        "所属の決定について。",
        ref("def_one_step_dependency"),
        " より、",
        math(String.raw`\bigl((s,u),(t,v)\bigr)\in D_\tau`),
        " は「",
        math(String.raw`t=s+1`),
        " かつ ",
        math(String.raw`u\in\operatorname{supp}(f_v)`),
        "」と同値である。前者は ",
        math(String.raw`\mathbb{N}`),
        " の元 ",
        math(String.raw`t`),
        " と ",
        math(String.raw`s+1`),
        " の等号検査 1 回である。後者について、",
        ref("claim_support_finite_decidability"),
        " を局所真理値表 ",
        math(String.raw`(N(v),f_v)`),
        " に適用すると、",
        math(String.raw`\operatorname{supp}(f_v)`),
        " 全体が高々 ",
        math(String.raw`|N(v)|\cdot 2^{|N(v)|}`),
        " 回の真理値表の値の比較で決定できるので、その部分である所属 ",
        math(String.raw`u\in\operatorname{supp}(f_v)`),
        " も同じ回数以内の比較で決定できる。回数はいずれも ",
        math(String.raw`\mathbb{N}`),
        " の元であり、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "time_expansion_dependency_claim_time_strictly_increases",
    kind: "claim",
    title: { text: "一段依存で時刻は厳密に増える" },
    labels: ["claim_time_strictly_increases"],
    habitat: "N",
    statement: [
      paragraph([
        "任意の ",
        math(String.raw`\bigl((s,u),(t,v)\bigr)\in D_\tau`),
        "（",
        ref("def_one_step_dependency"),
        "）について ",
        math(String.raw`s<t`),
        " が成り立つ（",
        math(String.raw`<`),
        " は ",
        math(String.raw`\mathbb{N}`),
        " の大小比較）。",
      ]),
    ],
    proof: [
      paragraph([
        ref("def_one_step_dependency"),
        " より ",
        math(String.raw`t=s+1`),
        " である。",
        math(String.raw`\mathbb{N}`),
        " で ",
        math(String.raw`s<s+1`),
        " なので ",
        math(String.raw`s<t`),
        " である。比較はいずれも ",
        math(String.raw`\mathbb{N}`),
        " の元の間で行われ、実数体も複素数体も現れない。",
      ]),
    ],
  },
]);
