/**
 * 章「依存の推移閉包の反対称性」: 一段依存関係 D_τ の推移閉包（到達可能関係）を
 * 依存経路で定義し、一段依存で時刻が厳密に増えること（前章の claim）だけから、
 * 到達可能関係に相互到達がないこと（反対称性）と、その反射閉包が
 * イベント集合上の部分順序になることを示す。
 *
 * 使う ℕ の構造は前章と同じく大小比較と後者（+1）だけである。
 * 物理的な意味（因果・光円錐・時空など）はここへ持ち込まない。ℝ/ℂ は現れない。
 * 文書順はこの配列の並びが正本である。
 */

import { defineBlocks, displayMath, math, paragraph, ref } from "../schema.ts";

export default defineBlocks([
  {
    id: "transitive_closure_antisymmetry_heading",
    kind: "heading",
    level: 1,
    title: { text: "依存の推移閉包の反対称性" },
    labels: [],
  },

  {
    id: "transitive_closure_antisymmetry_definition_dependency_path",
    kind: "definition",
    title: { text: "有限関係の経路" },
    labels: ["def_dependency_path"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限集合 ", math(String.raw`X`), " と二項関係 ",
        math(String.raw`R\subseteq X\times X`), " に対し、",
        math(String.raw`n\in\mathbb{N}`),
        "、",
        math(String.raw`n\geq1`),
        " と、写像 ",
        math(String.raw`p:[0,n]_{\mathbb{N}}\to X`),
        "（",
        math(String.raw`[0,n]_{\mathbb{N}}`),
        " は ",
        ref("def_finite_index_interval"),
        "）であって、すべての ",
        math(String.raw`i\in[0,n-1]_{\mathbb{N}}`),
        " について ",
        math(String.raw`\bigl(p(i),\,p(i+1)\bigr)\in R`),
        " を満たすものの組 ",
        math(String.raw`(n,p)`),
        " を、",
        math(String.raw`p(0)`),
        " から ",
        math(String.raw`p(n)`),
        " への",
        "長さ ",
        math(String.raw`n`),
        " の ", math(String.raw`R`), "-経路",
        "と呼ぶ。",
        math(String.raw`p(0)`),
        " を始点、",
        math(String.raw`p(n)`),
        " を終点と呼ぶ。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_claim_relation_path_finite",
    kind: "claim",
    title: { text: "有限関係の経路は有限表である" },
    labels: ["claim_relation_path_finite"],
    habitat: "finite",
    statement: [paragraph([
      ref("def_dependency_path"), " の ", math(String.raw`R`), "-経路 ",
      math(String.raw`p:[0,n]_{\mathbb{N}}\to X`),
      " は有限集合の間の写像であり、有限表で指定できる。",
    ])],
    proof: [paragraph([
      math(String.raw`[0,n]_{\mathbb{N}}`), " は ", math(String.raw`n+1`),
      " 元の有限集合であり、", math(String.raw`X`), " は仮定により有限集合なのである。",
    ])],
  },

  {
    id: "transitive_closure_antisymmetry_definition_ca_dependency_path",
    kind: "definition",
    title: { text: "一段依存関係に沿う依存経路" },
    labels: ["def_ca_dependency_path"],
    habitat: "finite",
    statement: [paragraph([
      "有限舞台上の 2 値セルオートマトンと ", math(String.raw`\tau\in\mathbb{N}`),
      " に対し、", ref("def_dependency_path"), " で ", math(String.raw`X:=E_\tau`),
      "（", ref("def_event_set"), "）、", math(String.raw`R:=D_\tau`),
      "（", ref("def_one_step_dependency"), "）と特殊化した ", math(String.raw`R`),
      "-経路を依存経路と呼ぶ。",
    ])],
  },

  {
    id: "transitive_closure_antisymmetry_claim_path_time_strictly_increases",
    kind: "claim",
    title: { text: "依存経路に沿って時刻は厳密に増える" },
    labels: ["claim_path_time_strictly_increases"],
    habitat: "N",
    verification: ["sagemath/check/transitive-closure-antisymmetry"],
    statement: [
      paragraph([
        "有限舞台上の 2 値セルオートマトンについて、任意の依存経路 ",
        math(String.raw`(n,p)`),
        "（",
        ref("def_ca_dependency_path"),
        "）について、",
        math(String.raw`p(0)=(s,u)`),
        "、",
        math(String.raw`p(n)=(t,v)`),
        " と成分を書くと ",
        math(String.raw`s<t`),
        " が成り立つ（",
        math(String.raw`<`),
        " は ",
        math(String.raw`\mathbb{N}`),
        " の大小比較）。",
      ]),
    ],
    proof: [
      paragraph([
        "経路の長さ ",
        math(String.raw`n\geq1`),
        " についての数学的帰納法で示す。各イベント ",
        math(String.raw`p(i)\in E_\tau`),
        " の第 1 成分（時刻。",
        ref("def_event_set"),
        "）を ",
        math(String.raw`t_i\in\mathbb{N}`),
        " と書く。示すことは ",
        math(String.raw`t_0<t_n`),
        " である。",
      ]),
      paragraph([
        "基底（",
        math(String.raw`n=1`),
        "）: ",
        math(String.raw`\bigl(p(0),p(1)\bigr)\in D_\tau`),
        "（",
        ref("def_ca_dependency_path"),
        "）なので、",
        ref("claim_time_strictly_increases"),
        " より ",
        math(String.raw`t_0<t_1`),
        " である。",
      ]),
      paragraph([
        "帰納段（",
        math(String.raw`n\geq2`),
        "）: 長さ ",
        math(String.raw`n-1`),
        " について主張が成り立つと仮定する。",
        math(String.raw`p`),
        " の ",
        math(String.raw`[0,n-1]_{\mathbb{N}}`),
        " への制限は、",
        ref("def_ca_dependency_path"),
        " の条件をすべての ",
        math(String.raw`i\in[0,n-2]_{\mathbb{N}}`),
        " で満たすので、長さ ",
        math(String.raw`n-1`),
        " の依存経路である。帰納法の仮定より ",
        math(String.raw`t_0<t_{n-1}`),
        " である。また ",
        math(String.raw`\bigl(p(n-1),p(n)\bigr)\in D_\tau`),
        "（",
        ref("def_ca_dependency_path"),
        "）なので、",
        ref("claim_time_strictly_increases"),
        " より ",
        math(String.raw`t_{n-1}<t_n`),
        " である。",
        math(String.raw`\mathbb{N}`),
        " の大小比較の推移性より ",
        math(String.raw`t_0<t_n`),
        " である。",
      ]),
      paragraph([
        "比較はいずれも ",
        math(String.raw`\mathbb{N}`),
        " の元の間で行われ、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_definition_reachability",
    kind: "definition",
    title: { text: "有限関係の推移閉包" },
    labels: ["def_reachability"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限集合 ", math(String.raw`X`), " と二項関係 ",
        math(String.raw`R\subseteq X\times X`), " に対し、集合",
      ]),
      displayMath(
        String.raw`R^{+}:=\bigl\{\,(a,b)\in X\times X\ \bigm|\ a\ \text{から}\ b\ \text{への }R\text{-経路が存在する}\,\bigr\}`,
      ),
      paragraph([
        "を",
        "推移閉包",
        "と呼ぶ（経路は ",
        ref("def_dependency_path"),
        "）。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_definition_ca_reachability",
    kind: "definition",
    title: { text: "一段依存関係の到達可能関係" },
    labels: ["def_ca_reachability"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限舞台上の 2 値セルオートマトンと ", math(String.raw`\tau\in\mathbb{N}`),
        " に対し、", ref("def_one_step_dependency"), " の ", math(String.raw`D_\tau`),
        " を ", ref("def_reachability"), " の有限関係 ", math(String.raw`R`),
        " に代入して得る推移閉包を",
      ]),
      displayMath(String.raw`C_\tau:=D_\tau^{+}\subseteq E_\tau\times E_\tau`),
      paragraph(["と書き、到達可能関係と呼ぶ。"]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_claim_reachability_finite",
    kind: "claim",
    title: { text: "有限関係の推移閉包は有限である" },
    labels: ["claim_reachability_finite"],
    habitat: "finite",
    statement: [paragraph([
      ref("def_reachability"), " の ", math(String.raw`R^+`), " は有限集合である。",
    ])],
    proof: [paragraph([
      math(String.raw`R^+\subseteq X\times X`), " であり、有限集合の直積と部分集合は有限なのである。",
    ])],
  },

  {
    id: "transitive_closure_antisymmetry_claim_one_step_subset",
    kind: "claim",
    title: { text: "有限関係はその推移閉包に含まれる" },
    labels: ["claim_one_step_subset_reachability"],
    habitat: "finite",
    verification: ["sagemath/check/transitive-closure-antisymmetry"],
    statement: [
      paragraph([ref("def_reachability"), " の有限関係について ",
        math(String.raw`R\subseteq R^+`), " が成り立つ。"]),
    ],
    proof: [
      paragraph([
        math(String.raw`(a,b)\in R`),
        " とする。",
        math(String.raw`n:=1`),
        "、",
        math(String.raw`p(0):=a`),
        "、",
        math(String.raw`p(1):=b`),
        " と置くと、組 ",
        math(String.raw`(n,p)`),
        " は ",
        ref("def_dependency_path"),
        " の条件（",
        math(String.raw`i=0`),
        " について ",
        math(String.raw`\bigl(p(0),p(1)\bigr)=(a,b)\in R`),
        "）を満たすので、",
        math(String.raw`a`),
        " から ",
        math(String.raw`b`),
        " への長さ 1 の ", math(String.raw`R`), "-経路である。よって ",
        ref("def_reachability"),
        " より ",
        math(String.raw`(a,b)\in R^+`),
        " である。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_claim_reachability_transitive",
    kind: "claim",
    title: { text: "推移閉包は推移的である" },
    labels: ["claim_reachability_transitive"],
    habitat: "finite",
    verification: ["sagemath/check/transitive-closure-antisymmetry"],
    statement: [
      paragraph([
        math(String.raw`(a,b)\in R^+`),
        " かつ ",
        math(String.raw`(b,c)\in R^+`),
        " ならば ",
        math(String.raw`(a,c)\in R^+`),
        " である（",
        math(String.raw`R^+`),
        " は ",
        ref("def_reachability"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        ref("def_reachability"),
        " より、",
        math(String.raw`a`),
        " から ",
        math(String.raw`b`),
        " への長さ ",
        math(String.raw`m`),
        " の ", math(String.raw`R`), "-経路 ",
        math(String.raw`(m,p)`),
        " と、",
        math(String.raw`b`),
        " から ",
        math(String.raw`c`),
        " への長さ ",
        math(String.raw`n`),
        " の ", math(String.raw`R`), "-経路 ",
        math(String.raw`(n,q)`),
        " が存在する。写像 ",
        math(String.raw`r:[0,m+n]_{\mathbb{N}}\to X`),
        " を",
      ]),
      displayMath(
        String.raw`r(i):=\begin{cases}p(i)&(i\in[0,m]_{\mathbb{N}})\\ q(i-m)&(i\in[0,m+n]_{\mathbb{N}}\ \text{かつ}\ i\geq m)\end{cases}`,
      ),
      paragraph([
        "で定める（",
        math(String.raw`i=m`),
        " では ",
        math(String.raw`p(m)=b=q(0)`),
        " なので二つの場合は一致し、",
        math(String.raw`r`),
        " は well-defined である）。各 ",
        math(String.raw`i\in[0,m+n-1]_{\mathbb{N}}`),
        " について、",
        math(String.raw`i\leq m-1`),
        " なら ",
        math(String.raw`\bigl(r(i),r(i+1)\bigr)=\bigl(p(i),p(i+1)\bigr)\in R`),
        "（",
        math(String.raw`(m,p)`),
        " が ", math(String.raw`R`), "-経路であることによる。",
        ref("def_dependency_path"),
        "）、",
        math(String.raw`i\geq m`),
        " なら ",
        math(String.raw`\bigl(r(i),r(i+1)\bigr)=\bigl(q(i-m),q(i-m+1)\bigr)\in R`),
        "（",
        math(String.raw`(n,q)`),
        " が ", math(String.raw`R`), "-経路であることによる。",
        ref("def_dependency_path"),
        "）である。",
        math(String.raw`m\geq1`),
        "、",
        math(String.raw`n\geq1`),
        " より ",
        math(String.raw`m+n\geq1`),
        " なので、組 ",
        math(String.raw`(m+n,r)`),
        " は ",
        math(String.raw`a=r(0)`),
        " から ",
        math(String.raw`c=r(m+n)`),
        " への ", math(String.raw`R`), "-経路である。よって ",
        ref("def_reachability"),
        " より ",
        math(String.raw`(a,c)\in R^+`),
        " である。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_claim_reachability_minimal",
    kind: "claim",
    title: { text: "推移閉包は元の関係を含む最小の推移的関係である" },
    labels: ["claim_reachability_minimal"],
    habitat: "finite",
    verification: ["sagemath/check/transitive-closure-antisymmetry"],
    statement: [
      paragraph([
        ref("def_reachability"), " の有限関係 ", math(String.raw`R\subseteq X\times X`),
        " に対し、", math(String.raw`S\subseteq X\times X`),
        " が推移的（",
        math(String.raw`(a,b)\in S`),
        " かつ ",
        math(String.raw`(b,c)\in S`),
        " ならば ",
        math(String.raw`(a,c)\in S`),
        "）で ",
        math(String.raw`R\subseteq S`),
        " を満たすならば、",
        math(String.raw`R^+\subseteq S`), " である。",
      ]),
    ],
    proof: [
      paragraph([
        "「長さ ",
        math(String.raw`n`),
        " の任意の ", math(String.raw`R`), "-経路 ",
        math(String.raw`(n,p)`),
        " について ",
        math(String.raw`\bigl(p(0),p(n)\bigr)\in S`),
        "」を ",
        math(String.raw`n\geq1`),
        " についての数学的帰納法で示す。",
      ]),
      paragraph([
        "基底（",
        math(String.raw`n=1`),
        "）: ",
        math(String.raw`\bigl(p(0),p(1)\bigr)\in R`),
        "（",
        ref("def_dependency_path"),
        "）と仮定 ",
        math(String.raw`R\subseteq S`),
        " より ",
        math(String.raw`\bigl(p(0),p(1)\bigr)\in S`),
        " である。",
      ]),
      paragraph([
        "帰納段（",
        math(String.raw`n\geq2`),
        "）: ",
        math(String.raw`p`),
        " の ",
        math(String.raw`[0,n-1]_{\mathbb{N}}`),
        " への制限は長さ ",
        math(String.raw`n-1`),
        " の ", math(String.raw`R`), "-経路である（",
        ref("def_dependency_path"),
        " の辺条件を ", math(String.raw`i\in[0,n-2]_{\mathbb{N}}`),
        " に制限する）。したがって帰納法の仮定より ",
        math(String.raw`\bigl(p(0),p(n-1)\bigr)\in S`),
        " である。また ",
        math(String.raw`\bigl(p(n-1),p(n)\bigr)\in R\subseteq S`),
        "（",
        ref("def_dependency_path"),
        " と仮定）である。",
        math(String.raw`S`),
        " の推移性より ",
        math(String.raw`\bigl(p(0),p(n)\bigr)\in S`),
        " である。",
      ]),
      paragraph([
        "任意の ",
        math(String.raw`(a,b)\in R^+`),
        " は ", ref("def_reachability"),
        " よりある ", math(String.raw`R`), "-経路の始点と終点の組なので、以上より ",
        math(String.raw`(a,b)\in S`),
        " である。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_claim_no_mutual_reachability",
    kind: "claim",
    title: { text: "相互に到達可能な二つのイベントは存在しない" },
    labels: ["claim_no_mutual_reachability"],
    habitat: "N",
    verification: ["sagemath/check/transitive-closure-antisymmetry"],
    statement: [
      paragraph([
        math(String.raw`(a,b)\in C_\tau`),
        " かつ ",
        math(String.raw`(b,a)\in C_\tau`),
        " となる ",
        math(String.raw`a,b\in E_\tau`),
        " は存在しない（",
        math(String.raw`C_\tau`),
        " は ",
        ref("def_ca_reachability"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`(a,b)\in C_\tau`),
        " かつ ",
        math(String.raw`(b,a)\in C_\tau`),
        " と仮定して矛盾を導く。",
        math(String.raw`a=(s,u)`),
        "、",
        math(String.raw`b=(t,v)`),
        " と成分を書く（",
        ref("def_event_set"),
        "）。",
        math(String.raw`(a,b)\in C_\tau`),
        " より ",
        math(String.raw`a`),
        " から ",
        math(String.raw`b`),
        " への依存経路が存在し（",
        ref("def_ca_reachability"),
        "）、",
        ref("claim_path_time_strictly_increases"),
        " より ",
        math(String.raw`s<t`),
        " である。同様に ",
        math(String.raw`(b,a)\in C_\tau`),
        " と ",
        ref("claim_path_time_strictly_increases"),
        " より ",
        math(String.raw`t<s`),
        " である。",
        math(String.raw`\mathbb{N}`),
        " の大小比較の推移性より ",
        math(String.raw`s<s`),
        " となるが、",
        math(String.raw`\mathbb{N}`),
        " の大小比較は非反射的（",
        math(String.raw`s<s`),
        " は成り立たない）なので矛盾である。よって仮定した組は存在しない。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_claim_reachability_irreflexive",
    kind: "claim",
    title: { text: "どのイベントも自分自身に到達しない" },
    labels: ["claim_reachability_irreflexive"],
    habitat: "N",
    verification: ["sagemath/check/transitive-closure-antisymmetry"],
    statement: [
      paragraph([
        math(String.raw`(a,a)\in C_\tau`),
        " となる ",
        math(String.raw`a\in E_\tau`),
        " は存在しない（",
        math(String.raw`C_\tau`),
        " は ",
        ref("def_ca_reachability"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`(a,a)\in C_\tau`),
        " と仮定すると、",
        math(String.raw`b:=a`),
        " と置いて ",
        math(String.raw`(a,b)\in C_\tau`),
        " かつ ",
        math(String.raw`(b,a)\in C_\tau`),
        " となり、",
        ref("claim_no_mutual_reachability"),
        " に矛盾する。よってそのような ",
        math(String.raw`a`),
        " は存在しない。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_definition_reflexive_reachability",
    kind: "definition",
    title: { text: "有限関係の反射推移閉包" },
    labels: ["def_reflexive_reachability"],
    habitat: "finite",
    statement: [
      paragraph([
        "有限集合 ", math(String.raw`X`), " と二項関係 ",
        math(String.raw`R\subseteq X\times X`), " に対し、集合",
      ]),
      displayMath(
        String.raw`R^{*}:=\bigl\{\,(a,b)\in X\times X\ \bigm|\ a=b\ \text{または}\ (a,b)\in R^+\,\bigr\}`,
      ),
      paragraph([
        "を",
        "反射推移閉包",
        "と呼ぶ（", math(String.raw`R^+`), " は ", ref("def_reachability"), "）。等号 ",
        math(String.raw`a=b`),
        " は ", math(String.raw`X`), " の元の等号である。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_definition_ca_reflexive_reachability",
    kind: "definition",
    title: { text: "一段依存関係の反射的到達可能関係" },
    labels: ["def_ca_reflexive_reachability"],
    habitat: "finite",
    statement: [paragraph([
      ref("def_ca_reachability"), " の ", math(String.raw`C_\tau=D_\tau^+`),
      " に対し、", ref("def_reflexive_reachability"), " の特殊化 ",
      math(String.raw`D_\tau^*`), " を ", math(String.raw`\preceq_\tau`),
      " と書く。すなわち ",
      math(String.raw`a\preceq_\tau b\iff a=b\ \text{または}\ (a,b)\in C_\tau`), " である。",
    ])],
  },

  {
    id: "transitive_closure_antisymmetry_definition_partial_order",
    kind: "definition",
    title: { text: "部分順序" },
    labels: ["def_partial_order"],
    habitat: "none",
    statement: [
      paragraph([
        "集合 ",
        math(String.raw`X`),
        " と部分集合 ",
        math(String.raw`R\subseteq X\times X`),
        " について、",
        math(String.raw`R`),
        " が ",
        math(String.raw`X`),
        " 上の",
        "部分順序",
        "であるとは、次の 3 条件をすべて満たすことをいう。",
        "反射性: すべての ",
        math(String.raw`x\in X`),
        " について ",
        math(String.raw`(x,x)\in R`),
        "。反対称性: ",
        math(String.raw`(x,y)\in R`),
        " かつ ",
        math(String.raw`(y,x)\in R`),
        " ならば ",
        math(String.raw`x=y`),
        "。推移性: ",
        math(String.raw`(x,y)\in R`),
        " かつ ",
        math(String.raw`(y,z)\in R`),
        " ならば ",
        math(String.raw`(x,z)\in R`),
        "。",
      ]),
    ],
  },

  {
    id: "transitive_closure_antisymmetry_claim_partial_order",
    kind: "claim",
    title: { text: "反射的到達可能関係はイベント集合上の部分順序である" },
    labels: ["claim_reachability_partial_order"],
    habitat: "finite",
    verification: ["sagemath/check/transitive-closure-antisymmetry"],
    statement: [
      paragraph([
        "反射的到達可能関係 ",
        math(String.raw`\preceq_\tau`),
        "（",
        ref("def_ca_reflexive_reachability"),
        "）は、有限集合 ",
        math(String.raw`E_\tau`),
        " 上の部分順序（",
        ref("def_partial_order"),
        "）である。",
      ]),
    ],
    proof: [
      paragraph([
        "反射性: 任意の ",
        math(String.raw`a\in E_\tau`),
        " について ",
        math(String.raw`a=a`),
        " なので、",
        ref("def_ca_reflexive_reachability"),
        " より ",
        math(String.raw`a\preceq_\tau a`),
        " である。",
      ]),
      paragraph([
        "反対称性: ",
        math(String.raw`a\preceq_\tau b`),
        " かつ ",
        math(String.raw`b\preceq_\tau a`),
        " とする。",
        math(String.raw`a=b`),
        " でないと仮定すると、",
        ref("def_ca_reflexive_reachability"),
        " より ",
        math(String.raw`(a,b)\in C_\tau`),
        " かつ ",
        math(String.raw`(b,a)\in C_\tau`),
        " であるが、これは ",
        ref("claim_no_mutual_reachability"),
        " に矛盾する。よって ",
        math(String.raw`a=b`),
        " である。",
      ]),
      paragraph([
        "推移性: ",
        math(String.raw`a\preceq_\tau b`),
        " かつ ",
        math(String.raw`b\preceq_\tau c`),
        " とする。",
        ref("def_ca_reflexive_reachability"),
        " により 4 つの場合に分かれる。",
        math(String.raw`a=b`),
        " かつ ",
        math(String.raw`b=c`),
        " なら ",
        math(String.raw`a=c`),
        " なので ",
        math(String.raw`a\preceq_\tau c`),
        "。",
        math(String.raw`a=b`),
        " かつ ",
        math(String.raw`(b,c)\in C_\tau`),
        " なら ",
        math(String.raw`(a,c)\in C_\tau`),
        "（等しい元の置き換え）なので ",
        math(String.raw`a\preceq_\tau c`),
        "。",
        math(String.raw`(a,b)\in C_\tau`),
        " かつ ",
        math(String.raw`b=c`),
        " なら同様に ",
        math(String.raw`(a,c)\in C_\tau`),
        " なので ",
        math(String.raw`a\preceq_\tau c`),
        "。",
        math(String.raw`(a,b)\in C_\tau`),
        " かつ ",
        math(String.raw`(b,c)\in C_\tau`),
        " なら ",
        ref("claim_reachability_transitive"),
        " より ",
        math(String.raw`(a,c)\in C_\tau`),
        " なので ",
        math(String.raw`a\preceq_\tau c`),
        " である。",
      ]),
      paragraph([
        "以上の 3 条件がすべて成り立つので、",
        ref("def_partial_order"),
        " より ",
        math(String.raw`\preceq_\tau`),
        " は ",
        math(String.raw`E_\tau`),
        " 上の部分順序である。議論はすべて有限集合の元の等号・所属と ",
        math(String.raw`\mathbb{N}`),
        " の大小比較の中で行われ、実数体も複素数体も現れない。",
      ]),
    ],
  },
]);
