

# This file was *autogenerated* from the file onsager_structure.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_70 = Integer(70); _sage_const_4 = Integer(4)# cycle 4 / T2: カイラル Potts(超可積分 ℤ_3)の有限 N スペクトルの代数構造を観察。
# 仮説(既知の超可積分構造): 準位 E = A ± Σ_k m_k √(α_k)(Onsager 代数/自由フェルミ)。
#  ⇒ 各固有値の最小多項式次数は 2 の冪、スペクトルは多重2次体に住む。
#  ⇒ 2次因子 x^2+bx+c の判別式 b^2-4c が「フェルミオン的」量(√の中身)。
# 有限 N データから極限の Onsager 構造の足跡を読む(T2: 有限 N→極限への橋)。

n=_sage_const_3 
w=QQbar.zeta(_sage_const_3 )
Z=matrix(QQbar,[[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,w,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,w**_sage_const_2 ]])
X=matrix(QQbar,[[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ,_sage_const_0 ]])
I3=identity_matrix(QQbar,_sage_const_3 )
def emb(op,i,N):
    m=[op if k==i else I3 for k in range(N)]
    M=m[_sage_const_0 ]
    for k in range(_sage_const_1 ,N): M=M.tensor_product(m[k])
    return M
def H_cp(N,lam):
    H=matrix(QQbar,_sage_const_3 **N,_sage_const_3 **N); coef={a:(_sage_const_1 -w**(-a))**(-_sage_const_1 ) for a in [_sage_const_1 ,_sage_const_2 ]}
    Zi={i:emb(Z,i,N) for i in range(N)}; Xi={i:emb(X,i,N) for i in range(N)}
    for j in range(N):
        jp=(j+_sage_const_1 )%N
        for a in [_sage_const_1 ,_sage_const_2 ]:
            H += -coef[a]*(Xi[j]**a + lam*Zi[j]**a*Zi[jp]**(n-a))
    return H

def is_pow2(m):
    return m>_sage_const_0  and (m & (m-_sage_const_1 ))==_sage_const_0 

print("="*_sage_const_70 )
print("カイラル Potts 有限 N スペクトルの Onsager/多重2次体 構造")
print("="*_sage_const_70 )

for lam in [QQ(_sage_const_1 ), QQ(_sage_const_1 )/_sage_const_2 ]:
    print(f"\n#### λ={lam}")
    for N in [_sage_const_2 ,_sage_const_3 ]:
        H=H_cp(N,lam)
        evs=H.eigenvalues()
        mps={}
        for ev in evs:
            mp=QQbar(ev).minpoly()
            mps[mp]=mps.get(mp,_sage_const_0 )+_sage_const_1 
        degs=sorted(set(p.degree() for p in mps))
        all_pow2=all(is_pow2(p.degree()) for p in mps)
        allreal=all(ev.imag()==_sage_const_0  for ev in evs)
        # 2次因子の判別式(√の中身)
        discs=set()
        for p in mps:
            if p.degree()==_sage_const_2 :
                c=p.list()  # [c0,c1,1]
                b,cc=c[_sage_const_1 ],c[_sage_const_0 ]
                discs.add(QQ(b**_sage_const_2 -_sage_const_4 *cc))
        print(f"  N={N}: dim={_sage_const_3 **N}, 最小多項式次数集合={degs}, 全2冪次数={all_pow2}, 全実={allreal}")
        print(f"        2次固有値の判別式(√の中身)集合={sorted(discs)}  (← Onsager フェルミオン量の候補)")

print("\n"+"="*_sage_const_70 )
print("読み: 次数が 2 の冪・スペクトルが少数の √(判別式)で生成 ⇒ 超可積分の")
print(" Onsager/自由フェルミ構造の有限 N での足跡。√ の中身の集合が N で安定/規則的なら")
print(" 極限のフェルミオン準位への橋(T2)。有限 N は完全に ℚ̄ で決定可能。")
print("="*_sage_const_70 )

