

# This file was *autogenerated* from the file check_01_sqrt_of_inverse.sage
from sage.all_cmdline import *   # import sage library

_sage_const_304 = Integer(304); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_0p0 = RealNumber('0.0'); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_2 = Integer(2); _sage_const_1p0 = RealNumber('1.0')# <sqrt_cc_of_inverse>: (sqrt z)^{-1} = 1/sqrt z = ± sqrt(1/z)
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import math
load(os.path.join(_dir, "_prelude.sage"))
rng = np.random.default_rng(int(_sage_const_304 ))
rep = CheckReport("sqrt_cc_of_inverse")
zs = [z for z in sample_complex(rng) if abs(z) > _sage_const_1en8 ]
c0 = cp = _sage_const_0 
for z in zs:
    a = arg_def(z)
    rhs = _sage_const_1 /sqrt_def(z)
    rep.close(_sage_const_1 /sqrt_def(z), rhs, f"z={z}: (sqrt z)^{{-1}} = 1/sqrt z")
    lhs = sqrt_def(_sage_const_1 /z)
    if a == _sage_const_0p0 :
        c0 += _sage_const_1 
        rep.close(rhs, lhs, f"z={z} arg=0: 1/sqrt z = sqrt(1/z)")
    elif a < _sage_const_1en9  or a > _sage_const_2 *math.pi - _sage_const_1en9 :
        ok = (abs(rhs-lhs) < _sage_const_1en8 *max(_sage_const_1p0 ,abs(rhs))) or (abs(rhs+lhs) < _sage_const_1en8 *max(_sage_const_1p0 ,abs(rhs)))
        rep.truth(ok, f"境界 z={z}: ± のいずれか")
    else:
        cp += _sage_const_1 
        rep.close(rhs, -lhs, f"z={z} 0<arg<2pi: 1/sqrt z = -sqrt(1/z)")
print(f"  arg=0 の場合 {c0} 件、0<arg<2pi の場合 {cp} 件")
rep.truth(c0 > _sage_const_0  and cp > _sage_const_0 , "両方の場合を踏んでいる")
rep.finish()

