

# This file was *autogenerated* from the file check_01_conversion.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_7 = Integer(7)# <cosh_sinh_coefficient_conversion>: (i/2)K_1 H_1^{(±)} 版と i K_2^* H_2 版の n 重交換子
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import math
rep = CheckReport("cosh_sinh_coefficient_conversion")
for M in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    for p in OP_TEST_PARAMS[:_sage_const_3 ]:
        K1 = p['K1']; K2s = K_star(p['K2'])
        for mu in list(range(-M,_sage_const_0 )) + list(range(_sage_const_1 ,M+_sage_const_1 )):
            e_m = np.exp(-_sage_const_1j *_sage_const_2 *np.pi*mu/M)
            for sgn in ['+','-']:
                X1 = _sage_const_1j *(K1/_sage_const_2p0 )*H1_op(M, sgn)
                Zs = hatZ_op(mu,M,sgn); Ys = hatY_op(mu,M)
                for n in range(_sage_const_0 , _sage_const_7 ):
                    lhs = ad_pow(X1, Zs, n)
                    rhs = (_sage_const_1j *K1**n*e_m*Ys) if n % _sage_const_2  == _sage_const_1  else (K1**n*Zs)
                    rep.close(lhs, rhs, f"M={M} sgn={sgn} mu={mu} n={n}: (h1.z)")
            X2 = _sage_const_1j *K2s*H2_op(M)
            Zm = hatZ_op(mu,M,'-'); Ym = hatY_op(mu,M)
            for n in range(_sage_const_0 , _sage_const_7 ):
                lhs = ad_pow(X2, Zm, n)
                rhs = (-_sage_const_1j *(_sage_const_2 *K2s)**n*Ym) if n % _sage_const_2  == _sage_const_1  else ((_sage_const_2 *K2s)**n*Zm)
                rep.close(lhs, rhs, f"M={M} mu={mu} n={n}: (h2.z-)")
rep.finish()

