

# This file was *autogenerated* from the file spanning_tree_both_places.sage
from sage.all_cmdline import *   # import sage library

_sage_const_300 = Integer(300); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_0p915965594177219015 = RealNumber('0.915965594177219015'); _sage_const_70 = Integer(70); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_1en3 = RealNumber('1e-3'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29)# cycle 9 / T1: 2変数スペクトル曲線 = 離散ラプラシアン P(z,w)=4-(z+1/z)-(w+1/w)。
# これは全域木/ダイマー/ガウス自由場の曲線。matrix-tree 定理:
#   L×L トーラスの全域木数 τ(L) = (1/L^2) Π_{(j,k)≠(0,0)} (4-2cos(2πj/L)-2cos(2πk/L)) ∈ ℤ。
# つまり a_L = Π_{(z,w)≠(1,1)} P = L^2·τ(L)。 同一 P の両素点:
#   ℝ側: (1/L^2)log τ(L) → 4G/π (全域木エントロピー, G=Catalan 定数, 既知).
#   Λ側: v_p(τ(L)) = Φ_L∈Λ の ℓ_p 係数 (素因数分解, 決定可能).

def tau(L, prec=_sage_const_300 ):
    C=RealField(prec)
    import math
    prod=C(_sage_const_1 )
    for j in range(L):
        for k in range(L):
            if j==_sage_const_0  and k==_sage_const_0 : continue
            ev = C(_sage_const_4 ) - _sage_const_2 *C(cos(_sage_const_2 *C.pi()*j/L)) - _sage_const_2 *C(cos(_sage_const_2 *C.pi()*k/L))
            prod *= ev
    val = prod / (L**_sage_const_2 )
    t = val.round()
    err = abs(val - t)
    return ZZ(t), float(err)

# 4G/π (Catalan)
G = _sage_const_0p915965594177219015    # Catalan 定数
target = _sage_const_4 *G/pi

print("="*_sage_const_70 )
print("2変数スペクトル曲線 P=4-(z+1/z)-(w+1/w): 全域木の両素点")
print("="*_sage_const_70 )
print(f"既知: 全域木エントロピー = 4G/π = {float(target):.6f}  (G=Catalan)")
print(f"\n{'L':>2} {'τ(L)=#全域木':>26} {'(_sage_const_1 /L**_sage_const_2 )logτ':>12}   v_p 構造(Λ側)")
for L in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_5 ,_sage_const_6 ,_sage_const_7 ,_sage_const_8 ]:
    t,err=tau(L)
    assert err<_sage_const_1en3 , f"L={L} 整数化誤差 {err}"
    rate=float(RR(t).log()/L**_sage_const_2 ) if t>_sage_const_1  else _sage_const_0p0 
    facs={p:t.valuation(p) for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ] if t%p==_sage_const_0 }
    lam=" ".join(f"{e}*l_{p}" for p,e in facs.items()) if facs else "(単数/大素数)"
    print(f"{L:>2} {t:>26} {rate:>12.6f}   {lam}")

print("\n"+"="*_sage_const_70 )
print("確認: (1/L^2)logτ(L) → 4G/π = 1.16624 (ℝ側=全域木エントロピー, 既知の Catalan 定数).")
print(" 同じ τ(L)∈ℤ の素因数分解 = Φ_L∈Λ (Λ側, 決定可能).")
print(" ⇒ 同一整数スペクトル曲線 P から ℝ(既知物理定数)と Λ(素因数構造)の両素点. cycle5 の toy P を")
print("   実際の格子模型(全域木/ダイマー/GFF)へ拡張. ℝ側が既知定数と一致=Reframe の裏付け.")
print("="*_sage_const_70 )

