import { defineNotes, paragraph, math, displayMath, list, ref } from "../schema.ts";

// 章「線型空間の一般論」に紐づく参照用ノート。文書本体ではない。

export default defineNotes([
  {
    id: "note_linear_space_general_001_reading_and_usage",
    targets: ["tensor_basis"],
    title: { text: "ステートメントの読み方と本論文での用途" },
    sourcePath: "_old/typst/parts/002_線型空間の一般論/000_theorem_テンソル積の基底は基底のテンソル積.typ",
    body: [
      paragraph([
        "基底であるのは族全体であって、個々のクロネッカー積 ",
        math(String.raw`b_{a_1} \boxtimes \cdots \boxtimes b_{a_M}`),
        " ではない（単一の元は 1 次元しか張らないので、",
        math(String.raw`4^M \geq 2`),
        " のとき基底になり得ない）。本論文での用途は次のとおりである。",
      ]),
      list([
        [
          "(1)（行列単位のクロネッカー積）: ",
          ref("centralizer_is_scalar"),
          " で ",
          math(String.raw`W`),
          " を展開するとき、および ",
          ref("def_end_iso"),
          " で ",
          math(String.raw`\mathbf{end}`),
          " を基底上で定めるときに使う。",
        ],
        [
          "(2)（一般の基底 ",
          math(String.raw`\{I,\sigma^x,\sigma^y,\sigma^z\}`),
          " のクロネッカー積）: ",
          ref("Z_Y_linearly_independent"),
          " と ",
          ref("Z_Y_generate_algebra"),
          " で使う。",
        ],
        [
          "(3)（数ベクトルの標準基底のクロネッカー積）: ",
          ref("def_end_iso"),
          " で ",
          math(String.raw`\mathcal{F} = \mathbb{C}^{2^M}`),
          " の基底を得るために使う。",
        ],
      ]),
    ],
  },
  {
    id: "note_linear_space_general_002_abstract_tensor_product_view",
    targets: ["tensor_basis", "def_kronecker", "kronecker_product_rule", "kronecker_multilinear"],
    title: { text: "抽象テンソル積による見方（本文には採用しなかった）" },
    sourcePath: "_old/typst/parts/002_線型空間の一般論/000_theorem_テンソル積の基底は基底のテンソル積.typ",
    body: [
      paragraph([
        "この見方は、ゴールに照らして本文には採用しなかった。理由は ",
        "README「使ってよい道具・使わない道具」で抽象テンソル積の一般論を使わないと定めており、",
        "とりわけ「基底のテンソル積が基底」という主張を本文に置かないと明記しているためである。",
        "読者に、テンソル積の普遍性・商空間による構成・一般の体上の線型代数を先に要求してしまい、",
        "Ising 模型の本筋と関係のないところで負担が生じる。ここには、以前に本文へ置いていた",
        "抽象版の主張と、具体版との対応だけを記録しておく。",
      ]),
      paragraph(["以前に本文（ラベル ", ref("tensor_basis"), "）へ置いていた抽象版の主張は次のものである。"]),
      paragraph([
        math(String.raw`m, n \in \mathbb{Z}_{\geq 1}`),
        " とする。",
        math(String.raw`V`),
        " を ",
        math(String.raw`n`),
        " 次元 ",
        math(String.raw`K`),
        "-線型空間、",
        math(String.raw`E = \{e_1,\dots,e_n\}`),
        " を ",
        math(String.raw`V`),
        " の基底とするとき、多重添字 ",
        math(String.raw`(i_1,\dots,i_m) \in \{1,\dots,n\}^m`),
        " で添字づけられた族",
      ]),
      displayMath(
        String.raw`\left\{\, e_{i_1} \otimes \cdots \otimes e_{i_m} \;\middle|\; (i_1,\dots,i_m) \in \{1,\dots,n\}^m \,\right\}`,
      ),
      paragraph([
        "は、",
        math(String.raw`m`),
        " 階テンソル冪 ",
        math(String.raw`V^{\otimes m}`),
        " の基底である。特に ",
        math(String.raw`\dim_K V^{\otimes m} = n^m`),
        " である。",
      ]),
      paragraph([
        "具体版（現在の本文）との対応は次のとおり。抽象版で ",
        math(String.raw`K = \mathbb{C}`),
        "、",
        math(String.raw`V = \mathrm{Mat}(2,\mathbb{C})`),
        "（",
        math(String.raw`n = 4`),
        "）、",
        math(String.raw`m = M`),
        " とした場合が ",
        ref("tensor_basis"),
        " (2) に、",
        math(String.raw`V = \mathbb{C}^2`),
        "（",
        math(String.raw`n = 2`),
        "）とした場合が (3) に当たる。抽象版では ",
        math(String.raw`V^{\otimes m}`),
        " の元は「テンソル積という構成で作った空間の元」であって成分を持たないが、具体版では ",
        ref("def_kronecker"),
        " のとおり ",
        math(String.raw`2^M`),
        " 次の複素行列・",
        math(String.raw`2^M`),
        " 次元の数ベクトルそのものであり、すべての主張が成分の計算で確かめられる。",
      ]),
      paragraph([
        "抽象版では公理として与えられていた 2 つの計算規則",
        math(String.raw`\ (A_1\otimes\cdots\otimes A_M)(B_1\otimes\cdots\otimes B_M) = (A_1B_1)\otimes\cdots\otimes(A_MB_M)\ `),
        "（テンソル積代数の積の定義）と各因子についての ",
        math(String.raw`\mathbb{C}`),
        "-線型性は、具体版ではそれぞれ ",
        ref("kronecker_product_rule"),
        " と ",
        ref("kronecker_multilinear"),
        " として成分計算で証明される主張になる。これが具体化のいちばんの利点である",
        "（旧構成では、この 2 つの規則は全編 20 箇所以上で根拠に使われながら、",
        "定義も証明も本文に存在しなかった）。",
      ]),
      paragraph([
        "抽象版の Lean 形式化は ",
        math(String.raw`\texttt{lean/Ising2D/Part002/Theorem000\_TensorBasis.lean}`),
        " にある（README 4 節の「抽象版は Lean の中だけに置く」に従い、本文へは戻さない）。",
      ]),
    ],
  },
]);
