import { defineNotes, paragraph, math, displayMath, list, ref } from "../schema.ts";

// 群の一般論（自己同型群・群準同型・核・像・中心・完全列・環の乗法群）。
//
// これらは 008 章の本文（content/008_TV1_hatZ_hatY_part1.ts）に定義・主張として
// 置かれていたが、README のゴール設定（「環・体などの一般論に持ち上げた証明は使わない」
// 「脇道の一般論なら具体的な形に落とす」）に照らして本文からは外し、ここへ退避した。
// 内容は要約せずそのまま移してある。ただし本文から消えたラベルへの相互参照だけは、
// 参照が解決しなくなるため「本ノート「…」」という文字列へ書き換えてある。
//
// 本文側でこの一式が実際に効いていたのは
// injectivity_of_T_up_to_scalar（共役写像 T の定数倍を除いた単射性）の証明中の
// 「核が中心に一致する」という 1 点だけであり、そこは
// 「g x g^{-1} = g' x g'^{-1} と (g^{-1}g') x = x (g^{-1}g') が同値」と書き換えて
// centralizer_is_scalar を当てることで、群論の語彙を使わずに書き直した。

export default defineNotes([
  {
    id: "note_TV1_hatZ_hatY_007_definition_automorphism_groups",
    targets: ["injectivity_of_T_up_to_scalar"],
    title: { text: "自己同型群・内部自己同型群・外部自己同型群" },
    sourcePath: "_old/typst/parts/008_T_V1_hatZとhatZ_hatYの関係/006_definition_自己同型群_内部自己同型群_外部自己同型群.typ",
    body: [
      paragraph([
        "【ゴールに照らして本文には採用しなかった】理由: 高校生の読者が Ising 模型の本筋に入る前に、群・正規部分群・商群・完全列を通過させられるため。実際に必要だった 1 点（共役写像 ",
        math(String.raw`T`),
        " が定数倍を除いて単射であること）は、",
        ref("centralizer_is_scalar"),
        "（すべての元と可換な元はスカラー倍の単位行列に限る）を直接当てるだけで書けた（",
        ref("injectivity_of_T_up_to_scalar"),
        "）。",
      ]),
      paragraph(["群 ", math(String.raw`G`), " について、"]),
      displayMath(
        String.raw`\mathrm{Aut}(G) := \{\varphi \mid \varphi : G \to G,\; \varphi \text{ は群同型}\}`,
      ),
      paragraph([
        "を ",
        math(String.raw`G`),
        " の自己同型群という。ここで「",
        math(String.raw`\varphi`),
        " は群同型」とは、",
        math(String.raw`\varphi`),
        " が全単射かつ ",
        math(String.raw`\forall h_1, h_2 \in G,\ \varphi(h_1 h_2) = \varphi(h_1)\varphi(h_2)`),
        " を満たすことをいう。",
        math(String.raw`\mathrm{Aut}(G)`),
        " は写像の合成 ",
        math(String.raw`\circ`),
        " について群をなす：合成は結合的、",
        math(String.raw`\mathrm{id}_G \in \mathrm{Aut}(G)`),
        " が単位元、",
        math(String.raw`\varphi \in \mathrm{Aut}(G)`),
        " の逆写像 ",
        math(String.raw`\varphi^{-1}`),
        " も全単射で ",
        math(String.raw`\varphi^{-1}(h_1 h_2) = \varphi^{-1}(h_1)\varphi^{-1}(h_2)`),
        "（",
        math(String.raw`\varphi`),
        " を両辺に施すと ",
        math(String.raw`h_1h_2 = h_1h_2`),
        " に帰着）なので ",
        math(String.raw`\varphi^{-1} \in \mathrm{Aut}(G)`),
        " が逆元、また ",
        math(String.raw`\varphi_1, \varphi_2 \in \mathrm{Aut}(G)`),
        " について ",
        math(String.raw`\varphi_1\circ\varphi_2`),
        " も全単射かつ準同型なので ",
        math(String.raw`\circ`),
        " は ",
        math(String.raw`\mathrm{Aut}(G)`),
        " 上の演算になる。",
      ]),
      paragraph([
        math(String.raw`g \in G`),
        " について ",
        math(String.raw`\varphi_g : G \to G,\; h \mapsto ghg^{-1}`),
        " と定め、",
        math(String.raw`\varphi : G \to \mathrm{Aut}(G),\; g \mapsto \varphi_g`),
        " の像 ",
        math(String.raw`\mathrm{Im}(\varphi)`),
        " を内部自己同型群 ",
        math(String.raw`\mathrm{Inn}(G)`),
        " という。",
      ]),
      displayMath(
        String.raw`\mathrm{Out}(G) := \mathrm{Aut}(G)/\mathrm{Inn}(G) \quad \text{（外部自己同型群）}`,
      ),
      paragraph([
        "この商が群として定義できること（",
        math(String.raw`\mathrm{Inn}(G) \trianglelefteq \mathrm{Aut}(G)`),
        "、すなわち ",
        math(String.raw`\mathrm{Inn}(G)`),
        " が ",
        math(String.raw`\mathrm{Aut}(G)`),
        " の正規部分群であること）は ",
        "本ノート「Inn(G) は Aut(G) の正規部分群」",
        " による。",
      ]),
      paragraph(["（本文からノートへ移す前の変換記録）"]),
      paragraph(["原文は Aut(G) の群構造・Inn(G) の正規性に触れていないが、Out(G) := Aut(G)/Inn(G) が群として定義できるために必要なので statement へ書き足した（正しさに必要ならそれは注記ではない）。正規性の証明は inn_is_normal_in_aut に置いた。"]),
    ],
  },
  {
    id: "note_TV1_hatZ_hatY_007a_definition_group_hom_ker_im",
    targets: ["injectivity_of_T_up_to_scalar"],
    title: { text: "群準同型・核・像" },
    sourcePath: "structured-latex/content/008_TV1_hatZ_hatY_part1.ts",
    body: [
      paragraph([
        "【ゴールに照らして本文には採用しなかった】理由: 高校生の読者が Ising 模型の本筋に入る前に、群・正規部分群・商群・完全列を通過させられるため。実際に必要だった 1 点（共役写像 ",
        math(String.raw`T`),
        " が定数倍を除いて単射であること）は、",
        ref("centralizer_is_scalar"),
        "（すべての元と可換な元はスカラー倍の単位行列に限る）を直接当てるだけで書けた（",
        ref("injectivity_of_T_up_to_scalar"),
        "）。",
      ]),
      paragraph([
        "群 ",
        math(String.raw`G, H`),
        " について、写像 ",
        math(String.raw`f : G \to H`),
        " が",
      ]),
      displayMath(
        String.raw`\forall g_1, g_2 \in G,\quad f(g_1 g_2) = f(g_1) f(g_2)`,
      ),
      paragraph([
        "を満たすとき ",
        math(String.raw`f`),
        " を群準同型という。このとき ",
        math(String.raw`e_G \in G`),
        "、",
        math(String.raw`e_H \in H`),
        " をそれぞれの単位元として ",
        math(String.raw`f(e_G) = e_H`),
        " および ",
        math(String.raw`\forall g \in G,\ f(g^{-1}) = f(g)^{-1}`),
        " が成り立つ（前者は ",
        math(String.raw`f(e_G) = f(e_Ge_G) = f(e_G)f(e_G)`),
        " の両辺に ",
        math(String.raw`f(e_G)^{-1}`),
        " を掛けて得られ、後者は ",
        math(String.raw`f(g)f(g^{-1}) = f(gg^{-1}) = f(e_G) = e_H`),
        " による）。",
      ]),
      paragraph([
        "群準同型 ",
        math(String.raw`f : G \to H`),
        " について、",
      ]),
      displayMath(
        String.raw`\mathrm{Ker}(f) := \{g \in G \mid f(g) = e_H\} \subseteq G,
\qquad
\mathrm{Im}(f) := \{f(g) \mid g \in G\} \subseteq H`,
      ),
      paragraph([
        "をそれぞれ ",
        math(String.raw`f`),
        " の核・像という。",
        math(String.raw`\mathrm{Ker}(f)`),
        " は ",
        math(String.raw`G`),
        " の正規部分群であり、",
        math(String.raw`\mathrm{Im}(f)`),
        " は ",
        math(String.raw`H`),
        " の部分群である。",
      ]),
      paragraph([
        "また ",
        math(String.raw`f`),
        " が単射であることと ",
        math(String.raw`\mathrm{Ker}(f) = \{e_G\}`),
        " であることは同値である。",
      ]),
      paragraph([
        math(String.raw`\mathrm{Ker}(f)`),
        " が部分群であること：",
        math(String.raw`f(e_G) = e_H`),
        " より ",
        math(String.raw`e_G \in \mathrm{Ker}(f)`),
        "。",
        math(String.raw`g_1, g_2 \in \mathrm{Ker}(f)`),
        " なら ",
        math(String.raw`f(g_1g_2) = f(g_1)f(g_2) = e_He_H = e_H`),
        " より ",
        math(String.raw`g_1g_2 \in \mathrm{Ker}(f)`),
        "。",
        math(String.raw`g \in \mathrm{Ker}(f)`),
        " なら ",
        math(String.raw`f(g^{-1}) = f(g)^{-1} = e_H^{-1} = e_H`),
        " より ",
        math(String.raw`g^{-1} \in \mathrm{Ker}(f)`),
        "。",
      ]),
      paragraph([
        math(String.raw`\mathrm{Ker}(f)`),
        " が正規であること：",
        math(String.raw`g \in G`),
        "、",
        math(String.raw`k \in \mathrm{Ker}(f)`),
        " について",
      ]),
      displayMath(
        String.raw`f(gkg^{-1}) = f(g)f(k)f(g^{-1}) = f(g)\,e_H\,f(g)^{-1} = f(g)f(g)^{-1} = e_H`,
      ),
      paragraph([
        "より ",
        math(String.raw`gkg^{-1} \in \mathrm{Ker}(f)`),
        "、すなわち ",
        math(String.raw`g\,\mathrm{Ker}(f)\,g^{-1} \subseteq \mathrm{Ker}(f)`),
        "。これが任意の ",
        math(String.raw`g`),
        " について成り立つので ",
        math(String.raw`g^{-1}`),
        " に適用して ",
        math(String.raw`g^{-1}\mathrm{Ker}(f)g \subseteq \mathrm{Ker}(f)`),
        " すなわち ",
        math(String.raw`\mathrm{Ker}(f) \subseteq g\,\mathrm{Ker}(f)\,g^{-1}`),
        " も得られ、",
        math(String.raw`g\,\mathrm{Ker}(f)\,g^{-1} = \mathrm{Ker}(f)`),
        "。",
      ]),
      paragraph([
        math(String.raw`\mathrm{Im}(f)`),
        " が部分群であること：",
        math(String.raw`e_H = f(e_G) \in \mathrm{Im}(f)`),
        "、",
        math(String.raw`f(g_1)f(g_2) = f(g_1g_2) \in \mathrm{Im}(f)`),
        "、",
        math(String.raw`f(g)^{-1} = f(g^{-1}) \in \mathrm{Im}(f)`),
        "。",
      ]),
      paragraph([
        "単射性との同値：",
        math(String.raw`f`),
        " が単射なら、",
        math(String.raw`g \in \mathrm{Ker}(f)`),
        " について ",
        math(String.raw`f(g) = e_H = f(e_G)`),
        " より ",
        math(String.raw`g = e_G`),
        "。逆に ",
        math(String.raw`\mathrm{Ker}(f) = \{e_G\}`),
        " のとき ",
        math(String.raw`f(g_1) = f(g_2)`),
        " なら ",
        math(String.raw`f(g_1g_2^{-1}) = f(g_1)f(g_2)^{-1} = e_H`),
        " より ",
        math(String.raw`g_1g_2^{-1} \in \mathrm{Ker}(f) = \{e_G\}`),
        "、よって ",
        math(String.raw`g_1 = g_2`),
        "。",
      ]),
      paragraph(["（本文からノートへ移す前の変換記録）"]),
      paragraph(["原文（parts/008/007）は「TODO: Ker, Im の定義」とのみ書いて定義を欠いていたため、完全列の主張に必要な定義と基本性質を新規に書き起こした。"]),
    ],
  },
  {
    id: "note_TV1_hatZ_hatY_007b_definition_center_of_group",
    targets: ["injectivity_of_T_up_to_scalar"],
    title: { text: "群の中心" },
    sourcePath: "structured-latex/content/008_TV1_hatZ_hatY_part1.ts",
    body: [
      paragraph([
        "【ゴールに照らして本文には採用しなかった】理由: 高校生の読者が Ising 模型の本筋に入る前に、群・正規部分群・商群・完全列を通過させられるため。実際に必要だった 1 点（共役写像 ",
        math(String.raw`T`),
        " が定数倍を除いて単射であること）は、",
        ref("centralizer_is_scalar"),
        "（すべての元と可換な元はスカラー倍の単位行列に限る）を直接当てるだけで書けた（",
        ref("injectivity_of_T_up_to_scalar"),
        "）。",
      ]),
      paragraph(["群 ", math(String.raw`G`), " について、"]),
      displayMath(
        String.raw`Z(G) := \{g \in G \mid \forall h \in G,\ gh = hg\} \subseteq G`,
      ),
      paragraph([
        "を ",
        math(String.raw`G`),
        " の中心という。",
        math(String.raw`Z(G)`),
        " は ",
        math(String.raw`G`),
        " の正規部分群である。",
      ]),
      paragraph([
        "部分群であること：",
        math(String.raw`e_G h = h = h e_G`),
        " より ",
        math(String.raw`e_G \in Z(G)`),
        "。",
        math(String.raw`g_1, g_2 \in Z(G)`),
        " について ",
        math(String.raw`(g_1g_2)h = g_1(g_2h) = g_1(hg_2) = (g_1h)g_2 = (hg_1)g_2 = h(g_1g_2)`),
        " より ",
        math(String.raw`g_1g_2 \in Z(G)`),
        "。",
        math(String.raw`g \in Z(G)`),
        " について ",
        math(String.raw`gh = hg`),
        " の両辺に左右から ",
        math(String.raw`g^{-1}`),
        " を掛けて ",
        math(String.raw`hg^{-1} = g^{-1}h`),
        " を得るので ",
        math(String.raw`g^{-1} \in Z(G)`),
        "。",
      ]),
      paragraph([
        "正規であること：",
        math(String.raw`g \in Z(G)`),
        "、",
        math(String.raw`h \in G`),
        " について ",
        math(String.raw`hgh^{-1} = ghh^{-1} = g \in Z(G)`),
        "。よって ",
        math(String.raw`hZ(G)h^{-1} = Z(G)`),
        "。",
      ]),
      paragraph(["（本文からノートへ移す前の変換記録）"]),
      paragraph(["原文（parts/008/007）は「TODO: Z(G) の定義」とのみ書いていたため新規に書き起こした。"]),
    ],
  },
  {
    id: "note_TV1_hatZ_hatY_007c_claim_inn_normal_in_aut",
    targets: ["injectivity_of_T_up_to_scalar"],
    title: { tex: String.raw`\mathrm{Inn}(G) \trianglelefteq \mathrm{Aut}(G)` },
    sourcePath: "structured-latex/content/008_TV1_hatZ_hatY_part1.ts",
    body: [
      paragraph([
        "【ゴールに照らして本文には採用しなかった】理由: 高校生の読者が Ising 模型の本筋に入る前に、群・正規部分群・商群・完全列を通過させられるため。実際に必要だった 1 点（共役写像 ",
        math(String.raw`T`),
        " が定数倍を除いて単射であること）は、",
        ref("centralizer_is_scalar"),
        "（すべての元と可換な元はスカラー倍の単位行列に限る）を直接当てるだけで書けた（",
        ref("injectivity_of_T_up_to_scalar"),
        "）。",
      ]),
      paragraph([
        "群 ",
        math(String.raw`G`),
        " について、",
        "本ノート「自己同型群・内部自己同型群・外部自己同型群」",
        " の ",
        math(String.raw`\varphi_g : G \to G,\ h \mapsto ghg^{-1}`),
        " と ",
        math(String.raw`\varphi : G \to \mathrm{Aut}(G),\ g \mapsto \varphi_g`),
        " について次が成り立つ。",
      ]),
      list([
        [
          "(i) 各 ",
          math(String.raw`g \in G`),
          " について ",
          math(String.raw`\varphi_g \in \mathrm{Aut}(G)`),
          "（すなわち ",
          math(String.raw`\varphi`),
          " は ",
          math(String.raw`\mathrm{Aut}(G)`),
          " へ値をとる）。",
        ],
        [
          "(ii) ",
          math(String.raw`\varphi`),
          " は群準同型である。したがって ",
          math(String.raw`\mathrm{Inn}(G) = \mathrm{Im}(\varphi)`),
          " は ",
          math(String.raw`\mathrm{Aut}(G)`),
          " の部分群である。",
        ],
        [
          "(iii) ",
          math(String.raw`\forall \psi \in \mathrm{Aut}(G),\ \forall g \in G,\quad \psi\circ\varphi_g\circ\psi^{-1} = \varphi_{\psi(g)}`),
          "。したがって ",
          math(String.raw`\mathrm{Inn}(G) \trianglelefteq \mathrm{Aut}(G)`),
          " であり、商群 ",
          math(String.raw`\mathrm{Out}(G) = \mathrm{Aut}(G)/\mathrm{Inn}(G)`),
          " が定義できる。",
        ],
      ]),
      paragraph([
        "(i) ",
        math(String.raw`\varphi_g`),
        " が準同型であること：",
        math(String.raw`h_1, h_2 \in G`),
        " について",
      ]),
      displayMath(
        String.raw`\varphi_g(h_1 h_2) = g h_1 h_2 g^{-1}
= g h_1 \left(g^{-1} g\right) h_2 g^{-1}
= \left(g h_1 g^{-1}\right)\left(g h_2 g^{-1}\right)
= \varphi_g(h_1)\,\varphi_g(h_2)`,
      ),
      paragraph([
        "全単射であること：",
        math(String.raw`\varphi_{g^{-1}}(\varphi_g(h)) = g^{-1}(ghg^{-1})g = h`),
        " および ",
        math(String.raw`\varphi_g(\varphi_{g^{-1}}(h)) = g(g^{-1}hg)g^{-1} = h`),
        " より ",
        math(String.raw`\varphi_{g^{-1}}`),
        " が ",
        math(String.raw`\varphi_g`),
        " の逆写像であり、逆写像をもつ写像は全単射である。よって ",
        math(String.raw`\varphi_g \in \mathrm{Aut}(G)`),
        "。",
      ]),
      paragraph([
        "(ii) ",
        math(String.raw`g_1, g_2 \in G`),
        " と任意の ",
        math(String.raw`h \in G`),
        " について",
      ]),
      displayMath(
        String.raw`\varphi_{g_1 g_2}(h) = (g_1g_2)h(g_1g_2)^{-1}
= g_1 g_2 h g_2^{-1} g_1^{-1}
= g_1\left(\varphi_{g_2}(h)\right)g_1^{-1}
= \varphi_{g_1}\!\left(\varphi_{g_2}(h)\right)
= \left(\varphi_{g_1}\circ\varphi_{g_2}\right)(h)`,
      ),
      paragraph([
        "（2 番目の等号で ",
        math(String.raw`(g_1g_2)^{-1} = g_2^{-1}g_1^{-1}`),
        " を用いた。）",
        math(String.raw`h`),
        " は任意なので ",
        math(String.raw`\varphi(g_1g_2) = \varphi_{g_1g_2} = \varphi_{g_1}\circ\varphi_{g_2} = \varphi(g_1)\circ\varphi(g_2)`),
        "、すなわち ",
        math(String.raw`\varphi`),
        " は群準同型である。",
        "本ノート「群準同型・核・像」",
        " より ",
        math(String.raw`\mathrm{Im}(\varphi) = \mathrm{Inn}(G)`),
        " は ",
        math(String.raw`\mathrm{Aut}(G)`),
        " の部分群である。",
      ]),
      paragraph([
        "(iii) ",
        math(String.raw`\psi \in \mathrm{Aut}(G)`),
        "、",
        math(String.raw`g \in G`),
        "、任意の ",
        math(String.raw`h \in G`),
        " について、",
      ]),
      displayMath(
        String.raw`\begin{aligned}
\left(\psi\circ\varphi_g\circ\psi^{-1}\right)(h)
&= \psi\!\left(\varphi_g\!\left(\psi^{-1}(h)\right)\right) \\
&= \psi\!\left(g\,\psi^{-1}(h)\,g^{-1}\right) \\
&= \psi(g)\,\psi\!\left(\psi^{-1}(h)\right)\,\psi\!\left(g^{-1}\right)
   \quad (\because \psi \text{ は準同型}) \\
&= \psi(g)\,h\,\psi(g)^{-1}
   \quad (\because \psi\circ\psi^{-1} = \mathrm{id}_G,\ \psi(g^{-1}) = \psi(g)^{-1}) \\
&= \varphi_{\psi(g)}(h)
\end{aligned}`,
      ),
      paragraph([
        math(String.raw`h`),
        " は任意なので ",
        math(String.raw`\psi\circ\varphi_g\circ\psi^{-1} = \varphi_{\psi(g)} \in \mathrm{Inn}(G)`),
        "。よって ",
        math(String.raw`\psi\,\mathrm{Inn}(G)\,\psi^{-1} \subseteq \mathrm{Inn}(G)`),
        " が任意の ",
        math(String.raw`\psi \in \mathrm{Aut}(G)`),
        " について成り立ち、",
        math(String.raw`\psi^{-1} \in \mathrm{Aut}(G)`),
        " へ適用して逆向きの包含も得られるので ",
        math(String.raw`\psi\,\mathrm{Inn}(G)\,\psi^{-1} = \mathrm{Inn}(G)`),
        "、すなわち ",
        math(String.raw`\mathrm{Inn}(G) \trianglelefteq \mathrm{Aut}(G)`),
        "。正規部分群による商集合には ",
        math(String.raw`(\psi_1\mathrm{Inn}(G))(\psi_2\mathrm{Inn}(G)) := (\psi_1\circ\psi_2)\mathrm{Inn}(G)`),
        " で well-defined な群構造が入るので ",
        math(String.raw`\mathrm{Out}(G)`),
        " は群である。",
      ]),
      paragraph(["（本文からノートへ移す前の変換記録）"]),
      paragraph(["原文には無いが、原文の Out(G) := Aut(G)/Inn(G) が群として定義できるために必要な事実（Inn(G) の正規性）と、完全列の証明で使う φ の準同型性をまとめて新規に書き起こした。"]),
    ],
  },
  {
    id: "note_TV1_hatZ_hatY_007d_definition_exact_sequence",
    targets: ["injectivity_of_T_up_to_scalar"],
    title: { text: "群の完全列" },
    sourcePath: "structured-latex/content/008_TV1_hatZ_hatY_part1.ts",
    body: [
      paragraph([
        "【ゴールに照らして本文には採用しなかった】理由: 高校生の読者が Ising 模型の本筋に入る前に、群・正規部分群・商群・完全列を通過させられるため。実際に必要だった 1 点（共役写像 ",
        math(String.raw`T`),
        " が定数倍を除いて単射であること）は、",
        ref("centralizer_is_scalar"),
        "（すべての元と可換な元はスカラー倍の単位行列に限る）を直接当てるだけで書けた（",
        ref("injectivity_of_T_up_to_scalar"),
        "）。",
      ]),
      paragraph([
        "群の列と群準同型の列",
      ]),
      displayMath(
        String.raw`G_0 \xrightarrow{f_1} G_1 \xrightarrow{f_2} G_2 \to \cdots \to G_{n-1} \xrightarrow{f_n} G_n`,
      ),
      paragraph([
        "が完全列であるとは、各中間の添字 ",
        math(String.raw`k \in \{1,\dots,n-1\}`),
        " について",
      ]),
      displayMath(String.raw`\mathrm{Im}(f_k) = \mathrm{Ker}(f_{k+1})`),
      paragraph([
        "（",
        "本ノート「群準同型・核・像」",
        " の像と核）が ",
        math(String.raw`G_k`),
        " の部分集合として成り立つことをいう。この条件が成り立つとき「",
        math(String.raw`G_k`),
        " で完全である」という。",
      ]),
      paragraph([
        "記号 ",
        math(String.raw`1`),
        " は単位元のみからなる自明群 ",
        math(String.raw`\{e\}`),
        " を表し、",
        math(String.raw`1 \to G`),
        " と ",
        math(String.raw`G \to 1`),
        " はそれぞれ一意に定まる群準同型（前者は ",
        math(String.raw`e \mapsto e_G`),
        "、後者は ",
        math(String.raw`g \mapsto e`),
        "）を表す。したがって",
      ]),
      list([
        [
          math(String.raw`1 \to G_1 \xrightarrow{f} G_2`),
          " が ",
          math(String.raw`G_1`),
          " で完全 ",
          math(String.raw`\iff \mathrm{Ker}(f) = \mathrm{Im}(1 \to G_1) = \{e_{G_1}\} \iff f`),
          " は単射（",
          "本ノート「群準同型・核・像」",
          "）",
        ],
        [
          math(String.raw`G_1 \xrightarrow{f} G_2 \to 1`),
          " が ",
          math(String.raw`G_2`),
          " で完全 ",
          math(String.raw`\iff \mathrm{Im}(f) = \mathrm{Ker}(G_2 \to 1) = G_2 \iff f`),
          " は全射",
        ],
      ]),
      paragraph(["（本文からノートへ移す前の変換記録）"]),
      paragraph(["原文（parts/008/007）は「TODO: 完全列の定義」とのみ書いていたため新規に書き起こした。両端の 1 の扱い（単射性・全射性への読み替え）も明示した。"]),
    ],
  },
  {
    id: "note_TV1_hatZ_hatY_008_definition_exact_sequence_aut",
    targets: ["injectivity_of_T_up_to_scalar"],
    title: { text: "自己同型群の完全列" },
    sourcePath: "_old/typst/parts/008_T_V1_hatZとhatZ_hatYの関係/007_definition_自己同型群の完全列.typ",
    body: [
      paragraph([
        "【ゴールに照らして本文には採用しなかった】理由: 高校生の読者が Ising 模型の本筋に入る前に、群・正規部分群・商群・完全列を通過させられるため。実際に必要だった 1 点（共役写像 ",
        math(String.raw`T`),
        " が定数倍を除いて単射であること）は、",
        ref("centralizer_is_scalar"),
        "（すべての元と可換な元はスカラー倍の単位行列に限る）を直接当てるだけで書けた（",
        ref("injectivity_of_T_up_to_scalar"),
        "）。",
      ]),
      paragraph([
        "群 ",
        math(String.raw`G`),
        " について、",
        "本ノート「群の中心」",
        " の中心 ",
        math(String.raw`Z(G)`),
        "、",
        "本ノート「自己同型群・内部自己同型群・外部自己同型群」",
        " の ",
        math(String.raw`\mathrm{Aut}(G), \mathrm{Inn}(G), \mathrm{Out}(G)`),
        " をとる。準同型を",
      ]),
      list([
        [
          math(String.raw`\iota : Z(G) \to G,\ g \mapsto g`),
          "（包含写像）",
        ],
        [
          math(String.raw`\varphi : G \to \mathrm{Aut}(G),\ g \mapsto \varphi_g`),
          "（",
          math(String.raw`\varphi_g(h) := ghg^{-1}`),
          "。",
          "本ノート「Inn(G) は Aut(G) の正規部分群」",
          " (i)(ii) によりこれは ",
          math(String.raw`\mathrm{Aut}(G)`),
          " への群準同型）",
        ],
        [
          math(String.raw`\pi : \mathrm{Aut}(G) \to \mathrm{Out}(G),\ \psi \mapsto \psi\,\mathrm{Inn}(G)`),
          "（商写像）",
        ],
      ]),
      paragraph(["と定めるとき、"]),
      displayMath(
        String.raw`1 \to Z(G) \xrightarrow{\ \iota\ } G \xrightarrow{\ \varphi\ } \mathrm{Aut}(G) \xrightarrow{\ \pi\ } \mathrm{Out}(G) \to 1`,
      ),
      paragraph([
        "は ",
        "本ノート「群の完全列」",
        " の意味で完全列をなす。すなわち ",
        math(String.raw`Z(G)`),
        "、",
        math(String.raw`G`),
        "、",
        math(String.raw`\mathrm{Aut}(G)`),
        "、",
        math(String.raw`\mathrm{Out}(G)`),
        " の 4 箇所すべてで完全である。",
      ]),
      paragraph([
        "まず ",
        math(String.raw`\iota`),
        " と ",
        math(String.raw`\pi`),
        " が群準同型であることを確認する。",
        math(String.raw`Z(G)`),
        " は ",
        math(String.raw`G`),
        " の部分群（",
        "本ノート「群の中心」",
        "）で ",
        math(String.raw`\iota(g_1g_2) = g_1g_2 = \iota(g_1)\iota(g_2)`),
        " だから ",
        math(String.raw`\iota`),
        " は群準同型。",
        math(String.raw`\mathrm{Inn}(G) \trianglelefteq \mathrm{Aut}(G)`),
        "（",
        "本ノート「Inn(G) は Aut(G) の正規部分群」",
        " (iii)）より商群 ",
        math(String.raw`\mathrm{Out}(G)`),
        " の演算は ",
        math(String.raw`(\psi_1\mathrm{Inn}(G))(\psi_2\mathrm{Inn}(G)) = (\psi_1\circ\psi_2)\mathrm{Inn}(G)`),
        " で定義されるので ",
        math(String.raw`\pi(\psi_1\circ\psi_2) = (\psi_1\circ\psi_2)\mathrm{Inn}(G) = \pi(\psi_1)\pi(\psi_2)`),
        "、すなわち ",
        math(String.raw`\pi`),
        " は群準同型。",
        math(String.raw`\varphi`),
        " が群準同型であることは ",
        "本ノート「Inn(G) は Aut(G) の正規部分群」",
        " (ii) による。",
      ]),

      paragraph([
        "(1) ",
        math(String.raw`Z(G)`),
        " での完全性：",
        math(String.raw`\mathrm{Im}(1 \to Z(G)) = \mathrm{Ker}(\iota)`),
        " を示す。",
      ]),
      paragraph([
        "左辺は自明群の像なので ",
        math(String.raw`\{e_G\}`),
        "（",
        math(String.raw`e_G`),
        " は ",
        math(String.raw`G`),
        " の単位元であり ",
        math(String.raw`Z(G)`),
        " の単位元でもある）。右辺は",
      ]),
      displayMath(
        String.raw`\mathrm{Ker}(\iota) = \{g \in Z(G) \mid \iota(g) = e_G\} = \{g \in Z(G) \mid g = e_G\} = \{e_G\}`,
      ),
      paragraph([
        "であり一致する。これは ",
        "本ノート「群の完全列」",
        " により ",
        math(String.raw`\iota`),
        " が単射であることと同値であり、実際 ",
        math(String.raw`\iota(g_1) = \iota(g_2) \Rightarrow g_1 = g_2`),
        " である。",
      ]),

      paragraph([
        "(2) ",
        math(String.raw`G`),
        " での完全性：",
        math(String.raw`\mathrm{Im}(\iota) = \mathrm{Ker}(\varphi)`),
        " を示す。",
      ]),
      paragraph([
        math(String.raw`\mathrm{Im}(\iota) = \{\iota(g) \mid g \in Z(G)\} = Z(G)`),
        " である。一方 ",
        math(String.raw`\mathrm{Aut}(G)`),
        " の単位元は ",
        math(String.raw`\mathrm{id}_G`),
        " なので、",
      ]),
      displayMath(
        String.raw`\begin{aligned}
\mathrm{Ker}(\varphi)
&= \{g \in G \mid \varphi_g = \mathrm{id}_G\} \\
&= \{g \in G \mid \forall h \in G,\ \varphi_g(h) = h\}
   \quad (\because \text{写像の相等は各点での値の相等}) \\
&= \{g \in G \mid \forall h \in G,\ ghg^{-1} = h\} \\
&= \{g \in G \mid \forall h \in G,\ gh = hg\}
   \quad (\because ghg^{-1} = h \iff gh = hg\ (\text{両辺に右から } g)) \\
&= Z(G)
   \quad (\because \text{中心の定義})
\end{aligned}`,
      ),
      paragraph([
        "よって ",
        math(String.raw`\mathrm{Im}(\iota) = Z(G) = \mathrm{Ker}(\varphi)`),
        "。",
      ]),

      paragraph([
        "(3) ",
        math(String.raw`\mathrm{Aut}(G)`),
        " での完全性：",
        math(String.raw`\mathrm{Im}(\varphi) = \mathrm{Ker}(\pi)`),
        " を示す。",
      ]),
      paragraph([
        math(String.raw`\mathrm{Im}(\varphi) = \mathrm{Inn}(G)`),
        " は ",
        "本ノート「自己同型群・内部自己同型群・外部自己同型群」",
        " の ",
        math(String.raw`\mathrm{Inn}(G)`),
        " の定義そのものである。一方 ",
        math(String.raw`\mathrm{Out}(G)`),
        " の単位元は剰余類 ",
        math(String.raw`\mathrm{Inn}(G) = \mathrm{id}_G\,\mathrm{Inn}(G)`),
        " なので、",
      ]),
      displayMath(
        String.raw`\begin{aligned}
\mathrm{Ker}(\pi)
&= \{\psi \in \mathrm{Aut}(G) \mid \pi(\psi) = \mathrm{Inn}(G)\} \\
&= \{\psi \in \mathrm{Aut}(G) \mid \psi\,\mathrm{Inn}(G) = \mathrm{Inn}(G)\} \\
&= \{\psi \in \mathrm{Aut}(G) \mid \psi \in \mathrm{Inn}(G)\}
= \mathrm{Inn}(G)
\end{aligned}`,
      ),
      paragraph([
        "最後の等号は次による。",
        math(String.raw`\psi\,\mathrm{Inn}(G) = \mathrm{Inn}(G)`),
        " なら ",
        math(String.raw`\psi = \psi\circ\mathrm{id}_G \in \psi\,\mathrm{Inn}(G) = \mathrm{Inn}(G)`),
        "。逆に ",
        math(String.raw`\psi \in \mathrm{Inn}(G)`),
        " なら、",
        math(String.raw`\mathrm{Inn}(G)`),
        " が部分群であることから ",
        math(String.raw`\psi\,\mathrm{Inn}(G) \subseteq \mathrm{Inn}(G)`),
        " かつ、任意の ",
        math(String.raw`\chi \in \mathrm{Inn}(G)`),
        " について ",
        math(String.raw`\chi = \psi\circ(\psi^{-1}\circ\chi) \in \psi\,\mathrm{Inn}(G)`),
        "（",
        math(String.raw`\psi^{-1}\circ\chi \in \mathrm{Inn}(G)`),
        "）なので ",
        math(String.raw`\mathrm{Inn}(G) \subseteq \psi\,\mathrm{Inn}(G)`),
        "。よって ",
        math(String.raw`\mathrm{Ker}(\pi) = \mathrm{Inn}(G) = \mathrm{Im}(\varphi)`),
        "。",
      ]),

      paragraph([
        "(4) ",
        math(String.raw`\mathrm{Out}(G)`),
        " での完全性：",
        math(String.raw`\mathrm{Im}(\pi) = \mathrm{Ker}(\mathrm{Out}(G) \to 1)`),
        " を示す。",
      ]),
      paragraph([
        "右辺は ",
        math(String.raw`\mathrm{Out}(G)`),
        " のすべての元が自明群の単位元へ移るので ",
        math(String.raw`\mathrm{Out}(G)`),
        " 全体である。左辺は ",
        math(String.raw`\mathrm{Out}(G)`),
        " の任意の元が定義により ",
        math(String.raw`\psi\,\mathrm{Inn}(G)`),
        "（",
        math(String.raw`\psi \in \mathrm{Aut}(G)`),
        "）の形をしており ",
        math(String.raw`\psi\,\mathrm{Inn}(G) = \pi(\psi)`),
        " だから ",
        math(String.raw`\mathrm{Im}(\pi) = \mathrm{Out}(G)`),
        "（",
        math(String.raw`\pi`),
        " は全射）。よって両辺は一致する。",
      ]),
      paragraph([
        "(1)〜(4) により 4 箇所すべてで完全であり、主張の列は完全列である。",
      ]),
      paragraph(["（本文からノートへ移す前の変換記録）"]),
      paragraph(["原文（parts/008/007）は statement に「TODO: Ker, Im の定義、Z(G) の定義、完全列の定義」、proof に「TODO:」と書かれただけで中身が無かった。必要な定義を def_group_hom_ker_im / def_center_of_group / def_exact_sequence / inn_is_normal_in_aut として新規に追加し、4 箇所すべての完全性を証明して todo を除去した。"]),
      paragraph(["原文は kind が definition だが内容は主張（完全列をなす）である。原文の構造を保つため kind は definition のままとし、proof に証明を置いた。"]),
      paragraph(["この完全列そのものは、本文の他のブロックからは参照されていない（grep で確認：Aut / Out / Inn / 完全列 の語は本章のこの一連のブロックと、005_exp_conjugation_proof.ts の Ad : G → Aut(G) の記述にしか現れず、後者はこの完全列を使っていない）。ただし『T の（定数倍を除いた）単射性』（injectivity_of_T_up_to_scalar）の証明でこの完全列の (2) Ker(φ) = Z(G) の部分を使うため、削除せず本文に残している。"]),
    ],
  },
  {
    id: "note_TV1_hatZ_hatY_009_definition_ring_multiplicative_group",
    targets: ["injectivity_of_T_up_to_scalar"],
    title: { text: "環の乗法群" },
    sourcePath: "_old/typst/parts/008_T_V1_hatZとhatZ_hatYの関係/008_definition_環の乗法群.typ",
    body: [
      paragraph([
        "【ゴールに照らして本文には採用しなかった】理由: 一般の環についての定義であり、読者に環と群の定義を先に要求するため。本文で必要なのは ",
        math(String.raw`\mathrm{Mat}(2^M,\mathbb{C})`),
        " の可逆元だけなので、そこへ具体的に落とした ",
        ref("def_invertible_elements_of_R"),
        " を本文に置き、この一般の環についての記述はここへ退避した。",
      ]),
      paragraph(["環 ", math(String.raw`\mathbf{R} = (R, +_R, \cdot_R)`), " について、"]),
      displayMath(
        String.raw`\mathbf{R}^\times := \{r \in \mathbf{R} \mid r \text{ は } \cdot_R \text{ について可逆}\}`,
      ),
      paragraph([
        math(String.raw`\mathbf{R}^\times`),
        " は ",
        math(String.raw`\cdot_R`),
        " について群をなす。これを ",
        math(String.raw`\mathbf{R}`),
        " の乗法群という。",
      ]),
    ],
  },
]);
