

# This file was *autogenerated* from the file /Users/masaori/git/masaori/math/.claude/worktrees/reflective-fluttering-panda/exact-solution-of-2d-ising-model/sagemath/check/190_claim_exp_sum/check_02_geometric_series_path.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_0p0j = ComplexNumber(0, '0.0'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_0 = Integer(0); _sage_const_1en12 = RealNumber('1e-12')# exp_sum の proof (b) が使う等比数列の和の公式そのものを独立に検証する。
#   r := exp(2 pi i k / M) != 1 のとき  sum_{j=1}^{M} r^j = r (1 - r^M) / (1 - r) = 0
#
# 経路 A: r^j を 1 項ずつ足す（べき乗として計算。check_01 の exp(...) 直接評価とは別の計算経路）
# 経路 B: 等比級数の閉じた表示 r (1 - r^M) / (1 - r)
# 経路 C: 0
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '../../_shared/operators.sage'))

rep = CheckReport("exp_sum proof(b): 等比数列の和の公式と 0 への一致")

M_LIST = [_sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 , _sage_const_6 , _sage_const_7 , _sage_const_8 ]

for M in M_LIST:
    for k in range(-_sage_const_3  * int(M), _sage_const_3  * int(M) + _sage_const_1 ):
        r = _np.exp(_sage_const_1j  * _sage_const_2  * _np.pi * float(k) / float(M))
        # 経路 A: 累乗和
        powsum = _sage_const_0p0  + _sage_const_0p0j 
        p = _sage_const_1p0  + _sage_const_0p0j 
        for _ in range(int(M)):
            p = p * r
            powsum += p
        if (k % int(M)) == _sage_const_0 :
            # r = 1 なので公式は使えない。和は M になる。
            rep.close(powsum, float(M), "M=%d k=%d (r=1, 和=M)" % (M, k))
            rep.truth(abs(r - _sage_const_1p0 ) < _sage_const_1en12 , "M=%d k=%d で r=1" % (M, k))
        else:
            rep.truth(abs(r - _sage_const_1p0 ) > _sage_const_1en12 , "M=%d k=%d で r!=1（公式の適用条件）" % (M, k))
            # 経路 B: 閉じた表示
            closed = r * (_sage_const_1p0  - r ** int(M)) / (_sage_const_1p0  - r)
            rep.close(powsum, closed, "M=%d k=%d 累乗和 vs 等比公式" % (M, k))
            rep.close(closed, _sage_const_0p0 , "M=%d k=%d 等比公式の値が 0" % (M, k))

rep.finish()

