

# This file was *autogenerated* from the file check_01_negative.sage
from sage.all_cmdline import *   # import sage library

_sage_const_220 = Integer(220); _sage_const_1en12 = RealNumber('1e-12'); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_1e6 = RealNumber('1e6'); _sage_const_7 = Integer(7); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_40 = Integer(40); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)# <negative_number_to_sqrt>: x < 0 について x = -sqrt((-x)^2)
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
load(os.path.join(_dir, "_prelude.sage"))
import numpy as np
import math
rng = np.random.default_rng(int(_sage_const_220 ))
rep = CheckReport("negative_number_to_sqrt")
xs = [-_sage_const_1en12 , -_sage_const_1en6 , -_sage_const_0p5 , -_sage_const_1p0 , -_sage_const_2p0 , -_sage_const_1e6 ] + [-abs(float(rng.normal()))*_sage_const_7  - _sage_const_1en9  for _ in range(_sage_const_40 )]
for x in xs:
    rep.close(x, -sqrt_nonneg((-x)**_sage_const_2 ), f"x={x:.6e}: x = -sqrt((-x)^2)")
    rep.truth(-x > _sage_const_0 , f"x={x:.6e}: -x > 0（sqrt の定義域）")
    # 正の数では符号が逆になる（主張が x<0 に限られる理由）
    rep.close(-x, sqrt_nonneg((-x)**_sage_const_2 ), f"x={x:.6e}: -x = sqrt((-x)^2)")
rep.finish()

