import { defineBlocks, paragraph, math, displayMath, list, ref } from "../schema.ts";

const SRC = "structured-latex/content/012_free_energy.ts";

export default defineBlocks([
  {
    id: "heading_free_energy",
    kind: "heading",
    level: 2,
    sourcePath: SRC,
    sourceOrdinal: 1,
    title: { text: "自由エネルギーと熱力学極限" },
    labels: [],
    conversion: { status: "added" },
  },

  {
    id: "freeenergy_000_remark_escape_to_real_analysis",
    kind: "remark",
    sourcePath: SRC,
    sourceOrdinal: 2,
    title: { text: "実数解析へ移行するのはこの章のこの箇所だけである" },
    labels: ["remark_real_analysis_escape_point"],
    statement: [
      paragraph([
        "ここまでの章はすべて、複素数を成分とする有限サイズの行列の積・和・スカラー倍と、",
        "行列の指数関数（",
        ref("def_exp"),
        "：ノルムについて収束する級数）だけで書かれてきた。",
        "実数の極限は使ったが、積分は一度も使っていない。",
      ]),
      paragraph([
        "**この章の ",
        ref("riemann_sum_to_integral"),
        " が、本証明で唯一、実数解析（Riemann 積分）へ移行する箇所である。**",
        "そこで外部から持ち込む事実は次の 2 つだけであり、他では使わない。",
      ]),
      list([
        [
          "(R1) **Heine–Cantor**：有界閉区間 ",
          math(String.raw`[a,b] \subset \mathbb{R}`),
          " 上の連続関数は一様連続である。すなわち ",
          math(String.raw`\forall\epsilon>0\ \exists\delta>0`),
          " が存在して ",
          math(String.raw`|s-t|\leq\delta \Rightarrow |g(s)-g(t)|\leq\epsilon`),
          "。",
        ],
        [
          "(R2) **連続関数の Riemann 可積分性**：",
          math(String.raw`[a,b]`),
          " 上の連続関数 ",
          math(String.raw`g`),
          " は Riemann 積分可能で、積分は区間についての加法性 ",
          math(String.raw`\int_a^c = \int_a^b + \int_b^c`),
          " と評価 ",
          math(String.raw`\left|\int_a^b g\right| \leq (b-a)\sup_{[a,b]}|g|`),
          "、および定数の積分 ",
          math(String.raw`\int_a^b \lambda\,dt = \lambda(b-a)`),
          " を満たす。",
        ],
      ]),
      paragraph([
        "移行が必要になる理由も明示しておく。",
        ref("partition_function_sandwich"),
        " と ",
        ref("limit_of_log_Z_in_N_row"),
        " により、鎖の長さ ",
        math(String.raw`M`),
        " を固定したままの量 ",
        math(String.raw`\frac{1}{M}\log c(M)`),
        " までは有限の行列計算で到達する。",
        "しかし ",
        math(String.raw`M \to \infty`),
        " で現れるのは ",
        math(String.raw`\frac{1}{M}\sum_{\mu=1}^{M}\gamma(\theta_\mu)`),
        " という**点の個数が増えていく有限和**であり、その極限を閉じた式で書くには",
        "「等間隔の点での値の平均が積分に収束する」という実数解析の事実が要る。",
        "ここだけは有限の代数計算では代用できない。",
      ]),
    ],
    conversion: { status: "added" },
  },

  {
    id: "freeenergy_001_claim_gamma1_lower_bound_all_theta",
    kind: "claim",
    sourcePath: SRC,
    sourceOrdinal: 3,
    title: { tex: String.raw`\gamma_1(\theta) \geq \cosh(2K_1 - 2K_2^*) \geq 1 \quad (\forall\theta\in\mathbb{R})` },
    labels: ["gamma1_lower_bound_all_theta"],
    statement: [
      paragraph([
        ref("def_A_theta"),
        " の ",
        math(String.raw`\gamma_1(\theta) = c_1c_2^* - s_1s_2^*\cos\theta`),
        " を**すべての実数** ",
        math(String.raw`\theta`),
        " について考える（",
        ref("gamma1_geq_1"),
        " は ",
        math(String.raw`\theta = \theta_\mu`),
        " の場合の主張だが、以下の評価は任意の実数 ",
        math(String.raw`\theta`),
        " で成り立つ）。このとき",
      ]),
      displayMath(
        String.raw`\gamma_1(\theta) \geq \cosh\left(2K_1 - 2K_2^*\right) \geq 1
\qquad (\forall \theta \in \mathbb{R})`,
      ),
      paragraph([
        "とくに ",
        math(String.raw`\gamma(\theta) := \mathrm{arccosh}\left(\gamma_1(\theta)\right) \in \mathbb{R}_{\geq 0}`),
        " が**すべての実数** ",
        math(String.raw`\theta`),
        " について定まる（",
        ref("def_gamma_theta_mu"),
        " の ",
        math(String.raw`\gamma(\theta_\mu)`),
        " の拡張）。",
      ]),
    ],
    proof: [
      paragraph([
        ref("cosh_sinh_basic_properties"),
        " の加法定理 ",
        math(String.raw`\cosh(x-y) = \cosh x\cosh y - \sinh x\sinh y`),
        " を ",
        math(String.raw`x = 2K_1`),
        "、",
        math(String.raw`y = 2K_2^*`),
        " に適用すると",
      ]),
      displayMath(
        String.raw`\cosh\left(2K_1-2K_2^*\right) = c_1c_2^* - s_1s_2^*`,
      ),
      paragraph([
        ref("def_transfer_matrix_symbols"),
        " より ",
        math(String.raw`K_1, K_2^* > 0`),
        " なので ",
        math(String.raw`s_1 = \sinh 2K_1 > 0`),
        "、",
        math(String.raw`s_2^* = \sinh 2K_2^* > 0`),
        "、したがって ",
        math(String.raw`s_1s_2^* > 0`),
        " である。また ",
        math(String.raw`\cos\theta \leq 1`),
        " なので",
      ]),
      displayMath(
        String.raw`\gamma_1(\theta) = c_1c_2^* - s_1s_2^*\cos\theta
\geq c_1c_2^* - s_1s_2^* = \cosh\left(2K_1-2K_2^*\right)`,
      ),
      paragraph([
        ref("cosh_sinh_basic_properties"),
        " より ",
        math(String.raw`\cosh x \geq 1`),
        " がすべての実数 ",
        math(String.raw`x`),
        " で成り立つので、",
        math(String.raw`\gamma_1(\theta) \geq 1`),
        "。",
        math(String.raw`\mathrm{arccosh}`),
        " は ",
        math(String.raw`[1,\infty)`),
        " 上で定義された（",
        math(String.raw`\cosh|_{[0,\infty)}`),
        " の逆写像としての）実数値関数なので ",
        math(String.raw`\gamma(\theta)`),
        " が定まり、値は ",
        math(String.raw`\mathbb{R}_{\geq 0}`),
        " に属する。",
      ]),
    ],
    conversion: { status: "added" },
  },

  {
    id: "freeenergy_002_claim_gamma_is_continuous",
    kind: "claim",
    sourcePath: SRC,
    sourceOrdinal: 4,
    title: { tex: String.raw`\gamma \text{ は } \mathbb{R} \text{ 上で連続}` },
    labels: ["gamma_is_continuous"],
    statement: [
      paragraph([
        ref("gamma1_lower_bound_all_theta"),
        " の ",
        math(String.raw`\gamma : \mathbb{R} \to \mathbb{R}_{\geq 0}`),
        " は連続であり、周期 ",
        math(String.raw`2\pi`),
        " をもつ：",
        math(String.raw`\gamma(\theta + 2\pi) = \gamma(\theta)`),
        "。",
      ]),
      paragraph([
        "これが ",
        ref("riemann_sum_to_integral"),
        " を適用するために実際に使う条件である。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 1（",
        math(String.raw`\gamma_1`),
        " の連続性と周期性）。",
        math(String.raw`\gamma_1(\theta) = c_1c_2^* - s_1s_2^*\cos\theta`),
        " は定数と ",
        math(String.raw`\cos`),
        " の 1 次式である。",
        math(String.raw`\cos`),
        " は ",
        math(String.raw`\mathbb{R}`),
        " 上連続で周期 ",
        math(String.raw`2\pi`),
        " をもつので、",
        math(String.raw`\gamma_1`),
        " も連続で周期 ",
        math(String.raw`2\pi`),
        " をもつ。",
      ]),
      paragraph([
        "Step 2（",
        math(String.raw`\mathrm{arccosh}`),
        " の連続性）。",
        math(String.raw`y \geq 1`),
        " について",
      ]),
      displayMath(
        String.raw`\mathrm{arccosh}(y) = \log\left(y + \sqrt{y^2-1}\right)`,
      ),
      paragraph([
        "である（右辺を ",
        math(String.raw`u`),
        " とおくと ",
        math(String.raw`e^{u} = y+\sqrt{y^2-1}`),
        "、",
        math(String.raw`e^{-u} = \dfrac{1}{y+\sqrt{y^2-1}} = y-\sqrt{y^2-1}`),
        "（分母の有理化）なので ",
        math(String.raw`\cosh u = \dfrac{e^u+e^{-u}}{2} = y`),
        "、かつ ",
        math(String.raw`y \geq 1`),
        " より ",
        math(String.raw`u \geq 0`),
        "）。",
        math(String.raw`y \mapsto y^2-1`),
        " は連続で ",
        math(String.raw`[1,\infty)`),
        " 上非負、非負実数の平方根は連続、",
        math(String.raw`y+\sqrt{y^2-1} \geq 1 > 0`),
        " 上で ",
        math(String.raw`\log`),
        " は連続なので、合成として ",
        math(String.raw`\mathrm{arccosh}`),
        " は ",
        math(String.raw`[1,\infty)`),
        " 上連続である。",
      ]),
      paragraph([
        "Step 3。",
        ref("gamma1_lower_bound_all_theta"),
        " より ",
        math(String.raw`\gamma_1(\mathbb{R}) \subseteq [1,\infty)`),
        " なので、連続写像の合成 ",
        math(String.raw`\gamma = \mathrm{arccosh}\circ\gamma_1`),
        " は ",
        math(String.raw`\mathbb{R}`),
        " 上連続である。周期性は ",
        math(String.raw`\gamma_1`),
        " の周期性から従う。",
      ]),
    ],
    conversion: { status: "added" },
  },

  {
    id: "freeenergy_003_claim_limit_in_N_row",
    kind: "claim",
    sourcePath: SRC,
    sourceOrdinal: 5,
    title: { tex: String.raw`N_{\mathrm{row}} \to \infty \text{ の極限}` },
    labels: ["limit_of_log_Z_in_N_row"],
    statement: [
      paragraph([
        math(String.raw`M \in \mathbb{Z}_{\geq 2}`),
        " を固定する。",
        ref("partition_function_sandwich"),
        " の ",
        math(String.raw`c(M)`),
        " について、極限",
      ]),
      displayMath(
        String.raw`\lim_{N_{\mathrm{row}} \to \infty}
\frac{1}{M\,N_{\mathrm{row}}}\log Z(J,J')
= \frac{1}{M}\log c(M)`,
      ),
      paragraph([
        "が存在する。すなわち、行数 ",
        math(String.raw`N_{\mathrm{row}}`),
        " についての極限は ",
        math(String.raw`c(M)`),
        " だけで決まる。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`Z := Z(J,J')`),
        "、",
        math(String.raw`c := c(M)`),
        "、",
        math(String.raw`N := N_{\mathrm{row}}`),
        " と略記する。",
        ref("def_partition_function_2d_ising"),
        " より ",
        math(String.raw`Z \in \mathbb{R}_{>0}`),
        "、",
        ref("def_rayleigh_sup"),
        " より ",
        math(String.raw`c > 0`),
        " なので、両者の ",
        math(String.raw`\log`),
        " が定まる。",
      ]),
      paragraph([
        ref("partition_function_sandwich"),
        " の ",
        math(String.raw`c^{N} \leq Z \leq 2^{M}c^{N}`),
        " に、",
        math(String.raw`\mathbb{R}_{>0}`),
        " 上で狭義単調増加な ",
        math(String.raw`\log`),
        " を施すと",
      ]),
      displayMath(
        String.raw`N\log c \ \leq\ \log Z \ \leq\ M\log 2 + N\log c`,
      ),
      paragraph([
        "（",
        math(String.raw`\log(ab) = \log a + \log b`),
        "、",
        math(String.raw`\log(c^N) = N\log c`),
        "、",
        math(String.raw`\log 2^M = M\log 2`),
        "）。各辺を ",
        math(String.raw`MN > 0`),
        " で割ると",
      ]),
      displayMath(
        String.raw`\frac{1}{M}\log c \ \leq\ \frac{1}{MN}\log Z \ \leq\ \frac{1}{M}\log c + \frac{\log 2}{N}`,
      ),
      paragraph([
        "したがって",
      ]),
      displayMath(
        String.raw`\left|\frac{1}{MN}\log Z - \frac{1}{M}\log c\right| \leq \frac{\log 2}{N}`,
      ),
      paragraph([
        "右辺は ",
        math(String.raw`N \to \infty`),
        " で ",
        math(String.raw`0`),
        " に収束する（",
        math(String.raw`\log 2`),
        " は ",
        math(String.raw`N`),
        " に依らない定数）。よって主張の極限が存在して値は ",
        math(String.raw`\frac1M\log c(M)`),
        " である。",
      ]),
      paragraph([
        "**この段階では実数解析へ移行していない**：使ったのは有限個の実数の不等式、",
        math(String.raw`\log`),
        " の単調性と乗法から加法への変換、および実数列 ",
        math(String.raw`(\log 2)/N \to 0`),
        " だけである。",
      ]),
    ],
    conversion: { status: "added" },
  },

  {
    id: "freeenergy_004_theorem_riemann_sum_to_integral",
    kind: "theorem",
    sourcePath: SRC,
    sourceOrdinal: 6,
    title: { text: "等間隔点の平均は積分に収束する（★実数解析への移行点）" },
    labels: ["riemann_sum_to_integral"],
    statement: [
      paragraph([
        "**本証明で実数解析（Riemann 積分）を使うのはこの主張だけである。**",
        "用いる外部事実は ",
        ref("remark_real_analysis_escape_point"),
        " の (R1)(R2) に限る。",
      ]),
      paragraph([
        math(String.raw`g : \mathbb{R} \to \mathbb{R}`),
        " を連続かつ周期 ",
        math(String.raw`2\pi`),
        " の関数とし、",
        math(String.raw`\delta \in [0,1)`),
        " を固定する。",
        math(String.raw`M \in \mathbb{Z}_{\geq 1}`),
        " に対して",
      ]),
      displayMath(
        String.raw`t^{(M)}_\mu := \frac{2\pi(\mu-\delta)}{M} \qquad (\mu = 1,\dots,M)`,
      ),
      paragraph(["とおく。このとき"]),
      displayMath(
        String.raw`\lim_{M\to\infty} \frac{1}{M}\sum_{\mu=1}^{M} g\!\left(t^{(M)}_\mu\right)
= \frac{1}{2\pi}\int_{0}^{2\pi} g(t)\,dt`,
      ),
      paragraph([
        "が成り立つ。より詳しく、",
        math(String.raw`g`),
        " の ",
        math(String.raw`[0,2\pi]`),
        " 上の連続度を",
      ]),
      displayMath(
        String.raw`\omega(h) := \sup\left\{\,|g(s)-g(t)| \ \middle|\ s,t \in [0,2\pi],\ |s-t| \leq h \,\right\}`,
      ),
      paragraph(["とおくと"]),
      displayMath(
        String.raw`\left|\frac{1}{M}\sum_{\mu=1}^{M} g\!\left(t^{(M)}_\mu\right)
- \frac{1}{2\pi}\int_{0}^{2\pi} g(t)\,dt\right|
\ \leq\ \omega\!\left(\frac{2\pi}{M}\right)`,
      ),
      paragraph([
        "であり、(R1) より ",
        math(String.raw`\omega(h) \to 0\ (h \to +0)`),
        " なので右辺は ",
        math(String.raw`0`),
        " に収束する。",
      ]),
      paragraph([
        "とくに ",
        math(String.raw`\delta = 0`),
        "（整数点 ",
        math(String.raw`2\pi\mu/M`),
        "）と ",
        math(String.raw`\delta = 1/2`),
        "（半整数点 ",
        math(String.raw`2\pi(\mu-\tfrac12)/M`),
        "）のどちらでも、極限は同じ値である。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 0（設定）。",
        math(String.raw`g`),
        " は ",
        math(String.raw`\mathbb{R}`),
        " 上連続なので、とくに有界閉区間 ",
        math(String.raw`[0,2\pi]`),
        " 上で連続であり、(R2) より ",
        math(String.raw`\int_0^{2\pi}g(t)\,dt`),
        " が定まる。",
        math(String.raw`M`),
        " を固定し",
      ]),
      displayMath(
        String.raw`I_\mu := \left[\frac{2\pi(\mu-1)}{M},\ \frac{2\pi\mu}{M}\right] \qquad (\mu = 1,\dots,M)`,
      ),
      paragraph([
        "とおく。これらは ",
        math(String.raw`[0,2\pi]`),
        " を長さ ",
        math(String.raw`2\pi/M`),
        " の ",
        math(String.raw`M`),
        " 個の区間に分割したものであり、(R2) の区間加法性より",
      ]),
      displayMath(
        String.raw`\int_0^{2\pi} g(t)\,dt = \sum_{\mu=1}^{M}\int_{I_\mu} g(t)\,dt`,
      ),
      paragraph([
        "Step 1（代表点が区間に入ること）。",
        math(String.raw`\delta \in [0,1)`),
        " より ",
        math(String.raw`0 < 1-\delta \leq 1`),
        " なので",
      ]),
      displayMath(
        String.raw`\frac{2\pi(\mu-1)}{M} < \frac{2\pi(\mu-\delta)}{M} \leq \frac{2\pi\mu}{M}`,
      ),
      paragraph([
        "すなわち ",
        math(String.raw`t^{(M)}_\mu \in I_\mu`),
        "。したがって ",
        math(String.raw`t \in I_\mu`),
        " なら ",
        math(String.raw`\left|t - t^{(M)}_\mu\right| \leq \dfrac{2\pi}{M}`),
        "（同じ長さ ",
        math(String.raw`2\pi/M`),
        " の区間に属する 2 点の距離）。",
      ]),
      paragraph([
        "Step 2（各区間での誤差）。",
        math(String.raw`\mu`),
        " を固定する。(R2) の定数の積分より ",
        math(String.raw`\int_{I_\mu} g\!\left(t^{(M)}_\mu\right)dt = \dfrac{2\pi}{M}\,g\!\left(t^{(M)}_\mu\right)`),
        " なので、積分の線型性と評価 ",
        math(String.raw`\left|\int_{I}h\right| \leq |I|\sup_I|h|`),
        " より",
      ]),
      displayMath(
        String.raw`\left|\int_{I_\mu} g(t)\,dt - \frac{2\pi}{M}\,g\!\left(t^{(M)}_\mu\right)\right|
= \left|\int_{I_\mu}\left(g(t) - g\!\left(t^{(M)}_\mu\right)\right)dt\right|
\leq \frac{2\pi}{M}\,\sup_{t \in I_\mu}\left|g(t) - g\!\left(t^{(M)}_\mu\right)\right|`,
      ),
      paragraph([
        "Step 1 より ",
        math(String.raw`t \in I_\mu`),
        " と ",
        math(String.raw`t^{(M)}_\mu`),
        " はいずれも ",
        math(String.raw`[0,2\pi]`),
        " に属し距離が ",
        math(String.raw`2\pi/M`),
        " 以下なので、",
        math(String.raw`\omega`),
        " の定義より ",
        math(String.raw`\left|g(t)-g\!\left(t^{(M)}_\mu\right)\right| \leq \omega\!\left(\frac{2\pi}{M}\right)`),
        "。よって",
      ]),
      displayMath(
        String.raw`\left|\int_{I_\mu} g(t)\,dt - \frac{2\pi}{M}\,g\!\left(t^{(M)}_\mu\right)\right|
\leq \frac{2\pi}{M}\,\omega\!\left(\frac{2\pi}{M}\right)`,
      ),
      paragraph(["Step 3（総和）。三角不等式で ", math(String.raw`\mu`), " について足すと"]),
      displayMath(
        String.raw`\left|\int_0^{2\pi} g(t)\,dt - \frac{2\pi}{M}\sum_{\mu=1}^{M} g\!\left(t^{(M)}_\mu\right)\right|
\leq \sum_{\mu=1}^{M}\frac{2\pi}{M}\,\omega\!\left(\frac{2\pi}{M}\right)
= 2\pi\,\omega\!\left(\frac{2\pi}{M}\right)`,
      ),
      paragraph([
        "両辺を ",
        math(String.raw`2\pi > 0`),
        " で割ると statement の評価を得る。",
      ]),
      paragraph([
        "Step 4（収束）。(R1) を ",
        math(String.raw`[0,2\pi]`),
        " 上の連続関数 ",
        math(String.raw`g`),
        " に適用する。任意の ",
        math(String.raw`\epsilon > 0`),
        " に対して ",
        math(String.raw`\delta_0 > 0`),
        " が存在して、",
        math(String.raw`s,t \in [0,2\pi]`),
        "、",
        math(String.raw`|s-t| \leq \delta_0`),
        " なら ",
        math(String.raw`|g(s)-g(t)| \leq \epsilon`),
        " である。これは ",
        math(String.raw`h \leq \delta_0`),
        " なら ",
        math(String.raw`\omega(h) \leq \epsilon`),
        " を意味する。",
        math(String.raw`M > 2\pi/\delta_0`),
        " なら ",
        math(String.raw`2\pi/M < \delta_0`),
        " なので ",
        math(String.raw`\omega(2\pi/M) \leq \epsilon`),
        "。",
      ]),
      paragraph([
        "したがって Step 3 の評価より、",
        math(String.raw`M > 2\pi/\delta_0`),
        " なる ",
        math(String.raw`M`),
        " について",
      ]),
      displayMath(
        String.raw`\left|\frac{1}{M}\sum_{\mu=1}^{M} g\!\left(t^{(M)}_\mu\right)
- \frac{1}{2\pi}\int_{0}^{2\pi} g(t)\,dt\right| \leq \epsilon`,
      ),
      paragraph([
        math(String.raw`\epsilon > 0`),
        " は任意だったので、主張の極限が成り立つ。",
      ]),
      paragraph([
        "（周期性は本証明では ",
        math(String.raw`\delta = 0`),
        " のとき ",
        math(String.raw`t^{(M)}_M = 2\pi`),
        " が区間 ",
        math(String.raw`[0,2\pi]`),
        " の端点として現れることを許すために使っている。",
        math(String.raw`g(2\pi) = g(0)`),
        " なので、どちらの端点を代表点に取っても値は同じである。）",
      ]),
    ],
    conversion: {
      status: "added",
      notes: [
        "delta ∈ [0,1) を許すことで、整数点（delta = 0、V^{(-)} セクター）と半整数点（delta = 1/2、V^{(+)} セクター）の両方を 1 つの主張で扱える。どちらでも極限が同じであることが、熱力学極限でセクターの区別が消える理由である。",
        "収束の速さは γ の連続度に支配される。臨界点（sinh 2K_1 sinh 2K_2 = 1）では γ(θ) が θ = 0 の近くで |θ| のオーダーでしか小さくならず、連続度が Lipschitz より悪くなるため収束が遅い。数値でも臨界点だけ収束が遅いことを確認している（sagemath/check/045_claim_free_energy/check_02_riemann_sum.sage）。",
      ],
    },
  },

  {
    id: "freeenergy_005_theorem_onsager_expression",
    kind: "theorem",
    sourcePath: SRC,
    sourceOrdinal: 7,
    title: { text: "Onsager の自由エネルギーの表式" },
    labels: ["onsager_free_energy_expression"],
    statement: [
      paragraph([
        math(String.raw`\delta \in [0,1)`),
        " を固定し、",
        math(String.raw`M \in \mathbb{Z}_{\geq 2}`),
        " について",
      ]),
      displayMath(
        String.raw`\Theta_M^{(\delta)} := \left\{\, \frac{2\pi(\mu-\delta)}{M} \ \middle|\ \mu = 1,\dots,M \,\right\},
\qquad
\Lambda^{(\delta)}_M := (2\sinh 2K_2)^{M/2}
\exp\left(\frac{1}{2}\sum_{\theta \in \Theta_M^{(\delta)}} \gamma(\theta)\right)`,
      ),
      paragraph([
        "とおく（",
        ref("eigenvalues_of_V"),
        " の ",
        math(String.raw`\Lambda_{\max}`),
        " は ",
        math(String.raw`\delta = 0`),
        " の場合にあたる）。このとき",
      ]),
      displayMath(
        String.raw`\lim_{M\to\infty}\frac{1}{M}\log \Lambda^{(\delta)}_M
= \frac{1}{2}\log\left(2\sinh 2K_2\right)
+ \frac{1}{4\pi}\int_0^{2\pi}\gamma(\theta)\,d\theta`,
      ),
      paragraph([
        "が成り立つ。**右辺は ",
        math(String.raw`\delta`),
        " に依らない。** ここで",
      ]),
      displayMath(
        String.raw`\gamma(\theta) = \mathrm{arccosh}\left(\cosh 2K_1\cosh 2K_2^* - \sinh 2K_1 \sinh 2K_2^*\cos\theta\right)`,
      ),
      paragraph([
        "であり（",
        ref("def_A_theta"),
        "、",
        ref("gamma1_lower_bound_all_theta"),
        "）、これが Onsager の自由エネルギーの表式である。",
      ]),
    ],
    proof: [
      paragraph([
        math(String.raw`\Lambda := \Lambda^{(\delta)}_M`),
        " の ",
        math(String.raw`\log`),
        " を取る。",
        math(String.raw`2\sinh 2K_2 > 0`),
        "（",
        math(String.raw`K_2 > 0`),
        "）と ",
        math(String.raw`\exp`),
        " の正値性より ",
        math(String.raw`\Lambda > 0`),
        " なので ",
        math(String.raw`\log\Lambda`),
        " が定まり、",
        math(String.raw`\log(ab) = \log a + \log b`),
        "、",
        math(String.raw`\log(x^{r}) = r\log x`),
        "、",
        math(String.raw`\log(e^{y}) = y`),
        " より",
      ]),
      displayMath(
        String.raw`\log\Lambda^{(\delta)}_M
= \frac{M}{2}\log\left(2\sinh 2K_2\right)
+ \frac{1}{2}\sum_{\theta\in\Theta_M^{(\delta)}}\gamma(\theta)`,
      ),
      paragraph([math(String.raw`M > 0`), " で割ると"]),
      displayMath(
        String.raw`\frac{1}{M}\log\Lambda^{(\delta)}_M
= \frac{1}{2}\log\left(2\sinh 2K_2\right)
+ \frac{1}{2}\cdot\frac{1}{M}\sum_{\mu=1}^{M}\gamma\!\left(\frac{2\pi(\mu-\delta)}{M}\right)`,
      ),
      paragraph([
        "第 1 項は ",
        math(String.raw`M`),
        " に依らない定数である。第 2 項について、",
        ref("gamma_is_continuous"),
        " より ",
        math(String.raw`\gamma`),
        " は ",
        math(String.raw`\mathbb{R}`),
        " 上連続かつ周期 ",
        math(String.raw`2\pi`),
        " なので、",
        ref("riemann_sum_to_integral"),
        " を ",
        math(String.raw`g = \gamma`),
        " として適用でき",
      ]),
      displayMath(
        String.raw`\frac{1}{M}\sum_{\mu=1}^{M}\gamma\!\left(\frac{2\pi(\mu-\delta)}{M}\right)
\ \xrightarrow[M\to\infty]{}\ \frac{1}{2\pi}\int_0^{2\pi}\gamma(\theta)\,d\theta`,
      ),
      paragraph([
        "収束する実数列の定数倍・定数加算はそれぞれ収束するので",
      ]),
      displayMath(
        String.raw`\lim_{M\to\infty}\frac{1}{M}\log\Lambda^{(\delta)}_M
= \frac{1}{2}\log\left(2\sinh 2K_2\right)
+ \frac{1}{2}\cdot\frac{1}{2\pi}\int_0^{2\pi}\gamma(\theta)\,d\theta`,
      ),
      paragraph([
        "であり、",
        math(String.raw`\frac12\cdot\frac1{2\pi} = \frac1{4\pi}`),
        " より主張の式を得る。",
        ref("riemann_sum_to_integral"),
        " の極限が ",
        math(String.raw`\delta`),
        " に依らないので、右辺も ",
        math(String.raw`\delta`),
        " に依らない。",
      ]),
    ],
    conversion: { status: "added" },
  },

  {
    id: "freeenergy_006_remark_remaining_input",
    kind: "remark",
    sourcePath: SRC,
    sourceOrdinal: 8,
    title: { text: "厳密解へ残っている入力：偶セクターの固有値" },
    labels: ["remark_remaining_input_even_sector"],
    statement: [
      paragraph([
        "ここまでで得られたものを並べると、分配関数から自由エネルギーまでの経路は次のようになっている。",
      ]),
      list([
        [
          ref("partition_function_in_pauli_form"),
          "：",
          math(String.raw`Z = \mathrm{tr}\!\left((V_1V_2)^{N_{\mathrm{row}}}\right)`),
        ],
        [
          ref("partition_function_sandwich"),
          "：",
          math(String.raw`c(M)^{N_{\mathrm{row}}} \leq Z \leq 2^{M}c(M)^{N_{\mathrm{row}}}`),
        ],
        [
          ref("limit_of_log_Z_in_N_row"),
          "：",
          math(String.raw`\dfrac{1}{MN_{\mathrm{row}}}\log Z \to \dfrac{1}{M}\log c(M)`),
        ],
        [
          ref("sector_decomposition_of_rayleigh_sup"),
          "：",
          math(String.raw`c(M) = \max\left(c_+(M),c_-(M)\right)`),
        ],
        [
          ref("onsager_free_energy_expression"),
          "：",
          math(String.raw`\dfrac{1}{M}\log\Lambda^{(\delta)}_M \to \dfrac12\log(2\sinh 2K_2) + \dfrac1{4\pi}\displaystyle\int_0^{2\pi}\gamma`),
          "（",
          math(String.raw`\delta`),
          " に依らない）",
        ],
      ]),
      paragraph([
        "**残っている入力は 1 つだけである**（",
        "これは 013 章から 018 章で証明され、",
        ref("c_plus_equals_Lambda_half_integer"),
        " で解消された。最終的な結論は ",
        ref("onsager_exact_solution"),
        "）：",
        math(String.raw`c_+(M)`),
        "（",
        math(String.raw`\varepsilon`),
        " の固有値 ",
        math(String.raw`+1`),
        " のセクターでの上限）が ",
        math(String.raw`\Lambda^{(1/2)}_M`),
        " に等しいこと、すなわち ",
        math(String.raw`V^{(+)}`),
        " の固有値が**半整数運動量** ",
        math(String.raw`2\pi(\mu-\tfrac12)/M`),
        " で与えられることである。",
      ]),
      paragraph([
        "本文にこれが無い理由は具体的である。",
        ref("def_hatZ_hatY"),
        " の ",
        math(String.raw`\hat{Z}_\mu^{(\pm)}`),
        " は第 1 項に符号 ",
        math(String.raw`\mp`),
        " を持つ。",
        ref("commutator_of_H_and_Z_Y"),
        " の (C) ",
        math(String.raw`[H_2, \hat{Z}_\mu^{(-)}] = -2\hat{Y}_\mu`),
        " は、",
        math(String.raw`[H_2, Z_j] = -2Y_j`),
        " を各項に適用して係数どうしを比べる形で示されるが、",
        math(String.raw`\hat{Z}_\mu^{(+)}`),
        " では第 1 項の符号だけが反転しているため右辺が ",
        math(String.raw`-2\hat{Y}_\mu`),
        " にならない。",
        "したがって 008 章以降の議論は ",
        math(String.raw`\hat{Z}_\mu^{(-)}`),
        "（整数運動量）に対してのみ成立しており、",
        math(String.raw`V^{(+)}`),
        " には適用できない。",
      ]),
      paragraph([
        "偶セクターを扱うには、符号を第 1 項に置く代わりに**位相に繰り込んだ**",
      ]),
      displayMath(
        String.raw`\check{Z}_\mu := \sum_{j=1}^{M} Z_j\,e^{-i j \tilde\theta_\mu},\qquad
\check{Y}_\mu := \sum_{j=1}^{M} Y_j\,e^{-i j \tilde\theta_\mu},\qquad
\tilde\theta_\mu := \frac{2\pi\left(\mu-\tfrac12\right)}{M}`,
      ),
      paragraph([
        "を用いればよい。この ",
        math(String.raw`\check{Z}, \check{Y}`),
        " については ",
        ref("commutator_of_H_and_Z_Y"),
        " の (A)〜(D) が ",
        math(String.raw`H_1^{(+)}, H_2`),
        " に対して成り立ち（",
        ref("commutator_of_H_and_check_Z_Y"),
        "）、反交換関係の対は ",
        math(String.raw`\nu = M+1-\mu`),
        " になる（",
        ref("anticommutator_of_check_Z_Y"),
        "）。",
        "**この道筋は 013 章から 018 章で本文として実行済みであり、以降の証明の根拠として使ってよい。**",
        "到達点は ",
        ref("c_plus_equals_Lambda_half_integer"),
        " の ",
        math(String.raw`c_+(M) = \Lambda^{(1/2)}_M`),
        " と ",
        ref("onsager_exact_solution"),
        " である。",
      ]),
    ],
    conversion: {
      status: "added",
      notes: [
        "V^{(+)} の固有値が半整数運動量で与えられることは M=2,3,4 で数値的に確認済み（相対誤差 1e-14 以下、整数運動量では 0.5〜2.4 の相対差で明確に不一致）。また最大固有値が (+) セクターで達成されることも M=2,3,4 で確認した（W の成分がすべて正なので Perron–Frobenius から期待される通り）。これらは sagemath/check/044_claim_max_eigenvalue/ と 045_claim_free_energy/ に記録した。",
      ],
    },
  },
]);
