

# This file was *autogenerated* from the file /Users/masaori/git/masaori/math/.claude/worktrees/polished-sleeping-badger/exact-solution-of-2d-ising-model/sagemath/check/100_cosh_sinh_basic_properties/check_02_cosh2_minus_sinh2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_300 = Integer(300); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1000 = Integer(1000); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_0p4407 = RealNumber('0.4407'); _sage_const_0p2 = RealNumber('0.2'); _sage_const_0p813 = RealNumber('0.813'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_1p7 = RealNumber('1.7'); _sage_const_5p0 = RealNumber('5.0'); _sage_const_10p4 = RealNumber('10.4'); _sage_const_15 = Integer(15); _sage_const_25 = Integer(25); _sage_const_1p0 = RealNumber('1.0')# ---------------------------------------------------------
# <cosh_sinh_basic_properties> (2)  (cosh x)^2 - (sinh x)^2 = 1
#
# 独立経路: 左辺は定義式 (exp(x)±exp(-x))/2 から 300 bit で組み上げて自乗し差を取る。
# 右辺は定数 1。本文の証明は (cosh-sinh)(cosh+sinh)=exp(-x)exp(x)=exp(0)=1 と
# 積へ分解する経路なので、こちらは分解せず素朴に自乗して引く経路を取る。
# ---------------------------------------------------------
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '../../_shared/operators.sage'))

RF = RealField(_sage_const_300 )

XS = [RF(v) for v in [
    _sage_const_0 , _sage_const_1 /_sage_const_1000 , -_sage_const_1 /_sage_const_1000 , _sage_const_1 /_sage_const_3 , -_sage_const_1 /_sage_const_3 , _sage_const_1 , -_sage_const_1 , _sage_const_2 , -_sage_const_2 ,
    _sage_const_2 *_sage_const_0p4407 , -_sage_const_2 *_sage_const_0p4407 , _sage_const_2 *_sage_const_0p2 , _sage_const_2 *_sage_const_0p813 , _sage_const_2 *_sage_const_0p05 , _sage_const_2 *_sage_const_0p1 ,
    _sage_const_2 *_sage_const_0p4 , _sage_const_2 *_sage_const_0p8 , _sage_const_2 *_sage_const_1p2 , _sage_const_2 *_sage_const_0p3 , _sage_const_2 *_sage_const_1p7 , _sage_const_2 *_sage_const_5p0 , _sage_const_2 *_sage_const_10p4 , -_sage_const_2 *_sage_const_10p4 ,
    _sage_const_15 , -_sage_const_15 , _sage_const_25 , -_sage_const_25 ,
]]

rep = CheckReport("<cosh_sinh_basic_properties> (2) cosh^2 - sinh^2 = 1")

for x in XS:
    c = (RF(x).exp() + RF(-x).exp()) / _sage_const_2 
    s = (RF(x).exp() - RF(-x).exp()) / _sage_const_2 
    rep.close(float(c**_sage_const_2  - s**_sage_const_2 ), _sage_const_1p0 , "cosh^2-sinh^2=1 @x=%s" % x)
    # 本文の分解経路（積の形）も別途確認する
    rep.close(float((c - s) * (c + s)), _sage_const_1p0 , "(cosh-sinh)(cosh+sinh)=1 @x=%s" % x)

rep.finish()

