

# This file was *autogenerated* from the file /Users/masaori/git/masaori/math/.claude/worktrees/polished-sleeping-badger/exact-solution-of-2d-ising-model/sagemath/check/100_cosh_sinh_basic_properties/check_04_square_injective_on_positives.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_6 = Integer(6); _sage_const_1000 = Integer(1000); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_4407 = Integer(4407); _sage_const_10000 = Integer(10000); _sage_const_813 = Integer(813); _sage_const_17 = Integer(17); _sage_const_0 = Integer(0)# ---------------------------------------------------------
# <cosh_sinh_basic_properties> (4)  a, b in R_{>0} について a^2 = b^2 <=> a = b
#
# 有理数（厳密演算）で全 pair を走査する。丸めが入らないので同値性を厳密に判定できる。
# 反例探索の方針:
#   - a != b なのに a^2 = b^2 になる正の pair があれば FAIL（乗法性の破れ）。
#   - 仮定「a,b > 0」を外すと主張が破れることも確認する（a>0, b=-a は a^2=b^2 だが a != b）。
#     これを確認しないと、仮定が効いているかを検証したことにならない。
# ---------------------------------------------------------
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '../../_shared/operators.sage'))

POSITIVES = [QQ(v) for v in [
    _sage_const_1 /_sage_const_10 **_sage_const_6 , _sage_const_1 /_sage_const_1000 , _sage_const_1 /_sage_const_7 , _sage_const_1 /_sage_const_3 , _sage_const_1 /_sage_const_2 , _sage_const_2 /_sage_const_3 , _sage_const_1 , _sage_const_5 /_sage_const_4 , _sage_const_3 /_sage_const_2 , _sage_const_2 , _sage_const_7 /_sage_const_3 , _sage_const_3 , _sage_const_5 , _sage_const_10 ,
    _sage_const_100 , _sage_const_1000 , _sage_const_10 **_sage_const_6 , _sage_const_4407 /_sage_const_10000 , _sage_const_813 /_sage_const_1000 , _sage_const_17 /_sage_const_10 ,
]]

rep = CheckReport("<cosh_sinh_basic_properties> (4) a,b>0: a^2=b^2 <=> a=b")

n_eq_sq = _sage_const_0 
for a in POSITIVES:
    for b in POSITIVES:
        eq_sq = (a**_sage_const_2  == b**_sage_const_2 )
        eq = (a == b)
        if eq_sq:
            n_eq_sq += _sage_const_1 
        rep.truth(eq_sq == eq, "a=%s, b=%s: (a^2=b^2) == (a=b)" % (a, b))

print("  a^2=b^2 となった pair: %d 組（すべて a=b のはず、pair 総数 %d）"
      % (n_eq_sq, len(POSITIVES)**_sage_const_2 ))

# 仮定 a,b>0 を外した場合: b = -a では a^2=b^2 だが a != b
n_broken = _sage_const_0 
for a in POSITIVES:
    b = -a
    if (a**_sage_const_2  == b**_sage_const_2 ) and (a != b):
        n_broken += _sage_const_1 
rep.truth(n_broken == len(POSITIVES),
          "仮定 a,b>0 を外すと全 %d 例で主張が破れる（仮定が効いている）" % len(POSITIVES))

rep.finish()

