

# This file was *autogenerated* from the file check_01_square_of_sqrt.sage
from sage.all_cmdline import *   # import sage library

_sage_const_211 = Integer(211); _sage_const_0 = Integer(0); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_2 = Integer(2); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_1en12 = RealNumber('1e-12'); _sage_const_1 = Integer(1)# <square_of_sqrt>: z = ± sqrt(z^2) の場合分け
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
load(os.path.join(_dir, "_prelude.sage"))
import numpy as np
import math
rng = np.random.default_rng(int(_sage_const_211 ))
rep = CheckReport("square_of_sqrt")
zs = sample_complex(rng)
c1 = c2 = _sage_const_0 
for z in zs:
    a = arg_def(z)
    s = sqrt_def(z*z)
    # 境界 arg z = 0, pi はどちらの分岐に落ちるかが倍精度で定まらないので分離する。
    if abs(a) < _sage_const_1en9  or abs(a - math.pi) < _sage_const_1en9  or abs(a - _sage_const_2 *math.pi) < _sage_const_1en9 :
        ok = (abs(z - s) < _sage_const_1en8 *max(_sage_const_1p0 ,abs(z))) or (abs(z + s) < _sage_const_1en8 *max(_sage_const_1p0 ,abs(z)))
        rep.truth(ok, f"境界 z={z} arg={a:.12f}: ± のいずれかに一致")
        continue
    if a < math.pi - _sage_const_1en12 :
        c1 += _sage_const_1 
        rep.close(z, s, f"z={z} arg={a:.6f} < pi: z = sqrt(z^2)")
    else:
        c2 += _sage_const_1 
        rep.close(z, -s, f"z={z} arg={a:.6f} >= pi: z = -sqrt(z^2)")
print(f"  0<=arg<pi の場合 {c1} 件、pi<=arg<2pi の場合 {c2} 件")
rep.truth(c1 > _sage_const_0  and c2 > _sage_const_0 , "両方の場合を踏んでいる")
rep.finish()

