

# This file was *autogenerated* from the file check_01_arccosh.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_2 = Integer(2); _sage_const_2p0 = RealNumber('2.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_0p4407 = RealNumber('0.4407'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_1p1 = RealNumber('1.1'); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)# <def_gamma_theta_mu> + <lambda_eq_exp_gamma>: gamma := arccosh(gamma_1), lambda_± = e^{±gamma}
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np

def crit_K1(K2):
    """臨界条件 sinh(2K_1) sinh(2K_2) = 1 をちょうど満たす K_1。"""
    return float(np.arcsinh(_sage_const_1p0 /np.sinh(_sage_const_2 *K2))/_sage_const_2p0 )

CRIT_PARAMS = [{"K1": crit_K1(k2), "K2": k2} for k2 in [_sage_const_0p3 , _sage_const_0p4407 , _sage_const_0p6 , _sage_const_1p1 ]]
ALL_PARAMS = list(OP_TEST_PARAMS) + CRIT_PARAMS

rep = CheckReport("lambda_eq_exp_gamma")
for M in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_8 ]:
    for p in ALL_PARAMS:
        K1, K2 = p['K1'], p['K2']
        for mu in list(range(-M,_sage_const_0 )) + list(range(_sage_const_1 ,M+_sage_const_1 )):
            th = theta_mu_of(mu, M)
            g1 = float(np.real(gamma1_of(th,K1,K2)))
            g = float(np.arccosh(max(g1, _sage_const_1p0 )))
            lp, lm = lambda_pm_of(mu,M,K1,K2)
            rep.close(lp, np.exp(g), f"M={M} mu={mu}: lambda_+ = e^gamma")
            rep.close(lm, np.exp(-g), f"M={M} mu={mu}: lambda_- = e^-gamma")
            rep.close(np.cosh(g), g1, f"M={M} mu={mu}: cosh(gamma) = gamma_1")
            rep.truth(g >= _sage_const_0 , f"M={M} mu={mu}: gamma >= 0")
rep.finish()

