

# This file was *autogenerated* from the file check_01_zero_condition.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_2 = Integer(2); _sage_const_2p0 = RealNumber('2.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_0p4407 = RealNumber('0.4407'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_1p1 = RealNumber('1.1'); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_1en12 = RealNumber('1e-12'); _sage_const_1en9 = RealNumber('1e-9'); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_1en8 = RealNumber('1e-8')# <gamma_2_theta_is_0>: gamma_2 = 0 ⟺ {sin th = 0 かつ c_2 s_1 = c_1 cos th} ⟺ mu = ±M かつ c_1 = s_1 c_2
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np

def crit_K1(K2):
    """臨界条件 sinh(2K_1) sinh(2K_2) = 1 をちょうど満たす K_1。"""
    return float(np.arcsinh(_sage_const_1p0 /np.sinh(_sage_const_2 *K2))/_sage_const_2p0 )

CRIT_PARAMS = [{"K1": crit_K1(k2), "K2": k2} for k2 in [_sage_const_0p3 , _sage_const_0p4407 , _sage_const_0p6 , _sage_const_1p1 ]]
ALL_PARAMS = list(OP_TEST_PARAMS) + CRIT_PARAMS

rep = CheckReport("gamma_2_theta_is_0")
n_even_half = _sage_const_0 
for M in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_6 ,_sage_const_8 ]:
    for p in ALL_PARAMS:
        K1, K2 = p['K1'], p['K2']
        c1, s1, c2 = c_of(K1), s_of(K1), c_of(K2)
        for mu in list(range(-M,_sage_const_0 )) + list(range(_sage_const_1 ,M+_sage_const_1 )):
            th = theta_mu_of(mu, M)
            g2 = gamma2_of(th,K1,K2)
            cond = (abs(np.sin(th)) < _sage_const_1en12 ) and (abs(c2*s1 - c1*np.cos(th)) < _sage_const_1en9 )
            rep.truth((abs(g2) < _sage_const_1en9 ) == cond,
                      f"M={M} mu={mu} K1={K1:.4f} K2={K2}: gamma_2=0 ⟺ 連立条件 (|g2|={abs(g2):.3e})")
            # M が偶数で mu = ±M/2 のとき sin th = 0 だが gamma_2 != 0 であること
            if M % _sage_const_2  == _sage_const_0  and abs(mu) == M//_sage_const_2 :
                n_even_half += _sage_const_1 
                rep.truth(abs(np.sin(th)) < _sage_const_1en12 , f"M={M} mu={mu}: sin(theta_mu) = 0")
                rep.truth(abs(g2) > _sage_const_1en6 ,
                          f"M={M} mu={mu} K1={K1:.4f}: sin=0 でも gamma_2 != 0（|g2|={abs(g2):.4e}）")
                # 理由: cos th = -1 なので第2条件が c_2 s_1 = -c_1 < 0 を要求して正値性に反する
                rep.truth(c2*s1 > _sage_const_0  and -c1 < _sage_const_0 , f"M={M} mu={mu}: c_2 s_1 > 0 > -c_1（矛盾の根拠）")
            # gamma_2 = 0 が起きるのは mu = ±M かつ c_1 = s_1 c_2 のときだけ
            if abs(g2) < _sage_const_1en9 :
                rep.truth(abs(mu) == M, f"M={M} mu={mu}: gamma_2=0 ⟹ |mu| = M")
                rep.truth(abs(c1 - s1*c2) < _sage_const_1en8 , f"M={M} mu={mu}: gamma_2=0 ⟹ c_1 = s_1 c_2")
print(f"  M 偶数・mu=±M/2（sin=0 だが gamma_2!=0）の事例: {n_even_half} 件")
rep.finish()

