

# This file was *autogenerated* from the file /Users/masaori/git/masaori/math/.claude/worktrees/reflective-fluttering-panda/exact-solution-of-2d-ising-model/sagemath/check/191_definition_def_hatZ_hatY/check_02_plus_minus_differ_only_at_j1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_1p0 = RealNumber('1.0')# def_hatZ_hatY: hatZ^{(+)} と hatZ^{(-)} の差が j=1 の項の符号だけであることを明示的に確認する。
#
# 定義から従う帰結（本文が「j=1 の重みが ∓1」と述べていることの内容）:
#   hatZ^{(+)}_mu - hatZ^{(-)}_mu = (-1 - (+1)) Z_1 exp(-i 2 pi mu / M) = -2 Z_1 exp(-i 2 pi mu / M)
#   hatZ^{(+)}_mu + hatZ^{(-)}_mu = 2 sum_{j=2}^{M} Z_j exp(-i 2 pi j mu / M)
#
# 独立経路: 左辺は hatZ_op（ライブラリ）から、右辺は Zop から素朴に組む。
# さらに「差が j=1 の項だけ」を、j>=2 の各項が両者で完全一致することでも確かめる（同語反復回避）。
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '../../_shared/operators.sage'))

rep = CheckReport("def_hatZ_hatY: hatZ^{(+)} と hatZ^{(-)} の差は j=1 の項の符号のみ")

M_LIST = [_sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 ]

for M in M_LIST:
    calM = [m for m in range(-int(M), int(M) + _sage_const_1 ) if m != _sage_const_0 ]
    for mu in calM:
        zp = hatZ_op(mu, M, '+')
        zm = hatZ_op(mu, M, '-')
        e1 = _np.exp(-_sage_const_1j  * _sage_const_2  * _np.pi * float(mu) / float(M))

        rep.close(zp - zm, -_sage_const_2p0  * Zop(_sage_const_1 , M) * e1,
                  "M=%d mu=%+d: hatZ^{(+)} - hatZ^{(-)} = -2 Z_1 e^{-i2πμ/M}" % (M, mu))

        tail = _np.zeros((_sage_const_2  ** int(M), _sage_const_2  ** int(M)), dtype=complex)
        for j in range(_sage_const_2 , int(M) + _sage_const_1 ):
            tail = tail + Zop(j, M) * _np.exp(-_sage_const_1j  * _sage_const_2  * _np.pi * float(j) * float(mu) / float(M))
        rep.close(zp + zm, _sage_const_2p0  * tail,
                  "M=%d mu=%+d: hatZ^{(+)} + hatZ^{(-)} = 2 Σ_{j>=2}" % (M, mu))

        # j=1 の項を各々から取り除くと完全に一致する（＝差は j=1 の項に限る）
        rep.close(zp - (-_sage_const_1p0 ) * Zop(_sage_const_1 , M) * e1, zm - (+_sage_const_1p0 ) * Zop(_sage_const_1 , M) * e1,
                  "M=%d mu=%+d: j=1 の項を除くと両符号で一致" % (M, mu))

        # 反例探し: 差が本当に 0 でないこと（＝ (+) と (-) は別物であること）を確認する。
        # -2 Z_1 e^{...} は Z_1 が可逆（Z_1^2 = I）なのでノルムは 0 にならないはず。
        d = float(_np.max(_np.abs(zp - zm)))
        rep.truth(d > _sage_const_1p0 , "M=%d mu=%+d: hatZ^{(+)} != hatZ^{(-)}（最大成分差 %.3f）" % (M, mu, d))

rep.finish()

