

# This file was *autogenerated* from the file degenerate_odd.sage
from sage.all_cmdline import *   # import sage library

_sage_const_12 = Integer(12); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_78 = Integer(78); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_29 = Integer(29); _sage_const_2400 = Integer(2400); _sage_const_4 = Integer(4); _sage_const_1200 = Integer(1200); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11)# cycle 16 / T3: ell が奇素数の退化塔（ell = 1 mod 4 のトーラス）に絞った検証。
#
# 対応する証明本体: outputs/reports/cycle16_T3_lower_order_and_degeneracy.md の §6。
# 共有定義は _defs.sage。
#
# report §6.3 の「仮説 6.1」は
#     退化帯の上の全ての点で v_ell(E) = 4 / phi(ell^M)
# であり、そこから閉形式
#     (6.3)  ord_ell(kappa_n) = (2 ell + 6)/(ell - 1) * (ell^n - 1) - 2n
# が出る。(6.3) には n ell^n 項が無い。
#
# 仮説 6.1 は band_structure.sage Step D で「小さい M での観察」として得たものである。
# ell = 2 の帯は M <= 2 では層が 1 つしか無く、M = 3 で初めて分裂した。
# したがって「小さい M で一定」は「大きい M でも一定」の根拠にならない。
# そこで本スクリプトは 2 方向から仮説 6.1 を突く。
#
#   Step A  (6.3) を実際の塔の値 ord_ell(kappa_n) と照合する。
#           (6.3) は帯の付値の観察だけから導いたもので kappa_n を使っていないので、
#           これは塔の値に対して out-of-sample である。
#           ただし後述のとおり M の範囲については out-of-sample ではない。
#   Step B  band_structure.sage が届かなかった **より大きい M** で、帯の上の点を
#           全列挙ではなく **標本抽出** して v_ell(E)*phi(ell^M) を測る。
#           層の分裂が起きるかどうかを直接見るのが目的。
#
# 実行: sage degenerate_odd.sage

load('_defs.sage')

# Step B の大きい M（例: ell=5, M=4 は phi(5^4) = 500 次の円分体）で
# 既定 1GB の PARI スタックが溢れるので広げておく。
pari.allocatemem(_sage_const_12  * _sage_const_10 **_sage_const_9 , silent=True)

print("=" * _sage_const_78 )
print("cycle 16 / T3: ell = 1 mod 4 のトーラス（退化塔）の検証")
print("SageMath", version())
print("=" * _sage_const_78 )

TOR = (_sage_const_1 , [(_sage_const_0 , _sage_const_0 , (_sage_const_1 , _sage_const_0 )), (_sage_const_0 , _sage_const_0 , (_sage_const_0 , _sage_const_1 ))])
Dtor = detL(*TOR)
print("トーラスの D =", Dtor)


def h61(ell, n):
    """仮説 6.1 から導いた閉形式 (6.3)。"""
    return QQ(_sage_const_2  * ell + _sage_const_6 ) / (ell - _sage_const_1 ) * (ell**n - _sage_const_1 ) - _sage_const_2  * n


def band_dirs(ell):
    """H = -(T^2+S^2) の P^1(F_ell) 有理零点 (1:c)、c^2 = -1。"""
    F = GF(ell)
    return [c for c in F if c != _sage_const_0  and c**_sage_const_2  == -_sage_const_1 ]


# ==========================================================================
# Step A  (6.3) と実際の塔の値の照合
# ==========================================================================
print()
print("### Step A  仮説 6.1 由来の閉形式 (6.3) と実測の ord_ell(kappa_n) の照合")
print("    (6.3) ord_ell(kappa_n) = (2 ell + 6)/(ell - 1) (ell^n - 1) - 2n")
print("    比較対照として、非退化なら成り立ったはずの定理 N1 の値も出す。")
print()

STEP_A = {_sage_const_5 : _sage_const_3 , _sage_const_13 : _sage_const_2 , _sage_const_17 : _sage_const_1 , _sage_const_29 : _sage_const_1 }
# 対象が 4 塔しかないので、lower_order.sage の一括掃引より段あたり予算を大きく取る。
STEP_A_BUDGET = _sage_const_2400 
cntA = badA = _sage_const_0 
for ell in sorted(STEP_A):
    inv = invariants(TOR[_sage_const_0 ], TOR[_sage_const_1 ], ell)
    ords = usable_prefix(tower_ords(TOR[_sage_const_0 ], TOR[_sage_const_1 ], ell, STEP_A[ell],
                                    tag='StepA torus ell=%d' % ell,
                                    budget=STEP_A_BUDGET))
    zs = inv['zeros']
    print("  ell=%2d: k=%d mu=%d z_H=%d %s / 帯の割合 %d/%d / 計算できた段 n=0..%d"
          % (ell, inv['k'], inv['mu'], len(zs), zs, len(zs), ell + _sage_const_1 , len(ords) - _sage_const_1 ))
    for n in range(len(ords)):
        nd = predicted_ord(inv, ell, QQ(_sage_const_0 ), n)      # 非退化型（定理 N1）の値
        hv = h61(ell, n)
        ok = (ords[n] == hv)
        if n >= _sage_const_1 :
            cntA += _sage_const_1 
            if not ok:
                badA += _sage_const_1 
        print("     n=%d: 実測 %-8s | 非退化型 %-10s 差 %-8s | (6.3) %-10s 一致=%s"
              % (n, ords[n], nd, ords[n] - nd, hv, ok))
print("  %s Step A: n>=1 の照合 %d 件、破れ %d 件" % (el(), cntA, badA))
print("  注意（射程）: トーラスの ord_ell(kappa_n) はレベル M <= n の点にしか依存しない。")
print("    よって n <= 3 での一致は M <= 3 の帯の付値しか使っておらず、")
print("    band_structure.sage で既に測った範囲と同じである。")
print("    すなわち Step A が確かめているのは「帯の付値を足し上げると塔の値を再現する」")
print("    という **帳尻** であって、大きい M への外挿ではない。外挿は Step B で突く。")

# ==========================================================================
# Step B  より大きい M での帯の付値（標本抽出）
# ==========================================================================
print()
print("### Step B  より大きい M での帯の上の v_ell(E)*phi(ell^M)（標本抽出）")
print("    仮説 6.1 が正しければ、どの M でも一律に 4 になるはず。")
print("    全列挙は点が phi(ell^M)^2 個あって不可能なので、対角かつ帯に入る点を標本抽出する。")
print("    比較のため、帯に入らない対角点（非退化予言 k=2）も同数程度測る。")
print()

STEP_B = {_sage_const_5 : [_sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 ], _sage_const_13 : [_sage_const_1 , _sage_const_2 , _sage_const_3 ], _sage_const_17 : [_sage_const_1 , _sage_const_2 ], _sage_const_29 : [_sage_const_1 , _sage_const_2 ]}
SAMPLE_BUDGET = _sage_const_1200 
cntB = badB = _sage_const_0 
for ell in sorted(STEP_B):
    cs = band_dirs(ell)
    nonband = [c for c in GF(ell) if c != _sage_const_0  and c**_sage_const_2  != -_sage_const_1 ][:_sage_const_3 ]
    for M in STEP_B[ell]:
        N = ell**M
        t0 = walltime()
        try:
            alarm(SAMPLE_BUDGET)
            vals_band = {}
            vals_non = {}
            for (cs_list, bucket) in [(cs, vals_band), (nonband, vals_non)]:
                for c in cs_list:
                    for a in [_sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_7 , _sage_const_11 ]:
                        if a % ell == _sage_const_0 :
                            continue
                        for hi in [_sage_const_0 , _sage_const_1 , _sage_const_2 ]:
                            b = (ZZ(c.lift()) * a + hi * ell) % N
                            if b % ell == _sage_const_0 :
                                continue
                            v = point_val(Dtor, ell, M, a, b)
                            vp = v * euler_phi(N)
                            bucket[vp] = bucket.get(vp, _sage_const_0 ) + _sage_const_1 
            cancel_alarm()
            nb = sum(vals_band.values())
            ok = (set(vals_band.keys()) == {_sage_const_4 }) if vals_band else None
            cntB += _sage_const_1 
            if ok is False:
                badB += _sage_const_1 
            print("  ell=%2d M=%d phi=%-5d | 帯 %3d 点 v*phi=%-18s 一律 4 =%s | 非帯 %3d 点 v*phi=%s  [%.0fs]"
                  % (ell, M, euler_phi(N), nb, vals_band, ok,
                     sum(vals_non.values()), vals_non, walltime() - t0))
        except AlarmInterrupt:
            cancel_alarm()
            SKIPS.append(('StepB band sample', _sage_const_1 , (), ell, M, SAMPLE_BUDGET))
            print("  ell=%2d M=%d | %d 秒で打ち切り -> **未検証**" % (ell, M, SAMPLE_BUDGET))
        except Exception as ex:
            cancel_alarm()
            print("  ell=%2d M=%d | ERROR %s" % (ell, M, ex))
print("  %s Step B: 照合 %d 件、「一律 4」から外れた件数 %d" % (el(), cntB, badB))
print("  注意: これは標本抽出であって全列挙ではない。外れた点が標本に入らなかった可能性は排除できない。")
print("    また、ここで測れた M の上限より大きい M については何も言えていない。")

# ==========================================================================
# 打ち切り一覧
# ==========================================================================
print()
print("### 時間上限で打ち切った計算の一覧")
if not SKIPS:
    print("  なし（全ての計算が上限内で完了した）")
else:
    for rec in SKIPS:
        print("  %s ell=%s n/M=%s で打ち切り（上限 %s 秒）" % (rec[_sage_const_0 ], rec[_sage_const_3 ], rec[_sage_const_4 ], rec[_sage_const_5 ]))
    print("  合計 %d 件。これらは **未検証** であり、上の結論の射程外である。" % len(SKIPS))

print()
print("=" * _sage_const_78 )
print("%s 終了" % el())
print("=" * _sage_const_78 )

