

# This file was *autogenerated* from the file check_02_commutators.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0p0 = RealNumber('0.0'); _sage_const_2 = Integer(2)# ---------------------------------------------------------
# SageMath: 半整数運動量モードの交換関係と反周期性
#   e^{-i M theta~_mu} = -1,  checkZ_{mu+M} = checkZ_mu,
#   theta~_{M+1-mu} = 2pi - theta~_mu,  checkZ_{M+1-mu} = checkZ_{1-mu}
#   (A) [H_1^{(+)}, checkZ_mu] =  2 e^{-i theta~} checkY_mu
#   (B) [H_1^{(+)}, checkY_mu] = -2 e^{ i theta~} checkZ_mu
#   (C) [H_2,       checkZ_mu] = -2 checkY_mu
#   (D) [H_2,       checkY_mu] =  2 checkZ_mu
# 対象: structured-latex commutator_of_H_and_check_Z_Y
#   （def_half_integer_modes も併せて検証）
# ---------------------------------------------------------
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '_prelude.sage'))

print("=== 反周期性と (A)-(D) ===")
all_ok = True
for M in EVEN_CASES_M:
    O = SpinOps(M)
    H1p = O.H1(+_sage_const_1 )
    w = {'antiper': _sage_const_0p0 , 'period': _sage_const_0p0 , 'conj': _sage_const_0p0 , 'A': _sage_const_0p0 , 'B': _sage_const_0p0 , 'C': _sage_const_0p0 , 'D': _sage_const_0p0 }
    for mu in range(_sage_const_1 , M + _sage_const_1 ):
        t = th_tilde(M, mu)
        w['antiper'] = max(w['antiper'], abs(eiph(-M * t) + _sage_const_1 ))
        w['period'] = max(w['period'], opnorm(checkZ(O, mu + M) - checkZ(O, mu)),
                          opnorm(checkY(O, mu + M) - checkY(O, mu)))
        # conjugate_index_of_check_Z_Y (1)(3): 共役添字は M+1-mu で取る（1-mu と同じ値）
        w['conj'] = max(w['conj'], abs(th_tilde(M, M + _sage_const_1  - mu) - (CDF(_sage_const_2  * pi) - t)),
                        opnorm(checkZ(O, M + _sage_const_1  - mu) - checkZ(O, _sage_const_1  - mu)),
                        opnorm(checkY(O, M + _sage_const_1  - mu) - checkY(O, _sage_const_1  - mu)))
        cZ = checkZ(O, mu); cY = checkY(O, mu)
        w['A'] = max(w['A'], opnorm(comm(H1p, cZ) - _sage_const_2  * eiph(-t) * cY))
        w['B'] = max(w['B'], opnorm(comm(H1p, cY) + _sage_const_2  * eiph(t) * cZ))
        w['C'] = max(w['C'], opnorm(comm(O.H2, cZ) + _sage_const_2  * cY))
        w['D'] = max(w['D'], opnorm(comm(O.H2, cY) - _sage_const_2  * cZ))
    worst = max(w.values())
    ok = worst <= TOL
    print(f"  M={M}: 反周期性 {w['antiper']:.1e}, 添字周期 {w['period']:.1e}, 共役添字 {w['conj']:.1e}, "
          f"(A) {w['A']:.1e} (B) {w['B']:.1e} (C) {w['C']:.1e} (D) {w['D']:.1e}"
          f"  -> {'PASS' if ok else 'FAIL'}")
    all_ok = ok and all_ok

print("RESULT: PASS" if all_ok else "RESULT: FAIL")

