

# This file was *autogenerated* from the file check_02_A_theta_consistency.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_2 = Integer(2); _sage_const_2p0 = RealNumber('2.0'); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0p4 = RealNumber('0.4'); _sage_const_0p8 = RealNumber('0.8'); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)# T_(V) の hatZ, hatY への作用が A(theta_mu) で与えられること（<T_V_hatZ_hatY> の作用素側での確認）
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
import itertools
def crit_K1(K2):
    return float(np.arcsinh(_sage_const_1p0 /np.sinh(_sage_const_2 *K2))/_sage_const_2p0 )
rep = CheckReport("T_(V) の作用 = A(theta_mu)（作用素レベル）")
for M in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    for p in [{'K1':_sage_const_0p4 ,'K2':_sage_const_0p8 },{'K1':_sage_const_1p2 ,'K2':_sage_const_0p3 },{'K1':crit_K1(_sage_const_0p6 ),'K2':_sage_const_0p6 }]:
        K1, K2 = p['K1'], p['K2']
        g1 = principal_sqrt_of_V1pm(K1, M, '-')
        V = g1 @ V2_op(K2, M) @ g1
        for mu in list(range(-M,_sage_const_0 )) + list(range(_sage_const_1 ,M+_sage_const_1 )):
            th = theta_mu_of(mu, M)
            A = A_of(th, K1, K2)
            Zm = hatZ_op(mu,M,'-'); Ym = hatY_op(mu,M)
            rep.close(T_conj(V, Zm), A[_sage_const_0 ,_sage_const_0 ]*Zm + A[_sage_const_1 ,_sage_const_0 ]*Ym, f"M={M} mu={mu}: T_(V)(hatZ^(-)) = A の第1列")
            rep.close(T_conj(V, Ym), A[_sage_const_0 ,_sage_const_1 ]*Zm + A[_sage_const_1 ,_sage_const_1 ]*Ym, f"M={M} mu={mu}: T_(V)(hatY) = A の第2列")
rep.finish()

