

# This file was *autogenerated* from the file /Users/masaori/git/masaori/math/.claude/worktrees/reflective-fluttering-panda/exact-solution-of-2d-ising-model/sagemath/check/192_claim_hatZ_hatY_M_periodicity/check_02_general_M_periodicity.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_1en6 = RealNumber('1e-6')# hatZ_hatY_M_periodicity（本文の主張の一般化）:
# 本文は mu = ±M の特殊値だけを述べているが、定義から従うのは一般の M 周期性である。
#   任意の mu ∈ Z, s ∈ {+,-} について  hatZ^{(s)}_{mu+M} = hatZ^{(s)}_{mu},  hatY_{mu+M} = hatY_{mu}
#
# ここではさらに「周期が M より小さくないこと」（M が最小周期であること）も反例探しとして確認する。
# 1 <= d < M について hatY_{mu+d} != hatY_mu を確かめる。これが破れていれば
# 「M 周期性」という言い方が弱すぎる（もっと強い性質がある）ことになる。
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '../../_shared/operators.sage'))

rep = CheckReport("hatZ_hatY_M_periodicity: 一般の mu ∈ Z についての M 周期性と最小性")

M_LIST = [_sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 ]

for M in M_LIST:
    Mi = int(M)
    # (1) 一般の mu についての M 周期性
    for mu in range(-_sage_const_3  * Mi, _sage_const_3  * Mi + _sage_const_1 ):
        for sign in ['+', '-']:
            rep.close(hatZ_op(mu + Mi, M, sign), hatZ_op(mu, M, sign),
                      "M=%d mu=%+d sign=%s: hatZ_{mu+M} = hatZ_mu" % (M, mu, sign))
        rep.close(hatY_op(mu + Mi, M), hatY_op(mu, M),
                  "M=%d mu=%+d: hatY_{mu+M} = hatY_mu" % (M, mu))

    # (2) 任意の整数 l 倍のシフトでも成り立つ
    for mu in [-Mi, -_sage_const_1 , _sage_const_1 , Mi]:
        for l in [-_sage_const_3 , -_sage_const_2 , _sage_const_2 , _sage_const_3 ]:
            rep.close(hatZ_op(mu + l * Mi, M, '-'), hatZ_op(mu, M, '-'),
                      "M=%d mu=%+d l=%+d: hatZ^{(-)}_{mu+lM} = hatZ^{(-)}_mu" % (M, mu, l))
            rep.close(hatY_op(mu + l * Mi, M), hatY_op(mu, M),
                      "M=%d mu=%+d l=%+d: hatY_{mu+lM} = hatY_mu" % (M, mu, l))

    # (3) 反例探し: 周期は M より真に小さくならない
    for mu in range(_sage_const_1 , Mi + _sage_const_1 ):
        for d in range(_sage_const_1 , Mi):
            gap = float(_np.max(_np.abs(hatY_op(mu + d, M) - hatY_op(mu, M))))
            rep.truth(gap > _sage_const_1en6 ,
                      "M=%d mu=%d d=%d: hatY_{mu+d} != hatY_mu（最大成分差 %.3e）" % (M, mu, d, gap))

rep.finish()

