

# This file was *autogenerated* from the file /Users/masaori/git/masaori/math/.claude/worktrees/reflective-fluttering-panda/exact-solution-of-2d-ising-model/sagemath/check/195_claim_anticommutator_of_hat_Z_and_hat_Y/check_03_hatZ_hatY_and_hatY_hatY.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2p0 = RealNumber('2.0')# anticommutator_of_hat_Z_and_hat_Y (3/4, 4/4):
#   [hatZ^{(±)}_mu, hatY_nu]_+ = 0
#   [hatY_mu, hatY_nu]_+ = 2M delta^M_{mu+nu,0} I
#
# 原文はこの 2 式を「同様」として証明を省いているので、数値検証の価値が高い。
# μ+ν が M の倍数になる場合とならない場合の両方を含める。
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '../../_shared/operators.sage'))

rep = CheckReport("anticommutator: [hatZ,hatY]_+ = 0 と [hatY,hatY]_+ = 2M δ I")

M_LIST = [_sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 ]
n_deg = _sage_const_0 
n_nondeg = _sage_const_0 

for M in M_LIST:
    Mi = int(M)
    calM = [m for m in range(-Mi, Mi + _sage_const_1 ) if m != _sage_const_0 ]
    Z = _np.zeros((_sage_const_2  ** Mi, _sage_const_2  ** Mi), dtype=complex)
    for mu in calM:
        for nu in calM:
            for sign in ['+', '-']:
                rep.close(acomm(hatZ_op(mu, M, sign), hatY_op(nu, M)), Z,
                          "M=%d sign=%s mu=%+d nu=%+d: [hatZ,hatY]_+ = 0" % (M, sign, mu, nu))
            rep.close(acomm(hatY_op(mu, M), hatY_op(nu, M)),
                      _sage_const_2p0  * float(Mi) * delta_M(mu + nu, _sage_const_0 , Mi) * eye_M(Mi),
                      "M=%d mu=%+d nu=%+d: [hatY,hatY]_+" % (M, mu, nu))
            if (mu + nu) % Mi == _sage_const_0 :
                n_deg += _sage_const_1 
            else:
                n_nondeg += _sage_const_1 

print("  μ+ν ≡ 0 (mod M) の組: %d 件、そうでない組: %d 件" % (n_deg, n_nondeg))
rep.truth(n_deg > _sage_const_0  and n_nondeg > _sage_const_0 , "両方の場合をカバーしている")

# 土台となる Z, Y の反交換関係（<anticommutator_of_Z_and_Y>）も併せて確認しておく。
# これが成り立たなければ上の 4 式の証明が成立しない。
for M in M_LIST:
    Mi = int(M)
    for j in range(_sage_const_1 , Mi + _sage_const_1 ):
        for k in range(_sage_const_1 , Mi + _sage_const_1 ):
            rep.close(acomm(Zop(j, M), Zop(k, M)),
                      _sage_const_2p0  * delta_M(j, k, Mi) * eye_M(Mi), "M=%d [Z_%d,Z_%d]_+" % (M, j, k))
            rep.close(acomm(Yop(j, M), Yop(k, M)),
                      _sage_const_2p0  * delta_M(j, k, Mi) * eye_M(Mi), "M=%d [Y_%d,Y_%d]_+" % (M, j, k))
            rep.close(acomm(Zop(j, M), Yop(k, M)),
                      _np.zeros((_sage_const_2  ** Mi, _sage_const_2  ** Mi), dtype=complex),
                      "M=%d [Z_%d,Y_%d]_+ = 0" % (M, j, k))

rep.finish()

