

# This file was *autogenerated* from the file /Users/masaori/git/masaori/math/.claude/worktrees/reflective-fluttering-panda/exact-solution-of-2d-ising-model/sagemath/check/195_claim_anticommutator_of_hat_Z_and_hat_Y/check_02_hatZ_mixed_sign.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_4p0 = RealNumber('4.0'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_8p0 = RealNumber('8.0'); _sage_const_1en12 = RealNumber('1e-12'); _sage_const_1en6 = RealNumber('1e-6')# anticommutator_of_hat_Z_and_hat_Y (2/4)  ← 補正項の符号と係数を厳密に検証する
#   [hatZ^{(±)}_mu, hatZ^{(∓)}_nu]_+
#     = 2M delta^M_{mu+nu,0} I + ( -2 exp(-i (2π/M)(mu+nu)) · 2 I )   （複号同順）
#
# 「複号同順」は (上,下) = ('+','-') と ('-','+') の 2 通り。両方を回す。
# μ+ν が M の倍数の場合／ならない場合の両方を必ず含める。
#
# 反例探し: 補正項の係数を -2·2 = -4 から ±2, -4 の符号反転, 位相の符号反転などに
# 変えた変種が破れることも確認し、係数・符号が一意であることを示す。
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '../../_shared/operators.sage'))

rep = CheckReport("anticommutator: [hatZ^{(±)}_mu, hatZ^{(∓)}_nu]_+ の補正項")

M_LIST = [_sage_const_2 , _sage_const_3 , _sage_const_4 , _sage_const_5 ]
PAIRS = [('+', '-'), ('-', '+')]   # 複号同順の 2 通り
n_deg = _sage_const_0 
n_nondeg = _sage_const_0 

for M in M_LIST:
    Mi = int(M)
    calM = [m for m in range(-Mi, Mi + _sage_const_1 ) if m != _sage_const_0 ]
    for (s1, s2) in PAIRS:
        for mu in calM:
            for nu in calM:
                lhs = acomm(hatZ_op(mu, M, s1), hatZ_op(nu, M, s2))
                phase = _np.exp(-_sage_const_1j  * (_sage_const_2  * _np.pi / float(Mi)) * float(mu + nu))
                rhs = (_sage_const_2p0  * float(Mi) * delta_M(mu + nu, _sage_const_0 , Mi) * eye_M(Mi)
                       + (-_sage_const_2p0  * phase * _sage_const_2p0  * eye_M(Mi)))
                rep.close(lhs, rhs,
                          "M=%d (%s,%s) mu=%+d nu=%+d" % (M, s1, s2, mu, nu))
                if (mu + nu) % Mi == _sage_const_0 :
                    n_deg += _sage_const_1 
                else:
                    n_nondeg += _sage_const_1 

print("  μ+ν ≡ 0 (mod M) の組: %d 件、そうでない組: %d 件" % (n_deg, n_nondeg))
rep.truth(n_deg > _sage_const_0  and n_nondeg > _sage_const_0 , "両方の場合をカバーしている")

# --- 反例探し: 補正項の係数・符号の変種が破れること ---
VARIANTS = [
    ("係数を +4 にする", +_sage_const_4p0 , -_sage_const_1p0 ),
    ("係数を -2 にする", -_sage_const_2p0 , -_sage_const_1p0 ),
    ("係数を -8 にする", -_sage_const_8p0 , -_sage_const_1p0 ),
    ("位相の符号を反転する", -_sage_const_4p0 , +_sage_const_1p0 ),
]
n_skipped = _sage_const_0 
for M in [_sage_const_3 , _sage_const_4 , _sage_const_5 ]:
    Mi = int(M)
    for (s1, s2) in PAIRS:
        for (mu, nu) in [(_sage_const_1 , _sage_const_1 ), (_sage_const_1 , _sage_const_2 ), (_sage_const_1 , -_sage_const_1 ), (_sage_const_2 , -_sage_const_2 ), (Mi, -Mi)]:
            lhs = acomm(hatZ_op(mu, M, s1), hatZ_op(nu, M, s2))
            true_term = -_sage_const_4p0  * _np.exp(-_sage_const_1j  * (_sage_const_2  * _np.pi / float(Mi)) * float(mu + nu))
            for (name, coef, psign) in VARIANTS:
                var_term = coef * _np.exp(psign * _sage_const_1j  * (_sage_const_2  * _np.pi / float(Mi)) * float(mu + nu))
                if abs(var_term - true_term) < _sage_const_1en12 :
                    # この (μ,ν) では変種が本文の式と数値的に一致してしまい判定できない
                    n_skipped += _sage_const_1 
                    continue
                rhs = (_sage_const_2p0  * float(Mi) * delta_M(mu + nu, _sage_const_0 , Mi) * eye_M(Mi)
                       + var_term * eye_M(Mi))
                r = float(_np.max(_np.abs(lhs - rhs)))
                rep.truth(r > _sage_const_1en6 ,
                          "M=%d (%s,%s) μ=%+d ν=%+d 変種「%s」は破れる（残差 %.3f）"
                          % (M, s1, s2, mu, nu, name, r))
print("  変種判定: %d 件は本文の式と数値的に一致するため判定不能としてスキップ" % n_skipped)

rep.finish()

