

# This file was *autogenerated* from the file tau_v2_verify.sage
from sage.all_cmdline import *   # import sage library

_sage_const_78 = Integer(78); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_15 = Integer(15); _sage_const_17 = Integer(17); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_14 = Integer(14)# cycle 13 / T1: 観察 T の決着 — v_2(tau(L)) の厳密計算と、証明の各ステップの検証
#
# tau(L) = L×L トーラス(周期境界の正方格子)の全域木数。
# 観察 T: 奇 L に対し v_2(tau(L)) = 2(L-1)。
#
# 本スクリプトは次を検証する。
#   (1) tau(L) を Kirchhoff の matrix-tree 定理で厳密整数計算し、v_2 を求める(奇偶の両方)。
#   (2) 証明で使う分解 tau(L) = prod_{j=1}^{L-1} (r_j^L + r_j^{-L} - 2) を厳密に確認する。
#   (3) 証明の核 v(m_j) = 1 を、m_j の満たす2次方程式の Newton 多角形から確認する。
#   (4) 偶 L で証明が破れる箇所を具体的に確認する。

print("=" * _sage_const_78 )
print("cycle 13 / T1: 観察 T (奇 L で v_2(tau(L)) = 2(L-1)) の決着")
print("=" * _sage_const_78 )

def torus_spanning_trees(L):
    """L×L トーラスの全域木数を Kirchhoff の matrix-tree 定理で厳密整数計算する。"""
    n = L * L
    idx = lambda i, j: (i % L) * L + (j % L)
    M = matrix(ZZ, n, n)
    for i in range(L):
        for j in range(L):
            a = idx(i, j)
            for (di, dj) in ((_sage_const_1 , _sage_const_0 ), (-_sage_const_1 , _sage_const_0 ), (_sage_const_0 , _sage_const_1 ), (_sage_const_0 , -_sage_const_1 )):
                b = idx(i + di, j + dj)
                if a == b:
                    continue
                M[a, a] += _sage_const_1 
                M[a, b] -= _sage_const_1 
    return M.submatrix(_sage_const_0 , _sage_const_0 , n - _sage_const_1 , n - _sage_const_1 ).determinant()

print()
print("--- (1) tau(L) の厳密計算と v_2 ---")
print(" L  parity  v_2(tau(L))  2(L-1)  一致  桁数")
odd_ok = True
odd_range = [_sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_9 , _sage_const_11 , _sage_const_13 , _sage_const_15 , _sage_const_17 ]
even_range = [_sage_const_2 , _sage_const_4 , _sage_const_6 , _sage_const_8 , _sage_const_10 , _sage_const_12 , _sage_const_14 ]
for L in sorted(odd_range + even_range):
    t = torus_spanning_trees(L)
    v = t.valuation(_sage_const_2 )
    par = "odd " if L % _sage_const_2  else "even"
    match = (v == _sage_const_2  * (L - _sage_const_1 )) if L % _sage_const_2  else None
    if L % _sage_const_2  and not match:
        odd_ok = False
    print("%2d  %s   v_2=%4d      %4d   %s   %d"
          % (L, par, v, _sage_const_2  * (L - _sage_const_1 ), str(match), len(str(t))))
print()
print("奇 L=3..17 で観察 T が全一致: %s" % odd_ok)
print("偶 L では 2(L-1) と一致しない(上表)。観察 T は奇 L 限定の主張である。")

print()
print("--- (2) 分解 tau(L) = prod_{j=1}^{L-1} (r_j^L + r_j^{-L} - 2) の厳密確認 ---")
print("  A_j = 4 - (z^j + z^-j), r_j + 1/r_j = A_j とし、s_n = r^n + r^-n を")
print("  s_n = A s_{n-1} - s_{n-2}, s_0=2, s_1=A で生成する(整数係数の漸化)。")
print("  D_j = s_L(A_j) - 2 として prod_j D_j が tau(L) に一致するかを円分体上で確認する。")
for L in [_sage_const_3 , _sage_const_4 , _sage_const_5 , _sage_const_6 , _sage_const_7 , _sage_const_9 ]:
    K = CyclotomicField(L)
    zeta = K.gen()
    prod_D = K(_sage_const_1 )
    for j in range(_sage_const_1 , L):
        A = K(_sage_const_4 ) - (zeta**j + zeta**(-j))
        s_prev, s_cur = K(_sage_const_2 ), A          # s_0, s_1
        for _ in range(_sage_const_2 , L + _sage_const_1 ):
            s_prev, s_cur = s_cur, A * s_cur - s_prev
        prod_D *= (s_cur - K(_sage_const_2 ))
    tau = torus_spanning_trees(L)
    ok = (prod_D == K(tau))
    print("  L=%2d: prod_j D_j == tau(L) ? %s" % (L, ok))

print()
print("--- (3) 証明の核: v(m_j) = 1 の確認 ---")
print("  r_j = zeta^j (1 + m_j) と置くと m_j は")
print("    zeta^j m^2 + (3 zeta^j + zeta^-j - 4) m - 2 (1-zeta^j)(1-zeta^-j) = 0")
print("  を満たす。奇 L では 2 は Z[zeta_L] で不分岐、1-zeta^j は 2 で単数、")
print("  線型係数も 2 で単数、定数項の付値はちょうど 1。よって Newton 多角形から")
print("  2根の付値は 0 と 1 で、m_j ≡ 0 (mod p) 側の根は v(m_j) = 1。")
print()
for L in [_sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_9 , _sage_const_11 , _sage_const_13 ]:
    K = CyclotomicField(L)
    zeta = K.gen()
    P = K.primes_above(_sage_const_2 )[_sage_const_0 ]
    fdeg = P.residue_class_degree()
    e = P.ramification_index()
    lines = []
    all_ok = True
    for j in range(_sage_const_1 , L):
        a = zeta**j
        b = _sage_const_3  * zeta**j + zeta**(-j) - _sage_const_4 
        c = -_sage_const_2  * (_sage_const_1  - zeta**j) * (_sage_const_1  - zeta**(-j))
        va, vb, vc = a.valuation(P), b.valuation(P), c.valuation(P)
        ok = (va == _sage_const_0  and vb == _sage_const_0  and vc == _sage_const_1 )
        all_ok = all_ok and ok
        lines.append((j, va, vb, vc, ok))
    print("  L=%2d: 2 の分岐指数 e=%d(不分岐なら 1), 剰余次数 f=%d" % (L, e, fdeg))
    print("        全 j=1..%d で v(lead)=0, v(linear)=0, v(const)=1 : %s"
          % (L - _sage_const_1 , all_ok))
    if not all_ok:
        print("        内訳:", lines)

print()
print("--- (4) 偶 L で証明が破れる箇所 ---")
print("  奇 L の証明は次の2点を使う。")
print("    (i) 1 - zeta^j が 2 で単数(2 が Z[zeta_L] で不分岐であることによる)")
print("    (ii) v(L) = 0 なので u^L - 1 = L m + C(L,2) m^2 + ... の主要項が L m")
print("  偶 L ではどちらも壊れる。実際に確認する。")
for L in [_sage_const_4 , _sage_const_6 , _sage_const_8 ]:
    K = CyclotomicField(L)
    zeta = K.gen()
    P = K.primes_above(_sage_const_2 )[_sage_const_0 ]
    e = P.ramification_index()
    j0 = L // _sage_const_2 
    val = (_sage_const_1  - zeta**j0).valuation(P) if (_sage_const_1  - zeta**j0) != _sage_const_0  else None
    print("  L=%2d: 2 の分岐指数 e=%d (>1 なら分岐), v_P(1 - zeta^(L/2)) = %s, v_2(L) = %d"
          % (L, e, str(val), ZZ(L).valuation(_sage_const_2 )))
print("  ⇒ 偶 L では (i)(ii) がともに成立せず、証明は適用できない。")
print("     (1) の表が示すとおり実際に v_2(tau(L)) ≠ 2(L-1) である。")

print()
print("=" * _sage_const_78 )
print("結論: 観察 T は奇 L=3..17 で厳密に成立し、証明の各前提((3) の付値条件)も")
print("      全 j で満たされることを確認した。偶 L では前提が壊れ、結論も成立しない。")
print("=" * _sage_const_78 )

