

# This file was *autogenerated* from the file check_02_convergence_definition.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_5100 = Integer(5100); _sage_const_1p0 = RealNumber('1.0'); _sage_const_5200 = Integer(5200); _sage_const_1 = Integer(1); _sage_const_16 = Integer(16); _sage_const_64 = Integer(64); _sage_const_256 = Integer(256); _sage_const_5300 = Integer(5300); _sage_const_0p0 = RealNumber('0.0'); _sage_const_10 = Integer(10); _sage_const_100 = Integer(100); _sage_const_1000 = Integer(1000); _sage_const_0 = Integer(0); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p4 = RealNumber('0.4'); _sage_const_5400 = Integer(5400); _sage_const_0p3 = RealNumber('0.3'); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p5j = ComplexNumber(0, '0.5'); _sage_const_400 = Integer(400); _sage_const_5 = Integer(5); _sage_const_20 = Integer(20); _sage_const_399 = Integer(399)# ---------------------------------------------------------
# <def_matrix_norm> の「収束」の定義が、成分ごとの収束と同じものを指すことを確認する。
#
# 定義: A_N → A ⟺ ‖A_N − A‖ → 0。
# 独立経路: 成分ごとの最大絶対差 d_N := max_{i,j} |(A_N)_ij − A_ij|。
#   有限次元では ‖·‖ と max|·| は同値なノルムで、n×n 行列について
#       d_N ≤ ‖A_N − A‖ ≤ n · d_N
#   が成り立つ。これを実際の収束列で数値的に確認する（同語反復ではなく、
#   「ノルム収束 ⟺ 成分収束」という本文が暗に使っている事実の検査）。
#
# 併せて、級数 Σ B_m := lim S_N（S_N = Σ_{m≤N} B_m）の定義が、
# 独立に計算できる閉じた極限（等比級数）と一致することを確認する。
#
# 対象: structured-latex def_matrix_norm
# ---------------------------------------------------------
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '../../_shared/operators.sage'))
load(os.path.join(_dir, '_prelude.sage'))
import numpy as np

rep = CheckReport("def_matrix_norm: 収束の定義（ノルム収束 ⟺ 成分収束、級数の定義）")

# --- 1. ノルム収束 ⟺ 成分収束 -----------------------------------------
for n in [_sage_const_2 , _sage_const_4 , _sage_const_8 ]:
    A = rand_mat(n, _sage_const_5100  + n, _sage_const_1p0 )
    C = rand_mat(n, _sage_const_5200  + n, _sage_const_1p0 )
    print("n=%d: N, ‖A_N-A‖, max|成分差|, 比" % n)
    for N in [_sage_const_1 , _sage_const_4 , _sage_const_16 , _sage_const_64 , _sage_const_256 ]:
        AN = A + C / float(N)
        d = float(np.max(np.abs(AN - A)))
        f = fro(AN - A)
        rep.truth(le_ok(d, f), "n=%d,N=%d: max|成分差| ≤ ‖·‖" % (n, N))
        rep.truth(le_ok(f, n * d), "n=%d,N=%d: ‖·‖ ≤ n·max|成分差|" % (n, N))
        print("   N=%3d  %.6e  %.6e  %.4f" % (N, f, d, f / d))

# 逆向き: 成分が収束しない列はノルムでも収束しない（定義の非退化性）
A = rand_mat(_sage_const_4 , _sage_const_5300 , _sage_const_1p0 )
worst = _sage_const_0p0 
for N in [_sage_const_10 , _sage_const_100 , _sage_const_1000 ]:
    AN = A.copy()
    AN[_sage_const_0 , _sage_const_0 ] = AN[_sage_const_0 , _sage_const_0 ] + _sage_const_0p5    # 1 成分だけずらしたまま
    worst = max(worst, fro(AN - A))
rep.truth(worst >= _sage_const_0p4 , "1 成分がずれ続ける列は ‖A_N−A‖→0 にならない（実測 %.3f）" % worst)

# --- 2. 級数の定義 Σ B_m = lim S_N -----------------------------------
# B_m := r^m C（|r|<1）とすると Σ_{m=0}^{∞} B_m = (1-r)^{-1} C（等比級数、閉形式）。
# S_N を素朴に足した結果がこの閉形式へノルム収束することを確認する。
C = rand_mat(_sage_const_4 , _sage_const_5400 , _sage_const_1p0 )
for r in [_sage_const_0p5 , -_sage_const_0p3 , _sage_const_0p9 , _sage_const_0p5  + _sage_const_0p5j ]:
    S_inf = C / (_sage_const_1p0  - r)
    S = np.zeros((_sage_const_4 , _sage_const_4 ), dtype=complex)
    prev = None
    for m in range(_sage_const_0 , _sage_const_400 ):
        S = S + (r ** m) * C
        if m in (_sage_const_0 , _sage_const_1 , _sage_const_5 , _sage_const_20 , _sage_const_100 , _sage_const_399 ):
            prev = fro(S - S_inf)
    rep.close(S, S_inf, "Σ_{m} r^m C = (1-r)^{-1} C  (r=%s)" % (r,))
    print("r=%s: ‖S_399 − S‖ = %.3e" % (r, prev))

rep.finish()

