

# This file was *autogenerated* from the file sagemath/check/047_claim_even_sector_T_action/check_03_T_actions.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0p0 = RealNumber('0.0'); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)# ---------------------------------------------------------
# SageMath: T_{(V_1^{(+)})^{1/2}} と T_{V_2} の checkZ, checkY への作用
#
# 対象: structured-latex T_actions_on_check_Z_Y
#       （併せて calc_of_TxT_check_Z_Y：右から B_1(th~), B_2 を掛けること）
#
#   T_{(V_1^{(+)})^{1/2}}(checkZ_mu) = cosh(K1) checkZ_mu + i e^{-i th~} sinh(K1) checkY_mu
#   T_{(V_1^{(+)})^{1/2}}(checkY_mu) = -i e^{i th~} sinh(K1) checkZ_mu + cosh(K1) checkY_mu
#   T_{V_2}(checkZ_mu)               = cosh(2K2*) checkZ_mu - i sinh(2K2*) checkY_mu
#   T_{V_2}(checkY_mu)               = i sinh(2K2*) checkZ_mu + cosh(2K2*) checkY_mu
#
#   (T(checkZ), T(checkY)) = (checkZ, checkY) B_1(th~_mu)   （V_1 分）
#   (T(checkZ), T(checkY)) = (checkZ, checkY) B_2           （V_2 分）
#
# T_g(X) = g X g^{-1} を行列指数関数から直接計算する（級数展開に依存しない独立経路）。
# V_2 は前因子 (2 s_2)^{M/2} を明示的に付けて相殺も確認する。
# ---------------------------------------------------------
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if '__file__' in dir() else '.'
load(os.path.join(_dir, '_prelude.sage'))

print("=== T_{(V_1^{(+)})^{1/2}}, T_{V_2} の作用と B_1(th~), B_2 による右乗 ===")
all_ok = True
for M in EVEN_M:
    O = SpinOps(M)
    for params in EVEN_PARAMS:
        K1v = RDF(params['K1'])
        K2v = RDF(params['K2'])
        K2s = K_star(K2v)
        E1, E1inv = V1p_half(O, K1v)
        E2, E2inv = V2_mat(O, K2v)
        Bmat2 = B2(K2s)
        w = {'TV1(Z)': _sage_const_0p0 , 'TV1(Y)': _sage_const_0p0 , 'TV2(Z)': _sage_const_0p0 , 'TV2(Y)': _sage_const_0p0 ,
             'B1col': _sage_const_0p0 , 'B2col': _sage_const_0p0 }
        for mu in range(_sage_const_1 , M + _sage_const_1 ):
            t = th_tilde(M, mu)
            Zc, Yc = checkZ(O, mu), checkY(O, mu)
            ch1, sh1 = CDF(cosh(K1v)), CDF(sinh(K1v))
            ch2, sh2 = CDF(cosh(_sage_const_2  * K2s)), CDF(sinh(_sage_const_2  * K2s))
            TV1Z = E1 * Zc * E1inv
            TV1Y = E1 * Yc * E1inv
            TV2Z = E2 * Zc * E2inv
            TV2Y = E2 * Yc * E2inv
            w['TV1(Z)'] = max(w['TV1(Z)'], opnorm(
                TV1Z - (ch1 * Zc + CDF(I) * eiph(-t) * sh1 * Yc)))
            w['TV1(Y)'] = max(w['TV1(Y)'], opnorm(
                TV1Y - (-CDF(I) * eiph(t) * sh1 * Zc + ch1 * Yc)))
            w['TV2(Z)'] = max(w['TV2(Z)'], opnorm(
                TV2Z - (ch2 * Zc - CDF(I) * sh2 * Yc)))
            w['TV2(Y)'] = max(w['TV2(Y)'], opnorm(
                TV2Y - (CDF(I) * sh2 * Zc + ch2 * Yc)))
            # 行ベクトル×行列の形で確認: (T(Z), T(Y)) = (Z, Y) B
            Bmat1 = B1(K1v, t)
            w['B1col'] = max(w['B1col'],
                             opnorm(TV1Z - combine(Zc, Yc, Bmat1.column(_sage_const_0 ))),
                             opnorm(TV1Y - combine(Zc, Yc, Bmat1.column(_sage_const_1 ))))
            w['B2col'] = max(w['B2col'],
                             opnorm(TV2Z - combine(Zc, Yc, Bmat2.column(_sage_const_0 ))),
                             opnorm(TV2Y - combine(Zc, Yc, Bmat2.column(_sage_const_1 ))))
        worst = max(w.values())
        ok = worst <= TOL
        print(f"  M={M}, K1={params['K1']}, K2={params['K2']}: "
              f"TV1(Z) {w['TV1(Z)']:.1e} TV1(Y) {w['TV1(Y)']:.1e} "
              f"TV2(Z) {w['TV2(Z)']:.1e} TV2(Y) {w['TV2(Y)']:.1e} | "
              f"B1 右乗 {w['B1col']:.1e}, B2 右乗 {w['B2col']:.1e}"
              f"  -> {'PASS' if ok else 'FAIL'}")
        all_ok = ok and all_ok

print("RESULT: PASS" if all_ok else "RESULT: FAIL")

