

# This file was *autogenerated* from the file pi_p1_refined.sage
from sage.all_cmdline import *   # import sage library

_sage_const_20000 = Integer(20000); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_70 = Integer(70); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11)# cycle 8 / T3: π(p,1) の精密公式と等号条件。
# Tr T^N mod p = Σ_λ (m_λ mod p) λ^N (λ=相異固有値∈F̄_p, m_λ=代数的重複度)。
# 相異 λ の幾何列 λ^N は一次独立 ⇒ 周期 = lcm{ord(λ): m_λ ≢ 0 mod p}。
# よって π(p,1) = lcm{ord(λ): p ∤ m_λ}。 lcm{全 λ の ord} との等号は『全 order 寄与固有値の mult が p∤』のとき。

def trace_period_mod_p(T,p,maxN=_sage_const_20000 ):
    R=GF(p); Tm=T.change_ring(R)
    seenM={}; N=_sage_const_0 ; Pk=identity_matrix(R,T.nrows())
    while N<=maxN:
        Pk=Pk*Tm; N+=_sage_const_1 
        key=tuple(Pk.list())
        if key in seenM:
            pre=seenM[key]; per=N-seenM[key]
            tr=[ZZ((Tm**j).trace()) for j in range(_sage_const_1 ,pre+_sage_const_2 *per+_sage_const_1 )]
            for d in divisors(per):
                if all(tr[i]==tr[i+d] for i in range(pre,len(tr)-d-_sage_const_1 )): return d
            return per
        seenM[key]=N
    return None

def orders_and_mult(T,p):
    # 相異固有値の (ord, 代数的重複度) を F̄_p で
    R=GF(p); cp=T.charpoly().change_ring(R)
    res=[]
    for f,mult in cp.factor():
        d=f.degree(); Fq=GF(p**d,'a')
        for r,_ in f.change_ring(Fq).roots():
            if r==_sage_const_0 : res.append((_sage_const_0 ,mult)); continue
            res.append((r.multiplicative_order(), mult))
    return res

def lcm_all(om):
    L=_sage_const_1 
    for o,m in om:
        if o==_sage_const_0 : continue
        L=lcm(L,o)
    return L
def lcm_refined(om,p):
    L=_sage_const_1 
    for o,m in om:
        if o==_sage_const_0 : continue
        if m%p!=_sage_const_0 : L=lcm(L,o)
    return L

def L_ops(a,b,c):
    return [[matrix(ZZ,[[a,_sage_const_0 ],[_sage_const_0 ,b]]),matrix(ZZ,[[_sage_const_0 ,_sage_const_0 ],[c,_sage_const_0 ]])],
            [matrix(ZZ,[[_sage_const_0 ,c],[_sage_const_0 ,_sage_const_0 ]]),matrix(ZZ,[[b,_sage_const_0 ],[_sage_const_0 ,a]])]]
def embed(op,i,L):
    I2=identity_matrix(ZZ,_sage_const_2 ); m=[op if k==i else I2 for k in range(L)]
    M=m[_sage_const_0 ]
    for k in range(_sage_const_1 ,L): M=M.tensor_product(m[k])
    return M
def transfer_matrix(L,a,b,c):
    dim=_sage_const_2 **L; Lo=L_ops(a,b,c)
    M=[[identity_matrix(ZZ,dim),zero_matrix(ZZ,dim)],[zero_matrix(ZZ,dim),identity_matrix(ZZ,dim)]]
    for i in range(L):
        Li=[[embed(Lo[r][s],i,L) for s in range(_sage_const_2 )] for r in range(_sage_const_2 )]
        M=[[M[_sage_const_0 ][_sage_const_0 ]*Li[_sage_const_0 ][_sage_const_0 ]+M[_sage_const_0 ][_sage_const_1 ]*Li[_sage_const_1 ][_sage_const_0 ], M[_sage_const_0 ][_sage_const_0 ]*Li[_sage_const_0 ][_sage_const_1 ]+M[_sage_const_0 ][_sage_const_1 ]*Li[_sage_const_1 ][_sage_const_1 ]],
           [M[_sage_const_1 ][_sage_const_0 ]*Li[_sage_const_0 ][_sage_const_0 ]+M[_sage_const_1 ][_sage_const_1 ]*Li[_sage_const_1 ][_sage_const_0 ], M[_sage_const_1 ][_sage_const_0 ]*Li[_sage_const_0 ][_sage_const_1 ]+M[_sage_const_1 ][_sage_const_1 ]*Li[_sage_const_1 ][_sage_const_1 ]]]
    return M[_sage_const_0 ][_sage_const_0 ]+M[_sage_const_1 ][_sage_const_1 ]

print("="*_sage_const_70 )
print("π(p,1) 精密公式: = lcm{ord(λ): p∤mult_λ}")
print("="*_sage_const_70 )
ok_ref=_sage_const_0 ; tot=_sage_const_0 ; strict=_sage_const_0 
for (a,b,c,L) in [(_sage_const_1 ,_sage_const_1 ,_sage_const_2 ,_sage_const_2 ),(_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_2 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_1 ,_sage_const_2 ),(_sage_const_1 ,_sage_const_1 ,_sage_const_2 ,_sage_const_3 ),(_sage_const_2 ,_sage_const_1 ,_sage_const_3 ,_sage_const_2 ),(_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_3 ),(_sage_const_3 ,_sage_const_2 ,_sage_const_1 ,_sage_const_2 ),(_sage_const_1 ,_sage_const_3 ,_sage_const_2 ,_sage_const_2 )]:
    T=transfer_matrix(L,a,b,c); dt=ZZ(T.det())
    for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ]:
        if dt%p==_sage_const_0 : continue
        pi=trace_period_mod_p(T,p)
        if pi is None: continue
        om=orders_and_mult(T,p)
        la=lcm_all(om); lr=lcm_refined(om,p)
        tot+=_sage_const_1 
        if pi==lr: ok_ref+=_sage_const_1 
        if lr!=la: strict+=_sage_const_1 
        mark = "OK" if pi==lr else "✗MISMATCH"
        extra = "  [精密<全: mult≡0 脱落あり]" if lr!=la else ""
        print(f"  ({a},{b},{c})L{L} p={p}: π={pi}, lcm_refined={lr}, lcm_all={la} [{mark}]{extra}")
print(f"\n  合計 {tot}: π=lcm_refined が {ok_ref} 件; lcm_refined<lcm_all(mult≡0脱落) が {strict} 件")
print("\n"+"="*_sage_const_70 )
print("結論: π(p,1) = lcm{ord(λ): p∤mult_λ}(一次独立より, rigorous)。")
print(" 等号 π=lcm_all は『order に効く全固有値の重複度が p∤』のとき。")
print(" mult≡0 mod p の固有値はトレース mod p から脱落し周期を下げうる(精密<全)。")
print("="*_sage_const_70 )

