

# This file was *autogenerated* from the file check_01_eigen.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_2 = Integer(2); _sage_const_2p0 = RealNumber('2.0'); _sage_const_0p3 = RealNumber('0.3'); _sage_const_0p4407 = RealNumber('0.4407'); _sage_const_0p6 = RealNumber('0.6'); _sage_const_1p1 = RealNumber('1.1'); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_1en10 = RealNumber('1e-10'); _sage_const_0p7j = ComplexNumber(0, '0.7'); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p1j = ComplexNumber(0, '0.1'); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_1en12 = RealNumber('1e-12')# <eigenvector_of_A_theta>: 固有値 lambda_± と固有ベクトル v_±
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np

def crit_K1(K2):
    """臨界条件 sinh(2K_1) sinh(2K_2) = 1 をちょうど満たす K_1。"""
    return float(np.arcsinh(_sage_const_1p0 /np.sinh(_sage_const_2 *K2))/_sage_const_2p0 )

CRIT_PARAMS = [{"K1": crit_K1(k2), "K2": k2} for k2 in [_sage_const_0p3 , _sage_const_0p4407 , _sage_const_0p6 , _sage_const_1p1 ]]
ALL_PARAMS = list(OP_TEST_PARAMS) + CRIT_PARAMS

rep = CheckReport("eigenvector_of_A_theta")
ngz = _sage_const_0 ; nz = _sage_const_0 
for M in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ,_sage_const_8 ]:
    for p in ALL_PARAMS:
        K1, K2 = p['K1'], p['K2']
        for mu in list(range(-M,_sage_const_0 )) + list(range(_sage_const_1 ,M+_sage_const_1 )):
            th = theta_mu_of(mu, M)
            A = A_of(th,K1,K2)
            g2p = gamma2_of(th,K1,K2); g2m = gamma2_of(-th,K1,K2)
            lp, lm = lambda_pm_of(mu,M,K1,K2)
            if abs(g2p) < _sage_const_1en10 :
                nz += _sage_const_1 
                rep.close(A, np.eye(_sage_const_2 ), f"M={M} mu={mu}: gamma_2=0 なら A = I")
                # 任意のベクトルが固有ベクトル
                v = np.array([_sage_const_0p3 +_sage_const_0p7j , -_sage_const_1p2 +_sage_const_0p1j ])
                rep.close(A @ v, lp*v, f"M={M} mu={mu}: gamma_2=0 で任意の v が固有ベクトル")
            else:
                ngz += _sage_const_1 
                r = sqrt_cc_np(g2p*g2m)
                for s, lam in [(+_sage_const_1 , lp), (-_sage_const_1 , lm)]:
                    v = np.array([s*_sage_const_1j *r, g2m])
                    rep.close(A @ v, lam*v, f"M={M} mu={mu} s={s}: A v = lambda v")
                    rep.truth(np.linalg.norm(v) > _sage_const_1en12 , f"M={M} mu={mu} s={s}: v != 0")
print(f"  gamma_2 != 0 の事例 {ngz} 件、gamma_2 = 0 の事例 {nz} 件")
rep.finish()

