

# This file was *autogenerated* from the file check_02_limit_uniqueness.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_1en12 = RealNumber('1e-12'); _sage_const_4 = Integer(4); _sage_const_8001 = Integer(8001); _sage_const_8002 = Integer(8002); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_64 = Integer(64); _sage_const_256 = Integer(256); _sage_const_1024 = Integer(1024); _sage_const_4096 = Integer(4096); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_10p0 = RealNumber('10.0'); _sage_const_8100 = Integer(8100); _sage_const_2en3 = RealNumber('2e-3'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_1en2 = RealNumber('1e-2')# <matrix_norm_triangle_inequality> (4) 極限の一意性: A_N -> A かつ A_N -> A' ならば A = A'
#
# 数値でこれを「そのまま」確かめることはできない（A=A' は極限の話）。
# そこで本文の証明の骨格そのものを検査する:
#   ||A - A'|| <= ||A_N - A|| + ||A_N - A'||   （三角不等式）
# 右辺が 0 に落ちるなら左辺（N に依らない定数）は 0 でなければならない。
#
#   (a) 収束列 A_N -> A を作り、A' := A + δ（δ != O）を候補にすると
#       ||A_N - A'|| は ||δ|| へ収束し 0 には落ちない（＝別の極限は存在しない）。
#   (b) 三角不等式による評価が全 N で成り立つ。
#   (c) δ を 0 に近づけると、区別できる N が大きくなるだけで、δ != O なら必ず区別できる。
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
rep = CheckReport("matrix_norm_triangle_inequality (4) 極限の一意性")

def fro(A):
    return float(np.linalg.norm(np.asarray(A, dtype=complex)))
def rand_mat(n, seed, scale=_sage_const_1p0 ):
    g = np.random.default_rng(int(seed))
    return float(scale)*(g.standard_normal((int(n),int(n))) + _sage_const_1j *g.standard_normal((int(n),int(n))))
def le_ok(x, y, slack=_sage_const_1en12 ):
    x = float(x); y = float(y)
    return x <= y + float(slack)*max(_sage_const_1p0 , abs(x), abs(y))

A = rand_mat(_sage_const_4 , _sage_const_8001 , _sage_const_1p0 )
C = rand_mat(_sage_const_4 , _sage_const_8002 , _sage_const_1p0 )      # A_N := A + C/N（A へ収束する列）
Ns = [_sage_const_1 ,_sage_const_2 ,_sage_const_4 ,_sage_const_8 ,_sage_const_16 ,_sage_const_64 ,_sage_const_256 ,_sage_const_1024 ,_sage_const_4096 ]

for e in [_sage_const_0 ,-_sage_const_2 ,-_sage_const_4 ,-_sage_const_6 ,-_sage_const_8 ]:
    delta = (_sage_const_10p0 **e)*rand_mat(_sage_const_4 , _sage_const_8100 +e, _sage_const_1p0 )
    Ap = A + delta
    d = fro(delta)
    tail = None
    for N in Ns:
        AN = A + C/float(N)
        lhs = fro(A - Ap)
        rhs = fro(AN - A) + fro(AN - Ap)
        rep.truth(le_ok(lhs, rhs),
                  f"(4) ||A-A'|| <= ||A_N-A||+||A_N-A'|| (||δ||={d:.1e}, N={N})")
        tail = fro(AN - Ap)
    # δ != O なら ||A_N - A'|| は ||δ|| へ張り付き、0 には落ちない。
    # A_N - A' = C/N - δ なので、逆向きの三角不等式より
    #   | ||A_N-A'|| - ||δ|| | <= ||C||/N
    # これが N -> ∞ で 0 になることが「||A_N-A'|| -> ||δ||」の中身である。
    gap = abs(tail - d)
    rep.truth(le_ok(gap, fro(C)/float(Ns[-_sage_const_1 ])),
              f"(4) | ||A_N-A'|| - ||δ|| | <= ||C||/N (||δ||={d:.1e}, N={Ns[-1]})")
    rep.truth(gap < _sage_const_2en3 , f"(4) ||A_N-A'|| -> ||δ|| （N={Ns[-_sage_const_1 ]} での差 {gap:.3e}）")
    rep.truth(tail > _sage_const_0p5 *d, f"(4) δ != O なら ||A_N-A'|| は 0 に落ちない (||δ||={d:.1e})")
    print("||δ||=%.1e: ||A_%d-A||=%.3e, ||A_%d-A'||=%.3e"
          % (d, Ns[-_sage_const_1 ], fro(C/float(Ns[-_sage_const_1 ])), Ns[-_sage_const_1 ], tail))

# δ = O（同じ極限）のときは ||A_N - A'|| = ||C||/N で 0 へ落ちる
for N in Ns:
    rep.close(fro(C/float(N)), fro(C)/float(N), f"(4) δ=O: ||A_N-A'|| = ||C||/N (N={N})")
tail0 = fro(C/float(Ns[-_sage_const_1 ]))
rep.truth(tail0 < _sage_const_1en2 , f"(4) δ=O のときは ||A_N-A'|| -> 0（実測 {tail0:.3e}）")

rep.finish()

