

# This file was *autogenerated* from the file check_01_matrix_form.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_0p37 = RealNumber('0.37'); _sage_const_0p21j = ComplexNumber(0, '0.21'); _sage_const_1p1 = RealNumber('1.1'); _sage_const_0p6j = ComplexNumber(0, '0.6')# <calc_of_TxT_hatZxhatY>: (T x T)(hatZ^{(-)}, hatY) = (hatZ^{(-)}, hatY) B  の行列表示 B_1, B_2
import os
_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else "."
load(os.path.join(_dir, "../../_shared/operators.sage"))
import numpy as np
rep = CheckReport("calc_of_TxT_hatZxhatY: 直積作用の 2x2 行列表示")
for M in [_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]:
    rng_mu = list(range(-M,_sage_const_0 )) + list(range(_sage_const_1 ,M+_sage_const_1 ))
    for p in OP_TEST_PARAMS[:_sage_const_4 ]:
        K1 = p['K1']; K2 = p['K2']
        for mu in rng_mu:
            th = theta_mu_of(mu, M)
            Zm = hatZ_op(mu,M,'-'); Ym = hatY_op(mu,M)
            B1 = B1_of(th, K1); B2 = B2_of(K2)
            g1 = principal_sqrt_of_V1pm(K1, M, '-')
            g2 = V2_op(K2, M)
            # 列ごとに (hatZ, hatY) B の各成分と突き合わせる
            rep.close(T_conj(g1, Zm), B1[_sage_const_0 ,_sage_const_0 ]*Zm + B1[_sage_const_1 ,_sage_const_0 ]*Ym, f"M={M} mu={mu}: B_1 の第1列")
            rep.close(T_conj(g1, Ym), B1[_sage_const_0 ,_sage_const_1 ]*Zm + B1[_sage_const_1 ,_sage_const_1 ]*Ym, f"M={M} mu={mu}: B_1 の第2列")
            rep.close(T_conj(g2, Zm), B2[_sage_const_0 ,_sage_const_0 ]*Zm + B2[_sage_const_1 ,_sage_const_0 ]*Ym, f"M={M} mu={mu}: B_2 の第1列")
            rep.close(T_conj(g2, Ym), B2[_sage_const_0 ,_sage_const_1 ]*Zm + B2[_sage_const_1 ,_sage_const_1 ]*Ym, f"M={M} mu={mu}: B_2 の第2列")
            # 線型性 <linearity_of_T>
            a, b = _sage_const_0p37 +_sage_const_0p21j , -_sage_const_1p1 +_sage_const_0p6j 
            rep.close(T_conj(g1, a*Zm + b*Ym), a*T_conj(g1,Zm) + b*T_conj(g1,Ym), f"M={M} mu={mu}: T の線型性(V1)")
            rep.close(T_conj(g2, a*Zm + b*Ym), a*T_conj(g2,Zm) + b*T_conj(g2,Ym), f"M={M} mu={mu}: T の線型性(V2)")
rep.finish()

