# 対象ラベル: claim_four_part_repeated_difference
import os
import sys
check_directory = os.path.dirname(os.path.abspath(sys.argv[0]))
load(os.path.join(check_directory, 'check_lift_first.sage'))
load(os.path.join(check_directory, 'check_lift_last.sage'))
load(os.path.join(check_directory, 'check_return_first.sage'))
load(os.path.join(check_directory, 'check_return_last.sage'))
load(os.path.join(check_directory, 'check_junction_lift_last.sage'))
load(os.path.join(check_directory, 'check_junction_return_first.sage'))
load(os.path.join(check_directory, 'check_junction_return_last.sage'))
load(os.path.join(check_directory, 'check_junction_lift_first.sage'))
load(os.path.join(check_directory, 'check_junction_fixed.sage'))
load(os.path.join(check_directory, 'check_four_part_split.sage'))
load(os.path.join(check_directory, 'check_gather_junctions.sage'))
load(os.path.join(check_directory, 'check_junction_sum_definition.sage'))
load(os.path.join(check_directory, 'check_substitute_fixed_junctions.sage'))
load(os.path.join(check_directory, 'check_normalize_fixed_terms.sage'))
load(os.path.join(check_directory, 'check_difference_successor.sage'))
load(os.path.join(check_directory, 'check_difference_current.sage'))
load(os.path.join(check_directory, 'check_difference_cancel.sage'))
load(os.path.join(check_directory, 'check_difference_lift.sage'))
load(os.path.join(check_directory, 'check_difference_return.sage'))
load(os.path.join(check_directory, 'check_whole_word.sage'))
