/**
 * 本文（章は見出しブロックで区切る）。
 *
 * 章「分配多項式」: 有限格子の分配関数を、指数関数を経由せず整係数多項式として定義する。
 * 章「有限系の自由エントロピー」: 有理点での値の素因数分解として Φ_L(q) ∈ Λ を定める。
 * どちらの章にも ℝ/ℂ は現れない。
 *
 * 文書順はこの配列の並びが正本である（README「章立ての予定」の表が読む順序の正本）。
 * 本文を 1 ファイルに置いているのは、システムが content/ のファイル名昇順を文書順とみなす一方、
 * リポジトリの規約がファイル名の連番を禁じているためである（分ける方法は未決。MEMORY.md 参照）。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref, todo } from "../schema.ts";

export default defineBlocks([
  {
    id: "partition_polynomial_heading",
    kind: "heading",
    level: 1,
    title: { text: "分配多項式" },
    labels: [],
  },

  {
    id: "partition_polynomial_definition_lattice_and_configuration",
    kind: "definition",
    title: { text: "格子と配位" },
    labels: ["def_lattice", "def_configuration"],
    habitat: "N",
    lean: [
      "Ising2DLambda.PartitionPolynomial.Vertex",
      "Ising2DLambda.PartitionPolynomial.Edge",
      "Ising2DLambda.PartitionPolynomial.boundary0",
      "Ising2DLambda.PartitionPolynomial.boundary1",
      "Ising2DLambda.PartitionPolynomial.Config",
      "Ising2DLambda.PartitionPolynomial.card_config",
    ],
    statement: [
      paragraph([
        "整数 ",
        math(String.raw`L\ge1`),
        " を固定する。格子とは、頂点集合",
      ]),
      displayMath(String.raw`V_L:=(\mathbb{Z}/L\mathbb{Z})\times(\mathbb{Z}/L\mathbb{Z})`),
      paragraph([
        "の元を ",
        math(String.raw`(i,j)`),
        " と書き、第 1 成分 ",
        math(String.raw`i`),
        " を行番号、第 2 成分 ",
        math(String.raw`j`),
        " を列番号と呼ぶ。すなわち行番号が等しい頂点どうしが同じ行に属する。この呼び方は以下で固定し、",
        "第 1 成分を列番号と読むことはしない。",
      ]),
      paragraph([
        "次に、横向きの辺の番号の集合・縦向きの辺の番号の集合",
      ]),
      displayMath(
        String.raw`E_{L,\mathrm{h}}:=\{1,2,\dots,L^2\},\qquad
E_{L,\mathrm{v}}:=\{L^2+1,\,L^2+2,\dots,2L^2\}`,
      ),
      paragraph([
        "および、その合併",
      ]),
      displayMath(String.raw`E_L:=E_{L,\mathrm{h}}\cup E_{L,\mathrm{v}}=\{1,2,\dots,2L^2\}`),
      paragraph([
        "と、各番号に 2 つの頂点（その辺の両端）を割り当てる写像 ",
        math(String.raw`\partial_0,\partial_1:E_L\to V_L`),
        " の 5 つ組 ",
        math(String.raw`(V_L,E_{L,\mathrm{h}},E_{L,\mathrm{v}},\partial_0,\partial_1)`),
        " のことである。",
        math(String.raw`E_{L,\mathrm{h}}`),
        " と ",
        math(String.raw`E_{L,\mathrm{v}}`),
        " は番号の範囲が重ならないので互いに素であり、どの ",
        math(String.raw`e\in E_L`),
        " もちょうど一方に属する。",
      ]),
      paragraph([
        "横向きと縦向きを最初から別の集合にしておくのは、後の章で破れボンド数を",
        "「同じ行の中の破れ」と「隣り合う行の間の破れ」に分けるとき、この分割をそのまま使うためである。",
        "上で定める端点写像により、横向きの辺は両端の行番号が等しく（同じ行の中）、",
        "縦向きの辺は両端の列番号が等しく行番号が 1 だけ異なる（隣り合う行の間）。",
      ]),
      paragraph([
        math(String.raw`\partial_0,\partial_1`),
        " を定めるために、番号を行と列へ分解する。除法の原理により、",
        math(String.raw`0\le k\le L^2-1`),
        " を満たす整数 ",
        math(String.raw`k`),
        " は",
      ]),
      displayMath(String.raw`k=iL+j,\qquad i,j\in\{0,1,\dots,L-1\}`),
      paragraph([
        "の形にただ一通りに書ける（",
        math(String.raw`k`),
        " を ",
        math(String.raw`L`),
        " で割った商が ",
        math(String.raw`i`),
        "、余りが ",
        math(String.raw`j`),
        "）。この分解を用いて、",
        math(String.raw`e\in E_{L,\mathrm{h}}`),
        " に対しては ",
        math(String.raw`e-1=iL+j`),
        " として",
      ]),
      displayMath(String.raw`\partial_0(e):=(i,j),\qquad \partial_1(e):=(i,\,j+1)`),
      paragraph([
        "と定め（行番号は変えず列番号だけを 1 進める。だから横向きである）、",
        math(String.raw`e\in E_{L,\mathrm{v}}`),
        " に対しては ",
        math(String.raw`e-L^2-1=iL+j`),
        " として",
      ]),
      displayMath(String.raw`\partial_0(e):=(i,j),\qquad \partial_1(e):=(i+1,\,j)`),
      paragraph([
        "と定める（どちらの場合も分解される整数は ",
        math(String.raw`0`),
        " 以上 ",
        math(String.raw`L^2-1`),
        " 以下なので、上の分解が使える）。ここで ",
        math(String.raw`\{0,1,\dots,L-1\}`),
        " の元は ",
        math(String.raw`\mathbb{Z}/L\mathbb{Z}`),
        " の元とみなし（各剰余類はこの範囲にちょうど 1 つの代表を持つ）、",
        math(String.raw`i+1`),
        " と ",
        math(String.raw`j+1`),
        " の加法は ",
        math(String.raw`\mathbb{Z}/L\mathbb{Z}`),
        " の中で行う。すなわち周期境界条件である。",
      ]),
      paragraph([
        "辺そのものを頂点の 2 元集合 ",
        math(String.raw`\{u,w\}`),
        " として定義しないのは、",
        math(String.raw`L\le2`),
        " のとき異なる辺が同じ 2 元集合になってしまうからである（",
        math(String.raw`L=1`),
        " では ",
        math(String.raw`\partial_0(e)=\partial_1(e)`),
        " で 1 元集合になり、",
        math(String.raw`L=2`),
        " では横向きの 2 本が同じ 2 点を結ぶ）。2 元集合の集合として数えると本数が ",
        math(String.raw`2L^2`),
        " からずれ、以下の主張が小さい ",
        math(String.raw`L`),
        " で成り立たなくなる。番号を付けておけば、同じ 2 点を結ぶ辺が複数あっても別の辺として数えられる。",
      ]),
      paragraph([
        "以下、有限集合 ",
        math(String.raw`X`),
        " に対し ",
        math(String.raw`|X|`),
        " でその元の個数（",
        math(String.raw`\mathbb{N}`),
        " の元）を表す。この記法をこれ以外の意味（絶対値・ノルム）では使わない。",
      ]),
      paragraph([
        math(String.raw`V_L`),
        " は有限集合で ",
        math(String.raw`|V_L|=L^2`),
        "、",
        math(String.raw`E_{L,\mathrm{h}}`),
        " と ",
        math(String.raw`E_{L,\mathrm{v}}`),
        " はいずれも有限集合で ",
        math(String.raw`|E_{L,\mathrm{h}}|=|E_{L,\mathrm{v}}|=L^2`),
        " である（連続する整数の個数）。両者は互いに素なので ",
        math(String.raw`|E_L|=L^2+L^2=2L^2`),
        " となる。",
      ]),
      paragraph([
        "配位とは写像 ",
        math(String.raw`\sigma:V_L\to\{+1,-1\}`),
        " のことである。配位全体の集合を",
      ]),
      displayMath(
        String.raw`\Sigma_L:=\bigl\{\,\sigma \;\bigm|\; \sigma\ \text{は}\ V_L\ \text{から}\ \{+1,-1\}\ \text{への写像}\,\bigr\}`,
      ),
      paragraph([
        "と書く（写像全体の集合を冪の記法 ",
        math(String.raw`\{+1,-1\}^{V_L}`),
        " で表すことはしない。指数と紛れるため）。",
        math(String.raw`\Sigma_L`),
        " は有限集合で ",
        math(String.raw`|\Sigma_L|=2^{L^2}`),
        " である（各頂点に独立に 2 通りの値を割り当てるので、",
        math(String.raw`|V_L|=L^2`),
        " 個の 2 通りの積）。",
      ]),
      paragraph([
        "この定義に現れる対象はすべて有限集合とその上の写像であり、実数体も複素数体も使っていない。値 ",
        math(String.raw`\pm1`),
        " は ",
        math(String.raw`\mathbb{Z}`),
        " の元として読む。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_definition_broken_bond_count",
    kind: "definition",
    title: { text: "破れボンド数" },
    labels: ["def_broken_bond_count"],
    habitat: "N",
    lean: [
      "Ising2DLambda.PartitionPolynomial.brokenBondCount",
      "Ising2DLambda.PartitionPolynomial.brokenBondCount_le",
    ],
    statement: [
      paragraph([
        ref("def_configuration"),
        " の配位 ",
        math(String.raw`\sigma\in\Sigma_L`),
        " と ",
        ref("def_lattice"),
        " の辺の番号 ",
        math(String.raw`e\in E_L`),
        " に対し、",
        math(String.raw`\sigma(\partial_0(e))\ne\sigma(\partial_1(e))`),
        " が成り立つとき「辺 ",
        math(String.raw`e`),
        " は ",
        math(String.raw`\sigma`),
        " のもとで破れている」という。",
      ]),
      paragraph([
        "配位 ",
        math(String.raw`\sigma`),
        " の破れボンド数 ",
        math(String.raw`b(\sigma)`),
        " を、破れている辺の番号の個数",
      ]),
      displayMath(
        String.raw`b(\sigma):=\bigl|\bigl\{\,e\in E_L \;\bigm|\; \sigma(\partial_0(e))\ne\sigma(\partial_1(e))\,\bigr\}\bigr|`,
      ),
      paragraph([
        "で定める。有限集合の部分集合の元の個数なので ",
        math(String.raw`b(\sigma)\in\mathbb{N}`),
        " であり、",
        math(String.raw`0\le b(\sigma)\le|E_L|=2L^2`),
        " が成り立つ。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_definition_multiplicity",
    kind: "definition",
    title: { text: "多重度" },
    labels: ["def_multiplicity"],
    habitat: "N",
    lean: ["Ising2DLambda.PartitionPolynomial.multiplicity"],
    statement: [
      paragraph([
        "整数 ",
        math(String.raw`m\in\{0,1,\dots,2L^2\}`),
        " に対し、多重度 ",
        math(String.raw`\Omega_L(m)`),
        " を",
      ]),
      displayMath(
        String.raw`\Omega_L(m):=\bigl|\bigl\{\,\sigma\in\Sigma_L \;\bigm|\; b(\sigma)=m\,\bigr\}\bigr|`,
      ),
      paragraph([
        "で定める（",
        math(String.raw`b(\sigma)`),
        " は ",
        ref("def_broken_bond_count"),
        "）。有限集合 ",
        math(String.raw`\Sigma_L`),
        " の部分集合の元の個数なので ",
        math(String.raw`\Omega_L(m)\in\mathbb{N}`),
        " である。",
      ]),
      paragraph([
        "多重度は数え上げだけで定義されており、温度・エネルギーといった量を含まない。",
        "これがこの章の主張のすべてを可算側に留める理由である。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_definition_partition_polynomial",
    kind: "definition",
    title: { text: "分配多項式" },
    labels: ["def_partition_polynomial"],
    habitat: "Z",
    lean: ["Ising2DLambda.PartitionPolynomial.partitionPolynomial"],
    statement: [
      paragraph([
        math(String.raw`x`),
        " を不定元とし、多項式環 ",
        math(String.raw`\mathbb{Z}[x]`),
        " の中で分配多項式を",
      ]),
      displayMath(String.raw`Z_L:=\sum_{\sigma\in\Sigma_L}x^{\,b(\sigma)}\ \in\ \mathbb{Z}[x]`),
      paragraph([
        "で定める（",
        math(String.raw`b(\sigma)`),
        " は ",
        ref("def_broken_bond_count"),
        "）。有限個の項の和なので右辺は ",
        math(String.raw`\mathbb{Z}[x]`),
        " の元として確定する。",
      ]),
      paragraph([
        "和の各項の指数は ",
        math(String.raw`b(\sigma)\in\mathbb{N}`),
        "、係数はいずれも ",
        math(String.raw`1\in\mathbb{Z}`),
        " である。この定義は多重度を用いていない。",
        "多重度を用いた形（各 ",
        math(String.raw`x^{\,m}`),
        " の係数が ",
        math(String.raw`\Omega_L(m)`),
        " であること）は定義ではなく、下で証明する。",
      ]),
      paragraph([
        "記法について 2 点を約束する。第一に、",
        math(String.raw`Z_L`),
        " は多項式そのものを表し、",
        math(String.raw`x`),
        " は不定元であって数ではない。第二に、可換環 ",
        math(String.raw`R`),
        " と元 ",
        math(String.raw`r\in R`),
        " に対する代入（評価）の結果を ",
        math(String.raw`Z_L(r)\in R`),
        " と書く。すなわち丸括弧が付いたものだけが代入の結果であり、",
        math(String.raw`Z_L`),
        " と ",
        math(String.raw`Z_L(r)`),
        " は別の対象である。",
      ]),
      paragraph([
        "この定義では代入を行わない。物理の分配関数を得るには ",
        math(String.raw`x`),
        " へ ",
        math(String.raw`e^{-2\beta J}`),
        " を代入するが、その代入は実数体への脱出であり、脱出を宣言したブロックでのみ行う（README「形式変数のまま進む」）。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_claim_configuration_partition",
    kind: "claim",
    title: { text: "配位全体は破れボンド数の値ごとに類別される" },
    labels: ["claim_configuration_partition"],
    habitat: "N",
    lean: [
      "Ising2DLambda.PartitionPolynomial.biUnion_brokenFiber",
      "Ising2DLambda.PartitionPolynomial.brokenFiber_pairwise_disjoint",
      "Ising2DLambda.NecSuf.PartitionPolynomial.biUnion_fiber",
      "Ising2DLambda.NecSuf.PartitionPolynomial.fiber_pairwise_disjoint",
    ],
    statement: [
      paragraph([
        "各 ",
        math(String.raw`L\ge1`),
        " と各 ",
        math(String.raw`m\in\{0,1,\dots,2L^2\}`),
        " に対し、破れボンド数が ",
        math(String.raw`m`),
        " である配位の集合を",
      ]),
      displayMath(
        String.raw`A_{L,m}:=\bigl\{\,\sigma\in\Sigma_L \;\bigm|\; b(\sigma)=m\,\bigr\}`,
      ),
      paragraph([
        "と書く（",
        math(String.raw`\Sigma_L`),
        " は ",
        ref("def_configuration"),
        "、",
        math(String.raw`b(\sigma)`),
        " は ",
        ref("def_broken_bond_count"),
        "）。右辺は ",
        math(String.raw`L`),
        " にも依存するので、添字には ",
        math(String.raw`m`),
        " だけでなく ",
        math(String.raw`L`),
        " も書く。このとき次の 2 つが成り立つ。",
      ]),
      list([
        [
          "（被覆）",
          math(String.raw`\Sigma_L=\bigcup_{m=0}^{2L^2}A_{L,m}`),
          " である。",
        ],
        [
          "（互いに素）",
          math(String.raw`m,m'\in\{0,1,\dots,2L^2\}`),
          " が ",
          math(String.raw`m\ne m'`),
          " を満たすならば ",
          math(String.raw`A_{L,m}\cap A_{L,m'}=\varnothing`),
          " である。",
        ],
      ]),
      paragraph([
        "すなわち ",
        math(String.raw`\{A_{L,m}\}_{m=0}^{2L^2}`),
        " は ",
        math(String.raw`\Sigma_L`),
        " の互いに素な有限個の部分集合への分割である。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 1（被覆）。",
        math(String.raw`A_{L,m}`),
        " の定義より ",
        math(String.raw`A_{L,m}\subset\Sigma_L`),
        " なので、合併も ",
        math(String.raw`\Sigma_L`),
        " に含まれる。逆を示す。任意の ",
        math(String.raw`\sigma\in\Sigma_L`),
        " に対し、",
        ref("def_broken_bond_count"),
        " より ",
        math(String.raw`b(\sigma)\in\mathbb{N}`),
        " かつ ",
        math(String.raw`b(\sigma)\le 2L^2`),
        " である。そこで ",
        math(String.raw`m:=b(\sigma)`),
        " と置くと ",
        math(String.raw`m\in\{0,1,\dots,2L^2\}`),
        " であり、",
        math(String.raw`b(\sigma)=m`),
        " なので ",
        math(String.raw`\sigma\in A_{L,m}`),
        " である。よって ",
        math(String.raw`\sigma`),
        " は合併に属する。",
      ]),
      paragraph([
        "Step 2（互いに素）。",
        math(String.raw`m\ne m'`),
        " とし、",
        math(String.raw`\sigma\in A_{L,m}\cap A_{L,m'}`),
        " が存在したとする。",
        math(String.raw`A_{L,m}`),
        " の定義より ",
        math(String.raw`b(\sigma)=m`),
        "、",
        math(String.raw`A_{L,m'}`),
        " の定義より ",
        math(String.raw`b(\sigma)=m'`),
        " である。",
        ref("def_broken_bond_count"),
        " の ",
        math(String.raw`b`),
        " は写像であり、1 つの ",
        math(String.raw`\sigma`),
        " に対する値は 1 つなので ",
        math(String.raw`m=b(\sigma)=m'`),
        " となり、",
        math(String.raw`m\ne m'`),
        " に反する。したがってそのような ",
        math(String.raw`\sigma`),
        " は存在せず、",
        math(String.raw`A_{L,m}\cap A_{L,m'}=\varnothing`),
        " である。",
      ]),
      paragraph([
        "以上の 2 つは有限集合の包含関係と写像の一意性だけからなり、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_claim_coefficient_representation",
    kind: "claim",
    title: { text: "分配多項式の係数は多重度である" },
    labels: ["claim_coefficient_representation"],
    habitat: "Z",
    lean: [
      "Ising2DLambda.PartitionPolynomial.partitionPolynomial_eq_sum_multiplicity",
      "Ising2DLambda.PartitionPolynomial.partitionPolynomial_eq_sum_multiplicity_from_necSuf",
      "Ising2DLambda.NecSuf.PartitionPolynomial.sum_comp_eq_sum_nsmul",
    ],
    verification: ["sagemath/check/partition-polynomial-coefficient-representation"],
    statement: [
      paragraph([
        "各 ",
        math(String.raw`L\ge1`),
        " について、多項式環 ",
        math(String.raw`\mathbb{Z}[x]`),
        " の中で",
      ]),
      displayMath(String.raw`Z_L=\sum_{m=0}^{2L^2}\Omega_L(m)\,x^{\,m}`),
      paragraph([
        "が成り立つ（",
        math(String.raw`Z_L`),
        " は ",
        ref("def_partition_polynomial"),
        "、",
        math(String.raw`\Omega_L(m)`),
        " は ",
        ref("def_multiplicity"),
        "）。すなわち ",
        math(String.raw`\Omega_L(m)\in\mathbb{N}\subset\mathbb{Z}`),
        " は ",
        math(String.raw`Z_L`),
        " の ",
        math(String.raw`x^{\,m}`),
        " の係数である。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 1（多重度を類の元の個数として読む）。",
        ref("def_multiplicity"),
        " により、",
        math(String.raw`\Omega_L(m)`),
        " は ",
        ref("claim_configuration_partition"),
        " の集合 ",
        math(String.raw`A_{L,m}`),
        " の元の個数 ",
        math(String.raw`|A_{L,m}|`),
        " である。",
      ]),
      paragraph([
        "Step 2（類別）。",
        ref("claim_configuration_partition"),
        " により、",
        math(String.raw`\{A_{L,m}\}_{m=0}^{2L^2}`),
        " は ",
        math(String.raw`\Sigma_L`),
        " の互いに素な有限個の部分集合への分割である。",
      ]),
      paragraph([
        "Step 3（和を類ごとに束ねる）。互いに素な有限個の有限集合の合併の上を走る和は、",
        "各集合の上を走る和の総和に等しい。",
        ref("def_partition_polynomial"),
        " の定義の和にこれを適用して",
      ]),
      displayMath(
        String.raw`Z_L=\sum_{\sigma\in\Sigma_L}x^{\,b(\sigma)}
=\sum_{m=0}^{2L^2}\ \sum_{\sigma\in A_{L,m}}x^{\,b(\sigma)}`,
      ),
      paragraph(["を得る。"]),
      paragraph([
        "Step 4（1 つの類の中では単項式が共通）。",
        math(String.raw`m`),
        " を固定する。",
        ref("claim_configuration_partition"),
        " の ",
        math(String.raw`A_{L,m}`),
        " の定義より、",
        math(String.raw`\sigma\in A_{L,m}`),
        " ならば ",
        math(String.raw`b(\sigma)=m`),
        " である。したがって内側の和の各項は ",
        math(String.raw`x^{\,m}`),
        " に等しく、",
      ]),
      displayMath(
        String.raw`\sum_{\sigma\in A_{L,m}}x^{\,b(\sigma)}
=\sum_{\sigma\in A_{L,m}}x^{\,m}
=|A_{L,m}|\cdot x^{\,m}
=\Omega_L(m)\,x^{\,m}`,
      ),
      paragraph([
        "となる（2 つ目の等号は同じ元を ",
        math(String.raw`|A_{L,m}|`),
        " 個足したこと、3 つ目の等号は Step 1）。",
      ]),
      paragraph([
        "Step 5（結論）。Step 4 を Step 3 の右辺の各項へ代入して",
      ]),
      displayMath(String.raw`Z_L=\sum_{m=0}^{2L^2}\Omega_L(m)\,x^{\,m}`),
      paragraph(["を得る。"]),
      paragraph([
        "以上の各ステップは有限和の組み替えと数え上げだけからなり、",
        math(String.raw`x`),
        " への代入を行っていない。実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_claim_coefficient_sum",
    kind: "claim",
    title: { text: "多重度の総和は配位の総数に等しい" },
    labels: ["claim_coefficient_sum"],
    habitat: "N",
    lean: [
      "Ising2DLambda.PartitionPolynomial.multiplicity_sum_eq_two_pow",
      "Ising2DLambda.PartitionPolynomial.multiplicity_sum_eq_two_pow_from_necSuf",
      "Ising2DLambda.NecSuf.PartitionPolynomial.sum_card_fiber_eq_card",
    ],
    verification: ["sagemath/check/partition-polynomial-coefficient-sum"],
    statement: [
      paragraph([
        "各 ",
        math(String.raw`L\ge1`),
        " について",
      ]),
      displayMath(String.raw`\sum_{m=0}^{2L^2}\Omega_L(m)=2^{L^2}`),
      paragraph([
        "が成り立つ（",
        math(String.raw`\Omega_L(m)`),
        " は ",
        ref("def_multiplicity"),
        "）。両辺は ",
        math(String.raw`\mathbb{N}`),
        " の元である。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 1（多重度を類の元の個数として読む）。",
        ref("def_multiplicity"),
        " により、",
        math(String.raw`\Omega_L(m)`),
        " は ",
        ref("claim_configuration_partition"),
        " の集合 ",
        math(String.raw`A_{L,m}`),
        " の元の個数 ",
        math(String.raw`|A_{L,m}|`),
        " である。",
      ]),
      paragraph([
        "Step 2（類別）。",
        ref("claim_configuration_partition"),
        " により、",
        math(String.raw`\{A_{L,m}\}_{m=0}^{2L^2}`),
        " は ",
        math(String.raw`\Sigma_L`),
        " の互いに素な有限個の部分集合への分割である。",
      ]),
      paragraph([
        "Step 3（有限集合の分割の元の個数）。互いに素な有限個の有限集合の合併の元の個数は、",
        "各集合の元の個数の和である。Step 2 の分割にこれを適用して",
      ]),
      displayMath(String.raw`|\Sigma_L|=\sum_{m=0}^{2L^2}|A_{L,m}|=\sum_{m=0}^{2L^2}\Omega_L(m)`),
      paragraph(["を得る（最後の等号は Step 1）。"]),
      paragraph([
        "Step 4（配位の総数）。",
        ref("def_configuration"),
        " により ",
        math(String.raw`|\Sigma_L|=2^{L^2}`),
        " である。",
      ]),
      paragraph([
        "Step 5（結論）。Step 3 の左辺へ Step 4 を代入して ",
        math(String.raw`\sum_{m=0}^{2L^2}\Omega_L(m)=2^{L^2}`),
        " を得る。",
      ]),
      paragraph([
        "以上の各ステップは有限集合の元の個数の計算だけからなり、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "free_entropy_heading",
    kind: "heading",
    level: 1,
    title: { text: "有限系の自由エントロピー" },
    labels: [],
  },

  {
    id: "free_entropy_definition_prime_exponent",
    kind: "definition",
    title: { text: "素因数分解の指数" },
    labels: ["def_prime_exponent"],
    habitat: "N",
    lean: ["Ising2DLambda.FreeEntropy.primeExponent"],
    statement: [
      paragraph([
        "素数全体の集合を ",
        math(String.raw`\mathcal{P}=\{2,3,5,7,\dots\}`),
        " と書く。これは無限集合だが可算である。",
      ]),
      paragraph([
        "1 以上の整数 ",
        math(String.raw`n`),
        " を取る。算術の基本定理により、相異なる有限個の素数 ",
        math(String.raw`p_1,\dots,p_k\in\mathcal{P}`),
        "（",
        math(String.raw`k\in\mathbb{N}`),
        "）と 1 以上の整数 ",
        math(String.raw`e_1,\dots,e_k`),
        " が存在して",
      ]),
      displayMath(String.raw`n=\prod_{i=1}^{k}p_i^{\,e_i}`),
      paragraph([
        "と書け、この表示は素数の並べ方の違いを除いてただ一通りである。",
        "右辺は有限個の因子の積であり、無限個の素数にわたる積は書いていない。",
        math(String.raw`n=1`),
        " のときは ",
        math(String.raw`k=0`),
        " であり、右辺は空積すなわち ",
        math(String.raw`1`),
        " である。",
      ]),
      paragraph([
        "この表示を用いて、素数 ",
        math(String.raw`p\in\mathcal{P}`),
        " に対し ",
        math(String.raw`v_p(n)\in\mathbb{N}`),
        " を",
      ]),
      displayMath(
        String.raw`v_p(n):=\begin{cases}e_i&(\text{ある}\ i\ \text{について}\ p=p_i\ \text{であるとき})\\[2pt]0&(\text{どの}\ i\ \text{についても}\ p\ne p_i\ \text{であるとき})\end{cases}`,
      ),
      paragraph([
        "で定め、これを ",
        math(String.raw`n`),
        " における ",
        math(String.raw`p`),
        " の指数と呼ぶ。",
        math(String.raw`p_1,\dots,p_k`),
        " は相異なるので、第一の場合の ",
        math(String.raw`i`),
        " は高々 1 つであり、右辺は定まる。",
        "また表示が並べ方を除いて一通りであることから、",
        math(String.raw`v_p(n)`),
        " は表示の取り方によらず ",
        math(String.raw`n`),
        " と ",
        math(String.raw`p`),
        " だけで決まる。",
      ]),
      paragraph([
        "定義より ",
        math(String.raw`v_p(n)\ne0`),
        " となる素数 ",
        math(String.raw`p`),
        " は ",
        math(String.raw`p_1,\dots,p_k`),
        " のいずれかなので、そのような素数は有限個（高々 ",
        math(String.raw`k`),
        " 個）である。したがって次の積は有限積として意味を持ち、",
      ]),
      displayMath(String.raw`n=\prod_{p:\ v_p(n)\ne0}p^{\,v_p(n)}`),
      paragraph([
        "が成り立つ（指数が ",
        math(String.raw`0`),
        " の素数を落としても因子 ",
        math(String.raw`p^{0}=1`),
        " が消えるだけである）。以後、素数を走る積はすべてこの形の有限積として書く。",
      ]),
      paragraph([
        "定義から直ちに次の 2 つが従う。第一に ",
        math(String.raw`v_p(1)=0`),
        " である（",
        math(String.raw`1`),
        " の表示は ",
        math(String.raw`k=0`),
        " の空積であり、どの素数も因子に持たない）。第二に、1 以上の整数 ",
        math(String.raw`m,n`),
        " に対し",
      ]),
      displayMath(String.raw`v_p(mn)=v_p(m)+v_p(n)`),
      paragraph([
        "が成り立つ（指数の加法性）。これを示す。まず有限集合",
      ]),
      displayMath(
        String.raw`S:=\{\,p\in\mathcal{P}\mid v_p(m)\ne0\,\}\cup\{\,p\in\mathcal{P}\mid v_p(n)\ne0\,\}`,
      ),
      paragraph([
        "を取る（有限集合 2 つの合併なので有限である）。",
        math(String.raw`S`),
        " の外の素数では ",
        math(String.raw`m`),
        " も ",
        math(String.raw`n`),
        " も指数が ",
        math(String.raw`0`),
        " なので、上の有限積の因子を ",
        math(String.raw`S`),
        " まで増やしても値は変わらず",
      ]),
      displayMath(
        String.raw`m=\prod_{p\in S}p^{\,v_p(m)},\qquad n=\prod_{p\in S}p^{\,v_p(n)}`,
      ),
      paragraph([
        "である。両辺どうしを掛け、同じ素数の冪をまとめると",
      ]),
      displayMath(String.raw`mn=\prod_{p\in S}p^{\,v_p(m)+v_p(n)}`),
      paragraph([
        "を得る。右辺は ",
        math(String.raw`mn`),
        " を相異なる有限個の素数の冪の積として書いたものなので、算術の基本定理の一意性より、",
        math(String.raw`S`),
        " に属する素数 ",
        math(String.raw`p`),
        " については指数が一致して ",
        math(String.raw`v_p(mn)=v_p(m)+v_p(n)`),
        " である。",
        math(String.raw`S`),
        " に属さない素数 ",
        math(String.raw`p`),
        " については、同じ一意性より ",
        math(String.raw`mn`),
        " の因子に現れないので ",
        math(String.raw`v_p(mn)=0`),
        " であり、",
        math(String.raw`v_p(m)=v_p(n)=0`),
        " だから両辺とも ",
        math(String.raw`0`),
        " で等しい。",
      ]),
      paragraph([
        "この定義に現れるのは 1 以上の整数と自然数だけであり、実数体も複素数体も使っていない。",
        "指数関数も実対数も現れないことに注意する。",
      ]),
    ],
  },

  {
    id: "free_entropy_definition_log_order_group",
    kind: "definition",
    title: { text: "対数順序群" },
    labels: ["def_log_order_group"],
    habitat: "Lambda",
    lean: [
      "Ising2DLambda.FreeEntropy.LogOrderGroup",
      "Ising2DLambda.FreeEntropy.generator",
    ],
    statement: [
      paragraph([
        "写像 ",
        math(String.raw`\lambda:\mathcal{P}\to\mathbb{Z}`),
        " のうち、",
        math(String.raw`\lambda(p)\ne0`),
        " となる素数 ",
        math(String.raw`p`),
        " が有限個であるもの全体の集合を",
      ]),
      displayMath(
        String.raw`\Lambda:=\bigl\{\,\lambda \;\bigm|\; \lambda\ \text{は}\ \mathcal{P}\ \text{から}\ \mathbb{Z}\ \text{への写像で、}\ \lambda(p)\ne0\ \text{となる}\ p\ \text{は有限個}\,\bigr\}`,
      ),
      paragraph([
        "と書き、加法を素数ごとに",
      ]),
      displayMath(String.raw`(\lambda+\mu)(p):=\lambda(p)+\mu(p)\qquad(p\in\mathcal{P})`),
      paragraph([
        "で定める（右辺の加法は ",
        math(String.raw`\mathbb{Z}`),
        " の中で行う）。",
        math(String.raw`\lambda+\mu`),
        " も有限個の素数でしか ",
        math(String.raw`0`),
        " と異なる値を取らないので ",
        math(String.raw`\Lambda`),
        " の元である（2 つの有限集合の合併は有限）。零写像を単位元、",
        math(String.raw`(-\lambda)(p):=-\lambda(p)`),
        " を逆元として、",
        math(String.raw`\Lambda`),
        " は加法についてアーベル群になる。これを対数順序群と呼ぶ。",
      ]),
      paragraph([
        "各素数 ",
        math(String.raw`p`),
        " に対し ",
        math(String.raw`\ell_p\in\Lambda`),
        " を",
      ]),
      displayMath(
        String.raw`\ell_p(p):=1,\qquad \ell_p(p'):=0\quad(p'\in\mathcal{P},\ p'\ne p)`,
      ),
      paragraph([
        "で定める。台が有限なので、",
        math(String.raw`\Lambda`),
        " の各元 ",
        math(String.raw`\lambda`),
        " は有限和",
      ]),
      displayMath(String.raw`\lambda=\sum_{p:\ \lambda(p)\ne0}\lambda(p)\,\ell_p`),
      paragraph([
        "としてただ一通りに書ける。記号 ",
        math(String.raw`\ell_p`),
        " は「",
        math(String.raw`p`),
        " の対数」と読むが、これは形式的な記号であって、実数としての自然対数の値を参照しない。",
        "実数体の元は一切登場しない。",
      ]),
      paragraph([
        "名前に「順序」という語が入っているが、ここで定めたのは加法群としての構造だけであり、",
        math(String.raw`\Lambda`),
        " に順序は定めていない。本章では順序を使わないためである。",
        "順序が必要になる箇所（零点の詰め寄りを述べるとき）で、そこで必要な形の順序を定義し、",
        "それが定義できることもそこで示す。",
        "対数順序群という呼び名は、その段階を先取りした名前として使っている。",
      ]),
    ],
  },

  {
    id: "free_entropy_claim_rational_exponent_well_defined",
    kind: "claim",
    title: { text: "有理数の指数は表示の取り方によらない" },
    labels: ["claim_rational_exponent_well_defined"],
    habitat: "Z",
    lean: [
      "Ising2DLambda.FreeEntropy.rationalExponent_well_defined",
      "Ising2DLambda.FreeEntropy.rationalExponent_well_defined_from_necSuf",
      "Ising2DLambda.NecSuf.FreeEntropy.sub_eq_sub_of_mul_eq_mul",
    ],
    verification: ["sagemath/check/free-entropy-definition"],
    statement: [
      paragraph([
        "素数 ",
        math(String.raw`p\in\mathcal{P}`),
        " と、1 以上の整数 ",
        math(String.raw`a,b,a',b'`),
        " を取る。有理数として ",
        math(String.raw`\dfrac{a}{b}=\dfrac{a'}{b'}`),
        " が成り立つならば、",
      ]),
      displayMath(String.raw`v_p(a)-v_p(b)=v_p(a')-v_p(b')`),
      paragraph([
        "が ",
        math(String.raw`\mathbb{Z}`),
        " の中で成り立つ（",
        math(String.raw`v_p`),
        " は ",
        ref("def_prime_exponent"),
        "）。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 1（分母を払う）。",
        math(String.raw`b`),
        " と ",
        math(String.raw`b'`),
        " はいずれも 1 以上の整数なので ",
        math(String.raw`bb'\ne0`),
        " である。仮定 ",
        math(String.raw`a/b=a'/b'`),
        " の両辺に ",
        math(String.raw`bb'`),
        " を掛けて",
      ]),
      displayMath(String.raw`ab'=a'b`),
      paragraph([
        "を得る。両辺は 1 以上の整数の積なので、いずれも 1 以上の整数である。",
      ]),
      paragraph([
        "Step 2（指数の加法性を両辺へ適用する）。",
        ref("def_prime_exponent"),
        " の指数の加法性より",
      ]),
      displayMath(
        String.raw`v_p(ab')=v_p(a)+v_p(b'),\qquad v_p(a'b)=v_p(a')+v_p(b)`,
      ),
      paragraph(["である。"]),
      paragraph([
        "Step 3（両辺の指数を比べる）。Step 1 の ",
        math(String.raw`ab'=a'b`),
        " は 1 以上の整数としての等式なので、その ",
        math(String.raw`p`),
        " の指数も等しく ",
        math(String.raw`v_p(ab')=v_p(a'b)`),
        " である。Step 2 を代入して",
      ]),
      displayMath(String.raw`v_p(a)+v_p(b')=v_p(a')+v_p(b)`),
      paragraph(["を得る。"]),
      paragraph([
        "Step 4（移項）。Step 3 の等式は ",
        math(String.raw`\mathbb{Z}`),
        " の中の等式である。両辺から ",
        math(String.raw`v_p(b)+v_p(b')`),
        " を引いて",
      ]),
      displayMath(String.raw`v_p(a)-v_p(b)=v_p(a')-v_p(b')`),
      paragraph(["を得る。"]),
      paragraph([
        "以上の各ステップは整数の演算と素因数分解の一意性だけからなり、実数体も複素数体も現れない。",
        "引き算のためだけに ",
        math(String.raw`\mathbb{N}`),
        " から ",
        math(String.raw`\mathbb{Z}`),
        " へ出ているが、どちらも可算である。",
      ]),
    ],
  },

  {
    id: "free_entropy_definition_rational_log",
    kind: "definition",
    title: { text: "正の有理数の対数" },
    labels: ["def_rational_log"],
    habitat: "Lambda",
    lean: [
      "Ising2DLambda.FreeEntropy.rationalExponent",
      "Ising2DLambda.FreeEntropy.logRat",
    ],
    statement: [
      paragraph([
        "正の有理数全体の集合を ",
        math(String.raw`\mathbb{Q}_{>0}`),
        " と書く。各 ",
        math(String.raw`q\in\mathbb{Q}_{>0}`),
        " は、1 以上の整数 ",
        math(String.raw`a,b`),
        " を用いて ",
        math(String.raw`q=a/b`),
        " と書ける。素数 ",
        math(String.raw`p`),
        " に対し",
      ]),
      displayMath(String.raw`w_p(q):=v_p(a)-v_p(b)\ \in\ \mathbb{Z}`),
      paragraph([
        "と定める（",
        math(String.raw`v_p`),
        " は ",
        ref("def_prime_exponent"),
        "）。この値は ",
        math(String.raw`q`),
        " の表示 ",
        math(String.raw`a/b`),
        " の取り方によらない（",
        ref("claim_rational_exponent_well_defined"),
        "）ので、",
        math(String.raw`w_p(q)`),
        " は ",
        math(String.raw`q`),
        " だけで決まる。関数の名前を ",
        math(String.raw`v_p`),
        " と分けてあるのは、定義域が異なるからである（",
        math(String.raw`v_p`),
        " は 1 以上の整数に、",
        math(String.raw`w_p`),
        " は正の有理数に定義されている）。",
      ]),
      paragraph([
        math(String.raw`w_p(q)\ne0`),
        " となる素数 ",
        math(String.raw`p`),
        " は有限個である。実際 ",
        math(String.raw`w_p(q)=v_p(a)-v_p(b)`),
        " なので、",
        math(String.raw`w_p(q)\ne0`),
        " ならば ",
        math(String.raw`v_p(a)\ne0`),
        " または ",
        math(String.raw`v_p(b)\ne0`),
        " であり、",
        ref("def_prime_exponent"),
        " よりそのような ",
        math(String.raw`p`),
        " はどちらについても有限個だからである。したがって写像 ",
        math(String.raw`p\mapsto w_p(q)`),
        " は ",
        ref("def_log_order_group"),
        " の ",
        math(String.raw`\Lambda`),
        " の元である。これを",
      ]),
      displayMath(String.raw`\log q:=\sum_{p:\ w_p(q)\ne0}w_p(q)\,\ell_p\ \in\ \Lambda`),
      paragraph([
        "と書き、",
        math(String.raw`q`),
        " の対数と呼ぶ。1 以上の整数 ",
        math(String.raw`n`),
        " については ",
        math(String.raw`n=n/1`),
        " と ",
        math(String.raw`v_p(1)=0`),
        " より ",
        math(String.raw`w_p(n)=v_p(n)`),
        " となるので、整数に対する指数と矛盾しない。",
      ]),
      paragraph([
        "この対数は級数でも極限でもなく、素因数分解そのものである。値は ",
        math(String.raw`\Lambda`),
        " の元であって、実数ではない。",
      ]),
    ],
  },

  {
    id: "free_entropy_claim_value_at_rational_is_positive",
    kind: "claim",
    title: { text: "分配多項式の正の有理点での値は正の有理数である" },
    labels: ["claim_value_at_rational_is_positive"],
    habitat: "Q",
    lean: [
      "Ising2DLambda.FreeEntropy.partitionPolynomial_eval_pos",
      "Ising2DLambda.FreeEntropy.partitionPolynomial_eval_pos_from_necSuf",
      "Ising2DLambda.NecSuf.FreeEntropy.sum_pow_pos",
    ],
    verification: ["sagemath/check/free-entropy-definition"],
    statement: [
      paragraph([
        "各 ",
        math(String.raw`L\ge1`),
        " と各 ",
        math(String.raw`q\in\mathbb{Q}_{>0}`),
        " について、",
        ref("def_partition_polynomial"),
        " の分配多項式へ ",
        math(String.raw`q`),
        " を代入した値は",
      ]),
      displayMath(String.raw`Z_L(q)\in\mathbb{Q}_{>0}`),
      paragraph([
        "を満たす。ここで代入は ",
        ref("def_partition_polynomial"),
        " の約束どおり、可換環 ",
        math(String.raw`\mathbb{Q}`),
        " とその元 ",
        math(String.raw`q`),
        " についての評価である。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 1（代入を和へ配る）。多項式への代入は、係数環 ",
        math(String.raw`\mathbb{Z}`),
        " から ",
        math(String.raw`\mathbb{Q}`),
        " への包含と ",
        math(String.raw`x\mapsto q`),
        " で定まる環準同型 ",
        math(String.raw`\mathbb{Z}[x]\to\mathbb{Q}`),
        " による像である。環準同型は和と積を保つので、",
        ref("def_partition_polynomial"),
        " の定義式へ適用して",
      ]),
      displayMath(String.raw`Z_L(q)=\sum_{\sigma\in\Sigma_L}q^{\,b(\sigma)}`),
      paragraph([
        "を得る（",
        math(String.raw`\Sigma_L`),
        " は ",
        ref("def_configuration"),
        "、",
        math(String.raw`b(\sigma)`),
        " は ",
        ref("def_broken_bond_count"),
        "）。右辺は有限個の有理数の和なので ",
        math(String.raw`\mathbb{Q}`),
        " の元である。",
      ]),
      paragraph([
        "Step 2（各項が正であること）。",
        math(String.raw`\sigma\in\Sigma_L`),
        " を固定する。",
        ref("def_broken_bond_count"),
        " より ",
        math(String.raw`b(\sigma)\in\mathbb{N}`),
        " である。",
        math(String.raw`q>0`),
        " なので、正の有理数を ",
        math(String.raw`b(\sigma)`),
        " 個掛けた ",
        math(String.raw`q^{\,b(\sigma)}`),
        " は正である（",
        math(String.raw`b(\sigma)=0`),
        " のときは空積で ",
        math(String.raw`q^{0}=1>0`),
        "）。",
      ]),
      paragraph([
        "Step 3（和が正であること）。",
        ref("def_configuration"),
        " より ",
        math(String.raw`|\Sigma_L|=2^{L^2}\ge1`),
        " なので、Step 1 の和は少なくとも 1 個の項を持つ。正の有理数を 1 個以上足したものは正なので ",
        math(String.raw`Z_L(q)>0`),
        " である。",
      ]),
      paragraph([
        "Step 4（結論）。Step 1 より ",
        math(String.raw`Z_L(q)\in\mathbb{Q}`),
        "、Step 3 より ",
        math(String.raw`Z_L(q)>0`),
        " なので ",
        math(String.raw`Z_L(q)\in\mathbb{Q}_{>0}`),
        " である。",
      ]),
      paragraph([
        "以上の各ステップは有理数の四則と有限和だけからなり、実数体も複素数体も現れない。",
        "代入したのは有理数であって、指数関数の値ではない。",
      ]),
    ],
  },

  {
    id: "free_entropy_definition_finite_free_entropy",
    kind: "definition",
    title: { text: "有限系の自由エントロピー" },
    labels: ["def_finite_free_entropy"],
    habitat: "Lambda",
    lean: ["Ising2DLambda.FreeEntropy.freeEntropy"],
    statement: [
      paragraph([
        "各 ",
        math(String.raw`L\ge1`),
        " と各 ",
        math(String.raw`q\in\mathbb{Q}_{>0}`),
        " に対し、有限系の自由エントロピーを",
      ]),
      displayMath(String.raw`\Phi_L(q):=\log Z_L(q)\ \in\ \Lambda`),
      paragraph([
        "で定める（",
        math(String.raw`\log`),
        " は ",
        ref("def_rational_log"),
        "、",
        math(String.raw`Z_L(q)`),
        " は ",
        ref("def_partition_polynomial"),
        " への代入）。",
        ref("claim_value_at_rational_is_positive"),
        " により ",
        math(String.raw`Z_L(q)`),
        " は正の有理数なので ",
        math(String.raw`\log`),
        " の定義域に入っており、右辺は ",
        math(String.raw`\Lambda`),
        " の元として確定する。",
      ]),
      paragraph([
        math(String.raw`\Phi_L`),
        " は ",
        math(String.raw`\mathbb{Q}_{>0}`),
        " から ",
        math(String.raw`\Lambda`),
        " への写像であり、",
        math(String.raw`\Phi_L(q)`),
        " はその値である。",
        math(String.raw`\Phi_L`),
        " と ",
        math(String.raw`\Phi_L(q)`),
        " を同じ記号で書くことはしない。",
      ]),
      paragraph([
        "具体例を 1 つ挙げる。",
        math(String.raw`L=2`),
        "、",
        math(String.raw`q=1/2`),
        " のとき ",
        math(String.raw`Z_2=2+12x^4+2x^8`),
        " なので",
      ]),
      displayMath(
        String.raw`Z_2(1/2)=2+\frac{12}{2^4}+\frac{2}{2^8}=\frac{353}{2^7},\qquad
\Phi_2(1/2)=\ell_{353}-7\,\ell_2\ \in\ \Lambda`,
      ),
      paragraph([
        "である（",
        math(String.raw`353`),
        " は素数）。自由エントロピーは分配多項式の値の素因数分解の指数ベクトルそのものであり、",
        "実数を経由しない。",
      ]),
    ],
  },

  {
    id: "main_text_remark_planned_chapters",
    kind: "remark",
    title: { text: "この先に置く章（未着手）" },
    labels: ["remark_planned_chapters"],
    habitat: "none",
    statement: [
      paragraph([
        "本文はここまでで、以下は未着手である。",
        "読む順序と各章が扱う量の住処は README の「章立ての予定」の表が正本である。",
      ]),
      list([
        [
          todo("未着手"),
          "「有限系の自由エントロピー」の続き: ",
          math(String.raw`\log`),
          " の加法性（",
          math(String.raw`\log(q_1q_2)=\log q_1+\log q_2`),
          "）と、",
          math(String.raw`\Phi_L`),
          " の基本性質。定義までは上で済んでいる。",
        ],
        [
          todo("未着手"),
          "「転送行列」: ",
          math(String.raw`T(x)\in M_{2^L}\bigl(\mathbb{Z}[x]\bigr)`),
          " を作り ",
          math(String.raw`Z_L(x)=\operatorname{Tr}T(x)^L`),
          " を示す。",
        ],
        [
          todo("未着手"),
          "「固有値の代数性」: 特性多項式が ",
          math(String.raw`\mathbb{Z}[x][\lambda]`),
          " に属することから固有値の代数性を出し、円分体上で対角化する。",
        ],
        [
          todo("未着手"),
          "「Fisher 零点」: 零点が ",
          math(String.raw`\overline{\mathbb{Q}}`),
          " に属することと Kramers–Wannier 双対から、自己双対点 ",
          math(String.raw`x_c=\sqrt2-1`),
          " を出す。",
        ],
        [
          todo("未着手"),
          "「零点の詰め寄り」: 相転移を ",
          math(String.raw`\mathbb{Q}`),
          " 上の量化言明として書く。",
        ],
        [
          todo("未着手"),
          "「熱力学極限」: 自由エネルギー密度と零点密度を扱う。ここが実数体への脱出である。",
        ],
        [
          todo("未着手"),
          "「臨界指数を零点列で書く」: 先頭零点の列 ",
          math(String.raw`\{x_1(L)\}_L\subset\overline{\mathbb{Q}}`),
          " と有限サイズスケーリングを対応させる。",
        ],
      ]),
      paragraph([
        "各章を書くときは、",
        ref("def_partition_polynomial"),
        " の分配多項式を出発点に据え、",
        math(String.raw`x`),
        " への代入を伴う操作をすべて実数体への脱出として宣言すること。",
      ]),
    ],
  },
]);
