/**
 * 章「分配多項式」。
 *
 * 有限格子の分配関数を、指数関数を経由せず整係数多項式として定義する。
 * この章に ℝ/ℂ は現れない（数え上げ ℕ と多項式環 ℤ[x] だけで閉じる）。
 *
 * 文書順はこの配列の並びが正本である（README「章立ての予定」の表が読む順序の正本）。
 */

import { defineBlocks, displayMath, list, math, paragraph, ref, todo } from "../schema.ts";

export default defineBlocks([
  {
    id: "partition_polynomial_heading",
    kind: "heading",
    level: 1,
    title: { text: "分配多項式" },
    labels: [],
  },

  {
    id: "partition_polynomial_definition_lattice_and_configuration",
    kind: "definition",
    title: { text: "格子と配位" },
    labels: ["def_lattice", "def_configuration"],
    habitat: "N",
    lean: [
      "Ising2DLambda.PartitionPolynomial.Vertex",
      "Ising2DLambda.PartitionPolynomial.Edge",
      "Ising2DLambda.PartitionPolynomial.boundary0",
      "Ising2DLambda.PartitionPolynomial.boundary1",
      "Ising2DLambda.PartitionPolynomial.Config",
      "Ising2DLambda.PartitionPolynomial.card_config",
    ],
    statement: [
      paragraph([
        "整数 ",
        math(String.raw`L\ge1`),
        " を固定する。格子とは、頂点集合",
      ]),
      displayMath(String.raw`V_L:=(\mathbb{Z}/L\mathbb{Z})\times(\mathbb{Z}/L\mathbb{Z})`),
      paragraph([
        "の元を ",
        math(String.raw`(i,j)`),
        " と書き、第 1 成分 ",
        math(String.raw`i`),
        " を行番号、第 2 成分 ",
        math(String.raw`j`),
        " を列番号と呼ぶ。すなわち行番号が等しい頂点どうしが同じ行に属する。この呼び方は以下で固定し、",
        "第 1 成分を列番号と読むことはしない。",
      ]),
      paragraph([
        "次に、横向きの辺の番号の集合・縦向きの辺の番号の集合",
      ]),
      displayMath(
        String.raw`E_{L,\mathrm{h}}:=\{1,2,\dots,L^2\},\qquad
E_{L,\mathrm{v}}:=\{L^2+1,\,L^2+2,\dots,2L^2\}`,
      ),
      paragraph([
        "および、その合併",
      ]),
      displayMath(String.raw`E_L:=E_{L,\mathrm{h}}\cup E_{L,\mathrm{v}}=\{1,2,\dots,2L^2\}`),
      paragraph([
        "と、各番号に 2 つの頂点（その辺の両端）を割り当てる写像 ",
        math(String.raw`\partial_0,\partial_1:E_L\to V_L`),
        " の 5 つ組 ",
        math(String.raw`(V_L,E_{L,\mathrm{h}},E_{L,\mathrm{v}},\partial_0,\partial_1)`),
        " のことである。",
        math(String.raw`E_{L,\mathrm{h}}`),
        " と ",
        math(String.raw`E_{L,\mathrm{v}}`),
        " は番号の範囲が重ならないので互いに素であり、どの ",
        math(String.raw`e\in E_L`),
        " もちょうど一方に属する。",
      ]),
      paragraph([
        "横向きと縦向きを最初から別の集合にしておくのは、後の章で破れボンド数を",
        "「同じ行の中の破れ」と「隣り合う行の間の破れ」に分けるとき、この分割をそのまま使うためである。",
        "上で定める端点写像により、横向きの辺は両端の行番号が等しく（同じ行の中）、",
        "縦向きの辺は両端の列番号が等しく行番号が 1 だけ異なる（隣り合う行の間）。",
      ]),
      paragraph([
        math(String.raw`\partial_0,\partial_1`),
        " を定めるために、番号を行と列へ分解する。除法の原理により、",
        math(String.raw`0\le k\le L^2-1`),
        " を満たす整数 ",
        math(String.raw`k`),
        " は",
      ]),
      displayMath(String.raw`k=iL+j,\qquad i,j\in\{0,1,\dots,L-1\}`),
      paragraph([
        "の形にただ一通りに書ける（",
        math(String.raw`k`),
        " を ",
        math(String.raw`L`),
        " で割った商が ",
        math(String.raw`i`),
        "、余りが ",
        math(String.raw`j`),
        "）。この分解を用いて、",
        math(String.raw`e\in E_{L,\mathrm{h}}`),
        " に対しては ",
        math(String.raw`e-1=iL+j`),
        " として",
      ]),
      displayMath(String.raw`\partial_0(e):=(i,j),\qquad \partial_1(e):=(i,\,j+1)`),
      paragraph([
        "と定め（行番号は変えず列番号だけを 1 進める。だから横向きである）、",
        math(String.raw`e\in E_{L,\mathrm{v}}`),
        " に対しては ",
        math(String.raw`e-L^2-1=iL+j`),
        " として",
      ]),
      displayMath(String.raw`\partial_0(e):=(i,j),\qquad \partial_1(e):=(i+1,\,j)`),
      paragraph([
        "と定める（どちらの場合も分解される整数は ",
        math(String.raw`0`),
        " 以上 ",
        math(String.raw`L^2-1`),
        " 以下なので、上の分解が使える）。ここで ",
        math(String.raw`\{0,1,\dots,L-1\}`),
        " の元は ",
        math(String.raw`\mathbb{Z}/L\mathbb{Z}`),
        " の元とみなし（各剰余類はこの範囲にちょうど 1 つの代表を持つ）、",
        math(String.raw`i+1`),
        " と ",
        math(String.raw`j+1`),
        " の加法は ",
        math(String.raw`\mathbb{Z}/L\mathbb{Z}`),
        " の中で行う。すなわち周期境界条件である。",
      ]),
      paragraph([
        "辺そのものを頂点の 2 元集合 ",
        math(String.raw`\{u,w\}`),
        " として定義しないのは、",
        math(String.raw`L\le2`),
        " のとき異なる辺が同じ 2 元集合になってしまうからである（",
        math(String.raw`L=1`),
        " では ",
        math(String.raw`\partial_0(e)=\partial_1(e)`),
        " で 1 元集合になり、",
        math(String.raw`L=2`),
        " では横向きの 2 本が同じ 2 点を結ぶ）。2 元集合の集合として数えると本数が ",
        math(String.raw`2L^2`),
        " からずれ、以下の主張が小さい ",
        math(String.raw`L`),
        " で成り立たなくなる。番号を付けておけば、同じ 2 点を結ぶ辺が複数あっても別の辺として数えられる。",
      ]),
      paragraph([
        "以下、有限集合 ",
        math(String.raw`X`),
        " に対し ",
        math(String.raw`|X|`),
        " でその元の個数（",
        math(String.raw`\mathbb{N}`),
        " の元）を表す。この記法をこれ以外の意味（絶対値・ノルム）では使わない。",
      ]),
      paragraph([
        math(String.raw`V_L`),
        " は有限集合で ",
        math(String.raw`|V_L|=L^2`),
        "、",
        math(String.raw`E_{L,\mathrm{h}}`),
        " と ",
        math(String.raw`E_{L,\mathrm{v}}`),
        " はいずれも有限集合で ",
        math(String.raw`|E_{L,\mathrm{h}}|=|E_{L,\mathrm{v}}|=L^2`),
        " である（連続する整数の個数）。両者は互いに素なので ",
        math(String.raw`|E_L|=L^2+L^2=2L^2`),
        " となる。",
      ]),
      paragraph([
        "配位とは写像 ",
        math(String.raw`\sigma:V_L\to\{+1,-1\}`),
        " のことである。配位全体の集合を",
      ]),
      displayMath(
        String.raw`\Sigma_L:=\bigl\{\,\sigma \;\bigm|\; \sigma\ \text{は}\ V_L\ \text{から}\ \{+1,-1\}\ \text{への写像}\,\bigr\}`,
      ),
      paragraph([
        "と書く（写像全体の集合を冪の記法 ",
        math(String.raw`\{+1,-1\}^{V_L}`),
        " で表すことはしない。指数と紛れるため）。",
        math(String.raw`\Sigma_L`),
        " は有限集合で ",
        math(String.raw`|\Sigma_L|=2^{L^2}`),
        " である（各頂点に独立に 2 通りの値を割り当てるので、",
        math(String.raw`|V_L|=L^2`),
        " 個の 2 通りの積）。",
      ]),
      paragraph([
        "この定義に現れる対象はすべて有限集合とその上の写像であり、実数体も複素数体も使っていない。値 ",
        math(String.raw`\pm1`),
        " は ",
        math(String.raw`\mathbb{Z}`),
        " の元として読む。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_definition_broken_bond_count",
    kind: "definition",
    title: { text: "破れボンド数" },
    labels: ["def_broken_bond_count"],
    habitat: "N",
    lean: [
      "Ising2DLambda.PartitionPolynomial.brokenBondCount",
      "Ising2DLambda.PartitionPolynomial.brokenBondCount_le",
    ],
    statement: [
      paragraph([
        ref("def_configuration"),
        " の配位 ",
        math(String.raw`\sigma\in\Sigma_L`),
        " と ",
        ref("def_lattice"),
        " の辺の番号 ",
        math(String.raw`e\in E_L`),
        " に対し、",
        math(String.raw`\sigma(\partial_0(e))\ne\sigma(\partial_1(e))`),
        " が成り立つとき「辺 ",
        math(String.raw`e`),
        " は ",
        math(String.raw`\sigma`),
        " のもとで破れている」という。",
      ]),
      paragraph([
        "配位 ",
        math(String.raw`\sigma`),
        " の破れボンド数 ",
        math(String.raw`b(\sigma)`),
        " を、破れている辺の番号の個数",
      ]),
      displayMath(
        String.raw`b(\sigma):=\bigl|\bigl\{\,e\in E_L \;\bigm|\; \sigma(\partial_0(e))\ne\sigma(\partial_1(e))\,\bigr\}\bigr|`,
      ),
      paragraph([
        "で定める。有限集合の部分集合の元の個数なので ",
        math(String.raw`b(\sigma)\in\mathbb{N}`),
        " であり、",
        math(String.raw`0\le b(\sigma)\le|E_L|=2L^2`),
        " が成り立つ。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_definition_multiplicity",
    kind: "definition",
    title: { text: "多重度" },
    labels: ["def_multiplicity"],
    habitat: "N",
    lean: ["Ising2DLambda.PartitionPolynomial.multiplicity"],
    statement: [
      paragraph([
        "整数 ",
        math(String.raw`m\in\{0,1,\dots,2L^2\}`),
        " に対し、多重度 ",
        math(String.raw`\Omega_L(m)`),
        " を",
      ]),
      displayMath(
        String.raw`\Omega_L(m):=\bigl|\bigl\{\,\sigma\in\Sigma_L \;\bigm|\; b(\sigma)=m\,\bigr\}\bigr|`,
      ),
      paragraph([
        "で定める（",
        math(String.raw`b(\sigma)`),
        " は ",
        ref("def_broken_bond_count"),
        "）。有限集合 ",
        math(String.raw`\Sigma_L`),
        " の部分集合の元の個数なので ",
        math(String.raw`\Omega_L(m)\in\mathbb{N}`),
        " である。",
      ]),
      paragraph([
        "多重度は数え上げだけで定義されており、温度・エネルギーといった量を含まない。",
        "これがこの章の主張のすべてを可算側に留める理由である。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_definition_partition_polynomial",
    kind: "definition",
    title: { text: "分配多項式" },
    labels: ["def_partition_polynomial"],
    habitat: "Z",
    lean: ["Ising2DLambda.PartitionPolynomial.partitionPolynomial"],
    statement: [
      paragraph([
        math(String.raw`x`),
        " を不定元とし、多項式環 ",
        math(String.raw`\mathbb{Z}[x]`),
        " の中で分配多項式を",
      ]),
      displayMath(String.raw`Z_L:=\sum_{\sigma\in\Sigma_L}x^{\,b(\sigma)}\ \in\ \mathbb{Z}[x]`),
      paragraph([
        "で定める（",
        math(String.raw`b(\sigma)`),
        " は ",
        ref("def_broken_bond_count"),
        "）。有限個の項の和なので右辺は ",
        math(String.raw`\mathbb{Z}[x]`),
        " の元として確定する。",
      ]),
      paragraph([
        "和の各項の指数は ",
        math(String.raw`b(\sigma)\in\mathbb{N}`),
        "、係数はいずれも ",
        math(String.raw`1\in\mathbb{Z}`),
        " である。この定義は多重度を用いていない。",
        "多重度を用いた形（各 ",
        math(String.raw`x^{\,m}`),
        " の係数が ",
        math(String.raw`\Omega_L(m)`),
        " であること）は定義ではなく、下で証明する。",
      ]),
      paragraph([
        "記法について 2 点を約束する。第一に、",
        math(String.raw`Z_L`),
        " は多項式そのものを表し、",
        math(String.raw`x`),
        " は不定元であって数ではない。第二に、可換環 ",
        math(String.raw`R`),
        " と元 ",
        math(String.raw`r\in R`),
        " に対する代入（評価）の結果を ",
        math(String.raw`Z_L(r)\in R`),
        " と書く。すなわち丸括弧が付いたものだけが代入の結果であり、",
        math(String.raw`Z_L`),
        " と ",
        math(String.raw`Z_L(r)`),
        " は別の対象である。",
      ]),
      paragraph([
        "この定義では代入を行わない。物理の分配関数を得るには ",
        math(String.raw`x`),
        " へ ",
        math(String.raw`e^{-2\beta J}`),
        " を代入するが、その代入は実数体への脱出であり、脱出を宣言したブロックでのみ行う（README「形式変数のまま進む」）。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_claim_configuration_partition",
    kind: "claim",
    title: { text: "配位全体は破れボンド数の値ごとに類別される" },
    labels: ["claim_configuration_partition"],
    habitat: "N",
    lean: [
      "Ising2DLambda.PartitionPolynomial.biUnion_brokenFiber",
      "Ising2DLambda.PartitionPolynomial.brokenFiber_pairwise_disjoint",
      "Ising2DLambda.NecSuf.PartitionPolynomial.biUnion_fiber",
      "Ising2DLambda.NecSuf.PartitionPolynomial.fiber_pairwise_disjoint",
    ],
    statement: [
      paragraph([
        "各 ",
        math(String.raw`L\ge1`),
        " と各 ",
        math(String.raw`m\in\{0,1,\dots,2L^2\}`),
        " に対し、破れボンド数が ",
        math(String.raw`m`),
        " である配位の集合を",
      ]),
      displayMath(
        String.raw`A_m:=\bigl\{\,\sigma\in\Sigma_L \;\bigm|\; b(\sigma)=m\,\bigr\}`,
      ),
      paragraph([
        "と書く（",
        math(String.raw`\Sigma_L`),
        " は ",
        ref("def_configuration"),
        "、",
        math(String.raw`b(\sigma)`),
        " は ",
        ref("def_broken_bond_count"),
        "）。このとき次の 2 つが成り立つ。",
      ]),
      list([
        [
          "（被覆）",
          math(String.raw`\Sigma_L=\bigcup_{m=0}^{2L^2}A_m`),
          " である。",
        ],
        [
          "（互いに素）",
          math(String.raw`m,m'\in\{0,1,\dots,2L^2\}`),
          " が ",
          math(String.raw`m\ne m'`),
          " を満たすならば ",
          math(String.raw`A_m\cap A_{m'}=\varnothing`),
          " である。",
        ],
      ]),
      paragraph([
        "すなわち ",
        math(String.raw`\{A_m\}_{m=0}^{2L^2}`),
        " は ",
        math(String.raw`\Sigma_L`),
        " の互いに素な有限個の部分集合への分割である。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 1（被覆）。",
        math(String.raw`A_m`),
        " の定義より ",
        math(String.raw`A_m\subset\Sigma_L`),
        " なので、合併も ",
        math(String.raw`\Sigma_L`),
        " に含まれる。逆を示す。任意の ",
        math(String.raw`\sigma\in\Sigma_L`),
        " に対し、",
        ref("def_broken_bond_count"),
        " より ",
        math(String.raw`b(\sigma)\in\mathbb{N}`),
        " かつ ",
        math(String.raw`b(\sigma)\le 2L^2`),
        " である。そこで ",
        math(String.raw`m:=b(\sigma)`),
        " と置くと ",
        math(String.raw`m\in\{0,1,\dots,2L^2\}`),
        " であり、",
        math(String.raw`b(\sigma)=m`),
        " なので ",
        math(String.raw`\sigma\in A_m`),
        " である。よって ",
        math(String.raw`\sigma`),
        " は合併に属する。",
      ]),
      paragraph([
        "Step 2（互いに素）。",
        math(String.raw`m\ne m'`),
        " とし、",
        math(String.raw`\sigma\in A_m\cap A_{m'}`),
        " が存在したとする。",
        math(String.raw`A_m`),
        " の定義より ",
        math(String.raw`b(\sigma)=m`),
        "、",
        math(String.raw`A_{m'}`),
        " の定義より ",
        math(String.raw`b(\sigma)=m'`),
        " である。",
        ref("def_broken_bond_count"),
        " の ",
        math(String.raw`b`),
        " は写像であり、1 つの ",
        math(String.raw`\sigma`),
        " に対する値は 1 つなので ",
        math(String.raw`m=b(\sigma)=m'`),
        " となり、",
        math(String.raw`m\ne m'`),
        " に反する。したがってそのような ",
        math(String.raw`\sigma`),
        " は存在せず、",
        math(String.raw`A_m\cap A_{m'}=\varnothing`),
        " である。",
      ]),
      paragraph([
        "以上の 2 つは有限集合の包含関係と写像の一意性だけからなり、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_claim_coefficient_representation",
    kind: "claim",
    title: { text: "分配多項式の係数は多重度である" },
    labels: ["claim_coefficient_representation"],
    habitat: "Z",
    lean: [
      "Ising2DLambda.PartitionPolynomial.partitionPolynomial_eq_sum_multiplicity",
      "Ising2DLambda.PartitionPolynomial.partitionPolynomial_eq_sum_multiplicity_from_necSuf",
      "Ising2DLambda.NecSuf.PartitionPolynomial.sum_comp_eq_sum_nsmul",
    ],
    verification: ["sagemath/check/partition-polynomial-coefficient-representation"],
    statement: [
      paragraph([
        "各 ",
        math(String.raw`L\ge1`),
        " について、多項式環 ",
        math(String.raw`\mathbb{Z}[x]`),
        " の中で",
      ]),
      displayMath(String.raw`Z_L=\sum_{m=0}^{2L^2}\Omega_L(m)\,x^{\,m}`),
      paragraph([
        "が成り立つ（",
        math(String.raw`Z_L`),
        " は ",
        ref("def_partition_polynomial"),
        "、",
        math(String.raw`\Omega_L(m)`),
        " は ",
        ref("def_multiplicity"),
        "）。すなわち ",
        math(String.raw`\Omega_L(m)\in\mathbb{N}\subset\mathbb{Z}`),
        " は ",
        math(String.raw`Z_L`),
        " の ",
        math(String.raw`x^{\,m}`),
        " の係数である。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 1（多重度を類の元の個数として読む）。",
        ref("def_multiplicity"),
        " により、",
        math(String.raw`\Omega_L(m)`),
        " は ",
        ref("claim_configuration_partition"),
        " の集合 ",
        math(String.raw`A_m`),
        " の元の個数 ",
        math(String.raw`|A_m|`),
        " である。",
      ]),
      paragraph([
        "Step 2（類別）。",
        ref("claim_configuration_partition"),
        " により、",
        math(String.raw`\{A_m\}_{m=0}^{2L^2}`),
        " は ",
        math(String.raw`\Sigma_L`),
        " の互いに素な有限個の部分集合への分割である。",
      ]),
      paragraph([
        "Step 3（和を類ごとに束ねる）。互いに素な有限個の有限集合の合併の上を走る和は、",
        "各集合の上を走る和の総和に等しい。",
        ref("def_partition_polynomial"),
        " の定義の和にこれを適用して",
      ]),
      displayMath(
        String.raw`Z_L=\sum_{\sigma\in\Sigma_L}x^{\,b(\sigma)}
=\sum_{m=0}^{2L^2}\ \sum_{\sigma\in A_m}x^{\,b(\sigma)}`,
      ),
      paragraph(["を得る。"]),
      paragraph([
        "Step 4（1 つの類の中では単項式が共通）。",
        math(String.raw`m`),
        " を固定する。",
        ref("claim_configuration_partition"),
        " の ",
        math(String.raw`A_m`),
        " の定義より、",
        math(String.raw`\sigma\in A_m`),
        " ならば ",
        math(String.raw`b(\sigma)=m`),
        " である。したがって内側の和の各項は ",
        math(String.raw`x^{\,m}`),
        " に等しく、",
      ]),
      displayMath(
        String.raw`\sum_{\sigma\in A_m}x^{\,b(\sigma)}
=\sum_{\sigma\in A_m}x^{\,m}
=|A_m|\cdot x^{\,m}
=\Omega_L(m)\,x^{\,m}`,
      ),
      paragraph([
        "となる（2 つ目の等号は同じ元を ",
        math(String.raw`|A_m|`),
        " 個足したこと、3 つ目の等号は Step 1）。",
      ]),
      paragraph([
        "Step 5（結論）。Step 4 を Step 3 の右辺の各項へ代入して",
      ]),
      displayMath(String.raw`Z_L=\sum_{m=0}^{2L^2}\Omega_L(m)\,x^{\,m}`),
      paragraph(["を得る。"]),
      paragraph([
        "以上の各ステップは有限和の組み替えと数え上げだけからなり、",
        math(String.raw`x`),
        " への代入を行っていない。実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_claim_coefficient_sum",
    kind: "claim",
    title: { text: "多重度の総和は配位の総数に等しい" },
    labels: ["claim_coefficient_sum"],
    habitat: "N",
    lean: [
      "Ising2DLambda.PartitionPolynomial.multiplicity_sum_eq_two_pow",
      "Ising2DLambda.PartitionPolynomial.multiplicity_sum_eq_two_pow_from_necSuf",
      "Ising2DLambda.NecSuf.PartitionPolynomial.sum_card_fiber_eq_card",
    ],
    verification: ["sagemath/check/partition-polynomial-coefficient-sum"],
    statement: [
      paragraph([
        "各 ",
        math(String.raw`L\ge1`),
        " について",
      ]),
      displayMath(String.raw`\sum_{m=0}^{2L^2}\Omega_L(m)=2^{L^2}`),
      paragraph([
        "が成り立つ（",
        math(String.raw`\Omega_L(m)`),
        " は ",
        ref("def_multiplicity"),
        "）。両辺は ",
        math(String.raw`\mathbb{N}`),
        " の元である。",
      ]),
    ],
    proof: [
      paragraph([
        "Step 1（多重度を類の元の個数として読む）。",
        ref("def_multiplicity"),
        " により、",
        math(String.raw`\Omega_L(m)`),
        " は ",
        ref("claim_configuration_partition"),
        " の集合 ",
        math(String.raw`A_m`),
        " の元の個数 ",
        math(String.raw`|A_m|`),
        " である。",
      ]),
      paragraph([
        "Step 2（類別）。",
        ref("claim_configuration_partition"),
        " により、",
        math(String.raw`\{A_m\}_{m=0}^{2L^2}`),
        " は ",
        math(String.raw`\Sigma_L`),
        " の互いに素な有限個の部分集合への分割である。",
      ]),
      paragraph([
        "Step 3（有限集合の分割の元の個数）。互いに素な有限個の有限集合の合併の元の個数は、",
        "各集合の元の個数の和である。Step 2 の分割にこれを適用して",
      ]),
      displayMath(String.raw`|\Sigma_L|=\sum_{m=0}^{2L^2}|A_m|=\sum_{m=0}^{2L^2}\Omega_L(m)`),
      paragraph(["を得る（最後の等号は Step 1）。"]),
      paragraph([
        "Step 4（配位の総数）。",
        ref("def_configuration"),
        " により ",
        math(String.raw`|\Sigma_L|=2^{L^2}`),
        " である。",
      ]),
      paragraph([
        "Step 5（結論）。Step 3 の左辺へ Step 4 を代入して ",
        math(String.raw`\sum_{m=0}^{2L^2}\Omega_L(m)=2^{L^2}`),
        " を得る。",
      ]),
      paragraph([
        "以上の各ステップは有限集合の元の個数の計算だけからなり、実数体も複素数体も現れない。",
      ]),
    ],
  },

  {
    id: "partition_polynomial_remark_planned_chapters",
    kind: "remark",
    title: { text: "この先に置く章（未着手）" },
    labels: ["remark_planned_chapters"],
    habitat: "none",
    statement: [
      paragraph([
        "本文はここまでで、以下は未着手である。",
        "読む順序と各章が扱う量の住処は README の「章立ての予定」の表が正本である。",
      ]),
      list([
        [
          todo("未着手"),
          "「有限系の自由エントロピー」: 有理点 ",
          math(String.raw`q\in\mathbb{Q}_{>0}`),
          " での値の素因数分解として ",
          math(String.raw`\Phi_L=\log Z_L(q)\in\Lambda`),
          " を定める。",
        ],
        [
          todo("未着手"),
          "「転送行列」: ",
          math(String.raw`T(x)\in M_{2^L}\bigl(\mathbb{Z}[x]\bigr)`),
          " を作り ",
          math(String.raw`Z_L(x)=\operatorname{Tr}T(x)^L`),
          " を示す。",
        ],
        [
          todo("未着手"),
          "「固有値の代数性」: 特性多項式が ",
          math(String.raw`\mathbb{Z}[x][\lambda]`),
          " に属することから固有値の代数性を出し、円分体上で対角化する。",
        ],
        [
          todo("未着手"),
          "「Fisher 零点」: 零点が ",
          math(String.raw`\overline{\mathbb{Q}}`),
          " に属することと Kramers–Wannier 双対から、自己双対点 ",
          math(String.raw`x_c=\sqrt2-1`),
          " を出す。",
        ],
        [
          todo("未着手"),
          "「零点の詰め寄り」: 相転移を ",
          math(String.raw`\mathbb{Q}`),
          " 上の量化言明として書く。",
        ],
        [
          todo("未着手"),
          "「熱力学極限」: 自由エネルギー密度と零点密度を扱う。ここが実数体への脱出である。",
        ],
        [
          todo("未着手"),
          "「臨界指数を零点列で書く」: 先頭零点の列 ",
          math(String.raw`\{x_1(L)\}_L\subset\overline{\mathbb{Q}}`),
          " と有限サイズスケーリングを対応させる。",
        ],
      ]),
      paragraph([
        "各章を書くときは、",
        ref("def_partition_polynomial"),
        " の分配多項式を出発点に据え、",
        math(String.raw`x`),
        " への代入を伴う操作をすべて実数体への脱出として宣言すること。",
      ]),
    ],
  },
]);
